{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"s:So20SMIFormTitleItemTypea8rawValueABSS_tcfc","title":"init(rawValue:)","modules":[{"name":"SMIClientCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleitemtype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/init(rawValue:)","role":"symbol","url":"\/documentation\/smiclientcore\/formtitleitemtype\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType":{"title":"FormTitleItemType","abstract":[{"text":"An enum that defines ","type":"text"},{"code":"SMIFormTitleItemType","type":"codeVoice"},{"text":" types to decorate form fields or responses.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitemtype","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItemType"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItemType"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/title","value":"SMIFormTitleItemType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/fragments","value":[{"text":"SMIFormTitleItemType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/navigatorTitle","value":[{"text":"SMIFormTitleItemType","kind":"identifier"}]}]}]}