{"metadata":{"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIFormTitleItemTypeTitleItem","kind":"identifier"}],"extendedModule":"SMIClientCore","title":"titleItem","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTitleItemType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType"}],"externalID":"c:@SMIFormTitleItemTypeTitleItem"},"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleitemtype\/titleitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtitleitemtype\/titleitem"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/titleItem"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","text":"FormTitleItemType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Represents a set of strings comprised of a title (required) and optional decorators and subtitles.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType":{"url":"\/documentation\/smiclientcore\/formtitleitemtype","type":"topic","title":"FormTitleItemType","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItemType"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines "},{"code":"SMIFormTitleItemType","type":"codeVoice"},{"type":"text","text":" types to decorate form fields or responses."}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItemType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType/titleItem":{"abstract":[{"type":"text","text":"Represents a set of strings comprised of a title (required) and optional decorators and subtitles."}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormTitleItemTypeTitleItem"}],"url":"\/documentation\/smiclientcore\/formtitleitemtype\/titleitem","title":"titleItem","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormTitleItemType","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/titleItem","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormTitleItemTypeTitleItem","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItemTypeTitleItem"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormTitleItemTypeTitleItem"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/title","value":"SMIFormTitleItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItemType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItemType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType~1titleItem\/title","value":"SMIFormTitleItemTypeTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType~1titleItem\/fragments","value":[{"text":"SMIFormTitleItemTypeTitleItem","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}