{"kind":"symbol","metadata":{"title":"integerValue","externalID":"c:objc(pl)SMIFormResponseIntegerValue(py)integerValue","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"integerValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"integerValue"}],"required":true},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The integer value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the whole number entered by the user, stored as an "},{"type":"codeVoice","code":"NSInteger"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"integerValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue\/integerValue","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseintegervalue\/integervalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseintegervalue\/integervalue"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseIntegerValue/integerValue":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue\/integerValue","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/formresponseintegervalue\/integervalue","abstract":[{"type":"text","text":"The integer value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the whole number entered by the user, stored as an "},{"type":"codeVoice","code":"NSInteger"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"integerValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"integerValue"}],"title":"integerValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseIntegerValue":{"type":"topic","url":"\/documentation\/smiclientcore\/formresponseintegervalue","title":"FormResponseIntegerValue","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue","navigatorTitle":[{"kind":"identifier","text":"FormResponseIntegerValue"}],"abstract":[{"text":"A protocol that defines a form response value containing a whole number.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormResponseIntegerValue"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"integerValue","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"integerValue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"text":"integerValue","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue~1integerValue\/title","value":"integerValue"},{"value":[{"kind":"identifier","text":"integerValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue~1integerValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/title","value":"SMIFormResponseIntegerValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/fragments","value":[{"text":"SMIFormResponseIntegerValue","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseIntegerValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/navigatorTitle"}]}]}