{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/clientMenu","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientMenu"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu","preciseIdentifier":"c:objc(pl)SMIParticipantClientMenu","text":"ParticipantClientMenu"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/participant\/clientmenu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participant\/clientmenu"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu"]}],"abstract":[{"text":"The client menu associated with this participant.","type":"text"}],"metadata":{"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"clientMenu","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientMenu","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIParticipantClientMenu","text":"ParticipantClientMenu","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)SMIParticipant(py)clientMenu","required":true,"title":"clientMenu"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenu":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenu"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantClientMenu"}],"url":"\/documentation\/smiclientcore\/participantclientmenu","abstract":[{"type":"text","text":"A protocol that represents a menu of available actions for a participant."}],"role":"symbol","title":"ParticipantClientMenu"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/clientMenu":{"title":"clientMenu","required":true,"navigatorTitle":[{"text":"clientMenu","kind":"identifier"}],"abstract":[{"text":"The client menu associated with this participant.","type":"text"}],"url":"\/documentation\/smiclientcore\/participant\/clientmenu","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientMenu"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIParticipantClientMenu","text":"ParticipantClientMenu","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/clientMenu","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Participant","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/participant","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","title":"Participant","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"clientMenu","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"clientMenu"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIParticipantClientMenu","text":"id<SMIParticipantClientMenu>"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientMenu"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIParticipantClientMenu","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/title"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenu"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/fragments"},{"value":[{"text":"SMIParticipantClientMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/navigatorTitle"},{"value":"clientMenu","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1clientMenu\/title"},{"value":[{"text":"clientMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1clientMenu\/fragments"},{"value":"SMIParticipant","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title"},{"value":[{"kind":"identifier","text":"SMIParticipant"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments"},{"value":[{"text":"SMIParticipant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}