{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/supportedModalities"},"abstract":[{"text":"XXX: JWRIGHT DOCS","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/participant\/supportedmodalities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participant\/supportedmodalities"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"supportedModalities","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"supportedModalities","required":true,"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(pl)SMIParticipant(py)supportedModalities","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/supportedModalities":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/supportedModalities","url":"\/documentation\/smiclientcore\/participant\/supportedmodalities","abstract":[{"text":"XXX: JWRIGHT DOCS","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supportedModalities"}],"required":true,"title":"supportedModalities","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/participant","role":"symbol","navigatorTitle":[{"text":"Participant","kind":"identifier"}],"title":"Participant","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"supportedModalities","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"supportedModalities","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"supportedModalities","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1supportedModalities\/title"},{"op":"replace","value":[{"text":"supportedModalities","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1supportedModalities\/fragments"},{"op":"replace","value":"SMIParticipant","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title"},{"op":"replace","value":[{"text":"SMIParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments"},{"op":"replace","value":[{"text":"SMIParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}