{"abstract":[{"text":"Logging message associated with core API operations.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/loggingcategory\/api"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/loggingcategory\/api"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/API"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"SMILoggingCategoryAPI","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","title":"API","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"symbolKind":"property","externalID":"c:@SMILoggingCategoryAPI"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","title":"LoggingCategory","abstract":[{"type":"text","text":"Logging category information."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/API":{"navigatorTitle":[{"text":"SMILoggingCategoryAPI","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/loggingcategory\/api","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/API","kind":"symbol","abstract":[{"type":"text","text":"Logging message associated with core API operations."}],"title":"API","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMILoggingCategoryAPI"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMILoggingCategoryAPI","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","text":"SMILoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILoggingCategoryAPI","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title","op":"replace","value":"SMILoggingCategory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle","op":"replace","value":[{"text":"SMILoggingCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1API\/title","op":"replace","value":"SMILoggingCategoryAPI"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1API\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategoryAPI"}]}]}]}