{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"database"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","text":"LoggingCategory"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"database","roleHeading":"Type Property","externalID":"c:@SMILoggingCategoryDatabase","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"database","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"navigatorTitle":[{"text":"SMILoggingCategoryDatabase","kind":"identifier"}],"extendedModule":"SMIClientCore","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/loggingcategory\/database"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/loggingcategory\/database"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/database","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Logging message associated with local database operations.","type":"text"}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/database":{"url":"\/documentation\/smiclientcore\/loggingcategory\/database","title":"database","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/database","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"database"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryDatabase"}],"abstract":[{"type":"text","text":"Logging message associated with local database operations."}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","title":"LoggingCategory","abstract":[{"type":"text","text":"Logging category information."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMILoggingCategoryDatabase","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMILoggingCategoryDatabase","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","text":"SMILoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMILoggingCategoryDatabase"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMILoggingCategoryDatabase","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1database\/title"},{"value":[{"text":"SMILoggingCategoryDatabase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1database\/fragments"},{"value":"SMILoggingCategory","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title"},{"value":[{"kind":"identifier","text":"SMILoggingCategory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments"},{"value":[{"kind":"identifier","text":"SMILoggingCategory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle"}]}]}