{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/_SwiftNewtypeWrapper-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_SwiftNewtypeWrapper.hashValue"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/hashValue"},"variants":[{"paths":["\/documentation\/smiclientcore\/loggingcategory\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"hashValue","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE04hashE0Sivp::SYNTHESIZED::c:SMILoggingCategory.h@T@SMILoggingCategory","role":"symbol","extendedModule":"Swift","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore","relatedModules":["Swift"]}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"url":"\/documentation\/smiclientcore\/loggingcategory","abstract":[{"type":"text","text":"Logging category information."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"role":"symbol","kind":"symbol","type":"topic","title":"LoggingCategory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/hashValue":{"url":"\/documentation\/smiclientcore\/loggingcategory\/hashvalue","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/hashValue","type":"topic","role":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/_SwiftNewtypeWrapper-Implementations":{"title":"_SwiftNewtypeWrapper Implementations","role":"collectionGroup","url":"\/documentation\/smiclientcore\/loggingcategory\/_swiftnewtypewrapper-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/_SwiftNewtypeWrapper-Implementations","kind":"article"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SMILoggingCategory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle"}]}]}