{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"c:@SMILoggingCategoryMemory","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryMemory"}],"role":"symbol","extendedModule":"SMIClientCore","title":"memory"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/loggingcategory\/memory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/loggingcategory\/memory"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/memory","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Logging message associated with memory management.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"kind":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}],"title":"LoggingCategory","type":"topic","abstract":[{"text":"Logging category information.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"LoggingCategory","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/memory":{"title":"memory","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/memory","abstract":[{"text":"Logging message associated with memory management.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMILoggingCategoryMemory","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"type":"topic","url":"\/documentation\/smiclientcore\/loggingcategory\/memory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMILoggingCategoryMemory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMILoggingCategoryMemory","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","text":"SMILoggingCategory","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILoggingCategoryMemory","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title","value":"SMILoggingCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments","value":[{"kind":"identifier","text":"SMILoggingCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle","value":[{"text":"SMILoggingCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1memory\/title","value":"SMILoggingCategoryMemory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1memory\/fragments","value":[{"text":"SMILoggingCategoryMemory","kind":"identifier"}]}]}]}