{"variants":[{"paths":["\/documentation\/smiclientcore\/loggingcategory\/multimedia"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/loggingcategory\/multimedia"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/multimedia","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multimedia"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Logging message associated with voice activity."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"]]},"metadata":{"extendedModule":"SMIClientCore","title":"multimedia","externalID":"c:@SMILoggingCategoryMultimedia","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"multimedia"},{"kind":"text","text":": "},{"text":"LoggingCategory","kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"navigatorTitle":[{"text":"SMILoggingCategoryMultimedia","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/multimedia":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimedia","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"url":"\/documentation\/smiclientcore\/loggingcategory\/multimedia","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryMultimedia"}],"abstract":[{"type":"text","text":"Logging message associated with voice activity."}],"title":"multimedia","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/multimedia"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"type":"topic","url":"\/documentation\/smiclientcore\/loggingcategory","title":"LoggingCategory","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"abstract":[{"type":"text","text":"Logging category information."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMILoggingCategoryMultimedia"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMILoggingCategoryMultimedia","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILoggingCategoryMultimedia","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1multimedia\/title","op":"replace","value":"SMILoggingCategoryMultimedia"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1multimedia\/fragments","op":"replace","value":[{"text":"SMILoggingCategoryMultimedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title","op":"replace","value":"SMILoggingCategory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments","op":"replace","value":[{"text":"SMILoggingCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle","op":"replace","value":[{"text":"SMILoggingCategory","kind":"identifier"}]}]}]}