{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue\/displayvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue\/displayvalue"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(pl)SMIFormSingleInputValue(py)displayValue","title":"displayValue","role":"symbol","required":true,"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"displayValue"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/displayValue"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The display string that represents this value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains a human-readable string representation of the value, which can be","type":"text"},{"text":" ","type":"text"},{"text":"used for display purposes in the UI. This may be formatted differently from the actual","type":"text"},{"text":" ","type":"text"},{"text":"value stored in the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","isActive":true,"type":"reference"},{"text":" property.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FormSingleInputValue","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a form input value containing a single response value.","type":"text"}],"title":"FormSingleInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue/value":{"title":"value","required":true,"abstract":[{"type":"text","text":"The typed response value."},{"type":"text","text":" "},{"type":"text","text":"This property contains the actual response value stored in a type-safe format. The value"},{"type":"text","text":" "},{"type":"text","text":"is represented by a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"type":"text","text":" that provides access to the underlying data"},{"type":"text","text":" "},{"type":"text","text":"in its native type."}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue\/value","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIFormResponseValue","kind":"typeIdentifier","text":"FormResponseValue"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"title":"FormResponseValue","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}],"url":"\/documentation\/smiclientcore\/formresponsevalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue/displayValue":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue\/displayvalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"displayValue","kind":"identifier"}],"abstract":[{"text":"The display string that represents this value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains a human-readable string representation of the value, which can be","type":"text"},{"text":" ","type":"text"},{"text":"used for display purposes in the UI. This may be formatted differently from the actual","type":"text"},{"text":" ","type":"text"},{"text":"value stored in the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","isActive":true},{"text":" property.","type":"text"}],"title":"displayValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/displayValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displayValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"displayValue","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"displayValue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/title","value":"SMIFormSingleInputValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/fragments","value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/navigatorTitle","value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","value":"SMIFormResponseValue"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle"},{"value":"displayValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1displayValue\/title"},{"value":[{"text":"displayValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1displayValue\/fragments"}]}]}