{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormResponseValue","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue\/value"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"anchor":"Related-Documentation"}],"abstract":[{"type":"text","text":"The typed response value."},{"type":"text","text":" "},{"type":"text","text":"This property contains the actual response value stored in a type-safe format. The value"},{"type":"text","text":" "},{"type":"text","text":"is represented by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"type":"text","text":" that provides access to the underlying data"},{"type":"text","text":" "},{"type":"text","text":"in its native type."}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormSingleInputValue(py)value","symbolKind":"property","title":"value","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormResponseValue","text":"FormResponseValue","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue/value":{"required":true,"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormResponseValue","text":"FormResponseValue","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue\/value","title":"value","abstract":[{"text":"The typed response value.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property contains the actual response value stored in a type-safe format. The value"},{"type":"text","text":" "},{"type":"text","text":"is represented by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"type":"text","text":" that provides access to the underlying data"},{"type":"text","text":" "},{"type":"text","text":"in its native type."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue":{"title":"FormSingleInputValue","navigatorTitle":[{"text":"FormSingleInputValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue","abstract":[{"text":"A protocol that represents a form input value containing a single response value.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputValue","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseValue"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}],"title":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"url":"\/documentation\/smiclientcore\/formresponsevalue","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"value"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"anchor":"Related-Documentation","title":"Related Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)SMIFormResponseValue","kind":"typeIdentifier","text":"id<SMIFormResponseValue>"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/title","op":"replace","value":"value"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/fragments"},{"value":"SMIFormSingleInputValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/title"},{"value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/fragments"},{"value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/navigatorTitle"},{"value":"SMIFormResponseValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}