{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/interactionItems","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/titlelinkitem\/interactionitems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/titlelinkitem\/interactionitems"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem"]]},"abstract":[{"text":"The array of interaction options available for this item.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","type":"reference","isActive":true},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option that users can interact with.","type":"text"}],"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"interactionItems"}],"role":"symbol","required":true,"roleHeading":"Instance Property","title":"interactionItems","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice"},{"kind":"text","text":"]"}],"externalID":"c:objc(pl)SMITitleLinkItem(py)interactionItems"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem/interactionItems":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/interactionItems","role":"symbol","kind":"symbol","abstract":[{"text":"The array of interaction options available for this item.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","type":"reference","isActive":true},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option that users can interact with.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"interactionItems"}],"title":"interactionItems","url":"\/documentation\/smiclientcore\/titlelinkitem\/interactionitems"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleLinkItem"}],"navigatorTitle":[{"kind":"identifier","text":"TitleLinkItem"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","title":"TitleLinkItem","abstract":[{"text":"A protocol that represents an interactive item in a carousel with a title and selectable options.","type":"text"}],"url":"\/documentation\/smiclientcore\/titlelinkitem","type":"topic","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"url":"\/documentation\/smiclientcore\/choice","navigatorTitle":[{"kind":"identifier","text":"Choice"}],"title":"Choice","type":"topic","abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Choice"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"interactionItems","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"interactionItems"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIChoice>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"interactionItems","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1interactionItems\/title","op":"replace","value":"interactionItems"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1interactionItems\/fragments","op":"replace","value":[{"kind":"identifier","text":"interactionItems"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/title","op":"replace","value":"SMITitleLinkItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/fragments","op":"replace","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/navigatorTitle","op":"replace","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title","op":"replace","value":"SMIChoice"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments","op":"replace","value":[{"text":"SMIChoice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChoice"}]}]}]}