{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The title information for this item."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the text and presentation details of the item’s title"},{"type":"text","text":" "},{"type":"text","text":"through the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","type":"reference","isActive":true},{"type":"text","text":" protocol."}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/titleItem","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/titlelinkitem\/titleitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/titlelinkitem\/titleitem"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"titleItem"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleItem"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"}],"required":true,"role":"symbol","externalID":"c:objc(pl)SMITitleLinkItem(py)titleItem","symbolKind":"property","roleHeading":"Instance Property","title":"titleItem"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleLinkItem"}],"navigatorTitle":[{"kind":"identifier","text":"TitleLinkItem"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","title":"TitleLinkItem","abstract":[{"text":"A protocol that represents an interactive item in a carousel with a title and selectable options.","type":"text"}],"url":"\/documentation\/smiclientcore\/titlelinkitem","type":"topic","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem/titleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/titleItem","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"}],"role":"symbol","kind":"symbol","title":"titleItem","navigatorTitle":[{"text":"titleItem","kind":"identifier"}],"required":true,"abstract":[{"text":"The title information for this item.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the text and presentation details of the item’s title","type":"text"},{"text":" ","type":"text"},{"text":"through the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","isActive":true,"type":"reference"},{"text":" protocol.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/titlelinkitem\/titleitem"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","title":"FormTitleItem","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"titleItem"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"titleItem"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFormTitleItem>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/title","op":"replace","value":"SMITitleLinkItem"},{"value":[{"text":"SMITitleLinkItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/fragments"},{"value":[{"kind":"identifier","text":"SMITitleLinkItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/navigatorTitle"},{"value":"titleItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1titleItem\/title"},{"value":[{"kind":"identifier","text":"titleItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1titleItem\/fragments"},{"value":"SMIFormTitleItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"}]}]}