{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/closed","interfaceLanguage":"swift"},"metadata":{"title":"ConversationStatus.closed","externalID":"c:@E@SMIConversationStatus@SMIConversationStatusClosed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"navigatorTitle":[{"text":"SMIConversationStatusClosed","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"SMIClientCore"}],"roleHeading":"Case"},"sections":[],"abstract":[{"text":"Conversation has closed.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the conversation has been terminated and cannot receive new messages.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationstatus\/closed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationstatus\/closed"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationStatus","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible states of a conversation.","type":"text"}],"navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationstatus","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus","title":"ConversationStatus"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/closed":{"abstract":[{"text":"Conversation has closed.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the conversation has been terminated and cannot receive new messages.","type":"text"}],"navigatorTitle":[{"text":"SMIConversationStatusClosed","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/closed","title":"ConversationStatus.closed","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationstatus\/closed"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationStatusClosed"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIConversationStatusClosed","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIConversationStatusClosed"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/title","op":"replace","value":"SMIConversationStatus"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationStatus"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1closed\/title","op":"replace","value":"SMIConversationStatusClosed"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1closed\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationStatusClosed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}