{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:So21SMIConversationStatusV8rawValueABSgSu_tcfc","title":"init(rawValue:)","roleHeading":"Initializer","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/init(rawValue:)"},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationstatus\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationstatus\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/init(rawValue:)","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus":{"title":"ConversationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus","abstract":[{"text":"An enum that defines the possible states of a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationstatus","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/title","op":"replace","value":"SMIConversationStatus"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationStatus"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}