{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationstatus\/open"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationstatus\/open"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"SMIConversationStatusOpen","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@SMIConversationStatus@SMIConversationStatusOpen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"}],"modules":[{"name":"SMIClientCore"}],"title":"ConversationStatus.open"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/open","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Conversation is still open."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the conversation is active and can receive messages."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus":{"title":"ConversationStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a conversation."}],"url":"\/documentation\/smiclientcore\/conversationstatus","role":"symbol","navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationStatus","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/open":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/open","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SMIConversationStatusOpen","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationstatus\/open","title":"ConversationStatus.open","abstract":[{"type":"text","text":"Conversation is still open."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the conversation is active and can receive messages."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIConversationStatusOpen","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIConversationStatusOpen"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SMIConversationStatusOpen"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/title","value":"SMIConversationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/fragments","value":[{"text":"SMIConversationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationStatus"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1open\/title","op":"replace","value":"SMIConversationStatusOpen"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1open\/fragments","op":"replace","value":[{"text":"SMIConversationStatusOpen","kind":"identifier"}]}]}]}