{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/integervalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/integervalue"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/integerValue"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@SMIFormResponseValueTypeIntegerValue","title":"integerValue","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"integerValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType"}],"roleHeading":"Type Property","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIFormResponseValueTypeIntegerValue","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"abstract":[{"text":"An integer response.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"integerValue"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","kind":"typeIdentifier","text":"FormResponseValueType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/integerValue":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"integerValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/integerValue","navigatorTitle":[{"text":"SMIFormResponseValueTypeIntegerValue","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An integer response."}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/integervalue","title":"integerValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType":{"role":"symbol","title":"FormResponseValueType","abstract":[{"type":"text","text":"An enum that defines the types of values that can be submitted in a form response."}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValueType","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FormResponseValueType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormResponseValueTypeIntegerValue","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueTypeIntegerValue"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFormResponseValueTypeIntegerValue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1integerValue\/title","value":"SMIFormResponseValueTypeIntegerValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1integerValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueTypeIntegerValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/title","value":"SMIFormResponseValueType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace"}]}]}