{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/textValue"},"metadata":{"externalID":"c:@SMIFormResponseValueTypeTextValue","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType"}],"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"title":"textValue","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseValueTypeTextValue"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"]]},"abstract":[{"type":"text","text":"A text response."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/textvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/textvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/textValue":{"abstract":[{"text":"A text response.","type":"text"}],"navigatorTitle":[{"text":"SMIFormResponseValueTypeTextValue","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType"}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/textvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/textValue","title":"textValue","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType":{"role":"symbol","title":"FormResponseValueType","abstract":[{"type":"text","text":"An enum that defines the types of values that can be submitted in a form response."}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValueType","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FormResponseValueType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormResponseValueTypeTextValue","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormResponseValueTypeTextValue"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormResponseValueTypeTextValue"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormResponseValueTypeTextValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1textValue\/title"},{"value":[{"text":"SMIFormResponseValueTypeTextValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1textValue\/fragments"},{"value":"SMIFormResponseValueType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/title"},{"value":[{"text":"SMIFormResponseValueType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/fragments"},{"value":[{"text":"SMIFormResponseValueType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}