{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlValue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","kind":"typeIdentifier","text":"FormResponseValueType"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@SMIFormResponseValueTypeURLValue","modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"urlValue","extendedModule":"SMIClientCore","symbolKind":"property","navigatorTitle":[{"text":"SMIFormResponseValueTypeURLValue","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"abstract":[{"type":"text","text":"A URL response."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/urlvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsevaluetype\/urlvalue"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/urlValue","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType":{"title":"FormResponseValueType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseValueType"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","url":"\/documentation\/smiclientcore\/formresponsevaluetype","abstract":[{"text":"An enum that defines the types of values that can be submitted in a form response.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseValueType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/urlValue":{"type":"topic","navigatorTitle":[{"text":"SMIFormResponseValueTypeURLValue","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType"}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/urlvalue","abstract":[{"text":"A URL response.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/urlValue","title":"urlValue","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormResponseValueTypeURLValue","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseValueTypeURLValue","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"SMIFormResponseValueType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseValueTypeURLValue","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/title","value":"SMIFormResponseValueType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1urlValue\/title","value":"SMIFormResponseValueTypeURLValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1urlValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueTypeURLValue"}],"op":"replace"}]}]}