{"sections":[],"kind":"symbol","abstract":[{"text":"A list of selectable options for this input.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property contains the available options that can be selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","isActive":true},{"type":"text","text":" that includes a title and identifier."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionItems"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"required":true,"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"optionItems","symbolKind":"property","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormOptionPickerInput(py)optionItems"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/optionItems":{"title":"optionItems","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"abstract":[{"text":"A list of selectable options for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the available options that can be selected in the picker.","type":"text"},{"text":" ","type":"text"},{"text":"Each option is represented by a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference","isActive":true},{"text":" that includes a title and identifier.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput":{"type":"topic","role":"symbol","title":"FormOptionPickerInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormOptionPickerInput"}],"abstract":[{"type":"text","text":"A protocol that represents a single-selection option picker input field in a form."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","kind":"symbol","url":"\/documentation\/smiclientcore\/formoptionpickerinput","navigatorTitle":[{"kind":"identifier","text":"FormOptionPickerInput"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"kind":"symbol","title":"FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"optionItems","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"optionItems","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIFormTitleOptionItem>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/title","value":"optionItems"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/fragments","value":[{"kind":"identifier","text":"optionItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/title","value":"SMIFormOptionPickerInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/fragments","value":[{"kind":"identifier","text":"SMIFormOptionPickerInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/navigatorTitle","value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","value":"SMIFormTitleOptionItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}