{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIFormOptionPickerInput(py)selectedOptionIndex","symbolKind":"property","title":"selectedOptionIndex","navigatorTitle":[{"kind":"identifier","text":"selectedOptionIndex"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptionIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/selectedoptionindex"]},{"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/selectedoptionindex"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The currently selected index in the options list."},{"type":"text","text":" "},{"type":"text","text":"This property indicates which option is currently selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"The index corresponds to the position of the selected option in the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","isActive":true,"type":"reference"},{"type":"text","text":" array."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedOptionIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/selectedOptionIndex","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/optionItems":{"url":"\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","abstract":[{"type":"text","text":"A list of selectable options for this input."},{"text":" ","type":"text"},{"type":"text","text":"This property contains the available options that can be selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference","isActive":true},{"type":"text","text":" that includes a title and identifier."}],"role":"symbol","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"text":"]","kind":"text"}],"required":true,"type":"topic","title":"optionItems"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput":{"type":"topic","url":"\/documentation\/smiclientcore\/formoptionpickerinput","title":"FormOptionPickerInput","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","navigatorTitle":[{"text":"FormOptionPickerInput","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a single-selection option picker input field in a form.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FormOptionPickerInput","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputoptionitem","title":"FormInputOptionItem","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputOptionItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/selectedOptionIndex":{"url":"\/documentation\/smiclientcore\/formoptionpickerinput\/selectedoptionindex","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/selectedOptionIndex","abstract":[{"type":"text","text":"The currently selected index in the options list."},{"text":" ","type":"text"},{"text":"This property indicates which option is currently selected in the picker.","type":"text"},{"text":" ","type":"text"},{"text":"The index corresponds to the position of the selected option in the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","type":"reference","isActive":true},{"text":" array.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedOptionIndex"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedOptionIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"required":true,"type":"topic","title":"selectedOptionIndex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"selectedOptionIndex","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"selectedOptionIndex"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"selectedOptionIndex","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"optionItems","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/title"},{"value":[{"text":"optionItems","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/fragments"},{"value":"SMIFormOptionPickerInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormOptionPickerInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/fragments"},{"value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/navigatorTitle"},{"value":"SMIFormTitleOptionItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle"},{"value":"selectedOptionIndex","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1selectedOptionIndex\/title"},{"value":[{"text":"selectedOptionIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1selectedOptionIndex\/fragments"}]}]}