{"abstract":[{"text":"The currently selected option for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property holds the currently selected option item. It can be read to get the current","type":"text"},{"text":" ","type":"text"},{"text":"selection and written to programmatically set a new selection. The value must be one of","type":"text"},{"text":" ","type":"text"},{"text":"the options in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems"},{"text":" array.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormInputOptionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"text":")?","kind":"text"}],"title":"value","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormOptionPickerInput(py)value"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/value"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","kind":"typeIdentifier","text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput\/value"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/value":{"type":"topic","required":true,"navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormInputOptionItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/value","title":"value","abstract":[{"type":"text","text":"The currently selected option for this input."},{"type":"text","text":" "},{"type":"text","text":"This property holds the currently selected option item. It can be read to get the current"},{"type":"text","text":" "},{"type":"text","text":"selection and written to programmatically set a new selection. The value must be one of"},{"type":"text","text":" "},{"type":"text","text":"the options in the "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","type":"reference"},{"type":"text","text":" array."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formoptionpickerinput\/value"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/optionItems":{"url":"\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A list of selectable options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property contains the available options that can be selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"},{"type":"text","text":" that includes a title and identifier."}],"title":"optionItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","required":true,"navigatorTitle":[{"kind":"identifier","text":"optionItems"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","navigatorTitle":[{"kind":"identifier","text":"FormOptionPickerInput"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormOptionPickerInput"}],"title":"FormOptionPickerInput","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formoptionpickerinput","abstract":[{"text":"A protocol that represents a single-selection option picker input field in a form.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"title":"FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"value"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFormTitleOptionItem>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleOptionItem"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1value\/title","op":"replace","value":"value"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1value\/fragments"},{"value":"optionItems","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/title"},{"value":[{"kind":"identifier","text":"optionItems"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/fragments"},{"value":"SMIFormOptionPickerInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/title"},{"value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormOptionPickerInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","op":"replace","value":"SMIFormTitleOptionItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","op":"replace","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}]}]}]}