{"abstract":[{"text":"The Pending Service Routing Id.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/queueposition\/pendingserviceroutingid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/queueposition\/pendingserviceroutingid"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition\/pendingServiceRoutingId","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingServiceRoutingId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"pendingServiceRoutingId"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","externalID":"c:objc(pl)SMIQueuePosition(py)pendingServiceRoutingId","required":true,"title":"pendingServiceRoutingId"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingServiceRoutingId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueuePosition/pendingServiceRoutingId":{"abstract":[{"text":"The Pending Service Routing Id.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"pendingServiceRoutingId","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition\/pendingServiceRoutingId","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/queueposition\/pendingserviceroutingid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pendingServiceRoutingId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"pendingServiceRoutingId"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueuePosition":{"kind":"symbol","url":"\/documentation\/smiclientcore\/queueposition","title":"QueuePosition","abstract":[{"type":"text","text":"Represents a queue position event within an "},{"type":"codeVoice","code":"SMIConversationEntry"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"QueuePosition","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueuePosition","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"pendingServiceRoutingId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"pendingServiceRoutingId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pendingServiceRoutingId"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition~1pendingServiceRoutingId\/title","op":"replace","value":"pendingServiceRoutingId"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition~1pendingServiceRoutingId\/fragments","op":"replace","value":[{"kind":"identifier","text":"pendingServiceRoutingId"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/title","op":"replace","value":"SMIQueuePosition"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueuePosition"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/navigatorTitle","op":"replace","value":[{"text":"SMIQueuePosition","kind":"identifier"}]}]}]}