{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"]]},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/!=(_:_:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/querybehaviour\/equatable-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/Equatable-Implementations"},"metadata":{"title":"Equatable Implementations","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/!=(_:_:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/!=(_:_:)","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/querybehaviour\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"!=(_:_:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"abstract":[{"type":"text","text":"The offline and network behaviour of an entry query."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}],"navigatorTitle":[{"text":"QueryBehaviour","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour","type":"topic","url":"\/documentation\/smiclientcore\/querybehaviour","title":"QueryBehaviour"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title","op":"replace","value":"SMIQueryBehaviour"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments","op":"replace","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]}]}]}