{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/querybehaviour\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"s:So17SMIQueryBehaviourV8rawValueABSgSu_tcfc","symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"modules":[{"name":"SMIClientCore"}],"title":"init(rawValue:)"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/init(rawValue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/smiclientcore\/querybehaviour\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/querybehaviour","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"QueryBehaviour","kind":"identifier"}],"title":"QueryBehaviour","abstract":[{"text":"The offline and network behaviour of an entry query.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title","value":"SMIQueryBehaviour"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]}]}]}