{"abstract":[{"type":"text","text":"Will return locally cached entities immediately within the completion of the query."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localOnly","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@SMIQueryBehaviour@SMIQueryBehaviourLocalOnly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localOnly","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourLocalOnly"}],"symbolKind":"case","role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Case","title":"QueryBehaviour.localOnly"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localOnly","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This is a purely offline operation and will not result in any network calls.","type":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/querybehaviour\/localonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/querybehaviour\/localonly"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"url":"\/documentation\/smiclientcore\/querybehaviour","navigatorTitle":[{"kind":"identifier","text":"QueryBehaviour"}],"title":"QueryBehaviour","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueryBehaviour"}],"abstract":[{"type":"text","text":"The offline and network behaviour of an entry query."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/localOnly":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localOnly"}],"navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourLocalOnly"}],"abstract":[{"type":"text","text":"Will return locally cached entities immediately within the completion of the query."}],"title":"QueryBehaviour.localOnly","kind":"symbol","url":"\/documentation\/smiclientcore\/querybehaviour\/localonly","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localOnly","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIQueryBehaviourLocalOnly"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviourLocalOnly"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMIQueryBehaviourLocalOnly","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title","op":"replace","value":"SMIQueryBehaviour"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localOnly\/title","op":"replace","value":"SMIQueryBehaviourLocalOnly"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localOnly\/fragments","op":"replace","value":[{"text":"SMIQueryBehaviourLocalOnly","kind":"identifier"}]}]}]}