{"sections":[],"abstract":[{"type":"text","text":"Will return locally cached entities immediately within the completion of the query."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"localWithNetwork","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Additional entities may be resolved with a network check, if this results in any net-new entities being found."},{"text":" ","type":"text"},{"text":"They will be emittied with a delegate event.","type":"text"},{"text":" ","type":"text"},{"text":"This is useful if you want to immediately return the local cache without having to wait for a network operation.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/querybehaviour\/localwithnetwork"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/querybehaviour\/localwithnetwork"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"localWithNetwork","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourLocalWithNetwork"}],"role":"symbol","externalID":"c:@E@SMIQueryBehaviour@SMIQueryBehaviourLocalWithNetwork","modules":[{"name":"SMIClientCore"}],"title":"QueryBehaviour.localWithNetwork","symbolKind":"case","roleHeading":"Case"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/localWithNetwork":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","role":"symbol","url":"\/documentation\/smiclientcore\/querybehaviour\/localwithnetwork","abstract":[{"text":"Will return locally cached entities immediately within the completion of the query.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localWithNetwork","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SMIQueryBehaviourLocalWithNetwork","kind":"identifier"}],"title":"QueryBehaviour.localWithNetwork"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour","title":"QueryBehaviour","navigatorTitle":[{"text":"QueryBehaviour","kind":"identifier"}],"abstract":[{"text":"The offline and network behaviour of an entry query.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/querybehaviour","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SMIQueryBehaviourLocalWithNetwork"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIQueryBehaviourLocalWithNetwork","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIQueryBehaviourLocalWithNetwork"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/title","value":"SMIQueryBehaviourLocalWithNetwork"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviourLocalWithNetwork"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title","value":"SMIQueryBehaviour"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]},{"op":"replace","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle"}]}]}