{"abstract":[{"type":"text","text":"Similar to "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","isActive":true},{"type":"text","text":" this will return locally cached entities as well as attempt to resolve any"},{"type":"text","text":" "},{"type":"text","text":"missing entities and update the local cache."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForNetwork"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The primary difference is that the completion will wait for the result of the network check and return all entities at a single time.","type":"text"}]},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"Any newly cached entries will still be emitted via a delegate event."}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/querybehaviour\/waitfornetwork"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/querybehaviour\/waitfornetwork"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/waitForNetwork"},"metadata":{"externalID":"c:@E@SMIQueryBehaviour@SMIQueryBehaviourWaitForNetwork","title":"QueryBehaviour.waitForNetwork","symbolKind":"case","navigatorTitle":[{"text":"SMIQueryBehaviourWaitForNetwork","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForNetwork","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/waitForNetwork":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForNetwork"}],"url":"\/documentation\/smiclientcore\/querybehaviour\/waitfornetwork","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/waitForNetwork","kind":"symbol","abstract":[{"type":"text","text":"Similar to "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","isActive":true,"type":"reference"},{"type":"text","text":" this will return locally cached entities as well as attempt to resolve any"},{"type":"text","text":" "},{"type":"text","text":"missing entities and update the local cache."}],"title":"QueryBehaviour.waitForNetwork","navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourWaitForNetwork"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/localWithNetwork":{"title":"QueryBehaviour.localWithNetwork","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","abstract":[{"type":"text","text":"Will return locally cached entities immediately within the completion of the query."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localWithNetwork"}],"navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourLocalWithNetwork"}],"url":"\/documentation\/smiclientcore\/querybehaviour\/localwithnetwork","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"url":"\/documentation\/smiclientcore\/querybehaviour","navigatorTitle":[{"kind":"identifier","text":"QueryBehaviour"}],"title":"QueryBehaviour","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueryBehaviour"}],"abstract":[{"type":"text","text":"The offline and network behaviour of an entry query."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIQueryBehaviourWaitForNetwork"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIQueryBehaviourWaitForNetwork","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SMIQueryBehaviourWaitForNetwork"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1waitForNetwork\/title","op":"replace","value":"SMIQueryBehaviourWaitForNetwork"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1waitForNetwork\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviourWaitForNetwork"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/title","op":"replace","value":"SMIQueryBehaviourLocalWithNetwork"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/fragments","op":"replace","value":[{"text":"SMIQueryBehaviourLocalWithNetwork","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title","op":"replace","value":"SMIQueryBehaviour"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIQueryBehaviour"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle","op":"replace","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}]}]}]}