{"metadata":{"symbolKind":"property","modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localParticipant","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaParticipant","kind":"typeIdentifier","preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC"},{"text":"?","kind":"text"}],"externalID":"s:19SMIMultimediaCommon17MultimediaSessionC16localParticipantAA0cF0CSgvp","title":"localParticipant","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:7Combine9PublishedV","text":"Published","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localParticipant","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant","preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC","text":"MultimediaParticipant","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediasession\/localparticipant"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/localParticipant","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession"]]},"abstract":[{"text":"The local participant in the session, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if unavailable."}],"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession":{"url":"\/documentation\/smimultimediacommon\/multimediasession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MultimediaSession","navigatorTitle":[{"kind":"identifier","text":"MultimediaSession"}],"abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservableObject"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference","isActive":true},{"text":" that publishes session state changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipant":{"role":"symbol","type":"topic","title":"MultimediaParticipant","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipant","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaParticipant","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaparticipant","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservableObject"},{"type":"text","text":" wrapper around "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"},{"type":"text","text":" that publishes participant state for use in SwiftUI views."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession/localParticipant":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localParticipant","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC","text":"MultimediaParticipant","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/localParticipant","abstract":[{"type":"text","text":"The local participant in the session, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if unavailable."}],"title":"localParticipant","url":"\/documentation\/smimultimediacommon\/multimediasession\/localparticipant"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"SMIMultimediaSession","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","op":"replace"},{"value":"SMIMultimediaParticipant","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}