{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:7Combine9PublishedV","text":"Published","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteParticipants","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant","text":"MultimediaParticipant","preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediasession\/remoteparticipants"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteParticipants","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MultimediaParticipant","kind":"typeIdentifier","preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC"},{"text":"]","kind":"text"}],"externalID":"s:19SMIMultimediaCommon17MultimediaSessionC18remoteParticipantsSayAA0C11ParticipantCGvp","symbolKind":"property","modules":[{"name":"SMIMultimediaCommon"}],"title":"remoteParticipants","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/remoteParticipants","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The remote participants currently in the session."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession":{"url":"\/documentation\/smimultimediacommon\/multimediasession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MultimediaSession","navigatorTitle":[{"kind":"identifier","text":"MultimediaSession"}],"abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservableObject"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference","isActive":true},{"text":" that publishes session state changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession/remoteParticipants":{"url":"\/documentation\/smimultimediacommon\/multimediasession\/remoteparticipants","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteParticipants","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MultimediaParticipant","kind":"typeIdentifier","preciseIdentifier":"s:19SMIMultimediaCommon21MultimediaParticipantC"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/remoteParticipants","abstract":[{"text":"The remote participants currently in the session.","type":"text"}],"title":"remoteParticipants","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipant":{"role":"symbol","type":"topic","title":"MultimediaParticipant","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipant","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaParticipant","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaparticipant","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservableObject"},{"type":"text","text":" wrapper around "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"},{"type":"text","text":" that publishes participant state for use in SwiftUI views."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","value":"SMIMultimediaParticipant"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","value":"SMIMultimediaSession","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}