{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession"]]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/session(_:didUpdateMicrophone:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"s:19SMIMultimediaCommon17MultimediaSessionC7session_19didUpdateMicrophoneyAA0cD8Protocol_p_SbtF","modules":[{"name":"SMIMultimediaCommon"}],"title":"session(_:didUpdateMicrophone:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateMicrophone","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"SMIMultimediaCommon","role":"symbol"},"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediasession\/session(_:didupdatemicrophone:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MultimediaSessionProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMicrophone"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"session","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true},{"type":"text","text":" instance that triggered the event."}]}]},{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the microphone is now enabled."}]}]}]}],"abstract":[{"text":"Delegate event that is triggered when the local participant’s microphone state changes.","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession/session(_:didUpdateMicrophone:)":{"role":"symbol","type":"topic","title":"session(_:didUpdateMicrophone:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/session(_:didUpdateMicrophone:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MultimediaSessionProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateMicrophone"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/smimultimediacommon\/multimediasession\/session(_:didupdatemicrophone:)","abstract":[{"text":"Delegate event that is triggered when the local participant’s microphone state changes.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession":{"url":"\/documentation\/smimultimediacommon\/multimediasession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MultimediaSession","navigatorTitle":[{"kind":"identifier","text":"MultimediaSession"}],"abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservableObject"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference","isActive":true},{"text":" that publishes session state changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","op":"replace","value":"SMIMultimediaSession"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","op":"replace","value":[{"text":"SMIMultimediaSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMIMultimediaSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}