{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol"},{"text":", ","kind":"text"},{"text":"didUpdateRemoteParticipants","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"participants","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant","text":"MultimediaParticipantProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol"},{"type":"text","text":" instance that triggered the event."}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The updated list of remote "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"},{"type":"text","text":" instances."}]}],"name":"participants"}]}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediasession\/session(_:didupdateremoteparticipants:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSessionProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"text":", ","kind":"text"},{"text":"didUpdateRemoteParticipants","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant"},{"text":"])","kind":"text"}],"externalID":"s:19SMIMultimediaCommon17MultimediaSessionC7session_27didUpdateRemoteParticipantsyAA0cD8Protocol_p_SayAA0c11ParticipantJ0_pGtF","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"method","title":"session(_:didUpdateRemoteParticipants:)","extendedModule":"SMIMultimediaCommon","role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/session(_:didUpdateRemoteParticipants:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Delegate event that is triggered when the list of remote participants changes."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession/session(_:didUpdateRemoteParticipants:)":{"url":"\/documentation\/smimultimediacommon\/multimediasession\/session(_:didupdateremoteparticipants:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MultimediaSessionProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateRemoteParticipants"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant","text":"MultimediaParticipantProtocol","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession\/session(_:didUpdateRemoteParticipants:)","abstract":[{"type":"text","text":"Delegate event that is triggered when the list of remote participants changes."}],"title":"session(_:didUpdateRemoteParticipants:)","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession":{"url":"\/documentation\/smimultimediacommon\/multimediasession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MultimediaSession","navigatorTitle":[{"kind":"identifier","text":"MultimediaSession"}],"abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservableObject"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference","isActive":true},{"text":" that publishes session state changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","value":"SMIMultimediaParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","value":"SMIMultimediaSession"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}