{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingtypes\/equatable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes"]]},"kind":"article","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection","title":"Equatable Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/routingtypes\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes":{"url":"\/documentation\/smiclientcore\/routingtypes","kind":"symbol","type":"topic","abstract":[{"text":"An enum that defines the possible types of routing operations that can occur in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","role":"symbol","navigatorTitle":[{"text":"RoutingTypes","kind":"identifier"}],"title":"RoutingTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingTypes","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/title","op":"replace","value":"SMIRoutingTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/fragments","op":"replace","value":[{"text":"SMIRoutingTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIRoutingTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}