{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initial","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/initial","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes"]]},"abstract":[{"text":"Indicates the action of initializing a new routing operation.","type":"text"}],"metadata":{"symbolKind":"property","externalID":"c:@SMIRoutingTypesInitial","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initial","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","text":"RoutingTypes","kind":"typeIdentifier"}],"title":"initial","navigatorTitle":[{"text":"SMIRoutingTypesInitial","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingtypes\/initial"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/routingtypes\/initial"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/initial":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/initial","role":"symbol","navigatorTitle":[{"text":"SMIRoutingTypesInitial","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/routingtypes\/initial","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initial","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","text":"RoutingTypes","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Indicates the action of initializing a new routing operation."}],"title":"initial","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes":{"url":"\/documentation\/smiclientcore\/routingtypes","kind":"symbol","type":"topic","abstract":[{"text":"An enum that defines the possible types of routing operations that can occur in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","role":"symbol","navigatorTitle":[{"text":"RoutingTypes","kind":"identifier"}],"title":"RoutingTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingTypes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIRoutingTypesInitial","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIRoutingTypesInitial","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRoutingTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRoutingTypesInitial","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIRoutingTypesInitial","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1initial\/title"},{"op":"replace","value":[{"text":"SMIRoutingTypesInitial","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1initial\/fragments"},{"op":"replace","value":"SMIRoutingTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRoutingTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRoutingTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/navigatorTitle"}]}]}