{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments\/attachments"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachments","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FileAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFileAsset"},{"text":"]","kind":"text"}],"symbolKind":"property","required":true,"externalID":"c:objc(pl)SMIAttachments(py)attachments","navigatorTitle":[{"text":"attachments","kind":"identifier"}],"roleHeading":"Instance Property","title":"attachments","modules":[{"name":"SMIClientCore"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments"]]},"abstract":[{"text":"The array of file attachments in this collection.","type":"text"},{"text":" ","type":"text"},{"text":"Each attachment in the array conforms to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"text":" protocol.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFileAsset","text":"FileAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachments\/attachments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachments\/attachments"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments/attachments":{"abstract":[{"type":"text","text":"The array of file attachments in this collection."},{"type":"text","text":" "},{"type":"text","text":"Each attachment in the array conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"type":"text","text":" protocol."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments\/attachments","role":"symbol","navigatorTitle":[{"text":"attachments","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/attachments\/attachments","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachments","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FileAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFileAsset"},{"text":"]","kind":"text"}],"title":"attachments","kind":"symbol","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments":{"url":"\/documentation\/smiclientcore\/attachments","kind":"symbol","type":"topic","title":"Attachments","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attachments"}],"navigatorTitle":[{"kind":"identifier","text":"Attachments"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","abstract":[{"type":"text","text":"A protocol that represents a collection of file attachments in a conversation."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"url":"\/documentation\/smiclientcore\/fileasset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","title":"FileAsset","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"attachments"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"attachments"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIFileAsset>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments~1attachments\/title","value":"attachments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments~1attachments\/fragments","value":[{"text":"attachments","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/title","value":"SMIAttachments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/fragments","value":[{"text":"SMIAttachments","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachments"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"kind":"identifier","text":"SMIFileAsset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}]}]}]}