{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"receive","kind":"identifier"},{"kind":"text","text":"("},{"text":"normalizedChannels","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":"])"}]}]},{"parameters":[{"name":"normalizedChannels","content":[{"type":"paragraph","inlineContent":[{"text":"An array of normalized amplitude values, one per channel.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/audioprocessreceiver\/receive(normalizedchannels:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/audioprocessreceiver\/receive(normalizedchannels:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"receive"},{"text":"(","kind":"text"},{"text":"normalizedChannels","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":"])","kind":"text"}],"modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver(im)receiveWithNormalizedChannels:","symbolKind":"method","title":"receive(normalizedChannels:)","navigatorTitle":[{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"required":true},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Receives normalized audio channel levels for visualization."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver/receive(normalizedChannels:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedChannels","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"])","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver\/receive(normalizedchannels:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","abstract":[{"text":"Receives normalized audio channel levels for visualization.","type":"text"}],"type":"topic","title":"receive(normalizedChannels:)","kind":"symbol","navigatorTitle":[{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","abstract":[{"type":"text","text":"A protocol for receiving processed audio data from an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"AudioProcessReceiver","kind":"symbol","navigatorTitle":[{"text":"AudioProcessReceiver","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"receiveWithNormalizedChannels:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"receiveWithNormalizedChannels:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"receiveWithNormalizedChannels:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"normalizedChannels"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An array of normalized amplitude values, one per channel.","type":"text"}],"type":"paragraph"}],"name":"normalizedChannels"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/title","value":"receiveWithNormalizedChannels:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"receiveWithNormalizedChannels:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title","value":"SMIAudioTrack","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments","value":[{"kind":"identifier","text":"SMIAudioTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAudioTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/title","value":"SMIAudioProcessReceiver","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/fragments","value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"op":"replace"}]}]}