{"kind":"symbol","metadata":{"externalID":"c:@SMIListAPIDirectionsAscending","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ascending"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","text":"ListAPIDirections"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"SMIListAPIDirectionsAscending"}],"extendedModule":"SMIClientCore","title":"ascending"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Orders list items from oldest to newest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in chronological order."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ascending"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListAPIDirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/ascending"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/listapidirections\/ascending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/listapidirections\/ascending"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/ascending":{"url":"\/documentation\/smiclientcore\/listapidirections\/ascending","abstract":[{"type":"text","text":"Orders list items from oldest to newest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in chronological order."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/ascending","role":"symbol","navigatorTitle":[{"text":"SMIListAPIDirectionsAscending","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ascending","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"}],"type":"topic","title":"ascending"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","role":"symbol","url":"\/documentation\/smiclientcore\/listapidirections","abstract":[{"type":"text","text":"An enum that defines the ordering direction for list-based API requests."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListAPIDirections","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ListAPIDirections","kind":"identifier"}],"title":"ListAPIDirections"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIListAPIDirectionsAscending","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIListAPIDirectionsAscending","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIListAPIDirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIListAPIDirectionsAscending"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIListAPIDirectionsAscending","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1ascending\/title"},{"value":[{"kind":"identifier","text":"SMIListAPIDirectionsAscending"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1ascending\/fragments"},{"value":"SMIListAPIDirections","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/title"},{"value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/fragments"},{"value":[{"kind":"identifier","text":"SMIListAPIDirections"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/navigatorTitle"}]}]}