{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@SMIListAPIDirectionsDescending","symbolKind":"property","navigatorTitle":[{"text":"SMIListAPIDirectionsDescending","kind":"identifier"}],"roleHeading":"Type Property","title":"descending","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descending","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","kind":"typeIdentifier"}],"modules":[{"name":"SMIClientCore"}]},"sections":[],"abstract":[{"text":"Orders list items from newest to oldest.","type":"text"},{"text":" ","type":"text"},{"text":"Used when you want to retrieve items in reverse chronological order.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"descending"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","kind":"typeIdentifier","text":"ListAPIDirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/listapidirections\/descending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/listapidirections\/descending"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections":{"title":"ListAPIDirections","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListAPIDirections","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","navigatorTitle":[{"text":"ListAPIDirections","kind":"identifier"}],"abstract":[{"text":"An enum that defines the ordering direction for list-based API requests.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/listapidirections","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/descending":{"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/listapidirections\/descending","abstract":[{"type":"text","text":"Orders list items from newest to oldest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in reverse chronological order."}],"kind":"symbol","title":"descending","navigatorTitle":[{"kind":"identifier","text":"SMIListAPIDirectionsDescending"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"descending"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","kind":"typeIdentifier","text":"ListAPIDirections"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIListAPIDirectionsDescending","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIListAPIDirectionsDescending"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","kind":"typeIdentifier","text":"SMIListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIListAPIDirectionsDescending"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIListAPIDirections","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/title","op":"replace"},{"value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIListAPIDirections"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/navigatorTitle","op":"replace"},{"value":"SMIListAPIDirectionsDescending","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIListAPIDirectionsDescending"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/fragments","op":"replace"}]}]}