{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/listapidirections\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"SMIClientCore"}],"role":"collectionGroup"},"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/!=(_:_:)"],"anchor":"Operators"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections":{"abstract":[{"type":"text","text":"An enum that defines the ordering direction for list-based API requests."}],"url":"\/documentation\/smiclientcore\/listapidirections","navigatorTitle":[{"text":"ListAPIDirections","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListAPIDirections","kind":"identifier"}],"title":"ListAPIDirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","role":"symbol","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/smiclientcore\/listapidirections\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/!=(_:_:)","title":"!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIListAPIDirections","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/title"},{"value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/fragments"},{"value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/navigatorTitle"}]}]}