{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/createconversation(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/createconversation(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/createConversation(_:)"},"metadata":{"roleHeading":"Instance Method","platforms":[{"deprecated":true,"message":"Will be removed in a future version. Use `createWithRemoteConfiguration:`","unavailable":false,"beta":false}],"title":"createConversation(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"createConversation:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIConversationClient(im)createConversation:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"remoteConfig","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":")","kind":"text"}]}]}],"deprecationSummary":[{"inlineContent":[{"text":"Will be removed in a future version. Use `createWithRemoteConfiguration:`","type":"text"}],"type":"paragraph"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/createConversation(_:)":{"title":"createConversation(_:)","deprecated":true,"abstract":[],"url":"\/documentation\/smiclientcore\/conversationclient\/createconversation(_:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/createConversation(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createConversation"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","kind":"typeIdentifier","text":"RemoteConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"createConversation:"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"abstract":[{"text":"A protocol that defines the configuration information for an embedded service deployment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","title":"RemoteConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"deprecated":true,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createConversation:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"createConversation:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"createConversation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIRemoteConfiguration>","preciseIdentifier":"c:Qoobjc(pl)SMIRemoteConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"remoteConfig","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in a future version. Use `createWithRemoteConfiguration:`","type":"text"}]}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1createConversation(_:)\/title","value":"createConversation:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1createConversation(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createConversation:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","value":"SMIRemoteConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace"}]}]}