{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/create(remoteconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/create(remoteconfig:)"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create(remoteConfig:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteConfig"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","kind":"typeIdentifier","text":"RemoteConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"remoteConfig","content":[{"inlineContent":[{"text":"The  ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"},{"text":" to submit.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Creates a conversation with the id assigned to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","type":"reference"},{"text":" ","type":"text"},{"text":"Note: That this is not a fully idempotent operation. Calling this on an existing active conversation may trigger a new session.","type":"text"},{"text":" ","type":"text"},{"text":"This can also be used to explicitly force a new session if there is no active session on the conversation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","required":true,"role":"symbol","navigatorTitle":[{"text":"createWithRemoteConfiguration:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SMIConversationClient(im)createWithRemoteConfiguration:","title":"create(remoteConfig:)","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/create(remoteConfig:)":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationclient\/create(remoteconfig:)","title":"create(remoteConfig:)","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create(remoteConfig:)","navigatorTitle":[{"text":"createWithRemoteConfiguration:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a conversation with the id assigned to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" "},{"type":"text","text":"Note: That this is not a fully idempotent operation. Calling this on an existing active conversation may trigger a new session."},{"type":"text","text":" "},{"text":"This can also be used to explicitly force a new session if there is no active session on the conversation.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteConfig"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"RemoteConfiguration","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"abstract":[{"text":"A protocol that defines the configuration information for an embedded service deployment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","title":"RemoteConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"createWithRemoteConfiguration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"createWithRemoteConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"createWithRemoteConfiguration:"},{"kind":"text","text":"("},{"text":"id<SMIRemoteConfiguration>","preciseIdentifier":"c:Qoobjc(pl)SMIRemoteConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"remoteConfig"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The  "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"reference","isActive":true},{"type":"text","text":" to submit."}],"type":"paragraph"}],"name":"remoteConfig"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"value":"createWithRemoteConfiguration:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create(remoteConfig:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"createWithRemoteConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create(remoteConfig:)\/fragments"},{"value":"SMIRemoteConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}