{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:completion:)"]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:completion:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation.","type":"text"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"entries(withLimit:offset:completion:)","symbolKind":"method","platforms":[],"externalID":"c:objc(pl)SMIConversationClient(im)entriesWithLimit:offset:completion:","required":true,"navigatorTitle":[{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"text":")","kind":"text"}],"modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"kind":"text","text":" "},{"kind":"internalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of results to expect."}]}]},{"name":"offset","content":[{"inlineContent":[{"type":"text","text":"The offset to begin searching for results."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the search query."}]}]}],"kind":"parameters"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:olderThanEntry:completion:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"navigatorTitle":[{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}],"title":"entries(withLimit:olderThanEntry:completion:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:completion:)","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FullQueryCompletion":{"title":"FullQueryCompletion","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullQueryCompletion"}],"navigatorTitle":[{"kind":"identifier","text":"FullQueryCompletion"}],"url":"\/documentation\/smiclientcore\/fullquerycompletion","abstract":[{"type":"text","text":"Completion block for queries returning "},{"type":"codeVoice","code":"SMIConversationEntry"},{"type":"text","text":" objects."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:offset:completion:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"navigatorTitle":[{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}],"title":"entries(withLimit:offset:completion:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:completion:)","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"entriesWithLimit:offset:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"entriesWithLimit:offset:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"entriesWithLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offset:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"offset"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<id<SMIConversationEntry>> *, id<SMIConversation>, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*Qoobjc(pl)SMIConversation#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"limit","content":[{"inlineContent":[{"text":"The maximum number of results to expect.","type":"text"}],"type":"paragraph"}]},{"name":"offset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The offset to begin searching for results."}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"The result of the search query.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"entriesWithLimit:olderThanEntry:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:completion:)\/fragments"},{"op":"replace","value":"SMIConversationClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"op":"replace","value":"SMIConversation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"op":"replace","value":"SMIFullQueryCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFullQueryCompletion"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/fragments"},{"op":"replace","value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/navigatorTitle"},{"op":"replace","value":"entriesWithLimit:offset:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"entriesWithLimit:offset:completion:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:completion:)\/fragments"}]}]}