{"abstract":[{"text":"Retrieves messages for this conversation. Only returns the first subset of messages.","type":"text"},{"text":" ","type":"text"},{"text":"This is a convenience method to make direct database calls for entries associated with this conversation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"metadata":{"platforms":[],"roleHeading":"Instance Method","modules":[{"name":"SMIClientCore"}],"title":"entries(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","text":"FullQueryCompletion"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)SMIConversationClient(im)entriesWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"entriesWithCompletion:"}],"required":true,"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(completion:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion"},{"text":")","kind":"text"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ([any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","text":"ConversationEntry"},{"kind":"text","text":"], any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","text":"Conversation"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The result of the search query."}],"type":"paragraph"}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`"}],"type":"paragraph"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FullQueryCompletion":{"title":"FullQueryCompletion","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullQueryCompletion"}],"navigatorTitle":[{"kind":"identifier","text":"FullQueryCompletion"}],"url":"\/documentation\/smiclientcore\/fullquerycompletion","abstract":[{"type":"text","text":"Completion block for queries returning "},{"type":"codeVoice","code":"SMIConversationEntry"},{"type":"text","text":" objects."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(completion:)":{"deprecated":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(completion:)","kind":"symbol","title":"entries(completion:)","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"entriesWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/conversationclient\/entries(completion:)","abstract":[{"type":"text","text":"Retrieves messages for this conversation. Only returns the first subset of messages."},{"type":"text","text":" "},{"type":"text","text":"This is a convenience method to make direct database calls for entries associated with this conversation."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"entriesWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"entriesWithCompletion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"entriesWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*Qoobjc(pl)SMIConversation#*$objc(cs)NSError)","text":"void (^)(NSArray<id<SMIConversationEntry>> *, id<SMIConversation>, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The result of the search query.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/title","value":"SMIFullQueryCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/fragments","value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFullQueryCompletion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(completion:)\/title","value":"entriesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"entriesWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"kind":"identifier","text":"SMIConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}