{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":"], any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"text":")","kind":"text"}]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"kind":"text","text":" "},{"kind":"internalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping "},{"kind":"text","text":"([any "},{"kind":"typeIdentifier","text":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","text":"Conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","preciseIdentifier":"c:objc(pl)SMIConversation"},{"kind":"text","text":")?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum number of results to expect.","type":"text"}]}],"name":"limit"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The offset to begin searching for results.","type":"text"}]}],"name":"offset"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the search query."}]}],"name":"completion"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:)"},"kind":"symbol","seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:)"],"title":"Related Documentation"}],"metadata":{"required":true,"platforms":[{"unavailable":false,"message":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`","deprecated":true,"beta":false}],"title":"entries(withLimit:offset:)","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIConversationClient(im)entriesWithLimit:offset:completion:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:offset:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":"], any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:)","navigatorTitle":[{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}],"abstract":[{"text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:)","title":"entries(withLimit:offset:)","required":true,"deprecated":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/smiclientcore\/conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:olderThanEntry:)":{"deprecated":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:)","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:)","title":"entries(withLimit:olderThanEntry:)","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FullQueryCompletion":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullQueryCompletion","kind":"identifier"}],"title":"FullQueryCompletion","abstract":[{"text":"Completion block for queries returning ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" objects.","type":"text"}],"navigatorTitle":[{"text":"FullQueryCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fullquerycompletion","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"deprecated":true,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"entriesWithLimit:offset:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:)"],"anchor":"Related-Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"entriesWithLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offset:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","text":"SMIFullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of results to expect."}]}],"name":"limit"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The offset to begin searching for results.","type":"text"}]}],"name":"offset"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the search query."}]}],"name":"completion"}]}},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`"}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:)\/title","value":"entriesWithLimit:offset:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"kind":"identifier","text":"SMIConversation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:)\/title","value":"entriesWithLimit:olderThanEntry:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/title","value":"SMIFullQueryCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/fragments","value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/navigatorTitle","value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}],"op":"replace"}]}]}