{"deprecationSummary":[{"inlineContent":[{"text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`","type":"text"}],"type":"paragraph"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ([any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"kind":"text","text":"], any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"kind":"text","text":")"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum number of results to expect.","type":"text"}]}],"name":"limit"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The comparison entry which serves as a base for returning older entries in the conversation. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"the query starts from the newest known entry."}]}],"name":"olderThanEntry"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the search query."}]}],"name":"completion"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:)"},"abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"title":"entries(withLimit:olderThanEntry:)","modules":[{"name":"SMIClientCore"}],"symbolKind":"method","externalID":"c:objc(pl)SMIConversationClient(im)entriesWithLimit:olderThanEntry:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ([any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"entriesWithLimit:olderThanEntry:completion:"}],"platforms":[{"message":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`","beta":false,"deprecated":true,"unavailable":false}],"role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FullQueryCompletion":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullQueryCompletion","kind":"identifier"}],"title":"FullQueryCompletion","abstract":[{"text":"Completion block for queries returning ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" objects.","type":"text"}],"navigatorTitle":[{"text":"FullQueryCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fullquerycompletion","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:olderThanEntry:)":{"deprecated":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:)","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:)","title":"entries(withLimit:olderThanEntry:)","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/smiclientcore\/conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"entriesWithLimit:olderThanEntry:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"entriesWithLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"olderThanEntry:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<SMIConversationEntry>","preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry"},{"kind":"text","text":") "},{"kind":"internalParam","text":"olderThanEntry"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SMIFullQueryCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The maximum number of results to expect.","type":"text"}],"type":"paragraph"}],"name":"limit"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The comparison entry which serves as a base for returning older entries in the conversation. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"the query starts from the newest known entry."}]}],"name":"olderThanEntry"},{"content":[{"inlineContent":[{"text":"The result of the search query.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"path":"\/deprecationSummary","op":"replace","value":[{"inlineContent":[{"text":"Will be removed in a future version. Use `entriesWithLimit:fromTimestamp:direction:completion:`","type":"text"}],"type":"paragraph"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/title","op":"replace","value":"SMIFullQueryCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFullQueryCompletion"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/navigatorTitle","op":"replace","value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:)\/title","op":"replace","value":"entriesWithLimit:olderThanEntry:completion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace","value":"SMIConversation"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}]}]}]}