{"deprecationSummary":[{"inlineContent":[{"text":"Will be removed in a future version. Use `fetchLatestVerifiedEntryWithCompletion:`","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/latestverifiedentry()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/latestverifiedentry()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/latestVerifiedEntry()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestVerifiedEntry","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":"], any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"kind":"text","text":")"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latestVerifiedEntry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"kind":"text","text":")?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The result of the search query.","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"kind":"symbol","metadata":{"role":"symbol","required":true,"title":"latestVerifiedEntry()","roleHeading":"Instance Method","externalID":"c:objc(pl)SMIConversationClient(im)latestVerifiedEntryWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"latestVerifiedEntryWithCompletion:"}],"modules":[{"name":"SMIClientCore"}],"platforms":[{"deprecated":true,"beta":false,"unavailable":false,"message":"Will be removed in a future version. Use `fetchLatestVerifiedEntryWithCompletion:`"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestVerifiedEntry"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ([any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":"], any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":")"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"abstract":[{"type":"text","text":"Returns the most recent verified entry."},{"type":"text","text":" "},{"type":"text","text":"An entry is considered verified if the entry in the local DB cache has been verified against the conversation transcript in the network service."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FullQueryCompletion":{"url":"\/documentation\/smiclientcore\/fullquerycompletion","navigatorTitle":[{"text":"FullQueryCompletion","kind":"identifier"}],"type":"topic","kind":"symbol","title":"FullQueryCompletion","role":"symbol","abstract":[{"type":"text","text":"Completion block for queries returning "},{"type":"codeVoice","code":"SMIConversationEntry"},{"type":"text","text":" objects."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FullQueryCompletion","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"type":"topic","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"url":"\/documentation\/smiclientcore\/conversationclient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"title":"Conversation","url":"\/documentation\/smiclientcore\/conversation","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/latestVerifiedEntry()":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/latestVerifiedEntry()","url":"\/documentation\/smiclientcore\/conversationclient\/latestverifiedentry()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latestVerifiedEntryWithCompletion:"}],"deprecated":true,"abstract":[{"text":"Returns the most recent verified entry.","type":"text"},{"text":" ","type":"text"},{"text":"An entry is considered verified if the entry in the local DB cache has been verified against the conversation transcript in the network service.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestVerifiedEntry"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ([any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":"], any "},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation"},{"kind":"text","text":")"}],"kind":"symbol","title":"latestVerifiedEntry()"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"latestVerifiedEntryWithCompletion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latestVerifiedEntryWithCompletion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"latestVerifiedEntryWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FullQueryCompletion","text":"SMIFullQueryCompletion","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the search query."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `fetchLatestVerifiedEntryWithCompletion:`"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMIFullQueryCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/title"},{"value":[{"text":"SMIFullQueryCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/fragments"},{"value":[{"kind":"identifier","text":"SMIFullQueryCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FullQueryCompletion\/navigatorTitle"},{"value":"SMIConversationClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"},{"value":"SMIConversation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"value":"latestVerifiedEntryWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1latestVerifiedEntry()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latestVerifiedEntryWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1latestVerifiedEntry()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}