{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveTranscript"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMIConversationRequestCompletion.h@T@SMITranscriptRequestCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptRequestCompletion","kind":"typeIdentifier","text":"TranscriptRequestCompletion"},{"kind":"text","text":")"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveTranscript"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFDocument","text":"PDFDocument"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The result of the transcript request with a PDF document of the conversation transcript.","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"metadata":{"symbolKind":"method","modules":[{"name":"SMIClientCore"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveTranscript"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationRequestCompletion.h@T@SMITranscriptRequestCompletion","text":"TranscriptRequestCompletion"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","title":"retrieveTranscript(_:)","navigatorTitle":[{"kind":"identifier","text":"retrieveTranscript:"}],"externalID":"c:objc(pl)SMIConversationClient(im)retrieveTranscript:"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/retrieveTranscript(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Attempt to download a transcript of the converation."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/retrievetranscript(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/retrievetranscript(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/retrieveTranscript(_:)":{"navigatorTitle":[{"text":"retrieveTranscript:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Attempt to download a transcript of the converation."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveTranscript","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TranscriptRequestCompletion","preciseIdentifier":"c:SMIConversationRequestCompletion.h@T@SMITranscriptRequestCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/retrieveTranscript(_:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/retrievetranscript(_:)","title":"retrieveTranscript(_:)","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TranscriptRequestCompletion":{"abstract":[{"type":"text","text":"The completion block for returning a conversation transcript."}],"title":"TranscriptRequestCompletion","navigatorTitle":[{"text":"TranscriptRequestCompletion","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranscriptRequestCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/transcriptrequestcompletion","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptRequestCompletion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"retrieveTranscript:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"retrieveTranscript:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"retrieveTranscript:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)PDFDocument#*$objc(cs)NSError)","text":"void (^)(PDFDocument *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The result of the transcript request with a PDF document of the conversation transcript.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1retrieveTranscript(_:)\/title","value":"retrieveTranscript:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1retrieveTranscript(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveTranscript:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/title","value":"SMITranscriptRequestCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/fragments","value":[{"kind":"identifier","text":"SMITranscriptRequestCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/navigatorTitle","value":[{"text":"SMITranscriptRequestCompletion","kind":"identifier"}],"op":"replace"}]}]}