{"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"send(form:)","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"form","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"EntryTypeFormMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"sendForm:","kind":"identifier"}],"externalID":"c:objc(pl)SMIConversationClient(im)sendForm:","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/send(form:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/send(form:)"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(form:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"form","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"EntryTypeFormMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"form","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"},{"type":"text","text":" to send."}]}]}],"kind":"parameters"}],"abstract":[{"text":"Sends a filled out Form.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(form:)":{"kind":"symbol","navigatorTitle":[{"text":"sendForm:","kind":"identifier"}],"required":true,"url":"\/documentation\/smiclientcore\/conversationclient\/send(form:)","abstract":[{"text":"Sends a filled out Form.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(form:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"form","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"EntryTypeFormMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"send(form:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormMessage":{"type":"topic","navigatorTitle":[{"text":"EntryTypeFormMessage","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeFormMessage","kind":"identifier"}],"title":"EntryTypeFormMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","url":"\/documentation\/smiclientcore\/entrytypeformmessage","abstract":[{"type":"text","text":"A protocol that defines the base type for form messages in a conversation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"text":"for events using the associated delegate.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationclient","role":"symbol","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendForm:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendForm:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendForm:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIEntryTypeFormMessage","text":"id<SMIEntryTypeFormMessage>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"form"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"form","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","isActive":true},{"type":"text","text":" to send."}]}]}]}},{"value":"sendForm:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(form:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendForm:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(form:)\/fragments"},{"value":"SMIEntryTypeFormMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/title"},{"value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/fragments"},{"value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/navigatorTitle"},{"value":"SMIConversationClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"}]}]}