{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reply"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","preciseIdentifier":"c:objc(pl)SMIAbstractChoice","text":"AbstractChoice"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","isActive":true},{"text":" which is emitted as part of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","isActive":true},{"text":" entry.","type":"text"}]}],"name":"reply"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(reply:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/send(reply:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/send(reply:)"]}],"metadata":{"externalID":"c:objc(pl)SMIConversationClient(im)sendReply:","required":true,"navigatorTitle":[{"text":"sendReply:","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"send(reply:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reply","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AbstractChoice","preciseIdentifier":"c:objc(pl)SMIAbstractChoice","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"text":"Sends a reply to a structured content message.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractchoice","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"kind":"symbol","title":"AbstractChoice","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(reply:)":{"url":"\/documentation\/smiclientcore\/conversationclient\/send(reply:)","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(reply:)","abstract":[{"type":"text","text":"Sends a reply to a structured content message."}],"kind":"symbol","type":"topic","title":"send(reply:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reply","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractChoice","text":"AbstractChoice","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"sendReply:","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"title":"Choice","url":"\/documentation\/smiclientcore\/choice","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Choice"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","navigatorTitle":[{"kind":"identifier","text":"Choice"}],"abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"sendReply:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendReply:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendReply:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMIAbstractChoice","kind":"typeIdentifier","text":"id<SMIAbstractChoice>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reply"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"reply","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","type":"reference"},{"text":" which is emitted as part of a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","type":"reference"},{"text":" entry.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/title","op":"replace","value":"SMIAbstractChoice"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/fragments","op":"replace","value":[{"text":"SMIAbstractChoice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/navigatorTitle","op":"replace","value":[{"text":"SMIAbstractChoice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(reply:)\/title","op":"replace","value":"sendReply:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(reply:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendReply:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title","op":"replace","value":"SMIChoice"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments","op":"replace","value":[{"text":"SMIChoice","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChoice"}]}]}]}