{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/set(sessioncontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/set(sessioncontext:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionContext","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SessionContextProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol","preciseIdentifier":"c:objc(pl)SMISessionContext"},{"text":")?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"sessionContext","content":[{"type":"paragraph","inlineContent":[{"text":"An array of session context items to be sent with the next message.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The context is stored in memory only and will be cleared when the message is successfully sent."}],"type":"paragraph"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/set(sessionContext:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","required":true,"navigatorTitle":[{"text":"setSessionContext:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionContext","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SessionContextProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMISessionContext"},{"text":")?)","kind":"text"}],"title":"set(sessionContext:)","externalID":"c:objc(pl)SMIConversationClient(im)setSessionContext:","modules":[{"name":"SMIClientCore"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"abstract":[{"type":"text","text":"Sets the session context that will be sent with the next message."}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/set(sessionContext:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionContext"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMISessionContext","kind":"typeIdentifier","text":"SessionContextProtocol"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/set(sessionContext:)","url":"\/documentation\/smiclientcore\/conversationclient\/set(sessioncontext:)","kind":"symbol","role":"symbol","type":"topic","required":true,"abstract":[{"type":"text","text":"Sets the session context that will be sent with the next message."}],"title":"set(sessionContext:)","navigatorTitle":[{"kind":"identifier","text":"setSessionContext:"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"title":"AbstractSessionContextProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol":{"navigatorTitle":[{"text":"SessionContextProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/sessioncontextprotocol","kind":"symbol","abstract":[{"type":"text","text":"Represents a session context item that contains an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol","type":"topic","title":"SessionContextProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setSessionContext:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSessionContext:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setSessionContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMISessionContext>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMISessionContext"},{"text":") ","kind":"text"},{"text":"sessionContext","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"sessionContext","content":[{"type":"paragraph","inlineContent":[{"text":"An array of session context items to be sent with the next message.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1set(sessionContext:)\/title","op":"replace","value":"setSessionContext:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1set(sessionContext:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSessionContext:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title","op":"replace","value":"SMIAbstractSessionContext"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments","op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/title","op":"replace","value":"SMISessionContext"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISessionContext"}]},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionContext"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/navigatorTitle"}]}]}