{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:createConversationOnSubmit:)"},"metadata":{"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIConversationClient(im)submitRemoteConfiguration:createConversationOnSubmit:","required":true,"title":"submit(remoteConfig:createConversationOnSubmit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"remoteConfig"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","text":"RemoteConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createConversationOnSubmit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"submitRemoteConfiguration:createConversationOnSubmit:"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Submits the remote configuration values and starts the conversation if "},{"code":"createConversationOnSubmit","type":"codeVoice"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the SDK stores the pre-chat data until the conversation is created."}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:createconversationonsubmit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:createconversationonsubmit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":", ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"},{"type":"text","text":" to submit."}]}],"name":"remoteConfig"},{"content":[{"inlineContent":[{"type":"text","text":"Determines if the conversation starts when the pre-chat data is submitted."}],"type":"paragraph"}],"name":"createConversationOnSubmit"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(remoteConfig:createConversationOnSubmit:)":{"role":"symbol","required":true,"title":"submit(remoteConfig:createConversationOnSubmit:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:createconversationonsubmit:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":", ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"submitRemoteConfiguration:createConversationOnSubmit:"}],"abstract":[{"text":"Submits the remote configuration values and starts the conversation if ","type":"text"},{"code":"createConversationOnSubmit","type":"codeVoice"},{"text":" is true.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the SDK stores the pre-chat data until the conversation is created.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:createConversationOnSubmit:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"submitRemoteConfiguration:createConversationOnSubmit:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitRemoteConfiguration:createConversationOnSubmit:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"submitRemoteConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMIRemoteConfiguration","kind":"typeIdentifier","text":"id<SMIRemoteConfiguration>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"remoteConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"createConversationOnSubmit:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createConversationOnSubmit","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The  ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"reference"},{"text":" to submit.","type":"text"}],"type":"paragraph"}],"name":"remoteConfig"},{"content":[{"inlineContent":[{"type":"text","text":"Determines if the conversation starts when the pre-chat data is submitted."}],"type":"paragraph"}],"name":"createConversationOnSubmit"}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:createConversationOnSubmit:)\/title","op":"replace","value":"submitRemoteConfiguration:createConversationOnSubmit:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:createConversationOnSubmit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitRemoteConfiguration:createConversationOnSubmit:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","value":"SMIRemoteConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}]}]}]}