{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"PreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"text":"], ","kind":"text"},{"text":"hiddenPreChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SMIConversationClient(im)submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","platforms":[{"unavailable":false,"beta":false,"message":"Will be removed in a future version. Use `submitRemoteConfiguration:createConversationOnSubmit:`","deprecated":true}],"role":"symbol","title":"submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"preChatFields","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},{"type":"text","text":" objects representing collected pre-chat data."}]}]},{"name":"hiddenPreChatFields","content":[{"inlineContent":[{"text":"An array of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference","isActive":true},{"text":" objects representing hidden prechat data.","type":"text"}],"type":"paragraph"}]},{"name":"createConversationOnSubmit","content":[{"inlineContent":[{"text":"Determines if the conversation starts when the pre-chat data is submitted.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Submits collected pre-chat fields and starts the conversation if ","type":"text"},{"type":"codeVoice","code":"createConversationOnSubmit"},{"text":" is true.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the SDK stores the pre-chat data until the conversation is created.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `submitRemoteConfiguration:createConversationOnSubmit:`"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:createconversationonsubmit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:createconversationonsubmit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"createConversationOnSubmit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","title":"submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:createconversationonsubmit:)","kind":"symbol","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Submits collected pre-chat fields and starts the conversation if "},{"type":"codeVoice","code":"createConversationOnSubmit"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the SDK stores the pre-chat data until the conversation is created."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","navigatorTitle":[{"kind":"identifier","text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"symbol","title":"PreChatField","type":"topic","url":"\/documentation\/smiclientcore\/prechatfield","role":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"text":"for events using the associated delegate.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationclient","role":"symbol","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"title":"HiddenPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a hidden pre-chat field in the conversation configuration."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":true}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"submitPreChatFields:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<SMIPreChatField>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"preChatFields","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<SMIHiddenPreChatField>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"hiddenPreChatFields","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"createConversationOnSubmit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createConversationOnSubmit","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":{"parameters":[{"name":"preChatFields","content":[{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","isActive":true},{"text":" objects representing collected pre-chat data.","type":"text"}]}]},{"name":"hiddenPreChatFields","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference"},{"type":"text","text":" objects representing hidden prechat data."}]}]},{"name":"createConversationOnSubmit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Determines if the conversation starts when the pre-chat data is submitted."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `submitRemoteConfiguration:createConversationOnSubmit:`"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)\/fragments"},{"value":"SMIPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title"},{"value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle"},{"value":"SMIConversationClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"},{"value":"SMIHiddenPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments"},{"op":"replace","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle"}]}]}