{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `submitRemoteConfiguration:`"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Submits collected pre-chat fields and creates a conversation if required."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","isActive":true},{"text":" objects representing collected pre-chat data.","type":"text"}]}],"name":"preChatFields"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"submitPreChatFields:"}],"required":true,"platforms":[{"deprecated":true,"unavailable":false,"beta":false,"message":"Will be removed in a future version. Use `submitRemoteConfiguration:`"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"submit(preChatFields:)","externalID":"c:objc(pl)SMIConversationClient(im)submitPreChatFields:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","kind":"typeIdentifier","text":"PreChatField"},{"kind":"text","text":"])"}]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:)":{"role":"symbol","deprecated":true,"abstract":[{"text":"Submits collected pre-chat fields and creates a conversation if required.","type":"text"}],"title":"submit(preChatFields:)","required":true,"url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"PreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"text":"])","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"submitPreChatFields:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatfield","kind":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"type":"topic","title":"PreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"type":"topic","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"url":"\/documentation\/smiclientcore\/conversationclient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"submitPreChatFields:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"submitPreChatFields:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<SMIPreChatField>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"preChatFields","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","isActive":true},{"type":"text","text":" objects representing collected pre-chat data."}]}],"name":"preChatFields"}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in a future version. Use `submitRemoteConfiguration:`","type":"text"}]}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:)\/title","value":"submitPreChatFields:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","value":"SMIPreChatField","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"}]}]}