{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"abstract":[{"type":"text","text":"Submits the remote configuration values."}],"metadata":{"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIConversationClient(im)submitRemoteConfiguration:","role":"symbol","required":true,"title":"submit(remoteConfig:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"submitRemoteConfiguration:","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:)"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"remoteConfig","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The  "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"reference","isActive":true},{"type":"text","text":" to submit."}]}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(remoteConfig:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:)","kind":"symbol","navigatorTitle":[{"text":"submitRemoteConfiguration:","kind":"identifier"}],"title":"submit(remoteConfig:)","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Submits the remote configuration values."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"submitRemoteConfiguration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitRemoteConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"submitRemoteConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMIRemoteConfiguration","kind":"typeIdentifier","text":"id<SMIRemoteConfiguration>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"remoteConfig"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"remoteConfig","content":[{"inlineContent":[{"type":"text","text":"The  "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","isActive":true},{"type":"text","text":" to submit."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","value":"SMIRemoteConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:)\/title","value":"submitRemoteConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitRemoteConfiguration:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}