{"abstract":[{"type":"text","text":"Submits collected pre-chat fields and creates a conversation if required."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField","kind":"typeIdentifier","text":"PreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An array of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","type":"reference","isActive":true},{"type":"text","text":" objects representing collected pre-chat data."}],"type":"paragraph"}],"name":"preChatFields"},{"content":[{"inlineContent":[{"type":"text","text":"An array of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference","isActive":true},{"type":"text","text":" objects representing hidden prechat data."}],"type":"paragraph"}],"name":"hiddenPreChatFields"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:)"},"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"])"}],"roleHeading":"Instance Method","symbolKind":"method","title":"submit(preChatFields:hiddenPreChatFields:)","platforms":[{"message":"Will be removed in a future version. Use `submitRemoteConfiguration:`","deprecated":true,"unavailable":false,"beta":false}],"role":"symbol","externalID":"c:objc(pl)SMIConversationClient(im)submitPreChatFields:hiddenPreChatFields:","required":true,"navigatorTitle":[{"kind":"identifier","text":"submitPreChatFields:hiddenPreChatFields:"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `submitRemoteConfiguration:`"}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:hiddenPreChatFields:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:)","navigatorTitle":[{"text":"submitPreChatFields:hiddenPreChatFields:","kind":"identifier"}],"required":true,"title":"submit(preChatFields:hiddenPreChatFields:)","abstract":[{"text":"Submits collected pre-chat fields and creates a conversation if required.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","text":"PreChatField","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"hiddenPreChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","text":"HiddenPreChatField","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"deprecated":true,"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatField"}],"navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"url":"\/documentation\/smiclientcore\/prechatfield","title":"PreChatField","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"abstract":[{"text":"A protocol that represents a hidden pre-chat field in the conversation configuration.","type":"text"}],"title":"HiddenPreChatField","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"submitPreChatFields:hiddenPreChatFields:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:hiddenPreChatFields:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"submitPreChatFields:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIPreChatField>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preChatFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreChatFields:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIHiddenPreChatField>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hiddenPreChatFields"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"preChatFields","content":[{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","isActive":true,"type":"reference"},{"text":" objects representing collected pre-chat data.","type":"text"}]}]},{"name":"hiddenPreChatFields","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference"},{"text":" objects representing hidden prechat data.","type":"text"}]}]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `submitRemoteConfiguration:`"}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:)\/title","value":"submitPreChatFields:hiddenPreChatFields:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:hiddenPreChatFields:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","value":"SMIPreChatField","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title","value":"SMIHiddenPreChatField","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"op":"replace"}]}]}