{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:modalities:createconversationonsubmit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:modalities:createconversationonsubmit:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:modalities:createConversationOnSubmit:)"},"metadata":{"title":"submit(remoteConfig:modalities:createConversationOnSubmit:)","externalID":"c:objc(pl)SMIConversationClient(im)submitRemoteConfiguration:modalities:createConversationOnSubmit:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modalities","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"submitRemoteConfiguration:modalities:createConversationOnSubmit:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Submits the remote configuration values and starts the conversation if "},{"code":"createConversationOnSubmit","type":"codeVoice"},{"text":" is true.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the SDK stores the pre-chat data until the conversation is created.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","text":"RemoteConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"modalities","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The  "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"reference","isActive":true},{"type":"text","text":" to submit."}]}],"name":"remoteConfig"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The starting modalities for this conversation. Currently only supports a single modality, API accepts an array for future functionality.","type":"text"}]}],"name":"modalities"},{"content":[{"inlineContent":[{"type":"text","text":"Determines if the conversation starts when the pre-chat data is submitted."}],"type":"paragraph"}],"name":"createConversationOnSubmit"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(remoteConfig:modalities:createConversationOnSubmit:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:modalities:createConversationOnSubmit:)","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:modalities:createconversationonsubmit:)","abstract":[{"type":"text","text":"Submits the remote configuration values and starts the conversation if "},{"type":"codeVoice","code":"createConversationOnSubmit"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the SDK stores the pre-chat data until the conversation is created."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":", ","kind":"text"},{"text":"modalities","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"submitRemoteConfiguration:modalities:createConversationOnSubmit:","kind":"identifier"}],"title":"submit(remoteConfig:modalities:createConversationOnSubmit:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"abstract":[{"text":"A protocol that defines the configuration information for an embedded service deployment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","title":"RemoteConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"submitRemoteConfiguration:modalities:createConversationOnSubmit:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"submitRemoteConfiguration:modalities:createConversationOnSubmit:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"submitRemoteConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMIRemoteConfiguration","kind":"typeIdentifier","text":"id<SMIRemoteConfiguration>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"remoteConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalities:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modalities"},{"kind":"text","text":" "},{"kind":"identifier","text":"createConversationOnSubmit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"createConversationOnSubmit"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The  "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"},{"type":"text","text":" to submit."}],"type":"paragraph"}],"name":"remoteConfig"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The starting modalities for this conversation. Currently only supports a single modality, API accepts an array for future functionality."}]}],"name":"modalities"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Determines if the conversation starts when the pre-chat data is submitted."}]}],"name":"createConversationOnSubmit"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"submitRemoteConfiguration:modalities:createConversationOnSubmit:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:modalities:createConversationOnSubmit:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitRemoteConfiguration:modalities:createConversationOnSubmit:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:modalities:createConversationOnSubmit:)\/fragments"},{"value":"SMIConversationClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","op":"replace","value":"SMIRemoteConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}]}]}]}