{"metadata":{"externalID":"c:objc(pl)SMICitationClaim(py)claimEndOffset","title":"claimEndOffset","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claimEndOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"claimEndOffset","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimEndOffset"},"abstract":[{"text":"The ending position of the citation in the text message.","type":"text"},{"text":" ","type":"text"},{"text":"This offset represents the index where the cited text ends in the message content.","type":"text"},{"text":" ","type":"text"},{"text":"The offset is exclusive, meaning it points to the character immediately after the last","type":"text"},{"text":" ","type":"text"},{"text":"character of the citation.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claimEndOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/citationclaim\/claimendoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citationclaim\/claimendoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitationClaim"}],"title":"CitationClaim","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitationClaim"}],"url":"\/documentation\/smiclientcore\/citationclaim","abstract":[{"text":"A protocol that represents the location of a citation within a text message.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim/claimEndOffset":{"abstract":[{"type":"text","text":"The ending position of the citation in the text message."},{"type":"text","text":" "},{"type":"text","text":"This offset represents the index where the cited text ends in the message content."},{"type":"text","text":" "},{"type":"text","text":"The offset is exclusive, meaning it points to the character immediately after the last"},{"type":"text","text":" "},{"type":"text","text":"character of the citation."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimEndOffset","title":"claimEndOffset","navigatorTitle":[{"text":"claimEndOffset","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/citationclaim\/claimendoffset","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claimEndOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"claimEndOffset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"claimEndOffset"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"claimEndOffset","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/title","value":"SMICitationClaim"},{"value":[{"kind":"identifier","text":"SMICitationClaim"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/fragments"},{"value":[{"kind":"identifier","text":"SMICitationClaim"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/navigatorTitle"},{"value":"claimEndOffset","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimEndOffset\/title"},{"value":[{"kind":"identifier","text":"claimEndOffset"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimEndOffset\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}