{"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged"]]},"abstract":[{"text":"An array of participant change operations.","type":"text"},{"text":" ","type":"text"},{"text":"Each operation in this array represents a single participant change, such as joining or leaving.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operations","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","preciseIdentifier":"c:objc(pl)SMIParticipantChangedOperation"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged\/operations","interfaceLanguage":"swift"},"metadata":{"title":"operations","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operations","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipantChangedOperation"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"operations","kind":"identifier"}],"required":true,"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIParticipantChanged(py)operations","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantchanged\/operations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantchanged\/operations"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChanged/operations":{"title":"operations","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operations","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipantChangedOperation"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"operations","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged\/operations","role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/participantchanged\/operations","abstract":[{"text":"An array of participant change operations.","type":"text"},{"text":" ","type":"text"},{"text":"Each operation in this array represents a single participant change, such as joining or leaving.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation":{"abstract":[{"text":"A protocol that represents an operation describing a change to a participant in a conversation.","type":"text"}],"title":"ParticipantChangedOperation","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperation","type":"topic","navigatorTitle":[{"text":"ParticipantChangedOperation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChanged":{"title":"ParticipantChanged","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChanged","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantchanged","role":"symbol","navigatorTitle":[{"text":"ParticipantChanged","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged","abstract":[{"type":"text","text":"A protocol that represents a participant change event within a conversation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"operations"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"operations","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIParticipantChangedOperation>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"operations"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged~1operations\/title","value":"operations","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged~1operations\/fragments","value":[{"text":"operations","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/title","value":"SMIParticipantChangedOperation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/title","value":"SMIParticipantChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChanged"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/navigatorTitle","value":[{"text":"SMIParticipantChanged","kind":"identifier"}],"op":"replace"}]}]}