{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":", ","kind":"text"},{"text":"didRequestPrechatValues","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"core:conversation:didRequestPrechatValues:completionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIHiddenPreChatDelegate(im)core:conversation:didRequestPrechatValues:completionHandler:","modules":[{"name":"SMIClientCore"}],"title":"core(_:conversation:didRequestPrechatValues:completionHandler:)","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"paths":["\/documentation\/smiclientcore\/hiddenprechatdelegate\/core(_:conversation:didrequestprechatvalues:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/hiddenprechatdelegate\/core(_:conversation:didrequestprechatvalues:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Delegate event that is triggered when submitting pre-chat data."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"core"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestPrechatValues"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping "},{"kind":"text","text":"([any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"core","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestPrechatValues"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields","kind":"internalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}],"name":"core"},{"content":[{"inlineContent":[{"text":"The current ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"conversation"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference"},{"text":" that require values.","type":"text"}]}],"name":"hiddenPreChatFields"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion","isActive":true,"type":"reference"},{"type":"text","text":" that provides the values for the expected hidden pre-chat fields."}]}],"name":"completionHandler"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate\/core(_:conversation:didRequestPrechatValues:completionHandler:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"abstract":[{"text":"A protocol that represents a hidden pre-chat field in the conversation configuration.","type":"text"}],"title":"HiddenPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatDelegate":{"abstract":[{"type":"text","text":"Delegate that handles requests for hidden pre-chat values."}],"navigatorTitle":[{"text":"HiddenPreChatDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate","title":"HiddenPreChatDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HiddenPreChatDelegate","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/hiddenprechatdelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatDelegate/core(_:conversation:didRequestPrechatValues:completionHandler:)":{"url":"\/documentation\/smiclientcore\/hiddenprechatdelegate\/core(_:conversation:didrequestprechatvalues:completionhandler:)","abstract":[{"type":"text","text":"Delegate event that is triggered when submitting pre-chat data."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate\/core(_:conversation:didRequestPrechatValues:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"core:conversation:didRequestPrechatValues:completionHandler:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":", ","kind":"text"},{"text":"didRequestPrechatValues","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"required":true,"type":"topic","title":"core(_:conversation:didRequestPrechatValues:completionHandler:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatValueCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion","title":"HiddenPreChatValueCompletion","navigatorTitle":[{"text":"HiddenPreChatValueCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Completion block for hidden pre-chat values."}],"type":"topic","url":"\/documentation\/smiclientcore\/hiddenprechatvaluecompletion","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HiddenPreChatValueCompletion","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"core:conversation:didRequestPrechatValues:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:conversation:didRequestPrechatValues:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"core:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMICoreClient>","preciseIdentifier":"c:Qoobjc(pl)SMICoreClient","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"core"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConversation","text":"id<SMIConversation>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"conversation"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestPrechatValues:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIHiddenPreChatField>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hiddenPreChatFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIHiddenPreChatDelegate.h@T@SMIHiddenPreChatValueCompletion","text":"SMIHiddenPreChatValueCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"core","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":" instance that is managing the current connection.","type":"text"}],"type":"paragraph"}]},{"name":"conversation","content":[{"type":"paragraph","inlineContent":[{"text":"The current ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},{"text":".","type":"text"}]}]},{"name":"hiddenPreChatFields","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","isActive":true},{"text":" that require values.","type":"text"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion","type":"reference"},{"text":" that provides the values for the expected hidden pre-chat fields.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SMIHiddenPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title"},{"value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments"},{"value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle"},{"value":"SMIHiddenPreChatDelegate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/title"},{"value":[{"kind":"identifier","text":"SMIHiddenPreChatDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SMIHiddenPreChatDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/navigatorTitle"},{"value":"SMICoreConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"value":"core:conversation:didRequestPrechatValues:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate~1core(_:conversation:didRequestPrechatValues:completionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"core:conversation:didRequestPrechatValues:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate~1core(_:conversation:didRequestPrechatValues:completionHandler:)\/fragments"},{"value":"SMICoreClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"value":"SMIConversation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"op":"replace","value":"SMIHiddenPreChatValueCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/fragments","value":[{"kind":"identifier","text":"SMIHiddenPreChatValueCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SMIHiddenPreChatValueCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace"}]}]}