{"variants":[{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/batchnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/batchnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)SMIComposedStreamingToken(py)batchNumber","role":"symbol","required":true,"title":"batchNumber","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"batchNumber"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/batchNumber","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The sequence number for related events within a turn."},{"type":"text","text":" "},{"type":"text","text":"Events with the same batch number are strongly associated and are delivered together."},{"type":"text","text":" "},{"type":"text","text":"Use this to identify and process groups of related events that should be handled"},{"type":"text","text":" "},{"type":"text","text":"as a single unit within a conversation turn."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"role":"symbol","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"title":"ComposedStreamingToken","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/batchNumber":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/batchNumber","abstract":[{"text":"The sequence number for related events within a turn.","type":"text"},{"text":" ","type":"text"},{"text":"Events with the same batch number are strongly associated and are delivered together.","type":"text"},{"text":" ","type":"text"},{"text":"Use this to identify and process groups of related events that should be handled","type":"text"},{"text":" ","type":"text"},{"text":"as a single unit within a conversation turn.","type":"text"}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/batchnumber","role":"symbol","navigatorTitle":[{"text":"batchNumber","kind":"identifier"}],"required":true,"title":"batchNumber","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"batchNumber","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"batchNumber","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SMIComposedStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle"},{"value":"batchNumber","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1batchNumber\/title"},{"value":[{"kind":"identifier","text":"batchNumber"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1batchNumber\/fragments"}]}]}