{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/derivedvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/derivedvalue"]}],"abstract":[{"type":"text","text":"The composed value derived from all current streaming tokens."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the current state of the composed content through"},{"type":"text","text":" "},{"type":"text","text":"the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","type":"reference","isActive":true},{"type":"text","text":" protocol, representing the accumulated result of all"},{"type":"text","text":" "},{"type":"text","text":"streaming tokens received so far."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"derivedValue"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"derivedValue"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"EntryFormat","preciseIdentifier":"c:objc(pl)SMIEntryFormat"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIComposedStreamingToken(py)derivedValue","roleHeading":"Instance Property","required":true,"symbolKind":"property","role":"symbol","title":"derivedValue"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"derivedValue","kind":"identifier"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","text":"EntryFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryFormat"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/derivedValue","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/derivedValue":{"navigatorTitle":[{"kind":"identifier","text":"derivedValue"}],"abstract":[{"type":"text","text":"The composed value derived from all current streaming tokens."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the current state of the composed content through"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","isActive":true},{"type":"text","text":" protocol, representing the accumulated result of all"},{"type":"text","text":" "},{"type":"text","text":"streaming tokens received so far."}],"required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken\/derivedvalue","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/derivedValue","title":"derivedValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"derivedValue"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"EntryFormat","preciseIdentifier":"c:objc(pl)SMIEntryFormat"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"kind":"symbol","url":"\/documentation\/smiclientcore\/entryformat","abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"EntryFormat","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormat","kind":"identifier"}],"title":"EntryFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"url":"\/documentation\/smiclientcore\/composedstreamingtoken","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","title":"ComposedStreamingToken","type":"topic","kind":"symbol","abstract":[{"text":"A protocol that represents a conversation entry composed of multiple streaming tokens.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"derivedValue","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"derivedValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIEntryFormat>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIEntryFormat"},{"text":" ","kind":"text"},{"text":"derivedValue","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"derivedValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1derivedValue\/title"},{"value":[{"kind":"identifier","text":"derivedValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1derivedValue\/fragments"},{"value":"SMIEntryFormat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title"},{"value":[{"text":"SMIEntryFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments"},{"value":[{"text":"SMIEntryFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle"},{"value":"SMIComposedStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title"},{"value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments"},{"value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle"}]}]}