{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/relatedStreamingTokens","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The ordered list of all streaming tokens associated with this entry."},{"type":"text","text":" "},{"type":"text","text":"This array contains all "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"},{"type":"text","text":" objects that have been received"},{"type":"text","text":" "},{"type":"text","text":"for this entry, maintained in their sequential order of arrival."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"relatedStreamingTokens"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIMessageStreamingToken","kind":"typeIdentifier","text":"MessageStreamingToken","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"relatedStreamingTokens","externalID":"c:objc(pl)SMIComposedStreamingToken(py)relatedStreamingTokens","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"relatedStreamingTokens"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"relatedStreamingTokens"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIMessageStreamingToken","kind":"typeIdentifier","text":"MessageStreamingToken"},{"kind":"text","text":"]"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/relatedstreamingtokens"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/relatedstreamingtokens"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/relatedStreamingTokens":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/relatedStreamingTokens","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relatedStreamingTokens","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIMessageStreamingToken","text":"MessageStreamingToken","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"relatedStreamingTokens","type":"topic","navigatorTitle":[{"text":"relatedStreamingTokens","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The ordered list of all streaming tokens associated with this entry."},{"type":"text","text":" "},{"type":"text","text":"This array contains all "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","isActive":true},{"type":"text","text":" objects that have been received"},{"type":"text","text":" "},{"type":"text","text":"for this entry, maintained in their sequential order of arrival."}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/relatedstreamingtokens"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"kind":"symbol","title":"ComposedStreamingToken","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComposedStreamingToken"}],"role":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken","abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComposedStreamingToken"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"type":"topic","title":"MessageStreamingToken","role":"symbol","navigatorTitle":[{"text":"MessageStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageStreamingToken","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"relatedStreamingTokens"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"relatedStreamingTokens"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIMessageStreamingToken>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"relatedStreamingTokens","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1relatedStreamingTokens\/title","value":"relatedStreamingTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1relatedStreamingTokens\/fragments","value":[{"text":"relatedStreamingTokens","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","value":"SMIComposedStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title","value":"SMIMessageStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageStreamingToken"}]}]}]}