{"variants":[{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/tokentype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/tokentype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/tokenType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","kind":"typeIdentifier","text":"StreamingTokenTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The type of streaming token being used."},{"type":"text","text":" "},{"type":"text","text":"This property indicates the type of streaming token through the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"enum, which helps determine how the token should be processed and displayed."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"metadata":{"symbolKind":"property","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tokenType"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"externalID":"c:objc(pl)SMIComposedStreamingToken(py)tokenType","title":"tokenType","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/tokenType":{"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/tokentype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/tokenType","abstract":[{"type":"text","text":"The type of streaming token being used."},{"type":"text","text":" "},{"type":"text","text":"This property indicates the type of streaming token through the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","isActive":true,"type":"reference"},{"type":"text","text":" "},{"type":"text","text":"enum, which helps determine how the token should be processed and displayed."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tokenType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"StreamingTokenTypes"}],"required":true,"type":"topic","title":"tokenType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"role":"symbol","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"title":"ComposedStreamingToken","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"tokenType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"tokenType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"SMIStreamingTokenTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"tokenType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIStreamingTokenTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title"},{"value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle"},{"value":"tokenType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1tokenType\/title"},{"value":[{"kind":"identifier","text":"tokenType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1tokenType\/fragments"},{"value":"SMIComposedStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title"},{"value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments"},{"value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle"}]}]}