{"variants":[{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/turnid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/turnid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The unique identifier for the current conversation turn."},{"type":"text","text":" "},{"type":"text","text":"This identifier correlates all events and responses within a single interaction between"},{"type":"text","text":" "},{"type":"text","text":"the user and agent. Use this to track and group related messages and events that occur"},{"type":"text","text":" "},{"type":"text","text":"within the same conversation turn."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"metadata":{"title":"turnId","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIComposedStreamingToken(py)turnId","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"turnId","kind":"identifier"}],"required":true,"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/turnId","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"type":"topic","abstract":[{"text":"A protocol that represents a conversation entry composed of multiple streaming tokens.","type":"text"}],"kind":"symbol","title":"ComposedStreamingToken","url":"\/documentation\/smiclientcore\/composedstreamingtoken","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/turnId":{"type":"topic","role":"symbol","title":"turnId","url":"\/documentation\/smiclientcore\/composedstreamingtoken\/turnid","navigatorTitle":[{"text":"turnId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier for the current conversation turn."},{"type":"text","text":" "},{"type":"text","text":"This identifier correlates all events and responses within a single interaction between"},{"type":"text","text":" "},{"type":"text","text":"the user and agent. Use this to track and group related messages and events that occur"},{"type":"text","text":" "},{"type":"text","text":"within the same conversation turn."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/turnId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"turnId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"turnId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"turnId"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","op":"replace","value":"SMIComposedStreamingToken"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1turnId\/title","value":"turnId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1turnId\/fragments","value":[{"kind":"identifier","text":"turnId"}]}]}]}