{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"StreamingTokenValidation","preciseIdentifier":"c:objc(pl)SMIStreamingTokenValidation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"That validation tokens may not be sent if the content has been accepted as final.","type":"text"}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/validation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/composedstreamingtoken\/validation"]}],"sections":[],"abstract":[{"text":"The validation status for this composed token.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to validation information through the","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","isActive":true,"type":"reference"},{"text":" protocol. When ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current stream of tokens","type":"text"},{"text":" ","type":"text"},{"text":"should be considered valid.","type":"text"},{"text":" ","type":"text"},{"text":"If present and its ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","isActive":true,"type":"reference"},{"text":" property is ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":", the content","type":"text"},{"text":" ","type":"text"},{"text":"should be considered to have been discarded and will be replaced.","type":"text"}],"metadata":{"required":true,"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIStreamingTokenValidation","text":"StreamingTokenValidation"},{"kind":"text","text":")?"}],"title":"validation","externalID":"c:objc(pl)SMIComposedStreamingToken(py)validation","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"validation"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/validation","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"url":"\/documentation\/smiclientcore\/composedstreamingtoken","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","title":"ComposedStreamingToken","type":"topic","kind":"symbol","abstract":[{"text":"A protocol that represents a conversation entry composed of multiple streaming tokens.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/valid":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","required":true,"navigatorTitle":[{"text":"valid","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The validation status of the composed token."},{"type":"text","text":" "},{"type":"text","text":"This property indicates whether the content of the stream has been validated as"},{"type":"text","text":" "},{"type":"text","text":"acceptable. When "},{"type":"codeVoice","code":"NO"},{"type":"text","text":", the content should be considered invalid and may be"},{"type":"text","text":" "},{"type":"text","text":"discarded or replaced."}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/valid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"valid"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"role":"symbol","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","title":"StreamingTokenValidation","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/validation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIStreamingTokenValidation","text":"StreamingTokenValidation"},{"kind":"text","text":")?"}],"abstract":[{"text":"The validation status for this composed token.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to validation information through the","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","isActive":true,"type":"reference"},{"text":" protocol. When ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current stream of tokens","type":"text"},{"text":" ","type":"text"},{"text":"should be considered valid.","type":"text"},{"text":" ","type":"text"},{"text":"If present and its ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","isActive":true,"type":"reference"},{"text":" property is ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":", the content","type":"text"},{"text":" ","type":"text"},{"text":"should be considered to have been discarded and will be replaced.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/validation","title":"validation","url":"\/documentation\/smiclientcore\/composedstreamingtoken\/validation","role":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"validation"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"validation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"validation","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIStreamingTokenValidation","text":"id<SMIStreamingTokenValidation>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","op":"replace","value":"SMIComposedStreamingToken"},{"value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments"},{"value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/title","value":"valid","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/fragments","value":[{"kind":"identifier","text":"valid"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title","value":"SMIStreamingTokenValidation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1validation\/title","value":"validation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1validation\/fragments","value":[{"text":"validation","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}