{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/reason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/reason"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The reason for invalidation, if applicable.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a detailed explanation of why the content was","type":"text"},{"text":" ","type":"text"},{"text":"considered invalid. Note that this property is intended for debugging and","type":"text"},{"text":" ","type":"text"},{"text":"traceability purposes only and should not be displayed to end users.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/reason","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"reason","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reason"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIStreamingTokenValidation(py)reason"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"navigatorTitle":[{"kind":"identifier","text":"StreamingTokenValidation"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that represents a validation event for a streamed message."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","title":"StreamingTokenValidation","kind":"symbol","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenValidation"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/reason":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/reason","kind":"symbol","title":"reason","role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/reason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The reason for invalidation, if applicable.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a detailed explanation of why the content was","type":"text"},{"text":" ","type":"text"},{"text":"considered invalid. Note that this property is intended for debugging and","type":"text"},{"text":" ","type":"text"},{"text":"traceability purposes only and should not be displayed to end users.","type":"text"}],"required":true,"navigatorTitle":[{"text":"reason","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"reason","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SMIStreamingTokenValidation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title"},{"op":"replace","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle"},{"value":"reason","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1reason\/title"},{"value":[{"text":"reason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1reason\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}