{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"]]},"abstract":[{"text":"The identifier that will be used for the final transcribed entry.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a unique identifier that links this validation token to its","type":"text"},{"text":" ","type":"text"},{"text":"corresponding ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","isActive":true,"type":"reference"},{"text":", allowing the validation status to be","type":"text"},{"text":" ","type":"text"},{"text":"associated with the correct message stream.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/targetMessageIdentifier","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"targetMessageIdentifier","kind":"identifier"}],"title":"targetMessageIdentifier","required":true,"externalID":"c:objc(pl)SMIStreamingTokenValidation(py)targetMessageIdentifier","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"targetMessageIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/targetmessageidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/targetmessageidentifier"]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"type":"topic","abstract":[{"text":"A protocol that represents a conversation entry composed of multiple streaming tokens.","type":"text"}],"kind":"symbol","title":"ComposedStreamingToken","url":"\/documentation\/smiclientcore\/composedstreamingtoken","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/targetMessageIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"targetMessageIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/targetMessageIdentifier","title":"targetMessageIdentifier","url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/targetmessageidentifier","role":"symbol","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[{"text":"The identifier that will be used for the final transcribed entry.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a unique identifier that links this validation token to its","type":"text"},{"text":" ","type":"text"},{"text":"corresponding ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","isActive":true,"type":"reference"},{"text":", allowing the validation status to be","type":"text"},{"text":" ","type":"text"},{"text":"associated with the correct message stream.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"kind":"symbol","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}],"title":"StreamingTokenValidation","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"targetMessageIdentifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"targetMessageIdentifier","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SMIComposedStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","op":"replace"},{"value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","op":"replace"},{"value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","op":"replace"},{"value":"targetMessageIdentifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1targetMessageIdentifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"targetMessageIdentifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1targetMessageIdentifier\/fragments","op":"replace"},{"value":"SMIStreamingTokenValidation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title","op":"replace"},{"value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments","op":"replace"},{"value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle","op":"replace"}]}]}