{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/turnId"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"]]},"abstract":[{"type":"text","text":"The unique identifier for the current conversation turn."},{"type":"text","text":" "},{"type":"text","text":"This identifier correlates all events and responses within a single interaction between"},{"type":"text","text":" "},{"type":"text","text":"the user and agent. Use this to track and group related messages and events that occur"},{"type":"text","text":" "},{"type":"text","text":"within the same conversation turn."}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"title":"turnId","role":"symbol","required":true,"externalID":"c:objc(pl)SMIStreamingTokenValidation(py)turnId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"turnId"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/turnid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation\/turnid"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/turnId":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/turnId","required":true,"abstract":[{"type":"text","text":"The unique identifier for the current conversation turn."},{"type":"text","text":" "},{"type":"text","text":"This identifier correlates all events and responses within a single interaction between"},{"type":"text","text":" "},{"type":"text","text":"the user and agent. Use this to track and group related messages and events that occur"},{"type":"text","text":" "},{"type":"text","text":"within the same conversation turn."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnId"}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/turnid","kind":"symbol","title":"turnId"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","type":"topic","title":"StreamingTokenValidation","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"turnId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"turnId"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1turnId\/title","value":"turnId","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1turnId\/fragments","value":[{"kind":"identifier","text":"turnId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title","value":"SMIStreamingTokenValidation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"op":"replace"}]}]}