{"metadata":{"title":"AuthorizationTypes.JWT","role":"symbol","externalID":"c:@E@SMIAuthorizationTypes@SMIAuthorizationTypesJWT","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWT","kind":"identifier"}],"navigatorTitle":[{"text":"SMIAuthorizationTypesJWT","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SMIClientCore"}]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/JWT","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"JWT-based user verification."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWT"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/jwt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/jwt"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/JWT":{"url":"\/documentation\/smiclientcore\/authorizationtypes\/jwt","title":"AuthorizationTypes.JWT","role":"symbol","abstract":[{"text":"JWT-based user verification.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/JWT","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWT","kind":"identifier"}],"navigatorTitle":[{"text":"SMIAuthorizationTypesJWT","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/authorizationtypes","abstract":[{"text":"An enum that defines the types of authorization for API requests.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","title":"AuthorizationTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIAuthorizationTypesJWT"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAuthorizationTypesJWT"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SMIAuthorizationTypesJWT"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1JWT\/title","value":"SMIAuthorizationTypesJWT","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1JWT\/fragments","value":[{"kind":"identifier","text":"SMIAuthorizationTypesJWT"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title","value":"SMIAuthorizationTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAuthorizationTypes"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}