{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"SMIClientCore"}],"externalID":"c:@E@SMIAuthorizationTypes@SMIAuthorizationTypesPassthrough","roleHeading":"Case","title":"AuthorizationTypes.passthrough","navigatorTitle":[{"text":"SMIAuthorizationTypesPassthrough","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passthrough","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"]]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/passthrough","interfaceLanguage":"swift"},"abstract":[{"text":"Allows for passthrough of MIAW issued jwts directly into the SDK authorization flow.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to handle authorization with the MIAW separately within your application or authentication processes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passthrough"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/passthrough"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/passthrough"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","url":"\/documentation\/smiclientcore\/authorizationtypes","navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}],"title":"AuthorizationTypes","abstract":[{"type":"text","text":"An enum that defines the types of authorization for API requests."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/passthrough":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passthrough","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/authorizationtypes\/passthrough","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/passthrough","role":"symbol","type":"topic","title":"AuthorizationTypes.passthrough","navigatorTitle":[{"text":"SMIAuthorizationTypesPassthrough","kind":"identifier"}],"abstract":[{"type":"text","text":"Allows for passthrough of MIAW issued jwts directly into the SDK authorization flow."},{"type":"text","text":" "},{"type":"text","text":"This can be used to handle authorization with the MIAW separately within your application or authentication processes."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIAuthorizationTypesPassthrough","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIAuthorizationTypesPassthrough","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIAuthorizationTypesPassthrough","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAuthorizationTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title"},{"value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments"},{"value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle"},{"value":"SMIAuthorizationTypesPassthrough","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1passthrough\/title"},{"value":[{"kind":"identifier","text":"SMIAuthorizationTypesPassthrough"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1passthrough\/fragments"}]}]}