{"sections":[],"abstract":[{"text":"Unauthenticated.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/unauthenticated"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthenticated"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/unauthenticated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/authorizationtypes\/unauthenticated"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SMIAuthorizationTypesUnauthenticated","kind":"identifier"}],"externalID":"c:@E@SMIAuthorizationTypes@SMIAuthorizationTypesUnauthenticated","symbolKind":"case","title":"AuthorizationTypes.unauthenticated","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unauthenticated","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the types of authorization for API requests.","type":"text"}],"navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/authorizationtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","title":"AuthorizationTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/unauthenticated":{"url":"\/documentation\/smiclientcore\/authorizationtypes\/unauthenticated","abstract":[{"text":"Unauthenticated.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/unauthenticated","role":"symbol","navigatorTitle":[{"text":"SMIAuthorizationTypesUnauthenticated","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unauthenticated","kind":"identifier"}],"type":"topic","title":"AuthorizationTypes.unauthenticated"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIAuthorizationTypesUnauthenticated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIAuthorizationTypesUnauthenticated","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIAuthorizationTypesUnauthenticated"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title","op":"replace","value":"SMIAuthorizationTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAuthorizationTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1unauthenticated\/title","op":"replace","value":"SMIAuthorizationTypesUnauthenticated"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1unauthenticated\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAuthorizationTypesUnauthenticated"}]}]}]}