{"metadata":{"role":"symbol","externalID":"c:objc(pl)SMIConversationEntry(py)format","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","title":"format","required":true,"navigatorTitle":[{"text":"format","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry\/format","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"],"title":"Related Documentation","anchor":"Related-Documentation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentry\/format"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentry\/format"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"]]},"sections":[],"abstract":[{"type":"text","text":"The format of the entry’s payload."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes","title":"ConversationFormatTypes","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ConversationFormatTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","abstract":[{"text":"An enum that defines the possible formats for messages and content in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry/format":{"required":true,"title":"format","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry\/format","abstract":[{"type":"text","text":"The format of the entry’s payload."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"format"}],"url":"\/documentation\/smiclientcore\/conversationentry\/format","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier","text":"ConversationFormatTypes"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"format"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"format","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMIConversationFormatTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title","op":"replace","value":"SMIConversationFormatTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry~1format\/title","op":"replace","value":"format"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry~1format\/fragments","op":"replace","value":[{"text":"format","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}