{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry\/payload"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Serializable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SMISerializable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"},{"text":" & ","kind":"text"},{"text":"EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The payload associated with this conversation entry.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"title":"Related Documentation","anchor":"Related-Documentation"}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentry\/payload"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentry\/payload"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:objc(pl)SMIConversationEntry(py)payload","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Serializable","preciseIdentifier":"c:objc(cs)SMISerializable","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","kind":"typeIdentifier"}],"title":"payload","required":true,"navigatorTitle":[{"text":"payload","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"abstract":[{"type":"text","text":"Common interface for the content of a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"title":"EntryPayload","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Serializable":{"navigatorTitle":[{"text":"Serializable","kind":"identifier"}],"abstract":[{"text":"Base class for JSON serializable objects used with network communication for In-App Messaging.","type":"text"}],"type":"topic","kind":"symbol","title":"Serializable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","url":"\/documentation\/smiclientcore\/serializable","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry/payload":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payload"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Serializable","preciseIdentifier":"c:objc(cs)SMISerializable"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"}],"kind":"symbol","title":"payload","url":"\/documentation\/smiclientcore\/conversationentry\/payload","abstract":[{"text":"The payload associated with this conversation entry.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry\/payload","navigatorTitle":[{"kind":"identifier","text":"payload"}],"type":"topic","role":"symbol","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"payload","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"payload"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"anchor":"Related-Documentation"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMISerializable<SMIEntryPayload>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)SMISerializableobjc(pl)SMIEntryPayload"},{"text":" * ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/title","value":"SMISerializable","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/fragments","value":[{"kind":"identifier","text":"SMISerializable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/navigatorTitle","value":[{"text":"SMISerializable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry~1payload\/title","value":"payload","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry~1payload\/fragments","value":[{"kind":"identifier","text":"payload"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}