{"kind":"symbol","abstract":[{"text":"The list of objects representing successful submission of the form.","type":"text"},{"text":" ","type":"text"},{"text":"This array contains the records that were created or updated as a result of the","type":"text"},{"text":" ","type":"text"},{"text":"form submission. Each record includes details about the changes made.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult\/records"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult"],"anchor":"Related-Documentation"}],"metadata":{"externalID":"c:objc(pl)SMIFormRecordsResult(py)records","role":"symbol","navigatorTitle":[{"text":"records","kind":"identifier"}],"required":true,"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"records","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormRecordResult","preciseIdentifier":"c:objc(pl)SMIFormRecordResult","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"property","title":"records","modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"records","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormRecordResult","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","preciseIdentifier":"c:objc(pl)SMIFormRecordResult"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formrecordsresult\/records"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formrecordsresult\/records"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordsResult/records":{"abstract":[{"type":"text","text":"The list of objects representing successful submission of the form."},{"type":"text","text":" "},{"type":"text","text":"This array contains the records that were created or updated as a result of the"},{"type":"text","text":" "},{"type":"text","text":"form submission. Each record includes details about the changes made."}],"navigatorTitle":[{"text":"records","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formrecordsresult\/records","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult\/records","required":true,"title":"records","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"records","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormRecordResult","preciseIdentifier":"c:objc(pl)SMIFormRecordResult","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"FormRecordResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","url":"\/documentation\/smiclientcore\/formrecordresult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordResult","kind":"identifier"}],"title":"FormRecordResult","abstract":[{"text":"A protocol that represents a record that has been created or updated as a result of a form submission.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordsResult":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordsResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A protocol that represents a successful form submission with created or updated records.","type":"text"}],"url":"\/documentation\/smiclientcore\/formrecordsresult","navigatorTitle":[{"text":"FormRecordsResult","kind":"identifier"}],"title":"FormRecordsResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"records","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"records","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIFormRecordResult>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"records","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult~1records\/title","value":"records","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult~1records\/fragments","value":[{"kind":"identifier","text":"records"}],"op":"replace"},{"op":"replace","value":"SMIFormRecordResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormRecordResult"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormRecordResult"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/navigatorTitle"},{"op":"replace","value":"SMIFormRecordsResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/title"},{"op":"replace","value":[{"text":"SMIFormRecordsResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/fragments"},{"op":"replace","value":[{"text":"SMIFormRecordsResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/navigatorTitle"}]}]}