{"sections":[],"abstract":[{"type":"text","text":"The floating-point value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the decimal number entered by the user, stored as a "},{"type":"codeVoice","code":"CGFloat"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The value can represent any real number, including fractional values."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue\/doubleValue"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValue"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsedoublevalue\/doublevalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsedoublevalue\/doublevalue"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"introducedAt":"2.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"2.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"2.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false}],"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIFormResponseDoubleValue(py)doubleValue","symbolKind":"property","title":"doubleValue","navigatorTitle":[{"kind":"identifier","text":"doubleValue"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDoubleValue":{"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a floating-point number."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseDoubleValue"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","title":"FormResponseDoubleValue","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDoubleValue"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsedoublevalue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDoubleValue/doubleValue":{"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formresponsedoublevalue\/doublevalue","role":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue\/doubleValue","title":"doubleValue","navigatorTitle":[{"kind":"identifier","text":"doubleValue"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"text":"The floating-point value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the decimal number entered by the user, stored as a ","type":"text"},{"code":"CGFloat","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The value can represent any real number, including fractional values.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"doubleValue","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"doubleValue"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValue"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/title","op":"replace","value":"SMIFormResponseDoubleValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseDoubleValue"}]},{"value":[{"kind":"identifier","text":"SMIFormResponseDoubleValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue~1doubleValue\/title","value":"doubleValue"},{"value":[{"text":"doubleValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue~1doubleValue\/fragments","op":"replace"}]}]}