{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textInputType"},"abstract":[{"type":"text","text":"The type of text expected for this input."},{"type":"text","text":" "},{"type":"text","text":"This property determines whether the input accepts single-line or multi-line text."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","isActive":true},{"type":"text","text":" for available text input types."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtextinput\/textinputtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtextinput\/textinputtype"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","text":"FormTextInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"textInputType","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"textInputType","roleHeading":"Instance Property","required":true,"symbolKind":"property","externalID":"c:objc(pl)SMIFormTextInput(py)textInputType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"},{"text":"?","kind":"text"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/textInputType":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The type of text expected for this input."},{"text":" ","type":"text"},{"type":"text","text":"This property determines whether the input accepts single-line or multi-line text."},{"type":"text","text":" "},{"text":"See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"},{"type":"text","text":" for available text input types."}],"navigatorTitle":[{"kind":"identifier","text":"textInputType"}],"url":"\/documentation\/smiclientcore\/formtextinput\/textinputtype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textInputType","title":"textInputType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType":{"url":"\/documentation\/smiclientcore\/formtextinputtype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormTextInputType"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An enum that defines the types of text input fields available in forms."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}],"title":"FormTextInputType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FormTextInput","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formtextinput","title":"FormTextInput","role":"symbol","navigatorTitle":[{"text":"FormTextInput","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a text input field in a form that supports various text input types and validation.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textInputType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textInputType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","kind":"typeIdentifier","text":"SMIFormTextInputType"},{"kind":"text","text":" "},{"kind":"identifier","text":"textInputType"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textInputType\/title","value":"textInputType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textInputType\/fragments","value":[{"kind":"identifier","text":"textInputType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/title","value":"SMIFormTextInputType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/fragments","value":[{"kind":"identifier","text":"SMIFormTextInputType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/navigatorTitle","value":[{"text":"SMIFormTextInputType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/title","value":"SMIFormTextInput"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTextInput"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTextInput"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/navigatorTitle"}]}]}