{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtextinput\/textcontenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtextinput\/textcontenttype"]}],"abstract":[{"text":"The content type for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property helps the system provide appropriate keyboard and validation for specific","type":"text"},{"text":" ","type":"text"},{"text":"types of content, such as email addresses or URLs.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextContentType","kind":"typeIdentifier","preciseIdentifier":"c:@T@UITextContentType"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textContentType"},"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormTextInput(py)textContentType","title":"textContentType","role":"symbol","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UITextContentType","text":"UITextContentType","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"textContentType","kind":"identifier"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput":{"url":"\/documentation\/smiclientcore\/formtextinput","title":"FormTextInput","navigatorTitle":[{"text":"FormTextInput","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTextInput","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a text input field in a form that supports various text input types and validation.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/textContentType":{"navigatorTitle":[{"text":"textContentType","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"textContentType","url":"\/documentation\/smiclientcore\/formtextinput\/textcontenttype","abstract":[{"text":"The content type for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property helps the system provide appropriate keyboard and validation for specific","type":"text"},{"text":" ","type":"text"},{"text":"types of content, such as email addresses or URLs.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textContentType","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITextContentType","preciseIdentifier":"c:@T@UITextContentType","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textContentType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textContentType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textContentType"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/title","value":"SMIFormTextInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/fragments","value":[{"kind":"identifier","text":"SMIFormTextInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTextInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textContentType\/title","value":"textContentType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textContentType\/fragments","value":[{"text":"textContentType","kind":"identifier"}]}]}]}