{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationupdated\/updatedby"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationupdated\/updatedby"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated\/updatedBy","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"updatedBy","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedBy"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant","text":"Participant"}],"navigatorTitle":[{"kind":"identifier","text":"updatedBy"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIConversationUpdated(py)updatedBy"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedBy"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","text":"Participant","preciseIdentifier":"c:objc(pl)SMIParticipant"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdated/updatedBy":{"abstract":[],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated\/updatedBy","navigatorTitle":[{"text":"updatedBy","kind":"identifier"}],"title":"updatedBy","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatedBy"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant","text":"Participant"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationupdated\/updatedby"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/participant","role":"symbol","navigatorTitle":[{"text":"Participant","kind":"identifier"}],"title":"Participant","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdated":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUpdated","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ConversationUpdated","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationupdated","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated","title":"ConversationUpdated"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"updatedBy","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"updatedBy","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIParticipant>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIParticipant"},{"text":" ","kind":"text"},{"text":"updatedBy","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated~1updatedBy\/title","value":"updatedBy"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated~1updatedBy\/fragments","value":[{"kind":"identifier","text":"updatedBy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title","value":"SMIParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments","value":[{"kind":"identifier","text":"SMIParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/title","value":"SMIConversationUpdated"},{"value":[{"text":"SMIConversationUpdated","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationUpdated"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/navigatorTitle"}]}]}