{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updates","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ConversationUpdateOperation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationUpdateOperation"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"updates","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIConversationUpdated(py)updates","modules":[{"name":"SMIClientCore"}],"title":"updates","roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationupdated\/updates"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationupdated\/updates"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updates"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","preciseIdentifier":"c:objc(pl)SMIConversationUpdateOperation","text":"ConversationUpdateOperation"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated\/updates","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdated/updates":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updates"},{"text":": [any ","kind":"text"},{"text":"ConversationUpdateOperation","preciseIdentifier":"c:objc(pl)SMIConversationUpdateOperation","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"updates","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationupdated\/updates","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated\/updates","title":"updates"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateOperation":{"url":"\/documentation\/smiclientcore\/conversationupdateoperation","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","role":"symbol","navigatorTitle":[{"text":"ConversationUpdateOperation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUpdateOperation","kind":"identifier"}],"type":"topic","title":"ConversationUpdateOperation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdated":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUpdated","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ConversationUpdated","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationupdated","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdated","title":"ConversationUpdated"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"updates","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"updates"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIConversationUpdateOperation>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"updates"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"updates","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated~1updates\/title"},{"op":"replace","value":[{"text":"updates","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated~1updates\/fragments"},{"op":"replace","value":"SMIConversationUpdateOperation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationUpdateOperation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/fragments"},{"op":"replace","value":[{"text":"SMIConversationUpdateOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/navigatorTitle"},{"value":"SMIConversationUpdated","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationUpdated"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdated\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationUpdated"}]}]}]}