{"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","isActive":true},{"type":"text","text":" with the specified credentials, which is used to pass in user verification credentials."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithJWT:lastEventId:","kind":"identifier"}],"title":"init(jwt:lastEventId:)","externalID":"c:objc(cs)SMIPassthroughVerification(im)initWithJWT:lastEventId:","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"JWT","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"JWT","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid MIAW authorized JWT to use for all network operations."}]}]},{"name":"lastEventId","content":[{"inlineContent":[{"type":"text","text":"This represents the last event which has been pulled down by the client on the persistent SSE connection."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/init(jwt:lastEventId:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"init(jwt:lastEventId:)","kind":"symbol","url":"\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)","navigatorTitle":[{"kind":"identifier","text":"initWithJWT:lastEventId:"}],"type":"topic","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","isActive":true},{"type":"text","text":" with the specified credentials, which is used to pass in user verification credentials."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"type":"topic","title":"PassthroughVerification","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}],"url":"\/documentation\/smiclientcore\/passthroughverification"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithJWT:lastEventId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithJWT:lastEventId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithJWT:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"JWT","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"lastEventId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lastEventId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"JWT","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid MIAW authorized JWT to use for all network operations."}]}]},{"name":"lastEventId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This represents the last event which has been pulled down by the client on the persistent SSE connection."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)\/title","op":"replace","value":"initWithJWT:lastEventId:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJWT:lastEventId:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title","op":"replace","value":"SMIPassthroughVerification"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]}]}]}