{"kind":"symbol","sections":[],"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithJWT:lastEventId:","kind":"identifier"}],"title":"init(jwt:lastEventId:)","externalID":"c:objc(cs)SMIPassthroughVerification(im)initWithJWT:lastEventId:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)-2r9jf","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"},{"text":" with the specified credentials, which is used to pass in user verification credentials.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"JWT","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"JWT","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid MIAW authorized JWT to use for all network operations."}]}]},{"name":"lastEventId","content":[{"type":"paragraph","inlineContent":[{"text":"This represents the last event which has been pulled down by the client on the persistent SSE connection.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-2r9jf"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-2r9jf"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","type":"topic","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}],"url":"\/documentation\/smiclientcore\/passthroughverification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"role":"symbol","title":"PassthroughVerification"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/init(jwt:lastEventId:)-2r9jf":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)-2r9jf","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJWT:lastEventId:"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-2r9jf","type":"topic","title":"init(jwt:lastEventId:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","isActive":true,"type":"reference"},{"text":" with the specified credentials, which is used to pass in user verification credentials.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithJWT:lastEventId:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJWT:lastEventId:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithJWT:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"JWT","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"lastEventId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lastEventId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"JWT","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid MIAW authorized JWT to use for all network operations."}]}]},{"name":"lastEventId","content":[{"inlineContent":[{"type":"text","text":"This represents the last event which has been pulled down by the client on the persistent SSE connection."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title","op":"replace","value":"SMIPassthroughVerification"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle","op":"replace","value":[{"text":"SMIPassthroughVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)-2r9jf\/title","op":"replace","value":"initWithJWT:lastEventId:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)-2r9jf\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJWT:lastEventId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}