{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"JWT","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"init(JWT:lastEventId:)","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JWT","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","platforms":[],"role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SMIPassthroughVerification(im)initWithJWT:lastEventId:::SYNTHESIZED::c:objc(cs)SMIPassthroughVerification"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(JWT:lastEventId:)-1xsjy"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-1xsjy"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PassthroughVerification.init(JWT:lastEventId:)"},{"type":"text","text":"."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/init(JWT:lastEventId:)-1xsjy":{"title":"init(JWT:lastEventId:)","abstract":[],"url":"\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-1xsjy","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JWT","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lastEventId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(JWT:lastEventId:)-1xsjy","kind":"symbol","role":"symbol","deprecated":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"type":"topic","title":"PassthroughVerification","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}],"url":"\/documentation\/smiclientcore\/passthroughverification"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIPassthroughVerification","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title"},{"value":[{"text":"SMIPassthroughVerification","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments"},{"value":[{"text":"SMIPassthroughVerification","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle"}]}]}