{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastEventId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"content":[{"inlineContent":[{"text":"If you are unsure of what the lastEventId should be you can pass in “0”. However passing in a value that’s too high could result in","type":"text"},{"text":" ","type":"text"},{"text":"missing messages. Preferably you would pass in the value retrieved when retrieving the ","type":"text"},{"code":"JWT","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"}],"kind":"content"}],"abstract":[{"text":"The lastEventId represents the latest event which has been retrieved by a given authorized user.","type":"text"},{"text":" ","type":"text"},{"text":"When retrieving a MIAW JWT the lastEventId is also provided in the response.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/lastEventId"},"metadata":{"externalID":"c:objc(cs)SMIPassthroughVerification(py)lastEventId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastEventId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"lastEventId","kind":"identifier"}],"symbolKind":"property","title":"lastEventId","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/passthroughverification\/lasteventid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/passthroughverification\/lasteventid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"url":"\/documentation\/smiclientcore\/passthroughverification","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","type":"topic","title":"PassthroughVerification","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/lastEventId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/lastEventId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastEventId"}],"title":"lastEventId","url":"\/documentation\/smiclientcore\/passthroughverification\/lasteventid","type":"topic","role":"symbol","abstract":[{"text":"The lastEventId represents the latest event which has been retrieved by a given authorized user.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When retrieving a MIAW JWT the lastEventId is also provided in the response."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"lastEventId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"lastEventId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"lastEventId","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIPassthroughVerification","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments"},{"op":"replace","value":[{"text":"SMIPassthroughVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle"},{"op":"replace","value":"lastEventId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1lastEventId\/title"},{"op":"replace","value":[{"text":"lastEventId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1lastEventId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}