{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citations"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","preciseIdentifier":"c:objc(pl)SMICitation","text":"Citation"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"abstract":[{"text":"The array of citations associated with this message.","type":"text"},{"text":" ","type":"text"},{"text":"Each citation in the array conforms to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","type":"reference"},{"text":" protocol and contains","type":"text"},{"text":" ","type":"text"},{"text":"information about a specific reference, including its location in the message and","type":"text"},{"text":" ","type":"text"},{"text":"any associated reference details.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent\/citations"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citations"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"Citation","preciseIdentifier":"c:objc(pl)SMICitation"},{"kind":"text","text":"]"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"citations"}],"role":"symbol","required":true,"externalID":"c:objc(pl)SMICitationContent(py)citations","title":"citations"},"variants":[{"paths":["\/documentation\/smiclientcore\/citationcontent\/citations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citationcontent\/citations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationContent/citations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent\/citations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citations"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"Citation","preciseIdentifier":"c:objc(pl)SMICitation"},{"kind":"text","text":"]"}],"url":"\/documentation\/smiclientcore\/citationcontent\/citations","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"citations"}],"role":"symbol","required":true,"abstract":[{"type":"text","text":"The array of citations associated with this message."},{"type":"text","text":" "},{"type":"text","text":"Each citation in the array conforms to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"},{"type":"text","text":" protocol and contains"},{"type":"text","text":" "},{"type":"text","text":"information about a specific reference, including its location in the message and"},{"type":"text","text":" "},{"type":"text","text":"any associated reference details."}],"title":"citations","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation":{"abstract":[{"type":"text","text":"A protocol that represents a citation in a conversation, providing reference and offset information."}],"kind":"symbol","role":"symbol","title":"Citation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","type":"topic","navigatorTitle":[{"text":"Citation","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Citation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationContent":{"title":"CitationContent","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitationContent","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"CitationContent","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a collection of citations associated with a text message."}],"url":"\/documentation\/smiclientcore\/citationcontent","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"citations","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"citations","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMICitation>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"citations","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"citations","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent~1citations\/title","op":"replace"},{"value":[{"text":"citations","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent~1citations\/fragments","op":"replace"},{"value":"SMICitation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/navigatorTitle","op":"replace"},{"value":"SMICitationContent","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitationContent"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/fragments","op":"replace"},{"value":[{"text":"SMICitationContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}