{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)SMIStructuredValue(im)initWithValue:","modules":[{"name":"SMIClientCore"}],"title":"init(value:)","symbolKind":"init","roleHeading":"Initializer"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/structuredvalue\/init(value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/structuredvalue\/init(value:)"]}],"abstract":[{"text":"Initializes a new structured value with the provided dictionary.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary containing the structured value data. Keys should be "},{"type":"codeVoice","code":"NSString"}]}],"name":"value"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue\/init(value:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol":{"type":"topic","url":"\/documentation\/smiclientcore\/structuredvalueprotocol","title":"StructuredValueProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A structured value that contains a dictionary of key-value pairs."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue/init(value:)":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"abstract":[{"text":"Initializes a new structured value with the provided dictionary.","type":"text"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/structuredvalue\/init(value:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue\/init(value:)","title":"init(value:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue":{"type":"topic","url":"\/documentation\/smiclientcore\/structuredvalue","title":"StructuredValue","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue","navigatorTitle":[{"text":"StructuredValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StructuredValue","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithValue:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A dictionary containing the structured value data. Keys should be "},{"code":"NSString","type":"codeVoice"}],"type":"paragraph"}],"name":"value"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SMIStructuredValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/navigatorTitle"},{"op":"replace","value":"initWithValue:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue~1init(value:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue~1init(value:)\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/title","op":"replace","value":"SMIStructuredValue"},{"value":[{"text":"SMIStructuredValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/fragments"},{"value":[{"text":"SMIStructuredValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/navigatorTitle"}]}]}