{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/checkbox","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"A field type for boolean values.","type":"text"},{"text":" ","type":"text"},{"text":"Use this type for true\/false choices.","type":"text"}],"metadata":{"modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"title":"checkbox","extendedModule":"SMIClientCore","externalID":"c:@SMIPreChatFieldTypesCheckbox","roleHeading":"Type Property","navigatorTitle":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkbox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","text":"PreChatFieldTypes"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/checkbox"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/checkbox"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PreChatFieldTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","title":"PreChatFieldTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatFieldTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/checkbox":{"type":"topic","navigatorTitle":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"abstract":[{"text":"A field type for boolean values.","type":"text"},{"text":" ","type":"text"},{"text":"Use this type for true\/false choices.","type":"text"}],"title":"checkbox","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/checkbox","role":"symbol","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/checkbox"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIPreChatFieldTypesCheckbox","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIPreChatFieldTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title"},{"value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle"},{"value":"SMIPreChatFieldTypesCheckbox","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1checkbox\/title"},{"value":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1checkbox\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}