{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","text":"PreChatFieldTypes","kind":"typeIdentifier"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/choiceList"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/choicelist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/choicelist"]}],"abstract":[{"type":"text","text":"A field type for selecting from predefined options."},{"type":"text","text":" "},{"type":"text","text":"Use this type when you want users to choose from a list of predefined values."},{"type":"text","text":" "},{"type":"text","text":"The available options are defined by an associated "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"symbolKind":"property","roleHeading":"Type Property","title":"choiceList","role":"symbol","externalID":"c:@SMIPreChatFieldTypesChoiceList","navigatorTitle":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}],"extendedModule":"SMIClientCore"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/choiceList":{"type":"topic","title":"choiceList","abstract":[{"text":"A field type for selecting from predefined options.","type":"text"},{"text":" ","type":"text"},{"text":"Use this type when you want users to choose from a list of predefined values.","type":"text"},{"text":" ","type":"text"},{"text":"The available options are defined by an associated ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/choiceList","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/choicelist","navigatorTitle":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"kind":"symbol","title":"ChoiceList","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/choicelist","navigatorTitle":[{"text":"ChoiceList","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"PreChatFieldTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","title":"PreChatFieldTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatFieldTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIPreChatFieldTypesChoiceList"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","text":"SMIPreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SMIPreChatFieldTypesChoiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1choiceList\/title"},{"op":"replace","value":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1choiceList\/fragments"},{"op":"replace","value":"SMIChoiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title"},{"op":"replace","value":[{"text":"SMIChoiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments"},{"op":"replace","value":[{"text":"SMIChoiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle"},{"op":"replace","value":"SMIPreChatFieldTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}