{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/phone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/phone"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A field type for phone numbers."},{"type":"text","text":" "},{"type":"text","text":"Use this type when collecting phone numbers."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@SMIPreChatFieldTypesPhone","title":"phone","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","text":"PreChatFieldTypes"}],"roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesPhone"}],"extendedModule":"SMIClientCore"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/phone","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/phone":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/phone","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/phone","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesPhone"}],"kind":"symbol","type":"topic","title":"phone","abstract":[{"type":"text","text":"A field type for phone numbers."},{"type":"text","text":" "},{"type":"text","text":"Use this type when collecting phone numbers."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatFieldTypes"}],"abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","title":"PreChatFieldTypes","navigatorTitle":[{"kind":"identifier","text":"PreChatFieldTypes"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIPreChatFieldTypesPhone","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIPreChatFieldTypesPhone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","text":"SMIPreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypesPhone","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIPreChatFieldTypesPhone","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1phone\/title"},{"value":[{"text":"SMIPreChatFieldTypesPhone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1phone\/fragments"},{"value":"SMIPreChatFieldTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title"},{"value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle"}]}]}