{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/textArea","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A field type for multi-line text input."},{"type":"text","text":" "},{"type":"text","text":"Use this type for longer text inputs that may require multiple lines."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/textarea"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/textarea"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","text":"PreChatFieldTypes"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"]]},"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIPreChatFieldTypesTextArea","kind":"identifier"}],"externalID":"c:@SMIPreChatFieldTypesTextArea","symbolKind":"property","title":"textArea","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier","text":"PreChatFieldTypes"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreChatFieldTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatFieldTypes"}],"title":"PreChatFieldTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/textArea":{"title":"textArea","abstract":[{"type":"text","text":"A field type for multi-line text input."},{"type":"text","text":" "},{"type":"text","text":"Use this type for longer text inputs that may require multiple lines."}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/textarea","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/textArea","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier","text":"PreChatFieldTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesTextArea"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIPreChatFieldTypesTextArea"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIPreChatFieldTypesTextArea","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"SMIPreChatFieldTypesTextArea","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title","value":"SMIPreChatFieldTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"op":"replace"},{"value":"SMIPreChatFieldTypesTextArea","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1textArea\/title"},{"value":[{"text":"SMIPreChatFieldTypesTextArea","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1textArea\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}