{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/text"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes\/text"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/text"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"text":"PreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"languages":["swift"]}]}],"abstract":[{"text":"A field type for single-line text input.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use this type for short text inputs such as names or short answers."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"extendedModule":"SMIClientCore","role":"symbol","externalID":"c:@SMIPreChatFieldTypesText","navigatorTitle":[{"text":"SMIPreChatFieldTypesText","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"text","roleHeading":"Type Property","symbolKind":"property"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/text":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/text","title":"text","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesText"}],"abstract":[{"type":"text","text":"A field type for single-line text input."},{"type":"text","text":" "},{"type":"text","text":"Use this type for short text inputs such as names or short answers."}],"type":"topic","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/text","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier","text":"PreChatFieldTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreChatFieldTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatFieldTypes"}],"title":"PreChatFieldTypes","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIPreChatFieldTypesText","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIPreChatFieldTypesText","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIPreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"SMIPreChatFieldTypesText","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIPreChatFieldTypesText","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1text\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1text\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title","op":"replace","value":"SMIPreChatFieldTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}]},{"op":"replace","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}