{"kind":"symbol","metadata":{"title":"!=(_:_:)","role":"symbol","symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:SMIFormInputValueType.h@T@SMIFormInputValueType","roleHeading":"Operator","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/!=(_:_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype\/!=(_:_:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputValueType"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputValueType"}],"type":"topic","title":"FormInputValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","url":"\/documentation\/smiclientcore\/forminputvaluetype","abstract":[{"type":"text","text":"An enum that defines the types of values that can be collected from form inputs."}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/!=(_:_:)":{"type":"topic","abstract":[],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/title","value":"SMIFormInputValueType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/fragments","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/navigatorTitle","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]}]}]}