{"variants":[{"paths":["\/documentation\/smiclientcore\/forminputvaluetype\/selectedoptionsinputvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype\/selectedoptionsinputvalue"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/selectedOptionsInputValue","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptionsInputValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Represents a collection of selected options from a form input.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when the form input allows users to select one or more options,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as in a multi-select dropdown or checkbox group."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType"]]},"metadata":{"symbolKind":"property","role":"symbol","extendedModule":"SMIClientCore","navigatorTitle":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedOptionsInputValue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"FormInputValueType","kind":"typeIdentifier"}],"externalID":"c:@SMIFormInputValueTypeSelectedOptionsInputValue","title":"selectedOptionsInputValue","modules":[{"name":"SMIClientCore"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType":{"url":"\/documentation\/smiclientcore\/forminputvaluetype","abstract":[{"text":"An enum that defines the types of values that can be collected from form inputs.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputValueType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FormInputValueType","kind":"identifier"}],"type":"topic","title":"FormInputValueType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/selectedOptionsInputValue":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedOptionsInputValue"},{"text":": ","kind":"text"},{"text":"FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/selectedoptionsinputvalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a collection of selected options from a form input."},{"text":" ","type":"text"},{"type":"text","text":"This type is used when the form input allows users to select one or more options,"},{"text":" ","type":"text"},{"type":"text","text":"such as in a multi-select dropdown or checkbox group."}],"title":"selectedOptionsInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/selectedOptionsInputValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormInputValueTypeSelectedOptionsInputValue","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"SMIFormInputValueType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInputValueTypeSelectedOptionsInputValue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/title","value":"SMIFormInputValueType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/fragments","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/navigatorTitle","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1selectedOptionsInputValue\/title","value":"SMIFormInputValueTypeSelectedOptionsInputValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1selectedOptionsInputValue\/fragments","value":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}]}]}]}