{"sections":[],"abstract":[{"text":"Represents a single value input from a form field.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This type is used when the form input collects a single value, such as text input,"},{"type":"text","text":" "},{"text":"date picker, or single-selection option picker.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/singleInputValue"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"singleInputValue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"FormInputValueType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype\/singleinputvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype\/singleinputvalue"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"singleInputValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"FormInputValueType","kind":"typeIdentifier"}],"extendedModule":"SMIClientCore","role":"symbol","externalID":"c:@SMIFormInputValueTypeSingleInputValue","navigatorTitle":[{"text":"SMIFormInputValueTypeSingleInputValue","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"singleInputValue","roleHeading":"Type Property","symbolKind":"property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/singleInputValue":{"title":"singleInputValue","abstract":[{"type":"text","text":"Represents a single value input from a form field."},{"type":"text","text":" "},{"text":"This type is used when the form input collects a single value, such as text input,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"date picker, or single-selection option picker."}],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/singleinputvalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/singleInputValue","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleInputValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormInputValueTypeSingleInputValue"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType":{"url":"\/documentation\/smiclientcore\/forminputvaluetype","abstract":[{"text":"An enum that defines the types of values that can be collected from form inputs.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputValueType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"FormInputValueType","kind":"identifier"}],"type":"topic","title":"FormInputValueType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","value":"SMIFormInputValueTypeSingleInputValue","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputValueTypeSingleInputValue"}]},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","kind":"typeIdentifier","text":"SMIFormInputValueType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIFormInputValueTypeSingleInputValue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SMIFormInputValueTypeSingleInputValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1singleInputValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormInputValueTypeSingleInputValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1singleInputValue\/fragments"},{"op":"replace","value":"SMIFormInputValueType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/title"},{"value":[{"text":"SMIFormInputValueType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/fragments"},{"value":[{"text":"SMIFormInputValueType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}