{"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"required":true,"externalID":"c:objc(pl)SMISessionContextSet(py)contextVariables","navigatorTitle":[{"text":"contextVariables","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextVariables","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"NamedValueProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMINamedValue"},{"text":"]","kind":"text"}],"title":"contextVariables","symbolKind":"property"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol\/contextVariables","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextVariables","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMINamedValue","text":"NamedValueProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property contains a collection of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","isActive":true},{"type":"text","text":" that represent the context"},{"type":"text","text":" "},{"type":"text","text":"variables for this session."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessioncontextsetprotocol\/contextvariables"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessioncontextsetprotocol\/contextvariables"]}],"abstract":[{"text":"Array of named context variables that make up this session context set.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"navigatorTitle":[{"text":"NamedValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/namedvalueprotocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","role":"symbol","type":"topic","kind":"symbol","title":"NamedValueProtocol","abstract":[{"text":"Represents a named value variable item with a name and ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValueProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValue":{"type":"topic","abstract":[{"type":"text","text":"Concrete implementation of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/namedvalue","role":"symbol","kind":"symbol","title":"NamedValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","navigatorTitle":[{"text":"NamedValue","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol/contextVariables":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol\/contextVariables","kind":"symbol","type":"topic","navigatorTitle":[{"text":"contextVariables","kind":"identifier"}],"abstract":[{"type":"text","text":"Array of named context variables that make up this session context set."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextVariables","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"NamedValueProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMINamedValue"},{"text":"]","kind":"text"}],"title":"contextVariables","required":true,"url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol\/contextvariables"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"role":"symbol","title":"AbstractValueProtocol","abstract":[{"text":"Protocol that defines the base type for session context values.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","kind":"symbol","abstract":[{"type":"text","text":"Represents a session context item with a name and value."}],"role":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol","title":"SessionContextSetProtocol","navigatorTitle":[{"text":"SessionContextSetProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSetProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"contextVariables","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"contextVariables"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMINamedValue>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"contextVariables"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMINamedValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMINamedValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/title","value":"SMINamedValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/fragments","value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol~1contextVariables\/title","value":"contextVariables","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol~1contextVariables\/fragments","value":[{"text":"contextVariables","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","value":"SMIAbstractValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","value":[{"kind":"identifier","text":"SMIAbstractValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","value":[{"text":"SMIAbstractValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/title","value":"SMISessionContextSet","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/fragments","value":[{"kind":"identifier","text":"SMISessionContextSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionContextSet"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}