{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedReference","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citation\/citedreference"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citation\/citedreference"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedReference","kind":"identifier"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","preciseIdentifier":"c:objc(pl)SMICitedReference","text":"CitedReference","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"The reference information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the link and source details through the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","isActive":true},{"text":" ","type":"text"},{"text":"protocol, which contains the primary reference information for the citation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"]]},"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedReference","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"CitedReference","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedReference"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMICitation(py)citedReference","modules":[{"name":"SMIClientCore"}],"title":"citedReference","navigatorTitle":[{"text":"citedReference","kind":"identifier"}],"required":true},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation/citedReference":{"abstract":[{"text":"The reference information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the link and source details through the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","type":"reference"},{"text":" ","type":"text"},{"text":"protocol, which contains the primary reference information for the citation.","type":"text"}],"kind":"symbol","title":"citedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedReference","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedReference"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"CitedReference","preciseIdentifier":"c:objc(pl)SMICitedReference"}],"navigatorTitle":[{"kind":"identifier","text":"citedReference"}],"url":"\/documentation\/smiclientcore\/citation\/citedreference"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CitedReference","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedreference","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReference","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","title":"CitedReference","abstract":[{"type":"text","text":"A protocol that represents the reference information for a citation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation":{"abstract":[{"type":"text","text":"A protocol that represents a citation in a conversation, providing reference and offset information."}],"kind":"symbol","title":"Citation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Citation","kind":"identifier"}],"navigatorTitle":[{"text":"Citation","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"citedReference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"citedReference","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMICitedReference>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMICitedReference"},{"text":" ","kind":"text"},{"text":"citedReference","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedReference\/title","value":"citedReference"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedReference\/fragments","value":[{"kind":"identifier","text":"citedReference"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/title","value":"SMICitedReference"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/fragments","value":[{"text":"SMICitedReference","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/navigatorTitle","value":[{"text":"SMICitedReference","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/title","value":"SMICitation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/fragments","value":[{"text":"SMICitation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitation"}]}]}]}