{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetails"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedDetails","text":"CitedDetails"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citation\/citeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citation\/citeddetails"]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedDetails","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"]]},"metadata":{"navigatorTitle":[{"text":"citedDetails","kind":"identifier"}],"required":true,"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","role":"symbol","title":"citedDetails","symbolKind":"property","externalID":"c:objc(pl)SMICitation(py)citedDetails","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedDetails","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICitedDetails","text":"CitedDetails","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"kind":"symbol","abstract":[{"type":"text","text":"Additional details about the citation’s location in the source material."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides access to offset and positioning information through the"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","type":"reference"},{"type":"text","text":" protocol, which can include details about where the citation appears"},{"type":"text","text":" "},{"type":"text","text":"in the referenced source."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails":{"role":"symbol","url":"\/documentation\/smiclientcore\/citeddetails","navigatorTitle":[{"text":"CitedDetails","kind":"identifier"}],"abstract":[{"text":"A protocol that represents the location and type information for a citation.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedDetails","kind":"identifier"}],"type":"topic","title":"CitedDetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Citation","kind":"identifier"}],"title":"Citation","abstract":[{"text":"A protocol that represents a citation in a conversation, providing reference and offset information.","type":"text"}],"url":"\/documentation\/smiclientcore\/citation","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Citation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation/citedDetails":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedDetails","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"CitedDetails","preciseIdentifier":"c:objc(pl)SMICitedDetails","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"citedDetails","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/citation\/citeddetails","title":"citedDetails","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedDetails","abstract":[{"type":"text","text":"Additional details about the citation’s location in the source material."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides access to offset and positioning information through the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"},{"text":" protocol, which can include details about where the citation appears","type":"text"},{"text":" ","type":"text"},{"text":"in the referenced source.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"citedDetails","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"citedDetails","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMICitedDetails>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMICitedDetails"},{"text":" ","kind":"text"},{"text":"citedDetails","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMICitedDetails","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/title"},{"op":"replace","value":[{"text":"SMICitedDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICitedDetails"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/navigatorTitle"},{"op":"replace","value":"SMICitation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/title"},{"op":"replace","value":[{"text":"SMICitation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/fragments"},{"op":"replace","value":[{"text":"SMICitation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/navigatorTitle"},{"op":"replace","value":"citedDetails","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedDetails\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"citedDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}