{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inlineMetadata"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","text":"CitedInlineMetadata","preciseIdentifier":"c:objc(pl)SMICitedInlineMetadata"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails\/inlineMetadata"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The array of inline metadata entries for this citation."},{"type":"text","text":" "},{"type":"text","text":"Each entry in the array conforms to the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","isActive":true,"type":"reference"},{"type":"text","text":" protocol and provides"},{"type":"text","text":" "},{"type":"text","text":"detailed information about where the citation appears in the text, including claim"},{"type":"text","text":" "},{"type":"text","text":"information and location offsets."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails"]]},"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIInlineMetadataCitedDetails(py)inlineMetadata","required":true,"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"CitedInlineMetadata","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedInlineMetadata"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"inlineMetadata","kind":"identifier"}],"role":"symbol","title":"inlineMetadata","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/inlinemetadataciteddetails\/inlinemetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/inlinemetadataciteddetails\/inlinemetadata"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata":{"kind":"symbol","title":"CitedInlineMetadata","abstract":[{"type":"text","text":"A protocol that represents inline metadata for a citation, including its location and claim information."}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CitedInlineMetadata"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedInlineMetadata"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/InlineMetadataCitedDetails":{"navigatorTitle":[{"text":"InlineMetadataCitedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/inlinemetadataciteddetails","abstract":[{"type":"text","text":"A protocol that represents citation details with inline metadata for the given citations."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InlineMetadataCitedDetails","kind":"identifier"}],"kind":"symbol","title":"InlineMetadataCitedDetails"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/InlineMetadataCitedDetails/inlineMetadata":{"url":"\/documentation\/smiclientcore\/inlinemetadataciteddetails\/inlinemetadata","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inlineMetadata"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"CitedInlineMetadata","preciseIdentifier":"c:objc(pl)SMICitedInlineMetadata"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails\/inlineMetadata","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"inlineMetadata"}],"abstract":[{"type":"text","text":"The array of inline metadata entries for this citation."},{"type":"text","text":" "},{"type":"text","text":"Each entry in the array conforms to the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","isActive":true},{"type":"text","text":" protocol and provides"},{"type":"text","text":" "},{"type":"text","text":"detailed information about where the citation appears in the text, including claim"},{"type":"text","text":" "},{"type":"text","text":"information and location offsets."}],"role":"symbol","type":"topic","title":"inlineMetadata"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"inlineMetadata"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"inlineMetadata","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMICitedInlineMetadata>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/title","op":"replace","value":"SMICitedInlineMetadata"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/fragments","op":"replace","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/navigatorTitle","op":"replace","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/title","op":"replace","value":"SMIInlineMetadataCitedDetails"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIInlineMetadataCitedDetails"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/navigatorTitle","op":"replace","value":[{"text":"SMIInlineMetadataCitedDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails~1inlineMetadata\/title","op":"replace","value":"inlineMetadata"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails~1inlineMetadata\/fragments","op":"replace","value":[{"text":"inlineMetadata","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}