{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/!=(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"op","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}],"roleHeading":"Operator","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"extendedModule":"Swift","title":"!=(_:_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype\/!=(_:_:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType":{"abstract":[{"type":"text","text":"An enum that defines the possible states of an attachment upload operation."}],"title":"AttachmentUploadResultType","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResultType","kind":"identifier"}],"navigatorTitle":[{"text":"AttachmentUploadResultType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/attachmentuploadresulttype","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/Equatable-Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/!=(_:_:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SMIAttachmentUploadResultType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/title"},{"op":"replace","value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/fragments"},{"op":"replace","value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}