{"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype\/completed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype\/completed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/completed","interfaceLanguage":"swift"},"abstract":[{"text":"Upload completed successfully.","type":"text"},{"text":" ","type":"text"},{"text":"Used when the attachment has been successfully uploaded to the server.","type":"text"}],"metadata":{"extendedModule":"SMIClientCore","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"AttachmentUploadResultType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeCompleted"}],"roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"title":"completed","externalID":"c:@SMIAttachmentUploadResultTypeCompleted","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"AttachmentUploadResultType"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/completed":{"abstract":[{"type":"text","text":"Upload completed successfully."},{"text":" ","type":"text"},{"text":"Used when the attachment has been successfully uploaded to the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/completed","type":"topic","role":"symbol","title":"completed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/completed","navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeCompleted"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","title":"AttachmentUploadResultType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResultType"}],"type":"topic","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype","abstract":[{"type":"text","text":"An enum that defines the possible states of an attachment upload operation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResultType"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIAttachmentUploadResultTypeCompleted","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIAttachmentUploadResultTypeCompleted","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"SMIAttachmentUploadResultType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAttachmentUploadResultTypeCompleted"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAttachmentUploadResultTypeCompleted","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1completed\/title","op":"replace"},{"value":[{"text":"SMIAttachmentUploadResultTypeCompleted","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1completed\/fragments","op":"replace"},{"value":"SMIAttachmentUploadResultType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResultType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/fragments","op":"replace"},{"value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}