{"metadata":{"roleHeading":"Type Property","title":"error","externalID":"c:@SMIAttachmentUploadResultTypeError","role":"symbol","navigatorTitle":[{"text":"SMIAttachmentUploadResultTypeError","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AttachmentUploadResultType","kind":"typeIdentifier","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}],"extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype\/error"]}],"abstract":[{"text":"Upload failed with an error.","type":"text"},{"text":" ","type":"text"},{"text":"Used when the attachment upload encountered an error and failed.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AttachmentUploadResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/error","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/error":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"AttachmentUploadResultType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeError"}],"title":"error","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/error","abstract":[{"type":"text","text":"Upload failed with an error."},{"type":"text","text":" "},{"type":"text","text":"Used when the attachment upload encountered an error and failed."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/error"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","title":"AttachmentUploadResultType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResultType"}],"type":"topic","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype","abstract":[{"type":"text","text":"An enum that defines the possible states of an attachment upload operation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResultType"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SMIAttachmentUploadResultTypeError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIAttachmentUploadResultTypeError","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"SMIAttachmentUploadResultType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAttachmentUploadResultTypeError","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1error\/title","value":"SMIAttachmentUploadResultTypeError","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1error\/fragments","value":[{"text":"SMIAttachmentUploadResultTypeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/title","value":"SMIAttachmentUploadResultType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/fragments","value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachmentUploadResultType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}