{"sections":[],"abstract":[{"type":"text","text":"Indicates the action of updating progress information."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType\/modalityUpdate"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"modalityUpdate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType","text":"ConversationUpdateType"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationupdatetype\/modalityupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationupdatetype\/modalityupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIConversationUpdateTypeModalityUpdate","kind":"identifier"}],"externalID":"c:@SMIConversationUpdateTypeModalityUpdate","symbolKind":"property","title":"modalityUpdate","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modalityUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType","text":"ConversationUpdateType","kind":"typeIdentifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateType":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationupdatetype","title":"ConversationUpdateType","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","navigatorTitle":[{"kind":"identifier","text":"ConversationUpdateType"}],"abstract":[{"type":"text","text":"An enum that defines types of updates that may be received on the state of the conversation."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationUpdateType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateType/modalityUpdate":{"abstract":[{"type":"text","text":"Indicates the action of updating progress information."}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationUpdateTypeModalityUpdate"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType\/modalityUpdate","title":"modalityUpdate","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalityUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType","text":"ConversationUpdateType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationupdatetype\/modalityupdate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"SMIConversationUpdateTypeModalityUpdate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIConversationUpdateTypeModalityUpdate"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","text":"SMIConversationUpdateType","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationUpdateTypeModalityUpdate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/title","value":"SMIConversationUpdateType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/fragments","value":[{"text":"SMIConversationUpdateType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SMIConversationUpdateType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType~1modalityUpdate\/title","value":"SMIConversationUpdateTypeModalityUpdate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType~1modalityUpdate\/fragments","value":[{"kind":"identifier","text":"SMIConversationUpdateTypeModalityUpdate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}