{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"batchNumber"}],"title":"batchNumber","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"externalID":"c:objc(pl)SMIMessageStreamingToken(py)batchNumber","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Corresponds to an identifier applied to the agent’s response. Events which have a strong association will be sent in batches."},{"type":"text","text":" "},{"type":"text","text":"This identifier can be used to identifier a batch of related events within a single turn."}],"variants":[{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/batchnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/batchnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/batchNumber"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","navigatorTitle":[{"text":"MessageStreamingToken","kind":"identifier"}],"type":"topic","title":"MessageStreamingToken","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"url":"\/documentation\/smiclientcore\/messagestreamingtoken","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageStreamingToken"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/batchNumber":{"title":"batchNumber","abstract":[{"text":"Corresponds to an identifier applied to the agent’s response. Events which have a strong association will be sent in batches.","type":"text"},{"text":" ","type":"text"},{"text":"This identifier can be used to identifier a batch of related events within a single turn.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"batchNumber"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken\/batchnumber","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/batchNumber","required":true,"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"batchNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"batchNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title","value":"SMIMessageStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageStreamingToken"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1batchNumber\/title","value":"batchNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1batchNumber\/fragments","value":[{"kind":"identifier","text":"batchNumber"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}