{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/targetMessageIdentifier"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"targetMessageIdentifier"}],"required":true,"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property","role":"symbol","title":"targetMessageIdentifier","externalID":"c:objc(pl)SMIMessageStreamingToken(py)targetMessageIdentifier","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/targetmessageidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/targetmessageidentifier"]}],"kind":"symbol","abstract":[{"type":"text","text":"The identifier that will be used for the final transcribed entry."},{"type":"text","text":" "},{"type":"text","text":"This property provides a unique identifier that will be associated with the complete"},{"type":"text","text":" "},{"type":"text","text":"message once all streaming tokens have been received and processed."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"title":"MessageStreamingToken","navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageStreamingToken"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/targetMessageIdentifier":{"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"targetMessageIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/targetMessageIdentifier","type":"topic","navigatorTitle":[{"kind":"identifier","text":"targetMessageIdentifier"}],"url":"\/documentation\/smiclientcore\/messagestreamingtoken\/targetmessageidentifier","kind":"symbol","abstract":[{"text":"The identifier that will be used for the final transcribed entry.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a unique identifier that will be associated with the complete","type":"text"},{"text":" ","type":"text"},{"text":"message once all streaming tokens have been received and processed.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"targetMessageIdentifier"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"targetMessageIdentifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"targetMessageIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIMessageStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1targetMessageIdentifier\/title","op":"replace","value":"targetMessageIdentifier"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1targetMessageIdentifier\/fragments","op":"replace","value":[{"text":"targetMessageIdentifier","kind":"identifier"}]}]}]}