{"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/token"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken\/token"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The content of this streaming token.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the token’s content through the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat"},{"text":" ","type":"text"},{"text":"protocol.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","text":"EntryFormat","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"]]},"metadata":{"externalID":"c:objc(pl)SMIMessageStreamingToken(py)token","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryFormat","text":"EntryFormat"}],"navigatorTitle":[{"kind":"identifier","text":"token"}],"required":true,"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"title":"token","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/token","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"kind":"symbol","url":"\/documentation\/smiclientcore\/entryformat","abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"EntryFormat","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormat","kind":"identifier"}],"title":"EntryFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/token":{"role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"EntryFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryFormat"}],"abstract":[{"text":"The content of this streaming token.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the token’s content through the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"protocol.","type":"text"}],"url":"\/documentation\/smiclientcore\/messagestreamingtoken\/token","kind":"symbol","navigatorTitle":[{"text":"token","kind":"identifier"}],"title":"token","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/token"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"title":"MessageStreamingToken","navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageStreamingToken"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"token","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"token","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIEntryFormat","text":"id<SMIEntryFormat>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIEntryFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title"},{"op":"replace","value":[{"text":"SMIEntryFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments"},{"op":"replace","value":[{"text":"SMIEntryFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle"},{"op":"replace","value":"token","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1token\/title"},{"op":"replace","value":[{"text":"token","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1token\/fragments"},{"op":"replace","value":"SMIMessageStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title"},{"op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments"},{"op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle"}]}]}