{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/staticerrordetails\/errorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/staticerrordetails\/errorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorCode"},"metadata":{"title":"errorCode","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"errorCode"}],"modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"property","externalID":"c:objc(pl)SMIStaticErrorDetails(py)errorCode"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails":{"url":"\/documentation\/smiclientcore\/staticerrordetails","navigatorTitle":[{"text":"StaticErrorDetails","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"StaticErrorDetails","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorDetails","kind":"identifier"}],"abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"type":"text","text":" Support for Static LightningType messages with Agentforce."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails/errorCode":{"kind":"symbol","title":"errorCode","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorCode","navigatorTitle":[{"text":"errorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/smiclientcore\/staticerrordetails\/errorcode","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"errorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"errorCode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"errorCode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/title","op":"replace","value":"SMIStaticErrorDetails"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/fragments","op":"replace","value":[{"text":"SMIStaticErrorDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIStaticErrorDetails"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorCode\/title","op":"replace","value":"errorCode"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"errorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}