{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"This property will enable Lightning Type experiences with Agentforce Agents.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/experimentalconfiguration\/enablelightningtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/experimentalconfiguration\/enablelightningtypes"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableLightningTypes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Toggling this flag will not impact existing users or conversations and would require destroying the database cache for it to take effect.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is only available with un authenticated deployments."}]}],"name":"Note","type":"aside","style":"note"}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","title":"enableLightningTypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableLightningTypes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:objc(pl)SMIExperimentalConfiguration(py)enableLightningTypes","roleHeading":"Instance Property","navigatorTitle":[{"text":"enableLightningTypes","kind":"identifier"}],"required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration\/enableLightningTypes"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ExperimentalConfiguration/enableLightningTypes":{"navigatorTitle":[{"kind":"identifier","text":"enableLightningTypes"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLightningTypes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/smiclientcore\/experimentalconfiguration\/enablelightningtypes","title":"enableLightningTypes","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration\/enableLightningTypes","type":"topic","abstract":[{"text":"This property will enable Lightning Type experiences with Agentforce Agents.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ExperimentalConfiguration":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExperimentalConfiguration","kind":"identifier"}],"title":"ExperimentalConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration","abstract":[{"text":"This class stores configuration for experimental or beta features.","type":"text"}],"url":"\/documentation\/smiclientcore\/experimentalconfiguration","kind":"symbol","navigatorTitle":[{"text":"ExperimentalConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"enableLightningTypes","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"enableLightningTypes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"enableLightningTypes","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"enableLightningTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration~1enableLightningTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"enableLightningTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration~1enableLightningTypes\/fragments"},{"op":"replace","value":"SMIExperimentalConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/title"},{"op":"replace","value":[{"text":"SMIExperimentalConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIExperimentalConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/navigatorTitle"}]}]}