{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/startTime","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/businesshours\/starttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshours\/starttime"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"}],"externalID":"c:objc(pl)SMIBusinessHours(py)startTime","navigatorTitle":[{"text":"startTime","kind":"identifier"}],"title":"startTime","symbolKind":"property","roleHeading":"Instance Property","required":true},"abstract":[{"type":"text","text":"The start time of the business hours interval."},{"type":"text","text":" "},{"type":"text","text":"This time represents when the deployment is considered open to customers."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours/startTime":{"required":true,"abstract":[{"text":"The start time of the business hours interval.","type":"text"},{"text":" ","type":"text"},{"text":"This time represents when the deployment is considered open to customers.","type":"text"}],"kind":"symbol","type":"topic","title":"startTime","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/startTime","url":"\/documentation\/smiclientcore\/businesshours\/starttime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"}],"navigatorTitle":[{"kind":"identifier","text":"startTime"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours":{"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines a time interval for business hours."}],"navigatorTitle":[{"text":"BusinessHours","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"title":"BusinessHours","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","url":"\/documentation\/smiclientcore\/businesshours"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"startTime","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"startTime","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"startTime","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1startTime\/title"},{"value":[{"text":"startTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1startTime\/fragments"},{"value":"SMIBusinessHours","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/title"},{"value":[{"text":"SMIBusinessHours","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/fragments"},{"value":[{"text":"SMIBusinessHours","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}