{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/messagereason\/automatedresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/messagereason\/automatedresponse"]}],"kind":"symbol","abstract":[{"text":"Indicates the action of sending an automated response message.","type":"text"}],"metadata":{"role":"symbol","externalID":"c:@SMIMessageReasonAutomatedResponse","symbolKind":"property","navigatorTitle":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatedResponse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","text":"MessageReason","kind":"typeIdentifier"}],"title":"automatedResponse","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/automatedResponse","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatedResponse","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","text":"MessageReason","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/automatedResponse":{"title":"automatedResponse","kind":"symbol","abstract":[{"type":"text","text":"Indicates the action of sending an automated response message."}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatedResponse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","text":"MessageReason","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/automatedResponse","navigatorTitle":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/messagereason\/automatedresponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReason"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageReason"}],"abstract":[{"type":"text","text":"An enum that defines the possible reasons for a message in a conversation."}],"title":"MessageReason","role":"symbol","url":"\/documentation\/smiclientcore\/messagereason","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SMIMessageReasonAutomatedResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIMessageReason","kind":"typeIdentifier","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SMIMessageReasonAutomatedResponse","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1automatedResponse\/title","op":"replace"},{"value":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1automatedResponse\/fragments","op":"replace"},{"value":"SMIMessageReason","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/title","op":"replace"},{"value":[{"text":"SMIMessageReason","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/fragments","op":"replace"},{"value":[{"text":"SMIMessageReason","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}