{"abstract":[{"type":"text","text":"Describes a Close Conversation type."}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"externalID":"c:@SMIConversationEntryTypesCloseConversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesCloseConversation"}],"extendedModule":"SMIClientCore","symbolKind":"property","title":"closeConversation"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/closeconversation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/closeconversation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/closeConversation"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier","text":"ConversationEntryTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryTypes"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes","navigatorTitle":[{"kind":"identifier","text":"ConversationEntryTypes"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","role":"symbol","title":"ConversationEntryTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/closeConversation":{"abstract":[{"type":"text","text":"Describes a Close Conversation type."}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/closeconversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/closeConversation","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesCloseConversation"}],"type":"topic","kind":"symbol","title":"closeConversation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIConversationEntryTypesCloseConversation","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypesCloseConversation"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"SMIConversationEntryTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryTypesCloseConversation"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIConversationEntryTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle"},{"op":"replace","value":"SMIConversationEntryTypesCloseConversation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1closeConversation\/title"},{"op":"replace","value":[{"text":"SMIConversationEntryTypesCloseConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1closeConversation\/fragments"}]}]}