{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/participantchanged"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/participantchanged"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/participantChanged","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","externalID":"c:@SMIConversationEntryTypesParticipantChanged","title":"participantChanged","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesParticipantChanged"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore"},"abstract":[{"type":"text","text":"Indicates a change in conversation participants."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/participantChanged":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/participantChanged","title":"participantChanged","navigatorTitle":[{"text":"SMIConversationEntryTypesParticipantChanged","kind":"identifier"}],"abstract":[{"text":"Indicates a change in conversation participants.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/participantchanged","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participantChanged","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","title":"ConversationEntryTypes","navigatorTitle":[{"text":"ConversationEntryTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIConversationEntryTypesParticipantChanged","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIConversationEntryTypesParticipantChanged","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"SMIConversationEntryTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryTypesParticipantChanged"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1participantChanged\/title","op":"replace","value":"SMIConversationEntryTypesParticipantChanged"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1participantChanged\/fragments","op":"replace","value":[{"text":"SMIConversationEntryTypesParticipantChanged","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","op":"replace","value":"SMIConversationEntryTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","op":"replace","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]}]}]}