{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/richMessage"},"metadata":{"extendedModule":"SMIClientCore","title":"richMessage","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIConversationEntryTypesRichMessage","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"externalID":"c:@SMIConversationEntryTypesRichMessage"},"sections":[],"abstract":[{"type":"text","text":"Represents a message containing rich media or interactive content."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMessage"},{"kind":"text","text":": "},{"text":"ConversationEntryTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/richmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/richmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/richMessage":{"title":"richMessage","abstract":[{"text":"Represents a message containing rich media or interactive content.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/richmessage","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/richMessage","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesRichMessage"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","title":"ConversationEntryTypes","navigatorTitle":[{"text":"ConversationEntryTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIConversationEntryTypesRichMessage","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIConversationEntryTypesRichMessage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryTypesRichMessage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1richMessage\/title","value":"SMIConversationEntryTypesRichMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1richMessage\/fragments","value":[{"text":"SMIConversationEntryTypesRichMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","value":"SMIConversationEntryTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}