{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingWorkResult","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/routingworkresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/routingworkresult"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesRoutingWorkResult"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingWorkResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier","text":"ConversationEntryTypes"}],"externalID":"c:@SMIConversationEntryTypesRoutingWorkResult","title":"routingWorkResult","role":"symbol"},"abstract":[{"type":"text","text":"Result of a routing work operation."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingWorkResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/routingWorkResult":{"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingWorkResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingWorkResult","title":"routingWorkResult","navigatorTitle":[{"text":"SMIConversationEntryTypesRoutingWorkResult","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/routingworkresult","type":"topic","abstract":[{"type":"text","text":"Result of a routing work operation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryTypes"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes","navigatorTitle":[{"kind":"identifier","text":"ConversationEntryTypes"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","role":"symbol","title":"ConversationEntryTypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIConversationEntryTypesRoutingWorkResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIConversationEntryTypesRoutingWorkResult","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"SMIConversationEntryTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryTypesRoutingWorkResult"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingWorkResult\/title","value":"SMIConversationEntryTypesRoutingWorkResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingWorkResult\/fragments","value":[{"text":"SMIConversationEntryTypesRoutingWorkResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","value":"SMIConversationEntryTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]}]}]}