{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionContext","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/sessioncontext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/sessioncontext"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"extendedModule":"SMIClientCore","roleHeading":"Type Property","role":"symbol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIConversationEntryTypesSessionContext","kind":"identifier"}],"symbolKind":"property","externalID":"c:@SMIConversationEntryTypesSessionContext","title":"sessionContext"},"abstract":[{"type":"text","text":"Describes a SessionContext"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryTypes","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ConversationEntryTypes","kind":"identifier"}],"title":"ConversationEntryTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","url":"\/documentation\/smiclientcore\/conversationentrytypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/sessionContext":{"navigatorTitle":[{"text":"SMIConversationEntryTypesSessionContext","kind":"identifier"}],"title":"sessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionContext","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes a SessionContext"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/sessioncontext","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryTypesSessionContext"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypesSessionContext"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryTypesSessionContext","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","op":"replace","value":"SMIConversationEntryTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionContext\/title","op":"replace","value":"SMIConversationEntryTypesSessionContext"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypesSessionContext"}]}]}]}