{"sections":[],"abstract":[{"type":"text","text":"Represents a streaming token for real-time updates."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/streamingToken","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamingToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/streamingtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationentrytypes\/streamingtoken"]}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIConversationEntryTypesStreamingToken","kind":"identifier"}],"externalID":"c:@SMIConversationEntryTypesStreamingToken","symbolKind":"property","title":"streamingToken","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamingToken","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","title":"ConversationEntryTypes","navigatorTitle":[{"text":"ConversationEntryTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/streamingToken":{"abstract":[{"type":"text","text":"Represents a streaming token for real-time updates."}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesStreamingToken"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/streamingToken","title":"streamingToken","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamingToken"},{"kind":"text","text":": "},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrytypes\/streamingtoken"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIConversationEntryTypesStreamingToken","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIConversationEntryTypesStreamingToken","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryTypesStreamingToken"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","op":"replace","value":"SMIConversationEntryTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","op":"replace","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}],"op":"replace"},{"value":"SMIConversationEntryTypesStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1streamingToken\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1streamingToken\/fragments","value":[{"text":"SMIConversationEntryTypesStreamingToken","kind":"identifier"}],"op":"replace"}]}]}