{"metadata":{"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","text":"ConversationEntryStatus","kind":"typeIdentifier"}],"title":"attachmentError","navigatorTitle":[{"text":"SMIConversationEntryStatusAttachmentError","kind":"identifier"}],"platforms":[{"beta":false,"message":"Use `SMIConversationEntryStatusError`","deprecated":true,"unavailable":false}],"roleHeading":"Type Property","role":"symbol","externalID":"c:@SMIConversationEntryStatusAttachmentError","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/attachmentError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" has failed when sent to a bot."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrystatus\/attachmenterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrystatus\/attachmenterror"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus"}]}],"kind":"declarations"}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Use `SMIConversationEntryStatusError`","type":"text"}],"type":"paragraph"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/attachmentError":{"deprecated":true,"navigatorTitle":[{"text":"SMIConversationEntryStatusAttachmentError","kind":"identifier"}],"role":"symbol","type":"topic","title":"attachmentError","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" has failed when sent to a bot."}],"url":"\/documentation\/smiclientcore\/conversationentrystatus\/attachmenterror","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/attachmentError","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus":{"title":"ConversationEntryStatus","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ConversationEntryStatus","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","url":"\/documentation\/smiclientcore\/conversationentrystatus","abstract":[{"text":"An enum that defines the possible statuses of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":true,"unavailable":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIConversationEntryStatusAttachmentError","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIConversationEntryStatusAttachmentError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","text":"SMIConversationEntryStatus"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryStatusAttachmentError"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":[{"inlineContent":[{"text":"Use `SMIConversationEntryStatusError`","type":"text"}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"value":"SMIConversationEntryStatusAttachmentError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1attachmentError\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryStatusAttachmentError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1attachmentError\/fragments","op":"replace"},{"value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace"},{"value":"SMIConversationEntryStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/fragments","op":"replace"},{"value":[{"text":"SMIConversationEntryStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}