{"kind":"symbol","sections":[],"abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":" is confirmed to have been delivered to the other participant’s client.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delivered","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","text":"ConversationEntryStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrystatus\/delivered"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrystatus\/delivered"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"roleHeading":"Type Property","title":"delivered","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryStatusDelivered"}],"symbolKind":"property","extendedModule":"SMIClientCore","role":"symbol","externalID":"c:@SMIConversationEntryStatusDelivered","modules":[{"name":"SMIClientCore"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/delivered","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/delivered":{"navigatorTitle":[{"text":"SMIConversationEntryStatusDelivered","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrystatus\/delivered","title":"delivered","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/delivered","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delivered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":" is confirmed to have been delivered to the other participant’s client.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus":{"title":"ConversationEntryStatus","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryStatus","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"ConversationEntryStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","abstract":[{"text":"An enum that defines the possible statuses of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationentrystatus","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryStatusDelivered"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusDelivered","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIConversationEntryStatusDelivered","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMIConversationEntryStatusDelivered","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1delivered\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryStatusDelivered"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1delivered\/fragments"},{"value":"SMIConversationEntryStatus","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/fragments"},{"value":[{"text":"SMIConversationEntryStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/navigatorTitle"}]}]}