{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType"]]},"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/Equatable-Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/!=(_:_:)"],"anchor":"Operators","generated":true}],"kind":"article","variants":[{"paths":["\/documentation\/smiclientcore\/citedreferencetype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/!=(_:_:)","url":"\/documentation\/smiclientcore\/citedreferencetype\/!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedReferenceType"}],"url":"\/documentation\/smiclientcore\/citedreferencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of citation references available in the system."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedReferenceType"}],"title":"CitedReferenceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SMICitedReferenceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/fragments"},{"op":"replace","value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}