{"metadata":{"title":"link","navigatorTitle":[{"kind":"identifier","text":"SMICitedReferenceTypeLink"}],"externalID":"c:@SMICitedReferenceTypeLink","roleHeading":"Type Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType","kind":"typeIdentifier","text":"CitedReferenceType"}],"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore"},"abstract":[{"type":"text","text":"Represents a citation reference that includes a link to the source material."},{"type":"text","text":" "},{"type":"text","text":"This type is used when the citation references an external source through a URL or"},{"type":"text","text":" "},{"type":"text","text":"other link-based reference mechanism."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/link","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","text":"CitedReferenceType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citedreferencetype\/link"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citedreferencetype\/link"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType/link":{"url":"\/documentation\/smiclientcore\/citedreferencetype\/link","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/link","role":"symbol","title":"link","navigatorTitle":[{"text":"SMICitedReferenceTypeLink","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedReferenceType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType"}],"abstract":[{"text":"Represents a citation reference that includes a link to the source material.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when the citation references an external source through a URL or","type":"text"},{"text":" ","type":"text"},{"text":"other link-based reference mechanism.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType":{"url":"\/documentation\/smiclientcore\/citedreferencetype","kind":"symbol","role":"symbol","title":"CitedReferenceType","abstract":[{"text":"An enum that defines the types of citation references available in the system.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReferenceType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CitedReferenceType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMICitedReferenceTypeLink","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitedReferenceTypeLink"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMICitedReferenceTypeLink"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMICitedReferenceTypeLink","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType~1link\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitedReferenceTypeLink"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType~1link\/fragments","op":"replace"},{"value":"SMICitedReferenceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/title","op":"replace"},{"value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/navigatorTitle","op":"replace"}]}]}