{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedOptions"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption","preciseIdentifier":"c:objc(pl)SMIFormSelectedOption","text":"SelectedOption"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptions","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"SelectedOption","preciseIdentifier":"c:objc(pl)SMIFormSelectedOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"externalID":"c:objc(pl)SMIFormSelectedOptionsInputValue(py)selectedOptions","navigatorTitle":[{"text":"selectedOptions","kind":"identifier"}],"role":"symbol","title":"selectedOptions"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue\/selectedOptions","interfaceLanguage":"swift"},"abstract":[{"text":"A list of selected options in this input value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains an array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption","isActive":true},{"text":" objects, each representing","type":"text"},{"text":" ","type":"text"},{"text":"a selected option with its identifier and title. The array may be empty if no options","type":"text"},{"text":" ","type":"text"},{"text":"are selected, or contain multiple items when multiple selections are allowed.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/smiclientcore\/formselectedoptionsinputvalue\/selectedoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formselectedoptionsinputvalue\/selectedoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SelectedOption","kind":"identifier"}],"title":"SelectedOption","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelectedOption","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a selected option in a multi-option form input."}],"url":"\/documentation\/smiclientcore\/selectedoption","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectedOptionsInputValue":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a form input value containing multiple selected options."}],"navigatorTitle":[{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/formselectedoptionsinputvalue","title":"FormSelectedOptionsInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectedOptionsInputValue/selectedOptions":{"title":"selectedOptions","abstract":[{"text":"A list of selected options in this input value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains an array of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},{"text":" objects, each representing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a selected option with its identifier and title. The array may be empty if no options"},{"type":"text","text":" "},{"type":"text","text":"are selected, or contain multiple items when multiple selections are allowed."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue\/selectedOptions","required":true,"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/formselectedoptionsinputvalue\/selectedoptions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptions","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"SelectedOption","preciseIdentifier":"c:objc(pl)SMIFormSelectedOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"selectedOptions","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"selectedOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"selectedOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIFormSelectedOption>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"selectedOptions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/title","op":"replace","value":"SMIFormSelectedOption"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/fragments","op":"replace","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/navigatorTitle","op":"replace","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/title","op":"replace","value":"SMIFormSelectedOptionsInputValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue~1selectedOptions\/title","op":"replace","value":"selectedOptions"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue~1selectedOptions\/fragments","op":"replace","value":[{"text":"selectedOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}