{"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"core(_:conversation:didReceiveEvents:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": any "},{"text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didReceiveEvents","kind":"externalParam"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"core:conversation:didReceiveEvents:"}],"role":"symbol","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMICoreDelegate(im)core:conversation:didReceiveEvents:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"]]},"abstract":[{"text":"Delegate event that is triggered when receiving a conversation events.","type":"text"},{"text":" ","type":"text"},{"text":"A conversation event is a ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" that is not saved to the conversation transcript.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"core","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","text":"CoreClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveEvents"},{"kind":"text","text":" "},{"kind":"internalParam","text":"events"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"core","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"text":" instance that is managing the current connection.","type":"text"}]}]},{"name":"conversation","content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","type":"reference","isActive":true},{"type":"text","text":" instance that owns the emitted entries."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" data modles. Each represents  a conversation event."}]}],"name":"events"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEvents:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didreceiveevents:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didreceiveevents:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","title":"CoreDelegate","navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate used to receive events for the ","type":"text"},{"code":"SMICoreClient","type":"codeVoice"},{"text":" framework. Use this protocol to listen","type":"text"},{"text":" ","type":"text"},{"text":"for chat messages, receive message status changes, detect network status changes, and receive error messages.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didReceiveEvents:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEvents:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didreceiveevents:)","abstract":[{"text":"Delegate event that is triggered when receiving a conversation events.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A conversation event is a "},{"code":"SMIConversationEntry","type":"codeVoice"},{"type":"text","text":" that is not saved to the conversation transcript."}],"role":"symbol","title":"core(_:conversation:didReceiveEvents:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveEvents","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"core:conversation:didReceiveEvents:","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"core:conversation:didReceiveEvents:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"core:conversation:didReceiveEvents:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"core:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMICoreClient","text":"id<SMICoreClient>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"core","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMIConversation>","preciseIdentifier":"c:Qoobjc(pl)SMIConversation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"conversation"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveEvents:"},{"text":"(","kind":"text"},{"text":"NSArray<id<SMIConversationEntry>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"events","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}],"name":"core"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","isActive":true},{"type":"text","text":" instance that owns the emitted entries."}],"type":"paragraph"}],"name":"conversation"},{"name":"events","content":[{"type":"paragraph","inlineContent":[{"text":"The array of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" data modles. Each represents  a conversation event."}]}]}],"kind":"parameters"}},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"op":"replace","value":"SMICoreDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/navigatorTitle","value":[{"text":"SMICoreDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","op":"replace","value":"SMICoreConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace"},{"op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"op":"replace","value":"SMIConversation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"value":"core:conversation:didReceiveEvents:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEvents:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"core:conversation:didReceiveEvents:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEvents:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}