{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"core:didError:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)SMICoreDelegate(im)core:didError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"core(_:didError:)"},"abstract":[{"text":"Delegate event that is triggered if an unhandled error is detected as part","type":"text"},{"text":" ","type":"text"},{"text":"of the normal activity of the In-App Messaging client.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didError:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:diderror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:diderror:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"core"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"text":" instance that is managing the current connection.","type":"text"}],"type":"paragraph"}],"name":"core"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" which triggered this event."}],"type":"paragraph"}],"name":"error"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didError:)":{"abstract":[{"type":"text","text":"Delegate event that is triggered if an unhandled error is detected as part"},{"type":"text","text":" "},{"type":"text","text":"of the normal activity of the In-App Messaging client."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didError"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:didError:"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:diderror:)","title":"core(_:didError:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Delegate used to receive events for the "},{"code":"SMICoreClient","type":"codeVoice"},{"type":"text","text":" framework. Use this protocol to listen"},{"type":"text","text":" "},{"type":"text","text":"for chat messages, receive message status changes, detect network status changes, and receive error messages."}],"role":"symbol","kind":"symbol","title":"CoreDelegate","url":"\/documentation\/smiclientcore\/coredelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"core:didError:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"core:didError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"core:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMICoreClient","kind":"typeIdentifier","text":"id<SMICoreClient>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"core"},{"kind":"text","text":" "},{"kind":"identifier","text":"didError:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"core"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" which triggered this event.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace"},{"value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace"},{"value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace"},{"value":"core:didError:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"core:didError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didError:)\/fragments","op":"replace"},{"value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","op":"replace"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace"},{"value":"SMICoreDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/title","op":"replace"},{"value":[{"text":"SMICoreDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/fragments","op":"replace"},{"value":[{"text":"SMICoreDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/navigatorTitle","op":"replace"}]}]}