{"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)"],"anchor":"Related-Documentation","title":"Related Documentation"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `-core:conversation:didUpdateEntries:` instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:didupdate:)-5msg3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coredelegate\/core(_:didupdate:)-5msg3"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-5msg3","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"core","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entry"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"core"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" data model that represents an incoming\/outgoing message."}],"type":"paragraph"}],"name":"entry"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"]]},"metadata":{"symbolKind":"method","platforms":[{"deprecated":true,"message":"Will be removed in a future version. Use `-core:conversation:didUpdateEntries:` instead.","unavailable":false,"beta":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:didUpdateEntry:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":")"}],"externalID":"c:objc(pl)SMICoreDelegate(im)core:didUpdateEntry:","title":"core(_:didUpdate:)","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didUpdate:)-5msg3":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-5msg3","role":"symbol","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didupdate:)-5msg3","abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:didUpdateEntry:"}],"title":"core(_:didUpdate:)","deprecated":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","title":"CoreDelegate","navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate used to receive events for the ","type":"text"},{"code":"SMICoreClient","type":"codeVoice"},{"text":" framework. Use this protocol to listen","type":"text"},{"text":" ","type":"text"},{"text":"for chat messages, receive message status changes, detect network status changes, and receive error messages.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didUpdateEntries:)":{"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didupdateentries:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"core:conversation:didUpdateEntries:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)","title":"core(_:conversation:didUpdateEntries:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":", ","kind":"text"},{"text":"didUpdateEntries","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":"])","kind":"text"}],"abstract":[{"text":"Delegate event that is triggered when a message’s status has been updated.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that any current references to an entry with a matching ID are refreshed.","type":"text"},{"text":" ","type":"text"},{"text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI","type":"text"},{"text":" ","type":"text"},{"text":"should account for that.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"beta":false,"deprecated":true,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"core:didUpdateEntry:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"core:didUpdateEntry:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)"],"anchor":"Related-Documentation","title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"core:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMICoreClient>","preciseIdentifier":"c:Qoobjc(pl)SMICoreClient"},{"kind":"text","text":") "},{"kind":"internalParam","text":"core"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateEntry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMIConversationEntry>","preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry"},{"kind":"text","text":") "},{"text":"entry","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"core"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"text":" data model that represents an incoming\/outgoing message.","type":"text"}],"type":"paragraph"}],"name":"entry"}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"Will be removed in a future version. Use `-core:conversation:didUpdateEntries:` instead.","type":"text"}],"type":"paragraph"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-5msg3\/title","value":"core:didUpdateEntry:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-5msg3\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didUpdateEntry:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/title","value":"SMICoreDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/fragments","value":[{"text":"SMICoreDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateEntries:)\/title","value":"core:conversation:didUpdateEntries:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateEntries:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:conversation:didUpdateEntries:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}