{"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/callKit","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode"]]},"kind":"symbol","abstract":[{"type":"text","text":"Errors related to Apple’s "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/callkit"},{"type":"text","text":" API."},{"type":"text","text":" "},{"type":"text","text":"These typically surface when managing call state in the background on a physical device."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"callKit"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaerrorcode\/callkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediaerrorcode\/callkit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"MultimediaErrorCode.callKit","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SMIMultimediaErrorCodeCallKit"}],"modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@E@SMIMultimediaErrorCode@SMIMultimediaErrorCodeCallKit","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callKit","kind":"identifier"}]},"references":{"https://developer.apple.com/documentation/callkit":{"identifier":"https:\/\/developer.apple.com\/documentation\/callkit","titleInlineContent":[{"type":"text","text":"CallKit"}],"title":"CallKit","url":"https:\/\/developer.apple.com\/documentation\/callkit","type":"link"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode":{"title":"MultimediaErrorCode","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode","kind":"symbol","navigatorTitle":[{"text":"MultimediaErrorCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaErrorCode"}],"abstract":[{"text":"An enum that defines the categories of errors that can occur within the multimedia client.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode/callKit":{"navigatorTitle":[{"text":"SMIMultimediaErrorCodeCallKit","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode\/callkit","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/callKit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callKit","kind":"identifier"}],"title":"MultimediaErrorCode.callKit","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Errors related to Apple’s "},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/callkit","type":"reference"},{"text":" API.","type":"text"},{"text":" ","type":"text"},{"text":"These typically surface when managing call state in the background on a physical device.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIMultimediaErrorCodeCallKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIMultimediaErrorCodeCallKit","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SMIMultimediaErrorCodeCallKit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/title","value":"SMIMultimediaErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/navigatorTitle","value":[{"text":"SMIMultimediaErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode~1callKit\/title","value":"SMIMultimediaErrorCodeCallKit"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode~1callKit\/fragments","value":[{"text":"SMIMultimediaErrorCodeCallKit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}