{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode"]]},"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"SMIMultimediaCommon"}],"role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/Equatable-Implementations"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaerrorcode\/equatable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode":{"title":"MultimediaErrorCode","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode","kind":"symbol","navigatorTitle":[{"text":"MultimediaErrorCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaErrorCode"}],"abstract":[{"text":"An enum that defines the categories of errors that can occur within the multimedia client.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode/!=(_:_:)":{"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/title","value":"SMIMultimediaErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaErrorCode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}