{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/multimediaProvider","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaerrorcode\/multimediaprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaerrorcode\/multimediaprovider"]}],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"SMIMultimediaCommon"}],"title":"MultimediaErrorCode.multimediaProvider","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SMIMultimediaErrorCodeMultimediaProvider","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@E@SMIMultimediaErrorCode@SMIMultimediaErrorCodeMultimediaProvider"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaProvider","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Errors originating from the underlying WebRTC library used to orchestrate the voice session.","type":"text"},{"text":" ","type":"text"},{"text":"These indicate a failure within the multimedia provider’s connection or media pipeline.","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode/multimediaProvider":{"navigatorTitle":[{"text":"SMIMultimediaErrorCodeMultimediaProvider","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode\/multimediaprovider","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode\/multimediaProvider","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaProvider","kind":"identifier"}],"title":"MultimediaErrorCode.multimediaProvider","kind":"symbol","type":"topic","abstract":[{"text":"Errors originating from the underlying WebRTC library used to orchestrate the voice session.","type":"text"},{"text":" ","type":"text"},{"text":"These indicate a failure within the multimedia provider’s connection or media pipeline.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode":{"title":"MultimediaErrorCode","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode","kind":"symbol","navigatorTitle":[{"text":"MultimediaErrorCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaErrorCode"}],"abstract":[{"text":"An enum that defines the categories of errors that can occur within the multimedia client.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIMultimediaErrorCodeMultimediaProvider","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIMultimediaErrorCodeMultimediaProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIMultimediaErrorCodeMultimediaProvider"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIMultimediaErrorCodeMultimediaProvider","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode~1multimediaProvider\/title"},{"op":"replace","value":[{"text":"SMIMultimediaErrorCodeMultimediaProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode~1multimediaProvider\/fragments"},{"op":"replace","value":"SMIMultimediaErrorCode","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/title"},{"op":"replace","value":[{"text":"SMIMultimediaErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/navigatorTitle"}]}]}