{"kind":"symbol","metadata":{"title":"formType","navigatorTitle":[{"kind":"identifier","text":"formType"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(pl)SMIPreChatConfiguration(py)formType","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"}],"symbolKind":"property"},"abstract":[{"text":"The type of form this configuration represents.","type":"text"},{"text":" ","type":"text"},{"text":"This value determines the form’s behavior and presentation.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/formType"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/formtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/formtype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","text":"SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that defines the available form types for pre-chat configurations."}],"type":"topic","title":"SMIPreChatConfigurationFormTypes","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreChatConfiguration"}],"abstract":[{"type":"text","text":"A protocol that defines the configuration for a pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatConfiguration"}],"kind":"symbol","title":"PreChatConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/formType":{"title":"formType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/formType","required":true,"url":"\/documentation\/smiclientcore\/prechatconfiguration\/formtype","role":"symbol","navigatorTitle":[{"text":"formType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"}],"kind":"symbol","abstract":[{"text":"The type of form this configuration represents.","type":"text"},{"text":" ","type":"text"},{"text":"This value determines the form’s behavior and presentation.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"formType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"formType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"],"anchor":"Related-Documentation","title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","text":"SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"formType"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIPreChatConfigurationFormTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle","op":"replace"},{"value":"SMIPreChatConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/title","op":"replace"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/navigatorTitle","op":"replace"},{"value":"formType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1formType\/title","op":"replace"},{"value":[{"text":"formType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1formType\/fragments","op":"replace"}]}]}