{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The list of hidden fields in the pre-chat form."},{"type":"text","text":" "},{"type":"text","text":"These fields are not displayed to users but can contain values set programmatically."},{"type":"text","text":" "},{"type":"text","text":"Each field is an instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIPreChatConfiguration(py)hiddenPreChatFields","modules":[{"name":"SMIClientCore"}],"required":true,"title":"hiddenPreChatFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"hiddenPreChatFields"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/hiddenPreChatFields","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","text":"HiddenPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/hiddenprechatfields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/hiddenprechatfields"]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/hiddenPreChatFields":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"]"}],"title":"hiddenPreChatFields","navigatorTitle":[{"kind":"identifier","text":"hiddenPreChatFields"}],"url":"\/documentation\/smiclientcore\/prechatconfiguration\/hiddenprechatfields","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/hiddenPreChatFields","required":true,"abstract":[{"text":"The list of hidden fields in the pre-chat form.","type":"text"},{"text":" ","type":"text"},{"text":"These fields are not displayed to users but can contain values set programmatically.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each field is an instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration":{"kind":"symbol","title":"PreChatConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreChatConfiguration"}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechatconfiguration","abstract":[{"text":"A protocol that defines the configuration for a pre-chat form.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a hidden pre-chat field in the conversation configuration."}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"title":"HiddenPreChatField","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hiddenPreChatFields"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hiddenPreChatFields"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIHiddenPreChatField>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"hiddenPreChatFields","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1hiddenPreChatFields\/title","value":"hiddenPreChatFields"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1hiddenPreChatFields\/fragments","value":[{"text":"hiddenPreChatFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/title","value":"SMIPreChatConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/fragments","value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/navigatorTitle","value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title","value":"SMIHiddenPreChatField"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}]}]}]}