{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration"]]},"sections":[],"abstract":[{"text":"The list of visible fields in the pre-chat form.","type":"text"},{"text":" ","type":"text"},{"text":"These fields are displayed to users and can be filled out directly.","type":"text"},{"text":" ","type":"text"},{"text":"Each field is an instance of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","isActive":true,"type":"reference"},{"text":".","type":"text"}],"metadata":{"required":true,"modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"]"}],"externalID":"c:objc(pl)SMIPreChatConfiguration(py)preChatFields","title":"preChatFields","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"preChatFields"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/prechatfields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatconfiguration\/prechatfields"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFields"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"typeIdentifier","text":"PreChatField"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/preChatFields","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/preChatFields":{"required":true,"abstract":[{"text":"The list of visible fields in the pre-chat form.","type":"text"},{"text":" ","type":"text"},{"text":"These fields are displayed to users and can be filled out directly.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each field is an instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},{"type":"text","text":"."}],"role":"symbol","title":"preChatFields","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"preChatFields"}],"type":"topic","url":"\/documentation\/smiclientcore\/prechatconfiguration\/prechatfields","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/preChatFields"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration":{"kind":"symbol","title":"PreChatConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreChatConfiguration"}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechatconfiguration","abstract":[{"text":"A protocol that defines the configuration for a pre-chat form.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatfield","kind":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"type":"topic","title":"PreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"preChatFields","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"preChatFields"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIPreChatField>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"preChatFields","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"preChatFields","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1preChatFields\/title"},{"value":[{"text":"preChatFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1preChatFields\/fragments"},{"value":"SMIPreChatConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIPreChatConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/fragments"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/navigatorTitle"},{"value":"SMIPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title"},{"value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}