{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsedatevalue\/datevalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsedatevalue\/datevalue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue\/dateValue"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"dateValue"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"8.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"8.0"}],"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"required":true,"title":"dateValue","externalID":"c:objc(pl)SMIFormResponseDateValue(py)dateValue","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"The date value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the date information selected by the user, without any time","type":"text"},{"type":"text","text":" "},{"type":"text","text":"components."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateValue/dateValue":{"kind":"symbol","title":"dateValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The date value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the date information selected by the user, without any time","type":"text"},{"text":" ","type":"text"},{"text":"components.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue\/dateValue","url":"\/documentation\/smiclientcore\/formresponsedatevalue\/datevalue","role":"symbol","navigatorTitle":[{"text":"dateValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateValue":{"title":"FormResponseDateValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDateValue","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FormResponseDateValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponsedatevalue","abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dateValue","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"dateValue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dateValue"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dateValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue~1dateValue\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue~1dateValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"dateValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/title","op":"replace","value":"SMIFormResponseDateValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}]}]}]}