{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/agentavailabilityinfo\/isagentavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/agentavailabilityinfo\/isagentavailable"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo\/isAgentAvailable"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAgentAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"Indicates whether the agent is availability.","type":"text"},{"text":" ","type":"text"},{"text":"When ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", an agents is considered to be available."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(pl)SMIAgentAvailabilityInfo(py)agentAvailable","modules":[{"name":"SMIClientCore"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAgentAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"agentAvailable"}],"title":"isAgentAvailable"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo/isAgentAvailable":{"type":"topic","url":"\/documentation\/smiclientcore\/agentavailabilityinfo\/isagentavailable","title":"isAgentAvailable","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo\/isAgentAvailable","navigatorTitle":[{"text":"agentAvailable","kind":"identifier"}],"abstract":[{"text":"Indicates whether the agent is availability.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When "},{"code":"true","type":"codeVoice"},{"type":"text","text":", an agents is considered to be available."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAgentAvailable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentAvailabilityInfo"}],"url":"\/documentation\/smiclientcore\/agentavailabilityinfo","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AgentAvailabilityInfo"}],"abstract":[{"type":"text","text":"A protocol that defines the agent availability configuration for a deployment."}],"title":"AgentAvailabilityInfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"agentAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"agentAvailable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"kind":"identifier","text":"isAgentAvailable"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"agentAvailable","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo~1isAgentAvailable\/title","value":"agentAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo~1isAgentAvailable\/fragments","value":[{"kind":"identifier","text":"agentAvailable"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/title","op":"replace","value":"SMIAgentAvailabilityInfo"},{"value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/fragments","op":"replace"},{"value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/navigatorTitle","op":"replace"}]}]}