{"kind":"symbol","seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation"}],"metadata":{"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIFormResponseInputs(py)formTitle","symbolKind":"property","title":"formTitle","navigatorTitle":[{"text":"formTitle","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTitle","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormTitleItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"},{"text":")?","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The title of the form response.","type":"text"},{"text":" ","type":"text"},{"text":"This property identifies which form this response corresponds to.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTitle"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/formTitle"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseinputs\/formtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseinputs\/formtitle"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs/formTitle":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTitle","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"abstract":[{"text":"The title of the form response.","type":"text"},{"text":" ","type":"text"},{"text":"This property identifies which form this response corresponds to.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"formTitle"}],"url":"\/documentation\/smiclientcore\/formresponseinputs\/formtitle","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/formTitle","title":"formTitle"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"url":"\/documentation\/smiclientcore\/formresponseinputs","abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","role":"symbol","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormResponseInputs"}],"type":"topic","title":"FormResponseInputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"formTitle","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"formTitle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"title":"Related Documentation","anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SMIFormTitleItem>","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTitle"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formTitle","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1formTitle\/title"},{"value":[{"text":"formTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1formTitle\/fragments"},{"value":"SMIFormResponseInputs","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title"},{"value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments"},{"value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle"},{"value":"SMIFormTitleItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}