{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseinputs\/inputvalues"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseinputs\/inputvalues"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/inputValues","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"],"title":"Related Documentation"}],"abstract":[{"type":"text","text":"The values collected from a user for each section of the form."},{"type":"text","text":" "},{"type":"text","text":"This array contains the user’s input for each field in the form."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"inputValues","navigatorTitle":[{"kind":"identifier","text":"inputValues"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValues"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIFormInputValue","kind":"typeIdentifier","text":"SMIFormInputValue"},{"kind":"text","text":"]"}],"externalID":"c:objc(pl)SMIFormResponseInputs(py)inputValues","required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputValues","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","text":"SMIFormInputValue","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue":{"url":"\/documentation\/smiclientcore\/smiforminputvalue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormInputValue","kind":"identifier"}],"title":"SMIFormInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SMIFormInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a form input value with its associated metadata."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs/inputValues":{"abstract":[{"type":"text","text":"The values collected from a user for each section of the form."},{"type":"text","text":" "},{"type":"text","text":"This array contains the user’s input for each field in the form."}],"type":"topic","navigatorTitle":[{"text":"inputValues","kind":"identifier"}],"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputValues","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInputValue","text":"SMIFormInputValue","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/formresponseinputs\/inputvalues","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/inputValues","title":"inputValues","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"role":"symbol","url":"\/documentation\/smiclientcore\/formresponseinputs","abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseInputs","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","type":"topic","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"kind":"symbol","title":"FormResponseInputs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"inputValues","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"inputValues"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"],"title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIFormInputValue>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"inputValues","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIFormInputValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/fragments","value":[{"text":"SMIFormInputValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/navigatorTitle","value":[{"text":"SMIFormInputValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1inputValues\/title","value":"inputValues","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1inputValues\/fragments","value":[{"kind":"identifier","text":"inputValues"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title","value":"SMIFormResponseInputs","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseInputs"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseInputs"}],"op":"replace"}]}]}