{"metadata":{"navigatorTitle":[{"text":"referenceId","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"referenceId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"referenceId","roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(pl)SMIPendingAttachmentUploadResult(py)referenceId"},"variants":[{"paths":["\/documentation\/smiclientcore\/pendingattachmentuploadresult\/referenceid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/pendingattachmentuploadresult\/referenceid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"A unique reference identifier for the pending upload.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to track the status of the upload or correlate it with other operations.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"referenceId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult\/referenceId"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PendingAttachmentUploadResult/referenceId":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"referenceId"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult\/referenceId","type":"topic","url":"\/documentation\/smiclientcore\/pendingattachmentuploadresult\/referenceid","title":"referenceId","abstract":[{"type":"text","text":"A unique reference identifier for the pending upload."},{"type":"text","text":" "},{"type":"text","text":"This can be used to track the status of the upload or correlate it with other operations."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PendingAttachmentUploadResult":{"url":"\/documentation\/smiclientcore\/pendingattachmentuploadresult","type":"topic","title":"PendingAttachmentUploadResult","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PendingAttachmentUploadResult","kind":"identifier"}],"navigatorTitle":[{"text":"PendingAttachmentUploadResult","kind":"identifier"}],"abstract":[{"text":"Represents an attachment upload that is in a pending state.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"referenceId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"referenceId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"referenceId","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"referenceId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult~1referenceId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"referenceId"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult~1referenceId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/title","value":"SMIPendingAttachmentUploadResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/fragments","value":[{"kind":"identifier","text":"SMIPendingAttachmentUploadResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/navigatorTitle","value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}