{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/identifier","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/choicelist\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicelist\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","required":true,"externalID":"c:objc(pl)SMIChoiceList(py)identifier","role":"symbol","title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"The unique identifier for this choice list."},{"type":"text","text":" "},{"type":"text","text":"This ID is used to reference the choice list in configurations and dependencies."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList/identifier":{"url":"\/documentation\/smiclientcore\/choicelist\/identifier","abstract":[{"text":"The unique identifier for this choice list.","type":"text"},{"text":" ","type":"text"},{"text":"This ID is used to reference the choice list in configurations and dependencies.","type":"text"}],"role":"symbol","required":true,"kind":"symbol","title":"identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/identifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}],"title":"ChoiceList","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"identifier","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"identifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1identifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1identifier\/fragments","op":"replace"},{"value":"SMIChoiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoiceList"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoiceList"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","op":"replace"}]}]}