{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"]]},"abstract":[{"type":"text","text":"The array of available options in this choice list."},{"type":"text","text":" "},{"type":"text","text":"Each value in the array is a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue"},{"type":"text","text":" that defines a selectable option."}],"variants":[{"paths":["\/documentation\/smiclientcore\/choicelist\/values"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicelist\/values"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"values","kind":"identifier"},{"text":": [any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","preciseIdentifier":"c:objc(pl)SMIChoiceListValue","text":"ChoiceListValue","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/values"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"values"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"required":true,"roleHeading":"Instance Property","title":"values","externalID":"c:objc(pl)SMIChoiceList(py)values","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"values"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListValue","text":"ChoiceListValue"},{"kind":"text","text":"]"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList/values":{"url":"\/documentation\/smiclientcore\/choicelist\/values","title":"values","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/values","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"values"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"ChoiceListValue","preciseIdentifier":"c:objc(pl)SMIChoiceListValue"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The array of available options in this choice list."},{"type":"text","text":" "},{"type":"text","text":"Each value in the array is a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","isActive":true},{"type":"text","text":" that defines a selectable option."}],"navigatorTitle":[{"kind":"identifier","text":"values"}],"kind":"symbol","type":"topic","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue":{"abstract":[{"text":"A protocol that defines a single option within a choice list in pre-chat.","type":"text"}],"url":"\/documentation\/smiclientcore\/choicelistvalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceListValue"}],"navigatorTitle":[{"text":"ChoiceListValue","kind":"identifier"}],"title":"ChoiceListValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}],"title":"ChoiceList","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"values","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"values","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIChoiceListValue>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"values","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1values\/title","value":"values"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1values\/fragments","value":[{"kind":"identifier","text":"values"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/title","value":"SMIChoiceListValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/fragments","value":[{"text":"SMIChoiceListValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/navigatorTitle","value":[{"text":"SMIChoiceListValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","value":"SMIChoiceList"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}]}]}]}