{"variants":[{"paths":["\/documentation\/smiclientcore\/citedinlinemetadata\/citedlocationoffset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citedinlinemetadata\/citedlocationoffset"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)SMICitedInlineMetadata(py)citedLocationOffset","required":true,"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedLocationOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"symbolKind":"property","navigatorTitle":[{"text":"citedLocationOffset","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"citedLocationOffset"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/citedLocationOffset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The ending position of the citation in the text."},{"type":"text","text":" "},{"type":"text","text":"This offset represents the index where the citation should end in the text content."},{"type":"text","text":" "},{"type":"text","text":"The offset is exclusive, meaning it points to the character immediately after the last"},{"type":"text","text":" "},{"type":"text","text":"character of the citation."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedLocationOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata":{"title":"CitedInlineMetadata","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","abstract":[{"type":"text","text":"A protocol that represents inline metadata for a citation, including its location and claim information."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedInlineMetadata","kind":"identifier"}],"navigatorTitle":[{"text":"CitedInlineMetadata","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata/citedLocationOffset":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"citedLocationOffset"}],"title":"citedLocationOffset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedLocationOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"required":true,"url":"\/documentation\/smiclientcore\/citedinlinemetadata\/citedlocationoffset","abstract":[{"text":"The ending position of the citation in the text.","type":"text"},{"text":" ","type":"text"},{"text":"This offset represents the index where the citation should end in the text content.","type":"text"},{"text":" ","type":"text"},{"text":"The offset is exclusive, meaning it points to the character immediately after the last","type":"text"},{"text":" ","type":"text"},{"text":"character of the citation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/citedLocationOffset"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"citedLocationOffset","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"citedLocationOffset"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedLocationOffset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMICitedInlineMetadata","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICitedInlineMetadata"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/fragments"},{"op":"replace","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/navigatorTitle"},{"op":"replace","value":"citedLocationOffset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1citedLocationOffset\/title"},{"op":"replace","value":[{"kind":"identifier","text":"citedLocationOffset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1citedLocationOffset\/fragments"}]}]}