{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citedinlinemetadata\/claim"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citedinlinemetadata\/claim"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/claim","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"claim","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claim","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICitationClaim","text":"CitationClaim","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)SMICitedInlineMetadata(py)claim","required":true,"modules":[{"name":"SMIClientCore"}],"title":"claim"},"abstract":[{"text":"The claim information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to the start and end offsets of the cited content","type":"text"},{"text":" ","type":"text"},{"text":"through the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim"},{"text":" protocol. When present, it defines the exact location","type":"text"},{"text":" ","type":"text"},{"text":"of the citation within the text.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claim","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","preciseIdentifier":"c:objc(pl)SMICitationClaim","text":"CitationClaim","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim":{"url":"\/documentation\/smiclientcore\/citationclaim","abstract":[{"text":"A protocol that represents the location of a citation within a text message.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","role":"symbol","navigatorTitle":[{"text":"CitationClaim","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CitationClaim","kind":"identifier"}],"type":"topic","title":"CitationClaim"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedInlineMetadata"}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedInlineMetadata"}],"abstract":[{"type":"text","text":"A protocol that represents inline metadata for a citation, including its location and claim information."}],"title":"CitedInlineMetadata","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata/claim":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"claim"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"CitationClaim","preciseIdentifier":"c:objc(pl)SMICitationClaim"},{"kind":"text","text":")?"}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata\/claim","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"claim"}],"abstract":[{"text":"The claim information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to the start and end offsets of the cited content","type":"text"},{"text":" ","type":"text"},{"text":"through the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim"},{"text":" protocol. When present, it defines the exact location","type":"text"},{"text":" ","type":"text"},{"text":"of the citation within the text.","type":"text"}],"title":"claim","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/claim"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"claim","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"claim","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMICitationClaim>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMICitationClaim"},{"text":" ","kind":"text"},{"text":"claim","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMICitationClaim","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/title"},{"op":"replace","value":[{"text":"SMICitationClaim","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/fragments"},{"op":"replace","value":[{"text":"SMICitationClaim","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/navigatorTitle"},{"op":"replace","value":"SMICitedInlineMetadata","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICitedInlineMetadata"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/fragments"},{"op":"replace","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/navigatorTitle"},{"op":"replace","value":"claim","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1claim\/title"},{"op":"replace","value":[{"kind":"identifier","text":"claim"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1claim\/fragments"}]}]}