{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isRequired"}],"externalID":"c:objc(pl)SMITermsAndConditions(py)isRequired","title":"isRequired","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRequired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions"]]},"abstract":[{"type":"text","text":"Indicates whether users must accept the terms and conditions."},{"type":"text","text":" "},{"type":"text","text":"When true, users must acknowledge the terms before proceeding with the chat."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isRequired"},"variants":[{"paths":["\/documentation\/smiclientcore\/termsandconditions\/isrequired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/termsandconditions\/isrequired"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions":{"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines the terms and conditions for the pre-chat form."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsAndConditions"}],"navigatorTitle":[{"kind":"identifier","text":"TermsAndConditions"}],"kind":"symbol","type":"topic","title":"TermsAndConditions","url":"\/documentation\/smiclientcore\/termsandconditions"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions/isRequired":{"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isRequired"}],"abstract":[{"type":"text","text":"Indicates whether users must accept the terms and conditions."},{"type":"text","text":" "},{"type":"text","text":"When true, users must acknowledge the terms before proceeding with the chat."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isRequired","type":"topic","url":"\/documentation\/smiclientcore\/termsandconditions\/isrequired","title":"isRequired"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isRequired","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isRequired","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRequired"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMITermsAndConditions","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/title"},{"value":[{"kind":"identifier","text":"SMITermsAndConditions"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/fragments"},{"value":[{"text":"SMITermsAndConditions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/navigatorTitle"},{"value":"isRequired","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isRequired\/title"},{"value":[{"kind":"identifier","text":"isRequired"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isRequired\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}