{"abstract":[{"text":"The title of the form.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides the main heading for the form.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTitle","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","externalID":"c:objc(pl)SMIFormInputs(py)formTitle","navigatorTitle":[{"text":"formTitle","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTitle","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"}],"title":"formTitle","modules":[{"name":"SMIClientCore"}],"required":true,"roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/formTitle","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"]]},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/forminputs\/formtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputs\/formtitle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","role":"symbol","abstract":[{"text":"A protocol that defines the structure for title components used in forms.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/formTitle":{"navigatorTitle":[{"kind":"identifier","text":"formTitle"}],"required":true,"title":"formTitle","url":"\/documentation\/smiclientcore\/forminputs\/formtitle","abstract":[{"type":"text","text":"The title of the form."},{"type":"text","text":" "},{"type":"text","text":"This property provides the main heading for the form."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/formTitle","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTitle"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"url":"\/documentation\/smiclientcore\/forminputs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"text":"A protocol that represents a form in a conversation.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"formTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"formTitle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SMIFormTitleItem>","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTitle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"},{"value":"formTitle","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1formTitle\/title"},{"value":[{"text":"formTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1formTitle\/fragments"},{"value":"SMIFormInputs","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormInputs"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}