{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A message which optionally accompanies a form.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides additional context or instructions for the form.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/message"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputs\/message"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputs\/message"]}],"sections":[],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation"}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"message","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormTitleItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)SMIFormInputs(py)message","symbolKind":"property","navigatorTitle":[{"text":"message","kind":"identifier"}],"required":true,"roleHeading":"Instance Property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/message":{"required":true,"navigatorTitle":[{"text":"message","kind":"identifier"}],"role":"symbol","title":"message","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/message","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/smiclientcore\/forminputs\/message","abstract":[{"type":"text","text":"A message which optionally accompanies a form."},{"type":"text","text":" "},{"type":"text","text":"This property provides additional context or instructions for the form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"kind":"symbol","role":"symbol","type":"topic","title":"FormInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"abstract":[{"type":"text","text":"A protocol that represents a form in a conversation."}],"url":"\/documentation\/smiclientcore\/forminputs","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"message","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"message","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFormTitleItem>","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1message\/title","value":"message","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1message\/fragments","value":[{"kind":"identifier","text":"message"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title","value":"SMIFormInputs","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments","value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormInputs"}],"op":"replace"}]}]}