{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/reply"},"metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"reply","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIFormInputs(py)reply","modules":[{"name":"SMIClientCore"}],"title":"reply","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"abstract":[{"text":"The reply text for the form.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reply"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier","text":"FormTitleItem"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"]]},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/forminputs\/reply"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputs\/reply"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/reply":{"url":"\/documentation\/smiclientcore\/forminputs\/reply","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/reply","abstract":[{"text":"The reply text for the form.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reply"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"},{"kind":"text","text":")?"}],"required":true,"type":"topic","title":"reply"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"type":"text","text":"A protocol that represents a form in a conversation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/forminputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reply"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reply"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation","title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem","text":"id<SMIFormTitleItem>"},{"kind":"text","text":" "},{"kind":"identifier","text":"reply"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1reply\/title","value":"reply","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1reply\/fragments","value":[{"text":"reply","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title","value":"SMIFormInputs","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments","value":[{"kind":"identifier","text":"SMIFormInputs"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormInputs"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace"}]}]}