{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"]]},"metadata":{"externalID":"c:objc(pl)SMIFormInputs(py)result","symbolKind":"property","navigatorTitle":[{"text":"result","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormResponseResult","preciseIdentifier":"c:objc(pl)SMIFormResponseResult","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"modules":[{"name":"SMIClientCore"}],"title":"result","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"The result of the form."},{"type":"text","text":" "},{"type":"text","text":"This value is set once the acknowledgment is received after the form response is sent to the server."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","text":"FormResponseResult","preciseIdentifier":"c:objc(pl)SMIFormResponseResult"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/result"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult"],"anchor":"Related-Documentation","title":"Related Documentation"}],"variants":[{"paths":["\/documentation\/smiclientcore\/forminputs\/result"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputs\/result"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"url":"\/documentation\/smiclientcore\/forminputs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"text":"A protocol that represents a form in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult":{"navigatorTitle":[{"text":"FormResponseResult","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","title":"FormResponseResult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResult","kind":"identifier"}],"abstract":[{"text":"A protocol that represents the server’s response to a form submission.","type":"text"}],"url":"\/documentation\/smiclientcore\/formresponseresult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/result":{"url":"\/documentation\/smiclientcore\/forminputs\/result","abstract":[{"type":"text","text":"The result of the form."},{"type":"text","text":" "},{"type":"text","text":"This value is set once the acknowledgment is received after the form response is sent to the server."}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/result","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormResponseResult","text":"FormResponseResult","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"result","role":"symbol","navigatorTitle":[{"text":"result","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"result"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"result","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult"],"title":"Related Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SMIFormResponseResult>","preciseIdentifier":"c:Qoobjc(pl)SMIFormResponseResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title","op":"replace","value":"SMIFormInputs"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputs"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle","op":"replace","value":[{"text":"SMIFormInputs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/title","op":"replace","value":"SMIFormResponseResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1result\/title","op":"replace","value":"result"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1result\/fragments","op":"replace","value":[{"kind":"identifier","text":"result"}]}]}]}