{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/sections","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"sections","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sections","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputSection","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInputSection"},{"text":"]","kind":"text"}],"externalID":"c:objc(pl)SMIFormInputs(py)sections","required":true,"modules":[{"name":"SMIClientCore"}],"title":"sections"},"abstract":[{"text":"The sections which individually represent a single input for each form field.","type":"text"},{"text":" ","type":"text"},{"text":"Each section contains one input field that collects user data.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sections"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInputSection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","text":"FormInputSection"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"]]},"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"],"anchor":"Related-Documentation"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputs\/sections"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputs\/sections"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"type":"text","text":"A protocol that represents a form in a conversation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/forminputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/sections":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sections","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInputSection","text":"FormInputSection","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/forminputs\/sections","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"sections","kind":"identifier"}],"abstract":[{"text":"The sections which individually represent a single input for each form field.","type":"text"},{"text":" ","type":"text"},{"text":"Each section contains one input field that collects user data.","type":"text"}],"title":"sections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/sections"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection":{"title":"FormInputSection","abstract":[{"text":"A protocol that defines the base type for form input sections.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminputsection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputSection","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputSection","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sections","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"sections","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"],"title":"Related Documentation","anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIFormInputSection>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"sections","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormInputs","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title","op":"replace"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputs"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle","op":"replace"},{"value":"sections","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1sections\/title","op":"replace"},{"value":[{"text":"sections","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1sections\/fragments","op":"replace"},{"value":"SMIFormInputSection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputSection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/fragments","op":"replace"},{"value":[{"text":"SMIFormInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/navigatorTitle","op":"replace"}]}]}