{"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation","title":"Related Documentation"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionTitle"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionTitle"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","kind":"typeIdentifier","text":"FormTitleItem"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The title of this selected option."},{"type":"text","text":" "},{"type":"text","text":"This property contains the visual representation of the selected option, including its"},{"type":"text","text":" "},{"type":"text","text":"text content and any associated styling or formatting."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/selectedoption\/optiontitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/selectedoption\/optiontitle"]}],"metadata":{"required":true,"modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionTitle"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier","text":"FormTitleItem"}],"title":"optionTitle","roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormSelectedOption(py)optionTitle","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"optionTitle"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption/optionTitle":{"title":"optionTitle","role":"symbol","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionTitle","navigatorTitle":[{"text":"optionTitle","kind":"identifier"}],"abstract":[{"type":"text","text":"The title of this selected option."},{"type":"text","text":" "},{"type":"text","text":"This property contains the visual representation of the selected option, including its"},{"type":"text","text":" "},{"type":"text","text":"text content and any associated styling or formatting."}],"url":"\/documentation\/smiclientcore\/selectedoption\/optiontitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionTitle","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/selectedoption","type":"topic","title":"SelectedOption","abstract":[{"text":"A protocol that defines a selected option in a multi-option form input.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectedOption"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption","navigatorTitle":[{"kind":"identifier","text":"SelectedOption"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"optionTitle","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"optionTitle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"title":"Related Documentation","anchor":"Related-Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem","text":"id<SMIFormTitleItem>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"optionTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"optionTitle","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionTitle\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"optionTitle"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionTitle\/fragments"},{"op":"replace","value":"SMIFormSelectedOption","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/title"},{"op":"replace","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/fragments"},{"op":"replace","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/navigatorTitle"},{"op":"replace","value":"SMIFormTitleItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"op":"replace","value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"}]}]}