{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse\/selectedValues"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedValues"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"required":true,"symbolKind":"property","role":"symbol","title":"selectedValues","externalID":"c:objc(pl)SMIChoicesExperienceTypeResponse(py)selectedValues","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedValues","kind":"identifier"},{"text":": [[","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]]","kind":"text"}],"navigatorTitle":[{"text":"selectedValues","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choicesexperiencetyperesponse\/selectedvalues"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choicesexperiencetyperesponse\/selectedvalues"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","navigatorTitle":[{"kind":"identifier","text":"ChoicesExperienceTypeResponse"}],"kind":"symbol","title":"ChoicesExperienceTypeResponse","url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoicesExperienceTypeResponse"}],"role":"symbol","type":"topic","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse/selectedValues":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedValues"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]"}],"navigatorTitle":[{"kind":"identifier","text":"selectedValues"}],"url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse\/selectedvalues","required":true,"title":"selectedValues","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse\/selectedValues","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"selectedValues"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"selectedValues","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSDictionary<NSString *,id> *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"selectedValues"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/title","value":"SMIChoicesExperienceTypeResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/fragments","op":"replace","value":[{"text":"SMIChoicesExperienceTypeResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse~1selectedValues\/title","op":"replace","value":"selectedValues"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse~1selectedValues\/fragments","op":"replace","value":[{"text":"selectedValues","kind":"identifier"}]}]}]}