{"metadata":{"roleHeading":"API Collection","modules":[{"name":"SMIClientCore"}],"title":"Equatable Implementations","role":"collectionGroup"},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","title":"FormResponseErrorType","abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseErrorType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FormResponseErrorType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/!=(_:_:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype\/!=(_:_:)","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title","op":"replace","value":"SMIFormResponseErrorType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}