{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formRequestExpired"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"formRequestExpired","externalID":"c:@SMIFormResponseErrorTypeFormRequestExpired","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeFormRequestExpired"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formRequestExpired"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/formRequestExpired"},"abstract":[{"type":"text","text":"The form is no longer eligible for submission."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/formrequestexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/formrequestexpired"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"title":"FormResponseErrorType","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseErrorType"}],"abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/formRequestExpired":{"type":"topic","abstract":[{"type":"text","text":"The form is no longer eligible for submission."}],"title":"formRequestExpired","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formRequestExpired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseErrorType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/formRequestExpired","kind":"symbol","navigatorTitle":[{"text":"SMIFormResponseErrorTypeFormRequestExpired","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/formrequestexpired"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseErrorTypeFormRequestExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseErrorTypeFormRequestExpired"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseErrorTypeFormRequestExpired"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title","value":"SMIFormResponseErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1formRequestExpired\/title","value":"SMIFormResponseErrorTypeFormRequestExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1formRequestExpired\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseErrorTypeFormRequestExpired"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}