{"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/invalidformresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/invalidformresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/invalidFormResponse","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFormResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormResponseErrorType","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType"}],"externalID":"c:@SMIFormResponseErrorTypeInvalidFormResponse","title":"invalidFormResponse","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeInvalidFormResponse"}],"roleHeading":"Type Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidFormResponse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","text":"FormResponseErrorType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"]]},"abstract":[{"type":"text","text":"A validation error occurred on the submitted form."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"url":"\/documentation\/smiclientcore\/formresponseerrortype","title":"FormResponseErrorType","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/invalidFormResponse":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/invalidFormResponse","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidFormResponse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","text":"FormResponseErrorType","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/invalidformresponse","navigatorTitle":[{"text":"SMIFormResponseErrorTypeInvalidFormResponse","kind":"identifier"}],"abstract":[{"text":"A validation error occurred on the submitted form.","type":"text"}],"title":"invalidFormResponse","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormResponseErrorTypeInvalidFormResponse","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseErrorTypeInvalidFormResponse","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseErrorType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseErrorTypeInvalidFormResponse","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title","value":"SMIFormResponseErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1invalidFormResponse\/title","value":"SMIFormResponseErrorTypeInvalidFormResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1invalidFormResponse\/fragments","value":[{"text":"SMIFormResponseErrorTypeInvalidFormResponse","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}