{"kind":"symbol","abstract":[{"type":"text","text":"An API error prevented the successful submission of the form."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/typeapiresulterrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/typeapiresulterrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeApiResultErrorCode"}],"roleHeading":"Type Property","symbolKind":"property","title":"typeApiResultErrorCode","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeApiResultErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormResponseErrorType","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType"}],"role":"symbol","extendedModule":"SMIClientCore","externalID":"c:@SMIFormResponseErrorTypeTypeApiResultErrorCode"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeApiResultErrorCode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"typeApiResultErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","text":"FormResponseErrorType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"}]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/typeApiResultErrorCode":{"kind":"symbol","abstract":[{"text":"An API error prevented the successful submission of the form.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeApiResultErrorCode"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/typeapiresulterrorcode","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeApiResultErrorCode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeApiResultErrorCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}],"title":"typeApiResultErrorCode"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"title":"FormResponseErrorType","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseErrorType"}],"abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseErrorTypeTypeApiResultErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeApiResultErrorCode"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeApiResultErrorCode"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeApiResultErrorCode\/title","value":"SMIFormResponseErrorTypeTypeApiResultErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeApiResultErrorCode\/fragments","value":[{"text":"SMIFormResponseErrorTypeTypeApiResultErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title","value":"SMIFormResponseErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle","value":[{"text":"SMIFormResponseErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}