{"kind":"symbol","metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"}],"externalID":"c:@SMIFormResponseErrorTypeTypeInternalServerError","symbolKind":"property","title":"typeInternalServerError","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"typeInternalServerError","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","text":"FormResponseErrorType"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"An internal service error was triggered preventing the submission of the form."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"typeInternalServerError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","text":"FormResponseErrorType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeInternalServerError"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/typeinternalservererror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseerrortype\/typeinternalservererror"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","title":"FormResponseErrorType","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseErrorType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/typeInternalServerError":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeInternalServerError","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype\/typeinternalservererror","abstract":[{"type":"text","text":"An internal service error was triggered preventing the submission of the form."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"typeInternalServerError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseErrorType","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"}],"title":"typeInternalServerError"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseErrorTypeTypeInternalServerError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","text":"SMIFormResponseErrorType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SMIFormResponseErrorType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle"},{"op":"replace","value":"SMIFormResponseErrorTypeTypeInternalServerError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeInternalServerError\/title"},{"op":"replace","value":[{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeInternalServerError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}