{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider"]]},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection"},"kind":"article","variants":[{"paths":["\/documentation\/smiclientcore\/voiceprovider\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/Equatable-Implementations"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"navigatorTitle":[{"kind":"identifier","text":"VoiceProvider"}],"url":"\/documentation\/smiclientcore\/voiceprovider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","title":"VoiceProvider"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/!=(_:_:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/voiceprovider\/!=(_:_:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/title","value":"SMIVoiceProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/fragments","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/navigatorTitle","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"}]}]}