{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/init(rawValue:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(rawValue:)","externalID":"s:So16SMIVoiceProvidera8rawValueABSS_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"init","modules":[{"name":"SMIClientCore"}],"roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/voiceprovider\/init(rawvalue:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/voiceprovider\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"navigatorTitle":[{"kind":"identifier","text":"VoiceProvider"}],"url":"\/documentation\/smiclientcore\/voiceprovider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","title":"VoiceProvider"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/title","value":"SMIVoiceProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/fragments","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/navigatorTitle","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"}]}]}