{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoiceProvider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","kind":"typeIdentifier","preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/liveKit","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@SMIVoiceProviderLiveKit","symbolKind":"property","title":"liveKit","extendedModule":"SMIMultimediaCommon","navigatorTitle":[{"kind":"identifier","text":"SMIVoiceProviderLiveKit"}],"role":"symbol","modules":[{"name":"SMIClientCore","relatedModules":["SMIMultimediaCommon"]}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveKit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","kind":"typeIdentifier","text":"VoiceProvider"}]},"abstract":[{"type":"text","text":"Voice connection serviced via LiveKit"}],"variants":[{"paths":["\/documentation\/smiclientcore\/voiceprovider\/livekit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/voiceprovider\/livekit"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"navigatorTitle":[{"kind":"identifier","text":"VoiceProvider"}],"url":"\/documentation\/smiclientcore\/voiceprovider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","title":"VoiceProvider"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/liveKit":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoiceProvider","kind":"typeIdentifier","preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider"}],"abstract":[{"text":"Voice connection serviced via LiveKit","type":"text"}],"navigatorTitle":[{"text":"SMIVoiceProviderLiveKit","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/voiceprovider\/livekit","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/liveKit","title":"liveKit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIVoiceProviderLiveKit","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIVoiceProviderLiveKit"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIVoiceProvider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIVoiceProviderLiveKit"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/title","op":"replace","value":"SMIVoiceProvider"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider~1liveKit\/title","op":"replace","value":"SMIVoiceProviderLiveKit"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider~1liveKit\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIVoiceProviderLiveKit"}]}]}]}