{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversation\/activemodalities"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversation\/activemodalities"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeModalities","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeModalities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","preciseIdentifier":"c:SMIModality.h@T@SMIModality","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"text":"XXX: JWRIGHT DOCS","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"]]},"metadata":{"symbolKind":"property","required":true,"role":"symbol","navigatorTitle":[{"text":"activeModalities","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeModalities","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:objc(pl)SMIConversation(py)activeModalities","title":"activeModalities","modules":[{"name":"SMIClientCore"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/activeModalities":{"url":"\/documentation\/smiclientcore\/conversation\/activemodalities","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeModalities","abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeModalities"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"]"}],"required":true,"type":"topic","title":"activeModalities"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"activeModalities","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"activeModalities"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"activeModalities"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"activeModalities","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeModalities\/title","op":"replace"},{"value":[{"kind":"identifier","text":"activeModalities"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeModalities\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"kind":"identifier","text":"SMIConversation"}]},{"value":[{"kind":"identifier","text":"SMIConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"}]}]}