{"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"],"title":"Related Documentation","anchor":"Related-Documentation"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/hiddenPreChatFields"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversation\/hiddenprechatfields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversation\/hiddenprechatfields"]}],"metadata":{"externalID":"c:objc(pl)SMIConversation(py)hiddenPreChatFields","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","text":"HiddenPreChatField","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"hiddenPreChatFields","kind":"identifier"}],"title":"hiddenPreChatFields","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"]]},"abstract":[{"text":"The list of hidden pre-chat fields associated with this conversation.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"abstract":[{"text":"A protocol that represents a hidden pre-chat field in the conversation configuration.","type":"text"}],"title":"HiddenPreChatField","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"kind":"symbol","title":"Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/smiclientcore\/conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/hiddenPreChatFields":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"kind":"text","text":"]"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/hiddenPreChatFields","abstract":[{"text":"The list of hidden pre-chat fields associated with this conversation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"hiddenPreChatFields"}],"type":"topic","title":"hiddenPreChatFields","required":true,"url":"\/documentation\/smiclientcore\/conversation\/hiddenprechatfields"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hiddenPreChatFields"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hiddenPreChatFields"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"],"title":"Related Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<SMIHiddenPreChatField>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hiddenPreChatFields"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title","op":"replace","value":"SMIHiddenPreChatField"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle","op":"replace","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace","value":"SMIConversation"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1hiddenPreChatFields\/title","op":"replace","value":"hiddenPreChatFields"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1hiddenPreChatFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"hiddenPreChatFields"}]}]}]}