{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversation\/inboundhighwatermark"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversation\/inboundhighwatermark"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inboundHighWaterMark"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Inbound in this case refers to the direction of the read acknowledgement. It is the logical reverse of the direction of the message itself."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/inboundHighWaterMark"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Holds a reference to a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" representing what has been marked as read by the remote participant.","type":"text"}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(pl)SMIConversation(py)inboundHighWaterMark","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"inboundHighWaterMark","kind":"identifier"}],"title":"inboundHighWaterMark","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")?","kind":"text"}],"required":true,"symbolKind":"property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","title":"Conversation","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/inboundHighWaterMark":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")?","kind":"text"}],"role":"symbol","abstract":[{"text":"Holds a reference to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"text":" representing what has been marked as read by the remote participant.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/inboundHighWaterMark","title":"inboundHighWaterMark","type":"topic","navigatorTitle":[{"text":"inboundHighWaterMark","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/conversation\/inboundhighwatermark","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"inboundHighWaterMark"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"inboundHighWaterMark"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"id<SMIConversationEntry>"},{"kind":"text","text":" "},{"kind":"identifier","text":"inboundHighWaterMark"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace","value":"SMIConversation"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1inboundHighWaterMark\/title","op":"replace","value":"inboundHighWaterMark"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1inboundHighWaterMark\/fragments","op":"replace","value":[{"text":"inboundHighWaterMark","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}