{"sections":[],"abstract":[{"text":"Holds a reference to a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"text":" representing what has been marked as read by the consuming client.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/outboundHighWaterMark","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Note: Outbound in this case refers to the direction of the read acknowledgement. It is the logical reverse of the direction of the message itself."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversation\/outboundhighwatermark"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversation\/outboundhighwatermark"]}],"metadata":{"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIConversation(py)outboundHighWaterMark","symbolKind":"property","title":"outboundHighWaterMark","navigatorTitle":[{"kind":"identifier","text":"outboundHighWaterMark"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outboundHighWaterMark"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":")?"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/outboundHighWaterMark":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/outboundHighWaterMark","title":"outboundHighWaterMark","navigatorTitle":[{"text":"outboundHighWaterMark","kind":"identifier"}],"abstract":[{"text":"Holds a reference to a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":" representing what has been marked as read by the consuming client."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversation\/outboundhighwatermark","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")?","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"outboundHighWaterMark","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"outboundHighWaterMark","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIConversationEntry>","preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"outboundHighWaterMark","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1outboundHighWaterMark\/title","value":"outboundHighWaterMark","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1outboundHighWaterMark\/fragments","value":[{"text":"outboundHighWaterMark","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace"}]}]}