{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversation\/supportedmodalities"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversation\/supportedmodalities"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)SMIConversation(py)supportedModalities","title":"supportedModalities","required":true,"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"supportedModalities","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"]","kind":"text"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/supportedModalities","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/supportedModalities":{"title":"supportedModalities","required":true,"abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"url":"\/documentation\/smiclientcore\/conversation\/supportedmodalities","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/supportedModalities","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"supportedModalities","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"supportedModalities","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"supportedModalities","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIConversation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace"},{"value":"supportedModalities","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1supportedModalities\/title","op":"replace"},{"value":[{"text":"supportedModalities","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1supportedModalities\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}