{"abstract":[{"type":"text","text":"A message containing a list of choices for the user."}],"metadata":{"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","externalID":"c:@SMIConversationEntryMessageTypesChoices","extendedModule":"SMIClientCore","role":"symbol","title":"choices","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier","text":"ConversationEntryMessageTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoices"}],"roleHeading":"Type Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/choices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/choices"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choices"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","text":"ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"title":"ConversationEntryMessageTypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/choices":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choices","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}],"type":"topic","abstract":[{"text":"A message containing a list of choices for the user.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/choices","title":"choices","navigatorTitle":[{"text":"SMIConversationEntryMessageTypesChoices","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choices","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIConversationEntryMessageTypesChoices","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIConversationEntryMessageTypesChoices","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"SMIConversationEntryMessageTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoices"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIConversationEntryMessageTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle"},{"op":"replace","value":"SMIConversationEntryMessageTypesChoices","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choices\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoices"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choices\/fragments"}]}]}