{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/!=(_:_:)"],"generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"title":"ConversationEntryMessageTypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/!=(_:_:)","abstract":[],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/!=(_:_:)","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIConversationEntryMessageTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title"},{"value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments"},{"value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle"}]}]}