{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/formresponsemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/formresponsemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@SMIConversationEntryMessageTypesFormResponseMessage","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formResponseMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIConversationEntryMessageTypesFormResponseMessage","kind":"identifier"}],"symbolKind":"property","roleHeading":"Type Property","title":"formResponseMessage","extendedModule":"SMIClientCore"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formResponseMessage"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"abstract":[{"text":"A message containing a form submission response.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formResponseMessage","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","text":"ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"title":"ConversationEntryMessageTypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/formResponseMessage":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formResponseMessage","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/formresponsemessage","abstract":[{"text":"A message containing a form submission response.","type":"text"}],"title":"formResponseMessage","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SMIConversationEntryMessageTypesFormResponseMessage","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formResponseMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryMessageTypesFormResponseMessage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesFormResponseMessage","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"SMIConversationEntryMessageTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryMessageTypesFormResponseMessage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title","op":"replace","value":"SMIConversationEntryMessageTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formResponseMessage\/title","op":"replace","value":"SMIConversationEntryMessageTypesFormResponseMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formResponseMessage\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesFormResponseMessage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}