{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Initializer","externalID":"s:So32SMIConversationEntryMessageTypesa8rawValueABSS_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","symbolKind":"init"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/init(rawValue:)"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/init(rawvalue:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"title":"ConversationEntryMessageTypes","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryMessageTypes"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntryMessageTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/init(rawValue:)":{"role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIConversationEntryMessageTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments"},{"value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle"}]}]}