{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/staticcontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/staticcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"staticContent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","text":"ConversationEntryMessageTypes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/staticContent","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","title":"staticContent","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesStaticContent"}],"externalID":"c:@SMIConversationEntryMessageTypesStaticContent","symbolKind":"property","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"staticContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes"}]},"abstract":[{"type":"text","text":"A message containing static content."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/staticContent":{"navigatorTitle":[{"text":"SMIConversationEntryMessageTypesStaticContent","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/staticcontent","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/staticContent","kind":"symbol","abstract":[{"type":"text","text":"A message containing static content."}],"type":"topic","role":"symbol","title":"staticContent","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"staticContent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"title":"ConversationEntryMessageTypes","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryMessageTypesStaticContent"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesStaticContent"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","text":"SMIConversationEntryMessageTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationEntryMessageTypesStaticContent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1staticContent\/title","op":"replace","value":"SMIConversationEntryMessageTypesStaticContent"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1staticContent\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesStaticContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title","op":"replace","value":"SMIConversationEntryMessageTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}