{"metadata":{"symbolKind":"property","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier"}],"roleHeading":"Type Property","externalID":"c:@SMIConversationEntryMessageTypesUnspecified","navigatorTitle":[{"text":"SMIConversationEntryMessageTypesUnspecified","kind":"identifier"}],"role":"symbol","title":"unspecified","modules":[{"name":"SMIClientCore"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Represents an unknown or unspecified message type.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/unspecified","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/unspecified"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes\/unspecified"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/unspecified":{"navigatorTitle":[{"text":"SMIConversationEntryMessageTypesUnspecified","kind":"identifier"}],"type":"topic","title":"unspecified","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/unspecified","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/unspecified","abstract":[{"text":"Represents an unknown or unspecified message type.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryMessageTypes"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEntryMessageTypes"}],"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","role":"symbol","title":"ConversationEntryMessageTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIConversationEntryMessageTypesUnspecified","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesUnspecified"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"SMIConversationEntryMessageTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationEntryMessageTypesUnspecified"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1unspecified\/title","value":"SMIConversationEntryMessageTypesUnspecified"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1unspecified\/fragments","value":[{"text":"SMIConversationEntryMessageTypesUnspecified","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title","value":"SMIConversationEntryMessageTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}]}]}]}