{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_SwiftNewtypeWrapper.hash(into:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/hash(into:)"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"title":"hash(into:)","roleHeading":"Instance Method","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}],"extendedModule":"Swift","symbolKind":"method","externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:SMIFormInputSectionType.h@T@SMIFormInputSectionType"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/_SwiftNewtypeWrapper-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputsectiontype\/hash(into:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","title":"FormInputSectionType","type":"topic","url":"\/documentation\/smiclientcore\/forminputsectiontype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputSectionType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputSectionType"}],"abstract":[{"text":"An enum that defines the types of form input sections available in the system.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType/_SwiftNewtypeWrapper-Implementations":{"url":"\/documentation\/smiclientcore\/forminputsectiontype\/_swiftnewtypewrapper-implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/_SwiftNewtypeWrapper-Implementations","title":"_SwiftNewtypeWrapper Implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType/hash(into:)":{"title":"hash(into:)","kind":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"url":"\/documentation\/smiclientcore\/forminputsectiontype\/hash(into:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/title","op":"replace","value":"SMIFormInputSectionType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputSectionType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormInputSectionType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}