{"sections":[],"metadata":{"symbolKind":"init","externalID":"s:So23SMIFormInputSectionTypea8rawValueABSS_tcfc","role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"init(rawValue:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/init(rawValue:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputsectiontype\/init(rawvalue:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/init(rawValue:)","url":"\/documentation\/smiclientcore\/forminputsectiontype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"init(rawValue:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType":{"abstract":[{"type":"text","text":"An enum that defines the types of form input sections available in the system."}],"title":"FormInputSectionType","navigatorTitle":[{"kind":"identifier","text":"FormInputSectionType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/forminputsectiontype","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputSectionType"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/title","value":"SMIFormInputSectionType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/fragments","value":[{"kind":"identifier","text":"SMIFormInputSectionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/navigatorTitle","value":[{"text":"SMIFormInputSectionType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}