{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType"]]},"metadata":{"roleHeading":"Type Property","externalID":"c:@SMIFormInputSectionTypeSingleInputSection","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleInputSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType","text":"FormInputSectionType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormInputSectionTypeSingleInputSection"}],"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","title":"singleInputSection","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleInputSection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputSectionType","preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/singleInputSection","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Represents a section that collects a single input value from the user."},{"type":"text","text":" "},{"type":"text","text":"This type is used when the section needs to collect one input value."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputsectiontype\/singleinputsection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputsectiontype\/singleinputsection"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","title":"FormInputSectionType","type":"topic","url":"\/documentation\/smiclientcore\/forminputsectiontype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputSectionType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputSectionType"}],"abstract":[{"text":"An enum that defines the types of form input sections available in the system.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType/singleInputSection":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType\/singleInputSection","url":"\/documentation\/smiclientcore\/forminputsectiontype\/singleinputsection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIFormInputSectionTypeSingleInputSection"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleInputSection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputSectionType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType"}],"abstract":[{"text":"Represents a section that collects a single input value from the user.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when the section needs to collect one input value.","type":"text"}],"title":"singleInputSection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormInputSectionTypeSingleInputSection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputSectionTypeSingleInputSection"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFormInputSectionTypeSingleInputSection","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/title","op":"replace","value":"SMIFormInputSectionType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputSectionType"}]},{"value":[{"kind":"identifier","text":"SMIFormInputSectionType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/navigatorTitle"},{"value":"SMIFormInputSectionTypeSingleInputSection","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType~1singleInputSection\/title"},{"value":[{"kind":"identifier","text":"SMIFormInputSectionTypeSingleInputSection"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType~1singleInputSection\/fragments"}]}]}