{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","extendedModule":"SMIClientCore","roleHeading":"Type Property","externalID":"c:@SMITypingIndicatorTypesStarted","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"SMITypingIndicatorTypesStarted"}],"title":"started","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","text":"TypingIndicatorTypes","kind":"typeIdentifier"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"started","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/typingindicatortypes\/started"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/typingindicatortypes\/started"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/started","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates the action of a participant started to type."}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","url":"\/documentation\/smiclientcore\/typingindicatortypes","type":"topic","role":"symbol","kind":"symbol","title":"TypingIndicatorTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"identifier"}],"navigatorTitle":[{"text":"TypingIndicatorTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of a typing indicator in a conversation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/started":{"type":"topic","abstract":[{"type":"text","text":"Indicates the action of a participant started to type."}],"title":"started","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/started","url":"\/documentation\/smiclientcore\/typingindicatortypes\/started","role":"symbol","navigatorTitle":[{"text":"SMITypingIndicatorTypesStarted","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"started","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMITypingIndicatorTypesStarted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMITypingIndicatorTypesStarted"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","text":"SMITypingIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMITypingIndicatorTypesStarted","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/title","value":"SMITypingIndicatorTypes","op":"replace"},{"value":[{"kind":"identifier","text":"SMITypingIndicatorTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/fragments","op":"replace"},{"value":[{"text":"SMITypingIndicatorTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/navigatorTitle","op":"replace"},{"value":"SMITypingIndicatorTypesStarted","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1started\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMITypingIndicatorTypesStarted"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1started\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}