{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","text":"TypingIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/stopped","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@SMITypingIndicatorTypesStopped","symbolKind":"property","title":"stopped","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMITypingIndicatorTypesStopped"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","text":"TypingIndicatorTypes"}]},"abstract":[{"type":"text","text":"Indicates the action of a participant stopped typing."}],"variants":[{"paths":["\/documentation\/smiclientcore\/typingindicatortypes\/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/typingindicatortypes\/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of a typing indicator in a conversation."}],"navigatorTitle":[{"text":"TypingIndicatorTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/typingindicatortypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","title":"TypingIndicatorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/stopped":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","text":"TypingIndicatorTypes"}],"abstract":[{"text":"Indicates the action of a participant stopped typing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMITypingIndicatorTypesStopped"}],"url":"\/documentation\/smiclientcore\/typingindicatortypes\/stopped","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/stopped","title":"stopped"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMITypingIndicatorTypesStopped"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMITypingIndicatorTypesStopped"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","text":"SMITypingIndicatorTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITypingIndicatorTypesStopped"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/title","value":"SMITypingIndicatorTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/fragments","value":[{"kind":"identifier","text":"SMITypingIndicatorTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/navigatorTitle","value":[{"text":"SMITypingIndicatorTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1stopped\/title","value":"SMITypingIndicatorTypesStopped"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1stopped\/fragments","value":[{"kind":"identifier","text":"SMITypingIndicatorTypesStopped"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}