{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/staticerrormessage\/errordetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/staticerrormessage\/errordetails"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage"]]},"sections":[],"abstract":[{"type":"text","text":"Specific details regarding the error which triggered this message."}],"metadata":{"symbolKind":"property","required":true,"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDetails","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIStaticErrorDetails","text":"StaticErrorDetails","kind":"typeIdentifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"errorDetails","kind":"identifier"}],"externalID":"c:objc(pl)SMIStaticErrorMessage(py)errorDetails","title":"errorDetails"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage\/errorDetails","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDetails","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"StaticErrorDetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIStaticErrorDetails"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorMessage":{"role":"symbol","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorMessage","kind":"identifier"}],"navigatorTitle":[{"text":"StaticErrorMessage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","type":"topic","title":"StaticErrorMessage","url":"\/documentation\/smiclientcore\/staticerrormessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorMessage/errorDetails":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDetails","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"StaticErrorDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIStaticErrorDetails"}],"title":"errorDetails","navigatorTitle":[{"text":"errorDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Specific details regarding the error which triggered this message."}],"url":"\/documentation\/smiclientcore\/staticerrormessage\/errordetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage\/errorDetails","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorDetails","kind":"identifier"}],"navigatorTitle":[{"text":"StaticErrorDetails","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/staticerrordetails","title":"StaticErrorDetails","abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"errorDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"errorDetails","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIStaticErrorDetails>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIStaticErrorDetails"},{"text":" ","kind":"text"},{"text":"errorDetails","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/title","value":"SMIStaticErrorMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/fragments","value":[{"text":"SMIStaticErrorMessage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStaticErrorMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage~1errorDetails\/title","value":"errorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage~1errorDetails\/fragments","value":[{"text":"errorDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/title","value":"SMIStaticErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/fragments","value":[{"kind":"identifier","text":"SMIStaticErrorDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/navigatorTitle","value":[{"text":"SMIStaticErrorDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}