{"metadata":{"title":"voiceProvider","modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voiceProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","text":"VoiceProvider","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"voiceProvider","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractVoiceConnection(py)voiceProvider","required":true,"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voiceProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","text":"VoiceProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/abstractvoiceconnection\/voiceprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/abstractvoiceconnection\/voiceprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection\/voiceProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"]]},"abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","isActive":true,"type":"reference"},{"text":" that services this voice connection.","type":"text"}],"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceProvider":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoiceProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"VoiceProvider","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"title":"VoiceProvider","url":"\/documentation\/smimultimediacommon\/voiceprovider"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection":{"navigatorTitle":[{"text":"AbstractVoiceConnection","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"identifier"}],"title":"AbstractVoiceConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an abstract voice connection and identifies the voice provider."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection/voiceProvider":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voiceProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","text":"VoiceProvider","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"voiceProvider","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection\/voiceProvider","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","isActive":true,"type":"reference"},{"text":" that services this voice connection.","type":"text"}],"title":"voiceProvider","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection\/voiceprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"voiceProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"voiceProvider"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","text":"SMIVoiceProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider"},{"text":" ","kind":"text"},{"text":"voiceProvider","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/title","value":"SMIVoiceProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/fragments","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/navigatorTitle","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/title","value":"SMIAbstractVoiceConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/fragments","value":[{"kind":"identifier","text":"SMIAbstractVoiceConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractVoiceConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection~1voiceProvider\/title","value":"voiceProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection~1voiceProvider\/fragments","value":[{"kind":"identifier","text":"voiceProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}