{"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"_SwiftNewtypeWrapper Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/hashValue"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/hash(into:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citeddetailstype\/_swiftnewtypewrapper-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/_SwiftNewtypeWrapper-Implementations"},"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType/hash(into:)":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hash(into:)","type":"topic","url":"\/documentation\/smiclientcore\/citeddetailstype\/hash(into:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/hash(into:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedDetailsType"}],"type":"topic","url":"\/documentation\/smiclientcore\/citeddetailstype","title":"CitedDetailsType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetailsType"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of citation details available in the system."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType/hashValue":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"title":"hashValue","url":"\/documentation\/smiclientcore\/citeddetailstype\/hashvalue","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/hashValue","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/title","op":"replace","value":"SMICitedDetailsType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICitedDetailsType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/navigatorTitle","op":"replace","value":[{"text":"SMICitedDetailsType","kind":"identifier"}]}]}]}