{"metadata":{"role":"collectionGroup","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection","title":"Equatable Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"]]},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/!=(_:_:)"],"anchor":"Operators"}],"variants":[{"paths":["\/documentation\/smiclientcore\/citeddetailstype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/Equatable-Implementations"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType/!=(_:_:)":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"!=(_:_:)","abstract":[],"url":"\/documentation\/smiclientcore\/citeddetailstype\/!=(_:_:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","title":"CitedDetailsType","abstract":[{"type":"text","text":"An enum that defines the types of citation details available in the system."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedDetailsType","kind":"identifier"}],"navigatorTitle":[{"text":"CitedDetailsType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citeddetailstype","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/title","value":"SMICitedDetailsType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/fragments","value":[{"text":"SMICitedDetailsType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/navigatorTitle","value":[{"text":"SMICitedDetailsType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}