{"kind":"symbol","sections":[],"abstract":[{"text":"Represents citation details that include inline metadata.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when the citation includes additional metadata about where it appears","type":"text"},{"text":" ","type":"text"},{"text":"in the text, such as location offsets and claim information.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedDetailsType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType"}],"extendedModule":"SMIClientCore","externalID":"c:@SMICitedDetailsTypeInlineMetadata","title":"inlineMetadata","navigatorTitle":[{"text":"SMICitedDetailsTypeInlineMetadata","kind":"identifier"}],"roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/smiclientcore\/citeddetailstype\/inlinemetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citeddetailstype\/inlinemetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/inlineMetadata"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","text":"CitedDetailsType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","role":"symbol","abstract":[{"text":"An enum that defines the types of citation details available in the system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedDetailsType"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetailsType"}],"title":"CitedDetailsType","url":"\/documentation\/smiclientcore\/citeddetailstype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType/inlineMetadata":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SMICitedDetailsTypeInlineMetadata","kind":"identifier"}],"title":"inlineMetadata","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedDetailsType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType"}],"url":"\/documentation\/smiclientcore\/citeddetailstype\/inlinemetadata","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType\/inlineMetadata","abstract":[{"text":"Represents citation details that include inline metadata.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when the citation includes additional metadata about where it appears","type":"text"},{"text":" ","type":"text"},{"text":"in the text, such as location offsets and claim information.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMICitedDetailsTypeInlineMetadata","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMICitedDetailsTypeInlineMetadata"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICitedDetailsType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICitedDetailsTypeInlineMetadata","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/title","value":"SMICitedDetailsType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/fragments","value":[{"text":"SMICitedDetailsType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitedDetailsType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType~1inlineMetadata\/title","value":"SMICitedDetailsTypeInlineMetadata","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType~1inlineMetadata\/fragments","value":[{"text":"SMICitedDetailsTypeInlineMetadata","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}