{"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/add(processReceiver:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"]]},"kind":"symbol","abstract":[{"type":"text","text":"Registers a process receiver to consume audio data from this track."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"processReceiver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","text":"AudioProcessReceiver"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"processReceiver","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","type":"reference","isActive":true},{"text":" to add.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/add(processreceiver:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/add(processreceiver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"addWithProcessReceiver:"}],"required":true,"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"processReceiver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AudioProcessReceiver","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver"},{"text":")","kind":"text"}],"title":"add(processReceiver:)","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioTrack(im)addWithProcessReceiver:"},"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol/add(processReceiver:)":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"processReceiver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver","text":"AudioProcessReceiver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addWithProcessReceiver:"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/add(processReceiver:)","abstract":[{"type":"text","text":"Registers a process receiver to consume audio data from this track."}],"title":"add(processReceiver:)","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol\/add(processreceiver:)"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","abstract":[{"type":"text","text":"A protocol for receiving processed audio data from an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"AudioProcessReceiver","kind":"symbol","navigatorTitle":[{"text":"AudioProcessReceiver","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addWithProcessReceiver:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addWithProcessReceiver:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addWithProcessReceiver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIAudioProcessReceiver>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver"},{"text":") ","kind":"text"},{"text":"processReceiver","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"processReceiver","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver"},{"type":"text","text":" to add."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"addWithProcessReceiver:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1add(processReceiver:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addWithProcessReceiver:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1add(processReceiver:)\/fragments","op":"replace"},{"value":"SMIAudioProcessReceiver","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title","value":"SMIAudioTrack","op":"replace"},{"value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}