{"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/remove(processReceiver:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/remove(processreceiver:)"]},{"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/remove(processreceiver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"]]},"metadata":{"modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"processReceiver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver","text":"AudioProcessReceiver"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"remove(processReceiver:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeWithProcessReceiver:"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioTrack(im)removeWithProcessReceiver:","required":true},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Removes a previously registered process receiver from this track."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"processReceiver"},{"text":": ","kind":"text"},{"text":"AudioProcessReceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"processReceiver","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","isActive":true},{"type":"text","text":" to remove."}],"type":"paragraph"}]}]}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","url":"\/documentation\/smimultimediacommon","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","title":"SMIMultimediaCommon","kind":"symbol","type":"topic","abstract":[{"text":"The common protocols and types that define the public API surface for multimedia capabilities.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol/remove(processReceiver:)":{"navigatorTitle":[{"text":"removeWithProcessReceiver:","kind":"identifier"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol\/remove(processreceiver:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/remove(processReceiver:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"processReceiver"},{"text":": ","kind":"text"},{"text":"AudioProcessReceiver","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"remove(processReceiver:)","kind":"symbol","type":"topic","abstract":[{"text":"Removes a previously registered process receiver from this track.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","abstract":[{"type":"text","text":"A protocol for receiving processed audio data from an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"AudioProcessReceiver","kind":"symbol","navigatorTitle":[{"text":"AudioProcessReceiver","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"removeWithProcessReceiver:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeWithProcessReceiver:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeWithProcessReceiver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMIAudioProcessReceiver>","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver"},{"kind":"text","text":") "},{"kind":"internalParam","text":"processReceiver"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"processReceiver","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","type":"reference"},{"text":" to remove.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"removeWithProcessReceiver:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1remove(processReceiver:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeWithProcessReceiver:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1remove(processReceiver:)\/fragments"},{"op":"replace","value":"SMIAudioTrack","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAudioTrack"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAudioTrack"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle"},{"op":"replace","value":"SMIAudioProcessReceiver","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAudioProcessReceiver"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}