{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/removeAll()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/removeall()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/removeall()"]}],"metadata":{"roleHeading":"Instance Method","required":true,"role":"symbol","title":"removeAll()","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"removeAll","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioTrack(im)removeAll"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Removes all registered process receivers from this track."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol/removeAll()":{"role":"symbol","required":true,"type":"topic","title":"removeAll()","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/removeAll()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"removeAll","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audiotrackprotocol\/removeall()","abstract":[{"type":"text","text":"Removes all registered process receivers from this track."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"removeAll","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAll","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAll"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"removeAll","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1removeAll()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAll","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1removeAll()\/fragments"},{"op":"replace","value":"SMIAudioTrack","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title"},{"op":"replace","value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle"}]}]}