{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/start(emitBuffer:normalizedChannelCount:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/start(emitbuffer:normalizedchannelcount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/audiotrackprotocol\/start(emitbuffer:normalizedchannelcount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioTrack(im)startWithEmitBuffer:normalizedChannelCount:","required":true,"title":"start(emitBuffer:normalizedChannelCount:)","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"emitBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"normalizedChannelCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"startWithEmitBuffer:normalizedChannelCount:"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"emitBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"normalizedChannelCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether to emit raw PCM buffers to registered receivers via ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)","type":"reference","isActive":true},{"text":".","type":"text"}]}],"name":"emitBuffer"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The number of normalized channels to emit to registered receivers via ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","type":"reference","isActive":true},{"text":".","type":"text"}]}],"name":"normalizedChannelCount"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Starts audio processing on this track."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol/start(emitBuffer:normalizedChannelCount:)":{"role":"symbol","required":true,"type":"topic","title":"start(emitBuffer:normalizedChannelCount:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol\/start(emitBuffer:normalizedChannelCount:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"emitBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"normalizedChannelCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"startWithEmitBuffer:normalizedChannelCount:","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audiotrackprotocol\/start(emitbuffer:normalizedchannelcount:)","abstract":[{"text":"Starts audio processing on this track.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver/receive(normalizedChannels:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedChannels","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"])","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver\/receive(normalizedchannels:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","abstract":[{"text":"Receives normalized audio channel levels for visualization.","type":"text"}],"type":"topic","title":"receive(normalizedChannels:)","kind":"symbol","navigatorTitle":[{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver/render(buffer:)":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"render","kind":"identifier"},{"text":"(","kind":"text"},{"text":"buffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","text":"AVAudioPCMBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"renderWithBuffer:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)","abstract":[{"type":"text","text":"Receives the raw audio PCM buffer for rendering or processing."}],"title":"render(buffer:)","url":"\/documentation\/smimultimediacommon\/audioprocessreceiver\/render(buffer:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startWithEmitBuffer:normalizedChannelCount:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"startWithEmitBuffer:normalizedChannelCount:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithEmitBuffer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"emitBuffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedChannelCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"normalizedChannelCount"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Whether to emit raw PCM buffers to registered receivers via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"emitBuffer"},{"content":[{"inlineContent":[{"text":"The number of normalized channels to emit to registered receivers via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"normalizedChannelCount"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"startWithEmitBuffer:normalizedChannelCount:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1start(emitBuffer:normalizedChannelCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startWithEmitBuffer:normalizedChannelCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol~1start(emitBuffer:normalizedChannelCount:)\/fragments"},{"value":"receiveWithNormalizedChannels:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/fragments"},{"value":"SMIAudioTrack","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title"},{"value":[{"text":"SMIAudioTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments"},{"value":[{"text":"SMIAudioTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle"},{"value":"renderWithBuffer:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1render(buffer:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"renderWithBuffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1render(buffer:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}