{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate","text":"MultimediaClientDelegate","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClientDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate","type":"reference","isActive":true},{"text":" to register.","type":"text"}]}],"name":"delegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The dispatch queue on which delegate callbacks are delivered. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to use the default queue.","type":"text"}]}],"name":"queue"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/add(delegate:queue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/add(delegate:queue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MultimediaClientDelegate","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClientDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient(im)addWithDelegate:queue:","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"method","title":"add(delegate:queue:)","navigatorTitle":[{"kind":"identifier","text":"addWithDelegate:queue:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/add(delegate:queue:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Registers a delegate to receive client events."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol/add(delegate:queue:)":{"role":"symbol","required":true,"type":"topic","title":"add(delegate:queue:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/add(delegate:queue:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClientDelegate"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"addWithDelegate:queue:","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol\/add(delegate:queue:)","abstract":[{"type":"text","text":"Registers a delegate to receive client events."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientDelegate":{"title":"MultimediaClientDelegate","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate","url":"\/documentation\/smimultimediacommon\/multimediaclientdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultimediaClientDelegate"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaClientDelegate"}],"abstract":[{"type":"text","text":"A delegate protocol for receiving events from a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"},{"type":"text","text":" instance."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addWithDelegate:queue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithDelegate:queue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addWithDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClientDelegate","text":"id<SMIMultimediaClientDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"queue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"queue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate"},{"type":"text","text":" to register."}]}]},{"name":"queue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The dispatch queue on which delegate callbacks are delivered. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to use the default queue."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1add(delegate:queue:)\/title","value":"addWithDelegate:queue:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1add(delegate:queue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWithDelegate:queue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title","value":"SMIMultimediaClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/title","value":"SMIMultimediaClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaClientDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}