{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration","text":"MultimediaConfiguration","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(cs)SMIMultimediaConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultimediaConfiguration","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(cs)SMIMultimediaConfiguration"}],"modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient(py)configuration","symbolKind":"property","title":"configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/configuration"},"abstract":[{"text":"The configuration used to customize multimedia client behavior.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfiguration"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfiguration"}],"title":"MultimediaConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol"},{"type":"text","text":" that stores configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfigurationProtocol":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"title":"MultimediaConfigurationProtocol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol/configuration":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultimediaConfiguration","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(cs)SMIMultimediaConfiguration"}],"url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol\/configuration","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/configuration","abstract":[{"type":"text","text":"The configuration used to customize multimedia client behavior."}],"type":"topic","title":"configuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"configuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"configuration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(cs)SMIMultimediaConfiguration","text":"SMIMultimediaConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/title","op":"replace","value":"SMIMultimediaConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/title","op":"replace","value":"SMIMultimediaConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1configuration\/title","op":"replace","value":"configuration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1configuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"configuration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title","op":"replace","value":"SMIMultimediaClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}