{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/currentSession"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/currentsession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaclientprotocol\/currentsession"]}],"metadata":{"roleHeading":"Instance Property","required":true,"role":"symbol","title":"currentSession","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentSession","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaSessionProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currentSession","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient(py)currentSession"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentSession","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The currently active multimedia session, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no session exists."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol/currentSession":{"role":"symbol","required":true,"type":"topic","title":"currentSession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol\/currentSession","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentSession","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currentSession","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol\/currentsession","abstract":[{"type":"text","text":"The currently active multimedia session, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no session exists."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"currentSession","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"currentSession","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"id<SMIMultimediaSession>"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentSession"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","value":"SMIMultimediaSession","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title","value":"SMIMultimediaClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1currentSession\/title","value":"currentSession","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol~1currentSession\/fragments","value":[{"text":"currentSession","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}