{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formRecordsResult"},"abstract":[{"type":"text","text":"Represents a successful submission and contains references to objects that have been updated or created as a result."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseresulttype\/formrecordsresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseresulttype\/formrecordsresult"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formRecordsResult","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","text":"FormResponseResultType","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"formRecordsResult","symbolKind":"property","externalID":"c:@SMIFormResultTypeFormRecordsResult","extendedModule":"SMIClientCore","navigatorTitle":[{"text":"SMIFormResultTypeFormRecordsResult","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"formRecordsResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/formRecordsResult":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMIFormResultTypeFormRecordsResult"}],"abstract":[{"text":"Represents a successful submission and contains references to objects that have been updated or created as a result.","type":"text"}],"url":"\/documentation\/smiclientcore\/formresponseresulttype\/formrecordsresult","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formRecordsResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","kind":"typeIdentifier","text":"FormResponseResultType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formRecordsResult","kind":"symbol","title":"formRecordsResult","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType":{"navigatorTitle":[{"text":"FormResponseResultType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseresulttype","abstract":[{"text":"An enum that defines the types of results that can be returned from a form submission.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","title":"FormResponseResultType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormResultTypeFormRecordsResult","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormResultTypeFormRecordsResult"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIFormResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResultTypeFormRecordsResult"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormResultTypeFormRecordsResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formRecordsResult\/title"},{"value":[{"text":"SMIFormResultTypeFormRecordsResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formRecordsResult\/fragments"},{"value":"SMIFormResultType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/title"},{"value":[{"text":"SMIFormResultType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResultType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}