{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseresulttype\/formerrorresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseresulttype\/formerrorresult"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formErrorResult","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@SMIFormResultTypeFormErrorResult","title":"formErrorResult","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","navigatorTitle":[{"text":"SMIFormResultTypeFormErrorResult","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formErrorResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","kind":"typeIdentifier"}],"extendedModule":"SMIClientCore","role":"symbol","roleHeading":"Type Property"},"abstract":[{"type":"text","text":"Represents a failed submission and contains an array of errors that prevent the form submission."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formErrorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","text":"FormResponseResultType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/formErrorResult":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formErrorResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","text":"FormResponseResultType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Represents a failed submission and contains an array of errors that prevent the form submission."}],"type":"topic","navigatorTitle":[{"text":"SMIFormResultTypeFormErrorResult","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formErrorResult","title":"formErrorResult","url":"\/documentation\/smiclientcore\/formresponseresulttype\/formerrorresult","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseResultType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseresulttype","title":"FormResponseResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","abstract":[{"text":"An enum that defines the types of results that can be returned from a form submission.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResultTypeFormErrorResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormResultTypeFormErrorResult"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","text":"SMIFormResultType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResultTypeFormErrorResult"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formErrorResult\/title","value":"SMIFormResultTypeFormErrorResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formErrorResult\/fragments","value":[{"text":"SMIFormResultTypeFormErrorResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/title","value":"SMIFormResultType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/fragments","value":[{"text":"SMIFormResultType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/navigatorTitle","value":[{"text":"SMIFormResultType","kind":"identifier"}]}]}]}