{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/init(rawValue:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseresulttype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","role":"symbol","externalID":"s:So17SMIFormResultTypea8rawValueABSS_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(rawValue:)","modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseResultType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseresulttype","title":"FormResponseResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","abstract":[{"text":"An enum that defines the types of results that can be returned from a form submission.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/init(rawValue:)":{"role":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/smiclientcore\/formresponseresulttype\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/init(rawValue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/title","value":"SMIFormResultType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/fragments","value":[{"text":"SMIFormResultType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/navigatorTitle","value":[{"text":"SMIFormResultType","kind":"identifier"}]}]}]}