{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/closed","interfaceLanguage":"swift"},"metadata":{"extendedModule":"SMIClientCore","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState"}],"navigatorTitle":[{"kind":"identifier","text":"SMIRealtimeConnectionStateClosed"}],"roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"title":"closed","externalID":"c:@SMIRealtimeConnectionStateClosed","symbolKind":"property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/closed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/closed"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The realtime event connection is closed and not receiving events."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the connection to the realtime event service"},{"type":"text","text":" "},{"type":"text","text":"is closed and no events will be received until a new connection is established."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible states of the realtime event connection.","type":"text"}],"type":"topic","title":"RealtimeConnectionState"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/closed":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/closed","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/closed","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState"}],"navigatorTitle":[{"kind":"identifier","text":"SMIRealtimeConnectionStateClosed"}],"kind":"symbol","title":"closed","abstract":[{"text":"The realtime event connection is closed and not receiving events.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the connection to the realtime event service","type":"text"},{"text":" ","type":"text"},{"text":"is closed and no events will be received until a new connection is established.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIRealtimeConnectionStateClosed","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionStateClosed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRealtimeConnectionState","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRealtimeConnectionStateClosed","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIRealtimeConnectionState","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle","op":"replace"},{"value":"SMIRealtimeConnectionStateClosed","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1closed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRealtimeConnectionStateClosed"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1closed\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}