{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/connecting"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/connecting"]}],"kind":"symbol","abstract":[{"text":"The realtime event connection is in the process of establishing.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the connection to the realtime event service is being established. Events will not be received until the connection transitions to the open state.","type":"text"}],"metadata":{"extendedModule":"SMIClientCore","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState","kind":"typeIdentifier"}],"title":"connecting","roleHeading":"Type Property","externalID":"c:@SMIRealtimeConnectionStateConnecting","navigatorTitle":[{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of the realtime event connection."}],"role":"symbol","title":"RealtimeConnectionState","kind":"symbol","navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/connecting":{"title":"connecting","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/connecting","kind":"symbol","navigatorTitle":[{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"}],"abstract":[{"text":"The realtime event connection is in the process of establishing.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the connection to the realtime event service is being established. Events will not be received until the connection transitions to the open state.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RealtimeConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/connecting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIRealtimeConnectionStateConnecting","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"SMIRealtimeConnectionState","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIRealtimeConnectionState","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title"},{"op":"replace","value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments"},{"op":"replace","value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle"},{"op":"replace","value":"SMIRealtimeConnectionStateConnecting","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1connecting\/title"},{"op":"replace","value":[{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1connecting\/fragments"}]}]}