{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/equatable-implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of the realtime event connection."}],"role":"symbol","title":"RealtimeConnectionState","kind":"symbol","navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/!=(_:_:)":{"title":"!=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/!=(_:_:)","kind":"symbol","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/!=(_:_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIRealtimeConnectionState","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title"},{"value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRealtimeConnectionState"}]}]}]}