{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","text":"RealtimeConnectionState"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIRealtimeConnectionStateOpen"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"}],"symbolKind":"property","role":"symbol","extendedModule":"SMIClientCore","externalID":"c:@SMIRealtimeConnectionStateOpen","title":"open"},"variants":[{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/open"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate\/open"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/open","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The realtime event connection is open and receiving events."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the connection to the realtime event service"},{"type":"text","text":" "},{"type":"text","text":"is fully established and events are being received."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/open":{"title":"open","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIRealtimeConnectionStateOpen","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/open","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/open","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The realtime event connection is open and receiving events."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the connection to the realtime event service"},{"type":"text","text":" "},{"type":"text","text":"is fully established and events are being received."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"role":"symbol","url":"\/documentation\/smiclientcore\/realtimeconnectionstate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","title":"RealtimeConnectionState","kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible states of the realtime event connection."}],"navigatorTitle":[{"kind":"identifier","text":"RealtimeConnectionState"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RealtimeConnectionState"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIRealtimeConnectionStateOpen","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionStateOpen","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","text":"SMIRealtimeConnectionState","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRealtimeConnectionStateOpen","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIRealtimeConnectionStateOpen","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1open\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRealtimeConnectionStateOpen"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1open\/fragments","op":"replace"},{"value":"SMIRealtimeConnectionState","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments","op":"replace"},{"value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}