{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationformattypes\/attachments"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationformattypes\/attachments"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"SMIConversationFormatTypesAttachments","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","externalID":"c:@SMIConversationFormatTypesAttachments","title":"attachments","extendedModule":"SMIClientCore","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachments","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/attachments","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A message containing file attachments."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/attachments":{"title":"attachments","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/attachments","navigatorTitle":[{"kind":"identifier","text":"SMIConversationFormatTypesAttachments"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/attachments","role":"symbol","abstract":[{"text":"A message containing file attachments.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier","text":"ConversationFormatTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationFormatTypes"}],"title":"ConversationFormatTypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationFormatTypes"}],"url":"\/documentation\/smiclientcore\/conversationformattypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible formats for messages and content in a conversation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationFormatTypesAttachments"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIConversationFormatTypesAttachments","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","kind":"typeIdentifier","text":"SMIConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationFormatTypesAttachments"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1attachments\/title","op":"replace","value":"SMIConversationFormatTypesAttachments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1attachments\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypesAttachments"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title","op":"replace","value":"SMIConversationFormatTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments","op":"replace","value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}]}]}]}