{"variants":[{"paths":["\/documentation\/smiclientcore\/conversationformattypes\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/hash(into:)"},"metadata":{"title":"hash(into:)","extendedModule":"Swift","roleHeading":"Instance Method","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}],"externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"},"abstract":[{"type":"text","text":"Hashes the essential components of this value by feeding them into the"},{"type":"text","text":" "},{"type":"text","text":"given hasher."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"hasher","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The hasher to use when combining the components"},{"type":"text","text":" "},{"type":"text","text":"of this instance."}]}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/hash(into:)","type":"topic","role":"symbol","kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"abstract":[{"text":"Hashes the essential components of this value by feeding them into the","type":"text"},{"text":" ","type":"text"},{"text":"given hasher.","type":"text"}],"title":"hash(into:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/hash(into:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"abstract":[{"text":"An enum that defines the possible formats for messages and content in a conversation.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"title":"ConversationFormatTypes","url":"\/documentation\/smiclientcore\/conversationformattypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationFormatTypes"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIConversationFormatTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title"},{"value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"op":"replace"}]}]}