{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"]]},"sections":[],"abstract":[{"text":"A message containing an image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationformattypes\/imagemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationformattypes\/imagemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/imageMessage","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","extendedModule":"SMIClientCore","navigatorTitle":[{"text":"SMIConversationFormatTypesImageMessage","kind":"identifier"}],"title":"imageMessage","externalID":"c:@SMIConversationFormatTypesImageMessage","symbolKind":"property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/imageMessage":{"title":"imageMessage","url":"\/documentation\/smiclientcore\/conversationformattypes\/imagemessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/imageMessage","kind":"symbol","abstract":[{"type":"text","text":"A message containing an image."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIConversationFormatTypesImageMessage","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible formats for messages and content in a conversation."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes","role":"symbol","navigatorTitle":[{"text":"ConversationFormatTypes","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","title":"ConversationFormatTypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIConversationFormatTypesImageMessage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIConversationFormatTypesImageMessage"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationFormatTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationFormatTypesImageMessage","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1imageMessage\/title","value":"SMIConversationFormatTypesImageMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1imageMessage\/fragments","value":[{"text":"SMIConversationFormatTypesImageMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title","value":"SMIConversationFormatTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}],"op":"replace"}]}]}