{"sections":[],"abstract":[{"type":"text","text":"Represents a message containing selection options."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/selections"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selections"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","kind":"typeIdentifier","text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationformattypes\/selections"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationformattypes\/selections"]}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMIConversationFormatTypesSelections","kind":"identifier"}],"externalID":"c:@SMIConversationFormatTypesSelections","symbolKind":"property","title":"selections","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selections","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","kind":"typeIdentifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"abstract":[{"text":"An enum that defines the possible formats for messages and content in a conversation.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"title":"ConversationFormatTypes","url":"\/documentation\/smiclientcore\/conversationformattypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationFormatTypes"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/selections":{"url":"\/documentation\/smiclientcore\/conversationformattypes\/selections","abstract":[{"type":"text","text":"Represents a message containing selection options."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/selections","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationFormatTypesSelections"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selections"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes"}],"type":"topic","title":"selections"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIConversationFormatTypesSelections","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIConversationFormatTypesSelections"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"SMIConversationFormatTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationFormatTypesSelections"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title","value":"SMIConversationFormatTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments","value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1selections\/title","value":"SMIConversationFormatTypesSelections","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1selections\/fragments","value":[{"kind":"identifier","text":"SMIConversationFormatTypesSelections"}],"op":"replace"}]}]}