{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/attachmentUploadResult"},"variants":[{"paths":["\/documentation\/smiclientcore\/fileasset\/attachmentuploadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/fileasset\/attachmentuploadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadResult","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AttachmentUploadResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]]},"abstract":[{"type":"text","text":"The result of the file asset’s upload operation."},{"type":"text","text":" "},{"type":"text","text":"This property provides information about the upload status and any associated metadata."},{"type":"text","text":" "},{"type":"text","text":"The value is nil if the file hasn’t been uploaded or if the upload hasn’t completed."}],"kind":"symbol","metadata":{"role":"symbol","title":"attachmentUploadResult","roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFileAsset(py)attachmentUploadResult","modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadResult","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AttachmentUploadResult","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"attachmentUploadResult","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"url":"\/documentation\/smiclientcore\/attachmentuploadresult","abstract":[{"type":"text","text":"Result of an attachment upload operation."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AttachmentUploadResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","title":"AttachmentUploadResult","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResult","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/fileasset","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"title":"FileAsset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/attachmentUploadResult":{"title":"attachmentUploadResult","role":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/attachmentuploadresult","abstract":[{"text":"The result of the file asset’s upload operation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides information about the upload status and any associated metadata.","type":"text"},{"text":" ","type":"text"},{"text":"The value is nil if the file hasn’t been uploaded or if the upload hasn’t completed.","type":"text"}],"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadResult","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AttachmentUploadResult","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/attachmentUploadResult","navigatorTitle":[{"text":"attachmentUploadResult","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"attachmentUploadResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"attachmentUploadResult","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIAttachmentUploadResult","text":"id<SMIAttachmentUploadResult>"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentUploadResult"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle"},{"value":"SMIFileAsset","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title"},{"value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments"},{"value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle"},{"value":"attachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1attachmentUploadResult\/title"},{"value":[{"text":"attachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1attachmentUploadResult\/fragments"}]}]}