{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchContent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchContentWithCompletion:"}],"title":"fetchContent(completion:)","externalID":"c:objc(pl)SMIFileAsset(im)fetchContentWithCompletion:","modules":[{"name":"SMIClientCore"}],"role":"symbol","required":true,"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]},{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchContent"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameters","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"completion: A block that is called when the fetch operation completes. The block receives any error that occurred during the fetch operation."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"}]}],"abstract":[{"type":"text","text":"Fetches the content of this file asset asynchronously."},{"type":"text","text":" "},{"type":"text","text":"This method downloads the file content if it’s not already cached."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fileasset","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"title":"FileAsset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"title":"fetchContent(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)","role":"symbol","type":"topic","abstract":[{"text":"Fetches the content of this file asset asynchronously.","type":"text"},{"text":" ","type":"text"},{"text":"This method downloads the file content if it’s not already cached.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","navigatorTitle":[{"text":"fetchContentWithCompletion:","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileFetchCompletion":{"title":"FileFetchCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileFetchCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/filefetchcompletion","role":"symbol","type":"topic","abstract":[{"text":"A completion handler for file fetch operations.","type":"text"},{"text":" ","type":"text"},{"text":"This block is called when a file fetch operation completes, providing any error that occurred.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileFetchCompletion","navigatorTitle":[{"text":"FileFetchCompletion","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fetchContentWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchContentWithCompletion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fetchContentWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SMIFileFetchCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIFileAsset.h@T@SMIFileFetchCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileFetchCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"text":"SMIFileAsset","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","value":"fetchContentWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchContentWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/title","value":"SMIFileFetchCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/fragments","value":[{"text":"SMIFileFetchCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/navigatorTitle","value":[{"text":"SMIFileFetchCompletion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}