{"variants":[{"paths":["\/documentation\/smiclientcore\/fileasset\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/fileasset\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(pl)SMIFileAsset(py)identifier","role":"symbol","required":true,"title":"identifier","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/identifier","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The unique identifier for this file asset.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property provides a stable way to identify and reference the file."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/identifier":{"type":"topic","url":"\/documentation\/smiclientcore\/fileasset\/identifier","title":"identifier","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier for this file asset."},{"type":"text","text":" "},{"type":"text","text":"This property provides a stable way to identify and reference the file."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/fileasset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","role":"symbol","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"title":"FileAsset","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileAsset","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"identifier","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}],"op":"replace"}]}]}