{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mimeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The MIME type of this file asset.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]]},"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIFileAsset(py)mimeType","role":"symbol","roleHeading":"Instance Property","title":"mimeType","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mimeType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"navigatorTitle":[{"text":"mimeType","kind":"identifier"}],"symbolKind":"property","required":true},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/mimeType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/fileasset\/mimetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/fileasset\/mimetype"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkMimeTypes","kind":"identifier"}],"kind":"symbol","title":"NetworkMimeTypes","navigatorTitle":[{"text":"NetworkMimeTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/mimeType":{"abstract":[{"type":"text","text":"The MIME type of this file asset."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mimeType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier","text":"NetworkMimeTypes"}],"kind":"symbol","role":"symbol","title":"mimeType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/mimeType","required":true,"navigatorTitle":[{"kind":"identifier","text":"mimeType"}],"url":"\/documentation\/smiclientcore\/fileasset\/mimetype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fileasset","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"title":"FileAsset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"mimeType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"mimeType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"],"anchor":"Related-Documentation","title":"Related Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","text":"SMINetworkMimeTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"mimeType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title","op":"replace","value":"SMINetworkMimeTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments","op":"replace","value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1mimeType\/title","op":"replace","value":"mimeType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1mimeType\/fragments","op":"replace","value":[{"text":"mimeType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","op":"replace","value":"SMIFileAsset"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","op":"replace","value":[{"text":"SMIFileAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFileAsset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}