{"abstract":[{"type":"text","text":"The URL where this file asset can be accessed."},{"type":"text","text":" "},{"type":"text","text":"This property provides a location to download or access the file content."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/url","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/fileasset\/url"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/fileasset\/url"]}],"metadata":{"required":true,"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"url"}],"title":"url","externalID":"c:objc(pl)SMIFileAsset(py)url"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"url":"\/documentation\/smiclientcore\/fileasset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","title":"FileAsset","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/url":{"type":"topic","title":"url","kind":"symbol","navigatorTitle":[{"text":"url","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/url","url":"\/documentation\/smiclientcore\/fileasset\/url","abstract":[{"type":"text","text":"The URL where this file asset can be accessed."},{"type":"text","text":" "},{"type":"text","text":"This property provides a location to download or access the file content."}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"url","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"url","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFileAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title"},{"op":"replace","value":[{"text":"SMIFileAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFileAsset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1url\/title"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1url\/fragments"}]}]}