{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/itemType"},"abstract":[{"type":"text","text":"The type of interaction item this object represents."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of interactive element and its behavior."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem\/itemtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem\/itemtype"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormTitleInteractionItemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","text":"FormTitleInteractionItemType"}],"roleHeading":"Instance Property","role":"symbol","title":"itemType","navigatorTitle":[{"kind":"identifier","text":"itemType"}],"required":true,"externalID":"c:objc(pl)SMIFormTitleInteractionItem(py)itemType","symbolKind":"property","modules":[{"name":"SMIClientCore"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem/itemType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/itemType","role":"symbol","type":"topic","required":true,"title":"itemType","url":"\/documentation\/smiclientcore\/formtitleinteractionitem\/itemtype","abstract":[{"text":"The type of interaction item this object represents.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the specific type of interactive element and its behavior.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"itemType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormTitleInteractionItemType","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem":{"title":"FormTitleInteractionItem","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","abstract":[{"type":"text","text":"A protocol that defines an interactive element on a form that contains a title item."}],"type":"topic","url":"\/documentation\/smiclientcore\/formtitleinteractionitem","role":"symbol","navigatorTitle":[{"text":"FormTitleInteractionItem","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the types of interactive elements that can be used in form titles."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItemType"}],"role":"symbol","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype","navigatorTitle":[{"kind":"identifier","text":"FormTitleInteractionItemType"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","title":"FormTitleInteractionItemType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"itemType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"itemType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"],"title":"Related Documentation"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","text":"SMIFormTitleInteractionItemType","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1itemType\/title","value":"itemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1itemType\/fragments","value":[{"kind":"identifier","text":"itemType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/title","value":"SMIFormTitleInteractionItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/navigatorTitle","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/title","value":"SMIFormTitleInteractionItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}