{"metadata":{"role":"symbol","title":"titleItem","modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"titleItem","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormTitleInteractionItem(py)titleItem"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"title":"Related Documentation","anchor":"Related-Documentation"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem\/titleitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem\/titleitem"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleItem"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/titleItem"},"abstract":[{"type":"text","text":"The title item associated with this interaction item."},{"type":"text","text":" "},{"type":"text","text":"This provides the visual representation and text content for the interactive element."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem/titleItem":{"url":"\/documentation\/smiclientcore\/formtitleinteractionitem\/titleitem","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"titleItem","kind":"identifier"}],"title":"titleItem","abstract":[{"type":"text","text":"The title item associated with this interaction item."},{"type":"text","text":" "},{"type":"text","text":"This provides the visual representation and text content for the interactive element."}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/titleItem","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","role":"symbol","abstract":[{"text":"A protocol that defines the structure for title components used in forms.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","title":"FormTitleInteractionItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines an interactive element on a form that contains a title item."}],"url":"\/documentation\/smiclientcore\/formtitleinteractionitem","navigatorTitle":[{"text":"FormTitleInteractionItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"titleItem","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"titleItem","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"],"anchor":"Related-Documentation","title":"Related Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIFormTitleItem","text":"id<SMIFormTitleItem>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1titleItem\/title","op":"replace","value":"titleItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1titleItem\/fragments","op":"replace","value":[{"text":"titleItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","op":"replace","value":"SMIFormTitleItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/title","op":"replace","value":"SMIFormTitleInteractionItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}]}]}]}