{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"emailFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeEmailFormat"}],"role":"symbol","externalID":"c:@E@SMIFormErrorType@SMIFormErrorTypeEmailFormat","modules":[{"name":"SMIClientCore"}],"title":"FormErrorType.emailFormat","roleHeading":"Case","symbolKind":"case"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/formerrortype\/emailformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formerrortype\/emailformat"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Email field doesn’t have a valid email address."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when an email input field contains text that doesn’t match the standard"},{"type":"text","text":" "},{"type":"text","text":"email format (e.g., missing @ symbol or invalid domain)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailFormat"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/emailFormat","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/emailFormat":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emailFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Email field doesn’t have a valid email address."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when an email input field contains text that doesn’t match the standard"},{"type":"text","text":" "},{"type":"text","text":"email format (e.g., missing @ symbol or invalid domain)."}],"navigatorTitle":[{"text":"SMIFormErrorTypeEmailFormat","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrortype\/emailformat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/emailFormat","title":"FormErrorType.emailFormat"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"role":"symbol","navigatorTitle":[{"text":"FormErrorType","kind":"identifier"}],"title":"FormErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formerrortype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormErrorTypeEmailFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIFormErrorTypeEmailFormat","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIFormErrorTypeEmailFormat"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1emailFormat\/title","value":"SMIFormErrorTypeEmailFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1emailFormat\/fragments","value":[{"text":"SMIFormErrorTypeEmailFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","value":"SMIFormErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","value":[{"text":"SMIFormErrorType","kind":"identifier"}]}]}]}