{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"]]},"kind":"article","topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/!=(_:_:)"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/Equatable-Implementations"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formerrortype\/equatable-implementations"]}],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formerrortype\/!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrortype","title":"FormErrorType","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","role":"symbol","navigatorTitle":[{"text":"FormErrorType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","op":"replace","value":"SMIFormErrorType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","value":[{"text":"SMIFormErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}