{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/maxLength","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/formerrortype\/maxlength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formerrortype\/maxlength"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Field value exceeds the maximum length."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input text is longer than the maximum allowed length specified"},{"type":"text","text":" "},{"type":"text","text":"by the form configuration."}],"metadata":{"externalID":"c:@E@SMIFormErrorType@SMIFormErrorTypeMaxLength","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeMaxLength"}],"role":"symbol","title":"FormErrorType.maxLength"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/maxLength":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/maxLength","role":"symbol","navigatorTitle":[{"text":"SMIFormErrorTypeMaxLength","kind":"identifier"}],"type":"topic","title":"FormErrorType.maxLength","url":"\/documentation\/smiclientcore\/formerrortype\/maxlength","abstract":[{"type":"text","text":"Field value exceeds the maximum length."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input text is longer than the maximum allowed length specified"},{"type":"text","text":" "},{"type":"text","text":"by the form configuration."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"navigatorTitle":[{"kind":"identifier","text":"FormErrorType"}],"title":"FormErrorType","abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormErrorType"}],"url":"\/documentation\/smiclientcore\/formerrortype"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormErrorTypeMaxLength","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIFormErrorTypeMaxLength","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SMIFormErrorTypeMaxLength"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormErrorTypeMaxLength","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1maxLength\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorTypeMaxLength"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1maxLength\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","value":"SMIFormErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments","value":[{"text":"SMIFormErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","value":[{"text":"SMIFormErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}