{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/requiredField"},"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:@E@SMIFormErrorType@SMIFormErrorTypeRequiredField","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"title":"FormErrorType.requiredField","navigatorTitle":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"text":"Required field not completed.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a field marked as required is left empty.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formerrortype\/requiredfield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formerrortype\/requiredfield"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/requiredField":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrortype\/requiredfield","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/requiredField","abstract":[{"type":"text","text":"Required field not completed."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when a field marked as required is left empty."}],"role":"symbol","navigatorTitle":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}],"kind":"symbol","title":"FormErrorType.requiredField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"navigatorTitle":[{"kind":"identifier","text":"FormErrorType"}],"title":"FormErrorType","abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormErrorType"}],"url":"\/documentation\/smiclientcore\/formerrortype"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormErrorTypeRequiredField"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1requiredField\/title","op":"replace","value":"SMIFormErrorTypeRequiredField"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1requiredField\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorTypeRequiredField"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","op":"replace","value":"SMIFormErrorType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}