{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"URL field doesn’t have a valid URL format.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a URL input field contains text that doesn’t match the standard","type":"text"},{"text":" ","type":"text"},{"text":"URL format (e.g., missing protocol or invalid characters).","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formerrortype\/urlformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formerrortype\/urlformat"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/urlFormat"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlFormat"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"]]},"metadata":{"title":"FormErrorType.urlFormat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlFormat","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeUrlFormat"}],"roleHeading":"Case","externalID":"c:@E@SMIFormErrorType@SMIFormErrorTypeUrlFormat","modules":[{"name":"SMIClientCore"}],"symbolKind":"case"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"role":"symbol","abstract":[{"text":"An enum that defines validation error types for form inputs.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","navigatorTitle":[{"kind":"identifier","text":"FormErrorType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formerrortype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormErrorType"}],"title":"FormErrorType","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/urlFormat":{"title":"FormErrorType.urlFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/urlFormat","url":"\/documentation\/smiclientcore\/formerrortype\/urlformat","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlFormat","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SMIFormErrorTypeUrlFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"URL field doesn’t have a valid URL format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when a URL input field contains text that doesn’t match the standard"},{"type":"text","text":" "},{"type":"text","text":"URL format (e.g., missing protocol or invalid characters)."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormErrorTypeUrlFormat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorTypeUrlFormat"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMIFormErrorTypeUrlFormat","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","value":"SMIFormErrorType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle"},{"op":"replace","value":"SMIFormErrorTypeUrlFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1urlFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorTypeUrlFormat"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1urlFormat\/fragments"}]}]}