{"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileAgentforceSDK","interfaceLanguage":"swift"},"abstract":[{"text":"Mobile client for Agentforce SDK integrations.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName"]]},"sections":[],"metadata":{"externalID":"c:@SMIClientNameMobileAgentforceSDK","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mobileAgentforceSDK","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","kind":"typeIdentifier","text":"ClientName"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"SMIClientNameMobileAgentforceSDK","kind":"identifier"}],"extendedModule":"SMIClientCore","title":"mobileAgentforceSDK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mobileAgentforceSDK","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ClientName","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/clientname\/mobileagentforcesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/clientname\/mobileagentforcesdk"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/mobileAgentforceSDK":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileAgentforceSDK","title":"mobileAgentforceSDK","navigatorTitle":[{"kind":"identifier","text":"SMIClientNameMobileAgentforceSDK"}],"abstract":[{"type":"text","text":"Mobile client for Agentforce SDK integrations."}],"type":"topic","url":"\/documentation\/smiclientcore\/clientname\/mobileagentforcesdk","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mobileAgentforceSDK","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","text":"ClientName"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","title":"ClientName","navigatorTitle":[{"text":"ClientName","kind":"identifier"}],"abstract":[{"text":"A type that defines the client name sent during authentication to identify the SDK integration type.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/clientname","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientName","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","value":"SMIClientNameMobileAgentforceSDK","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIClientNameMobileAgentforceSDK"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","text":"SMIClientName"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIClientNameMobileAgentforceSDK"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileAgentforceSDK\/title","value":"SMIClientNameMobileAgentforceSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileAgentforceSDK\/fragments","value":[{"kind":"identifier","text":"SMIClientNameMobileAgentforceSDK"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/title","op":"replace","value":"SMIClientName"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIClientName"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/navigatorTitle","op":"replace","value":[{"text":"SMIClientName","kind":"identifier"}]}]}]}