{"sections":[],"abstract":[{"type":"text","text":"A display label for the citation."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides a user-friendly label that can be used in place of"},{"type":"text","text":" "},{"type":"text","text":"the URL’s domain name, particularly useful when the domain is excessively long or"},{"type":"text","text":" "},{"type":"text","text":"not user-friendly."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/label","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference\/label"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference\/label"]}],"metadata":{"title":"label","roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"label","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMILinkCitedReference(py)label"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/label":{"url":"\/documentation\/smiclientcore\/linkcitedreference\/label","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/label","abstract":[{"text":"A display label for the citation.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a user-friendly label that can be used in place of","type":"text"},{"text":" ","type":"text"},{"text":"the URL’s domain name, particularly useful when the domain is excessively long or","type":"text"},{"text":" ","type":"text"},{"text":"not user-friendly.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"type":"topic","title":"label"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference","role":"symbol","url":"\/documentation\/smiclientcore\/linkcitedreference","abstract":[{"text":"A protocol that represents a citation reference that links to an external URL.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"title":"LinkCitedReference"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"label","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"label"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"label","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"label","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1label\/title","op":"replace"},{"value":[{"text":"label","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1label\/fragments","op":"replace"},{"value":"SMILinkCitedReference","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMILinkCitedReference"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/fragments","op":"replace"},{"value":[{"text":"SMILinkCitedReference","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/navigatorTitle","op":"replace"}]}]}