{"abstract":[{"text":"The unique identifier for the referenced record.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a record identifier that can be used to associate","type":"text"},{"text":" ","type":"text"},{"text":"the citation with a specific record in the system.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"recordId","modules":[{"name":"SMIClientCore"}],"required":true,"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"recordId"}],"externalID":"c:objc(pl)SMILinkCitedReference(py)recordId","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/recordId"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/linkcitedreference\/recordid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/linkcitedreference\/recordid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/recordId":{"type":"topic","required":true,"navigatorTitle":[{"text":"recordId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/smiclientcore\/linkcitedreference\/recordid","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/recordId","abstract":[{"text":"The unique identifier for the referenced record.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a record identifier that can be used to associate","type":"text"},{"text":" ","type":"text"},{"text":"the citation with a specific record in the system.","type":"text"}],"role":"symbol","title":"recordId","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference":{"role":"symbol","title":"LinkCitedReference","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a citation reference that links to an external URL."}],"navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/linkcitedreference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"recordId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"recordId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"recordId","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"recordId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1recordId\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1recordId\/fragments","op":"replace","value":[{"kind":"identifier","text":"recordId"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/title","op":"replace","value":"SMILinkCitedReference"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILinkCitedReference"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMILinkCitedReference"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}