{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/url","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The URL that this citation references."},{"type":"text","text":" "},{"type":"text","text":"This property provides the target URL that the citation links to. The URL can be used"},{"type":"text","text":" "},{"type":"text","text":"to navigate to the referenced content when the citation is selected."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference\/url"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference\/url"]}],"metadata":{"roleHeading":"Instance Property","title":"url","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0"}],"required":true,"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMILinkCitedReference(py)url","navigatorTitle":[{"kind":"identifier","text":"url"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference":{"abstract":[{"text":"A protocol that represents a citation reference that links to an external URL.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/linkcitedreference","title":"LinkCitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference","type":"topic","navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/url":{"title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/url","kind":"symbol","url":"\/documentation\/smiclientcore\/linkcitedreference\/url","abstract":[{"type":"text","text":"The URL that this citation references."},{"type":"text","text":" "},{"type":"text","text":"This property provides the target URL that the citation links to. The URL can be used"},{"type":"text","text":" "},{"type":"text","text":"to navigate to the referenced content when the citation is selected."}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"url"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"url","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"url"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"url"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/title","value":"SMILinkCitedReference","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/fragments","value":[{"kind":"identifier","text":"SMILinkCitedReference"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/navigatorTitle","value":[{"kind":"identifier","text":"SMILinkCitedReference"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1url\/fragments","value":[{"text":"url","kind":"identifier"}],"op":"replace"}]}]}