{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/expired","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The passed in token has expired."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expired","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason"]]},"metadata":{"externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonExpired","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonExpired"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expired"}],"roleHeading":"Case","title":"ChallengeReason.expired","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/challengereason\/expired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/challengereason\/expired"]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason/expired":{"title":"ChallengeReason.expired","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonExpired"}],"type":"topic","abstract":[{"type":"text","text":"The passed in token has expired."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/expired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expired"}],"url":"\/documentation\/smiclientcore\/challengereason\/expired"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason":{"title":"ChallengeReason","navigatorTitle":[{"kind":"identifier","text":"ChallengeReason"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeReason"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","kind":"symbol","abstract":[{"text":"An enum that defines the possible reasons for a user verification challenge.","type":"text"}],"url":"\/documentation\/smiclientcore\/challengereason","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIChallengeReasonExpired","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChallengeReasonExpired"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SMIChallengeReasonExpired"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIChallengeReasonExpired","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1expired\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1expired\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIChallengeReasonExpired"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/title","op":"replace","value":"SMIChallengeReason"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/fragments","op":"replace","value":[{"text":"SMIChallengeReason","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChallengeReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}