{"sections":[],"abstract":[{"text":"The passed in token was malformed.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/malformed","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"malformed","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/challengereason\/malformed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/challengereason\/malformed"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonMalformed","symbolKind":"case","title":"ChallengeReason.malformed","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"malformed"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason":{"abstract":[{"type":"text","text":"An enum that defines the possible reasons for a user verification challenge."}],"navigatorTitle":[{"kind":"identifier","text":"ChallengeReason"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","title":"ChallengeReason","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeReason"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/challengereason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason/malformed":{"type":"topic","url":"\/documentation\/smiclientcore\/challengereason\/malformed","title":"ChallengeReason.malformed","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/malformed","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"abstract":[{"text":"The passed in token was malformed.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"malformed"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIChallengeReasonMalformed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/title","value":"SMIChallengeReason","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/fragments","op":"replace","value":[{"text":"SMIChallengeReason","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChallengeReason"}]},{"op":"replace","value":"SMIChallengeReasonMalformed","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1malformed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1malformed\/fragments"}]}]}