{"abstract":[{"text":"The verification token is valid. This is a terminating state for determining user identity.","type":"text"}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SMIChallengeReasonNone","kind":"identifier"}],"externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonNone","title":"ChallengeReason.none","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/none","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/challengereason\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/challengereason\/none"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason/none":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/none","url":"\/documentation\/smiclientcore\/challengereason\/none","title":"ChallengeReason.none","type":"topic","abstract":[{"text":"The verification token is valid. This is a terminating state for determining user identity.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonNone"}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason":{"title":"ChallengeReason","navigatorTitle":[{"kind":"identifier","text":"ChallengeReason"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeReason"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","kind":"symbol","abstract":[{"text":"An enum that defines the possible reasons for a user verification challenge.","type":"text"}],"url":"\/documentation\/smiclientcore\/challengereason","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIChallengeReasonNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIChallengeReasonNone","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SMIChallengeReasonNone"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1none\/title","value":"SMIChallengeReasonNone"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1none\/fragments","value":[{"text":"SMIChallengeReasonNone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/title","value":"SMIChallengeReason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/fragments","value":[{"kind":"identifier","text":"SMIChallengeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/navigatorTitle","value":[{"text":"SMIChallengeReason","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}