{"abstract":[{"type":"text","text":"The verification token from the server has expired and user verification is required again."}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonRefresh"}],"title":"ChallengeReason.refresh","modules":[{"name":"SMIClientCore"}],"externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonRefresh","roleHeading":"Case"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/refresh"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/challengereason\/refresh"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/challengereason\/refresh"]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason/refresh":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/challengereason\/refresh","role":"symbol","navigatorTitle":[{"text":"SMIChallengeReasonRefresh","kind":"identifier"}],"abstract":[{"text":"The verification token from the server has expired and user verification is required again.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason\/refresh","title":"ChallengeReason.refresh"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/challengereason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeReason","kind":"identifier"}],"navigatorTitle":[{"text":"ChallengeReason","kind":"identifier"}],"title":"ChallengeReason","abstract":[{"text":"An enum that defines the possible reasons for a user verification challenge.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIChallengeReasonRefresh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIChallengeReasonRefresh"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIChallengeReasonRefresh","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1refresh\/title","value":"SMIChallengeReasonRefresh"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason~1refresh\/fragments","value":[{"text":"SMIChallengeReasonRefresh","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/title","value":"SMIChallengeReason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/fragments","value":[{"text":"SMIChallengeReason","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChallengeReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}