{"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/hashValue"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/hash(into:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"metadata":{"role":"collectionGroup","modules":[{"name":"SMIClientCore"}],"title":"_SwiftNewtypeWrapper Implementations","roleHeading":"API Collection"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/_SwiftNewtypeWrapper-Implementations"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/_swiftnewtypewrapper-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/hash(into:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hash(into:)","abstract":[],"url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/hash(into:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/hash(into:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"title":"SMIPreChatConfigurationFormTypes","type":"topic","abstract":[{"text":"A type that defines the available form types for pre-chat configurations.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/hashValue":{"abstract":[],"kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/hashvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/hashValue","type":"topic","title":"hashValue"}},"variantOverrides":[{"patch":[{"value":"SMIPreChatConfigurationFormTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title","op":"replace"},{"value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}