{"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/!=(_:_:)"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"]]},"kind":"article","sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/!=(_:_:)":{"abstract":[],"role":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"title":"SMIPreChatConfigurationFormTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"abstract":[{"text":"A type that defines the available form types for pre-chat configurations.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SMIPreChatConfigurationFormTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments"},{"op":"replace","value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle"}]}]}