{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:So32SMIPreChatConfigurationFormTypesa8rawValueABSS_tcfc","role":"symbol","symbolKind":"init","modules":[{"name":"SMIClientCore"}],"roleHeading":"Initializer","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/init(rawValue:)","type":"topic","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/init(rawvalue:)","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"title":"SMIPreChatConfigurationFormTypes","type":"topic","abstract":[{"text":"A type that defines the available form types for pre-chat configurations.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title","value":"SMIPreChatConfigurationFormTypes"},{"value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle"}]}]}