{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SMIPreChatConfigurationFormTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/prechat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/prechat"]}],"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preChat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypesPreChat","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","title":"preChat","role":"symbol","externalID":"c:@SMIPreChatConfigurationFormTypesPreChat","roleHeading":"Type Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/preChat"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The standard pre-chat form type."},{"type":"text","text":" "},{"type":"text","text":"This form type is used for collecting user information before starting a chat session."},{"type":"text","text":" "},{"type":"text","text":"The form includes visible fields that users can fill out and hidden fields that can"},{"type":"text","text":" "},{"type":"text","text":"be set programmatically."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"title":"SMIPreChatConfigurationFormTypes","type":"topic","abstract":[{"text":"A type that defines the available form types for pre-chat configurations.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/preChat":{"title":"preChat","abstract":[{"text":"The standard pre-chat form type.","type":"text"},{"text":" ","type":"text"},{"text":"This form type is used for collecting user information before starting a chat session.","type":"text"},{"text":" ","type":"text"},{"text":"The form includes visible fields that users can fill out and hidden fields that can","type":"text"},{"text":" ","type":"text"},{"text":"be set programmatically.","type":"text"}],"url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/prechat","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/preChat","kind":"symbol","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypesPreChat","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preChat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIPreChatConfigurationFormTypesPreChat","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypesPreChat"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypesPreChat","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIPreChatConfigurationFormTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title"},{"value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle"},{"value":"SMIPreChatConfigurationFormTypesPreChat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes~1preChat\/title"},{"value":[{"text":"SMIPreChatConfigurationFormTypesPreChat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes~1preChat\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}