{"abstract":[{"text":"The unique identifier for this selectable option.","type":"text"},{"text":" ","type":"text"},{"text":"This identifier is used to track the selection state of the option and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"associate the option with other form components or data.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"optionIdentifier","navigatorTitle":[{"kind":"identifier","text":"optionIdentifier"}],"symbolKind":"property","externalID":"c:objc(pl)SMIFormTitleOptionItem(py)optionIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","required":true,"roleHeading":"Instance Property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputoptionitem\/optionidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputoptionitem\/optionidentifier"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem\/optionIdentifier"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem/optionIdentifier":{"abstract":[{"type":"text","text":"The unique identifier for this selectable option."},{"type":"text","text":" "},{"type":"text","text":"This identifier is used to track the selection state of the option and can be used to"},{"type":"text","text":" "},{"type":"text","text":"associate the option with other form components or data."}],"title":"optionIdentifier","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"optionIdentifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/forminputoptionitem\/optionidentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem\/optionIdentifier","kind":"symbol","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"title":"FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"optionIdentifier","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"optionIdentifier","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"optionIdentifier","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem~1optionIdentifier\/title","value":"optionIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem~1optionIdentifier\/fragments","value":[{"text":"optionIdentifier","kind":"identifier"}],"op":"replace"},{"value":"SMIFormTitleOptionItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","op":"replace"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","op":"replace"}]}]}