{"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/isdateandtime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/isdateandtime"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)SMIFormDatePickerInput(py)isDateAndTime","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"isDateAndTime","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDateAndTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isDateAndTime","kind":"identifier"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/isDateAndTime","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDateAndTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A flag that indicates whether the date picker includes time selection."},{"type":"text","text":" "},{"type":"text","text":"This property is automatically determined based on the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","type":"reference","isActive":true},{"type":"text","text":"."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol","title":"FormDatePickerInput","abstract":[{"type":"text","text":"A protocol that represents a date picker input field in a form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/dateFormat":{"abstract":[{"text":"Required. The string format of the date.","type":"text"},{"text":" ","type":"text"},{"text":"This property defines how the date should be formatted when displayed or submitted.","type":"text"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput\/dateformat","title":"dateFormat","role":"symbol","navigatorTitle":[{"text":"dateFormat","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/isDateAndTime":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/isDateAndTime","title":"isDateAndTime","abstract":[{"type":"text","text":"A flag that indicates whether the date picker includes time selection."},{"type":"text","text":" "},{"type":"text","text":"This property is automatically determined based on the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","isActive":true},{"type":"text","text":"."}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"isDateAndTime"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput\/isdateandtime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDateAndTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isDateAndTime","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"isDateAndTime"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isDateAndTime","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormDatePickerInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle"},{"value":"dateFormat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1dateFormat\/title"},{"value":[{"kind":"identifier","text":"dateFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1dateFormat\/fragments"},{"value":"isDateAndTime","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1isDateAndTime\/title"},{"value":[{"text":"isDateAndTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1isDateAndTime\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}