{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/maximumDate"},"metadata":{"role":"symbol","title":"maximumDate","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false}],"navigatorTitle":[{"text":"maximumDate","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIFormDatePickerInput(py)maximumDate","required":true},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/maximumdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/maximumdate"]}],"abstract":[{"text":"The latest allowable date this input accepts.","type":"text"},{"text":" ","type":"text"},{"text":"This property sets an upper bound on the selectable dates. If not set, there is no maximum date limit.","type":"text"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"title":"FormDatePickerInput","role":"symbol","type":"topic","abstract":[{"text":"A protocol that represents a date picker input field in a form.","type":"text"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/maximumDate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"abstract":[{"text":"The latest allowable date this input accepts.","type":"text"},{"text":" ","type":"text"},{"text":"This property sets an upper bound on the selectable dates. If not set, there is no maximum date limit.","type":"text"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput\/maximumdate","navigatorTitle":[{"kind":"identifier","text":"maximumDate"}],"role":"symbol","title":"maximumDate","kind":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/maximumDate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maximumDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maximumDate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"maximumDate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title","value":"SMIFormDatePickerInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1maximumDate\/title","value":"maximumDate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1maximumDate\/fragments","op":"replace","value":[{"text":"maximumDate","kind":"identifier"}]}]}]}