{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/minimumDate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput"]]},"sections":[],"abstract":[{"type":"text","text":"The earliest allowable date this input accepts."},{"type":"text","text":" "},{"type":"text","text":"This property sets a lower bound on the selectable dates. If not set, there is no minimum date limit."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/minimumdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/minimumdate"]}],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"platforms":[{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"8.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false}],"externalID":"c:objc(pl)SMIFormDatePickerInput(py)minimumDate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"minimumDate","kind":"identifier"}],"title":"minimumDate","required":true},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/minimumDate":{"url":"\/documentation\/smiclientcore\/formdatepickerinput\/minimumdate","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"minimumDate","type":"topic","required":true,"abstract":[{"text":"The earliest allowable date this input accepts.","type":"text"},{"text":" ","type":"text"},{"text":"This property sets a lower bound on the selectable dates. If not set, there is no minimum date limit.","type":"text"}],"navigatorTitle":[{"text":"minimumDate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/minimumDate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol","title":"FormDatePickerInput","abstract":[{"type":"text","text":"A protocol that represents a date picker input field in a form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minimumDate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minimumDate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"minimumDate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1minimumDate\/title","op":"replace","value":"minimumDate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1minimumDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumDate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title","op":"replace","value":"SMIFormDatePickerInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments","op":"replace","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}]}]}]}