{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput"]]},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/startdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formdatepickerinput\/startdate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"startDate","kind":"identifier"}],"title":"startDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(pl)SMIFormDatePickerInput(py)startDate","modules":[{"name":"SMIClientCore"}],"platforms":[{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"Mac Catalyst","unavailable":false}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/startDate"},"abstract":[{"type":"text","text":"The initial default value for the date assigned to this input."},{"type":"text","text":" "},{"type":"text","text":"This property provides a starting value for the date picker. If not set, no default date is selected."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/startDate":{"kind":"symbol","navigatorTitle":[{"text":"startDate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/startDate","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The initial default value for the date assigned to this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a starting value for the date picker. If not set, no default date is selected.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formdatepickerinput\/startdate","title":"startDate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"title":"FormDatePickerInput","role":"symbol","type":"topic","abstract":[{"text":"A protocol that represents a date picker input field in a form.","type":"text"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"startDate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"startDate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"startDate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1startDate\/title","value":"startDate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1startDate\/fragments","value":[{"kind":"identifier","text":"startDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title","value":"SMIFormDatePickerInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}]}]}]}