{"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","title":"imageId","roleHeading":"Instance Property","externalID":"c:objc(pl)SMITitleImageItem(py)imageId","navigatorTitle":[{"kind":"identifier","text":"imageId"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem\/imageId","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"The unique identifier of the image associated with this title item.","type":"text"},{"text":" ","type":"text"},{"text":"This identifier can be used to fetch the actual image content from the SDK’s","type":"text"},{"text":" ","type":"text"},{"text":"asset management system.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/titleimageitem\/imageid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/titleimageitem\/imageid"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleImageItem":{"title":"TitleImageItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem","url":"\/documentation\/smiclientcore\/titleimageitem","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a title item with an associated image in a carousel or form."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TitleImageItem"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleImageItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleImageItem/imageId":{"type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem\/imageId","url":"\/documentation\/smiclientcore\/titleimageitem\/imageid","title":"imageId","abstract":[{"text":"The unique identifier of the image associated with this title item.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This identifier can be used to fetch the actual image content from the SDK’s"},{"type":"text","text":" "},{"type":"text","text":"asset management system."}],"kind":"symbol","navigatorTitle":[{"text":"imageId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"imageId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SMITitleImageItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMITitleImageItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/fragments"},{"op":"replace","value":[{"text":"SMITitleImageItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/navigatorTitle"},{"op":"replace","value":"imageId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem~1imageId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageId"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem~1imageId\/fragments"}]}]}