{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connecting"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconnectionstate\/connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconnectionstate\/connecting"]}],"metadata":{"externalID":"c:@SMIMultimediaConnectionStateConnecting","roleHeading":"Type Property","title":"connecting","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"extendedModule":"SMIMultimediaCommon","navigatorTitle":[{"text":"SMIMultimediaConnectionStateConnecting","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState","text":"MultimediaConnectionState","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A connection attempt is in progress."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/connecting":{"role":"symbol","type":"topic","title":"connecting","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connecting","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateConnecting","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/connecting","abstract":[{"type":"text","text":"A connection attempt is in progress."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState":{"title":"MultimediaConnectionState","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate","kind":"symbol","navigatorTitle":[{"text":"MultimediaConnectionState","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaConnectionState","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible connection states of a multimedia session.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIMultimediaConnectionStateConnecting","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionStateConnecting","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState","text":"SMIMultimediaConnectionState"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIMultimediaConnectionStateConnecting"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIMultimediaConnectionStateConnecting","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connecting\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionStateConnecting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connecting\/fragments"},{"op":"replace","value":"SMIMultimediaConnectionState","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/navigatorTitle"}]}]}