{"kind":"symbol","metadata":{"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachmentStorageLimitExceeded","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentStorageLimitExceeded"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentStorageLimitExceeded"}],"title":"ErrorCodes.attachmentStorageLimitExceeded"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Error code when storage limit is exceeded for attachment uploads.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentStorageLimitExceeded","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentStorageLimitExceeded"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentstoragelimitexceeded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentstoragelimitexceeded"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentStorageLimitExceeded":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentStorageLimitExceeded","role":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentstoragelimitexceeded","abstract":[{"text":"Error code when storage limit is exceeded for attachment uploads.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentStorageLimitExceeded","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentStorageLimitExceeded"}],"title":"ErrorCodes.attachmentStorageLimitExceeded"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","title":"ErrorCodes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIErrorCodesAttachmentStorageLimitExceeded","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIErrorCodesAttachmentStorageLimitExceeded","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SMIErrorCodesAttachmentStorageLimitExceeded","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIErrorCodesAttachmentStorageLimitExceeded","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentStorageLimitExceeded\/title"},{"value":[{"text":"SMIErrorCodesAttachmentStorageLimitExceeded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentStorageLimitExceeded\/fragments"},{"value":"SMIErrorCodes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title"},{"value":[{"kind":"identifier","text":"SMIErrorCodes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments"},{"value":[{"kind":"identifier","text":"SMIErrorCodes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}