{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadNotEnabled","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"abstract":[{"text":"Error code when attachment upload feature is not enabled.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotenabled"]}],"metadata":{"role":"symbol","roleHeading":"Case","title":"ErrorCodes.attachmentUploadNotEnabled","externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachmentUploadNotEnabled","modules":[{"name":"SMIClientCore"}],"symbolKind":"case","navigatorTitle":[{"text":"SMIErrorCodesAttachmentUploadNotEnabled","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadNotEnabled","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotEnabled","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentUploadNotEnabled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadNotEnabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotenabled","type":"topic","title":"ErrorCodes.attachmentUploadNotEnabled","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotEnabled","navigatorTitle":[{"text":"SMIErrorCodesAttachmentUploadNotEnabled","kind":"identifier"}],"abstract":[{"text":"Error code when attachment upload feature is not enabled.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"title":"ErrorCodes","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible error codes that can occur in the SDK."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SMIErrorCodesAttachmentUploadNotEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotEnabled"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIErrorCodesAttachmentUploadNotEnabled","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotEnabled\/title","value":"SMIErrorCodesAttachmentUploadNotEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotEnabled\/fragments","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","value":"SMIErrorCodes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","value":[{"text":"SMIErrorCodes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","value":[{"text":"SMIErrorCodes","kind":"identifier"}],"op":"replace"}]}]}