{"variants":[{"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotallowed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotallowed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotAllowed"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentUploadNotAllowed"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Error code when attachment upload is not allowed for the current user or context."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"SMIErrorCodesAttachmentUploadNotAllowed","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadNotAllowed","kind":"identifier"}],"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachmentUploadNotAllowed","title":"ErrorCodes.attachmentUploadNotAllowed","modules":[{"name":"SMIClientCore"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentUploadNotAllowed":{"abstract":[{"type":"text","text":"Error code when attachment upload is not allowed for the current user or context."}],"navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotAllowed"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotAllowed","title":"ErrorCodes.attachmentUploadNotAllowed","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentUploadNotAllowed"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotallowed"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","title":"ErrorCodes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIErrorCodesAttachmentUploadNotAllowed","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIErrorCodesAttachmentUploadNotAllowed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotAllowed"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIErrorCodesAttachmentUploadNotAllowed","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotAllowed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotAllowed"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotAllowed\/fragments"},{"op":"replace","value":"SMIErrorCodes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title"},{"op":"replace","value":[{"text":"SMIErrorCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle"}]}]}