{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachment"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachment"}],"title":"ErrorCodes.attachment","roleHeading":"Case","modules":[{"name":"SMIClientCore"}],"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachment","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachment"}],"role":"symbol","symbolKind":"case"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachment","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Error code when there is a general issue with file attachments.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"title":"ErrorCodes","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible error codes that can occur in the SDK."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachment":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachment","abstract":[{"type":"text","text":"Error code when there is a general issue with file attachments."}],"role":"symbol","title":"ErrorCodes.attachment","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachment","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/attachment","navigatorTitle":[{"text":"SMIErrorCodesAttachment","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIErrorCodesAttachment"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SMIErrorCodesAttachment"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMIErrorCodesAttachment","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIErrorCodes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIErrorCodes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIErrorCodes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","op":"replace"},{"value":"SMIErrorCodesAttachment","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachment\/title","op":"replace"},{"value":[{"text":"SMIErrorCodesAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachment\/fragments","op":"replace"}]}]}