{"abstract":[{"text":"Error code when the requested attachment is not found.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentnotfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmentnotfound"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentNotFound"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentNotFound","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachmentNotFound","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentNotFound","kind":"identifier"}],"navigatorTitle":[{"text":"SMIErrorCodesAttachmentNotFound","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SMIClientCore"}],"roleHeading":"Case","title":"ErrorCodes.attachmentNotFound"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentNotFound":{"url":"\/documentation\/smiclientcore\/errorcodes\/attachmentnotfound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentNotFound","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Error code when the requested attachment is not found."}],"role":"symbol","navigatorTitle":[{"text":"SMIErrorCodesAttachmentNotFound","kind":"identifier"}],"kind":"symbol","title":"ErrorCodes.attachmentNotFound","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentNotFound"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"type":"topic","role":"symbol","title":"ErrorCodes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","navigatorTitle":[{"text":"ErrorCodes","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/errorcodes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIErrorCodesAttachmentNotFound","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIErrorCodesAttachmentNotFound","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"SMIErrorCodesAttachmentNotFound","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentNotFound\/title","op":"replace","value":"SMIErrorCodesAttachmentNotFound"},{"op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentNotFound"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentNotFound\/fragments"},{"op":"replace","value":"SMIErrorCodes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments"},{"op":"replace","value":[{"text":"SMIErrorCodes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle"}]}]}