{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmenttoolarge"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/attachmenttoolarge"]}],"abstract":[{"type":"text","text":"Error code when the attachment is too large to upload."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentTooLarge","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentTooLarge","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentTooLarge"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@SMIErrorCodes@SMIErrorCodesAttachmentTooLarge","title":"ErrorCodes.attachmentTooLarge","navigatorTitle":[{"text":"SMIErrorCodesAttachmentTooLarge","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"SMIClientCore"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/errorcodes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"type":"topic","title":"ErrorCodes","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentTooLarge":{"title":"ErrorCodes.attachmentTooLarge","url":"\/documentation\/smiclientcore\/errorcodes\/attachmenttoolarge","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentTooLarge","abstract":[{"text":"Error code when the attachment is too large to upload.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentTooLarge","kind":"identifier"}],"navigatorTitle":[{"text":"SMIErrorCodesAttachmentTooLarge","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIErrorCodesAttachmentTooLarge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentTooLarge"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SMIErrorCodesAttachmentTooLarge","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","op":"replace","value":"SMIErrorCodes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","op":"replace","value":[{"text":"SMIErrorCodes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentTooLarge\/title","op":"replace","value":"SMIErrorCodesAttachmentTooLarge"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentTooLarge\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentTooLarge"}]}]}]}