{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/hashValue"},"metadata":{"symbolKind":"property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@SMIErrorCodes","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}],"title":"hashValue","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"roleHeading":"Instance Property","extendedModule":"Swift","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/smiclientcore\/errorcodes\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/RawRepresentable-Implementations"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/RawRepresentable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/RawRepresentable-Implementations","url":"\/documentation\/smiclientcore\/errorcodes\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"type":"topic","abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"title":"ErrorCodes","url":"\/documentation\/smiclientcore\/errorcodes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/hashValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","abstract":[],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hashValue","role":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/hashvalue","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","value":"SMIErrorCodes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","value":[{"kind":"identifier","text":"SMIErrorCodes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIErrorCodes"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}