{"sections":[],"abstract":[{"type":"text","text":"A secure form submission failed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/secureFormSubmission","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secureFormSubmission"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorcodes\/secureformsubmission"]},{"paths":["\/documentation\/smiclientcore\/errorcodes\/secureformsubmission"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"SMIErrorCodesSecureFormSubmission","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secureFormSubmission","kind":"identifier"}],"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesSecureFormSubmission","title":"ErrorCodes.secureFormSubmission","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/secureFormSubmission":{"abstract":[{"type":"text","text":"A secure form submission failed."}],"navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesSecureFormSubmission"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/secureFormSubmission","title":"ErrorCodes.secureFormSubmission","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secureFormSubmission"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/secureformsubmission"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","title":"ErrorCodes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SMIErrorCodesSecureFormSubmission","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SMIErrorCodesSecureFormSubmission","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SMIErrorCodesSecureFormSubmission","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1secureFormSubmission\/title","value":"SMIErrorCodesSecureFormSubmission"},{"value":[{"text":"SMIErrorCodesSecureFormSubmission","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1secureFormSubmission\/fragments","op":"replace"},{"value":"SMIErrorCodes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","op":"replace","value":[{"text":"SMIErrorCodes","kind":"identifier"}]}]}]}