{"kind":"symbol","metadata":{"externalID":"c:@E@SMIErrorCodes@SMIErrorCodesUserVerificationInvalidOrMissing","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userVerificationInvalidOrMissing","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SMIErrorCodesUserVerificationInvalidOrMissing","kind":"identifier"}],"title":"ErrorCodes.userVerificationInvalidOrMissing"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Returned when an invalid or missing response is returned from the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userVerificationInvalidOrMissing","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationInvalidOrMissing","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/errorcodes\/userverificationinvalidormissing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/errorcodes\/userverificationinvalidormissing"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/userVerificationInvalidOrMissing":{"url":"\/documentation\/smiclientcore\/errorcodes\/userverificationinvalidormissing","abstract":[{"text":"Returned when an invalid or missing response is returned from the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationInvalidOrMissing","role":"symbol","navigatorTitle":[{"text":"SMIErrorCodesUserVerificationInvalidOrMissing","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userVerificationInvalidOrMissing"}],"type":"topic","title":"ErrorCodes.userVerificationInvalidOrMissing"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/userVerificationDelegate":{"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/userverificationdelegate","title":"userVerificationDelegate","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","navigatorTitle":[{"text":"userVerificationDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegate that provides the challenge for the identity token for user verified connections."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userVerificationDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate","text":"UserVerificationDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","title":"ErrorCodes"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SMIErrorCodesUserVerificationInvalidOrMissing","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIErrorCodesUserVerificationInvalidOrMissing","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIErrorCodesUserVerificationInvalidOrMissing","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationInvalidOrMissing\/title","value":"SMIErrorCodesUserVerificationInvalidOrMissing","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationInvalidOrMissing\/fragments","value":[{"text":"SMIErrorCodesUserVerificationInvalidOrMissing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/title","value":"userVerificationDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/fragments","value":[{"text":"userVerificationDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","value":"SMIErrorCodes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","value":[{"text":"SMIErrorCodes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIErrorCodes"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}