{"metadata":{"title":"ErrorCodes.userVerificationNoDelegate","modules":[{"name":"SMIClientCore"}],"symbolKind":"case","externalID":"c:@E@SMIErrorCodes@SMIErrorCodesUserVerificationNoDelegate","roleHeading":"Case","navigatorTitle":[{"text":"SMIErrorCodesUserVerificationNoDelegate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userVerificationNoDelegate","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"]]},"abstract":[{"type":"text","text":"The user verification delegate was not set using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","isActive":true},{"type":"text","text":" property."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationNoDelegate"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationNoDelegate"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/errorcodes\/userverificationnodelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/errorcodes\/userverificationnodelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"type":"topic","abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"title":"ErrorCodes","url":"\/documentation\/smiclientcore\/errorcodes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/userVerificationNoDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationNoDelegate"}],"abstract":[{"type":"text","text":"The user verification delegate was not set using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","type":"reference","isActive":true},{"type":"text","text":" property."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationNoDelegate"}],"url":"\/documentation\/smiclientcore\/errorcodes\/userverificationnodelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationNoDelegate","title":"ErrorCodes.userVerificationNoDelegate","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/userVerificationDelegate":{"abstract":[{"type":"text","text":"The delegate that provides the challenge for the identity token for user verified connections."}],"url":"\/documentation\/smiclientcore\/coreclient\/userverificationdelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userVerificationDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UserVerificationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate"},{"text":")?","kind":"text"}],"required":true,"title":"userVerificationDelegate","kind":"symbol","navigatorTitle":[{"text":"userVerificationDelegate","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SMIErrorCodesUserVerificationNoDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationNoDelegate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMIErrorCodesUserVerificationNoDelegate","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","op":"replace","value":"SMIErrorCodes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationNoDelegate\/title","op":"replace","value":"SMIErrorCodesUserVerificationNoDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationNoDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationNoDelegate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/title","op":"replace","value":"userVerificationDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/fragments","op":"replace","value":[{"text":"userVerificationDelegate","kind":"identifier"}]}]}]}