{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]]},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"}],"extendedModule":"SMIClientCore","role":"symbol","externalID":"c:@SMISessionStatusActive","navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusActive"}],"modules":[{"name":"SMIClientCore"}],"title":"active","roleHeading":"Type Property","symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/active"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/active"]}],"abstract":[{"type":"text","text":"Session is currently active."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session is active and can handle interactions."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/active","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/active":{"type":"topic","url":"\/documentation\/smiclientcore\/sessionstatus\/active","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SMISessionStatusActive","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/active","title":"active","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"abstract":[{"text":"Session is currently active.","type":"text"},{"type":"text","text":" "},{"text":"This value indicates that the session is active and can handle interactions.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","role":"symbol","url":"\/documentation\/smiclientcore\/sessionstatus","abstract":[{"text":"An enum that defines the possible states of a session.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SessionStatus","kind":"identifier"}],"title":"SessionStatus"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SMISessionStatusActive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusActive"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SMISessionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatusActive","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1active\/title","value":"SMISessionStatusActive"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1active\/fragments","value":[{"kind":"identifier","text":"SMISessionStatusActive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title","value":"SMISessionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments","value":[{"text":"SMISessionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle","value":[{"text":"SMISessionStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}