{"sections":[],"kind":"symbol","abstract":[{"text":"Session requires consent.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session requires user consent to proceed.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusConsent"}],"title":"consent","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","role":"symbol","roleHeading":"Type Property","externalID":"c:@SMISessionStatusConsent","symbolKind":"property"},"variants":[{"paths":["\/documentation\/smiclientcore\/sessionstatus\/consent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessionstatus\/consent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/consent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"}],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/consent":{"navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusConsent"}],"kind":"symbol","title":"consent","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"}],"abstract":[{"type":"text","text":"Session requires consent."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session requires user consent to proceed."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/consent","url":"\/documentation\/smiclientcore\/sessionstatus\/consent","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"navigatorTitle":[{"kind":"identifier","text":"SessionStatus"}],"url":"\/documentation\/smiclientcore\/sessionstatus","title":"SessionStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a session."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionStatus"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMISessionStatusConsent","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMISessionStatusConsent"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SMISessionStatus","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatusConsent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMISessionStatusConsent","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1consent\/title"},{"value":[{"kind":"identifier","text":"SMISessionStatusConsent"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1consent\/fragments"},{"value":"SMISessionStatus","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title"},{"value":[{"kind":"identifier","text":"SMISessionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments"},{"value":[{"kind":"identifier","text":"SMISessionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}