{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/ended"},"metadata":{"navigatorTitle":[{"text":"SMISessionStatusEnded","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","role":"symbol","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier"}],"roleHeading":"Type Property","title":"ended","externalID":"c:@SMISessionStatusEnded"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/ended"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/ended"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Session has ended.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session has been terminated.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ended"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","kind":"typeIdentifier","text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"abstract":[{"text":"An enum that defines the possible states of a session.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SessionStatus","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","title":"SessionStatus","url":"\/documentation\/smiclientcore\/sessionstatus"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/ended":{"title":"ended","url":"\/documentation\/smiclientcore\/sessionstatus\/ended","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/ended","abstract":[{"type":"text","text":"Session has ended."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session has been terminated."}],"navigatorTitle":[{"text":"SMISessionStatusEnded","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMISessionStatusEnded","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusEnded"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMISessionStatusEnded","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMISessionStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title"},{"op":"replace","value":[{"text":"SMISessionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments"},{"op":"replace","value":[{"text":"SMISessionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle"},{"op":"replace","value":"SMISessionStatusEnded","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1ended\/title"},{"op":"replace","value":[{"text":"SMISessionStatusEnded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1ended\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}