{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_SwiftNewtypeWrapper.hash(into:)"},{"type":"text","text":"."}],"metadata":{"title":"hash(into:)","symbolKind":"method","extendedModule":"Swift","role":"symbol","roleHeading":"Instance Method","externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:SMISessionStatus.h@T@SMISessionStatus","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"modules":[{"name":"SMIClientCore","relatedModules":["Swift"]}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]}},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/hash(into:)"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/hash(into:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/_SwiftNewtypeWrapper-Implementations"]]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/_SwiftNewtypeWrapper-Implementations":{"title":"_SwiftNewtypeWrapper Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/_SwiftNewtypeWrapper-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/smiclientcore\/sessionstatus\/_swiftnewtypewrapper-implementations","type":"topic","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/hash(into:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/hash(into:)","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"kind":"symbol","url":"\/documentation\/smiclientcore\/sessionstatus\/hash(into:)","type":"topic","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"abstract":[{"text":"An enum that defines the possible states of a session.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SessionStatus","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","title":"SessionStatus","url":"\/documentation\/smiclientcore\/sessionstatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title","value":"SMISessionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments","value":[{"text":"SMISessionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionStatus"}],"op":"replace"}]}]}