{"variants":[{"paths":["\/documentation\/smiclientcore\/sessionstatus\/inactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessionstatus\/inactive"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Session is currently inactive."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session is inactive but not ended."}],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusInactive"}],"externalID":"c:@SMISessionStatusInactive","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Type Property","title":"inactive","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/inactive"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"type":"topic","title":"SessionStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a session."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SessionStatus"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SessionStatus"}],"url":"\/documentation\/smiclientcore\/sessionstatus"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/inactive":{"navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusInactive"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/inactive","title":"inactive","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier","text":"SessionStatus"}],"abstract":[{"text":"Session is currently inactive.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session is inactive but not ended.","type":"text"}],"url":"\/documentation\/smiclientcore\/sessionstatus\/inactive"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMISessionStatusInactive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusInactive"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","text":"SMISessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatusInactive","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title","op":"replace","value":"SMISessionStatus"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments","op":"replace","value":[{"text":"SMISessionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1inactive\/title","op":"replace","value":"SMISessionStatusInactive"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1inactive\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusInactive"}]}]}]}