{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]]},"metadata":{"title":"waiting","role":"symbol","symbolKind":"property","extendedModule":"SMIClientCore","roleHeading":"Type Property","externalID":"c:@SMISessionStatusWaiting","navigatorTitle":[{"text":"SMISessionStatusWaiting","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier"}]},"kind":"symbol","sections":[],"abstract":[{"text":"Session is waiting.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session is waiting for a response or action.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/waiting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatus\/waiting"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"waiting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/waiting","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"navigatorTitle":[{"kind":"identifier","text":"SessionStatus"}],"url":"\/documentation\/smiclientcore\/sessionstatus","title":"SessionStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a session."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionStatus"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/waiting":{"type":"topic","abstract":[{"type":"text","text":"Session is waiting."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session is waiting for a response or action."}],"kind":"symbol","title":"waiting","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusWaiting"}],"url":"\/documentation\/smiclientcore\/sessionstatus\/waiting","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/waiting","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"waiting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMISessionStatusWaiting","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMISessionStatusWaiting"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatus","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatusWaiting","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMISessionStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments","op":"replace"},{"value":[{"text":"SMISessionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle","op":"replace"},{"value":"SMISessionStatusWaiting","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1waiting\/title","op":"replace"},{"value":[{"text":"SMISessionStatusWaiting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1waiting\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}