{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accepted"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"RoutingWorkTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Type Property","symbolKind":"property","extendedModule":"SMIClientCore","navigatorTitle":[{"text":"SMIRoutingWorkTypesAccepted","kind":"identifier"}],"title":"accepted","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accepted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"RoutingWorkTypes","kind":"typeIdentifier"}],"externalID":"c:@SMIRoutingWorkTypesAccepted","role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/accepted","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingworktypes\/accepted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/routingworktypes\/accepted"]}],"abstract":[{"text":"Indicates the action of an agent accepting a routing work.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/accepted":{"abstract":[{"text":"Indicates the action of an agent accepting a routing work.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/routingworktypes\/accepted","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accepted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"navigatorTitle":[{"text":"SMIRoutingWorkTypesAccepted","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/accepted","title":"accepted","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of routing work operations that can occur in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"title":"RoutingWorkTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/routingworktypes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIRoutingWorkTypesAccepted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIRoutingWorkTypesAccepted","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"SMIRoutingWorkTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIRoutingWorkTypesAccepted"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1accepted\/title","op":"replace","value":"SMIRoutingWorkTypesAccepted"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1accepted\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRoutingWorkTypesAccepted"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","op":"replace","value":"SMIRoutingWorkTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}