{"kind":"symbol","metadata":{"title":"assigned","externalID":"c:@SMIRoutingWorkTypesAssigned","role":"symbol","extendedModule":"SMIClientCore","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assigned","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIRoutingWorkTypesAssigned","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"abstract":[{"type":"text","text":"Indicates the action of assigning a routing work to an agent."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingworktypes\/assigned"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/routingworktypes\/assigned"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/assigned","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assigned","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","text":"RoutingWorkTypes","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/assigned":{"title":"assigned","abstract":[{"text":"Indicates the action of assigning a routing work to an agent.","type":"text"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assigned","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"navigatorTitle":[{"text":"SMIRoutingWorkTypesAssigned","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/routingworktypes\/assigned","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/assigned","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"abstract":[{"text":"An enum that defines the possible types of routing work operations that can occur in a conversation.","type":"text"}],"type":"topic","title":"RoutingWorkTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/routingworktypes","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIRoutingWorkTypesAssigned","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIRoutingWorkTypesAssigned","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"SMIRoutingWorkTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIRoutingWorkTypesAssigned"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIRoutingWorkTypesAssigned","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1assigned\/title","op":"replace"},{"value":[{"text":"SMIRoutingWorkTypesAssigned","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1assigned\/fragments","op":"replace"},{"value":"SMIRoutingWorkTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","op":"replace"},{"value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRoutingWorkTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}