{"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","symbolKind":"property","title":"closed","role":"symbol","externalID":"c:@SMIRoutingWorkTypesClosed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","kind":"typeIdentifier","text":"RoutingWorkTypes"}],"extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMIRoutingWorkTypesClosed"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/closed","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/routingworktypes\/closed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/routingworktypes\/closed"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Indicates the action of closing a routing work.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/closed":{"role":"symbol","type":"topic","title":"closed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/closed","navigatorTitle":[{"kind":"identifier","text":"SMIRoutingWorkTypesClosed"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"url":"\/documentation\/smiclientcore\/routingworktypes\/closed","abstract":[{"type":"text","text":"Indicates the action of closing a routing work."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"abstract":[{"text":"An enum that defines the possible types of routing work operations that can occur in a conversation.","type":"text"}],"type":"topic","title":"RoutingWorkTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/routingworktypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIRoutingWorkTypesClosed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIRoutingWorkTypesClosed","kind":"identifier"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","text":"SMIRoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIRoutingWorkTypesClosed"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1closed\/title","value":"SMIRoutingWorkTypesClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1closed\/fragments","value":[{"text":"SMIRoutingWorkTypesClosed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","value":"SMIRoutingWorkTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]}]}]}