{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingworktypes\/equatable-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"SMIClientCore"}],"role":"collectionGroup"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/!=(_:_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/smiclientcore\/routingworktypes\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/!=(_:_:)","title":"!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","title":"RoutingWorkTypes","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of routing work operations that can occur in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/routingworktypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","op":"replace","value":"SMIRoutingWorkTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}