{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/escalated"},"abstract":[{"type":"text","text":"Indicates the action of escalating to a new agent."}],"variants":[{"paths":["\/documentation\/smiclientcore\/routingworktypes\/escalated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/routingworktypes\/escalated"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"escalated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","text":"RoutingWorkTypes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIRoutingWorkTypesEscalated"}],"modules":[{"name":"SMIClientCore"}],"title":"escalated","roleHeading":"Type Property","symbolKind":"property","externalID":"c:@SMIRoutingWorkTypesEscalated","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"escalated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"RoutingWorkTypes"}],"extendedModule":"SMIClientCore","role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/escalated":{"title":"escalated","abstract":[{"type":"text","text":"Indicates the action of escalating to a new agent."}],"url":"\/documentation\/smiclientcore\/routingworktypes\/escalated","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/escalated","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"escalated"},{"kind":"text","text":": "},{"text":"RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"navigatorTitle":[{"text":"SMIRoutingWorkTypesEscalated","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","title":"RoutingWorkTypes","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of routing work operations that can occur in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/routingworktypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIRoutingWorkTypesEscalated","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIRoutingWorkTypesEscalated"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"SMIRoutingWorkTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIRoutingWorkTypesEscalated"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1escalated\/title","op":"replace","value":"SMIRoutingWorkTypesEscalated"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1escalated\/fragments","op":"replace","value":[{"text":"SMIRoutingWorkTypesEscalated","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","op":"replace","value":"SMIRoutingWorkTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]}]}]}