{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/init(rawValue:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/routingworktypes\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"SMIClientCore"}],"externalID":"s:So19SMIRoutingWorkTypesa8rawValueABSS_tcfc","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of routing work operations that can occur in a conversation."}],"role":"symbol","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"title":"RoutingWorkTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/routingworktypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/smiclientcore\/routingworktypes\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SMIRoutingWorkTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRoutingWorkTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments"},{"op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}