{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/!=(_:_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Operator","symbolKind":"op","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","modules":[{"relatedModules":["Swift"],"name":"SMIClientCore"}],"title":"!=(_:_:)","extendedModule":"Swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/!=(_:_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"abstract":[{"text":"An enum that defines the possible operations that can be performed on conversation participants.","type":"text"}],"navigatorTitle":[{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","title":"ParticipantChangedOperationTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/!=(_:_:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/!=(_:_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title","op":"replace","value":"SMIParticipantChangedOperationTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments","op":"replace","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}