{"abstract":[{"type":"text","text":"Indicates the action of adding a participant to the conversation."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"]]},"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantChangedOperationTypes","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes"}],"externalID":"c:@SMIParticipantChangedOperationTypesAdd","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"}],"symbolKind":"property","title":"add","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantChangedOperationTypes","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/add"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/add"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/add","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"title":"ParticipantChangedOperationTypes","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperationTypes"}],"role":"symbol","abstract":[{"text":"An enum that defines the possible operations that can be performed on conversation participants.","type":"text"}],"url":"\/documentation\/smiclientcore\/participantchangedoperationtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperationTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/add":{"url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/add","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/add","abstract":[{"type":"text","text":"Indicates the action of adding a participant to the conversation."}],"title":"add","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","text":"ParticipantChangedOperationTypes"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIParticipantChangedOperationTypesAdd","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SMIParticipantChangedOperationTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title"},{"op":"replace","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle"},{"op":"replace","value":"SMIParticipantChangedOperationTypesAdd","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1add\/title"},{"op":"replace","value":[{"text":"SMIParticipantChangedOperationTypesAdd","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1add\/fragments"}]}]}