{"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/!=(_:_:)"],"generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"kind":"article","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","navigatorTitle":[{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible operations that can be performed on conversation participants."}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"title":"ParticipantChangedOperationTypes","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"!=(_:_:)","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/!=(_:_:)","type":"topic","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/!=(_:_:)","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title","value":"SMIParticipantChangedOperationTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypes"}]}]}]}