{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/remove","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"]]},"abstract":[{"text":"Indicates the action of removing a participant from the conversation.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","text":"ParticipantChangedOperationTypes","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/remove"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes\/remove"]}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"remove","navigatorTitle":[{"text":"SMIParticipantChangedOperationTypesRemove","kind":"identifier"}],"symbolKind":"property","externalID":"c:@SMIParticipantChangedOperationTypesRemove","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","navigatorTitle":[{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible operations that can be performed on conversation participants."}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"title":"ParticipantChangedOperationTypes","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/remove":{"title":"remove","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","kind":"typeIdentifier","text":"ParticipantChangedOperationTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/remove","type":"topic","abstract":[{"type":"text","text":"Indicates the action of removing a participant from the conversation."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesRemove"}],"url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/remove"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIParticipantChangedOperationTypesRemove"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesRemove"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","text":"SMIParticipantChangedOperationTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIParticipantChangedOperationTypesRemove","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title","value":"SMIParticipantChangedOperationTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1remove\/title","value":"SMIParticipantChangedOperationTypesRemove"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1remove\/fragments","value":[{"text":"SMIParticipantChangedOperationTypesRemove","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}