{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessHours"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","text":"BusinessHours","preciseIdentifier":"c:objc(pl)SMIBusinessHours"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A list of time intervals that define when the deployment is open for business."},{"type":"text","text":" "},{"type":"text","text":"Each interval is represented by a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","isActive":true},{"type":"text","text":" object containing start and end times."}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessHours"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"BusinessHours","preciseIdentifier":"c:objc(pl)SMIBusinessHours"},{"kind":"text","text":"]"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"businessHours"}],"roleHeading":"Instance Property","required":true,"symbolKind":"property","role":"symbol","title":"businessHours","externalID":"c:objc(pl)SMIBusinessHoursInfo(py)businessHours"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/businesshours"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/businesshours"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/businessHours"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours":{"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines a time interval for business hours."}],"navigatorTitle":[{"text":"BusinessHours","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"title":"BusinessHours","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","url":"\/documentation\/smiclientcore\/businesshours"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/businessHours":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/businessHours","kind":"symbol","abstract":[{"text":"A list of time intervals that define when the deployment is open for business.","type":"text"},{"text":" ","type":"text"},{"text":"Each interval is represented by a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","isActive":true,"type":"reference"},{"text":" object containing start and end times.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"businessHours","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"BusinessHours","preciseIdentifier":"c:objc(pl)SMIBusinessHours","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"required":true,"navigatorTitle":[{"text":"businessHours","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo\/businesshours","role":"symbol","type":"topic","title":"businessHours"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"title":"BusinessHoursInfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfo"}],"navigatorTitle":[{"kind":"identifier","text":"BusinessHoursInfo"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines the business hours configuration for a deployment."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","type":"topic","url":"\/documentation\/smiclientcore\/businesshoursinfo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"businessHours","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"businessHours"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<SMIBusinessHours>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"businessHours"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SMIBusinessHours","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/fragments","value":[{"text":"SMIBusinessHours","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/navigatorTitle","value":[{"kind":"identifier","text":"SMIBusinessHours"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1businessHours\/title","value":"businessHours","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1businessHours\/fragments","value":[{"text":"businessHours","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title","value":"SMIBusinessHoursInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SMIBusinessHoursInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}