{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"active"}],"modules":[{"name":"SMIClientCore"}],"title":"isActive","required":true,"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(pl)SMIBusinessHoursInfo(py)active","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Indicates whether the business hours configuration is currently active.","type":"text"},{"type":"text","text":" "},{"text":"When ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", the deployment is considered closed regardless of the time intervals.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isActive"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/isactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/isactive"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/isActive":{"type":"topic","url":"\/documentation\/smiclientcore\/businesshoursinfo\/isactive","title":"isActive","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isActive","navigatorTitle":[{"kind":"identifier","text":"active"}],"abstract":[{"type":"text","text":"Indicates whether the business hours configuration is currently active."},{"type":"text","text":" "},{"type":"text","text":"When "},{"code":"false","type":"codeVoice"},{"type":"text","text":", the deployment is considered closed regardless of the time intervals."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfo"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BusinessHoursInfo"}],"abstract":[{"text":"A protocol that defines the business hours configuration for a deployment.","type":"text"}],"title":"BusinessHoursInfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"active","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"active"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isActive","kind":"identifier"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"active","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isActive\/title","op":"replace"},{"value":[{"kind":"identifier","text":"active"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isActive\/fragments","op":"replace"},{"value":"SMIBusinessHoursInfo","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title","op":"replace"},{"value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}