{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Checks if a given time falls within any of the configured business hours intervals.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"comparisonTime","type":"codeVoice"},{"text":" parameter specifies the time to check against the business hours intervals.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current time will be used. Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the time falls within any of the","type":"text"},{"text":" ","type":"text"},{"text":"business hours intervals and the configuration is active, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/iswithinbusinesshours(comparisontime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshoursinfo\/iswithinbusinesshours(comparisontime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWithinBusinessHours"},{"kind":"text","text":"("},{"kind":"externalParam","text":"comparisonTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"metadata":{"required":true,"externalID":"c:objc(pl)SMIBusinessHoursInfo(im)isWithinBusinessHours:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isWithinBusinessHours","kind":"identifier"},{"text":"(","kind":"text"},{"text":"comparisonTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"isWithinBusinessHours(comparisonTime:)","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"8.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"8.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"8.0","beta":false}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isWithinBusinessHours:"}],"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isWithinBusinessHours(comparisonTime:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"type":"topic","title":"BusinessHoursInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHoursInfo","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","url":"\/documentation\/smiclientcore\/businesshoursinfo","abstract":[{"text":"A protocol that defines the business hours configuration for a deployment.","type":"text"}],"navigatorTitle":[{"text":"BusinessHoursInfo","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/isWithinBusinessHours(comparisonTime:)":{"abstract":[{"type":"text","text":"Checks if a given time falls within any of the configured business hours intervals."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"comparisonTime","type":"codeVoice"},{"type":"text","text":" parameter specifies the time to check against the business hours intervals."},{"type":"text","text":" "},{"type":"text","text":"If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", the current time will be used. Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the time falls within any of the"},{"type":"text","text":" "},{"type":"text","text":"business hours intervals and the configuration is active, "},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWithinBusinessHours"},{"kind":"text","text":"("},{"kind":"externalParam","text":"comparisonTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isWithinBusinessHours:"}],"required":true,"kind":"symbol","title":"isWithinBusinessHours(comparisonTime:)","url":"\/documentation\/smiclientcore\/businesshoursinfo\/iswithinbusinesshours(comparisontime:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isWithinBusinessHours(comparisonTime:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isWithinBusinessHours:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isWithinBusinessHours:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isWithinBusinessHours:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"comparisonTime","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIBusinessHoursInfo","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments","op":"replace","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle","op":"replace","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isWithinBusinessHours(comparisonTime:)\/title","op":"replace","value":"isWithinBusinessHours:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isWithinBusinessHours(comparisonTime:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isWithinBusinessHours:","kind":"identifier"}]}]}]}