{"variants":[{"paths":["\/documentation\/smiclientcore\/formsingleinputsection\/input"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formsingleinputsection\/input"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"],"anchor":"Related-Documentation"}],"metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"input","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInput","text":"FormInput","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"input","kind":"identifier"}],"title":"input","externalID":"c:objc(pl)SMIFormSingleInputSection(py)input","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"input"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The input object which describes how the input will be presented and collected from a user.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the configuration for the input field, including its type, validation","type":"text"},{"text":" ","type":"text"},{"text":"rules, and presentation details.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/input","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection":{"title":"FormSingleInputSection","navigatorTitle":[{"text":"FormSingleInputSection","kind":"identifier"}],"type":"topic","abstract":[{"text":"A protocol that represents a section in a form that collects a single input value from the user.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputSection","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection","url":"\/documentation\/smiclientcore\/formsingleinputsection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection/input":{"role":"symbol","navigatorTitle":[{"text":"input","kind":"identifier"}],"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"input","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formsingleinputsection\/input","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/input","title":"input","abstract":[{"text":"The input object which describes how the input will be presented and collected from a user.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the configuration for the input field, including its type, validation","type":"text"},{"text":" ","type":"text"},{"text":"rules, and presentation details.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"url":"\/documentation\/smiclientcore\/forminput","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInput"}],"kind":"symbol","title":"FormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInput"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"input","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"input","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFormInput>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFormInput"},{"text":" ","kind":"text"},{"text":"input","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/title","value":"SMIFormSingleInputSection","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/fragments","value":[{"text":"SMIFormSingleInputSection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormSingleInputSection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1input\/title","value":"input","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1input\/fragments","value":[{"text":"input","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments","value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"}]}]}