{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formsingleinputsection\/nextsectioninputid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formsingleinputsection\/nextsectioninputid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/nextSectionInputId"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextSectionInputId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"nextSectionInputId","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"title":"nextSectionInputId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextSectionInputId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:objc(pl)SMIFormSingleInputSection(py)nextSectionInputId","required":true},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection"]]},"sections":[],"abstract":[{"text":"The unique identifier of the next section in the form.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the flow of the form by specifying which section should be shown","type":"text"},{"text":" ","type":"text"},{"text":"after the current section is completed. When ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", there is no next section.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection":{"title":"FormSingleInputSection","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputSection","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formsingleinputsection","navigatorTitle":[{"text":"FormSingleInputSection","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a section in a form that collects a single input value from the user."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection/nextSectionInputId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/nextSectionInputId","url":"\/documentation\/smiclientcore\/formsingleinputsection\/nextsectioninputid","role":"symbol","navigatorTitle":[{"text":"nextSectionInputId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier of the next section in the form."},{"type":"text","text":" "},{"type":"text","text":"This property determines the flow of the form by specifying which section should be shown"},{"type":"text","text":" "},{"type":"text","text":"after the current section is completed. When "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", there is no next section."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextSectionInputId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"nextSectionInputId","kind":"symbol","type":"topic","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"nextSectionInputId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"nextSectionInputId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"nextSectionInputId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormSingleInputSection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/title"},{"op":"replace","value":[{"text":"SMIFormSingleInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/fragments"},{"op":"replace","value":[{"text":"SMIFormSingleInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/navigatorTitle"},{"op":"replace","value":"nextSectionInputId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1nextSectionInputId\/title"},{"op":"replace","value":[{"text":"nextSectionInputId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1nextSectionInputId\/fragments"}]}]}