{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/allowedFileTypes","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"allowedFileTypes","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedFileTypes","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AllowedFileTypes","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAllowedFileTypes"},{"text":")?","kind":"text"}],"externalID":"c:objc(pl)SMIAttachmentConfiguration(py)allowedFileTypes","required":true,"modules":[{"name":"SMIClientCore"}],"title":"allowedFileTypes"},"sections":[],"abstract":[{"text":"The allowed file types configuration.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowedFileTypes","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AllowedFileTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes","preciseIdentifier":"c:objc(pl)SMIAllowedFileTypes","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/allowedfiletypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/allowedfiletypes"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentConfiguration"}],"title":"AttachmentConfiguration","url":"\/documentation\/smiclientcore\/attachmentconfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttachmentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/allowedFileTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/allowedFileTypes","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowedFileTypes"}],"required":true,"url":"\/documentation\/smiclientcore\/attachmentconfiguration\/allowedfiletypes","title":"allowedFileTypes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedFileTypes"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"AllowedFileTypes","preciseIdentifier":"c:objc(pl)SMIAllowedFileTypes"},{"kind":"text","text":")?"}],"kind":"symbol","abstract":[{"type":"text","text":"The allowed file types configuration."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes":{"url":"\/documentation\/smiclientcore\/allowedfiletypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes","abstract":[{"text":"Protocol for defining the allowed file types for attachments.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AllowedFileTypes","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AllowedFileTypes"}],"type":"topic","title":"AllowedFileTypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowedFileTypes","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"allowedFileTypes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIAllowedFileTypes","text":"id<SMIAllowedFileTypes>"},{"kind":"text","text":" "},{"text":"allowedFileTypes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/title","value":"SMIAttachmentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/fragments","value":[{"text":"SMIAttachmentConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1allowedFileTypes\/title","value":"allowedFileTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1allowedFileTypes\/fragments","value":[{"text":"allowedFileTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/title","value":"SMIAllowedFileTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/fragments","value":[{"kind":"identifier","text":"SMIAllowedFileTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAllowedFileTypes"}]}]}]}