{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/endusertoagent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/endusertoagent"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/endUserToAgent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endUserToAgent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Determines whether end users can send attachments to agents."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration"]]},"metadata":{"symbolKind":"property","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endUserToAgent"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endUserToAgent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:objc(pl)SMIAttachmentConfiguration(py)endUserToAgent","title":"endUserToAgent","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/endUserToAgent":{"required":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/attachmentconfiguration\/endusertoagent","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/endUserToAgent","type":"topic","role":"symbol","abstract":[{"text":"Determines whether end users can send attachments to agents.","type":"text"}],"title":"endUserToAgent","navigatorTitle":[{"kind":"identifier","text":"endUserToAgent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endUserToAgent","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentConfiguration"}],"title":"AttachmentConfiguration","url":"\/documentation\/smiclientcore\/attachmentconfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttachmentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"endUserToAgent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"endUserToAgent","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"endUserToAgent"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1endUserToAgent\/title","value":"endUserToAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1endUserToAgent\/fragments","value":[{"kind":"identifier","text":"endUserToAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/title","value":"SMIAttachmentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/fragments","value":[{"text":"SMIAttachmentConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}