{"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIAttachmentConfiguration(py)maxFileSize","modules":[{"name":"SMIClientCore"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"maxFileSize"}],"title":"maxFileSize"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration"]]},"abstract":[{"type":"text","text":"The maximum file size (in bytes) allowed for attachments."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFileSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/maxFileSize","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/maxfilesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration\/maxfilesize"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/maxFileSize":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/maxFileSize","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxFileSize"}],"required":true,"title":"maxFileSize","url":"\/documentation\/smiclientcore\/attachmentconfiguration\/maxfilesize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxFileSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","abstract":[{"type":"text","text":"The maximum file size (in bytes) allowed for attachments."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentConfiguration"}],"title":"AttachmentConfiguration","url":"\/documentation\/smiclientcore\/attachmentconfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttachmentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"maxFileSize","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"maxFileSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFileSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"maxFileSize","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1maxFileSize\/title"},{"value":[{"text":"maxFileSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1maxFileSize\/fragments"},{"value":"SMIAttachmentConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/fragments"},{"value":[{"text":"SMIAttachmentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}