{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/Equatable-Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/!=(_:_:)"],"title":"Operators"}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"SMIClientCore"}],"role":"collectionGroup"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"url":"\/documentation\/smiclientcore\/streamingtokentypes\/!=(_:_:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIStreamingTokenTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle"}]}]}