{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/init(rawValue:)"},"variants":[{"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"metadata":{"title":"init(rawValue:)","roleHeading":"Initializer","externalID":"s:So22SMIStreamingTokenTypesa8rawValueABSS_tcfc","role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenTypes"}],"navigatorTitle":[{"kind":"identifier","text":"StreamingTokenTypes"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"title":"StreamingTokenTypes","url":"\/documentation\/smiclientcore\/streamingtokentypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/init(rawValue:)":{"abstract":[],"url":"\/documentation\/smiclientcore\/streamingtokentypes\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIStreamingTokenTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title","op":"replace"},{"value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments","op":"replace"},{"value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle","op":"replace"}]}]}