{"sections":[],"abstract":[{"type":"text","text":"Indicates the action of streaming a partial message content."}],"metadata":{"role":"symbol","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"title":"message","extendedModule":"SMIClientCore","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"SMIStreamingTokenTypesMessage"}],"externalID":"c:@SMIStreamingTokenTypesMessage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"StreamingTokenTypes"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/message"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/message"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/message"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","text":"StreamingTokenTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","title":"StreamingTokenTypes","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/message":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/streamingtokentypes\/message","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/message","title":"message","abstract":[{"text":"Indicates the action of streaming a partial message content.","type":"text"}],"navigatorTitle":[{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIStreamingTokenTypesMessage","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIStreamingTokenTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle","op":"replace"},{"value":"SMIStreamingTokenTypesMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1message\/title","op":"replace"},{"value":[{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1message\/fragments","op":"replace"}]}]}