{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/validation","interfaceLanguage":"swift"},"abstract":[{"text":"Indicates the action of validating a batch of streamed tokens.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/validation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtokentypes\/validation"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"validation","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","text":"StreamingTokenTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIStreamingTokenTypesValidation"}],"modules":[{"name":"SMIClientCore"}],"title":"validation","roleHeading":"Type Property","symbolKind":"property","externalID":"c:@SMIStreamingTokenTypesValidation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"StreamingTokenTypes"}],"extendedModule":"SMIClientCore","role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/validation":{"abstract":[{"text":"Indicates the action of validating a batch of streamed tokens.","type":"text"}],"navigatorTitle":[{"text":"SMIStreamingTokenTypesValidation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/validation","title":"validation","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"StreamingTokenTypes","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/streamingtokentypes\/validation"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIStreamingTokenTypesValidation","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIStreamingTokenTypesValidation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingTokenTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingTokenTypesValidation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIStreamingTokenTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title"},{"value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle"},{"value":"SMIStreamingTokenTypesValidation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1validation\/title"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypesValidation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1validation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}