{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/configuration\/clientname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/configuration\/clientname"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/clientName","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"clientName"}],"externalID":"c:objc(cs)SMICoreConfiguration(py)clientName","symbolKind":"property","title":"clientName","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientName"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","kind":"typeIdentifier","text":"ClientName"},{"kind":"text","text":"!"}],"role":"symbol"},"abstract":[{"type":"text","text":"The client name sent during authentication to identify the SDK integration."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","text":"ClientName","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileInAppSDK"},{"type":"text","text":"."}]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","isActive":true}]}],"name":"See Also"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/mobileInAppSDK":{"type":"topic","url":"\/documentation\/smiclientcore\/clientname\/mobileinappsdk","title":"mobileInAppSDK","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileInAppSDK","navigatorTitle":[{"kind":"identifier","text":"SMIClientNameMobileInAppSDK"}],"abstract":[{"type":"text","text":"Mobile client for In-App SDK integrations."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileInAppSDK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","text":"ClientName"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","title":"ClientName","navigatorTitle":[{"text":"ClientName","kind":"identifier"}],"abstract":[{"text":"A type that defines the client name sent during authentication to identify the SDK integration type.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/clientname","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientName","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/clientName":{"title":"clientName","abstract":[{"type":"text","text":"The client name sent during authentication to identify the SDK integration."}],"url":"\/documentation\/smiclientcore\/configuration\/clientname","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/clientName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ClientName","kind":"typeIdentifier","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"clientName","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clientName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","kind":"typeIdentifier","text":"SMIClientName","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientName"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileInAppSDK\/title","value":"SMIClientNameMobileInAppSDK","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileInAppSDK\/fragments","value":[{"kind":"identifier","text":"SMIClientNameMobileInAppSDK"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/title","value":"SMIClientName","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/fragments","value":[{"text":"SMIClientName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/navigatorTitle","value":[{"kind":"identifier","text":"SMIClientName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1clientName\/title","value":"clientName","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1clientName\/fragments","value":[{"text":"clientName","kind":"identifier"}],"op":"replace"}]}]}