{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"SMIClientCore"}],"role":"symbol","externalID":"c:objc(cs)SMICoreConfiguration(im)initWithURL:userVerificationRequired:","symbolKind":"init","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userVerificationRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithURL:userVerificationRequired:","kind":"identifier"}],"title":"init(url:userVerificationRequired:)"},"abstract":[{"text":"Creates a configuration object that can be used to instantiate an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":" object using ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userVerificationRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL to the JSON config file.","type":"text"}]}],"name":"url"},{"name":"userVerificationRequired","content":[{"type":"paragraph","inlineContent":[{"text":"Whether or not authorization connections are intended to be configured for User Verification.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:userVerificationRequired:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/configuration\/init(url:userverificationrequired:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/configuration\/init(url:userverificationrequired:)"]}],"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","title":"CoreClient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreClient"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(url:userVerificationRequired:)":{"type":"topic","abstract":[{"text":"Creates a configuration object that can be used to instantiate an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"},{"text":" object using ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:userVerificationRequired:)","title":"init(url:userVerificationRequired:)","navigatorTitle":[{"kind":"identifier","text":"initWithURL:userVerificationRequired:"}],"url":"\/documentation\/smiclientcore\/configuration\/init(url:userverificationrequired:)","role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userVerificationRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","kind":"symbol","title":"Configuration","url":"\/documentation\/smiclientcore\/configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"This class stores configuration information that is necessary when creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true},{"text":" instance using the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" class.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"}],"kind":"symbol","title":"CoreFactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithURL:userVerificationRequired:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithURL:userVerificationRequired:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userVerificationRequired:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"userVerificationRequired","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL to the JSON config file."}]}],"name":"url"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not authorization connections are intended to be configured for User Verification."}]}],"name":"userVerificationRequired"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:userVerificationRequired:)\/title","value":"initWithURL:userVerificationRequired:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:userVerificationRequired:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURL:userVerificationRequired:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"text":"SMICoreFactory","kind":"identifier"}]}]}]}