{"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)SMICoreConfiguration(py)organizationId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"organizationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","navigatorTitle":[{"text":"organizationId","kind":"identifier"}],"title":"organizationId"},"abstract":[{"type":"text","text":"The 15 character Salesforce org ID."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"organizationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/organizationId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/configuration\/organizationid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/configuration\/organizationid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/organizationId":{"navigatorTitle":[{"text":"organizationId","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/organizationId","url":"\/documentation\/smiclientcore\/configuration\/organizationid","type":"topic","title":"organizationId","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"organizationId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The 15 character Salesforce org ID."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"type":"text","text":" instance using the "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"type":"text","text":" class."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"organizationId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"organizationId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"organizationId"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"organizationId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1organizationId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"organizationId"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1organizationId\/fragments"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"op":"replace","value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title"},{"op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"op":"replace","value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"}]}]}