{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin\/init(rawValue:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantorigin\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:19SMIMultimediaCommon27MultimediaParticipantOriginO8rawValueACSgSi_tcfc","roleHeading":"Initializer","title":"init(rawValue:)","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantOrigin/init(rawValue:)":{"role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediaparticipantorigin\/init(rawvalue:)","abstract":[]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantOrigin":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","title":"MultimediaParticipantOrigin","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantorigin","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"abstract":[{"text":"An enum that identifies the origin of a participant in a multimedia session.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"SMIVoiceParticipantOrigin","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/title","op":"replace"},{"value":[{"text":"SMIVoiceParticipantOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/fragments","op":"replace"},{"value":[{"text":"SMIVoiceParticipantOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}