{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin\/local"},"metadata":{"navigatorTitle":[{"text":"SMIVoiceParticipantOriginLocal","kind":"identifier"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"local","kind":"identifier"}],"title":"MultimediaParticipantOrigin.local","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@E@SMIVoiceParticipantOrigin@SMIVoiceParticipantOriginLocal"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantorigin\/local"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantorigin\/local"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"local","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The local participant on this device."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantOrigin/local":{"navigatorTitle":[{"text":"SMIVoiceParticipantOriginLocal","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaparticipantorigin\/local","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin\/local","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"local","kind":"identifier"}],"title":"MultimediaParticipantOrigin.local","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The local participant on this device."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantOrigin":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","title":"MultimediaParticipantOrigin","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantorigin","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"abstract":[{"text":"An enum that identifies the origin of a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIVoiceParticipantOriginLocal","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIVoiceParticipantOriginLocal","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIVoiceParticipantOriginLocal"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIVoiceParticipantOriginLocal","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin~1local\/title"},{"op":"replace","value":[{"text":"SMIVoiceParticipantOriginLocal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin~1local\/fragments"},{"op":"replace","value":"SMIVoiceParticipantOrigin","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/title"},{"op":"replace","value":[{"text":"SMIVoiceParticipantOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/fragments"},{"op":"replace","value":[{"text":"SMIVoiceParticipantOrigin","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/navigatorTitle"}]}]}