{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext"},"abstract":[{"text":"This class serves as the base implementation for all session context types.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/abstractsessioncontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/abstractsessioncontext"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContext","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractSessionContext","kind":"identifier"}],"externalID":"c:objc(cs)SMIAbstractSessionContext","role":"symbol","title":"AbstractSessionContext","roleHeading":"Class","modules":[{"name":"SMIClientCore"}],"symbolKind":"class"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Serializable":{"kind":"symbol","url":"\/documentation\/smiclientcore\/serializable","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"title":"Serializable","abstract":[{"type":"text","text":"Base class for JSON serializable objects used with network communication for In-App Messaging."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","navigatorTitle":[{"text":"Serializable","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"title":"AbstractSessionContextProtocol"},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContext":{"title":"AbstractSessionContext","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This class serves as the base implementation for all session context types."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContext","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractSessionContext","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","url":"\/documentation\/smiclientcore\/abstractsessioncontext"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet":{"navigatorTitle":[{"text":"SessionContextSet","kind":"identifier"}],"type":"topic","abstract":[{"text":"Concrete implementation of SMISessionContextSet protocol.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSet","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet","url":"\/documentation\/smiclientcore\/sessioncontextset","title":"SessionContextSet"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIAbstractSessionContext","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"],"kind":"relationships","type":"inheritsFrom"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"kind":"relationships","type":"inheritedBy"},{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"],"kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAbstractSessionContext","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SMISerializable","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","preciseIdentifier":"c:objc(cs)SMISerializable"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/title","value":"SMISerializable"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/fragments","value":[{"kind":"identifier","text":"SMISerializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/navigatorTitle","value":[{"kind":"identifier","text":"SMISerializable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title","value":"SMIAbstractSessionContext"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/title","value":"SMIAbstractSessionContext"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/fragments","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/title","value":"SMISessionContextSet"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/fragments","value":[{"kind":"identifier","text":"SMISessionContextSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/navigatorTitle","value":[{"text":"SMISessionContextSet","kind":"identifier"}]}]}]}