{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/abstractchoice"]},{"paths":["\/documentation\/smiclientcore\/abstractchoice"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"externalID":"c:objc(pl)SMIAbstractChoice","symbolKind":"protocol","title":"AbstractChoice","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AbstractChoice","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption"]}],"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/optionId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/parentEntryId"],"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"abstract":[{"type":"text","text":"A response type that represents a specific choice for text based choice messages."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Choice","kind":"identifier"}],"title":"Choice","url":"\/documentation\/smiclientcore\/choice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Choice"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/OptionExperienceType":{"url":"\/documentation\/smiclientcore\/optionexperiencetype","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OptionExperienceType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionExperienceType"}],"type":"topic","title":"OptionExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenuOption":{"type":"topic","url":"\/documentation\/smiclientcore\/participantclientmenuoption","title":"ParticipantClientMenuOption","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","navigatorTitle":[{"text":"ParticipantClientMenuOption","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual menu option available to a participant."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice/parentEntryId":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentEntryId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The ID of the parent entry for this choice."}],"navigatorTitle":[{"text":"parentEntryId","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractchoice\/parententryid","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/parentEntryId","title":"parentEntryId"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice/optionId":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The ID of this option."}],"navigatorTitle":[{"text":"optionId","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractchoice\/optionid","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/optionId","title":"optionId"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice":{"url":"\/documentation\/smiclientcore\/abstractchoice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"}],"type":"topic","title":"AbstractChoice"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIAbstractChoice","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIAbstractChoice"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIAbstractChoice","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/optionId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice\/parentEntryId"],"title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAbstractChoice","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title","value":"SMIChoice","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments","value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle","value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/title","value":"SMIOptionExperienceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/fragments","value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIOptionExperienceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/title","value":"SMIParticipantClientMenuOption","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/fragments","value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/navigatorTitle","value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice~1parentEntryId\/title","value":"parentEntryId","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice~1parentEntryId\/fragments","value":[{"text":"parentEntryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice~1optionId\/title","value":"optionId","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice~1optionId\/fragments","value":[{"text":"optionId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/title","value":"SMIAbstractChoice","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/fragments","value":[{"kind":"identifier","text":"SMIAbstractChoice"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractChoice"}],"op":"replace"}]}]}