{"sections":[],"abstract":[{"text":"Protocol that defines the base type for all session contexts.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/abstractsessioncontextprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/abstractsessioncontextprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(pl)SMIAbstractSessionContext","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"title":"AbstractSessionContextProtocol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"],"title":"Related Documentation","anchor":"Related-Documentation"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"title":"AbstractSessionContextProtocol","abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContext","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractsessioncontext","kind":"symbol","type":"topic","abstract":[{"text":"This class serves as the base implementation for all session context types.","type":"text"}],"title":"AbstractSessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","role":"symbol","navigatorTitle":[{"text":"AbstractSessionContext","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet":{"type":"topic","url":"\/documentation\/smiclientcore\/sessioncontextset","title":"SessionContextSet","kind":"symbol","navigatorTitle":[{"text":"SessionContextSet","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSet","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet","role":"symbol","abstract":[{"type":"text","text":"Concrete implementation of SMISessionContextSet protocol."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","kind":"symbol","abstract":[{"type":"text","text":"Represents a session context item with a name and value."}],"role":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol","title":"SessionContextSetProtocol","navigatorTitle":[{"text":"SessionContextSetProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSetProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIAbstractSessionContext","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"],"type":"inheritedBy"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext"],"type":"conformingTypes"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"],"title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAbstractSessionContext"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIAbstractSessionContext","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle"},{"op":"replace","value":"SMIAbstractSessionContext","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/title"},{"op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/navigatorTitle"},{"op":"replace","value":"SMISessionContextSet","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISessionContextSet"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/navigatorTitle","op":"replace","value":[{"text":"SMISessionContextSet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/title","op":"replace","value":"SMISessionContextSet"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/fragments","op":"replace","value":[{"text":"SMISessionContextSet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMISessionContextSet","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}