{"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"],"anchor":"Related-Documentation"}],"relationshipsSections":[{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"],"kind":"relationships","type":"inheritedBy"},{"title":"Conforming Types","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"],"kind":"relationships","type":"conformingTypes"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/abstractvalueprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/abstractvalueprotocol"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Protocol that defines the base type for session context values."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractValueProtocol"}],"externalID":"c:objc(pl)SMIAbstractValue","title":"AbstractValueProtocol","modules":[{"name":"SMIClientCore"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"abstract":[{"text":"Protocol that defines the base type for session context values.","type":"text"}],"navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","title":"AbstractValueProtocol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AbstractValueProtocol"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/abstractvalueprotocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FormSingleInputValue","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a form input value containing a single response value.","type":"text"}],"title":"FormSingleInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectedOptionsInputValue":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a form input value containing multiple selected options."}],"navigatorTitle":[{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formselectedoptionsinputvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue","title":"FormSelectedOptionsInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","role":"symbol","url":"\/documentation\/smiclientcore\/namedvalueprotocol","abstract":[{"type":"text","text":"Represents a named value variable item with a name and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValueProtocol","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NamedValueProtocol"}],"title":"NamedValueProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol":{"type":"topic","url":"\/documentation\/smiclientcore\/structuredvalueprotocol","title":"StructuredValueProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A structured value that contains a dictionary of key-value pairs."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValue":{"title":"AbstractValue","abstract":[{"type":"text","text":"Concrete implementation of SMIAbstractValue protocol."}],"url":"\/documentation\/smiclientcore\/abstractvalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AbstractValue","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue":{"type":"topic","url":"\/documentation\/smiclientcore\/structuredvalue","title":"StructuredValue","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue","navigatorTitle":[{"text":"StructuredValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StructuredValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue":{"url":"\/documentation\/smiclientcore\/smiforminputvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","abstract":[{"text":"A protocol that defines a form input value with its associated metadata.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMIFormInputValue","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormInputValue","kind":"identifier"}],"type":"topic","title":"SMIFormInputValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIAbstractValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAbstractValue"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAbstractValue"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","op":"replace","value":"SMIAbstractValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","op":"replace","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/title","op":"replace","value":"SMIFormSingleInputValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormSingleInputValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormSingleInputValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/title","op":"replace","value":"SMIFormSelectedOptionsInputValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/fragments","op":"replace","value":[{"text":"SMIFormSelectedOptionsInputValue","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/navigatorTitle"},{"op":"replace","value":"SMINamedValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title"},{"op":"replace","value":[{"text":"SMINamedValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMINamedValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle"},{"op":"replace","value":"SMIStructuredValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/navigatorTitle"},{"op":"replace","value":"SMIAbstractValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/title"},{"op":"replace","value":[{"text":"SMIAbstractValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAbstractValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/navigatorTitle"},{"op":"replace","value":"SMIStructuredValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/title"},{"op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/fragments"},{"op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/navigatorTitle"},{"op":"replace","value":"SMIFormInputValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/title"},{"op":"replace","value":[{"text":"SMIFormInputValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/fragments"},{"op":"replace","value":[{"text":"SMIFormInputValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/navigatorTitle"}]}]}