{"metadata":{"symbolKind":"protocol","title":"AgentAvailabilityInfo","role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIAgentAvailabilityInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"AgentAvailabilityInfo","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/agentavailabilityinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/agentavailabilityinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo\/isAgentAvailable"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"This protocol provides information about the current availability status of an agent."},{"type":"text","text":" "},{"type":"text","text":"It exposes a property indicating whether an agent is available for user interaction."},{"type":"text","text":" "},{"type":"text","text":"Implementations may use this to determine if users can connect to a live agent."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A protocol that defines the agent availability configuration for a deployment.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"identifier"}],"navigatorTitle":[{"text":"AgentAvailabilityInfo","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A protocol that defines the agent availability configuration for a deployment.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/agentavailabilityinfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","title":"AgentAvailabilityInfo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo/isAgentAvailable":{"required":true,"url":"\/documentation\/smiclientcore\/agentavailabilityinfo\/isagentavailable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo\/isAgentAvailable","title":"isAgentAvailable","abstract":[{"type":"text","text":"Indicates whether the agent is availability."},{"type":"text","text":" "},{"type":"text","text":"When "},{"type":"codeVoice","code":"true"},{"type":"text","text":", an agents is considered to be available."}],"navigatorTitle":[{"text":"agentAvailable","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAgentAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIAgentAvailabilityInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAgentAvailabilityInfo"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo\/isAgentAvailable"],"generated":true,"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAgentAvailabilityInfo"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/title","op":"replace","value":"SMIAgentAvailabilityInfo"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/fragments","op":"replace","value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/navigatorTitle","op":"replace","value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo~1isAgentAvailable\/title","op":"replace","value":"agentAvailable"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo~1isAgentAvailable\/fragments","op":"replace","value":[{"kind":"identifier","text":"agentAvailable"}]}]}]}