{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/agentavailabilityinfocompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/agentavailabilityinfocompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:SMIAgentAvailabilityInfo.h@T@SMIAgentAvailabilityInfoCompletion","role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"AgentAvailabilityInfoCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentAvailabilityInfoCompletion"}],"navigatorTitle":[{"kind":"identifier","text":"AgentAvailabilityInfoCompletion"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentAvailabilityInfoCompletion"},{"kind":"text","text":" = ((any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","text":"AgentAvailabilityInfo","preciseIdentifier":"c:objc(pl)SMIAgentAvailabilityInfo"},{"kind":"text","text":")?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The agent availability information for the deployment, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if unavailable or the request failed."}],"type":"paragraph"}],"name":"agentAvailabilityInfo"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error describing why the request failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the request was successful or the result is simply empty."}]}],"name":"error"}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An empty result (no agent availability info) is "},{"type":"strong","inlineContent":[{"type":"text","text":"NOT"}]},{"type":"text","text":" considered an error."}]}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"abstract":[{"text":"A completion handler used to deliver the result of an agent availability request.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfoCompletion","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo":{"navigatorTitle":[{"text":"AgentAvailabilityInfo","kind":"identifier"}],"title":"AgentAvailabilityInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the agent availability configuration for a deployment."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","url":"\/documentation\/smiclientcore\/agentavailabilityinfo","kind":"symbol","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfoCompletion":{"abstract":[{"text":"A completion handler used to deliver the result of an agent availability request.","type":"text"}],"url":"\/documentation\/smiclientcore\/agentavailabilityinfocompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfoCompletion","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AgentAvailabilityInfoCompletion","kind":"identifier"}],"title":"AgentAvailabilityInfoCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfoCompletion","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIAgentAvailabilityInfoCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIAgentAvailabilityInfoCompletion","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIAgentAvailabilityInfoCompletion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(id<SMIAgentAvailabilityInfo>, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMIAgentAvailabilityInfo#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SMIAgentAvailabilityInfoCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/title","op":"replace","value":"SMIAgentAvailabilityInfo"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAgentAvailabilityInfo"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/navigatorTitle","op":"replace","value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/title","op":"replace","value":"SMIAgentAvailabilityInfoCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/fragments","op":"replace","value":[{"text":"SMIAgentAvailabilityInfoCompletion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAgentAvailabilityInfoCompletion"}]}]}]}