{"sections":[],"abstract":[{"text":"Protocol for defining the allowed file types for attachments.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AllowedFileTypes","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/allowedfiletypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/allowedfiletypes"]}],"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/audio","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/image","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/other","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/text","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/video"]}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"AllowedFileTypes","kind":"identifier"}],"externalID":"c:objc(pl)SMIAllowedFileTypes","symbolKind":"protocol","title":"AllowedFileTypes","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AllowedFileTypes","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes/image":{"title":"image","required":true,"abstract":[{"type":"text","text":"Array of allowed image file extensions."}],"url":"\/documentation\/smiclientcore\/allowedfiletypes\/image","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/image","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes":{"url":"\/documentation\/smiclientcore\/allowedfiletypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes","abstract":[{"text":"Protocol for defining the allowed file types for attachments.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AllowedFileTypes","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AllowedFileTypes"}],"type":"topic","title":"AllowedFileTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes/other":{"url":"\/documentation\/smiclientcore\/allowedfiletypes\/other","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/other","abstract":[{"type":"text","text":"Array of allowed other file extensions."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"other"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"required":true,"type":"topic","title":"other"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes/text":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Array of allowed text file extensions.","type":"text"}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/allowedfiletypes\/text","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/text","title":"text"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes/video":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"text":"Array of allowed video file extensions.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"video"}],"url":"\/documentation\/smiclientcore\/allowedfiletypes\/video","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/video","title":"video"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AllowedFileTypes/audio":{"url":"\/documentation\/smiclientcore\/allowedfiletypes\/audio","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/audio","abstract":[{"type":"text","text":"Array of allowed audio file extensions."}],"role":"symbol","navigatorTitle":[{"text":"audio","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"required":true,"type":"topic","title":"audio"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIAllowedFileTypes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIAllowedFileTypes","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIAllowedFileTypes","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/audio","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/image","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/other","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/text","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AllowedFileTypes\/video"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAllowedFileTypes","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1image\/title","op":"replace","value":"image"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"image"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/title","op":"replace","value":"SMIAllowedFileTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAllowedFileTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIAllowedFileTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1other\/title","op":"replace","value":"other"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1other\/fragments","op":"replace","value":[{"text":"other","kind":"identifier"}]},{"op":"replace","value":"text","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1text\/title"},{"op":"replace","value":[{"kind":"identifier","text":"text"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1text\/fragments"},{"op":"replace","value":"video","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1video\/title"},{"op":"replace","value":[{"text":"video","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1video\/fragments"},{"op":"replace","value":"audio","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1audio\/title"},{"op":"replace","value":[{"text":"audio","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AllowedFileTypes~1audio\/fragments"}]}]}