{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachments"]}],"sections":[],"metadata":{"title":"Attachments","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SMIAttachments","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Attachments","kind":"identifier"}],"navigatorTitle":[{"text":"Attachments","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A protocol that represents a collection of file attachments in a conversation."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attachments"}]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access a collection of file attachments associated with a conversation"},{"type":"text","text":" "},{"type":"text","text":"entry. Each attachment in the collection can be a different type of file asset, such as"},{"type":"text","text":" "},{"type":"text","text":"images, documents, or other media files."}]}],"kind":"content"}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments\/attachments"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Attachments","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Attachments"}],"title":"Attachments","url":"\/documentation\/smiclientcore\/attachments","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","abstract":[{"type":"text","text":"A protocol that represents a collection of file attachments in a conversation."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentEntry":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentEntry"}],"url":"\/documentation\/smiclientcore\/attachmententry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttachmentEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an attachment entry within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"title":"AttachmentEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"url":"\/documentation\/smiclientcore\/carousel","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"kind":"symbol","title":"Carousel"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"abstract":[{"type":"text","text":"A protocol that represents a file asset in a conversation."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileAsset"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","type":"topic","title":"FileAsset","url":"\/documentation\/smiclientcore\/fileasset","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments/attachments":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments\/attachments","title":"attachments","type":"topic","abstract":[{"type":"text","text":"The array of file attachments in this collection."},{"type":"text","text":" "},{"type":"text","text":"Each attachment in the array conforms to the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","isActive":true,"type":"reference"},{"type":"text","text":" protocol."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFileAsset","text":"FileAsset"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"attachments"}],"url":"\/documentation\/smiclientcore\/attachments\/attachments","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIAttachments","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIAttachments"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIAttachments","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments\/attachments"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAttachments","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIAttachments","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAttachments"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/fragments"},{"op":"replace","value":[{"text":"SMIAttachments","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/navigatorTitle"},{"op":"replace","value":"SMIAttachmentEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAttachmentEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/fragments"},{"op":"replace","value":[{"text":"SMIAttachmentEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/navigatorTitle"},{"op":"replace","value":"SMICarousel","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICarousel"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICarousel"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"op":"replace","value":"SMIFileAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFileAsset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments"},{"op":"replace","value":[{"text":"SMIFileAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle"},{"op":"replace","value":"attachments","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments~1attachments\/title"},{"op":"replace","value":[{"kind":"identifier","text":"attachments"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments~1attachments\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}