{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry"},"variants":[{"paths":["\/documentation\/smiclientcore\/attachmententry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/attachmententry"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentEntry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Attachments","preciseIdentifier":"c:objc(pl)SMIAttachments","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"text":"Use this protocol to access the content of an attachment displayed in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"An attachment entry can include a file asset and optional descriptive text.","type":"text"}],"type":"paragraph"}]}],"metadata":{"title":"AttachmentEntry","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentEntry","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"AttachmentEntry","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIAttachmentEntry","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"abstract":[{"text":"A protocol that represents an attachment entry within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":".","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry\/text"],"generated":true}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments":{"url":"\/documentation\/smiclientcore\/attachments","kind":"symbol","type":"topic","title":"Attachments","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attachments"}],"navigatorTitle":[{"kind":"identifier","text":"Attachments"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","abstract":[{"type":"text","text":"A protocol that represents a collection of file attachments in a conversation."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"abstract":[{"type":"text","text":"Common interface for the content of a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"title":"EntryPayload","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentEntry/text":{"url":"\/documentation\/smiclientcore\/attachmententry\/text","title":"text","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry\/text","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"text"}],"abstract":[{"type":"text","text":"The descriptive text for this attachment entry."}],"kind":"symbol","required":true,"type":"topic"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentEntry":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","navigatorTitle":[{"kind":"identifier","text":"AttachmentEntry"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentEntry"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that represents an attachment entry within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/smiclientcore\/attachmententry","title":"AttachmentEntry","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","type":"topic","kind":"symbol","title":"EntryTypeMessage","role":"symbol","url":"\/documentation\/smiclientcore\/entrytypemessage","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIAttachmentEntry"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAttachmentEntry"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIAttachmentEntry","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry\/text"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAttachmentEntry","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"SMIEntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","text":"SMIEntryTypeMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","text":"SMIAttachments","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachments"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/title","op":"replace","value":"SMIAttachments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAttachments"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAttachments"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace","value":"SMIEntryPayload"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry~1text\/title","op":"replace","value":"text"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry~1text\/fragments","op":"replace","value":[{"text":"text","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/title","op":"replace","value":"SMIAttachmentEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/fragments","op":"replace","value":[{"text":"SMIAttachmentEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAttachmentEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","op":"replace","value":"SMIEntryTypeMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","op":"replace","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]}]}]}