{"sections":[],"abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/attachmentconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentconfiguration"]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/allowedFileTypes","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/endUserToAgent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/maxFileSize"],"generated":true,"title":"Instance Properties"}],"metadata":{"navigatorTitle":[{"text":"AttachmentConfiguration","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentConfiguration","kind":"identifier"}],"externalID":"c:objc(pl)SMIAttachmentConfiguration","modules":[{"name":"SMIClientCore"}],"title":"AttachmentConfiguration"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/endUserToAgent":{"required":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/attachmentconfiguration\/endusertoagent","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/endUserToAgent","type":"topic","role":"symbol","abstract":[{"text":"Determines whether end users can send attachments to agents.","type":"text"}],"title":"endUserToAgent","navigatorTitle":[{"kind":"identifier","text":"endUserToAgent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endUserToAgent","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/maxFileSize":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/maxFileSize","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxFileSize"}],"required":true,"title":"maxFileSize","url":"\/documentation\/smiclientcore\/attachmentconfiguration\/maxfilesize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxFileSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","abstract":[{"type":"text","text":"The maximum file size (in bytes) allowed for attachments."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentConfiguration"}],"title":"AttachmentConfiguration","url":"\/documentation\/smiclientcore\/attachmentconfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttachmentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration/allowedFileTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/allowedFileTypes","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowedFileTypes"}],"required":true,"url":"\/documentation\/smiclientcore\/attachmentconfiguration\/allowedfiletypes","title":"allowedFileTypes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedFileTypes"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"AllowedFileTypes","preciseIdentifier":"c:objc(pl)SMIAllowedFileTypes"},{"kind":"text","text":")?"}],"kind":"symbol","abstract":[{"type":"text","text":"The allowed file types configuration."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SMIAttachmentConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIAttachmentConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/allowedFileTypes","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/endUserToAgent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration\/maxFileSize"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIAttachmentConfiguration"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1endUserToAgent\/title","value":"endUserToAgent"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1endUserToAgent\/fragments","value":[{"text":"endUserToAgent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1maxFileSize\/title","value":"maxFileSize","op":"replace"},{"value":[{"text":"maxFileSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1maxFileSize\/fragments"},{"value":"SMIAttachmentConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/fragments","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1allowedFileTypes\/title","value":"allowedFileTypes"},{"value":[{"text":"allowedFileTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration~1allowedFileTypes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}