{"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CompletedAttachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"variants":[{"paths":["\/documentation\/smiclientcore\/attachmentuploadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/attachmentuploadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult\/resultType"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResult","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Result of an attachment upload operation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"AttachmentUploadResult","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResult","kind":"identifier"}],"externalID":"c:objc(pl)SMIAttachmentUploadResult","title":"AttachmentUploadResult","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"abstract":[{"text":"Result of an attachment upload operation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","title":"AttachmentUploadResult","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResult"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/attachmentuploadresult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorAttachmentUploadResult":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult","role":"symbol","url":"\/documentation\/smiclientcore\/errorattachmentuploadresult","abstract":[{"text":"Represents an error result from an attachment upload attempt.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttachmentUploadResult","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ErrorAttachmentUploadResult","kind":"identifier"}],"title":"ErrorAttachmentUploadResult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PendingAttachmentUploadResult":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult","title":"PendingAttachmentUploadResult","navigatorTitle":[{"text":"PendingAttachmentUploadResult","kind":"identifier"}],"abstract":[{"text":"Represents an attachment upload that is in a pending state.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/pendingattachmentuploadresult","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PendingAttachmentUploadResult","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult/resultType":{"title":"resultType","required":true,"abstract":[{"type":"text","text":"The type\/status of the upload result (Completed, Pending, Error)."}],"url":"\/documentation\/smiclientcore\/attachmentuploadresult\/resulttype","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult\/resultType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resultType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"AttachmentUploadResultType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"resultType","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CompletedAttachmentUploadResult":{"url":"\/documentation\/smiclientcore\/completedattachmentuploadresult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CompletedAttachmentUploadResult","abstract":[{"type":"text","text":"Represents the result of a completed attachment upload operation."}],"role":"symbol","navigatorTitle":[{"text":"CompletedAttachmentUploadResult","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletedAttachmentUploadResult","kind":"identifier"}],"type":"topic","title":"CompletedAttachmentUploadResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIAttachmentUploadResult","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult\/resultType"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CompletedAttachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult"],"type":"inheritedBy","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAttachmentUploadResult","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title"},{"value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments"},{"value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle"},{"value":"SMIErrorAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/title"},{"value":[{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/fragments"},{"value":[{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/navigatorTitle"},{"value":"SMIPendingAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/title"},{"value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPendingAttachmentUploadResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult~1resultType\/title","value":"resultType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult~1resultType\/fragments","value":[{"kind":"identifier","text":"resultType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/title","value":"SMICompletedAttachmentUploadResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/fragments","value":[{"kind":"identifier","text":"SMICompletedAttachmentUploadResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/navigatorTitle","value":[{"text":"SMICompletedAttachmentUploadResult","kind":"identifier"}]}]}]}