{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/attachmentuploadresulttype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"An enum that defines the possible states of an attachment upload operation.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResultType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to track the status of attachment upload operations."}]},{"type":"heading","anchor":"Possible-Values","level":2,"text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/completed"},{"type":"text","text":" - Upload completed successfully"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/pending","isActive":true,"type":"reference"},{"type":"text","text":" - Upload is still pending\/in progress"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/error"},{"type":"text","text":" - Upload failed with an error"}]}]}]}],"kind":"content"}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/init(rawValue:)"]},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/completed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/error","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/pending"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/Equatable-Implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"externalID":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","symbolKind":"struct","modules":[{"name":"SMIClientCore"}],"roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResultType","kind":"identifier"}],"navigatorTitle":[{"text":"AttachmentUploadResultType","kind":"identifier"}],"role":"symbol","title":"AttachmentUploadResultType"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/completed":{"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/completed","title":"completed","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/completed","abstract":[{"text":"Upload completed successfully.","type":"text"},{"text":" ","type":"text"},{"text":"Used when the attachment has been successfully uploaded to the server.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeCompleted"}]},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/init(rawValue:)","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/pending":{"abstract":[{"text":"Upload is still pending\/in progress.","type":"text"},{"text":" ","type":"text"},{"text":"Used when the attachment upload is currently being processed.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/pending","navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypePending"}],"url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/pending","title":"pending","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/error":{"navigatorTitle":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeError"}],"role":"symbol","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/error","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/error","title":"error","type":"topic","abstract":[{"text":"Upload failed with an error.","type":"text"},{"text":" ","type":"text"},{"text":"Used when the attachment upload encountered an error and failed.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType":{"role":"symbol","title":"AttachmentUploadResultType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResultType"}],"url":"\/documentation\/smiclientcore\/attachmentuploadresulttype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResultType"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of an attachment upload operation."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/smiclientcore\/attachmentuploadresulttype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType\/Equatable-Implementations","kind":"article","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIAttachmentUploadResultType","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResultType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIAttachmentUploadResultType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIAttachmentUploadResultTypeCompleted","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1completed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeCompleted"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1completed\/fragments","op":"replace"},{"value":"SMIAttachmentUploadResultTypePending","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1pending\/title","op":"replace"},{"value":[{"text":"SMIAttachmentUploadResultTypePending","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1pending\/fragments","op":"replace"},{"value":"SMIAttachmentUploadResultTypeError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1error\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResultTypeError"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType~1error\/fragments","op":"replace"},{"value":"SMIAttachmentUploadResultType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/title","op":"replace"},{"value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAttachmentUploadResultType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}