{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/smiclientcore\/authorizationtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/authorizationtypes"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/JWT","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/invalid","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/passthrough","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/unauthenticated"],"generated":true,"title":"Enumeration Cases"},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"Use this enum to specify the type of authorization required for API requests.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The authorization type determines how requests are authenticated and what"},{"type":"text","text":" "},{"type":"text","text":"credentials are needed."}],"type":"paragraph"}]}],"abstract":[{"text":"An enum that defines the types of authorization for API requests.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthorizationTypes"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"externalID":"c:@E@SMIAuthorizationTypes","title":"AuthorizationTypes","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/smiclientcore\/authorizationtypes\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/passthrough":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/passthrough","abstract":[{"type":"text","text":"Allows for passthrough of MIAW issued jwts directly into the SDK authorization flow."},{"type":"text","text":" "},{"type":"text","text":"This can be used to handle authorization with the MIAW separately within your application or authentication processes."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIAuthorizationTypesPassthrough"}],"title":"AuthorizationTypes.passthrough","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"passthrough"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/authorizationtypes\/passthrough"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/JWT":{"title":"AuthorizationTypes.JWT","abstract":[{"text":"JWT-based user verification.","type":"text"}],"url":"\/documentation\/smiclientcore\/authorizationtypes\/jwt","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/JWT","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWT","kind":"identifier"}],"navigatorTitle":[{"text":"SMIAuthorizationTypesJWT","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/invalid":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/invalid","abstract":[{"type":"text","text":"Invalid authorization type."}],"role":"symbol","navigatorTitle":[{"text":"SMIAuthorizationTypesInvalid","kind":"identifier"}],"title":"AuthorizationTypes.invalid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/authorizationtypes\/invalid"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/smiclientcore\/authorizationtypes\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/unauthenticated":{"url":"\/documentation\/smiclientcore\/authorizationtypes\/unauthenticated","abstract":[{"text":"Unauthenticated.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/unauthenticated","role":"symbol","navigatorTitle":[{"text":"SMIAuthorizationTypesUnauthenticated","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unauthenticated","kind":"identifier"}],"type":"topic","title":"AuthorizationTypes.unauthenticated"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the types of authorization for API requests.","type":"text"}],"navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/authorizationtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","title":"AuthorizationTypes"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","kind":"article","url":"\/documentation\/smiclientcore\/authorizationtypes\/rawrepresentable-implementations"},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SMIAuthorizationTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIAuthorizationTypes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAuthorizationTypes"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/JWT","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/invalid","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/passthrough","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes\/unauthenticated"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAuthorizationTypes","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1passthrough\/title","value":"SMIAuthorizationTypesPassthrough"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1passthrough\/fragments","value":[{"kind":"identifier","text":"SMIAuthorizationTypesPassthrough"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1JWT\/title","value":"SMIAuthorizationTypesJWT"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1JWT\/fragments","value":[{"text":"SMIAuthorizationTypesJWT","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1invalid\/title","value":"SMIAuthorizationTypesInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1invalid\/fragments","value":[{"kind":"identifier","text":"SMIAuthorizationTypesInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1unauthenticated\/title","value":"SMIAuthorizationTypesUnauthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes~1unauthenticated\/fragments","value":[{"text":"SMIAuthorizationTypesUnauthenticated","kind":"identifier"}]},{"value":"SMIAuthorizationTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title"},{"value":[{"kind":"identifier","text":"SMIAuthorizationTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments"},{"value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle"}]}]}