{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/endTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/startTime"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"abstract":[{"type":"text","text":"A protocol that defines a time interval for business hours."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"This protocol represents a single time interval that defines when a deployment is open for business."},{"type":"text","text":" "},{"type":"text","text":"It is used as part of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","isActive":true},{"type":"text","text":" configuration to specify multiple time intervals"},{"type":"text","text":" "},{"type":"text","text":"across different days or times. Each interval has a start and end time that defines when the"},{"type":"text","text":" "},{"type":"text","text":"deployment is considered open."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/businesshours"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshours"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMIBusinessHours","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"BusinessHours","kind":"identifier"}],"title":"BusinessHours","role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","navigatorTitle":[{"text":"BusinessHours","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshours","kind":"symbol","type":"topic","title":"BusinessHours","abstract":[{"text":"A protocol that defines a time interval for business hours.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours/startTime":{"url":"\/documentation\/smiclientcore\/businesshours\/starttime","title":"startTime","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/startTime","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"startTime","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The start time of the business hours interval."},{"type":"text","text":" "},{"type":"text","text":"This time represents when the deployment is considered open to customers."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","navigatorTitle":[{"text":"BusinessHoursInfo","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHoursInfo","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo","kind":"symbol","type":"topic","title":"BusinessHoursInfo","abstract":[{"text":"A protocol that defines the business hours configuration for a deployment.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours/endTime":{"url":"\/documentation\/smiclientcore\/businesshours\/endtime","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"kind":"symbol","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"}],"role":"symbol","abstract":[{"type":"text","text":"The end time of the business hours interval."},{"type":"text","text":" "},{"type":"text","text":"This time represents when the deployment is considered closed to customers."}],"title":"endTime","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/endTime"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIBusinessHours","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIBusinessHours","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIBusinessHours","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/endTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours\/startTime"],"anchor":"Instance-Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIBusinessHours"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIBusinessHours","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIBusinessHours"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/fragments"},{"value":[{"kind":"identifier","text":"SMIBusinessHours"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/navigatorTitle"},{"value":"startTime","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1startTime\/title"},{"value":[{"text":"startTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1startTime\/fragments"},{"value":"SMIBusinessHoursInfo","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title"},{"value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments"},{"value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle"},{"value":"endTime","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1endTime\/title"},{"value":[{"text":"endTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours~1endTime\/fragments"}]}]}