{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfoCompletion"},{"kind":"text","text":" = ((any "},{"preciseIdentifier":"c:objc(pl)SMIBusinessHoursInfo","kind":"typeIdentifier","text":"BusinessHoursInfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"},{"kind":"text","text":")?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"content":[{"inlineContent":[{"text":"An empty result is ","type":"text"},{"inlineContent":[{"type":"text","text":"NOT"}],"type":"strong"},{"text":" considered an error.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"Note"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfoCompletion","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/businesshoursinfocompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/businesshoursinfocompletion"]}],"abstract":[{"type":"text","text":"A completion handler for retrieving business hours information."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"businessHoursInfo","type":"codeVoice"},{"type":"text","text":" parameter contains the business hours configuration for the deployment,"},{"type":"text","text":" "},{"type":"text","text":"or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the request failed. The "},{"code":"error","type":"codeVoice"},{"type":"text","text":" parameter contains an error object that describes"},{"type":"text","text":" "},{"type":"text","text":"why the request failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the request was successful."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"BusinessHoursInfoCompletion"}],"title":"BusinessHoursInfoCompletion","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfoCompletion"}],"externalID":"c:SMIBusinessHoursInfo.h@T@SMIBusinessHoursInfoCompletion","role":"symbol","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"navigatorTitle":[{"kind":"identifier","text":"BusinessHoursInfo"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/businesshoursinfo","title":"BusinessHoursInfo","abstract":[{"type":"text","text":"A protocol that defines the business hours configuration for a deployment."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfo"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfoCompletion":{"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfoCompletion"}],"title":"BusinessHoursInfoCompletion","abstract":[{"type":"text","text":"A completion handler for retrieving business hours information."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"businessHoursInfo"},{"type":"text","text":" parameter contains the business hours configuration for the deployment,"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the request failed. The "},{"type":"codeVoice","code":"error"},{"type":"text","text":" parameter contains an error object that describes"},{"type":"text","text":" "},{"type":"text","text":"why the request failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the request was successful."}],"url":"\/documentation\/smiclientcore\/businesshoursinfocompletion","navigatorTitle":[{"kind":"identifier","text":"BusinessHoursInfoCompletion"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfoCompletion","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIBusinessHoursInfoCompletion","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIBusinessHoursInfoCompletion"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIBusinessHoursInfoCompletion","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMIBusinessHoursInfo#*$objc(cs)NSError)","text":"void (^)(id<SMIBusinessHoursInfo>, NSError *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIBusinessHoursInfoCompletion"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title","op":"replace","value":"SMIBusinessHoursInfo"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments","op":"replace","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIBusinessHoursInfo"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfoCompletion\/title","op":"replace","value":"SMIBusinessHoursInfoCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfoCompletion\/fragments","op":"replace","value":[{"text":"SMIBusinessHoursInfoCompletion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfoCompletion\/navigatorTitle","op":"replace","value":[{"text":"SMIBusinessHoursInfoCompletion","kind":"identifier"}]}]}]}