{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol","title":"BusinessHoursInfo","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BusinessHoursInfo"}],"navigatorTitle":[{"text":"BusinessHoursInfo","kind":"identifier"}],"externalID":"c:objc(pl)SMIBusinessHoursInfo"},"abstract":[{"text":"A protocol that defines the business hours configuration for a deployment.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHoursInfo","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This protocol provides information about when a deployment is considered “open” for business."},{"type":"text","text":" "},{"type":"text","text":"It includes the name of the business hours configuration, whether it’s currently active,"},{"type":"text","text":" "},{"type":"text","text":"and a list of time intervals that define when the deployment is available. This information"},{"type":"text","text":" "},{"type":"text","text":"is used to determine if users can interact with the deployment based on the current time."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/businesshoursinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/businesshoursinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/businessHours","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isActive","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/requestTimestamp"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isWithinBusinessHours(comparisonTime:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/isWithinBusinessHours(comparisonTime:)":{"navigatorTitle":[{"text":"isWithinBusinessHours:","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/businesshoursinfo\/iswithinbusinesshours(comparisontime:)","role":"symbol","abstract":[{"type":"text","text":"Checks if a given time falls within any of the configured business hours intervals."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"comparisonTime"},{"text":" parameter specifies the time to check against the business hours intervals.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current time will be used. Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the time falls within any of the","type":"text"},{"text":" ","type":"text"},{"text":"business hours intervals and the configuration is active, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"required":true,"title":"isWithinBusinessHours(comparisonTime:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isWithinBusinessHours(comparisonTime:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isWithinBusinessHours","kind":"identifier"},{"text":"(","kind":"text"},{"text":"comparisonTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHours":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","navigatorTitle":[{"text":"BusinessHours","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHours","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshours","kind":"symbol","type":"topic","title":"BusinessHours","abstract":[{"text":"A protocol that defines a time interval for business hours.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo","navigatorTitle":[{"text":"BusinessHoursInfo","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BusinessHoursInfo","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo","kind":"symbol","type":"topic","title":"BusinessHoursInfo","abstract":[{"text":"A protocol that defines the business hours configuration for a deployment.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/isActive":{"abstract":[{"type":"text","text":"Indicates whether the business hours configuration is currently active."},{"type":"text","text":" "},{"type":"text","text":"When "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the deployment is considered closed regardless of the time intervals."}],"navigatorTitle":[{"text":"active","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo\/isactive","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isActive","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isActive","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/name":{"type":"topic","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/businesshoursinfo\/name","kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"abstract":[{"text":"The name of the business hours configuration as defined in Setup.","type":"text"}],"title":"name"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/requestTimestamp":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"requestTimestamp","kind":"identifier"}],"title":"requestTimestamp","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"}],"type":"topic","abstract":[{"text":"The timestamp when the business hours information was last retrieved from the server.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to determine if the business hours information needs to be refreshed.","type":"text"}],"url":"\/documentation\/smiclientcore\/businesshoursinfo\/requesttimestamp","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/requestTimestamp"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/BusinessHoursInfo/businessHours":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/businessHours","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"businessHours","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"BusinessHours","preciseIdentifier":"c:objc(pl)SMIBusinessHours","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"required":true,"type":"topic","abstract":[{"text":"A list of time intervals that define when the deployment is open for business.","type":"text"},{"text":" ","type":"text"},{"text":"Each interval is represented by a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHours","type":"reference","isActive":true},{"text":" object containing start and end times.","type":"text"}],"title":"businessHours","url":"\/documentation\/smiclientcore\/businesshoursinfo\/businesshours","navigatorTitle":[{"text":"businessHours","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIBusinessHoursInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIBusinessHoursInfo","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIBusinessHoursInfo"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/businessHours","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isActive","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/requestTimestamp"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/BusinessHoursInfo\/isWithinBusinessHours(comparisonTime:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIBusinessHoursInfo"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isWithinBusinessHours(comparisonTime:)\/title","op":"replace","value":"isWithinBusinessHours:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isWithinBusinessHours(comparisonTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isWithinBusinessHours:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/title","value":"SMIBusinessHours"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/fragments","value":[{"kind":"identifier","text":"SMIBusinessHours"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHours\/navigatorTitle","value":[{"text":"SMIBusinessHours","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/title","value":"SMIBusinessHoursInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/fragments","value":[{"kind":"identifier","text":"SMIBusinessHoursInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SMIBusinessHoursInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isActive\/title","value":"active"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1isActive\/fragments","value":[{"kind":"identifier","text":"active"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1requestTimestamp\/title","value":"requestTimestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1requestTimestamp\/fragments","value":[{"kind":"identifier","text":"requestTimestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1businessHours\/title","value":"businessHours"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1BusinessHoursInfo~1businessHours\/fragments","value":[{"kind":"identifier","text":"businessHours"}]}]}]}