{"abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/carousel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/carousel"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","kind":"typeIdentifier","text":"Attachments","preciseIdentifier":"c:objc(pl)SMIAttachments"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","text":"EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","text":"EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","kind":"typeIdentifier","text":"MessageSelectable","preciseIdentifier":"c:objc(pl)SMIMessageSelectable"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access a carousel of interactive items in a conversation. A carousel"},{"type":"text","text":" "},{"type":"text","text":"presents a collection of items that users can select from, typically displayed in a"},{"type":"text","text":" "},{"type":"text","text":"horizontal scrollable list."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel\/items"],"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","metadata":{"roleHeading":"Protocol","title":"Carousel","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"externalID":"c:objc(pl)SMICarousel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable":{"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/messageselectable","type":"topic","navigatorTitle":[{"text":"MessageSelectable","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a message with selectable choices within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageSelectable","kind":"identifier"}],"title":"MessageSelectable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Attachments":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Attachments"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Attachments"}],"title":"Attachments","abstract":[{"text":"A protocol that represents a collection of file attachments in a conversation.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","url":"\/documentation\/smiclientcore\/attachments"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleLinkItem"}],"navigatorTitle":[{"kind":"identifier","text":"TitleLinkItem"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","title":"TitleLinkItem","abstract":[{"text":"A protocol that represents an interactive item in a carousel with a title and selectable options.","type":"text"}],"url":"\/documentation\/smiclientcore\/titlelinkitem","type":"topic","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel/items":{"required":true,"abstract":[{"text":"The array of items displayed in this carousel.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","type":"reference","isActive":true},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option in the carousel.","type":"text"}],"kind":"symbol","title":"items","navigatorTitle":[{"kind":"identifier","text":"items"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel\/items","url":"\/documentation\/smiclientcore\/carousel\/items","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"TitleLinkItem","preciseIdentifier":"c:objc(pl)SMITitleLinkItem"},{"kind":"text","text":"]?"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"type":"topic","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}],"kind":"symbol","title":"EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Carousel","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Carousel","kind":"identifier"}],"type":"topic","title":"Carousel","url":"\/documentation\/smiclientcore\/carousel","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMICarousel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMICarousel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMICarousel","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel\/items"],"generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICarousel"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SMIMessageSelectable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","preciseIdentifier":"c:objc(pl)SMIMessageSelectable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SMIAttachments","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Attachments","preciseIdentifier":"c:objc(pl)SMIAttachments"},{"kind":"text","text":">"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/title","value":"SMIMessageSelectable"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/fragments","value":[{"kind":"identifier","text":"SMIMessageSelectable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageSelectable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/title","value":"SMIAttachments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/fragments","value":[{"kind":"identifier","text":"SMIAttachments"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Attachments\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachments"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/title","value":"SMITitleLinkItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/fragments","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/navigatorTitle","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel~1items\/title","value":"items"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel~1items\/fragments","value":[{"kind":"identifier","text":"items"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title","value":"SMICarousel"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments","value":[{"kind":"identifier","text":"SMICarousel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle","value":[{"kind":"identifier","text":"SMICarousel"}]}]}]}