{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/smiclientcore\/choicelistdependency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicelistdependency"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A protocol that defines a dependency relationship between two choice lists in pre-chat.","type":"text"}],"sections":[],"metadata":{"title":"ChoiceListDependency","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChoiceListDependency"}],"externalID":"c:objc(pl)SMIChoiceListDependency","role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"ChoiceListDependency"}],"roleHeading":"Protocol"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/childId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/parentId"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListDependency","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol represents a parent-child relationship between two "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true,"type":"reference"},{"type":"text","text":" objects,"},{"type":"text","text":" "},{"type":"text","text":"where the child list’s available options may depend on the selection made in the parent list."},{"type":"text","text":" "},{"type":"text","text":"This is used to create cascading or dependent choice lists in the pre-chat form."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListDependency/parentId":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The identifier of the parent choice list.","type":"text"},{"text":" ","type":"text"},{"text":"This ID references the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true,"type":"reference"},{"text":" that controls the available options in the child list.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/parentId","kind":"symbol","navigatorTitle":[{"text":"parentId","kind":"identifier"}],"title":"parentId","url":"\/documentation\/smiclientcore\/choicelistdependency\/parentid","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListDependency/childId":{"title":"childId","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/childId","type":"topic","kind":"symbol","abstract":[{"text":"The identifier of the child choice list.","type":"text"},{"text":" ","type":"text"},{"text":"This ID references the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true},{"text":" whose available options are determined by the parent list’s selection.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"childId","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choicelistdependency\/childid","role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListDependency":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListDependency","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines a dependency relationship between two choice lists in pre-chat."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","kind":"symbol","navigatorTitle":[{"text":"ChoiceListDependency","kind":"identifier"}],"title":"ChoiceListDependency","url":"\/documentation\/smiclientcore\/choicelistdependency","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol","navigatorTitle":[{"text":"ChoiceList","kind":"identifier"}],"title":"ChoiceList","url":"\/documentation\/smiclientcore\/choicelist","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIChoiceListDependency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIChoiceListDependency"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChoiceListDependency"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/childId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency\/parentId"],"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIChoiceListDependency"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency~1parentId\/title","value":"parentId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency~1parentId\/fragments","value":[{"kind":"identifier","text":"parentId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency~1childId\/title","value":"childId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency~1childId\/fragments","value":[{"kind":"identifier","text":"childId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/title","value":"SMIChoiceListDependency"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/fragments","value":[{"kind":"identifier","text":"SMIChoiceListDependency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/navigatorTitle","value":[{"text":"SMIChoiceListDependency","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","value":"SMIChoiceList"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}