{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/optionValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/title"],"anchor":"Instance-Properties","generated":true}],"metadata":{"title":"Choice","externalID":"c:objc(pl)SMIChoice","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Choice"}],"navigatorTitle":[{"kind":"identifier","text":"Choice"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/choice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choice"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A response type that represents a specific choice for text based choice messages."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Choice","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AbstractChoice","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","preciseIdentifier":"c:objc(pl)SMIAbstractChoice"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"url":"\/documentation\/smiclientcore\/choice","navigatorTitle":[{"kind":"identifier","text":"Choice"}],"title":"Choice","type":"topic","abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Choice"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenuOption":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ParticipantClientMenuOption","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","url":"\/documentation\/smiclientcore\/participantclientmenuoption","abstract":[{"type":"text","text":"A protocol that represents an individual menu option available to a participant."}],"title":"ParticipantClientMenuOption","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice/title":{"title":"title","type":"topic","abstract":[{"type":"text","text":"The display title for this choice."},{"type":"text","text":" "},{"type":"text","text":"This property provides the text that users see when presented with this choice."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/title","role":"symbol","url":"\/documentation\/smiclientcore\/choice\/title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","url":"\/documentation\/smiclientcore\/abstractchoice","abstract":[],"title":"AbstractChoice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice/optionValue":{"title":"optionValue","url":"\/documentation\/smiclientcore\/choice\/optionvalue","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/optionValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"optionValue"}],"abstract":[{"text":"The value that will be displayed in the chat feed when this choice is selected.","type":"text"},{"text":" ","type":"text"},{"text":"This property represents the text that appears in the conversation after selection.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIChoice","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIChoice"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/optionValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice\/title"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption"],"type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIChoice","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractChoice","text":"SMIAbstractChoice","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIChoice","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title"},{"value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments"},{"value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle"},{"value":"SMIParticipantClientMenuOption","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/title"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenuOption"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/fragments"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenuOption"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/navigatorTitle"},{"value":"title","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice~1title\/title"},{"value":[{"text":"title","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice~1title\/fragments"},{"value":"SMIAbstractChoice","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/title"},{"value":[{"kind":"identifier","text":"SMIAbstractChoice"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/fragments"},{"value":[{"text":"SMIAbstractChoice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/navigatorTitle"},{"value":"optionValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice~1optionValue\/title"},{"value":[{"kind":"identifier","text":"optionValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice~1optionValue\/fragments"}]}]}