{"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIChoiceListValue","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListValue","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"ChoiceListValue","kind":"identifier"}],"title":"ChoiceListValue"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"A protocol that defines a single option within a choice list in pre-chat.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"This protocol represents an individual option that can be selected from a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Each value has a unique identifier, display label, and can be marked as the default selection."},{"type":"text","text":" "},{"type":"text","text":"These values are used to populate dropdown menus and other selection interfaces in the pre-chat form."}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/isDefaultValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/order","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueName"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/choicelistvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicelistvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","title":"ChoiceListValue","navigatorTitle":[{"text":"ChoiceListValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a single option within a choice list in pre-chat."}],"type":"topic","url":"\/documentation\/smiclientcore\/choicelistvalue","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue/isDefaultValue":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDefaultValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Indicates whether this value should be pre-selected by default.","type":"text"},{"text":" ","type":"text"},{"text":"When true, this option will be automatically selected when the choice list is displayed.","type":"text"}],"navigatorTitle":[{"text":"isDefaultValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choicelistvalue\/isdefaultvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/isDefaultValue","title":"isDefaultValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue/valueId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueId","abstract":[{"text":"The unique identifier for this choice list value.","type":"text"},{"text":" ","type":"text"},{"text":"This ID is used to reference the specific option within a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","type":"reference"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"valueId","kind":"identifier"}],"title":"valueId","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistvalue\/valueid"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue/label":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The display text shown to users for this option."},{"type":"text","text":" "},{"type":"text","text":"This is the human-readable label that appears in the UI."}],"navigatorTitle":[{"text":"label","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choicelistvalue\/label","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/label","title":"label"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue/order":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/order","abstract":[{"text":"The display order of this value within its parent choice list.","type":"text"},{"text":" ","type":"text"},{"text":"Lower numbers appear first in the list of options.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"order","kind":"identifier"}],"title":"order","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"order","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistvalue\/order"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue/valueName":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"The internal name used to identify this value in the system.","type":"text"},{"text":" ","type":"text"},{"text":"This name is used for data processing and may differ from the display label.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"valueName"}],"url":"\/documentation\/smiclientcore\/choicelistvalue\/valuename","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueName","title":"valueName"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","navigatorTitle":[{"text":"ChoiceList","kind":"identifier"}],"title":"ChoiceList","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelist"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIChoiceListValue","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIChoiceListValue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIChoiceListValue","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/isDefaultValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/order","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue\/valueName"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIChoiceListValue"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIChoiceListValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIChoiceListValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/fragments"},{"op":"replace","value":[{"text":"SMIChoiceListValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/navigatorTitle"},{"op":"replace","value":"isDefaultValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1isDefaultValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isDefaultValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1isDefaultValue\/fragments"},{"op":"replace","value":"valueId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1valueId\/title"},{"op":"replace","value":[{"text":"valueId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1valueId\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1label\/title","op":"replace","value":"label"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1label\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1order\/title","op":"replace","value":"order"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1order\/fragments","op":"replace","value":[{"text":"order","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1valueName\/title","op":"replace","value":"valueName"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue~1valueName\/fragments","op":"replace","value":[{"text":"valueName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","op":"replace","value":"SMIChoiceList"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIChoiceList"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","op":"replace","value":[{"text":"SMIChoiceList","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}