{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"EntryPayload","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","text":"EntryTypeMessage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"name":"Note","content":[{"inlineContent":[{"text":"All properties and features which are exposed in this class are subject to change.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"},{"name":"Warning","content":[{"inlineContent":[{"type":"text","text":"Experimental features\/APIs may be removed without advanced notification at any time."},{"type":"text","text":" "},{"type":"text","text":"Any use of these features will "},{"type":"strong","inlineContent":[{"type":"text","text":"NOT"}]},{"type":"text","text":" be offered any official support, until such time as they may be adopted as full and stable features."}],"type":"paragraph"}],"type":"aside","style":"warning"}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","title":"ChoicesExperienceTypeResponse","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"ChoicesExperienceTypeResponse"}],"externalID":"c:objc(pl)SMIChoicesExperienceTypeResponse"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse\/selectedValues"],"generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/choicesexperiencetyperesponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicesexperiencetyperesponse"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeMessage"}],"navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"url":"\/documentation\/smiclientcore\/entrytypemessage","title":"EntryTypeMessage","kind":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse/selectedValues":{"abstract":[],"navigatorTitle":[{"text":"selectedValues","kind":"identifier"}],"required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse\/selectedvalues","title":"selectedValues","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedValues"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]]","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse\/selectedValues"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse":{"type":"topic","url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse","kind":"symbol","navigatorTitle":[{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"title":"ChoicesExperienceTypeResponse","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" object."}],"url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"title":"EntryPayload"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIChoicesExperienceTypeResponse","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse\/selectedValues"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIEntryTypeMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","op":"replace"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","op":"replace"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","op":"replace"},{"value":"selectedValues","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse~1selectedValues\/title","op":"replace"},{"value":[{"kind":"identifier","text":"selectedValues"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse~1selectedValues\/fragments","op":"replace"},{"value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace"},{"value":"SMIChoicesExperienceTypeResponse","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/title","op":"replace"},{"value":[{"text":"SMIChoicesExperienceTypeResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/navigatorTitle","op":"replace"},{"value":"SMIEntryPayload","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}