{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol represents a configuration that contains a set of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true},{"type":"text","text":" objects and their"},{"type":"text","text":" "},{"type":"text","text":"relationships for pre-chat fields. It manages both the available choice lists and the dependencies between them,"},{"type":"text","text":" "},{"type":"text","text":"allowing for complex hierarchical relationships between different sets of options in the pre-chat form."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","interfaceLanguage":"swift"},"metadata":{"symbolKind":"protocol","role":"symbol","externalID":"c:objc(pl)SMIChoiceListConfiguration","title":"ChoiceListConfiguration","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"ChoiceListConfiguration","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/choicelistconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choicelistconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/choiceLists","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/valueDependencies"],"generated":true}],"abstract":[{"text":"A protocol that defines the configuration for a collection of choice lists used in pre-chat.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration/choiceLists":{"required":true,"type":"topic","title":"choiceLists","url":"\/documentation\/smiclientcore\/choicelistconfiguration\/choicelists","abstract":[{"text":"The collection of available choice lists for pre-chat fields.","type":"text"},{"text":" ","type":"text"},{"text":"Each list in this array is a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},{"text":" that defines a set of options.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"choiceLists","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/choiceLists","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceLists","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ChoiceList","preciseIdentifier":"c:objc(pl)SMIChoiceList","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListDependency":{"title":"ChoiceListDependency","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListDependency","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ChoiceListDependency","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","url":"\/documentation\/smiclientcore\/choicelistdependency","role":"symbol","abstract":[{"text":"A protocol that defines a dependency relationship between two choice lists in pre-chat.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","navigatorTitle":[{"text":"ChoiceListConfiguration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choicelistconfiguration","title":"ChoiceListConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"A protocol that defines the configuration for a collection of choice lists used in pre-chat.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListConfiguration","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration/valueDependencies":{"title":"valueDependencies","url":"\/documentation\/smiclientcore\/choicelistconfiguration\/valuedependencies","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/valueDependencies","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueDependencies"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListDependency","text":"ChoiceListDependency"},{"kind":"text","text":"]"}],"kind":"symbol","abstract":[{"type":"text","text":"The relationships between different choice lists in pre-chat."},{"type":"text","text":" "},{"type":"text","text":"Each dependency in this array is a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","isActive":true},{"type":"text","text":" that defines how choice lists"},{"type":"text","text":" "},{"type":"text","text":"are related to each other."}],"navigatorTitle":[{"kind":"identifier","text":"valueDependencies"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}],"title":"ChoiceList","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIChoiceListConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIChoiceListConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIChoiceListConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/choiceLists","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/valueDependencies"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIChoiceListConfiguration"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1choiceLists\/title","value":"choiceLists","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1choiceLists\/fragments","value":[{"kind":"identifier","text":"choiceLists"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/title","value":"SMIChoiceListDependency","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/fragments","value":[{"text":"SMIChoiceListDependency","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/navigatorTitle","value":[{"text":"SMIChoiceListDependency","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/title","value":"SMIChoiceListConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/fragments","value":[{"kind":"identifier","text":"SMIChoiceListConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/navigatorTitle","value":[{"text":"SMIChoiceListConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1valueDependencies\/title","value":"valueDependencies","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1valueDependencies\/fragments","value":[{"text":"valueDependencies","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","value":"SMIChoiceList","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","value":[{"kind":"identifier","text":"SMIChoiceList"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}],"op":"replace"}]}]}