{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"role":"symbol","roleHeading":"Protocol","title":"ChoiceList","externalID":"c:objc(pl)SMIChoiceList","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/values"],"generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choicelist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choicelist"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This protocol represents a set of predefined options that can be presented to users.","type":"text"},{"text":" ","type":"text"},{"text":"Each choice list has a unique identifier and contains an array of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue"},{"text":" objects","type":"text"},{"text":" ","type":"text"},{"text":"that define the available options.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},"abstract":[{"text":"A protocol that defines a collection of choice list values.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList/identifier":{"abstract":[{"type":"text","text":"The unique identifier for this choice list."},{"type":"text","text":" "},{"type":"text","text":"This ID is used to reference the choice list in configurations and dependencies."}],"title":"identifier","kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/identifier","url":"\/documentation\/smiclientcore\/choicelist\/identifier","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue":{"abstract":[{"text":"A protocol that defines a single option within a choice list in pre-chat.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistvalue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListValue","kind":"identifier"}],"title":"ChoiceListValue","role":"symbol","type":"topic","navigatorTitle":[{"text":"ChoiceListValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"title":"ChoiceList","abstract":[{"text":"A protocol that defines a collection of choice list values.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList/values":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/values","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"values","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ChoiceListValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListValue"},{"text":"]","kind":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelist\/values","kind":"symbol","title":"values","navigatorTitle":[{"text":"values","kind":"identifier"}],"abstract":[{"text":"The array of available options in this choice list.","type":"text"},{"text":" ","type":"text"},{"text":"Each value in the array is a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","type":"reference"},{"text":" that defines a selectable option.","type":"text"}],"type":"topic","required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIChoiceList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIChoiceList"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList\/values"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIChoiceList"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/title","value":"SMIChoiceListValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/fragments","value":[{"kind":"identifier","text":"SMIChoiceListValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChoiceListValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","value":"SMIChoiceList"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1values\/title","value":"values"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList~1values\/fragments","value":[{"kind":"identifier","text":"values"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}