{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citationclaim"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citationclaim"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimEndOffset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimStartOffset"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitationClaim","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A protocol that represents the location of a citation within a text message."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitationClaim"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitationClaim","kind":"identifier"}],"externalID":"c:objc(pl)SMICitationClaim","title":"CitationClaim","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim":{"url":"\/documentation\/smiclientcore\/citationclaim","abstract":[{"text":"A protocol that represents the location of a citation within a text message.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","role":"symbol","navigatorTitle":[{"text":"CitationClaim","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CitationClaim","kind":"identifier"}],"type":"topic","title":"CitationClaim"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim/claimStartOffset":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claimStartOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The starting position of the citation in the text message."},{"type":"text","text":" "},{"type":"text","text":"This offset represents the index where the cited text begins in the message content."},{"type":"text","text":" "},{"type":"text","text":"The offset is zero-based, meaning the first character of the message is at offset 0."}],"navigatorTitle":[{"text":"claimStartOffset","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citationclaim\/claimstartoffset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimStartOffset","title":"claimStartOffset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim/claimEndOffset":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimEndOffset","abstract":[{"type":"text","text":"The ending position of the citation in the text message."},{"type":"text","text":" "},{"type":"text","text":"This offset represents the index where the cited text ends in the message content."},{"type":"text","text":" "},{"type":"text","text":"The offset is exclusive, meaning it points to the character immediately after the last"},{"type":"text","text":" "},{"type":"text","text":"character of the citation."}],"role":"symbol","navigatorTitle":[{"text":"claimEndOffset","kind":"identifier"}],"title":"claimEndOffset","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claimEndOffset","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/citationclaim\/claimendoffset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMICitationClaim"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMICitationClaim"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMICitationClaim","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimEndOffset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim\/claimStartOffset"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICitationClaim"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SMICitationClaim","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/title"},{"op":"replace","value":[{"text":"SMICitationClaim","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICitationClaim"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/navigatorTitle"},{"op":"replace","value":"claimStartOffset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimStartOffset\/title"},{"op":"replace","value":[{"text":"claimStartOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimStartOffset\/fragments"},{"op":"replace","value":"claimEndOffset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimEndOffset\/title"},{"op":"replace","value":[{"text":"claimEndOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim~1claimEndOffset\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}