{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/citation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citation"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Citation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A citation typically includes a reference to a source and may contain additional details about where the citation"},{"type":"text","text":" "},{"type":"text","text":"appears in the source material."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A protocol that represents a citation in a conversation, providing reference and offset information."}],"metadata":{"symbolKind":"protocol","title":"Citation","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"Citation"}],"externalID":"c:objc(pl)SMICitation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Citation"}],"role":"symbol","modules":[{"name":"SMIClientCore"}]},"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedDetails","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedReference"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation":{"abstract":[{"type":"text","text":"A protocol that represents a citation in a conversation, providing reference and offset information."}],"kind":"symbol","title":"Citation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Citation","kind":"identifier"}],"navigatorTitle":[{"text":"Citation","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation/citedDetails":{"navigatorTitle":[{"kind":"identifier","text":"citedDetails"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetails"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedDetails","text":"CitedDetails"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Additional details about the citation’s location in the source material."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides access to offset and positioning information through the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"},{"type":"text","text":" protocol, which can include details about where the citation appears"},{"type":"text","text":" "},{"type":"text","text":"in the referenced source."}],"required":true,"url":"\/documentation\/smiclientcore\/citation\/citeddetails","title":"citedDetails","role":"symbol","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","kind":"symbol","title":"CitedDetails","abstract":[{"type":"text","text":"A protocol that represents the location and type information for a citation."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/citeddetails","navigatorTitle":[{"text":"CitedDetails","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CitedReference","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedreference","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReference","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","title":"CitedReference","abstract":[{"type":"text","text":"A protocol that represents the reference information for a citation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation/citedReference":{"abstract":[{"text":"The reference information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the link and source details through the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","type":"reference"},{"text":" ","type":"text"},{"text":"protocol, which contains the primary reference information for the citation.","type":"text"}],"kind":"symbol","title":"citedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedReference","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedReference"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"CitedReference","preciseIdentifier":"c:objc(pl)SMICitedReference"}],"navigatorTitle":[{"kind":"identifier","text":"citedReference"}],"url":"\/documentation\/smiclientcore\/citation\/citedreference"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMICitation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMICitation"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitation"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedDetails","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation\/citedReference"],"title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICitation"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/title","value":"SMICitation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/fragments","value":[{"text":"SMICitation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedDetails\/title","value":"citedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedDetails\/fragments","value":[{"kind":"identifier","text":"citedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/title","value":"SMICitedDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/fragments","value":[{"kind":"identifier","text":"SMICitedDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/navigatorTitle","value":[{"text":"SMICitedDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/title","value":"SMICitedReference"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/fragments","value":[{"text":"SMICitedReference","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/navigatorTitle","value":[{"text":"SMICitedReference","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedReference\/title","value":"citedReference","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation~1citedReference\/fragments","value":[{"kind":"identifier","text":"citedReference"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}