{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent"},"abstract":[{"type":"text","text":"A protocol that represents a collection of citations associated with a text message."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"CitationContent"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)SMICitationContent","symbolKind":"protocol","title":"CitationContent","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitationContent"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitationContent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/smiclientcore\/citationcontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citationcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent\/citations"],"anchor":"Instance-Properties","generated":true}],"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationContent/citations":{"navigatorTitle":[{"text":"citations","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent\/citations","abstract":[{"text":"The array of citations associated with this message.","type":"text"},{"text":" ","type":"text"},{"text":"Each citation in the array conforms to the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation","isActive":true,"type":"reference"},{"text":" protocol and contains","type":"text"},{"text":" ","type":"text"},{"text":"information about a specific reference, including its location in the message and","type":"text"},{"text":" ","type":"text"},{"text":"any associated reference details.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citations","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"Citation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitation"},{"text":"]","kind":"text"}],"title":"citations","kind":"symbol","url":"\/documentation\/smiclientcore\/citationcontent\/citations","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationContent":{"type":"topic","role":"symbol","title":"CitationContent","kind":"symbol","url":"\/documentation\/smiclientcore\/citationcontent","navigatorTitle":[{"text":"CitationContent","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a collection of citations associated with a text message.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitationContent","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Citation":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Citation","kind":"identifier"}],"title":"Citation","abstract":[{"text":"A protocol that represents a citation in a conversation, providing reference and offset information.","type":"text"}],"url":"\/documentation\/smiclientcore\/citation","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Citation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Citation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMICitationContent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMICitationContent","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SMICitationContent"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationContent\/citations"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICitationContent"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent~1citations\/title","value":"citations","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent~1citations\/fragments","value":[{"text":"citations","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/title","value":"SMICitationContent","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/fragments","value":[{"kind":"identifier","text":"SMICitationContent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationContent\/navigatorTitle","value":[{"text":"SMICitationContent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/title","value":"SMICitation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/fragments","value":[{"kind":"identifier","text":"SMICitation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Citation\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}