{"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/link"],"anchor":"Type-Properties"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/Equatable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citedreferencetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citedreferencetype"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:SMICitedReferenceType.h@T@SMICitedReferenceType","role":"symbol","symbolKind":"struct","title":"CitedReferenceType","roleHeading":"Structure","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"CitedReferenceType"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CitedReferenceType","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CitedReferenceType","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"This enum is used to identify the type of citation reference being used. The type determines","type":"text"},{"text":" ","type":"text"},{"text":"how the citation’s source information should be interpreted and processed. Each type","type":"text"},{"text":" ","type":"text"},{"text":"corresponds to a specific format or structure of reference information.","type":"text"}],"type":"paragraph"},{"level":2,"type":"heading","anchor":"Possible-Values","text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/link","isActive":true,"type":"reference"},{"text":" - Represents a citation that references an external source","type":"text"}],"type":"paragraph"}]}]}]}],"sections":[],"abstract":[{"type":"text","text":"An enum that defines the types of citation references available in the system."}],"references":{"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType/Equatable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/Equatable-Implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","type":"topic","kind":"article","url":"\/documentation\/smiclientcore\/citedreferencetype\/equatable-implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType/link":{"url":"\/documentation\/smiclientcore\/citedreferencetype\/link","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/link","abstract":[{"type":"text","text":"Represents a citation reference that includes a link to the source material."},{"type":"text","text":" "},{"type":"text","text":"This type is used when the citation references an external source through a URL or"},{"type":"text","text":" "},{"type":"text","text":"other link-based reference mechanism."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMICitedReferenceTypeLink"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType","kind":"typeIdentifier","text":"CitedReferenceType"}],"type":"topic","title":"link"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/citedreferencetype\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CitedReferenceType","kind":"identifier"}],"abstract":[{"text":"An enum that defines the types of citation references available in the system.","type":"text"}],"navigatorTitle":[{"text":"CitedReferenceType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedreferencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","title":"CitedReferenceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMICitedReferenceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"SMICitedReferenceType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"SMICitedReferenceTypeLink","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType~1link\/title"},{"value":[{"text":"SMICitedReferenceTypeLink","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType~1link\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/title","value":"SMICitedReferenceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/fragments","value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/navigatorTitle","value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"op":"replace"}]}]}