{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReference","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access the reference information for a citation. The protocol"},{"type":"text","text":" "},{"type":"text","text":"provides a type identifier that determines the nature of the reference and how it"},{"type":"text","text":" "},{"type":"text","text":"should be processed."}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/citedreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/citedreference"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"CitedReference","kind":"identifier"}],"title":"CitedReference","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMICitedReference","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReference","kind":"identifier"}],"roleHeading":"Protocol"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"],"type":"inheritedBy"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","interfaceLanguage":"swift"},"abstract":[{"text":"A protocol that represents the reference information for a citation.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference\/citedReferenceType"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"}],"navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"title":"LinkCitedReference","url":"\/documentation\/smiclientcore\/linkcitedreference","abstract":[{"type":"text","text":"A protocol that represents a citation reference that links to an external URL."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType":{"url":"\/documentation\/smiclientcore\/citedreferencetype","kind":"symbol","role":"symbol","title":"CitedReferenceType","abstract":[{"text":"An enum that defines the types of citation references available in the system.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReferenceType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CitedReferenceType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference":{"navigatorTitle":[{"text":"CitedReference","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedreference","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedReference","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents the reference information for a citation."}],"kind":"symbol","title":"CitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference/citedReferenceType":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference\/citedReferenceType","abstract":[{"type":"text","text":"The type identifier for this citation reference."},{"type":"text","text":" "},{"type":"text","text":"This property determines the nature and format of the reference through the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType"},{"type":"text","text":" enum. The type helps determine how the reference"},{"type":"text","text":" "},{"type":"text","text":"should be processed and displayed in the UI."}],"required":true,"url":"\/documentation\/smiclientcore\/citedreference\/citedreferencetype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedReferenceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType","text":"CitedReferenceType"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"citedReferenceType"}],"title":"citedReferenceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMICitedReference","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMICitedReference","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMICitedReference","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference\/citedReferenceType"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference"]}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICitedReference","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/title","op":"replace","value":"SMILinkCitedReference"},{"value":[{"text":"SMILinkCitedReference","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/fragments"},{"value":[{"text":"SMILinkCitedReference","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/navigatorTitle"},{"value":"SMICitedReferenceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/title"},{"value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/fragments"},{"value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/navigatorTitle"},{"value":"SMICitedReference","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/title"},{"value":[{"text":"SMICitedReference","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/fragments"},{"value":[{"kind":"identifier","text":"SMICitedReference"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/navigatorTitle"},{"value":"citedReferenceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference~1citedReferenceType\/title"},{"value":[{"kind":"identifier","text":"citedReferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference~1citedReferenceType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}