{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citedinlinemetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citedinlinemetadata"]}],"metadata":{"navigatorTitle":[{"text":"CitedInlineMetadata","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)SMICitedInlineMetadata","modules":[{"name":"SMIClientCore"}],"title":"CitedInlineMetadata","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedInlineMetadata","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedInlineMetadata"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"abstract":[{"text":"A protocol that represents inline metadata for a citation, including its location and claim information.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/citedLocationOffset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/claim"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata":{"kind":"symbol","title":"CitedInlineMetadata","abstract":[{"type":"text","text":"A protocol that represents inline metadata for a citation, including its location and claim information."}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CitedInlineMetadata"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedInlineMetadata"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata/citedLocationOffset":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedLocationOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"required":true,"url":"\/documentation\/smiclientcore\/citedinlinemetadata\/citedlocationoffset","role":"symbol","kind":"symbol","type":"topic","title":"citedLocationOffset","abstract":[{"text":"The ending position of the citation in the text.","type":"text"},{"text":" ","type":"text"},{"text":"This offset represents the index where the citation should end in the text content.","type":"text"},{"text":" ","type":"text"},{"text":"The offset is exclusive, meaning it points to the character immediately after the last","type":"text"},{"text":" ","type":"text"},{"text":"character of the citation.","type":"text"}],"navigatorTitle":[{"text":"citedLocationOffset","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/citedLocationOffset"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata/claim":{"abstract":[{"text":"The claim information for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to the start and end offsets of the cited content","type":"text"},{"text":" ","type":"text"},{"text":"through the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","type":"reference","isActive":true},{"text":" protocol. When present, it defines the exact location","type":"text"},{"text":" ","type":"text"},{"text":"of the citation within the text.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/claim","url":"\/documentation\/smiclientcore\/citedinlinemetadata\/claim","kind":"symbol","required":true,"title":"claim","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"claim","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"CitationClaim","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitationClaim"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"claim","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitationClaim":{"type":"topic","navigatorTitle":[{"text":"CitationClaim","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citationclaim","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitationClaim","role":"symbol","kind":"symbol","title":"CitationClaim","abstract":[{"type":"text","text":"A protocol that represents the location of a citation within a text message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitationClaim","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMICitedInlineMetadata","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/citedLocationOffset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata\/claim"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICitedInlineMetadata","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/title","value":"SMICitedInlineMetadata","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/fragments","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitedInlineMetadata"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1citedLocationOffset\/title","value":"citedLocationOffset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1citedLocationOffset\/fragments","value":[{"kind":"identifier","text":"citedLocationOffset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1claim\/title","value":"claim","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata~1claim\/fragments","value":[{"kind":"identifier","text":"claim"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/title","value":"SMICitationClaim","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/fragments","value":[{"text":"SMICitationClaim","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitationClaim\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitationClaim"}],"op":"replace"}]}]}