{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents the location and type information for a citation."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citeddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citeddetails"]}],"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails\/citedDetailsType"]}],"metadata":{"symbolKind":"protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetails"}],"navigatorTitle":[{"kind":"identifier","text":"CitedDetails"}],"title":"CitedDetails","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMICitedDetails"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails/citedDetailsType":{"navigatorTitle":[{"text":"citedDetailsType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type identifier for this citation’s details."},{"type":"text","text":" "},{"type":"text","text":"The type is defined by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"},{"type":"text","text":" enum and helps determine the"},{"type":"text","text":" "},{"type":"text","text":"appropriate way to process and display the citation."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedDetailsType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedDetailsType","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","kind":"typeIdentifier"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails\/citedDetailsType","kind":"symbol","role":"symbol","title":"citedDetailsType","url":"\/documentation\/smiclientcore\/citeddetails\/citeddetailstype"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","role":"symbol","abstract":[{"text":"An enum that defines the types of citation details available in the system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedDetailsType"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetailsType"}],"title":"CitedDetailsType","url":"\/documentation\/smiclientcore\/citeddetailstype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/InlineMetadataCitedDetails":{"navigatorTitle":[{"text":"InlineMetadataCitedDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/inlinemetadataciteddetails","abstract":[{"type":"text","text":"A protocol that represents citation details with inline metadata for the given citations."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InlineMetadataCitedDetails","kind":"identifier"}],"kind":"symbol","title":"InlineMetadataCitedDetails"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetails"}],"url":"\/documentation\/smiclientcore\/citeddetails","abstract":[{"type":"text","text":"A protocol that represents the location and type information for a citation."}],"navigatorTitle":[{"kind":"identifier","text":"CitedDetails"}],"kind":"symbol","role":"symbol","title":"CitedDetails"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMICitedDetails","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitedDetails"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICitedDetails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails\/citedDetailsType"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails"],"type":"inheritedBy","title":"Inherited By"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICitedDetails","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails~1citedDetailsType\/title","op":"replace","value":"citedDetailsType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails~1citedDetailsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"citedDetailsType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/title","op":"replace","value":"SMICitedDetailsType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICitedDetailsType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/navigatorTitle","op":"replace","value":[{"text":"SMICitedDetailsType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/title","op":"replace","value":"SMIInlineMetadataCitedDetails"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIInlineMetadataCitedDetails"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIInlineMetadataCitedDetails"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/title","op":"replace","value":"SMICitedDetails"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/fragments","op":"replace","value":[{"text":"SMICitedDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/navigatorTitle","op":"replace","value":[{"text":"SMICitedDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}