{"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV1","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV2"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/clienttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/clienttype"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:SMIClientType.h@T@SMIClientType","title":"ClientType","symbolKind":"struct","role":"symbol","roleHeading":"Structure","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"ClientType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientType","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Possible Values","anchor":"Possible-Values","type":"heading"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV1","type":"reference"},{"text":" - Standard mobile client type for MIAW integrations","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV2"},{"text":" - Enhanced mobile client type for MIAW integrations with additional capabilities","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"sections":[],"abstract":[{"text":"A type that defines the client type sent during authentication to identify the SDK integration type.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType/miawMobileV2":{"abstract":[{"type":"text","text":"Enhanced mobile client type for MIAW integrations with additional capabilities."}],"navigatorTitle":[{"kind":"identifier","text":"SMIClientTypeMIAWMobileV2"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV2","title":"miawMobileV2","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"miawMobileV2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","text":"ClientType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/clienttype\/miawmobilev2"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType/miawMobileV1":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"miawMobileV1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","text":"ClientType"}],"url":"\/documentation\/smiclientcore\/clienttype\/miawmobilev1","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIClientTypeMIAWMobileV1"}],"abstract":[{"type":"text","text":"Standard mobile client type for MIAW integrations."}],"title":"miawMobileV1","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV1"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/init(rawValue:)","abstract":[],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/clienttype\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType/Equatable-Implementations":{"url":"\/documentation\/smiclientcore\/clienttype\/equatable-implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/Equatable-Implementations"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType","title":"ClientType","navigatorTitle":[{"kind":"identifier","text":"ClientType"}],"abstract":[{"type":"text","text":"A type that defines the client type sent during authentication to identify the SDK integration type."}],"type":"topic","url":"\/documentation\/smiclientcore\/clienttype","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientType"}]},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIClientType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIClientType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIClientType"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIClientType","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV2\/title","op":"replace","value":"SMIClientTypeMIAWMobileV2"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV2\/fragments","op":"replace","value":[{"text":"SMIClientTypeMIAWMobileV2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV1\/title","op":"replace","value":"SMIClientTypeMIAWMobileV1"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV1\/fragments","op":"replace","value":[{"text":"SMIClientTypeMIAWMobileV1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/title","op":"replace","value":"SMIClientType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/fragments","op":"replace","value":[{"text":"SMIClientType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/navigatorTitle","op":"replace","value":[{"text":"SMIClientType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}