{"kind":"symbol","metadata":{"externalID":"c:SMIClientName.h@T@SMIClientName","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientName","kind":"identifier"}],"symbolKind":"struct","roleHeading":"Structure","navigatorTitle":[{"kind":"identifier","text":"ClientName"}],"title":"ClientName"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"A type that defines the client name sent during authentication to identify the SDK integration type.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientName"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Possible-Values","type":"heading","text":"Possible Values"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileAgentforceSDK","type":"reference"},{"type":"text","text":" - Mobile client for Agentforce SDK integrations"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileInAppSDK","type":"reference"},{"text":" - Mobile client for In-App SDK integrations","type":"text"}]}]}],"type":"unorderedList"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileAgentforceSDK","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileInAppSDK"],"anchor":"Type-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/Equatable-Implementations"],"anchor":"Default-Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/clientname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/clientname"]}],"references":{"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/smiclientcore\/clientname\/equatable-implementations"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName","title":"ClientName","navigatorTitle":[{"text":"ClientName","kind":"identifier"}],"abstract":[{"text":"A type that defines the client name sent during authentication to identify the SDK integration type.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/clientname","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientName","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/mobileInAppSDK":{"type":"topic","url":"\/documentation\/smiclientcore\/clientname\/mobileinappsdk","title":"mobileInAppSDK","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileInAppSDK","navigatorTitle":[{"kind":"identifier","text":"SMIClientNameMobileInAppSDK"}],"abstract":[{"type":"text","text":"Mobile client for In-App SDK integrations."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileInAppSDK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","text":"ClientName"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/init(rawValue:)","abstract":[],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/clientname\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientName/mobileAgentforceSDK":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientName\/mobileAgentforceSDK","title":"mobileAgentforceSDK","navigatorTitle":[{"kind":"identifier","text":"SMIClientNameMobileAgentforceSDK"}],"abstract":[{"type":"text","text":"Mobile client for Agentforce SDK integrations."}],"type":"topic","url":"\/documentation\/smiclientcore\/clientname\/mobileagentforcesdk","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mobileAgentforceSDK","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientName.h@T@SMIClientName","text":"ClientName"}]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIClientName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIClientName","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIClientName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"SMIClientName"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"SMIClientName","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/title"},{"op":"replace","value":[{"text":"SMIClientName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/fragments"},{"op":"replace","value":[{"text":"SMIClientName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileInAppSDK\/title","value":"SMIClientNameMobileInAppSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileInAppSDK\/fragments","value":[{"text":"SMIClientNameMobileInAppSDK","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileAgentforceSDK\/title","value":"SMIClientNameMobileAgentforceSDK"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientName~1mobileAgentforceSDK\/fragments","value":[{"text":"SMIClientNameMobileAgentforceSDK","kind":"identifier"}],"op":"replace"}]}]}