{"abstract":[{"type":"text","text":"The completion block for returning the error result from the closeConversation call."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationCompletion","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CloseConversationCompletion"}],"roleHeading":"Type Alias","externalID":"c:SMIAPICompletions.h@T@SMICloseConversationCompletion","role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"CloseConversationCompletion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"inlineContent":[{"text":"If the closeConversation call results in an error, it is returned here. A successful close conversation call returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for the error.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/closeconversationcompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/closeconversationcompletion"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationCompletion","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CloseConversationCompletion":{"role":"symbol","title":"CloseConversationCompletion","kind":"symbol","abstract":[{"text":"The completion block for returning the error result from the closeConversation call.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationCompletion","url":"\/documentation\/smiclientcore\/closeconversationcompletion","navigatorTitle":[{"text":"CloseConversationCompletion","kind":"identifier"}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationCompletion","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMICloseConversationCompletion","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMICloseConversationCompletion","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMICloseConversationCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICloseConversationCompletion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMICloseConversationCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMICloseConversationCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/fragments"},{"value":[{"kind":"identifier","text":"SMICloseConversationCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/navigatorTitle"}]}]}