{"variants":[{"paths":["\/documentation\/smiclientcore\/completedattachmentuploadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/completedattachmentuploadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CompletedAttachmentUploadResult","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletedAttachmentUploadResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","text":"AttachmentUploadResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Represents the result of a completed attachment upload operation."}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"]}],"metadata":{"roleHeading":"Protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletedAttachmentUploadResult","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMICompletedAttachmentUploadResult","title":"CompletedAttachmentUploadResult","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"CompletedAttachmentUploadResult"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CompletedAttachmentUploadResult":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompletedAttachmentUploadResult"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/completedattachmentuploadresult","role":"symbol","abstract":[{"type":"text","text":"Represents the result of a completed attachment upload operation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CompletedAttachmentUploadResult","title":"CompletedAttachmentUploadResult","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletedAttachmentUploadResult"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"kind":"symbol","title":"AttachmentUploadResult","url":"\/documentation\/smiclientcore\/attachmentuploadresult","abstract":[{"type":"text","text":"Result of an attachment upload operation."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResult"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMICompletedAttachmentUploadResult","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMICompletedAttachmentUploadResult"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICompletedAttachmentUploadResult"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICompletedAttachmentUploadResult","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","text":"SMIAttachmentUploadResult","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/title","op":"replace","value":"SMICompletedAttachmentUploadResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICompletedAttachmentUploadResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CompletedAttachmentUploadResult\/navigatorTitle","op":"replace","value":[{"text":"SMICompletedAttachmentUploadResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title","op":"replace","value":"SMIAttachmentUploadResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments","op":"replace","value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle","op":"replace","value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}