{"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIComposedStreamingToken","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"title":"ComposedStreamingToken"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComposedStreamingToken"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"EntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"}]}]},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use this protocol to access a conversation entry that is composed of multiple streaming tokens."},{"type":"text","text":" "},{"type":"text","text":"This protocol extends "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"},{"type":"text","text":" to provide functionality for managing streaming"},{"type":"text","text":" "},{"type":"text","text":"content that is being built up over time. It includes validation capabilities and maintains"},{"type":"text","text":" "},{"type":"text","text":"the relationship between individual streaming tokens and their composed result."}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/derivedValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/relatedStreamingTokens","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/tokenType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/turnId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/validation"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/composedstreamingtoken"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/batchNumber":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/batchNumber","abstract":[{"text":"The sequence number for related events within a turn.","type":"text"},{"text":" ","type":"text"},{"text":"Events with the same batch number are strongly associated and are delivered together.","type":"text"},{"text":" ","type":"text"},{"text":"Use this to identify and process groups of related events that should be handled","type":"text"},{"text":" ","type":"text"},{"text":"as a single unit within a conversation turn.","type":"text"}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/batchnumber","role":"symbol","navigatorTitle":[{"text":"batchNumber","kind":"identifier"}],"required":true,"title":"batchNumber","type":"topic"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"role":"symbol","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"title":"ComposedStreamingToken","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","title":"EntryFormat","navigatorTitle":[{"kind":"identifier","text":"EntryFormat"}],"abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entryformat","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryFormat"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/validation":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validation","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIStreamingTokenValidation","text":"StreamingTokenValidation","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/validation","abstract":[{"text":"The validation status for this composed token.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides access to validation information through the","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","type":"reference"},{"text":" protocol. When ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current stream of tokens","type":"text"},{"text":" ","type":"text"},{"text":"should be considered valid.","type":"text"},{"text":" ","type":"text"},{"text":"If present and its ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","type":"reference"},{"text":" property is ","type":"text"},{"code":"NO","type":"codeVoice"},{"text":", the content","type":"text"},{"text":" ","type":"text"},{"text":"should be considered to have been discarded and will be replaced.","type":"text"}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/validation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validation"}],"required":true,"title":"validation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/targetMessageIdentifier":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/targetMessageIdentifier","abstract":[{"type":"text","text":"The identifier that will be used for the final transcribed entry."},{"type":"text","text":" "},{"type":"text","text":"This property provides a unique identifier that will be associated with the entry"},{"type":"text","text":" "},{"type":"text","text":"once all streaming tokens have been received and processed."}],"role":"symbol","navigatorTitle":[{"text":"targetMessageIdentifier","kind":"identifier"}],"title":"targetMessageIdentifier","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetMessageIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken\/targetmessageidentifier"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/turnId":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/turnid","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"turnId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier for the current conversation turn."},{"type":"text","text":" "},{"type":"text","text":"This identifier correlates all events and responses within a single interaction between"},{"type":"text","text":" "},{"type":"text","text":"the user and agent. Use this to track and group related messages and events that occur"},{"type":"text","text":" "},{"type":"text","text":"within the same conversation turn."}],"title":"turnId","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/turnId"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a validation event for a streamed message."}],"navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","title":"StreamingTokenValidation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/relatedStreamingTokens":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relatedStreamingTokens","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"MessageStreamingToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIMessageStreamingToken"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/relatedstreamingtokens","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"relatedStreamingTokens","kind":"identifier"}],"abstract":[{"text":"The ordered list of all streaming tokens associated with this entry.","type":"text"},{"text":" ","type":"text"},{"text":"This array contains all ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"},{"text":" objects that have been received","type":"text"},{"text":" ","type":"text"},{"text":"for this entry, maintained in their sequential order of arrival.","type":"text"}],"title":"relatedStreamingTokens","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/relatedStreamingTokens"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessageStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","url":"\/documentation\/smiclientcore\/messagestreamingtoken","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"title":"MessageStreamingToken","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/derivedValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/derivedValue","title":"derivedValue","navigatorTitle":[{"text":"derivedValue","kind":"identifier"}],"abstract":[{"text":"The composed value derived from all current streaming tokens.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the current state of the composed content through"},{"text":" ","type":"text"},{"text":"the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","isActive":true,"type":"reference"},{"text":" protocol, representing the accumulated result of all","type":"text"},{"type":"text","text":" "},{"text":"streaming tokens received so far.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/composedstreamingtoken\/derivedvalue","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"derivedValue","kind":"identifier"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryFormat","text":"EntryFormat"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"abstract":[{"type":"text","text":"Common interface for the content of a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"type":"text","text":" object."}],"type":"topic","url":"\/documentation\/smiclientcore\/entrypayload","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/valid":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","abstract":[{"type":"text","text":"The validation status of the composed token."},{"type":"text","text":" "},{"type":"text","text":"This property indicates whether the content of the stream has been validated as"},{"type":"text","text":" "},{"type":"text","text":"acceptable. When "},{"code":"NO","type":"codeVoice"},{"type":"text","text":", the content should be considered invalid and may be"},{"type":"text","text":" "},{"type":"text","text":"discarded or replaced."}],"role":"symbol","navigatorTitle":[{"text":"valid","kind":"identifier"}],"title":"valid","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/valid"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken/tokenType":{"url":"\/documentation\/smiclientcore\/composedstreamingtoken\/tokentype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/tokenType","abstract":[{"type":"text","text":"The type of streaming token being used."},{"type":"text","text":" "},{"type":"text","text":"This property indicates the type of streaming token through the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","isActive":true,"type":"reference"},{"type":"text","text":" "},{"type":"text","text":"enum, which helps determine how the token should be processed and displayed."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tokenType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"StreamingTokenTypes"}],"required":true,"type":"topic","title":"tokenType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIComposedStreamingToken","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/derivedValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/relatedStreamingTokens","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/tokenType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/turnId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken\/validation"],"generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIComposedStreamingToken","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1batchNumber\/title","value":"batchNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1batchNumber\/fragments","value":[{"text":"batchNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","value":"SMIComposedStreamingToken","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","value":[{"kind":"identifier","text":"SMIComposedStreamingToken"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title","value":"SMIEntryFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments","value":[{"kind":"identifier","text":"SMIEntryFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle","value":[{"text":"SMIEntryFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1validation\/title","value":"validation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1validation\/fragments","value":[{"kind":"identifier","text":"validation"}]},{"op":"replace","value":"SMIStreamingTokenTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle","value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1targetMessageIdentifier\/title","value":"targetMessageIdentifier","op":"replace"},{"value":[{"text":"targetMessageIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1targetMessageIdentifier\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1turnId\/title","op":"replace","value":"turnId"},{"op":"replace","value":[{"kind":"identifier","text":"turnId"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1turnId\/fragments"},{"op":"replace","value":"SMIStreamingTokenValidation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments"},{"value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle"},{"value":"relatedStreamingTokens","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1relatedStreamingTokens\/title"},{"op":"replace","value":[{"text":"relatedStreamingTokens","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1relatedStreamingTokens\/fragments"},{"op":"replace","value":"SMIMessageStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title"},{"value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1derivedValue\/title","op":"replace","value":"derivedValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1derivedValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"derivedValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace","value":"SMIEntryPayload"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/title","op":"replace","value":"valid"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/fragments","op":"replace","value":[{"kind":"identifier","text":"valid"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1tokenType\/title","op":"replace","value":"tokenType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken~1tokenType\/fragments","op":"replace","value":[{"text":"tokenType","kind":"identifier"}]}]}]}