{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:userVerificationRequired:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:userVerificationRequired:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/developerName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/isUserVerificationRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/organizationId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/remoteLocaleMap","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/serviceAPI"],"generated":true,"anchor":"Instance-Properties"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"Configuration","externalID":"c:objc(cs)SMICoreConfiguration"},"sections":[],"abstract":[{"text":"This class stores configuration information that is necessary when creating an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"text":" instance using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"text":" class.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/organizationId":{"title":"organizationId","url":"\/documentation\/smiclientcore\/configuration\/organizationid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"organizationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"organizationId"}],"abstract":[{"text":"The 15 character Salesforce org ID.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/organizationId","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(serviceAPI:organizationId:developerName:userVerificationRequired:)":{"url":"\/documentation\/smiclientcore\/configuration\/init(serviceapi:organizationid:developername:userverificationrequired:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:userVerificationRequired:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"serviceAPI","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"organizationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"developerName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userVerificationRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithServiceAPI:organizationId:developerName:userVerificationRequired:","kind":"identifier"}],"title":"init(serviceAPI:organizationId:developerName:userVerificationRequired:)","abstract":[{"type":"text","text":"Creates a configuration object that can be used to instantiate an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"},{"type":"text","text":" object using "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"},{"type":"text","text":"."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)":{"abstract":[{"type":"text","text":"Creates a configuration object that can be used to instantiate an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true},{"type":"text","text":" object using "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)","title":"init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)","navigatorTitle":[{"kind":"identifier","text":"initWithServiceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:"}],"type":"topic","url":"\/documentation\/smiclientcore\/configuration\/init(serviceapi:organizationid:developername:remotelocalemap:userverificationrequired:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"serviceAPI"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"organizationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"developerName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"remoteLocaleMap"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"userVerificationRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(url:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithURL:"}],"type":"topic","title":"init(url:)","role":"symbol","abstract":[{"type":"text","text":"Creates a configuration object that can be used to instantiate an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true},{"type":"text","text":" object using "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:)","url":"\/documentation\/smiclientcore\/configuration\/init(url:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/isUserVerificationRequired":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUserVerificationRequired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Indicates whether this configuration requires user verification.","type":"text"}],"title":"isUserVerificationRequired","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/isUserVerificationRequired","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration\/isuserverificationrequired","navigatorTitle":[{"text":"userVerificationRequired","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(serviceAPI:organizationId:developerName:)":{"abstract":[{"type":"text","text":"Creates a configuration object that can be used to instantiate an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" object using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"initWithServiceAPI:organizationId:developerName:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:)","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/configuration\/init(serviceapi:organizationid:developername:)","title":"init(serviceAPI:organizationId:developerName:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"serviceAPI","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"organizationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"developerName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/remoteLocaleMap":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteLocaleMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}],"title":"remoteLocaleMap","url":"\/documentation\/smiclientcore\/configuration\/remotelocalemap","abstract":[{"type":"text","text":"Used to provide mapping from device locale to a specific language when retrieving localized copy for the current deployment."},{"type":"text","text":" "},{"type":"text","text":"This currently impacts only localized strings as part of the RemoteConfiguration response."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"remoteLocaleMap"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/remoteLocaleMap"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/serviceAPI":{"title":"serviceAPI","abstract":[{"type":"text","text":"The base endpoint we are connecting to for all API requests."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/serviceAPI","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceAPI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"navigatorTitle":[{"kind":"identifier","text":"serviceAPI"}],"url":"\/documentation\/smiclientcore\/configuration\/serviceapi","type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP"},"doc://com.salesforce.SMIClientCore/objc(cs)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/init(url:userVerificationRequired:)":{"url":"\/documentation\/smiclientcore\/configuration\/init(url:userverificationrequired:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userVerificationRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:userVerificationRequired:)","navigatorTitle":[{"kind":"identifier","text":"initWithURL:userVerificationRequired:"}],"type":"topic","title":"init(url:userVerificationRequired:)","kind":"symbol","abstract":[{"text":"Creates a configuration object that can be used to instantiate an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"text":" object using ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration/developerName":{"kind":"symbol","role":"symbol","abstract":[{"text":"The API Name for the embedded service deployment associated with this configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"developerName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"developerName"}],"url":"\/documentation\/smiclientcore\/configuration\/developername","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/developerName","title":"developerName","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMICoreConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/developerName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/isUserVerificationRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/organizationId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/remoteLocaleMap","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/serviceAPI"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(serviceAPI:organizationId:developerName:userVerificationRequired:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration\/init(url:userVerificationRequired:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMICoreConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"organizationId","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1organizationId\/title"},{"value":[{"text":"organizationId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1organizationId\/fragments"},{"value":"initWithServiceAPI:organizationId:developerName:userVerificationRequired:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:userVerificationRequired:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithServiceAPI:organizationId:developerName:userVerificationRequired:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:userVerificationRequired:)\/fragments"},{"value":"initWithServiceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithServiceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:remoteLocaleMap:userVerificationRequired:)\/fragments"},{"value":"SMICoreConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"value":"initWithURL:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:)\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithURL:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1isUserVerificationRequired\/title","op":"replace","value":"userVerificationRequired"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1isUserVerificationRequired\/fragments","op":"replace","value":[{"kind":"identifier","text":"userVerificationRequired"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:)\/title","op":"replace","value":"initWithServiceAPI:organizationId:developerName:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(serviceAPI:organizationId:developerName:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithServiceAPI:organizationId:developerName:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1remoteLocaleMap\/title","op":"replace","value":"remoteLocaleMap"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1remoteLocaleMap\/fragments","op":"replace","value":[{"text":"remoteLocaleMap","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1serviceAPI\/title","op":"replace","value":"serviceAPI"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1serviceAPI\/fragments","op":"replace","value":[{"text":"serviceAPI","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:userVerificationRequired:)\/title","op":"replace","value":"initWithURL:userVerificationRequired:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1init(url:userVerificationRequired:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithURL:userVerificationRequired:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1developerName\/title","op":"replace","value":"developerName"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration~1developerName\/fragments","op":"replace","value":[{"text":"developerName","kind":"identifier"}]}]}]}