{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to categorize different types of messages that can appear in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a different kind of message content or interaction that can be displayed to users."}]},{"type":"heading","level":2,"text":"Possible Values","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/staticContent","isActive":true},{"type":"text","text":" - A message containing static content"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choicesResponse"},{"text":" - A message containing a response to a choices prompt","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choices","type":"reference"},{"type":"text","text":" - A message containing a list of choices for the user"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formMessage","isActive":true},{"type":"text","text":" - A message containing an interactive form"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formResponseMessage","type":"reference","isActive":true},{"text":" - A message containing a form submission response","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/unspecified"},{"type":"text","text":" - An unknown or unspecified message type"}]}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationentrymessagetypes"]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Structure","externalID":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","role":"symbol","symbolKind":"struct","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"title":"ConversationEntryMessageTypes"},"sections":[],"abstract":[{"type":"text","text":"An enum that defines the possible types of messages that can appear in a conversation."}],"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choices","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choicesResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/staticContent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/unspecified"],"title":"Type Properties"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/Equatable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/staticContent":{"abstract":[{"type":"text","text":"A message containing static content."}],"role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/staticcontent","title":"staticContent","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/staticContent","navigatorTitle":[{"text":"SMIConversationEntryMessageTypesStaticContent","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"staticContent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/init(rawValue:)":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/init(rawValue:)","role":"symbol","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/choices":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes"}],"title":"choices","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoices"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choices","kind":"symbol","abstract":[{"text":"A message containing a list of choices for the user.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/choices","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes":{"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes","role":"symbol","navigatorTitle":[{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"identifier"}],"title":"ConversationEntryMessageTypes","type":"topic","abstract":[{"text":"An enum that defines the possible types of messages that can appear in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/formMessage":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/formmessage","type":"topic","title":"formMessage","navigatorTitle":[{"text":"SMIConversationEntryMessageTypesFormMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A message containing an interactive form."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formMessage","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/choicesResponse":{"kind":"symbol","title":"choicesResponse","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoicesResponse"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/choicesresponse","abstract":[{"text":"A message containing a response to a choices prompt.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/choicesResponse","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"choicesResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/Equatable-Implementations","kind":"article","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/equatable-implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/formResponseMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/formResponseMessage","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formResponseMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","text":"ConversationEntryMessageTypes"}],"title":"formResponseMessage","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A message containing a form submission response."}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesFormResponseMessage"}],"url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/formresponsemessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryMessageTypes/unspecified":{"title":"unspecified","type":"topic","abstract":[{"type":"text","text":"Represents an unknown or unspecified message type."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryMessageTypes\/unspecified","url":"\/documentation\/smiclientcore\/conversationentrymessagetypes\/unspecified","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesUnspecified"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes","kind":"typeIdentifier","text":"ConversationEntryMessageTypes"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryMessageTypes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIConversationEntryMessageTypes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1staticContent\/title","op":"replace","value":"SMIConversationEntryMessageTypesStaticContent"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1staticContent\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesStaticContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choices\/title","op":"replace","value":"SMIConversationEntryMessageTypesChoices"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choices\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesChoices","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/title","op":"replace","value":"SMIConversationEntryMessageTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryMessageTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formMessage\/title","op":"replace","value":"SMIConversationEntryMessageTypesFormMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formMessage\/fragments","op":"replace","value":[{"text":"SMIConversationEntryMessageTypesFormMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choicesResponse\/title","op":"replace","value":"SMIConversationEntryMessageTypesChoicesResponse"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1choicesResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesChoicesResponse"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formResponseMessage\/title","op":"replace","value":"SMIConversationEntryMessageTypesFormResponseMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1formResponseMessage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesFormResponseMessage"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1unspecified\/title","op":"replace","value":"SMIConversationEntryMessageTypesUnspecified"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryMessageTypes~1unspecified\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryMessageTypesUnspecified"}]}]}]}