{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"languages":["swift"]}]}],"abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"text":"for events using the associated delegate.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"],"title":"Related Documentation","anchor":"Related-Documentation"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/core","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/identifier"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/closeConversation(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/conversation(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create(remoteConfig:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/endSession(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:behaviour:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/fetchLatestVerifiedEntry(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/latestVerifiedEntry(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/removeDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/retrieveTranscript(_:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:message:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(form:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:fileName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(message:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(pdf:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(reply:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendCancel(entry:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendTypingEvent()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/set(sessionContext:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:createConversationOnSubmit:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"externalID":"c:objc(pl)SMIConversationClient","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"ConversationClient"},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclient"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(remoteConfig:createConversationOnSubmit:)":{"role":"symbol","required":true,"title":"submit(remoteConfig:createConversationOnSubmit:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:createconversationonsubmit:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":", ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"submitRemoteConfiguration:createConversationOnSubmit:"}],"abstract":[{"text":"Submits the remote configuration values and starts the conversation if ","type":"text"},{"code":"createConversationOnSubmit","type":"codeVoice"},{"text":" is true.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the SDK stores the pre-chat data until the conversation is created.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:createConversationOnSubmit:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(message:)":{"url":"\/documentation\/smiclientcore\/conversationclient\/send(message:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"send(message:)","abstract":[{"type":"text","text":"Sends a message with the contents of the message parameter."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(message:)","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"sendMessage:"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/closeConversation(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIAPICompletions.h@T@SMICloseConversationCompletion","text":"CloseConversationCompletion"},{"kind":"text","text":")"}],"required":true,"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/closeConversation(completion:)","title":"closeConversation(completion:)","navigatorTitle":[{"kind":"identifier","text":"closeConversationWithCompletion:"}],"role":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/closeconversation(completion:)","abstract":[{"type":"text","text":"Close the current conversation."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(reply:)":{"url":"\/documentation\/smiclientcore\/conversationclient\/send(reply:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Sends a reply to a structured content message."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reply","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AbstractChoice","preciseIdentifier":"c:objc(pl)SMIAbstractChoice","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"send(reply:)","navigatorTitle":[{"text":"sendReply:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(reply:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/removeDelegate(delegate:)":{"url":"\/documentation\/smiclientcore\/conversationclient\/removedelegate(delegate:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClientDelegate","preciseIdentifier":"c:objc(pl)SMIConversationClientDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Removes the delegate to stop receiving events."}],"title":"removeDelegate(delegate:)","kind":"symbol","navigatorTitle":[{"text":"removeDelegate:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/removeDelegate(delegate:)","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/latestVerifiedEntry(completion:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"latestVerifiedEntryWithCompletion:"}],"deprecated":true,"type":"topic","role":"symbol","required":true,"title":"latestVerifiedEntry(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestVerifiedEntry"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","kind":"typeIdentifier","text":"FullQueryCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns the most recent verified entry."},{"type":"text","text":" "},{"type":"text","text":"An entry is considered verified if the entry in the local DB cache has been verified against the conversation transcript in the network service."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/latestVerifiedEntry(completion:)","url":"\/documentation\/smiclientcore\/conversationclient\/latestverifiedentry(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:offset:completion:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"navigatorTitle":[{"text":"entriesWithLimit:offset:completion:","kind":"identifier"}],"title":"entries(withLimit:offset:completion:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:offset:completion:)","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/sendCancel(entry:)":{"title":"sendCancel(entry:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"sendCancelForEntry:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient\/sendcancel(entry:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entry","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendCancel(entry:)","abstract":[{"type":"text","text":"Sends a cancel action referencing a conversation entry."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/identifier":{"url":"\/documentation\/smiclientcore\/conversationclient\/identifier","role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The identifier for the conversation managed by this client."}],"title":"identifier","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/identifier","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:olderThanEntry:completion:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanEntry","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"navigatorTitle":[{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}],"title":"entries(withLimit:olderThanEntry:completion:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:olderthanentry:completion:)","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(pdf:)":{"required":true,"kind":"symbol","role":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(pdf:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pdf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFDocument","text":"PDFDocument","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"sendPDF:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sends an PDF attachment."}],"title":"send(pdf:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(pdf:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)":{"deprecated":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","title":"submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:createconversationonsubmit:)","navigatorTitle":[{"text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","kind":"identifier"}],"abstract":[{"type":"text","text":"Submits collected pre-chat fields and starts the conversation if "},{"type":"codeVoice","code":"createConversationOnSubmit"},{"type":"text","text":" is true."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the SDK stores the pre-chat data until the conversation is created."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"PreChatField","preciseIdentifier":"c:objc(pl)SMIPreChatField","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"hiddenPreChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"createConversationOnSubmit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(completion:)":{"deprecated":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(completion:)","kind":"symbol","title":"entries(completion:)","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"entriesWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"entries"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FullQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/conversationclient\/entries(completion:)","abstract":[{"type":"text","text":"Retrieves messages for this conversation. Only returns the first subset of messages."},{"type":"text","text":" "},{"type":"text","text":"This is a convenience method to make direct database calls for entries associated with this conversation."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/create(remoteConfig:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create(remoteConfig:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a conversation with the remote configuration."}],"navigatorTitle":[{"text":"createConversation:","kind":"identifier"}],"role":"symbol","title":"create(remoteConfig:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/create(remoteconfig:)","required":true,"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(remoteConfig:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(remoteconfig:)","kind":"symbol","navigatorTitle":[{"text":"submitRemoteConfiguration:","kind":"identifier"}],"title":"submit(remoteConfig:)","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Submits the remote configuration values."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"remoteConfig","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RemoteConfiguration","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/conversation(completion:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/conversation(completion:)","abstract":[{"type":"text","text":"Retrieves the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","type":"reference","isActive":true},{"type":"text","text":" matching the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/identifier","isActive":true},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"text":"conversationWithCompletion:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient\/conversation(completion:)","title":"conversation(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SingleConversationQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMISingleConversationQueryCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:fromTimestamp:direction:completion:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:completion:)","title":"entries(withLimit:fromTimestamp:direction:completion:)","required":true,"type":"topic","abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"fromTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?, ","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FullQueryCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIFullQueryCompletion"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"entriesWithLimit:fromTimestamp:direction:completion:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:fromtimestamp:direction:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/core":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Reference to the core object which manages this client."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/core","role":"symbol","title":"core","navigatorTitle":[{"text":"core","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient\/core"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/addDelegate(delegate:queue:)":{"navigatorTitle":[{"text":"addDelegate:queue:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Adds a delegate to listen to ","type":"text"},{"code":"SMIConversationClientDelegate","type":"codeVoice"},{"text":" events.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI.","type":"text"}],"title":"addDelegate(delegate:queue:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationClientDelegate","text":"ConversationClientDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:queue:)","url":"\/documentation\/smiclientcore\/conversationclient\/adddelegate(delegate:queue:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"title":"ConversationClientDelegate","abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate","type":"topic","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:)":{"kind":"symbol","title":"submit(preChatFields:)","deprecated":true,"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"PreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"submitPreChatFields:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:)","abstract":[{"type":"text","text":"Submits collected pre-chat fields and creates a conversation if required."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/retrieveTranscript(_:)":{"navigatorTitle":[{"text":"retrieveTranscript:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Attempt to download a transcript of the converation."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveTranscript","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TranscriptRequestCompletion","preciseIdentifier":"c:SMIConversationRequestCompletion.h@T@SMITranscriptRequestCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/retrieveTranscript(_:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/retrievetranscript(_:)","title":"retrieveTranscript(_:)","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/set(sessionContext:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionContext","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SessionContextProtocol","preciseIdentifier":"c:objc(pl)SMISessionContext","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"setSessionContext:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/set(sessionContext:)","title":"set(sessionContext:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/set(sessioncontext:)","abstract":[{"type":"text","text":"Sets the session context that will be sent with the next message."}],"required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/sendTypingEvent()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendTypingEvent"},{"kind":"text","text":"()"}],"url":"\/documentation\/smiclientcore\/conversationclient\/sendtypingevent()","abstract":[{"type":"text","text":"Attempts to send a typing indicator."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"sendTypingEvent"}],"title":"sendTypingEvent()","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendTypingEvent()"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(form:)":{"required":true,"type":"topic","navigatorTitle":[{"text":"sendForm:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(form:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(form:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"form","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"EntryTypeFormMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sends a filled out Form."}],"title":"send(form:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(image:)":{"navigatorTitle":[{"text":"sendImage:","kind":"identifier"}],"type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Sends an image with the contents of the image parameter."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(image:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"send(image:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(file:fileName:)":{"navigatorTitle":[{"text":"sendFile:fileName:","kind":"identifier"}],"type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Sends a file attachment"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(file:filename:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"send(file:fileName:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/create()":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create()","required":true,"url":"\/documentation\/smiclientcore\/conversationclient\/create()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"()"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"createConversation"}],"role":"symbol","title":"create()","abstract":[{"type":"text","text":"Creates a conversation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(file:fileName:message:)":{"kind":"symbol","title":"send(file:fileName:message:)","navigatorTitle":[{"text":"sendFile:fileName:message:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Sends a file attachment"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:message:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(file:filename:message:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/addDelegate(delegate:)":{"required":true,"url":"\/documentation\/smiclientcore\/conversationclient\/adddelegate(delegate:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Adds a delegate to listener to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"},{"type":"text","text":" events."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClientDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClientDelegate"},{"kind":"text","text":")"}],"title":"addDelegate(delegate:)","navigatorTitle":[{"kind":"identifier","text":"addDelegate:"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/fetchLatestVerifiedEntry(completion:)":{"title":"fetchLatestVerifiedEntry(completion:)","url":"\/documentation\/smiclientcore\/conversationclient\/fetchlatestverifiedentry(completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchLatestVerifiedEntryWithCompletion:"}],"abstract":[{"text":"Returns the most recent verified entry.","type":"text"},{"text":" ","type":"text"},{"text":"An entry is considered verified if the entry in the local DB cache has been verified against the conversation transcript in the network service.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/fetchLatestVerifiedEntry(completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchLatestVerifiedEntry"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMISingleEntryQueryCompletion","text":"SingleEntryQueryCompletion"},{"kind":"text","text":")"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/submit(preChatFields:hiddenPreChatFields:)":{"title":"submit(preChatFields:hiddenPreChatFields:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField","text":"PreChatField"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hiddenPreChatFields"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","text":"HiddenPreChatField"},{"kind":"text","text":"])"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:)","url":"\/documentation\/smiclientcore\/conversationclient\/submit(prechatfields:hiddenprechatfields:)","navigatorTitle":[{"kind":"identifier","text":"submitPreChatFields:hiddenPreChatFields:"}],"deprecated":true,"abstract":[{"type":"text","text":"Submits collected pre-chat fields and creates a conversation if required."}],"type":"topic","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/entries(withLimit:fromTimestamp:direction:behaviour:completion:)":{"kind":"symbol","title":"entries(withLimit:fromTimestamp:direction:behaviour:completion:)","navigatorTitle":[{"text":"entriesWithLimit:fromTimestamp:direction:behaviour:completion:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Retrieves entries for this conversation. This is a convenience method to make direct database calls for entries associated with this conversation."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:behaviour:completion:)","url":"\/documentation\/smiclientcore\/conversationclient\/entries(withlimit:fromtimestamp:direction:behaviour:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entries","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fromTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"behaviour","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QueryBehaviour","preciseIdentifier":"c:@E@SMIQueryBehaviour","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/endSession(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EndSessionCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIAPICompletions.h@T@SMIEndSessionCompletion"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/conversationclient\/endsession(completion:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/endSession(completion:)","kind":"symbol","abstract":[{"type":"text","text":"End the current session."}],"required":true,"navigatorTitle":[{"text":"endSessionWithCompletion:","kind":"identifier"}],"title":"endSession(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient/send(image:fileName:)":{"navigatorTitle":[{"text":"sendImage:fileName:","kind":"identifier"}],"type":"topic","deprecated":true,"required":true,"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Sends an image with the contents of the data parameter."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:fileName:)","url":"\/documentation\/smiclientcore\/conversationclient\/send(image:filename:)","title":"send(image:fileName:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIConversationClient","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/core","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/identifier"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/addDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/closeConversation(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/conversation(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/create(remoteConfig:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/endSession(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:behaviour:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:fromTimestamp:direction:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:offset:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/entries(withLimit:olderThanEntry:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/fetchLatestVerifiedEntry(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/latestVerifiedEntry(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/removeDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/retrieveTranscript(_:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(file:fileName:message:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(form:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(image:fileName:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(message:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(pdf:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/send(reply:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendCancel(entry:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/sendTypingEvent()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/set(sessionContext:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient\/submit(remoteConfig:createConversationOnSubmit:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversationClient"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"submitRemoteConfiguration:createConversationOnSubmit:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:createConversationOnSubmit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"submitRemoteConfiguration:createConversationOnSubmit:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:createConversationOnSubmit:)\/fragments"},{"value":"sendMessage:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(message:)\/fragments"},{"value":"closeConversationWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1closeConversation(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeConversationWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1closeConversation(completion:)\/fragments"},{"value":"sendReply:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(reply:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendReply:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(reply:)\/fragments"},{"value":"removeDelegate:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1removeDelegate(delegate:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1removeDelegate(delegate:)\/fragments"},{"value":"latestVerifiedEntryWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1latestVerifiedEntry(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"latestVerifiedEntryWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1latestVerifiedEntry(completion:)\/fragments"},{"value":"entriesWithLimit:offset:completion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"entriesWithLimit:offset:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:offset:completion:)\/fragments"},{"value":"sendCancelForEntry:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1sendCancel(entry:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendCancelForEntry:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1sendCancel(entry:)\/fragments"},{"value":"SMIConversation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"value":[{"kind":"identifier","text":"SMIConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1identifier\/title"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1identifier\/fragments"},{"value":"entriesWithLimit:olderThanEntry:completion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:olderThanEntry:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:olderThanEntry:completion:)\/fragments"},{"value":"sendPDF:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(pdf:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendPDF:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(pdf:)\/fragments"},{"value":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:hiddenPreChatFields:createConversationOnSubmit:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:createConversationOnSubmit:)\/fragments"},{"value":"entriesWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"entriesWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(completion:)\/fragments"},{"value":"createConversation:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create(remoteConfig:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createConversation:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create(remoteConfig:)\/fragments"},{"value":"submitRemoteConfiguration:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitRemoteConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(remoteConfig:)\/fragments"},{"value":"conversationWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1conversation(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1conversation(completion:)\/fragments"},{"value":"entriesWithLimit:fromTimestamp:direction:completion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:fromTimestamp:direction:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"entriesWithLimit:fromTimestamp:direction:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:fromTimestamp:direction:completion:)\/fragments"},{"value":"core","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1core\/title"},{"value":[{"kind":"identifier","text":"core"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1core\/fragments"},{"value":"addDelegate:queue:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1addDelegate(delegate:queue:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addDelegate:queue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1addDelegate(delegate:queue:)\/fragments"},{"value":"SMIConversationClientDelegate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title"},{"value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments"},{"value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle"},{"value":"SMIConversationClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"},{"value":"submitPreChatFields:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"submitPreChatFields:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:)\/fragments"},{"value":"retrieveTranscript:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1retrieveTranscript(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveTranscript:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1retrieveTranscript(_:)\/fragments"},{"value":"setSessionContext:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1set(sessionContext:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSessionContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1set(sessionContext:)\/fragments"},{"value":"sendTypingEvent","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1sendTypingEvent()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendTypingEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1sendTypingEvent()\/fragments"},{"value":"sendForm:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(form:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendForm:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(form:)\/fragments"},{"value":"sendImage:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(image:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(image:)\/fragments"},{"value":"sendFile:fileName:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(file:fileName:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFile:fileName:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(file:fileName:)\/fragments"},{"value":"createConversation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1create()\/fragments"},{"value":"sendFile:fileName:message:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(file:fileName:message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sendFile:fileName:message:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(file:fileName:message:)\/fragments"},{"value":"addDelegate:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1addDelegate(delegate:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1addDelegate(delegate:)\/fragments"},{"value":"fetchLatestVerifiedEntryWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1fetchLatestVerifiedEntry(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchLatestVerifiedEntryWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1fetchLatestVerifiedEntry(completion:)\/fragments"},{"value":"submitPreChatFields:hiddenPreChatFields:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitPreChatFields:hiddenPreChatFields:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1submit(preChatFields:hiddenPreChatFields:)\/fragments"},{"value":"entriesWithLimit:fromTimestamp:direction:behaviour:completion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:fromTimestamp:direction:behaviour:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"entriesWithLimit:fromTimestamp:direction:behaviour:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1entries(withLimit:fromTimestamp:direction:behaviour:completion:)\/fragments"},{"value":"endSessionWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1endSession(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"endSessionWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1endSession(completion:)\/fragments"},{"value":"sendImage:fileName:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(image:fileName:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendImage:fileName:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient~1send(image:fileName:)\/fragments"}]}]}