{"metadata":{"roleHeading":"Structure","symbolKind":"struct","title":"ConversationFormatTypes","externalID":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationFormatTypes"}]},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/init(rawValue:)"]},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/attachments","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/cancelAction","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/errorMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/experienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/imageMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/inputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/listPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/quickReplies","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/result","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/richLink","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/selections","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/textMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/unspecified","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/webView"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/_SwiftNewtypeWrapper-Implementations"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationFormatTypes"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This enum is used to categorize different types of message formats that can appear in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each format type represents a different way of presenting content to users."}],"type":"paragraph"},{"text":"Possible Values","anchor":"Possible-Values","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/textMessage"},{"type":"text","text":" - A plain text message"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/imageMessage","isActive":true},{"type":"text","text":" - A message containing an image"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/richLink"},{"text":" - A message containing a rich link with preview","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/listPicker"},{"type":"text","text":" - A message containing a list of selectable items"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/quickReplies","type":"reference","isActive":true},{"type":"text","text":" - A message containing quick reply buttons"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/selections","isActive":true,"type":"reference"},{"text":" - A message containing selection options","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/attachments","isActive":true,"type":"reference"},{"text":" - A message containing file attachments","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/carousel","isActive":true},{"type":"text","text":" - A message containing a carousel of items"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/webView","isActive":true},{"type":"text","text":" - A message containing a web view"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/inputs","isActive":true},{"text":" - A message containing form input fields","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/result","isActive":true,"type":"reference"},{"text":" - A message containing form submission results","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/experienceType"},{"type":"text","text":" - A message containing a lightning experience definiton."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/errorMessage","isActive":true,"type":"reference"},{"type":"text","text":" - A message containing an error message definiton."}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/cancelAction","type":"reference","isActive":true},{"type":"text","text":" - A message containing a cancel action."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/unspecified","isActive":true,"type":"reference"},{"text":" - An unknown or unspecified format type","type":"text"}],"type":"paragraph"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationformattypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationformattypes"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An enum that defines the possible formats for messages and content in a conversation.","type":"text"}],"sections":[],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/unspecified":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"SMIConversationFormatTypesUnspecified","kind":"identifier"}],"title":"unspecified","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/unspecified","abstract":[{"type":"text","text":"An unknown or unspecified format type. This applies to certain ephemeral events."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/unspecified"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/cancelAction":{"type":"topic","abstract":[{"type":"text","text":"A message containing a cancel action."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelAction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","kind":"typeIdentifier"}],"title":"cancelAction","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/cancelaction","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/cancelAction","role":"symbol","navigatorTitle":[{"text":"SMIConversationFormatTypesCancelAction","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/quickReplies":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"SMIConversationFormatTypesQuickReplies","kind":"identifier"}],"title":"quickReplies","abstract":[{"type":"text","text":"A message containing quick reply buttons."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/quickReplies","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quickReplies","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/quickreplies"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/richLink":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"richLink","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/richlink","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/richLink","title":"richLink","abstract":[{"type":"text","text":"A message containing a rich link with preview."}],"navigatorTitle":[{"text":"SMIConversationFormatTypesRichLink","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/carousel":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"carousel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/carousel","kind":"symbol","title":"carousel","abstract":[{"type":"text","text":"A message containing a carousel of items."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/carousel","navigatorTitle":[{"text":"SMIConversationFormatTypesCarousel","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/experienceType":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"experienceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}],"abstract":[{"type":"text","text":"A message containing a lightning experience definiton."}],"kind":"symbol","title":"experienceType","type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/experiencetype","navigatorTitle":[{"text":"SMIConversationFormatTypesExperienceType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/experienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/selections":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/selections","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selections","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIConversationFormatTypesSelections","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a message containing selection options."}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/selections","kind":"symbol","title":"selections","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/result":{"title":"result","abstract":[{"type":"text","text":"A message containing form submission results."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationformattypes\/result","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/result","role":"symbol","navigatorTitle":[{"text":"SMIConversationFormatTypesResult","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/inputs":{"abstract":[{"type":"text","text":"A message containing form input fields."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/inputs","type":"topic","role":"symbol","kind":"symbol","title":"inputs","navigatorTitle":[{"text":"SMIConversationFormatTypesInputs","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/inputs","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"kind":"symbol","role":"symbol","type":"topic","title":"ConversationFormatTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationFormatTypes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible formats for messages and content in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationformattypes","navigatorTitle":[{"text":"ConversationFormatTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/textMessage":{"kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/textmessage","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/textMessage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"title":"textMessage","abstract":[{"type":"text","text":"A plain text message."}],"navigatorTitle":[{"text":"SMIConversationFormatTypesTextMessage","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/imageMessage":{"abstract":[{"text":"A message containing an image.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationformattypes\/imagemessage","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"SMIConversationFormatTypesImageMessage","kind":"identifier"}],"role":"symbol","title":"imageMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/imageMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/webView":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/webView","title":"webView","url":"\/documentation\/smiclientcore\/conversationformattypes\/webview","type":"topic","navigatorTitle":[{"text":"SMIConversationFormatTypesWebView","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A message containing a web view."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/attachments":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","text":"ConversationFormatTypes"}],"kind":"symbol","title":"attachments","url":"\/documentation\/smiclientcore\/conversationformattypes\/attachments","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/attachments","abstract":[{"text":"A message containing file attachments.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationFormatTypesAttachments"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/errorMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/errorMessage","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/errormessage","type":"topic","title":"errorMessage","navigatorTitle":[{"text":"SMIConversationFormatTypesErrorMessage","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A message containing an error message definiton."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/conversationformattypes\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/init(rawValue:)","type":"topic","url":"\/documentation\/smiclientcore\/conversationformattypes\/init(rawvalue:)","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/listPicker":{"title":"listPicker","navigatorTitle":[{"text":"SMIConversationFormatTypesListPicker","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/listPicker","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationformattypes\/listpicker","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listPicker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A message containing a list of selectable items."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes/_SwiftNewtypeWrapper-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/smiclientcore\/conversationformattypes\/_swiftnewtypewrapper-implementations","title":"_SwiftNewtypeWrapper Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes\/_SwiftNewtypeWrapper-Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIConversationFormatTypes","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"SMIConversationFormatTypes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIConversationFormatTypesUnspecified","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1unspecified\/title","op":"replace"},{"value":[{"text":"SMIConversationFormatTypesUnspecified","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1unspecified\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesCancelAction","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1cancelAction\/title","op":"replace"},{"value":[{"text":"SMIConversationFormatTypesCancelAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1cancelAction\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesQuickReplies","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1quickReplies\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationFormatTypesQuickReplies"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1quickReplies\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesRichLink","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1richLink\/title","op":"replace"},{"value":[{"text":"SMIConversationFormatTypesRichLink","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1richLink\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesCarousel","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1carousel\/title","op":"replace"},{"value":[{"text":"SMIConversationFormatTypesCarousel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1carousel\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1experienceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationFormatTypesExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1experienceType\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesSelections","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1selections\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationFormatTypesSelections"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1selections\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1result\/title","op":"replace"},{"value":[{"text":"SMIConversationFormatTypesResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1result\/fragments","op":"replace"},{"value":"SMIConversationFormatTypesInputs","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1inputs\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationFormatTypesInputs"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1inputs\/fragments","op":"replace"},{"op":"replace","value":"SMIConversationFormatTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle"},{"op":"replace","value":"SMIConversationFormatTypesTextMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1textMessage\/title"},{"op":"replace","value":[{"text":"SMIConversationFormatTypesTextMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1textMessage\/fragments"},{"op":"replace","value":"SMIConversationFormatTypesImageMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1imageMessage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypesImageMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1imageMessage\/fragments"},{"op":"replace","value":"SMIConversationFormatTypesWebView","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1webView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypesWebView"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1webView\/fragments"},{"op":"replace","value":"SMIConversationFormatTypesAttachments","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1attachments\/title"},{"op":"replace","value":[{"text":"SMIConversationFormatTypesAttachments","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1attachments\/fragments"},{"op":"replace","value":"SMIConversationFormatTypesErrorMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1errorMessage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationFormatTypesErrorMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1errorMessage\/fragments"},{"op":"replace","value":"SMIConversationFormatTypesListPicker","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1listPicker\/title"},{"op":"replace","value":[{"text":"SMIConversationFormatTypesListPicker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes~1listPicker\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}