{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/closed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/open","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/unknown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationStatus"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to track the current state of a conversation. Each status represents","type":"text"},{"text":" ","type":"text"},{"text":"a different stage in the conversation’s lifecycle, from creation through closure.","type":"text"}]}],"kind":"content"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"metadata":{"navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationStatus"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Enumeration","title":"ConversationStatus","externalID":"c:@E@SMIConversationStatus","symbolKind":"enum","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationstatus"]}],"abstract":[{"text":"An enum that defines the possible states of a conversation.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/Equatable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/conversationstatus\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/init(rawValue:)":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/conversationstatus\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/init(rawValue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/closed":{"title":"ConversationStatus.closed","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/closed","abstract":[{"text":"Conversation has closed.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the conversation has been terminated and cannot receive new messages.","type":"text"}],"navigatorTitle":[{"text":"SMIConversationStatusClosed","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationstatus\/closed","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/unknown":{"type":"topic","abstract":[{"type":"text","text":"Unknown conversation status."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the conversation’s state cannot be determined."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/unknown","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationstatus\/unknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"SMIConversationStatusUnknown","kind":"identifier"}],"title":"ConversationStatus.unknown"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus":{"title":"ConversationStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a conversation."}],"url":"\/documentation\/smiclientcore\/conversationstatus","role":"symbol","navigatorTitle":[{"text":"ConversationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationStatus","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/open":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/open","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"open","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SMIConversationStatusOpen","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationstatus\/open","title":"ConversationStatus.open","abstract":[{"type":"text","text":"Conversation is still open."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the conversation is active and can receive messages."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationStatus/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/smiclientcore\/conversationstatus\/rawrepresentable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SMIConversationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIConversationStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIConversationStatus","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/closed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/open","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationStatus\/unknown"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationStatus","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1closed\/title","value":"SMIConversationStatusClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1closed\/fragments","value":[{"text":"SMIConversationStatusClosed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1unknown\/title","value":"SMIConversationStatusUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1unknown\/fragments","value":[{"text":"SMIConversationStatusUnknown","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/title","value":"SMIConversationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/fragments","value":[{"kind":"identifier","text":"SMIConversationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1open\/title","value":"SMIConversationStatusOpen"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationStatus~1open\/fragments","value":[{"text":"SMIConversationStatusOpen","kind":"identifier"}]}]}]}