{"variants":[{"paths":["\/documentation\/smiclientcore\/conversation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeParticipants","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/created","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/developerName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/ended","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/hiddenPreChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/inboundHighWaterMark","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/lastActiveEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/outboundHighWaterMark","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/participants","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatSubmissionTimestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/status","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/supportedModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/termsAndConditions","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/unreadMessageCount"],"anchor":"Instance-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access information about a conversation, including its participants,","type":"text"},{"text":" ","type":"text"},{"text":"messages, status, and configuration.","type":"text"}]}]}],"abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"externalID":"c:objc(pl)SMIConversation","title":"Conversation","modules":[{"name":"SMIClientCore"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/outboundHighWaterMark":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/outboundHighWaterMark","title":"outboundHighWaterMark","navigatorTitle":[{"text":"outboundHighWaterMark","kind":"identifier"}],"abstract":[{"text":"Holds a reference to a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":" representing what has been marked as read by the consuming client."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversation\/outboundhighwatermark","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")?","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/supportedModalities":{"title":"supportedModalities","required":true,"abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"url":"\/documentation\/smiclientcore\/conversation\/supportedmodalities","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/supportedModalities","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"supportedModalities","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/preChatFields":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatFields","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/conversation\/prechatfields","abstract":[{"type":"text","text":"The list of pre-chat fields associated with this conversation."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preChatFields","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","text":"PreChatField","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"preChatFields","kind":"identifier"}],"title":"preChatFields"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/created":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"url":"\/documentation\/smiclientcore\/conversation\/created","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"created"}],"abstract":[{"type":"text","text":"The timestamp when this conversation was created."},{"type":"text","text":" "},{"type":"text","text":"This property indicates when the conversation was first established."}],"title":"created","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/created"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/inboundHighWaterMark":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation\/inboundhighwatermark","title":"inboundHighWaterMark","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/inboundHighWaterMark","navigatorTitle":[{"text":"inboundHighWaterMark","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds a reference to a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" representing what has been marked as read by the remote participant."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"inboundHighWaterMark","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"kind":"text","text":")?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/activeParticipants":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeParticipants"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant","text":"Participant"},{"kind":"text","text":"]"}],"url":"\/documentation\/smiclientcore\/conversation\/activeparticipants","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"activeParticipants","kind":"identifier"}],"abstract":[{"type":"text","text":"The list of currently active participants in this conversation."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to participants who are currently engaged in the conversation."}],"title":"activeParticipants","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeParticipants"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/identifier":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"}],"url":"\/documentation\/smiclientcore\/conversation\/identifier","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier for this conversation."},{"type":"text","text":" "},{"type":"text","text":"This property associates all messages and events with a given conversation."}],"title":"identifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/identifier"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/ended":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/ended","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/conversation\/ended","abstract":[{"type":"text","text":"The timestamp when this conversation was closed"},{"type":"text","text":" "},{"type":"text","text":"This property indicates when the converation was closed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ended"}],"title":"ended"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/termsAndConditions":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation\/termsandconditions","title":"termsAndConditions","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/termsAndConditions","navigatorTitle":[{"text":"termsAndConditions","kind":"identifier"}],"abstract":[{"text":"The terms and conditions associated with this conversation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"termsAndConditions","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMITermsAndConditions","text":"TermsAndConditions","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/preChatSubmissionTimestamp":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatSubmissionTimestamp"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatSubmissionTimestamp","abstract":[{"type":"text","text":"The timestamp when pre-chat information was last submitted."},{"type":"text","text":" "},{"type":"text","text":"This property tracks when the user completed the pre-chat form."}],"url":"\/documentation\/smiclientcore\/conversation\/prechatsubmissiontimestamp","role":"symbol","navigatorTitle":[{"text":"preChatSubmissionTimestamp","kind":"identifier"}],"required":true,"title":"preChatSubmissionTimestamp","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/participants":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participants","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant"},{"text":"]","kind":"text"}],"abstract":[{"text":"The list of all participants in this conversation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"participants"}],"url":"\/documentation\/smiclientcore\/conversation\/participants","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/participants","title":"participants"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/hiddenPreChatFields":{"abstract":[{"type":"text","text":"The list of hidden pre-chat fields associated with this conversation."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/hiddenPreChatFields","navigatorTitle":[{"text":"hiddenPreChatFields","kind":"identifier"}],"title":"hiddenPreChatFields","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversation\/hiddenprechatfields"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"url":"\/documentation\/smiclientcore\/conversation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"title":"Conversation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/status":{"abstract":[{"type":"text","text":"The current status of this conversation."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"title":"status","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SMIConversationStatus","text":"ConversationStatus","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversation\/status"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/unreadMessageCount":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"url":"\/documentation\/smiclientcore\/conversation\/unreadmessagecount","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unreadMessageCount"}],"abstract":[{"type":"text","text":"The number of unread messages in this conversation."},{"type":"text","text":" "},{"type":"text","text":"This property helps track the conversation’s unread state."}],"title":"unreadMessageCount","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/unreadMessageCount"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/activeModalities":{"url":"\/documentation\/smiclientcore\/conversation\/activemodalities","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeModalities","abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeModalities"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"]"}],"required":true,"type":"topic","title":"activeModalities"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/developerName":{"abstract":[{"text":"The API name for the embedded service deployment.","type":"text"},{"text":" ","type":"text"},{"text":"This property identifies the specific service configuration being used.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/developerName","navigatorTitle":[{"kind":"identifier","text":"developerName"}],"title":"developerName","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"developerName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversation\/developername"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation/lastActiveEntry":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation\/lastactiveentry","title":"lastActiveEntry","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/lastActiveEntry","navigatorTitle":[{"text":"lastActiveEntry","kind":"identifier"}],"abstract":[{"type":"text","text":"The last conversation entry that represents user activity."},{"type":"text","text":" "},{"type":"text","text":"This property helps track the most recent interaction in the conversation."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastActiveEntry"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")?"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIConversation","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/activeParticipants","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/created","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/developerName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/ended","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/hiddenPreChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/inboundHighWaterMark","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/lastActiveEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/outboundHighWaterMark","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/participants","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/preChatSubmissionTimestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/status","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/supportedModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/termsAndConditions","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation\/unreadMessageCount"],"title":"Instance Properties"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIConversation"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"outboundHighWaterMark","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1outboundHighWaterMark\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1outboundHighWaterMark\/fragments","value":[{"text":"outboundHighWaterMark","kind":"identifier"}],"op":"replace"},{"value":"supportedModalities","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1supportedModalities\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1supportedModalities\/fragments","value":[{"kind":"identifier","text":"supportedModalities"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1preChatFields\/title","value":"preChatFields","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"preChatFields"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1preChatFields\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1created\/title","value":"created"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1created\/fragments","value":[{"kind":"identifier","text":"created"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1inboundHighWaterMark\/title","value":"inboundHighWaterMark","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1inboundHighWaterMark\/fragments","value":[{"text":"inboundHighWaterMark","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeParticipants\/title","op":"replace","value":"activeParticipants"},{"value":[{"text":"activeParticipants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeParticipants\/fragments"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1identifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1identifier\/fragments"},{"op":"replace","value":"ended","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1ended\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1ended\/fragments","value":[{"kind":"identifier","text":"ended"}],"op":"replace"},{"op":"replace","value":"termsAndConditions","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1termsAndConditions\/title"},{"op":"replace","value":[{"text":"termsAndConditions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1termsAndConditions\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1preChatSubmissionTimestamp\/title","value":"preChatSubmissionTimestamp","op":"replace"},{"value":[{"kind":"identifier","text":"preChatSubmissionTimestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1preChatSubmissionTimestamp\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1participants\/title","value":"participants","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1participants\/fragments","value":[{"text":"participants","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1hiddenPreChatFields\/title","value":"hiddenPreChatFields"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1hiddenPreChatFields\/fragments","value":[{"text":"hiddenPreChatFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"text":"SMIConversation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"text":"SMIConversation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1status\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1unreadMessageCount\/title","value":"unreadMessageCount"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1unreadMessageCount\/fragments","value":[{"text":"unreadMessageCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeModalities\/title","value":"activeModalities"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1activeModalities\/fragments","value":[{"kind":"identifier","text":"activeModalities"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1developerName\/title","value":"developerName"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1developerName\/fragments","value":[{"kind":"identifier","text":"developerName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1lastActiveEntry\/title","value":"lastActiveEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation~1lastActiveEntry\/fragments","value":[{"text":"lastActiveEntry","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}