{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didCreateConversation:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didError:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceive:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEntries:paged:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEvents:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStartedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStoppedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-6sox3","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-jlte","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateActiveParticipants:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateUnreadMessageCount:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"],"anchor":"Related-Documentation","title":"Related Documentation"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"This protocol provides a set of callbacks for monitoring and responding to events"},{"type":"text","text":" "},{"type":"text","text":"in a specific conversation, including message delivery, typing indicators,"},{"type":"text","text":" "},{"type":"text","text":"participant changes, and error conditions."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClientDelegate"}],"navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"externalID":"c:objc(pl)SMIConversationClientDelegate","role":"symbol","title":"ConversationClientDelegate","roleHeading":"Protocol","symbolKind":"protocol"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveTypingStoppedEvent:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStoppedEvent:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didReceiveTypingStoppedEvent","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")","kind":"text"}],"title":"client(_:didReceiveTypingStoppedEvent:)","kind":"symbol","abstract":[{"text":"Delegate event that is triggered when receiving a typing stopped event from another participant.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"client:didReceiveTypingStoppedEvent:","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceivetypingstoppedevent:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateEntries:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)","navigatorTitle":[{"kind":"identifier","text":"client:didUpdateEntries:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateEntries"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateentries:)","title":"client(_:didUpdateEntries:)","abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"kind":"symbol","title":"ConversationClientDelegate","abstract":[{"text":"Delegate that handles events related to a conversation.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveEvents:)":{"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceiveevents:)","kind":"symbol","role":"symbol","title":"client(_:didReceiveEvents:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveEvents","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[{"text":"Delgate event that is triggered when receiving a conversation event.","type":"text"},{"text":" ","type":"text"},{"text":"A conversation event is a ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" that is not saved to the conversation transcipt.","type":"text"},{"text":" ","type":"text"},{"text":"These events are primarily focused on converying information that is temporary, like typing indicators etc.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEvents:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"client:didReceiveEvents:"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"type":"topic","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"url":"\/documentation\/smiclientcore\/conversationclient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdate:)-6sox3":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-6sox3","navigatorTitle":[{"text":"client:didUpdateConversation:","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when the conversation is updated."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"client(_:didUpdate:)","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdate:)-6sox3"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveEntries:paged:)":{"role":"symbol","navigatorTitle":[{"text":"client:didReceiveEntries:paged:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Delegate event that is triggered when entries have been added to a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"This fires for both inbound and outbound entries.","type":"text"}],"title":"client(_:didReceiveEntries:paged:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveEntries","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"paged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEntries:paged:)","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceiveentries:paged:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didCreateConversation:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didCreateConversation:)","title":"client(_:didCreateConversation:)","navigatorTitle":[{"kind":"identifier","text":"client:didCreateConversation:"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didcreateconversation:)","abstract":[{"text":"Delegate event that is triggered by the creation of a conversation for the conversationId associated with the client.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateConversation"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveTypingStartedEvent:)":{"title":"client(_:didReceiveTypingStartedEvent:)","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceivetypingstartedevent:)","navigatorTitle":[{"kind":"identifier","text":"client:didReceiveTypingStartedEvent:"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTypingStartedEvent"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")"}],"abstract":[{"text":"Delegate event that is triggered when receiving a typing started event from another participant.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStartedEvent:)","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateActiveParticipants:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateActiveParticipants:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didUpdateActiveParticipants","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when the active participants on a conversation have changed."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateactiveparticipants:)","navigatorTitle":[{"text":"client:didUpdateActiveParticipants:","kind":"identifier"}],"title":"client(_:didUpdateActiveParticipants:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdate:)-jlte":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-jlte","navigatorTitle":[{"text":"client:didUpdateEntry:","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdate:)-jlte","abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"title":"client(_:didUpdate:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceive:)":{"type":"topic","deprecated":true,"role":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceive:)","abstract":[{"type":"text","text":"Delegate event that is triggered when an entry has been added to a conversation."},{"type":"text","text":" "},{"type":"text","text":"This fires for both inbound and outbound entries."}],"title":"client(_:didReceive:)","kind":"symbol","navigatorTitle":[{"text":"client:didReceiveEntry:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateUnreadMessageCount:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"client:didUpdateUnreadMessageCount:"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateunreadmessagecount:)","role":"symbol","kind":"symbol","title":"client(_:didUpdateUnreadMessageCount:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateUnreadMessageCount:)","abstract":[{"type":"text","text":"Delegate event that is triggered when the unread message counter is updated"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateUnreadMessageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didError:)":{"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:diderror:)","abstract":[{"type":"text","text":"Delegate event that is triggered if an unhandled error is detected as part"},{"type":"text","text":" "},{"type":"text","text":"of the normal activity of the In-App Messaging client."}],"kind":"symbol","title":"client(_:didError:)","navigatorTitle":[{"text":"client:didError:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationClientDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didCreateConversation:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didError:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceive:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEntries:paged:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEvents:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStartedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStoppedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-6sox3","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-jlte","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateActiveParticipants:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateUnreadMessageCount:)"],"generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"],"anchor":"Related-Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIConversationClientDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStoppedEvent:)\/title","op":"replace","value":"client:didReceiveTypingStoppedEvent:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStoppedEvent:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveTypingStoppedEvent:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateEntries:)\/title","op":"replace","value":"client:didUpdateEntries:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateEntries:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateEntries:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","op":"replace","value":"SMIConversationClientDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEvents:)\/title","op":"replace","value":"client:didReceiveEvents:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEvents:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveEvents:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-6sox3\/title","op":"replace","value":"client:didUpdateConversation:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-6sox3\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateConversation:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEntries:paged:)\/title","op":"replace","value":"client:didReceiveEntries:paged:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEntries:paged:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveEntries:paged:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didCreateConversation:)\/title","op":"replace","value":"client:didCreateConversation:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didCreateConversation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didCreateConversation:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStartedEvent:)\/title","op":"replace","value":"client:didReceiveTypingStartedEvent:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStartedEvent:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveTypingStartedEvent:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateActiveParticipants:)\/title","op":"replace","value":"client:didUpdateActiveParticipants:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateActiveParticipants:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateActiveParticipants:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-jlte\/title","op":"replace","value":"client:didUpdateEntry:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-jlte\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateEntry:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceive:)\/title","op":"replace","value":"client:didReceiveEntry:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceive:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveEntry:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateUnreadMessageCount:)\/title","op":"replace","value":"client:didUpdateUnreadMessageCount:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateUnreadMessageCount:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didUpdateUnreadMessageCount:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didError:)\/title","op":"replace","value":"client:didError:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}