{"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/attachmentError","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/delivered","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/read","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sending","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sent"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/Equatable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryStatus"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"This enum is used to track the lifecycle of messages in a conversation, from initial creation","type":"text"},{"text":" ","type":"text"},{"text":"through delivery and read status. Each status represents a different stage in the message’s journey.","type":"text"}],"type":"paragraph"},{"anchor":"Possible-Values","text":"Possible Values","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","type":"reference"},{"text":" - There was some form of error when sending a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sending"},{"type":"text","text":" - The initial state of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" when created"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sent","isActive":true},{"text":" - The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"text":" has been confirmed to have been received by the messaging service","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/delivered","type":"reference","isActive":true},{"type":"text","text":" - The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":" is confirmed to have been delivered to the other participant’s client"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/read"},{"type":"text","text":" - The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" is confirmed to have been read by the other participant"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/attachmentError"},{"type":"text","text":" - The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" has failed when sent to a bot"}]}]}]}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEntryStatus"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"struct","externalID":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","title":"ConversationEntryStatus","roleHeading":"Structure","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An enum that defines the possible statuses of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationentrystatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationentrystatus"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/sending":{"role":"symbol","title":"sending","url":"\/documentation\/smiclientcore\/conversationentrystatus\/sending","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sending"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","text":"ConversationEntryStatus"}],"abstract":[{"text":"The initial state of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" when created.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sending","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryStatusSending"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/read":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/read","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" is confirmed to have been read by the other participant."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryStatusRead"}],"role":"symbol","title":"read","kind":"symbol","url":"\/documentation\/smiclientcore\/conversationentrystatus\/read"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/conversationentrystatus\/equatable-implementations","type":"topic","title":"Equatable Implementations","kind":"article"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/init(rawValue:)":{"abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/init(rawValue:)","url":"\/documentation\/smiclientcore\/conversationentrystatus\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/delivered":{"abstract":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":" is confirmed to have been delivered to the other participant’s client.","type":"text"}],"title":"delivered","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/delivered","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/conversationentrystatus\/delivered","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delivered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"SMIConversationEntryStatusDelivered","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/sent":{"role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrystatus\/sent","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/sent","kind":"symbol","title":"sent","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","text":"ConversationEntryStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" has been confirmed to have been received by the messaging service."}],"navigatorTitle":[{"text":"SMIConversationEntryStatusSent","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/error":{"type":"topic","navigatorTitle":[{"text":"SMIConversationEntryStatusError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","title":"error","url":"\/documentation\/smiclientcore\/conversationentrystatus\/error","abstract":[{"type":"text","text":"There was some form of error when sending a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/attachmentError":{"role":"symbol","deprecated":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/conversationentrystatus\/attachmenterror","abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" has failed when sent to a bot."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/attachmentError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus","text":"ConversationEntryStatus"}],"title":"attachmentError","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryStatusAttachmentError"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus":{"title":"ConversationEntryStatus","abstract":[{"type":"text","text":"An enum that defines the possible statuses of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/conversationentrystatus","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus","navigatorTitle":[{"text":"ConversationEntryStatus","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryStatus"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIConversationEntryStatus"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1sending\/title","op":"replace","value":"SMIConversationEntryStatusSending"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1sending\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusSending","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1read\/title","op":"replace","value":"SMIConversationEntryStatusRead"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1read\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusRead","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1delivered\/title","op":"replace","value":"SMIConversationEntryStatusDelivered"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1delivered\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryStatusDelivered"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1sent\/title","op":"replace","value":"SMIConversationEntryStatusSent"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1sent\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusSent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1error\/title","op":"replace","value":"SMIConversationEntryStatusError"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1error\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1attachmentError\/title","op":"replace","value":"SMIConversationEntryStatusAttachmentError"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1attachmentError\/fragments","op":"replace","value":[{"text":"SMIConversationEntryStatusAttachmentError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/title","op":"replace","value":"SMIConversationEntryStatus"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryStatus"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryStatus"}]}]}]}