{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ConversationEntryTypes"}],"role":"symbol","roleHeading":"Structure","symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntryTypes"}],"externalID":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","modules":[{"name":"SMIClientCore"}],"title":"ConversationEntryTypes"},"sections":[],"abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/choice","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/closeConversation","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/conversationUpdated","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/deliveryAck","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/messageUpdated","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/modalityConnection","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/participantChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/progressIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/queuePosition","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/readAck","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/richMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingWorkResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/selection","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionStatusChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/streamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/typingIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/unknown"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/Equatable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationEntryTypes"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Possible-Values","text":"Possible Values","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/typingIndicator","type":"reference"},{"text":" - Indicates that a participant is currently typing","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/progressIndicator"},{"text":" - Shows progress of an ongoing operation","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/streamingToken"},{"text":" - Represents a streaming token for real-time updates","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/message","isActive":true,"type":"reference"},{"text":" - A standard text or media message","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/choice","isActive":true,"type":"reference"},{"text":" - A message containing interactive choice options","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/selection","type":"reference","isActive":true},{"text":" - A message containing selection options","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/participantChanged","isActive":true},{"type":"text","text":" - Indicates a change in conversation participants"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/readAck"},{"type":"text","text":" - Acknowledges that a message has been read"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/deliveryAck","type":"reference"},{"text":" - Acknowledges that a message has been delivered","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/richMessage","type":"reference"},{"text":" - A message containing rich media or interactive content","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingWorkResult","type":"reference","isActive":true},{"text":" - Result of a routing work operation","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingResult","isActive":true},{"type":"text","text":" - Result of a routing operation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/closeConversation","type":"reference","isActive":true},{"type":"text","text":" - Indicates a conversation has been closed"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/conversationUpdated","type":"reference","isActive":true},{"type":"text","text":" - Describes a conversation state update"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/unknown","type":"reference","isActive":true},{"type":"text","text":" - An unknown or unspecified message type"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"This enum is used to categorize different types of entries that can appear in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a different kind of interaction or message that can be displayed to users."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationentrytypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationentrytypes"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/selection":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/selection","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesSelection","kind":"identifier"}],"abstract":[{"text":"Represents a message containing selection options.","type":"text"}],"title":"selection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/selection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/modalityConnection":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/modalityconnection","abstract":[{"text":"Describes connection details for a service supporting a given modality.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/modalityConnection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesModalityConnection"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalityConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes"}],"type":"topic","title":"modalityConnection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/choice":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/choice","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesChoice","kind":"identifier"}],"abstract":[{"text":"Represents a  message containing interactive choice options.","type":"text"}],"title":"choice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/choice"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/message":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/message","title":"message","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/message","navigatorTitle":[{"text":"SMIConversationEntryTypesMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a standard text or media message."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/participantChanged":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/participantChanged","title":"participantChanged","navigatorTitle":[{"text":"SMIConversationEntryTypesParticipantChanged","kind":"identifier"}],"abstract":[{"text":"Indicates a change in conversation participants.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/participantchanged","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participantChanged","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/streamingToken":{"abstract":[{"type":"text","text":"Represents a streaming token for real-time updates."}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesStreamingToken"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/streamingToken","title":"streamingToken","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamingToken"},{"kind":"text","text":": "},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrytypes\/streamingtoken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/Equatable-Implementations":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/richMessage":{"title":"richMessage","abstract":[{"text":"Represents a message containing rich media or interactive content.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/richmessage","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/richMessage","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"richMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesRichMessage"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/init(rawValue:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/conversationUpdated":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/conversationUpdated","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrytypes\/conversationupdated","abstract":[{"text":"Describes a conversation state update.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationUpdated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesConversationUpdated"}],"title":"conversationUpdated"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/sessionContext":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/sessioncontext","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesSessionContext","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a SessionContext"}],"title":"sessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionContext"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes","title":"ConversationEntryTypes","navigatorTitle":[{"text":"ConversationEntryTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of known entries that can appear in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntryTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/closeConversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/closeconversation","title":"closeConversation","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/closeConversation","navigatorTitle":[{"text":"SMIConversationEntryTypesCloseConversation","kind":"identifier"}],"abstract":[{"text":"Describes a Close Conversation type.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeConversation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/routingWorkResult":{"abstract":[{"text":"Result of a routing work operation.","type":"text"}],"navigatorTitle":[{"text":"SMIConversationEntryTypesRoutingWorkResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingWorkResult","title":"routingWorkResult","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"routingWorkResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrytypes\/routingworkresult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/messageUpdated":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/messageupdated","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/messageUpdated","abstract":[{"type":"text","text":"Indicates that a message has been updated."}],"role":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesMessageUpdated","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageUpdated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"type":"topic","title":"messageUpdated"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/typingIndicator":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"typingIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/typingindicator","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesTypingIndicator"}],"abstract":[{"type":"text","text":"Indicates that a participant is currently typing."}],"title":"typingIndicator","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/typingIndicator"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/progressIndicator":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/progressIndicator","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrytypes\/progressindicator","abstract":[{"type":"text","text":"Shows progress of an ongoing operation."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesProgressIndicator","kind":"identifier"}],"title":"progressIndicator"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/deliveryAck":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/deliveryack","abstract":[{"text":"Acknowledges that a message has been delivered.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/deliveryAck","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesDeliveryAck"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryAck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"type":"topic","title":"deliveryAck"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/readAck":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/readack","title":"readAck","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/readAck","navigatorTitle":[{"text":"SMIConversationEntryTypesReadAck","kind":"identifier"}],"abstract":[{"type":"text","text":"Acknowledges that a message has been read."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readAck","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/queuePosition":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/queueposition","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/queuePosition","abstract":[{"text":"Describes a Queue Position type.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesQueuePosition","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"type":"topic","title":"queuePosition"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/routingResult":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/routingresult","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesRoutingResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of a routing operation."}],"title":"routingResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/routingResult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/sessionStatusChanged":{"url":"\/documentation\/smiclientcore\/conversationentrytypes\/sessionstatuschanged","abstract":[{"text":"Indicates a session status change.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/sessionStatusChanged","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryTypesSessionStatusChanged"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStatusChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","text":"ConversationEntryTypes"}],"type":"topic","title":"sessionStatusChanged"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/unknown":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/conversationentrytypes\/unknown","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIConversationEntryTypesUnknown","kind":"identifier"}],"abstract":[{"text":"Describes a unknown or unspecified message type.","type":"text"}],"title":"unknown","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/unknown"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIConversationEntryTypes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntryTypes","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIConversationEntryTypes"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SMIConversationEntryTypesSelection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1selection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesSelection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1selection\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesModalityConnection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1modalityConnection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesModalityConnection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1modalityConnection\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesChoice","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1choice\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryTypesChoice","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1choice\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1message\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1message\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesParticipantChanged","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1participantChanged\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryTypesParticipantChanged","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1participantChanged\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1streamingToken\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesStreamingToken"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1streamingToken\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesRichMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1richMessage\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryTypesRichMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1richMessage\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesConversationUpdated","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1conversationUpdated\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryTypesConversationUpdated","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1conversationUpdated\/fragments","op":"replace"},{"value":"SMIConversationEntryTypesSessionContext","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionContext\/title","op":"replace"},{"value":[{"text":"SMIConversationEntryTypesSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionContext\/fragments","op":"replace"},{"value":"SMIConversationEntryTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntryTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1closeConversation\/title","value":"SMIConversationEntryTypesCloseConversation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1closeConversation\/fragments","value":[{"text":"SMIConversationEntryTypesCloseConversation","kind":"identifier"}],"op":"replace"},{"value":"SMIConversationEntryTypesRoutingWorkResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingWorkResult\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesRoutingWorkResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingWorkResult\/fragments"},{"value":"SMIConversationEntryTypesMessageUpdated","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1messageUpdated\/title"},{"value":[{"text":"SMIConversationEntryTypesMessageUpdated","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1messageUpdated\/fragments"},{"value":"SMIConversationEntryTypesTypingIndicator","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1typingIndicator\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesTypingIndicator"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1typingIndicator\/fragments"},{"value":"SMIConversationEntryTypesProgressIndicator","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1progressIndicator\/title"},{"value":[{"text":"SMIConversationEntryTypesProgressIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1progressIndicator\/fragments"},{"value":"SMIConversationEntryTypesDeliveryAck","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1deliveryAck\/title"},{"value":[{"text":"SMIConversationEntryTypesDeliveryAck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1deliveryAck\/fragments"},{"value":"SMIConversationEntryTypesReadAck","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1readAck\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesReadAck"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1readAck\/fragments"},{"value":"SMIConversationEntryTypesQueuePosition","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1queuePosition\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesQueuePosition"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1queuePosition\/fragments"},{"value":"SMIConversationEntryTypesRoutingResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingResult\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesRoutingResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1routingResult\/fragments"},{"value":"SMIConversationEntryTypesSessionStatusChanged","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionStatusChanged\/title"},{"value":[{"kind":"identifier","text":"SMIConversationEntryTypesSessionStatusChanged"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1sessionStatusChanged\/fragments"},{"value":"SMIConversationEntryTypesUnknown","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1unknown\/title"},{"value":[{"text":"SMIConversationEntryTypesUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1unknown\/fragments"}]}]}