{"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"title":"CoreDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}],"externalID":"c:objc(pl)SMICoreDelegate","role":"symbol"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEntries:paged:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEvents:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateActiveParticipants:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateUnreadMessageCount:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeConnectionState:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeNetworkState:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didCreateConversation:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didError:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceive:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStartedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStoppedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-5msg3","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-741b8"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/coredelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coredelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate used to receive events for the "},{"type":"codeVoice","code":"SMICoreClient"},{"type":"text","text":" framework. Use this protocol to listen"},{"type":"text","text":" "},{"type":"text","text":"for chat messages, receive message status changes, detect network status changes, and receive error messages."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol provides a comprehensive set of callbacks for monitoring and responding to"},{"type":"text","text":" "},{"type":"text","text":"various events in the In-App Messaging system, including message delivery, typing indicators,"},{"type":"text","text":" "},{"type":"text","text":"network state changes, and error conditions."}]}],"kind":"content"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didReceive:)":{"deprecated":true,"title":"core(_:didReceive:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didreceive:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceive:)","navigatorTitle":[{"text":"core:didReceiveEntry:","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when an entry has been added to a conversation."},{"type":"text","text":" "},{"type":"text","text":"This fires for both inbound and outbound entries."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didUpdateActiveParticipants:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateActiveParticipants"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIParticipant","kind":"typeIdentifier","text":"Participant"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when the active participants on a conversation have changed."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateActiveParticipants:)","navigatorTitle":[{"text":"core:conversation:didUpdateActiveParticipants:","kind":"identifier"}],"title":"core(_:conversation:didUpdateActiveParticipants:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didupdateactiveparticipants:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didCreateConversation:)":{"title":"core(_:didCreateConversation:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didcreateconversation:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didCreateConversation:)","navigatorTitle":[{"text":"core:didCreateConversation:","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate event that is triggered if an unhandled error is detected as part"},{"type":"text","text":" "},{"type":"text","text":"of the normal activity of the In-App Messaging client."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"didCreateConversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didReceiveEntries:paged:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveEntries"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"paged"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEntries:paged:)","title":"core(_:conversation:didReceiveEntries:paged:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didreceiveentries:paged:)","role":"symbol","abstract":[{"type":"text","text":"Delegate event that is triggered when entries have been added to a conversation."},{"type":"text","text":" "},{"type":"text","text":"This fires for both inbound and outbound entries."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:conversation:didReceiveEntries:paged:"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didUpdateUnreadMessageCount:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateUnreadMessageCount:)","abstract":[{"type":"text","text":"Delegate event that is triggered when the unread message counter is updated."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateUnreadMessageCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"core(_:conversation:didUpdateUnreadMessageCount:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:conversation:didUpdateUnreadMessageCount:"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didupdateunreadmessagecount:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Delegate used to receive events for the "},{"code":"SMICoreClient","type":"codeVoice"},{"type":"text","text":" framework. Use this protocol to listen"},{"type":"text","text":" "},{"type":"text","text":"for chat messages, receive message status changes, detect network status changes, and receive error messages."}],"role":"symbol","kind":"symbol","title":"CoreDelegate","url":"\/documentation\/smiclientcore\/coredelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didUpdate:)-5msg3":{"abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-5msg3","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"core:didUpdateEntry:","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didupdate:)-5msg3","title":"core(_:didUpdate:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didReceiveTypingStartedEvent:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStartedEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTypingStartedEvent"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didreceivetypingstartedevent:)","type":"topic","kind":"symbol","abstract":[{"text":"Delegate event that is triggered when receiving a typing started event from another participant.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"core:didReceiveTypingStartedEvent:"}],"role":"symbol","title":"core(_:didReceiveTypingStartedEvent:)","deprecated":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/addDelegate(delegate:)":{"role":"symbol","abstract":[{"text":"Adds a delegate to listen to ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","isActive":true,"type":"reference"},{"text":" events.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"CoreDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreDelegate"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)","kind":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/adddelegate(delegate:)","navigatorTitle":[{"text":"addDelegate:","kind":"identifier"}],"title":"addDelegate(delegate:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didReceiveEvents:)":{"title":"core(_:conversation:didReceiveEvents:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEvents:)","abstract":[{"type":"text","text":"Delegate event that is triggered when receiving a conversation events."},{"type":"text","text":" "},{"type":"text","text":"A conversation event is a "},{"code":"SMIConversationEntry","type":"codeVoice"},{"type":"text","text":" that is not saved to the conversation transcript."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversation","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveEvents","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didreceiveevents:)","kind":"symbol","navigatorTitle":[{"text":"core:conversation:didReceiveEvents:","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didChangeNetworkState:)":{"navigatorTitle":[{"text":"core:didChangeNetworkState:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeNetworkState:)","kind":"symbol","title":"core(_:didChangeNetworkState:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"didChangeNetworkState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didchangenetworkstate:)","abstract":[{"text":"Delegate event that is triggered by a change in the status of the network.","type":"text"},{"text":" ","type":"text"},{"text":"Based on the status change, you can decide how to convey","type":"text"},{"text":" ","type":"text"},{"text":"this information to the UI.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didError:)":{"abstract":[{"type":"text","text":"Delegate event that is triggered if an unhandled error is detected as part"},{"type":"text","text":" "},{"type":"text","text":"of the normal activity of the In-App Messaging client."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didError"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:didError:"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:diderror:)","title":"core(_:didError:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didUpdate:)-741b8":{"url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didupdate:)-741b8","navigatorTitle":[{"text":"core:didUpdateConversation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":")","kind":"text"}],"title":"core(_:didUpdate:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-741b8","kind":"symbol","abstract":[{"type":"text","text":"Delegate event that is triggered when the conversation is updated."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didReceiveTypingStoppedEvent:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"core:didReceiveTypingStoppedEvent:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTypingStoppedEvent"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry"},{"kind":"text","text":")"}],"deprecated":true,"title":"core(_:didReceiveTypingStoppedEvent:)","abstract":[{"text":"Delegate event that is triggered when receiving a typing stopped event from another participant.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStoppedEvent:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didreceivetypingstoppedevent:)"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:conversation:didUpdateEntries:)":{"navigatorTitle":[{"kind":"identifier","text":"core:conversation:didUpdateEntries:"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:conversation:didupdateentries:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversation"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateEntries"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","title":"core(_:conversation:didUpdateEntries:)","abstract":[{"text":"Delegate event that is triggered when a message’s status has been updated.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that any current references to an entry with a matching ID are refreshed.","type":"text"},{"text":" ","type":"text"},{"text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI","type":"text"},{"text":" ","type":"text"},{"text":"should account for that.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/addDelegate(delegate:queue:)":{"title":"addDelegate(delegate:queue:)","url":"\/documentation\/smiclientcore\/coreclient\/adddelegate(delegate:queue:)","kind":"symbol","abstract":[{"text":"Adds a delegate to listen to ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","isActive":true,"type":"reference"},{"text":" events.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"addDelegate:queue:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"CoreDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreDelegate"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate/core(_:didChangeConnectionState:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Delegate event that is triggered by a change in the connection state of the realtime event handler."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"},{"kind":"text","text":")"}],"title":"core(_:didChangeConnectionState:)","url":"\/documentation\/smiclientcore\/coredelegate\/core(_:didchangeconnectionstate:)","navigatorTitle":[{"kind":"identifier","text":"core:didChangeConnectionState:"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeConnectionState:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMICoreDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMICoreDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMICoreDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEntries:paged:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didReceiveEvents:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateActiveParticipants:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateEntries:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:conversation:didUpdateUnreadMessageCount:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeConnectionState:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didChangeNetworkState:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didCreateConversation:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didError:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceive:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStartedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didReceiveTypingStoppedEvent:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-5msg3","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate\/core(_:didUpdate:)-741b8"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)"],"title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMICoreDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceive:)\/title","value":"core:didReceiveEntry:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didReceiveEntry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateActiveParticipants:)\/title","value":"core:conversation:didUpdateActiveParticipants:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateActiveParticipants:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:conversation:didUpdateActiveParticipants:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didCreateConversation:)\/title","value":"core:didCreateConversation:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didCreateConversation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didCreateConversation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEntries:paged:)\/title","value":"core:conversation:didReceiveEntries:paged:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEntries:paged:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:conversation:didReceiveEntries:paged:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateUnreadMessageCount:)\/title","value":"core:conversation:didUpdateUnreadMessageCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateUnreadMessageCount:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:conversation:didUpdateUnreadMessageCount:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/title","value":"SMICoreDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/fragments","value":[{"text":"SMICoreDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/navigatorTitle","value":[{"text":"SMICoreDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-5msg3\/title","value":"core:didUpdateEntry:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-5msg3\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didUpdateEntry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceiveTypingStartedEvent:)\/title","value":"core:didReceiveTypingStartedEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceiveTypingStartedEvent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didReceiveTypingStartedEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:)\/title","value":"addDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEvents:)\/title","value":"core:conversation:didReceiveEvents:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didReceiveEvents:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:conversation:didReceiveEvents:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didChangeNetworkState:)\/title","value":"core:didChangeNetworkState:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didChangeNetworkState:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:didChangeNetworkState:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didError:)\/title","value":"core:didError:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-741b8\/title","value":"core:didUpdateConversation:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didUpdate:)-741b8\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didUpdateConversation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceiveTypingStoppedEvent:)\/title","value":"core:didReceiveTypingStoppedEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didReceiveTypingStoppedEvent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:didReceiveTypingStoppedEvent:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateEntries:)\/title","value":"core:conversation:didUpdateEntries:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:conversation:didUpdateEntries:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:conversation:didUpdateEntries:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:queue:)\/title","value":"addDelegate:queue:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:queue:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addDelegate:queue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didChangeConnectionState:)\/title","value":"core:didChangeConnectionState:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate~1core(_:didChangeConnectionState:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:didChangeConnectionState:","kind":"identifier"}]}]}]}