{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient"]},{"paths":["\/documentation\/smiclientcore\/coreclient"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","interfaceLanguage":"swift"},"metadata":{"title":"CoreClient","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreClient"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"role":"symbol","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMICoreClient"},"abstract":[{"type":"text","text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and provide an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"text":".","type":"text"}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/configuration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/multimediaClient","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/preChatDelegate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/salesforceAuthenticationRequestPath","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/state","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/templatedUrlDelegate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/closeConversation(withIdentifier:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversationClient(with:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:forceRefresh:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:sortedByActivityDirection:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/deregisterDevice(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage(andAuthorization:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/markAsRead(entry:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/register(deviceToken:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/removeDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveBusinessHours(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveRemoteConfiguration(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:preChatFields:hiddenPreChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(entry:remoteConfiguration:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeToken(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeTokenAndDeregisterDevice(_:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setPreChatDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setTemplatedUrlDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setUserVerificationDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/start()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/stop()"],"anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreClient"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"],"title":"Related Documentation"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/deregisterDevice(completion:)":{"abstract":[{"type":"text","text":"De-registers the device from receiving push notifications."},{"type":"text","text":" "},{"type":"text","text":"After this command has been executed, to receive push notifications again, the device will need to be registered again by calling"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/provide(deviceToken:)","isActive":true},{"type":"text","text":" on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":".","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/deregisterDevice(completion:)","navigatorTitle":[{"kind":"identifier","text":"deregisterDeviceWithCompletion:"}],"title":"deregisterDevice(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregisterDevice"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/deregisterdevice(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","title":"CoreDelegate","navigatorTitle":[{"text":"CoreDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate used to receive events for the ","type":"text"},{"code":"SMICoreClient","type":"codeVoice"},{"text":" framework. Use this protocol to listen","type":"text"},{"text":" ","type":"text"},{"text":"for chat messages, receive message status changes, detect network status changes, and receive error messages.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/coredelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/removeDelegate(delegate:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"text":"CoreDelegate","preciseIdentifier":"c:objc(pl)SMICoreDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/coreclient\/removedelegate(delegate:)","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"removeDelegate:","kind":"identifier"}],"abstract":[{"text":"Removes the delegate to stop receiving events.","type":"text"}],"title":"removeDelegate(delegate:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/removeDelegate(delegate:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory/provide(deviceToken:)":{"url":"\/documentation\/smiclientcore\/corefactory\/provide(devicetoken:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/provide(deviceToken:)","abstract":[{"type":"text","text":"Provide the APNS token which will be forwarded to the In-App services to forward notifications related to conversations."}],"role":"symbol","navigatorTitle":[{"text":"provideDeviceToken:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provide","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceToken"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"provide(deviceToken:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversations(withLimit:olderThanConversation:completion:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:completion:)","title":"conversations(withLimit:olderThanConversation:completion:)","navigatorTitle":[{"kind":"identifier","text":"conversationsWithLimit:olderThanConversation:completion:"}],"abstract":[{"type":"text","text":"Retrieves conversations available to the local participant."}],"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:olderthanconversation:completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"olderThanConversation"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ([any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/preChatDelegate":{"title":"preChatDelegate","required":true,"abstract":[{"type":"text","text":"The delegate that provides hidden pre-chat field values."}],"url":"\/documentation\/smiclientcore\/coreclient\/prechatdelegate","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/preChatDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preChatDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatDelegate","kind":"typeIdentifier","text":"HiddenPreChatDelegate"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"preChatDelegate"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/stop()":{"title":"stop()","required":true,"abstract":[{"type":"text","text":"Terminates the connection listening for realtime remote events."}],"url":"\/documentation\/smiclientcore\/coreclient\/stop()","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/stop()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stop"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retrieveRemoteConfiguration(completion:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveRemoteConfiguration(completion:)","title":"retrieveRemoteConfiguration(completion:)","navigatorTitle":[{"text":"retrieveRemoteConfigurationWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Retrieves the current remote configuration if available. Defaults to offline backups if the current configuration cannot be retrieved."}],"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/retrieveremoteconfiguration(completion:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveRemoteConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/configuration":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/configuration","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/configuration","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"text":" used to determine where to send and receive events for the In-App Messaging service.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SMICoreConfiguration","text":"Configuration","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"title":"configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/userVerificationDelegate":{"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/userverificationdelegate","title":"userVerificationDelegate","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","navigatorTitle":[{"text":"userVerificationDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegate that provides the challenge for the identity token for user verified connections."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userVerificationDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate","text":"UserVerificationDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/addDelegate(delegate:queue:)":{"url":"\/documentation\/smiclientcore\/coreclient\/adddelegate(delegate:queue:)","abstract":[{"text":"Adds a delegate to listen to ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate","type":"reference","isActive":true},{"text":" events.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addDelegate:queue:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreDelegate","text":"CoreDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"required":true,"type":"topic","title":"addDelegate(delegate:queue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/addDelegate(delegate:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreDelegate","text":"CoreDelegate"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/coreclient\/adddelegate(delegate:)","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addDelegate:"}],"abstract":[{"type":"text","text":"Adds a delegate to listen to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"},{"type":"text","text":" events."}],"title":"addDelegate(delegate:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/realtimeConnectionState":{"title":"realtimeConnectionState","required":true,"abstract":[{"type":"text","text":"Current realtime connection state."}],"url":"\/documentation\/smiclientcore\/coreclient\/realtimeconnectionstate","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"realtimeConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState"}],"navigatorTitle":[{"kind":"identifier","text":"realtimeConnectionState"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retrieveBusinessHours(completion:)":{"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/retrievebusinesshours(completion:)","title":"retrieveBusinessHours(completion:)","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveBusinessHours(completion:)","navigatorTitle":[{"text":"retrieveBusinessHoursWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Retrieves the business hour info for the current deployment."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrieveBusinessHours","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","text":"BusinessHoursInfo","preciseIdentifier":"c:objc(pl)SMIBusinessHoursInfo"},{"kind":"text","text":")?, (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversations(withLimit:olderThanConversation:forceRefresh:completion:)":{"title":"conversations(withLimit:olderThanConversation:forceRefresh:completion:)","required":true,"abstract":[{"text":"Retrieves conversations available to the local participant.","type":"text"}],"url":"\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:olderthanconversation:forcerefresh:completion:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:forceRefresh:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"olderThanConversation"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"forceRefresh"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ([any "},{"preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier","text":"Conversation"},{"kind":"text","text":"]?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversations(withLimit:sortedByActivityDirection:completion:)":{"url":"\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:sortedbyactivitydirection:completion:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:sortedByActivityDirection:completion:)","abstract":[{"type":"text","text":"Retrieves n number of conversations from offline cached data sorted by latest activity. This only returns an order based on offline cached data, and"},{"type":"text","text":" "},{"type":"text","text":"may not reflect the real-time state of conversations if the client has not retrieved that activity."}],"role":"symbol","navigatorTitle":[{"text":"conversationsWithLimit:sortedByActivityDirection:completion:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"conversations","kind":"identifier"},{"kind":"text","text":"("},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"sortedByActivityDirection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":"]?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"required":true,"type":"topic","title":"conversations(withLimit:sortedByActivityDirection:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/multimediaClient":{"title":"multimediaClient","required":true,"abstract":[{"text":"The MultiMedia client currently available on the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":" This is used to monitor the Multimedia communication when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the conversation is in a supported Modality."}],"url":"\/documentation\/smiclientcore\/coreclient\/multimediaclient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/multimediaClient","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaClient","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MultimediaClientProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"multimediaClient","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/state":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/state","abstract":[{"text":"Current network connectivity state.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"state"}],"title":"state","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/state"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversationClient(with:)":{"abstract":[{"type":"text","text":"Generates an instance of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true},{"type":"text","text":" object which is used to manage all conversation data."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversationClient(with:)","navigatorTitle":[{"text":"conversationClientWithId:","kind":"identifier"}],"title":"conversationClient(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":"?) -> any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/conversationclient(with:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/destroyStorage()":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage()","title":"destroyStorage()","navigatorTitle":[{"text":"destroyStorage:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/destroystorage()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroyStorage","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"deprecated":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/revokeToken(completion:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeToken(completion:)","abstract":[{"type":"text","text":"Revokes the authorization credentials associated with this configuration and de-registers the device from receiving push notifications."}],"role":"symbol","navigatorTitle":[{"text":"revokeTokenWithCompletion:","kind":"identifier"}],"title":"revokeToken(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokeToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/revoketoken(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/closeConversation(withIdentifier:completion:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/closeConversation(withIdentifier:completion:)","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/closeconversation(withidentifier:completion:)","abstract":[{"type":"text","text":"Closes the conversation identified by the given identifier."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"closeConversation","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"closeConversationWithIdentifier:completion:"}],"title":"closeConversation(withIdentifier:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/start()":{"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/start()","title":"start()","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/start()","navigatorTitle":[{"text":"start","kind":"identifier"}],"abstract":[{"text":"Initiates the connection to listen to realtime remote events.","type":"text"},{"text":" ","type":"text"},{"text":"Once executed the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"text":" will aggressively attempt to maintain this connection at all times.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retry(entry:remoteConfiguration:)":{"abstract":[{"type":"text","text":"Attempts to retry a message delivery and submit pre-chat fields with the entry."},{"type":"text","text":" "},{"type":"text","text":"If the message status is not "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","type":"reference","isActive":true},{"type":"text","text":", the entry is ignored."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(entry:remoteConfiguration:)","navigatorTitle":[{"text":"retryEntry:remoteConfiguration:","kind":"identifier"}],"title":"retry(entry:remoteConfiguration:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retry","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entry","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":", ","kind":"text"},{"text":"remoteConfiguration","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"RemoteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/retry(entry:remoteconfiguration:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/register(deviceToken:completion:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/register(deviceToken:completion:)","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/register(devicetoken:completion:)","abstract":[{"text":"Registers the device to receive push notifcations.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"registerDevice:completion:","kind":"identifier"}],"title":"register(deviceToken:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/salesforceAuthenticationRequestPath":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/salesforceAuthenticationRequestPath","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/salesforceauthenticationrequestpath","abstract":[{"text":"Provides the endpoint for Salesforce authentication requests given the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"salesforceAuthenticationRequestPath","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"salesforceAuthenticationRequestPath"}],"title":"salesforceAuthenticationRequestPath"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/destroyStorage(andAuthorization:completion:)":{"abstract":[{"type":"text","text":"Deletes the In-App Message store."},{"type":"text","text":" "},{"type":"text","text":"This will reset all conversation as well as authorization credentials."},{"type":"text","text":" "},{"type":"text","text":"By default this will also clear all auth credentials."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage(andAuthorization:completion:)","navigatorTitle":[{"text":"destroyStorageAndAuthorization:completion:","kind":"identifier"}],"title":"destroyStorage(andAuthorization:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroyStorage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"andAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/destroystorage(andauthorization:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setUserVerificationDelegate(delegate:queue:)":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserVerificationDelegate"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate","kind":"typeIdentifier","text":"UserVerificationDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"queue"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sets the userVerificationDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"navigatorTitle":[{"text":"setUserVerificationDelegate:queue:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient\/setuserverificationdelegate(delegate:queue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setUserVerificationDelegate(delegate:queue:)","title":"setUserVerificationDelegate(delegate:queue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retry(_:preChatFields:hiddenPreChatFields:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:preChatFields:hiddenPreChatFields:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"retryEntry:preChatFields:hiddenPreChatFields:"}],"title":"retry(_:preChatFields:hiddenPreChatFields:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retry"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry"},{"kind":"text","text":", "},{"text":"preChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"PreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField"},{"text":"]?, ","kind":"text"},{"text":"hiddenPreChatFields","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]?)","kind":"text"}],"type":"topic","deprecated":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/retry(_:prechatfields:hiddenprechatfields:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/templatedUrlDelegate":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/templatedUrlDelegate","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/templatedurldelegate","abstract":[{"text":"The delegate that provides the auto-response messaging component parameter values.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"TemplatedUrlDelegate","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate"},{"kind":"text","text":")?"}],"kind":"symbol","navigatorTitle":[{"text":"templatedUrlDelegate","kind":"identifier"}],"title":"templatedUrlDelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryStatus/error":{"abstract":[{"text":"There was some form of error when sending a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMIConversationEntryStatusError"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","title":"error","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationEntryStatus","preciseIdentifier":"c:SMIConversationEntryStatus.h@T@SMIConversationEntryStatus"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationentrystatus\/error"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/revokeTokenAndDeregisterDevice(_:completion:)":{"title":"revokeTokenAndDeregisterDevice(_:completion:)","required":true,"abstract":[{"type":"text","text":"Revokes the authorization credentials associated with this configuration and optionally de-registers the device from receiving push notifications."}],"url":"\/documentation\/smiclientcore\/coreclient\/revoketokenandderegisterdevice(_:completion:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeTokenAndDeregisterDevice(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"revokeTokenAndDeregisterDevice"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"revokeTokenAndDeregisterDevice:completion:","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setPreChatDelegate(delegate:queue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/setprechatdelegate(delegate:queue:)","kind":"symbol","role":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setPreChatDelegate(delegate:queue:)","title":"setPreChatDelegate(delegate:queue:)","navigatorTitle":[{"text":"setPreChatDelegate:queue:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreChatDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatDelegate","kind":"typeIdentifier","text":"HiddenPreChatDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the preChatDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retry(_:)":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retry","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":")","kind":"text"}],"abstract":[{"text":"Attempts to retry a message delivery. If the message status is not ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryStatus\/error","isActive":true},{"type":"text","text":",  the entry is ignored."}],"navigatorTitle":[{"text":"retryEntry:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient\/retry(_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:)","title":"retry(_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setTemplatedUrlDelegate(delegate:queue:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTemplatedUrlDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate","text":"TemplatedUrlDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/coreclient\/settemplatedurldelegate(delegate:queue:)","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTemplatedUrlDelegate:queue:"}],"abstract":[{"type":"text","text":"Sets the templatedUrlDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"title":"setTemplatedUrlDelegate(delegate:queue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setTemplatedUrlDelegate(delegate:queue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/markAsRead(entry:)":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"entry","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Marks a conversation entry as read."}],"navigatorTitle":[{"text":"markAsRead:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient\/markasread(entry:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/markAsRead(entry:)","title":"markAsRead(entry:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"SMICoreClient","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/configuration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/multimediaClient","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/preChatDelegate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/salesforceAuthenticationRequestPath","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/state","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/templatedUrlDelegate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/addDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/closeConversation(withIdentifier:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversationClient(with:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:forceRefresh:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:sortedByActivityDirection:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/deregisterDevice(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage(andAuthorization:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/markAsRead(entry:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/register(deviceToken:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/removeDelegate(delegate:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveBusinessHours(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveRemoteConfiguration(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(_:preChatFields:hiddenPreChatFields:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retry(entry:remoteConfiguration:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeToken(completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeTokenAndDeregisterDevice(_:completion:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setPreChatDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setTemplatedUrlDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setUserVerificationDelegate(delegate:queue:)","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/start()","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/stop()"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreDelegate"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SMICoreClient","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1deregisterDevice(completion:)\/title","value":"deregisterDeviceWithCompletion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1deregisterDevice(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deregisterDeviceWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/title","value":"SMICoreDelegate"},{"op":"replace","value":[{"text":"SMICoreDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreDelegate\/navigatorTitle"},{"op":"replace","value":"removeDelegate:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1removeDelegate(delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1removeDelegate(delegate:)\/fragments"},{"op":"replace","value":"provideDeviceToken:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1provide(deviceToken:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"provideDeviceToken:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1provide(deviceToken:)\/fragments"},{"op":"replace","value":"conversationsWithLimit:olderThanConversation:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsWithLimit:olderThanConversation:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:completion:)\/fragments"},{"op":"replace","value":"preChatDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1preChatDelegate\/title"},{"op":"replace","value":[{"text":"preChatDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1preChatDelegate\/fragments"},{"op":"replace","value":"stop","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1stop()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1stop()\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveRemoteConfiguration(completion:)\/title","value":"retrieveRemoteConfigurationWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveRemoteConfiguration(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"retrieveRemoteConfigurationWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1configuration\/title","op":"replace","value":"configuration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1configuration\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/title","op":"replace","value":"userVerificationDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"userVerificationDelegate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:queue:)\/title","op":"replace","value":"addDelegate:queue:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:queue:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addDelegate:queue:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:)\/title","op":"replace","value":"addDelegate:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1addDelegate(delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/title","op":"replace","value":"realtimeConnectionState"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/fragments","op":"replace","value":[{"kind":"identifier","text":"realtimeConnectionState"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveBusinessHours(completion:)\/title","op":"replace","value":"retrieveBusinessHoursWithCompletion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveBusinessHours(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveBusinessHoursWithCompletion:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:forceRefresh:completion:)\/title","op":"replace","value":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:forceRefresh:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:sortedByActivityDirection:completion:)\/title","op":"replace","value":"conversationsWithLimit:sortedByActivityDirection:completion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:sortedByActivityDirection:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsWithLimit:sortedByActivityDirection:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1multimediaClient\/title","value":"multimediaClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1multimediaClient\/fragments","value":[{"text":"multimediaClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversationClient(with:)\/title","value":"conversationClientWithId:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversationClient(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationClientWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage()\/title","value":"destroyStorage:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyStorage:"}]},{"op":"replace","value":"revokeTokenWithCompletion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeToken(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"revokeTokenWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeToken(completion:)\/fragments"},{"op":"replace","value":"closeConversationWithIdentifier:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1closeConversation(withIdentifier:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeConversationWithIdentifier:completion:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1closeConversation(withIdentifier:completion:)\/fragments"},{"op":"replace","value":"start","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1start()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1start()\/fragments"},{"op":"replace","value":"retryEntry:remoteConfiguration:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(entry:remoteConfiguration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retryEntry:remoteConfiguration:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(entry:remoteConfiguration:)\/fragments"},{"op":"replace","value":"registerDevice:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1register(deviceToken:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerDevice:completion:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1register(deviceToken:completion:)\/fragments"},{"op":"replace","value":"salesforceAuthenticationRequestPath","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1salesforceAuthenticationRequestPath\/title"},{"op":"replace","value":[{"text":"salesforceAuthenticationRequestPath","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1salesforceAuthenticationRequestPath\/fragments"},{"op":"replace","value":"destroyStorageAndAuthorization:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage(andAuthorization:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyStorageAndAuthorization:completion:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage(andAuthorization:completion:)\/fragments"},{"op":"replace","value":"setUserVerificationDelegate:queue:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setUserVerificationDelegate(delegate:queue:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setUserVerificationDelegate:queue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setUserVerificationDelegate(delegate:queue:)\/fragments"},{"op":"replace","value":"retryEntry:preChatFields:hiddenPreChatFields:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(_:preChatFields:hiddenPreChatFields:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"retryEntry:preChatFields:hiddenPreChatFields:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(_:preChatFields:hiddenPreChatFields:)\/fragments"},{"op":"replace","value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"op":"replace","value":"templatedUrlDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1templatedUrlDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"templatedUrlDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1templatedUrlDelegate\/fragments"},{"op":"replace","value":"SMIConversationEntryStatusError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1error\/title"},{"op":"replace","value":[{"text":"SMIConversationEntryStatusError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryStatus~1error\/fragments"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"op":"replace","value":"revokeTokenAndDeregisterDevice:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeTokenAndDeregisterDevice(_:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"revokeTokenAndDeregisterDevice:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeTokenAndDeregisterDevice(_:completion:)\/fragments"},{"op":"replace","value":"setPreChatDelegate:queue:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setPreChatDelegate(delegate:queue:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreChatDelegate:queue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setPreChatDelegate(delegate:queue:)\/fragments"},{"op":"replace","value":"retryEntry:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retryEntry:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retry(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setTemplatedUrlDelegate(delegate:queue:)\/title","value":"setTemplatedUrlDelegate:queue:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setTemplatedUrlDelegate(delegate:queue:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTemplatedUrlDelegate:queue:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1markAsRead(entry:)\/title","value":"markAsRead:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1markAsRead(entry:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"markAsRead:","kind":"identifier"}],"op":"replace"}]}]}