{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAsset"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFileAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","text":"FileAsset","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"Use this protocol to access binary data assets in a conversation. This protocol extends","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"text":" to provide access to the raw data content of files and documents.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset\/data"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAsset","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIDataAsset","symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"DataAsset","kind":"identifier"}],"roleHeading":"Protocol","title":"DataAsset"},"abstract":[{"text":"A protocol that represents a data asset in a conversation.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/dataasset"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/dataasset"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"kind":"relationships"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/DataAsset/data":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset\/data","url":"\/documentation\/smiclientcore\/dataasset\/data","abstract":[{"type":"text","text":"The binary data content of this asset."},{"text":" ","type":"text"},{"text":"This property provides access to the raw data of the file or document.","type":"text"}],"role":"symbol","title":"data","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/fileasset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","role":"symbol","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"title":"FileAsset","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileAsset","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/DataAsset":{"abstract":[{"text":"A protocol that represents a data asset in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DataAsset","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/dataasset","title":"DataAsset","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataAsset"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIDataAsset","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"SMIDataAsset","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIDataAsset"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset\/data"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SMIDataAsset","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFileAsset","preciseIdentifier":"c:objc(pl)SMIFileAsset","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset~1data\/fragments","value":[{"text":"data","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}]},{"op":"replace","value":"SMIDataAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/fragments","value":[{"kind":"identifier","text":"SMIDataAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIDataAsset"}]}]}]}