{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","abstract":[{"text":"The completion block for returning the error result from the endSession call.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EndSessionCompletion","kind":"identifier"}],"navigatorTitle":[{"text":"EndSessionCompletion","kind":"identifier"}],"externalID":"c:SMIAPICompletions.h@T@SMIEndSessionCompletion","title":"EndSessionCompletion","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/endsessioncompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/endsessioncompletion"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EndSessionCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If the endSesion call results in an error, it is returned here. A successful end session call returns ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for the error.","type":"text"}]}],"name":"error"}],"kind":"parameters"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EndSessionCompletion"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EndSessionCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EndSessionCompletion","abstract":[{"type":"text","text":"The completion block for returning the error result from the endSession call."}],"kind":"symbol","navigatorTitle":[{"text":"EndSessionCompletion","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EndSessionCompletion","kind":"identifier"}],"role":"symbol","title":"EndSessionCompletion","url":"\/documentation\/smiclientcore\/endsessioncompletion","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIEndSessionCompletion","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIEndSessionCompletion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIEndSessionCompletion","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIEndSessionCompletion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIEndSessionCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EndSessionCompletion\/title"},{"value":[{"text":"SMIEndSessionCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EndSessionCompletion\/fragments"},{"value":[{"text":"SMIEndSessionCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EndSessionCompletion\/navigatorTitle"}]}]}