{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage"],"type":"inheritedBy"}],"variants":[{"paths":["\/documentation\/smiclientcore\/entrytypemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/entrytypemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/messageReason","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/wasRevised"],"generated":true,"anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"Use this protocol to access message-specific properties for entries of type"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/message","isActive":true,"type":"reference"},{"text":". This protocol is typically used to determine","type":"text"},{"text":" ","type":"text"},{"text":"the reason for automated responses in the conversation.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeMessage"}],"externalID":"c:objc(pl)SMIEntryTypeMessage","title":"EntryTypeMessage","modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormResponseMessage":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"abstract":[{"type":"text","text":"A protocol that defines the base type for form response messages in a conversation."}],"navigatorTitle":[{"text":"EntryTypeFormResponseMessage","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/entrytypeformresponsemessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","title":"EntryTypeFormResponseMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedURL":{"type":"topic","url":"\/documentation\/smiclientcore\/templatedurl","title":"TemplatedURL","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","navigatorTitle":[{"kind":"identifier","text":"TemplatedURL"}],"abstract":[{"text":"A protocol that represents a templated URL within a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplatedURL"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage":{"abstract":[{"type":"text","text":"A protocol that represents a rich link message within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"RichLinkMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","title":"RichLinkMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RichLinkMessage","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/richlinkmessage"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","title":"EntryTypeMessage","navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentEntry":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","title":"AttachmentEntry","navigatorTitle":[{"text":"AttachmentEntry","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an attachment entry within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/smiclientcore\/attachmententry","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentEntry","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"type":"text","text":"A protocol that represents a form in a conversation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/forminputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TextMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","abstract":[{"type":"text","text":"A protocol that represents a text message within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextMessage"}],"title":"TextMessage","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMessage"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/textmessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse":{"abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Forms for LightningType interactions with Agentforce.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormExperienceTypeResponse"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","title":"FormExperienceTypeResponse","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormExperienceTypeResponse"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetyperesponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult":{"abstract":[{"text":"A protocol that represents the server’s response to a form submission.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","title":"FormResponseResult","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseResult"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseresult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesResponse":{"title":"ChoicesResponse","abstract":[{"type":"text","text":"A protocol that represents a response with selected choices within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/choicesresponse","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChoicesResponse","kind":"identifier"}],"navigatorTitle":[{"text":"ChoicesResponse","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage/messageReason":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason"}],"abstract":[{"text":"The reason for an automated message response.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messageReason"}],"url":"\/documentation\/smiclientcore\/entrytypemessage\/messagereason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/messageReason","title":"messageReason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceExperienceType"}],"url":"\/documentation\/smiclientcore\/choiceexperiencetype","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChoiceExperienceType"}],"abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"title":"ChoiceExperienceType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorMessage":{"url":"\/documentation\/smiclientcore\/staticerrormessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Static LightningType messages with Agentforce."}],"role":"symbol","navigatorTitle":[{"text":"StaticErrorMessage","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorMessage","kind":"identifier"}],"type":"topic","title":"StaticErrorMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"url":"\/documentation\/smiclientcore\/formresponseinputs","abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","role":"symbol","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormResponseInputs"}],"type":"topic","title":"FormResponseInputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntryTypes/message":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationentrytypes\/message","title":"message","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntryTypes\/message","navigatorTitle":[{"text":"SMIConversationEntryTypesMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a standard text or media message."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"navigatorTitle":[{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","title":"ChoicesExperienceTypeResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuickReply","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/quickreply","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"QuickReply","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a quick reply within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"title":"QuickReply","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticExperienceType":{"url":"\/documentation\/smiclientcore\/staticexperiencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType","abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StaticExperienceType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticExperienceType"}],"type":"topic","title":"StaticExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetype","title":"FormExperienceType","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","navigatorTitle":[{"kind":"identifier","text":"FormExperienceType"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormExperienceType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticCancelAction":{"type":"topic","url":"\/documentation\/smiclientcore\/staticcancelaction","title":"StaticCancelAction","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","navigatorTitle":[{"text":"StaticCancelAction","kind":"identifier"}],"abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticCancelAction","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"url":"\/documentation\/smiclientcore\/carousel","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"title":"Carousel","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage/wasRevised":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wasRevised","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"If this message was generated as part of a streamed response, this property can be used to determine if this final static response has been modified in any way from the original set of streamed tokens.","type":"text"}],"navigatorTitle":[{"text":"wasRevised","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/entrytypemessage\/wasrevised","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/wasRevised","title":"wasRevised"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","title":"EntryTypeFormMessage","navigatorTitle":[{"kind":"identifier","text":"EntryTypeFormMessage"}],"abstract":[{"type":"text","text":"A protocol that defines the base type for form messages in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/entrytypeformmessage","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormMessage"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker":{"url":"\/documentation\/smiclientcore\/listpicker","abstract":[{"text":"A protocol that represents a list picker within a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPicker"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPicker"}],"type":"topic","title":"ListPicker"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIEntryTypeMessage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/messageReason","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/wasRevised"],"anchor":"Instance-Properties","generated":true}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIEntryTypeMessage","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIEntryTypeFormResponseMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/title"},{"value":[{"kind":"identifier","text":"SMIEntryTypeFormResponseMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/fragments"},{"value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/navigatorTitle"},{"value":"SMITemplatedURL","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/title"},{"value":[{"text":"SMITemplatedURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/fragments"},{"value":[{"text":"SMITemplatedURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/navigatorTitle"},{"value":"SMIRichLinkMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/title"},{"value":[{"kind":"identifier","text":"SMIRichLinkMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/fragments"},{"value":[{"text":"SMIRichLinkMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/navigatorTitle"},{"value":"SMIEntryTypeMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title"},{"value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle"},{"value":"SMIAttachmentEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/title"},{"value":[{"kind":"identifier","text":"SMIAttachmentEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/fragments"},{"value":[{"text":"SMIAttachmentEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/navigatorTitle"},{"value":"SMIFormInputs","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title"},{"value":[{"kind":"identifier","text":"SMIFormInputs"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle"},{"value":"SMITextMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/title"},{"value":[{"text":"SMITextMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/fragments"},{"value":[{"text":"SMITextMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/navigatorTitle"},{"value":"SMIFormExperienceTypeResponse","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/title"},{"value":[{"kind":"identifier","text":"SMIFormExperienceTypeResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormExperienceTypeResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/navigatorTitle"},{"value":"SMIFormResponseResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/title"},{"value":[{"kind":"identifier","text":"SMIFormResponseResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/navigatorTitle"},{"value":"SMIChoicesResponse","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/title"},{"value":[{"text":"SMIChoicesResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/fragments"},{"value":[{"text":"SMIChoicesResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/navigatorTitle"},{"value":"messageReason","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1messageReason\/title"},{"value":[{"kind":"identifier","text":"messageReason"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1messageReason\/fragments"},{"value":"SMIChoicesExperienceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/title"},{"value":[{"kind":"identifier","text":"SMIChoicesExperienceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/navigatorTitle","op":"replace","value":[{"text":"SMIChoicesExperienceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/title","op":"replace","value":"SMIStaticErrorMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/fragments","op":"replace","value":[{"text":"SMIStaticErrorMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/navigatorTitle","op":"replace","value":[{"text":"SMIStaticErrorMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title","op":"replace","value":"SMIFormResponseInputs"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments","op":"replace","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1message\/title","op":"replace","value":"SMIConversationEntryTypesMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntryTypes~1message\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntryTypesMessage"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/title","op":"replace","value":"SMIChoicesExperienceTypeResponse"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/fragments","op":"replace","value":[{"text":"SMIChoicesExperienceTypeResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/title","op":"replace","value":"SMIQuickReply"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/fragments","op":"replace","value":[{"text":"SMIQuickReply","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/navigatorTitle","op":"replace","value":[{"text":"SMIQuickReply","kind":"identifier"}]},{"op":"replace","value":"SMIStaticExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIStaticExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/fragments"},{"op":"replace","value":[{"text":"SMIStaticExperienceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/navigatorTitle"},{"op":"replace","value":"SMIFormExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments","value":[{"text":"SMIFormExperienceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle","value":[{"text":"SMIFormExperienceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/title","value":"SMIStaticCancelAction"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/fragments","value":[{"kind":"identifier","text":"SMIStaticCancelAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStaticCancelAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title","value":"SMICarousel"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments","value":[{"text":"SMICarousel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle","value":[{"kind":"identifier","text":"SMICarousel"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1wasRevised\/title","value":"wasRevised","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1wasRevised\/fragments","value":[{"text":"wasRevised","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/title","value":"SMIEntryTypeFormMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeFormMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeFormMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/title","value":"SMIListPicker"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/fragments","value":[{"text":"SMIListPicker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/navigatorTitle","op":"replace","value":[{"text":"SMIListPicker","kind":"identifier"}]}]}]}