{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"title":"EntryPayload","role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)SMIEntryPayload"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownEntry"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSCopying","text":"NSCopying"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"This protocol defines the common properties and behavior for all conversation entry payloads."},{"type":"text","text":" "},{"type":"text","text":"It provides information about the format, type, and relationships of the entry content."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/entrypayload"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/entrypayload"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/inReplyToEntryId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/replyTo"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/format","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/messageType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/type"],"title":"Type Properties","anchor":"Type-Properties"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TextMessage":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMessage"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TextMessage"}],"abstract":[{"type":"text","text":"A protocol that represents a text message within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/textmessage","title":"TextMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuickReply","kind":"identifier"}],"title":"QuickReply","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","url":"\/documentation\/smiclientcore\/quickreply","kind":"symbol","abstract":[{"text":"A protocol that represents a quick reply within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"QuickReply","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker":{"abstract":[{"text":"A protocol that represents a list picker within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"title":"ListPicker","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","navigatorTitle":[{"text":"ListPicker","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/listpicker","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPicker","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatusChanged","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/sessionstatuschanged","type":"topic","abstract":[{"text":"A protocol that represents a session status change event within a conversation.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","title":"SessionStatusChanged","role":"symbol","navigatorTitle":[{"text":"SessionStatusChanged","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueuePosition":{"abstract":[{"type":"text","text":"Represents a queue position event within an "},{"code":"SMIConversationEntry","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","title":"QueuePosition","navigatorTitle":[{"kind":"identifier","text":"QueuePosition"}],"url":"\/documentation\/smiclientcore\/queueposition","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueuePosition"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents an individual token in a stream of content."}],"url":"\/documentation\/smiclientcore\/streamingtoken","kind":"symbol","type":"topic","title":"StreamingToken","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingToken"}],"navigatorTitle":[{"kind":"identifier","text":"StreamingToken"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CloseConversationEvent":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationEvent","kind":"identifier"}],"abstract":[{"text":"Represents a close conversation event within an ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"CloseConversationEvent","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent","url":"\/documentation\/smiclientcore\/closeconversationevent","kind":"symbol","title":"CloseConversationEvent"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormResponseMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","kind":"symbol","title":"EntryTypeFormResponseMessage","url":"\/documentation\/smiclientcore\/entrytypeformresponsemessage","type":"topic","role":"symbol","abstract":[{"text":"A protocol that defines the base type for form response messages in a conversation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage":{"title":"RichLinkMessage","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RichLinkMessage","kind":"identifier"}],"navigatorTitle":[{"text":"RichLinkMessage","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a rich link message within a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":".","type":"text"}],"url":"\/documentation\/smiclientcore\/richlinkmessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentEntry":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentEntry"}],"url":"\/documentation\/smiclientcore\/attachmententry","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AttachmentEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an attachment entry within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"title":"AttachmentEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingResult":{"title":"RoutingResult","url":"\/documentation\/smiclientcore\/routingresult","navigatorTitle":[{"text":"RoutingResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingResult","kind":"symbol","abstract":[{"text":"A protocol that represents a routing result within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingResult","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticCancelAction":{"title":"StaticCancelAction","role":"symbol","navigatorTitle":[{"text":"StaticCancelAction","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/staticcancelaction","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","type":"topic","kind":"symbol","abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Static LightningType messages with Agentforce."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticCancelAction","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/identifier":{"title":"identifier","url":"\/documentation\/smiclientcore\/entrypayload\/identifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The identifier for the message content for the associated "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"required":true,"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","type":"topic","title":"StreamingTokenValidation","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/messageType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/messageType","required":true,"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"messageType","kind":"identifier"}],"title":"messageType","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryMessageTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationEntryMessageTypes.h@T@SMIConversationEntryMessageTypes"}],"type":"topic","abstract":[{"type":"text","text":"The type of message content for the associated "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/entrypayload\/messagetype"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"url":"\/documentation\/smiclientcore\/carousel","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"kind":"symbol","title":"Carousel"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/inReplyToEntryId":{"title":"inReplyToEntryId","required":true,"navigatorTitle":[{"text":"inReplyToEntryId","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inReplyToEntryId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/smiclientcore\/entrypayload\/inreplytoentryid","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/inReplyToEntryId","role":"symbol","abstract":[{"type":"text","text":"The unique identifier of a specific "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" that this payload is a reply to."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","title":"FormInputs","url":"\/documentation\/smiclientcore\/forminputs","navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"abstract":[{"type":"text","text":"A protocol that represents a form in a conversation."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedURL":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplatedURL"}],"navigatorTitle":[{"kind":"identifier","text":"TemplatedURL"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","url":"\/documentation\/smiclientcore\/templatedurl","role":"symbol","title":"TemplatedURL","abstract":[{"text":"A protocol that represents a templated URL within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkResult":{"abstract":[{"text":"A protocol that represents a routing work result within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult","navigatorTitle":[{"kind":"identifier","text":"RoutingWorkResult"}],"title":"RoutingWorkResult","url":"\/documentation\/smiclientcore\/routingworkresult","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoutingWorkResult"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticExperienceType":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticExperienceType"}],"title":"StaticExperienceType","navigatorTitle":[{"kind":"identifier","text":"StaticExperienceType"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/staticexperiencetype","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse":{"type":"topic","url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse","kind":"symbol","navigatorTitle":[{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","kind":"identifier"}],"title":"ChoicesExperienceTypeResponse","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"type":"topic","title":"MessageStreamingToken","role":"symbol","navigatorTitle":[{"text":"MessageStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageStreamingToken","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/type":{"title":"type","role":"symbol","abstract":[{"type":"text","text":"The type of message content for the associated "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/entrypayload\/type","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/type","required":true,"navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationEntryTypes","preciseIdentifier":"c:SMIConversationEntryTypes.h@T@SMIConversationEntryTypes","kind":"typeIdentifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck":{"navigatorTitle":[{"kind":"identifier","text":"EntryAck"}],"type":"topic","url":"\/documentation\/smiclientcore\/entryack","title":"EntryAck","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents an acknowledgement within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryAck"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UnknownEntry":{"url":"\/documentation\/smiclientcore\/unknownentry","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownEntry","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnknownEntry","kind":"identifier"}],"kind":"symbol","title":"UnknownEntry","abstract":[{"type":"text","text":"A protocol that represents an unknown or unsupported entry type in a conversation."}],"navigatorTitle":[{"text":"UnknownEntry","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse":{"abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormExperienceTypeResponse"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetyperesponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","navigatorTitle":[{"kind":"identifier","text":"FormExperienceTypeResponse"}],"role":"symbol","title":"FormExperienceTypeResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/format":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/format","kind":"symbol","title":"format","required":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationFormatTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationFormatTypes.h@T@SMIConversationFormatTypes"}],"abstract":[{"type":"text","text":"The format of the message content for the associated "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/entrypayload\/format","navigatorTitle":[{"text":"format","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicator":{"navigatorTitle":[{"text":"TypingIndicator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicator","kind":"identifier"}],"title":"TypingIndicator","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator","url":"\/documentation\/smiclientcore\/typingindicator","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a typing indicator within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"type":"topic","title":"FormExperienceType","role":"symbol","navigatorTitle":[{"text":"FormExperienceType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormExperienceType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formexperiencetype","abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"kind":"symbol","title":"ComposedStreamingToken","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComposedStreamingToken"}],"role":"symbol","url":"\/documentation\/smiclientcore\/composedstreamingtoken","abstract":[{"type":"text","text":"A protocol that represents a conversation entry composed of multiple streaming tokens."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComposedStreamingToken"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorMessage":{"kind":"symbol","type":"topic","title":"StaticErrorMessage","url":"\/documentation\/smiclientcore\/staticerrormessage","abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticErrorMessage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StaticErrorMessage"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicator":{"type":"topic","url":"\/documentation\/smiclientcore\/progressindicator","kind":"symbol","navigatorTitle":[{"text":"ProgressIndicator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressIndicator","kind":"identifier"}],"title":"ProgressIndicator","abstract":[{"text":"A protocol that represents a progress indicator within a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" object."}],"url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"title":"EntryPayload"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesResponse":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoicesResponse"}],"navigatorTitle":[{"kind":"identifier","text":"ChoicesResponse"}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicesresponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a response with selected choices within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"type":"topic","title":"ChoicesResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResult","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseResult","kind":"identifier"}],"title":"FormResponseResult","abstract":[{"text":"A protocol that represents the server’s response to a form submission.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseresult","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChoiceExperienceType"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","title":"ChoiceExperienceType","kind":"symbol","url":"\/documentation\/smiclientcore\/choiceexperiencetype","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceExperienceType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseInputs","kind":"identifier"}],"title":"FormResponseInputs","role":"symbol","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseinputs","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload/replyTo":{"url":"\/documentation\/smiclientcore\/entrypayload\/replyto","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyTo","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"replyTo","kind":"identifier"}],"type":"topic","title":"replyTo","role":"symbol","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" that the payload is a reply to.","type":"text"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/replyTo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormMessage":{"kind":"symbol","navigatorTitle":[{"text":"EntryTypeFormMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","title":"EntryTypeFormMessage","url":"\/documentation\/smiclientcore\/entrytypeformmessage","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeFormMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the base type for form messages in a conversation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChanged":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChanged"}],"url":"\/documentation\/smiclientcore\/participantchanged","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantChanged"}],"abstract":[{"text":"A protocol that represents a participant change event within a conversation.","type":"text"}],"title":"ParticipantChanged","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIEntryPayload","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/inReplyToEntryId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/replyTo"]},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/format","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/messageType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload\/type"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentEntry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueuePosition","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticCancelAction","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticExperienceType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedURL","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownEntry"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIEntryPayload","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSCopying","preciseIdentifier":"c:objc(pl)NSCopying","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/title","value":"SMITextMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/fragments","value":[{"kind":"identifier","text":"SMITextMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/navigatorTitle","value":[{"text":"SMITextMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/title","value":"SMIQuickReply","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/fragments","value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/navigatorTitle","value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/title","value":"SMIListPicker","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/fragments","value":[{"text":"SMIListPicker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/navigatorTitle","value":[{"text":"SMIListPicker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/title","value":"SMISessionStatusChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/fragments","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/navigatorTitle","value":[{"text":"SMISessionStatusChanged","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/title","value":"SMIQueuePosition","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/fragments","value":[{"text":"SMIQueuePosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueuePosition\/navigatorTitle","value":[{"text":"SMIQueuePosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/title","value":"SMIStreamingToken","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/fragments","value":[{"text":"SMIStreamingToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/navigatorTitle","value":[{"text":"SMIStreamingToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/title","value":"SMICloseConversationEvent","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/fragments","value":[{"kind":"identifier","text":"SMICloseConversationEvent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/navigatorTitle","value":[{"text":"SMICloseConversationEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/title","value":"SMIEntryTypeFormResponseMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeFormResponseMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeFormResponseMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/title","value":"SMIRichLinkMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/fragments","value":[{"text":"SMIRichLinkMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRichLinkMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/title","value":"SMIAttachmentEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/fragments","value":[{"text":"SMIAttachmentEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentEntry\/navigatorTitle","value":[{"text":"SMIAttachmentEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingResult\/title","value":"SMIRoutingResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingResult\/fragments","value":[{"kind":"identifier","text":"SMIRoutingResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingResult\/navigatorTitle","value":[{"text":"SMIRoutingResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/title","value":"SMIStaticCancelAction","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/fragments","value":[{"text":"SMIStaticCancelAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticCancelAction\/navigatorTitle","value":[{"text":"SMIStaticCancelAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title","value":"SMIStreamingTokenValidation","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1messageType\/title","value":"messageType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1messageType\/fragments","value":[{"text":"messageType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title","value":"SMICarousel","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments","value":[{"kind":"identifier","text":"SMICarousel"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle","value":[{"text":"SMICarousel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1inReplyToEntryId\/title","value":"inReplyToEntryId","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1inReplyToEntryId\/fragments","value":[{"text":"inReplyToEntryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title","value":"SMIFormInputs","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments","value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle","value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/title","value":"SMITemplatedURL","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/fragments","value":[{"kind":"identifier","text":"SMITemplatedURL"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedURL\/navigatorTitle","value":[{"text":"SMITemplatedURL","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/title","value":"SMIRoutingWorkResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/fragments","value":[{"text":"SMIRoutingWorkResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/navigatorTitle","value":[{"text":"SMIRoutingWorkResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/title","value":"SMIStaticExperienceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/fragments","value":[{"text":"SMIStaticExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticExperienceType\/navigatorTitle","value":[{"text":"SMIStaticExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/title","value":"SMIChoicesExperienceTypeResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/fragments","value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChoicesExperienceTypeResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title","value":"SMIMessageStreamingToken","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageStreamingToken"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/title","value":"SMIEntryAck","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/fragments","value":[{"text":"SMIEntryAck","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/navigatorTitle","value":[{"text":"SMIEntryAck","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownEntry\/title","value":"SMIUnknownEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownEntry\/fragments","value":[{"kind":"identifier","text":"SMIUnknownEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIUnknownEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/title","value":"SMIFormExperienceTypeResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/fragments","value":[{"kind":"identifier","text":"SMIFormExperienceTypeResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormExperienceTypeResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1format\/title","value":"format","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1format\/fragments","value":[{"kind":"identifier","text":"format"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/title","value":"SMITypingIndicator","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/fragments","value":[{"kind":"identifier","text":"SMITypingIndicator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/navigatorTitle","value":[{"kind":"identifier","text":"SMITypingIndicator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title","value":"SMIFormExperienceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments","value":[{"text":"SMIFormExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","value":"SMIComposedStreamingToken","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/title","value":"SMIStaticErrorMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/fragments","value":[{"kind":"identifier","text":"SMIStaticErrorMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorMessage\/navigatorTitle","value":[{"text":"SMIStaticErrorMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/title","value":"SMIProgressIndicator","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/fragments","value":[{"kind":"identifier","text":"SMIProgressIndicator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/navigatorTitle","value":[{"text":"SMIProgressIndicator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/title","value":"SMIChoicesResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/fragments","value":[{"text":"SMIChoicesResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesResponse\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChoicesResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/title","value":"SMIFormResponseResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/fragments","value":[{"text":"SMIFormResponseResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/title","value":"SMIChoicesExperienceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/fragments","value":[{"kind":"identifier","text":"SMIChoicesExperienceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/navigatorTitle","value":[{"text":"SMIChoicesExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title","value":"SMIFormResponseInputs","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseInputs"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1replyTo\/title","value":"replyTo","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload~1replyTo\/fragments","value":[{"kind":"identifier","text":"replyTo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/title","value":"SMIEntryTypeFormMessage","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/fragments","value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeFormMessage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/title","value":"SMIParticipantChanged","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/fragments","value":[{"text":"SMIParticipantChanged","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChanged\/navigatorTitle","value":[{"text":"SMIParticipantChanged","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}