{"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIEntryTypeFormResponseMessage","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"title":"EntryTypeFormResponseMessage"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A protocol that defines the base type for form response messages in a conversation.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","text":"EntryPayload"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"EntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to identify and handle form response messages within a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"This protocol extends both ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","type":"reference","isActive":true},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"},{"text":" to provide","type":"text"},{"text":" ","type":"text"},{"text":"functionality for handling form responses. It serves as the base protocol for more","type":"text"},{"text":" ","type":"text"},{"text":"specific form response types, such as form input responses and form result responses.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/entrytypeformresponsemessage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/entrytypeformresponsemessage"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"url":"\/documentation\/smiclientcore\/formresponseinputs","abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","role":"symbol","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormResponseInputs"}],"type":"topic","title":"FormResponseInputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse":{"abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Forms for LightningType interactions with Agentforce.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormExperienceTypeResponse"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","title":"FormExperienceTypeResponse","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormExperienceTypeResponse"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetyperesponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult":{"abstract":[{"text":"A protocol that represents the server’s response to a form submission.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","title":"FormResponseResult","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseResult"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseresult"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","title":"EntryTypeMessage","navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"abstract":[{"type":"text","text":"Common interface for the content of a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"type":"text","text":" object."}],"type":"topic","url":"\/documentation\/smiclientcore\/entrypayload","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormResponseMessage":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"abstract":[{"type":"text","text":"A protocol that defines the base type for form response messages in a conversation."}],"navigatorTitle":[{"text":"EntryTypeFormResponseMessage","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/entrytypeformresponsemessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","title":"EntryTypeFormResponseMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIEntryTypeFormResponseMessage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMIEntryTypeFormResponseMessage"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult"],"type":"inheritedBy","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","text":"SMIEntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"kind":"text","text":">"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormResponseInputs","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title"},{"op":"replace","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments"},{"value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle"},{"value":"SMIFormExperienceTypeResponse","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/fragments","op":"replace","value":[{"text":"SMIFormExperienceTypeResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/navigatorTitle","op":"replace","value":[{"text":"SMIFormExperienceTypeResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/title","value":"SMIFormResponseResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/navigatorTitle","value":[{"text":"SMIFormResponseResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle"},{"op":"replace","value":"SMIEntryPayload","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/title","value":"SMIEntryTypeFormResponseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/fragments","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeFormResponseMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}]}]}]}