{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/ackType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/entry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/from","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/timestamp"],"anchor":"Instance-Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryAck","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Use this protocol to access the content of an acknowledgement displayed in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"An acknowledgement indicates that a message has been received, read, or otherwise processed.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"EntryAck","externalID":"c:objc(pl)SMIEntryAck","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EntryAck"}],"roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"EntryAck"}],"role":"symbol"},"abstract":[{"type":"text","text":"A protocol that represents an acknowledgement within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/entryack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/entryack"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck/ackType":{"kind":"symbol","title":"ackType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ackType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AcknowledgementTypes","preciseIdentifier":"c:@E@SMIAcknowledgementTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/entryack\/acktype","required":true,"abstract":[{"type":"text","text":"The type of acknowledgement."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/ackType","navigatorTitle":[{"text":"ackType","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck/timestamp":{"role":"symbol","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"type":"topic","required":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/entryack\/timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"title":"timestamp","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/timestamp","abstract":[{"type":"text","text":"The time when the message was acknowledged."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck/from":{"navigatorTitle":[{"kind":"identifier","text":"from"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/entryack\/from","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/from","abstract":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"},{"type":"text","text":" that acknowledged the entry."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIParticipant","kind":"typeIdentifier","text":"Participant"}],"type":"topic","title":"from","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" object."}],"url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"title":"EntryPayload"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck/entry":{"abstract":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":" that was acknowledged.","type":"text"}],"required":true,"kind":"symbol","navigatorTitle":[{"text":"entry","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/entry","url":"\/documentation\/smiclientcore\/entryack\/entry","title":"entry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entry","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","type":"unresolvable","title":"Foundation.NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Participant","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/participant","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","title":"Participant","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck":{"navigatorTitle":[{"kind":"identifier","text":"EntryAck"}],"type":"topic","url":"\/documentation\/smiclientcore\/entryack","title":"EntryAck","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents an acknowledgement within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryAck"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIEntryAck","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIEntryAck"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIEntryAck"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/ackType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/entry","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/from","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck\/timestamp"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIEntryAck"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ackType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1ackType\/title"},{"value":[{"text":"ackType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1ackType\/fragments"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1timestamp\/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1timestamp\/fragments"},{"value":"from","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1from\/title"},{"value":[{"kind":"identifier","text":"from"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1from\/fragments"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMIEntryPayload","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments"},{"value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle"},{"value":"entry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1entry\/title"},{"value":[{"text":"entry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck~1entry\/fragments"},{"value":"SMIParticipant","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title"},{"value":[{"kind":"identifier","text":"SMIParticipant"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments"},{"value":[{"text":"SMIParticipant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle"},{"value":"SMIEntryAck","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/title"},{"value":[{"text":"SMIEntryAck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/fragments"},{"value":[{"kind":"identifier","text":"SMIEntryAck"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}