{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to specify the format of content in a conversation entry. The format"},{"type":"text","text":" "},{"type":"text","text":"determines how the content should be interpreted and displayed. This protocol is used"},{"type":"text","text":" "},{"type":"text","text":"by various message types to indicate their content format, such as text messages,"},{"type":"text","text":" "},{"type":"text","text":"rich links, list pickers, and more."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/entryformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/entryformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Protocol","title":"EntryFormat","role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIEntryFormat","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormat","kind":"identifier"}],"navigatorTitle":[{"text":"EntryFormat","kind":"identifier"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat\/type"],"anchor":"Instance-Properties","title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormatText"],"title":"Inherited By","type":"inheritedBy"}],"abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormatText":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormatText","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"EntryFormatText","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/entryformattext","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormatText","title":"EntryFormatText","abstract":[{"text":"A protocol that represents a text-based entry format.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"url":"\/documentation\/smiclientcore\/entryformat","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the format of content in a conversation entry."}],"role":"symbol","title":"EntryFormat","navigatorTitle":[{"text":"EntryFormat","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryFormat","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationFormatTypes":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationFormatTypes"}],"title":"ConversationFormatTypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationFormatTypes"}],"url":"\/documentation\/smiclientcore\/conversationformattypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible formats for messages and content in a conversation."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat/type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat\/type","url":"\/documentation\/smiclientcore\/entryformat\/type","type":"topic","title":"type","navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The format type of this entry."},{"type":"text","text":" "},{"type":"text","text":"This property indicates how the content should be interpreted and displayed."},{"type":"text","text":" "},{"type":"text","text":"See "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationFormatTypes","isActive":true,"type":"reference"},{"type":"text","text":" for the available format types."}],"required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIEntryFormat"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIEntryFormat","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIEntryFormat"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat\/type"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormatText"],"type":"inheritedBy"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIEntryFormat"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormatText\/title","op":"replace","value":"SMIEntryFormatText"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormatText\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIEntryFormatText"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormatText\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryFormatText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title","op":"replace","value":"SMIEntryFormat"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments","op":"replace","value":[{"text":"SMIEntryFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/title","op":"replace","value":"SMIConversationFormatTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/fragments","op":"replace","value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationFormatTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationFormatTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}