{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPRequestPath","interfaceLanguage":"swift"},"metadata":{"symbolKind":"var","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPRequestPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@SMIErrorNetworkHTTPRequestPath","roleHeading":"Global Variable","title":"errorNetworkHTTPRequestPath","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"SMIErrorNetworkHTTPRequestPath"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPRequestPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The path of the HTTP request that resulted in the error."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttprequestpath"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttprequestpath"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/errorNetworkHTTPRequestPath":{"type":"topic","title":"errorNetworkHTTPRequestPath","abstract":[{"type":"text","text":"The path of the HTTP request that resulted in the error."}],"navigatorTitle":[{"kind":"identifier","text":"SMIErrorNetworkHTTPRequestPath"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPRequestPath","url":"\/documentation\/smiclientcore\/errornetworkhttprequestpath","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPRequestPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIErrorNetworkHTTPRequestPath"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIErrorNetworkHTTPRequestPath","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSErrorUserInfoKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSErrorUserInfoKey"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIErrorNetworkHTTPRequestPath","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPRequestPath\/title","value":"SMIErrorNetworkHTTPRequestPath"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPRequestPath\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPRequestPath"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}