{"abstract":[{"text":"An enum that defines the possible error codes that can occur in the SDK.","type":"text"}],"sections":[],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"ErrorCodes","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"role":"symbol","externalID":"c:@E@SMIErrorCodes","title":"ErrorCodes"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to categorize different types of errors that can occur during SDK operations."},{"type":"text","text":" "},{"type":"text","text":"Each error code represents a specific failure condition that developers can handle appropriately."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachment","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentInternalServerError","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentNotFound","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentStorageLimitExceeded","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentTooLarge","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotAllowed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/networkRESTFailure","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/secureFormSubmission","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/unknown","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationInvalidOrMissing","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationNoDelegate"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/errorcodes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/errorcodes"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentUploadNotEnabled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentUploadNotEnabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotenabled","type":"topic","title":"ErrorCodes.attachmentUploadNotEnabled","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotEnabled","navigatorTitle":[{"text":"SMIErrorCodesAttachmentUploadNotEnabled","kind":"identifier"}],"abstract":[{"text":"Error code when attachment upload feature is not enabled.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/Equatable-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/smiclientcore\/errorcodes\/equatable-implementations","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentInternalServerError":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentInternalServerError","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentinternalservererror","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentInternalServerError"}],"title":"ErrorCodes.attachmentInternalServerError","abstract":[{"type":"text","text":"Error code when there is an internal server error during attachment upload."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentInternalServerError"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/networkRESTFailure":{"title":"ErrorCodes.networkRESTFailure","abstract":[{"type":"text","text":"A REST API call failed."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/networkRESTFailure","url":"\/documentation\/smiclientcore\/errorcodes\/networkrestfailure","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRESTFailure"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesNetworkRESTFailure"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/secureFormSubmission":{"role":"symbol","abstract":[{"text":"A secure form submission failed.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secureFormSubmission","kind":"identifier"}],"navigatorTitle":[{"text":"SMIErrorCodesSecureFormSubmission","kind":"identifier"}],"title":"ErrorCodes.secureFormSubmission","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/secureFormSubmission","type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/secureformsubmission"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentUploadNotAllowed":{"url":"\/documentation\/smiclientcore\/errorcodes\/attachmentuploadnotallowed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentUploadNotAllowed"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotAllowed","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotAllowed"}],"abstract":[{"text":"Error code when attachment upload is not allowed for the current user or context.","type":"text"}],"title":"ErrorCodes.attachmentUploadNotAllowed"},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/userVerificationInvalidOrMissing":{"navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationInvalidOrMissing"}],"abstract":[{"text":"Returned when an invalid or missing response is returned from the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/userverificationinvalidormissing","title":"ErrorCodes.userVerificationInvalidOrMissing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationInvalidOrMissing"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationInvalidOrMissing"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodes"}],"url":"\/documentation\/smiclientcore\/errorcodes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCodes"}],"title":"ErrorCodes","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible error codes that can occur in the SDK."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentStorageLimitExceeded":{"navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentStorageLimitExceeded"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentStorageLimitExceeded","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentstoragelimitexceeded","title":"ErrorCodes.attachmentStorageLimitExceeded","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentStorageLimitExceeded"}],"abstract":[{"type":"text","text":"Error code when storage limit is exceeded for attachment uploads."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/unknown":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/unknown","url":"\/documentation\/smiclientcore\/errorcodes\/unknown","abstract":[{"type":"text","text":"An unknown or unspecified error occurred."}],"type":"topic","title":"ErrorCodes.unknown","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesUnknown"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentNotFound":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentNotFound"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentNotFound","type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/attachmentnotfound","abstract":[{"text":"Error code when the requested attachment is not found.","type":"text"}],"title":"ErrorCodes.attachmentNotFound","navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesAttachmentNotFound"}]},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachment":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachment","abstract":[{"type":"text","text":"Error code when there is a general issue with file attachments."}],"role":"symbol","title":"ErrorCodes.attachment","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachment","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/errorcodes\/attachment","navigatorTitle":[{"text":"SMIErrorCodesAttachment","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/attachmentTooLarge":{"url":"\/documentation\/smiclientcore\/errorcodes\/attachmenttoolarge","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentTooLarge","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentTooLarge","kind":"symbol","type":"topic","title":"ErrorCodes.attachmentTooLarge","abstract":[{"text":"Error code when the attachment is too large to upload.","type":"text"}],"navigatorTitle":[{"text":"SMIErrorCodesAttachmentTooLarge","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/userVerificationDelegate":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate","required":true,"abstract":[{"type":"text","text":"The delegate that provides the challenge for the identity token for user verified connections."}],"title":"userVerificationDelegate","navigatorTitle":[{"kind":"identifier","text":"userVerificationDelegate"}],"url":"\/documentation\/smiclientcore\/coreclient\/userverificationdelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate","kind":"typeIdentifier","text":"UserVerificationDelegate"},{"kind":"text","text":")?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorCodes/userVerificationNoDelegate":{"title":"ErrorCodes.userVerificationNoDelegate","url":"\/documentation\/smiclientcore\/errorcodes\/userverificationnodelegate","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationNoDelegate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationNoDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationNoDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"The user verification delegate was not set using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/userVerificationDelegate"},{"type":"text","text":" property."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SMIErrorCodes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIErrorCodes","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachment","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentInternalServerError","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentNotFound","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentStorageLimitExceeded","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentTooLarge","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotAllowed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/attachmentUploadNotEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/networkRESTFailure","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/secureFormSubmission","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/unknown","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationInvalidOrMissing","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorCodes\/userVerificationNoDelegate"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIErrorCodes","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotEnabled\/title","op":"replace","value":"SMIErrorCodesAttachmentUploadNotEnabled"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesAttachmentUploadNotEnabled"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentInternalServerError\/title","op":"replace","value":"SMIErrorCodesAttachmentInternalServerError"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentInternalServerError\/fragments","op":"replace","value":[{"text":"SMIErrorCodesAttachmentInternalServerError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1networkRESTFailure\/title","op":"replace","value":"SMIErrorCodesNetworkRESTFailure"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1networkRESTFailure\/fragments","op":"replace","value":[{"text":"SMIErrorCodesNetworkRESTFailure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1secureFormSubmission\/title","op":"replace","value":"SMIErrorCodesSecureFormSubmission"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1secureFormSubmission\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesSecureFormSubmission"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotAllowed\/title","op":"replace","value":"SMIErrorCodesAttachmentUploadNotAllowed"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentUploadNotAllowed\/fragments","op":"replace","value":[{"text":"SMIErrorCodesAttachmentUploadNotAllowed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationInvalidOrMissing\/title","op":"replace","value":"SMIErrorCodesUserVerificationInvalidOrMissing"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationInvalidOrMissing\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesUserVerificationInvalidOrMissing"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/title","op":"replace","value":"SMIErrorCodes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodes"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentStorageLimitExceeded\/title","op":"replace","value":"SMIErrorCodesAttachmentStorageLimitExceeded"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentStorageLimitExceeded\/fragments","op":"replace","value":[{"text":"SMIErrorCodesAttachmentStorageLimitExceeded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1unknown\/title","op":"replace","value":"SMIErrorCodesUnknown"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIErrorCodesUnknown"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentNotFound\/title","op":"replace","value":"SMIErrorCodesAttachmentNotFound"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentNotFound\/fragments","op":"replace","value":[{"text":"SMIErrorCodesAttachmentNotFound","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachment\/title","value":"SMIErrorCodesAttachment","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachment\/fragments","value":[{"kind":"identifier","text":"SMIErrorCodesAttachment"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentTooLarge\/title","value":"SMIErrorCodesAttachmentTooLarge","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1attachmentTooLarge\/fragments","value":[{"text":"SMIErrorCodesAttachmentTooLarge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/title","value":"userVerificationDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1userVerificationDelegate\/fragments","value":[{"text":"userVerificationDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationNoDelegate\/title","value":"SMIErrorCodesUserVerificationNoDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorCodes~1userVerificationNoDelegate\/fragments","value":[{"text":"SMIErrorCodesUserVerificationNoDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}