{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPFileSizeLimit"},"abstract":[{"text":"The file size limit that was exceeded, causing the error.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPFileSizeLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpfilesizelimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpfilesizelimit"]}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"SMIErrorNetworkHTTPFileSizeLimit","kind":"identifier"}],"title":"errorNetworkHTTPFileSizeLimit","externalID":"c:@SMIErrorNetworkHTTPFileSizeLimit","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPFileSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Global Variable","modules":[{"name":"SMIClientCore"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/errorNetworkHTTPFileSizeLimit":{"type":"topic","abstract":[{"text":"The file size limit that was exceeded, causing the error.","type":"text"}],"url":"\/documentation\/smiclientcore\/errornetworkhttpfilesizelimit","kind":"symbol","navigatorTitle":[{"text":"SMIErrorNetworkHTTPFileSizeLimit","kind":"identifier"}],"title":"errorNetworkHTTPFileSizeLimit","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPFileSizeLimit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPFileSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIErrorNetworkHTTPFileSizeLimit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPFileSizeLimit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@NSErrorUserInfoKey","text":"NSErrorUserInfoKey","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIErrorNetworkHTTPFileSizeLimit","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPFileSizeLimit\/title","value":"SMIErrorNetworkHTTPFileSizeLimit"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPFileSizeLimit\/fragments","value":[{"text":"SMIErrorNetworkHTTPFileSizeLimit","kind":"identifier"}]}]}]}