{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errorattachmentuploadresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errorattachmentuploadresult"]}],"kind":"symbol","sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult\/error"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"Represents an error result from an attachment upload attempt."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"],"type":"inheritsFrom"}],"metadata":{"title":"ErrorAttachmentUploadResult","externalID":"c:objc(pl)SMIErrorAttachmentUploadResult","modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttachmentUploadResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorAttachmentUploadResult"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttachmentUploadResult","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","text":"AttachmentUploadResult","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"kind":"symbol","title":"AttachmentUploadResult","url":"\/documentation\/smiclientcore\/attachmentuploadresult","abstract":[{"type":"text","text":"Result of an attachment upload operation."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResult"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorAttachmentUploadResult/error":{"role":"symbol","navigatorTitle":[{"text":"error","kind":"identifier"}],"title":"error","url":"\/documentation\/smiclientcore\/errorattachmentuploadresult\/error","required":true,"abstract":[{"type":"text","text":"The error returned from the attachment upload attempt."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult\/error"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ErrorAttachmentUploadResult":{"title":"ErrorAttachmentUploadResult","abstract":[{"type":"text","text":"Represents an error result from an attachment upload attempt."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorAttachmentUploadResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/errorattachmentuploadresult","role":"symbol","navigatorTitle":[{"text":"ErrorAttachmentUploadResult","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIErrorAttachmentUploadResult","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIErrorAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ErrorAttachmentUploadResult\/error"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","text":"SMIAttachmentUploadResult"},{"kind":"text","text":">"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title"},{"value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments"},{"value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle"},{"value":"error","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult~1error\/title"},{"value":[{"kind":"identifier","text":"error"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult~1error\/fragments"},{"value":"SMIErrorAttachmentUploadResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/title"},{"value":[{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/fragments"},{"value":[{"kind":"identifier","text":"SMIErrorAttachmentUploadResult"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ErrorAttachmentUploadResult\/navigatorTitle"}]}]}