{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPResponseBody","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@SMIErrorNetworkHTTPResponseBody","role":"symbol","navigatorTitle":[{"text":"SMIErrorNetworkHTTPResponseBody","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"var","roleHeading":"Global Variable","title":"errorNetworkHTTPResponseBody","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPResponseBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpresponsebody"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpresponsebody"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPResponseBody","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"The body of the HTTP response associated with the error.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/errorNetworkHTTPResponseBody":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPResponseBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"errorNetworkHTTPResponseBody","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPResponseBody","abstract":[{"type":"text","text":"The body of the HTTP response associated with the error."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseBody"}],"type":"topic","url":"\/documentation\/smiclientcore\/errornetworkhttpresponsebody","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIErrorNetworkHTTPResponseBody","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseBody"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSErrorUserInfoKey","preciseIdentifier":"c:@T@NSErrorUserInfoKey"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseBody"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIErrorNetworkHTTPResponseBody","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPResponseBody\/title"},{"value":[{"text":"SMIErrorNetworkHTTPResponseBody","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPResponseBody\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}