{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpresponsecode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpresponsecode"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPResponseCode"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPResponseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"SMIClientCore"}],"role":"symbol","externalID":"c:@SMIErrorNetworkHTTPResponseCode","title":"errorNetworkHTTPResponseCode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPResponseCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIErrorNetworkHTTPResponseCode","kind":"identifier"}]},"abstract":[{"text":"The HTTP response status code associated with the error.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/errorNetworkHTTPResponseCode":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPResponseCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPResponseCode","title":"errorNetworkHTTPResponseCode","url":"\/documentation\/smiclientcore\/errornetworkhttpresponsecode","kind":"symbol","abstract":[{"type":"text","text":"The HTTP response status code associated with the error."}],"type":"topic","navigatorTitle":[{"text":"SMIErrorNetworkHTTPResponseCode","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIErrorNetworkHTTPResponseCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseCode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseCode"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPResponseCode\/title","value":"SMIErrorNetworkHTTPResponseCode","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPResponseCode\/fragments","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPResponseCode"}],"op":"replace"}]}]}