{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPApiResultErrorType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPApiResultErrorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"SMIErrorNetworkHTTPApiResultErrorType"}],"externalID":"c:@SMIErrorNetworkHTTPApiResultErrorType","role":"symbol","title":"errorNetworkHTTPApiResultErrorType","modules":[{"name":"SMIClientCore"}],"roleHeading":"Global Variable"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNetworkHTTPApiResultErrorType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpapiresulterrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/errornetworkhttpapiresulterrortype"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"abstract":[{"text":"The type of API error that occurred.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/errorNetworkHTTPApiResultErrorType":{"abstract":[{"text":"The type of API error that occurred.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNetworkHTTPApiResultErrorType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIErrorNetworkHTTPApiResultErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/errorNetworkHTTPApiResultErrorType","type":"topic","title":"errorNetworkHTTPApiResultErrorType","kind":"symbol","url":"\/documentation\/smiclientcore\/errornetworkhttpapiresulterrortype"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIErrorNetworkHTTPApiResultErrorType","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPApiResultErrorType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSErrorUserInfoKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSErrorUserInfoKey"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIErrorNetworkHTTPApiResultErrorType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPApiResultErrorType\/title","value":"SMIErrorNetworkHTTPApiResultErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1errorNetworkHTTPApiResultErrorType\/fragments","value":[{"kind":"identifier","text":"SMIErrorNetworkHTTPApiResultErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}