{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"ExperimentalConfiguration","kind":"identifier"}],"title":"ExperimentalConfiguration","symbolKind":"protocol","externalID":"c:objc(pl)SMIExperimentalConfiguration","roleHeading":"Protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExperimentalConfiguration","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration\/enableLightningTypes"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/experimentalconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/experimentalconfiguration"]}],"abstract":[{"text":"This class stores configuration for experimental or beta features.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExperimentalConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"All properties and features which are exposed in this class are subject to change."}],"type":"paragraph"}]},{"name":"Warning","style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Experimental features\/APIs may be removed without advanced notification at any time.","type":"text"},{"text":" ","type":"text"},{"text":"Any use of these features will ","type":"text"},{"inlineContent":[{"type":"text","text":"NOT"}],"type":"strong"},{"text":" be offered any official support, until such time as they may be adopted as full and stable features.","type":"text"}]}]}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ExperimentalConfiguration":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExperimentalConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"This class stores configuration for experimental or beta features."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration","url":"\/documentation\/smiclientcore\/experimentalconfiguration","kind":"symbol","navigatorTitle":[{"text":"ExperimentalConfiguration","kind":"identifier"}],"title":"ExperimentalConfiguration","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ExperimentalConfiguration/enableLightningTypes":{"title":"enableLightningTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration\/enableLightningTypes","required":true,"abstract":[{"text":"This property will enable Lightning Type experiences with Agentforce Agents.","type":"text"}],"url":"\/documentation\/smiclientcore\/experimentalconfiguration\/enablelightningtypes","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLightningTypes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"enableLightningTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIExperimentalConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIExperimentalConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIExperimentalConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration\/enableLightningTypes"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIExperimentalConfiguration"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/title","value":"SMIExperimentalConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/fragments","value":[{"text":"SMIExperimentalConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/navigatorTitle","value":[{"text":"SMIExperimentalConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration~1enableLightningTypes\/title","value":"enableLightningTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration~1enableLightningTypes\/fragments","value":[{"text":"enableLightningTypes","kind":"identifier"}],"op":"replace"}]}]}