{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FailureTypes","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Possible-Values","text":"Possible Values","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/none"},{"type":"text","text":" - Indicates a successful routing operation"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/unknown","type":"reference"},{"text":" - An unknown or unspecified routing failure","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/submissionError"},{"type":"text","text":" - A failure occurred during form or data submission"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/routingError","isActive":true},{"type":"text","text":" - A failure occurred during the routing process"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/cancelled","type":"reference"},{"text":" - The routing operation was cancelled","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to categorize different types of failures that can occur during routing operations."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a specific failure condition that developers can handle appropriately."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/init(rawValue:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/cancelled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/none","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/routingError","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/submissionError","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/unknown"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/_SwiftNewtypeWrapper-Implementations"],"generated":true}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/failuretypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/failuretypes"]}],"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FailureTypes","kind":"identifier"}],"title":"FailureTypes","role":"symbol","symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"FailureTypes"}],"roleHeading":"Structure","modules":[{"name":"SMIClientCore"}],"externalID":"c:SMIFailureTypes.h@T@SMIFailureTypes"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"An enum that defines the possible types of routing failures that can occur."}],"references":{"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/none":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/none","title":"none","abstract":[{"type":"text","text":"The routing operation was successful."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIFailureTypesNone","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/failuretypes\/none","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/routingError":{"navigatorTitle":[{"kind":"identifier","text":"SMIFailureTypesRoutingError"}],"url":"\/documentation\/smiclientcore\/failuretypes\/routingerror","abstract":[{"type":"text","text":"A failure occurred during the routing process."}],"role":"symbol","title":"routingError","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/routingError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier","text":"FailureTypes"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/cancelled":{"role":"symbol","title":"cancelled","navigatorTitle":[{"text":"SMIFailureTypesCancelled","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/failuretypes\/cancelled","type":"topic","abstract":[{"text":"The routing operation was cancelled.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FailureTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/cancelled","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/submissionError":{"url":"\/documentation\/smiclientcore\/failuretypes\/submissionerror","navigatorTitle":[{"text":"SMIFailureTypesSubmissionError","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/submissionError","abstract":[{"type":"text","text":"A failure occurred during data submission."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submissionError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"submissionError"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/unknown":{"title":"unknown","type":"topic","abstract":[{"type":"text","text":"An unknown or unspecified routing failure."}],"url":"\/documentation\/smiclientcore\/failuretypes\/unknown","navigatorTitle":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/unknown","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/Equatable-Implementations","type":"topic","kind":"article","url":"\/documentation\/smiclientcore\/failuretypes\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/_SwiftNewtypeWrapper-Implementations":{"type":"topic","title":"_SwiftNewtypeWrapper Implementations","abstract":[],"url":"\/documentation\/smiclientcore\/failuretypes\/_swiftnewtypewrapper-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/_SwiftNewtypeWrapper-Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"abstract":[{"text":"An enum that defines the possible types of routing failures that can occur.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FailureTypes"}],"title":"FailureTypes","url":"\/documentation\/smiclientcore\/failuretypes","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/init(rawValue:)":{"abstract":[],"type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/failuretypes\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIFailureTypes","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFailureTypes"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIFailureTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFailureTypes","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIFailureTypesNone","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1none\/title","op":"replace"},{"value":[{"text":"SMIFailureTypesNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1none\/fragments","op":"replace"},{"value":"SMIFailureTypesRoutingError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1routingError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFailureTypesRoutingError"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1routingError\/fragments","op":"replace"},{"value":"SMIFailureTypesCancelled","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1cancelled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFailureTypesCancelled"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1cancelled\/fragments","op":"replace"},{"value":"SMIFailureTypesSubmissionError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1submissionError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFailureTypesSubmissionError"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1submissionError\/fragments","op":"replace"},{"value":"SMIFailureTypesUnknown","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1unknown\/title","op":"replace"},{"value":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1unknown\/fragments","op":"replace"},{"value":"SMIFailureTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title","op":"replace"},{"value":[{"text":"SMIFailureTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFailureTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}