{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/content","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/isEnabled"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/fallbackmessage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/fallbackmessage"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"abstract":[{"text":"A protocol that defines the fallback message configuration for when the service is unavailable.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"role":"symbol","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIFallbackMessage","symbolKind":"protocol","navigatorTitle":[{"text":"FallbackMessage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FallbackMessage"}],"title":"FallbackMessage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FallbackMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol represents a message that is displayed to users when the chat service"},{"type":"text","text":" "},{"type":"text","text":"is unavailable or encounters an error. The message can be formatted with rich text"},{"type":"text","text":" "},{"type":"text","text":"and can be enabled or disabled as needed."}]}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage/content":{"type":"topic","required":true,"title":"content","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/fallbackmessage\/content","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/content","abstract":[{"type":"text","text":"The formatted text of the fallback message."},{"type":"text","text":" "},{"type":"text","text":"This text can include rich formatting and is displayed to users when the service is unavailable."}],"navigatorTitle":[{"text":"content","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage/isEnabled":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEnabled","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/isEnabled","navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"url":"\/documentation\/smiclientcore\/fallbackmessage\/isenabled","abstract":[{"type":"text","text":"Indicates whether the fallback message is active."},{"type":"text","text":" "},{"type":"text","text":"When true, the fallback message will be displayed when the service is unavailable."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the fallback message configuration for when the service is unavailable."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FallbackMessage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FallbackMessage"}],"url":"\/documentation\/smiclientcore\/fallbackmessage","title":"FallbackMessage"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIFallbackMessage","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIFallbackMessage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFallbackMessage"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/content","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/isEnabled"],"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFallbackMessage","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"content","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1content\/title","op":"replace"},{"value":[{"text":"content","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1content\/fragments","op":"replace"},{"value":"isEnabled","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1isEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isEnabled"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1isEnabled\/fragments","op":"replace"},{"value":"SMIFallbackMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/title","op":"replace"},{"value":[{"text":"SMIFallbackMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/fragments","op":"replace"},{"value":[{"text":"SMIFallbackMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}