{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownAsset"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileAsset"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access information about file assets in a conversation, such as","type":"text"},{"text":" ","type":"text"},{"text":"images, documents, or other media files. This protocol provides access to file metadata","type":"text"},{"text":" ","type":"text"},{"text":"and content, with support for asynchronous file fetching.","type":"text"}]}]}],"abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Protocol","title":"FileAsset","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"externalID":"c:objc(pl)SMIFileAsset","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileAsset"}],"role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/attachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/file","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/mimeType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/parentEntryId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/url"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/fileasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/fileasset"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"kind":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","title":"fetchContent(completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchContentWithCompletion:"}],"abstract":[{"text":"Fetches the content of this file asset asynchronously.","type":"text"},{"text":" ","type":"text"},{"text":"This method downloads the file content if it’s not already cached.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchContent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/attachmentUploadResult":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/attachmentUploadResult","title":"attachmentUploadResult","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/attachmentuploadresult","required":true,"abstract":[{"text":"The result of the file asset’s upload operation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides information about the upload status and any associated metadata.","type":"text"},{"text":" ","type":"text"},{"text":"The value is nil if the file hasn’t been uploaded or if the upload hasn’t completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentUploadResult"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"AttachmentUploadResult","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"attachmentUploadResult"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"abstract":[{"type":"text","text":"A protocol that represents a file asset in a conversation."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileAsset"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","type":"topic","title":"FileAsset","url":"\/documentation\/smiclientcore\/fileasset","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset":{"type":"topic","abstract":[{"text":"A protocol that represents an image asset in a conversation.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","url":"\/documentation\/smiclientcore\/imageasset","title":"ImageAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/identifier":{"title":"identifier","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/identifier","abstract":[{"type":"text","text":"The unique identifier for this file asset."},{"type":"text","text":" "},{"type":"text","text":"This property provides a stable way to identify and reference the file."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UnknownAsset":{"url":"\/documentation\/smiclientcore\/unknownasset","abstract":[{"type":"text","text":"A protocol that represents an unknown or unsupported file asset type in a conversation."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnknownAsset","kind":"identifier"}],"role":"symbol","title":"UnknownAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownAsset","kind":"symbol","navigatorTitle":[{"text":"UnknownAsset","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/name":{"url":"\/documentation\/smiclientcore\/fileasset\/name","type":"topic","title":"name","abstract":[{"type":"text","text":"The display name of this file asset."},{"type":"text","text":" "},{"type":"text","text":"This property provides a human-readable name for the file."}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/name"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/file":{"required":true,"url":"\/documentation\/smiclientcore\/fileasset\/file","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/file","title":"file","navigatorTitle":[{"text":"file","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"file","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The cached file data for this asset."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the file’s content if it has been downloaded."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/url":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/url","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"url","type":"topic","navigatorTitle":[{"text":"url","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The URL where this file asset can be accessed."},{"type":"text","text":" "},{"type":"text","text":"This property provides a location to download or access the file content."}],"url":"\/documentation\/smiclientcore\/fileasset\/url"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PDFAsset":{"navigatorTitle":[{"text":"PDFAsset","kind":"identifier"}],"title":"PDFAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset","url":"\/documentation\/smiclientcore\/pdfasset","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFAsset","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a PDF document asset in a conversation.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/parentEntryId":{"title":"parentEntryId","url":"\/documentation\/smiclientcore\/fileasset\/parententryid","kind":"symbol","abstract":[{"text":"The identifier of the parent entry that this file asset belongs to.","type":"text"},{"text":" ","type":"text"},{"text":"This property links the file to its containing entry in the conversation.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/parentEntryId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentEntryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"parentEntryId"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/mimeType":{"url":"\/documentation\/smiclientcore\/fileasset\/mimetype","type":"topic","title":"mimeType","abstract":[{"type":"text","text":"The MIME type of this file asset."}],"navigatorTitle":[{"text":"mimeType","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mimeType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/mimeType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/DataAsset":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DataAsset","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAsset","kind":"identifier"}],"title":"DataAsset","abstract":[{"text":"A protocol that represents a data asset in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/dataasset"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIFileAsset","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFileAsset"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/attachmentUploadResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/file","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/mimeType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/parentEntryId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/url"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownAsset"],"title":"Inherited By"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFileAsset","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","value":"fetchContentWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchContentWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1attachmentUploadResult\/title","value":"attachmentUploadResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1attachmentUploadResult\/fragments","value":[{"text":"attachmentUploadResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"kind":"identifier","text":"SMIFileAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/title","value":"SMIImageAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/fragments","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/navigatorTitle","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/title","value":"SMIUnknownAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/fragments","value":[{"kind":"identifier","text":"SMIUnknownAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIUnknownAsset"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1file\/title","value":"file","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1file\/fragments","value":[{"text":"file","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1url\/fragments","value":[{"text":"url","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/title","value":"SMIPDFAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/fragments","value":[{"text":"SMIPDFAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/navigatorTitle","value":[{"text":"SMIPDFAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1parentEntryId\/title","value":"parentEntryId","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1parentEntryId\/fragments","value":[{"text":"parentEntryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1mimeType\/title","value":"mimeType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1mimeType\/fragments","value":[{"kind":"identifier","text":"mimeType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/title","value":"SMIDataAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/fragments","value":[{"text":"SMIDataAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataAsset\/navigatorTitle","value":[{"kind":"identifier","text":"SMIDataAsset"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}