{"kind":"symbol","metadata":{"externalID":"c:SMIFileAsset.h@T@SMIFileFetchCompletion","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileFetchCompletion"}],"symbolKind":"typealias","roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"FileFetchCompletion"}],"title":"FileFetchCompletion"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A completion handler for file fetch operations."},{"type":"text","text":" "},{"type":"text","text":"This block is called when a file fetch operation completes, providing any error that occurred."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileFetchCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileFetchCompletion","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/filefetchcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/filefetchcompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileFetchCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileFetchCompletion","abstract":[{"type":"text","text":"A completion handler for file fetch operations."},{"type":"text","text":" "},{"type":"text","text":"This block is called when a file fetch operation completes, providing any error that occurred."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FileFetchCompletion"}],"title":"FileFetchCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileFetchCompletion"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/filefetchcompletion"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIFileFetchCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFileFetchCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileFetchCompletion"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMIFileFetchCompletion","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/title","value":"SMIFileFetchCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/fragments","value":[{"text":"SMIFileFetchCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileFetchCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFileFetchCompletion"}],"op":"replace"}]}]}