{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseResult"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormResponseMessage","kind":"typeIdentifier","text":"EntryTypeFormResponseMessage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"Use this protocol to access the server’s response after a form has been submitted.","type":"text"},{"text":" ","type":"text"},{"text":"This protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","isActive":true,"type":"reference"},{"text":" to provide functionality","type":"text"},{"text":" ","type":"text"},{"text":"for handling form submission results. The result can indicate either a successful","type":"text"},{"text":" ","type":"text"},{"text":"submission with created\/updated records, or a failed submission with error details.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents the server’s response to a form submission."}],"metadata":{"role":"symbol","roleHeading":"Protocol","title":"FormResponseResult","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResult","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormResponseResult","navigatorTitle":[{"kind":"identifier","text":"FormResponseResult"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseresult"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult\/result"],"anchor":"Instance-Properties","generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeMessage"}],"navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"url":"\/documentation\/smiclientcore\/entrytypemessage","title":"EntryTypeMessage","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult/result":{"navigatorTitle":[{"text":"result","kind":"identifier"}],"abstract":[{"text":"The result of the form response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the server’s response to the form submission, which can be","type":"text"},{"text":" ","type":"text"},{"text":"either a successful result with records or an error result with failure details.","type":"text"}],"type":"topic","role":"symbol","required":true,"kind":"symbol","title":"result","url":"\/documentation\/smiclientcore\/formresponseresult\/result","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult\/result","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormResult","preciseIdentifier":"c:objc(pl)SMIFormResult","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormResponseMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","kind":"symbol","title":"EntryTypeFormResponseMessage","url":"\/documentation\/smiclientcore\/entrytypeformresponsemessage","type":"topic","role":"symbol","abstract":[{"text":"A protocol that defines the base type for form response messages in a conversation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EntryTypeFormResponseMessage"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryTypeFormResponseMessage"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" object."}],"url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"title":"EntryPayload"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResult":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResult","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseResult","kind":"identifier"}],"title":"FormResponseResult","abstract":[{"text":"A protocol that represents the server’s response to a form submission.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseresult","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseResult","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResult\/result"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseResult","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeFormResponseMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","text":"SMIEntryTypeFormResponseMessage","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult~1result\/title","value":"result"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult~1result\/fragments","value":[{"text":"result","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/title","value":"SMIEntryTypeFormResponseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/fragments","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/title","value":"SMIFormResponseResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResult\/navigatorTitle","value":[{"text":"SMIFormResponseResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}