{"abstract":[{"text":"A protocol that defines an interactive element on a form that contains a title item.","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/itemType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/titleItem"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"],"type":"inheritedBy"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"FormTitleInteractionItem"}],"title":"FormTitleInteractionItem","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIFormTitleInteractionItem","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItem"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItem","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to create interactive elements in forms that combine a title with interactive","type":"text"},{"text":" ","type":"text"},{"text":"behavior. The protocol serves as a base for different types of interactive elements, such as","type":"text"},{"text":" ","type":"text"},{"text":"selectable options. Each interaction item contains a title item that provides the visual","type":"text"},{"text":" ","type":"text"},{"text":"representation and text content for the interactive element.","type":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitem"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem/itemType":{"kind":"symbol","title":"itemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/itemType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","text":"FormTitleInteractionItemType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The type of interaction item this object represents."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of interactive element and its behavior."}],"url":"\/documentation\/smiclientcore\/formtitleinteractionitem\/itemtype","required":true,"role":"symbol","navigatorTitle":[{"text":"itemType","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem":{"abstract":[{"text":"A protocol that defines an interactive element on a form that contains a title item.","type":"text"}],"title":"FormTitleInteractionItem","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formtitleinteractionitem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormTitleInteractionItem","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"kind":"symbol","title":"FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem/titleItem":{"required":true,"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/formtitleinteractionitem\/titleitem","type":"topic","abstract":[{"text":"The title item associated with this interaction item.","type":"text"},{"text":" ","type":"text"},{"text":"This provides the visual representation and text content for the interactive element.","type":"text"}],"title":"titleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/titleItem","navigatorTitle":[{"text":"titleItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormTitleInteractionItem"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/itemType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem\/titleItem"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormTitleInteractionItem"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"op":"replace","value":"itemType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1itemType\/title"},{"op":"replace","value":[{"text":"itemType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1itemType\/fragments"},{"op":"replace","value":"SMIFormTitleInteractionItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/title"},{"op":"replace","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/fragments"},{"op":"replace","value":[{"text":"SMIFormTitleInteractionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/navigatorTitle"},{"op":"replace","value":"SMIFormTitleOptionItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle"},{"op":"replace","value":"titleItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1titleItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"titleItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem~1titleItem\/fragments"}]}]}