{"kind":"symbol","metadata":{"symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseDoubleValue"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDoubleValue","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormResponseDoubleValue","title":"FormResponseDoubleValue"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsedoublevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsedoublevalue"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDoubleValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"text":"Use this protocol to represent a form response that includes a decimal number value.","type":"text"},{"text":" ","type":"text"},{"text":"The protocol extends ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"reference"},{"text":" to add support for floating-point values,","type":"text"},{"text":" ","type":"text"},{"text":"which are stored as ","type":"text"},{"type":"codeVoice","code":"CGFloat"},{"text":" objects. This type of response is typically used with","type":"text"},{"text":" ","type":"text"},{"text":"text inputs that accept numeric values with decimal places.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a floating-point number."}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue\/doubleValue"],"generated":true}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDoubleValue/doubleValue":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue\/doubleValue","url":"\/documentation\/smiclientcore\/formresponsedoublevalue\/doublevalue","role":"symbol","navigatorTitle":[{"text":"doubleValue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"doubleValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The floating-point value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the decimal number entered by the user, stored as a "},{"code":"CGFloat","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The value can represent any real number, including fractional values."}],"title":"doubleValue","type":"topic","required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDoubleValue":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDoubleValue"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseDoubleValue"}],"type":"topic","url":"\/documentation\/smiclientcore\/formresponsedoublevalue","abstract":[{"text":"A protocol that defines a form response value containing a floating-point number.","type":"text"}],"kind":"symbol","title":"FormResponseDoubleValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"title":"FormResponseValue","type":"topic","url":"\/documentation\/smiclientcore\/formresponsevalue","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseDoubleValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseDoubleValue","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseDoubleValue"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue\/doubleValue"],"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseDoubleValue","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue~1doubleValue\/title","value":"doubleValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue~1doubleValue\/fragments","value":[{"text":"doubleValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/title","value":"SMIFormResponseDoubleValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/fragments","value":[{"text":"SMIFormResponseDoubleValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseDoubleValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","value":"SMIFormResponseValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}