{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseerrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseerrortype"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseErrorType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Possible Values","anchor":"Possible-Values","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/invalidFormResponse","isActive":true},{"type":"text","text":" - A validation error occurred on the submitted form"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/formRequestExpired"},{"text":" - The form is no longer eligible for submission","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeApiResultErrorCode","isActive":true},{"type":"text","text":" - An API error prevented the successful submission of the form"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeInternalServerError","isActive":true,"type":"reference"},{"text":" - An internal service error was triggered preventing the submission of the form","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to identify specific error conditions that can occur when submitting","type":"text"},{"text":" ","type":"text"},{"text":"a form. Each type represents a different category of error, such as validation failures,","type":"text"},{"text":" ","type":"text"},{"text":"expired requests, or server issues. These error types help provide clear feedback about","type":"text"},{"text":" ","type":"text"},{"text":"why a form submission failed.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType","interfaceLanguage":"swift"},"metadata":{"symbolKind":"struct","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseErrorType"}],"externalID":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","navigatorTitle":[{"kind":"identifier","text":"FormResponseErrorType"}],"roleHeading":"Structure","title":"FormResponseErrorType"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/formRequestExpired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/invalidFormResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeApiResultErrorCode","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeInternalServerError"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/Equatable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"references":{"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/formRequestExpired":{"type":"topic","abstract":[{"type":"text","text":"The form is no longer eligible for submission."}],"title":"formRequestExpired","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formRequestExpired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormResponseErrorType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/formRequestExpired","kind":"symbol","navigatorTitle":[{"text":"SMIFormResponseErrorTypeFormRequestExpired","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/formrequestexpired"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/typeInternalServerError":{"url":"\/documentation\/smiclientcore\/formresponseerrortype\/typeinternalservererror","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeInternalServerError"}],"abstract":[{"text":"An internal service error was triggered preventing the submission of the form.","type":"text"}],"title":"typeInternalServerError","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeInternalServerError","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeInternalServerError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/invalidFormResponse":{"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeInvalidFormResponse"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/invalidformresponse","title":"invalidFormResponse","kind":"symbol","type":"topic","abstract":[{"text":"A validation error occurred on the submitted form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/invalidFormResponse","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFormResponse"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/init(rawValue:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/smiclientcore\/formresponseerrortype\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType":{"title":"FormResponseErrorType","role":"symbol","url":"\/documentation\/smiclientcore\/formresponseerrortype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseErrorType"}],"abstract":[{"type":"text","text":"An enum that defines the types of errors that can occur during form submission."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/typeApiResultErrorCode":{"kind":"symbol","abstract":[{"text":"An API error prevented the successful submission of the form.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseErrorTypeTypeApiResultErrorCode"}],"url":"\/documentation\/smiclientcore\/formresponseerrortype\/typeapiresulterrorcode","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/typeApiResultErrorCode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeApiResultErrorCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseErrorType.h@T@SMIFormResponseErrorType","kind":"typeIdentifier","text":"FormResponseErrorType"}],"title":"typeApiResultErrorCode"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseErrorType/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseErrorType\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/formresponseerrortype\/equatable-implementations","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormResponseErrorType","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormResponseErrorType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormResponseErrorTypeFormRequestExpired","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1formRequestExpired\/title"},{"op":"replace","value":[{"text":"SMIFormResponseErrorTypeFormRequestExpired","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1formRequestExpired\/fragments"},{"op":"replace","value":"SMIFormResponseErrorTypeTypeInternalServerError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeInternalServerError\/title"},{"op":"replace","value":[{"text":"SMIFormResponseErrorTypeTypeInternalServerError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeInternalServerError\/fragments"},{"op":"replace","value":"SMIFormResponseErrorTypeInvalidFormResponse","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1invalidFormResponse\/title"},{"op":"replace","value":[{"text":"SMIFormResponseErrorTypeInvalidFormResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1invalidFormResponse\/fragments"},{"op":"replace","value":"SMIFormResponseErrorType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseErrorType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType\/navigatorTitle"},{"op":"replace","value":"SMIFormResponseErrorTypeTypeApiResultErrorCode","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeApiResultErrorCode\/title"},{"op":"replace","value":[{"text":"SMIFormResponseErrorTypeTypeApiResultErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseErrorType~1typeApiResultErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}