{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/input","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/nextSectionInputId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/submitForm"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSingleInputSection"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","kind":"typeIdentifier","text":"FormInputSection","preciseIdentifier":"c:objc(pl)SMIFormInputSection"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to handle individual sections in a form. This protocol extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to provide functionality for collecting a single input value from the user. Each section contains"},{"type":"text","text":" "},{"type":"text","text":"one input field that can be configured with various input types, such as text, date picker,"},{"type":"text","text":" "},{"type":"text","text":"option picker, or select input. The section can be configured to determine the flow of the form"},{"type":"text","text":" "},{"type":"text","text":"by specifying the next section or indicating that it’s the final section that submits the form."}]}]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"abstract":[{"text":"A protocol that represents a section in a form that collects a single input value from the user.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formsingleinputsection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formsingleinputsection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"title":"FormSingleInputSection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSingleInputSection"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormSingleInputSection","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","navigatorTitle":[{"text":"FormSingleInputSection","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection":{"title":"FormInputSection","url":"\/documentation\/smiclientcore\/forminputsection","navigatorTitle":[{"kind":"identifier","text":"FormInputSection"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputSection"}],"abstract":[{"type":"text","text":"A protocol that defines the base type for form input sections."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection/input":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/input","url":"\/documentation\/smiclientcore\/formsingleinputsection\/input","title":"input","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"input"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The input object which describes how the input will be presented and collected from a user."},{"type":"text","text":" "},{"type":"text","text":"This property contains the configuration for the input field, including its type, validation"},{"type":"text","text":" "},{"type":"text","text":"rules, and presentation details."}],"navigatorTitle":[{"kind":"identifier","text":"input"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection":{"title":"FormSingleInputSection","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputSection","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formsingleinputsection","navigatorTitle":[{"text":"FormSingleInputSection","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a section in a form that collects a single input value from the user."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection/nextSectionInputId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/nextSectionInputId","url":"\/documentation\/smiclientcore\/formsingleinputsection\/nextsectioninputid","role":"symbol","navigatorTitle":[{"text":"nextSectionInputId","kind":"identifier"}],"abstract":[{"type":"text","text":"The unique identifier of the next section in the form."},{"type":"text","text":" "},{"type":"text","text":"This property determines the flow of the form by specifying which section should be shown"},{"type":"text","text":" "},{"type":"text","text":"after the current section is completed. When "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", there is no next section."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextSectionInputId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"nextSectionInputId","kind":"symbol","type":"topic","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection/submitForm":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submitForm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"submitForm","role":"symbol","navigatorTitle":[{"text":"submitForm","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines whether this is the last section in the form."},{"type":"text","text":" "},{"type":"text","text":"When set to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", this indicates that completing this section will submit the form."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/submitForm","required":true,"type":"topic","url":"\/documentation\/smiclientcore\/formsingleinputsection\/submitform"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormSingleInputSection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"SMIFormSingleInputSection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormSingleInputSection"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/input","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/nextSectionInputId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection\/submitForm"],"title":"Instance Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormSingleInputSection"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInputSection","text":"SMIFormInputSection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormInputSection","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/title"},{"value":[{"text":"SMIFormInputSection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormInputSection"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/navigatorTitle"},{"value":"input","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1input\/title"},{"value":[{"kind":"identifier","text":"input"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1input\/fragments"},{"value":"SMIFormSingleInputSection","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/fragments","value":[{"text":"SMIFormSingleInputSection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormSingleInputSection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1nextSectionInputId\/title","value":"nextSectionInputId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1nextSectionInputId\/fragments","value":[{"text":"nextSectionInputId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1submitForm\/title","value":"submitForm"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection~1submitForm\/fragments","value":[{"text":"submitForm","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}