{"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue\/selectedOptions"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/formselectedoptionsinputvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formselectedoptionsinputvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"FormSelectedOptionsInputValue","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectedOptionsInputValue"}],"externalID":"c:objc(pl)SMIFormSelectedOptionsInputValue","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"FormSelectedOptionsInputValue"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSelectedOptionsInputValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SMIFormInputValue","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","preciseIdentifier":"c:objc(pl)SMIFormInputValue"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to represent the selected options in forms that support multiple selections,","type":"text"},{"text":" ","type":"text"},{"text":"such as option pickers or select inputs. This protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","type":"reference","isActive":true},{"text":" to add","type":"text"},{"text":" ","type":"text"},{"text":"support for tracking multiple selected options. Each selected option is represented by a","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption","type":"reference","isActive":true},{"text":" that contains both an identifier and a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"A protocol that represents a form input value containing multiple selected options.","type":"text"}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SelectedOption","kind":"identifier"}],"title":"SelectedOption","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelectedOption","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a selected option in a multi-option form input."}],"url":"\/documentation\/smiclientcore\/selectedoption","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","role":"symbol","abstract":[{"text":"A protocol that defines the structure for title components used in forms.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"role":"symbol","title":"AbstractValueProtocol","abstract":[{"text":"Protocol that defines the base type for session context values.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue":{"role":"symbol","title":"SMIFormInputValue","navigatorTitle":[{"kind":"identifier","text":"SMIFormInputValue"}],"url":"\/documentation\/smiclientcore\/smiforminputvalue","abstract":[{"text":"A protocol that defines a form input value with its associated metadata.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInputValue"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectedOptionsInputValue":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a form input value containing multiple selected options."}],"navigatorTitle":[{"text":"FormSelectedOptionsInputValue","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/formselectedoptionsinputvalue","title":"FormSelectedOptionsInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectedOptionsInputValue/selectedOptions":{"title":"selectedOptions","abstract":[{"text":"A list of selected options in this input value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains an array of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},{"text":" objects, each representing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a selected option with its identifier and title. The array may be empty if no options"},{"type":"text","text":" "},{"type":"text","text":"are selected, or contain multiple items when multiple selections are allowed."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue\/selectedOptions","required":true,"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/formselectedoptionsinputvalue\/selectedoptions","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptions","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"SelectedOption","preciseIdentifier":"c:objc(pl)SMIFormSelectedOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"selectedOptions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormSelectedOptionsInputValue","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIFormSelectedOptionsInputValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectedOptionsInputValue\/selectedOptions"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","kind":"typeIdentifier","text":"SMIFormInputValue","preciseIdentifier":"c:objc(pl)SMIFormInputValue"},{"kind":"text","text":">"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormSelectedOption","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/title"},{"value":[{"text":"SMIFormSelectedOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/fragments"},{"value":[{"text":"SMIFormSelectedOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/navigatorTitle"},{"value":"SMIFormTitleItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"},{"value":"SMIAbstractValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title"},{"value":[{"kind":"identifier","text":"SMIAbstractValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments"},{"value":[{"text":"SMIAbstractValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle"},{"value":"SMIFormInputValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/title"},{"value":[{"kind":"identifier","text":"SMIFormInputValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/fragments"},{"value":[{"text":"SMIFormInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/navigatorTitle"},{"value":"SMIFormSelectedOptionsInputValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/title"},{"value":[{"text":"SMIFormSelectedOptionsInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormSelectedOptionsInputValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue\/navigatorTitle"},{"value":"selectedOptions","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue~1selectedOptions\/title"},{"value":[{"kind":"identifier","text":"selectedOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectedOptionsInputValue~1selectedOptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}