{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItemType"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"Possible-Values","text":"Possible Values","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/titleOption"},{"type":"text","text":" - Defines a selectable option that contains a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This enum is used to specify the type of interactive element that can be associated with","type":"text"},{"text":" ","type":"text"},{"text":"a form title. Each type represents a different kind of interactive component that can be","type":"text"},{"text":" ","type":"text"},{"text":"used to enhance the user interface and provide additional functionality.","type":"text"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","symbolKind":"struct","roleHeading":"Structure","modules":[{"name":"SMIClientCore"}],"title":"FormTitleInteractionItemType","navigatorTitle":[{"text":"FormTitleInteractionItemType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItemType","kind":"identifier"}]},"sections":[],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/init(rawValue:)"]},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/titleOption"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/Equatable-Implementations"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"An enum that defines the types of interactive elements that can be used in form titles.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","kind":"article","abstract":[],"url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/Equatable-Implementations","type":"topic"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType":{"abstract":[{"text":"An enum that defines the types of interactive elements that can be used in form titles.","type":"text"}],"title":"FormTitleInteractionItemType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItemType"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleInteractionItemType"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/titleOption":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTitleInteractionItemType","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIFormTitleInteractionItemTypeTitleOption","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/titleOption","kind":"symbol","title":"titleOption","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/titleoption","abstract":[{"type":"text","text":"Defines a selectable option that contains a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","isActive":true,"type":"reference"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormTitleInteractionItemType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormTitleInteractionItemType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/title","value":"SMIFormTitleInteractionItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/fragments","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/navigatorTitle","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType~1titleOption\/title","value":"SMIFormTitleInteractionItemTypeTitleOption","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType~1titleOption\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemTypeTitleOption"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}