{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseInputs"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeFormResponseMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","kind":"typeIdentifier","text":"EntryTypeFormResponseMessage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access the data collected from a form submission. This protocol"},{"type":"text","text":" "},{"type":"text","text":"extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","isActive":true},{"type":"text","text":" to provide functionality for handling"},{"type":"text","text":" "},{"type":"text","text":"form responses. It contains the values entered by the user for each input field in"},{"type":"text","text":" "},{"type":"text","text":"the form, along with an optional title that identifies the form being responded to."}]}],"kind":"content"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/formTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/inputValues"],"generated":true}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"title":"FormResponseInputs","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormResponseInputs","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseInputs","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseinputs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseinputs"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"A protocol that represents the response data from a submitted form."}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs":{"role":"symbol","url":"\/documentation\/smiclientcore\/formresponseinputs","abstract":[{"text":"A protocol that represents the response data from a submitted form.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseInputs","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs","type":"topic","navigatorTitle":[{"text":"FormResponseInputs","kind":"identifier"}],"kind":"symbol","title":"FormResponseInputs"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs/inputValues":{"abstract":[{"type":"text","text":"The values collected from a user for each section of the form."},{"type":"text","text":" "},{"type":"text","text":"This array contains the user’s input for each field in the form."}],"type":"topic","navigatorTitle":[{"text":"inputValues","kind":"identifier"}],"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputValues","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInputValue","text":"SMIFormInputValue","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/formresponseinputs\/inputvalues","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/inputValues","title":"inputValues","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormResponseMessage":{"url":"\/documentation\/smiclientcore\/entrytypeformresponsemessage","title":"EntryTypeFormResponseMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeFormResponseMessage","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines the base type for form response messages in a conversation."}],"navigatorTitle":[{"text":"EntryTypeFormResponseMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseInputs/formTitle":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/formTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTitle","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"abstract":[{"type":"text","text":"The title of the form response."},{"type":"text","text":" "},{"type":"text","text":"This property identifies which form this response corresponds to."}],"type":"topic","navigatorTitle":[{"text":"formTitle","kind":"identifier"}],"kind":"symbol","title":"formTitle","url":"\/documentation\/smiclientcore\/formresponseinputs\/formtitle","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"type":"topic","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}],"kind":"symbol","title":"EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormResponseInputs","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIFormResponseInputs","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/formTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseInputs\/inputValues"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseInputs","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryTypeFormResponseMessage","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormResponseMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormResponseMessage"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace","value":"SMIEntryPayload"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/title","op":"replace","value":"SMIFormResponseInputs"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseInputs"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseInputs"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1inputValues\/title","op":"replace","value":"inputValues"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1inputValues\/fragments","value":[{"text":"inputValues","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/title","value":"SMIEntryTypeFormResponseMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/fragments","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormResponseMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeFormResponseMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1formTitle\/title","value":"formTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseInputs~1formTitle\/fragments","value":[{"text":"formTitle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}