{"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/datePickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/optionPickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/selectInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/textInput"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/_SwiftNewtypeWrapper-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/forminputtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputtype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputType","kind":"identifier"}],"roleHeading":"Structure","role":"symbol","symbolKind":"struct","title":"FormInputType","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"FormInputType","kind":"identifier"}],"externalID":"c:SMIFormInputType.h@T@SMIFormInputType"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputType"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"Possible-Values","type":"heading","text":"Possible Values"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/selectInput","isActive":true,"type":"reference"},{"type":"text","text":" - Represents a form input that allows users to select one or more options"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/optionPickerInput","type":"reference","isActive":true},{"type":"text","text":" - Represents a form input that allows users to select exactly one option from a list"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/datePickerInput"},{"type":"text","text":" - Represents a form input that allows users to select a date and\/or time"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/textInput","isActive":true,"type":"reference"},{"type":"text","text":" - Represents a form input that allows users to enter text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"This enum is used to identify the type of form input field being used. The type determines"},{"type":"text","text":" "},{"type":"text","text":"how the input is presented to the user and what kind of data it can collect. Each type"},{"type":"text","text":" "},{"type":"text","text":"corresponds to a specific input control and validation behavior."}],"type":"paragraph"}]}],"abstract":[{"text":"An enum that defines the types of form input fields available in the system.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/selectInput":{"abstract":[{"type":"text","text":"Represents a form input that allows users to select one or more options."}],"url":"\/documentation\/smiclientcore\/forminputtype\/selectinput","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/selectInput","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SMIFormInputTypeSelectInput","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"title":"selectInput"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/textInput":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/textInput","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/forminputtype\/textinput","role":"symbol","title":"textInput","abstract":[{"text":"Represents a form input that allows users to enter text.","type":"text"}],"navigatorTitle":[{"text":"SMIFormInputTypeTextInput","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/Equatable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/smiclientcore\/forminputtype\/equatable-implementations","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/init(rawValue:)","url":"\/documentation\/smiclientcore\/forminputtype\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/optionPickerInput":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionPickerInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/optionPickerInput","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/forminputtype\/optionpickerinput","title":"optionPickerInput","navigatorTitle":[{"text":"SMIFormInputTypeOptionPickerInput","kind":"identifier"}],"abstract":[{"text":"Represents a form input that allows users to select exactly one option from a list.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when you need to present a list of mutually exclusive options.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/datePickerInput":{"title":"datePickerInput","type":"topic","navigatorTitle":[{"text":"SMIFormInputTypeDatePickerInput","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/datePickerInput","abstract":[{"type":"text","text":"Represents a form input that allows users to select a date and\/or time."}],"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/forminputtype\/datepickerinput","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"datePickerInput","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","text":"FormInputType","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/_SwiftNewtypeWrapper-Implementations":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputtype\/_swiftnewtypewrapper-implementations","title":"_SwiftNewtypeWrapper Implementations","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/_SwiftNewtypeWrapper-Implementations","role":"collectionGroup","kind":"article"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType":{"navigatorTitle":[{"text":"FormInputType","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"An enum that defines the types of form input fields available in the system.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputType","kind":"identifier"}],"title":"FormInputType","url":"\/documentation\/smiclientcore\/forminputtype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormInputType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormInputType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputType"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormInputType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1selectInput\/title","op":"replace","value":"SMIFormInputTypeSelectInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1selectInput\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputTypeSelectInput"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1textInput\/title","op":"replace","value":"SMIFormInputTypeTextInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1textInput\/fragments","op":"replace","value":[{"text":"SMIFormInputTypeTextInput","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1optionPickerInput\/title","op":"replace","value":"SMIFormInputTypeOptionPickerInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1optionPickerInput\/fragments","op":"replace","value":[{"text":"SMIFormInputTypeOptionPickerInput","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1datePickerInput\/title","op":"replace","value":"SMIFormInputTypeDatePickerInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1datePickerInput\/fragments","op":"replace","value":[{"text":"SMIFormInputTypeDatePickerInput","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/title","op":"replace","value":"SMIFormInputType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/fragments","op":"replace","value":[{"text":"SMIFormInputType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormInputType","kind":"identifier"}]}]}]}