{"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/init(rawValue:)"]},{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formErrorResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formRecordsResult"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/Equatable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}]}]},{"content":[{"type":"heading","text":"Possible Values","anchor":"Possible-Values","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formRecordsResult","isActive":true,"type":"reference"},{"text":" - Represents a successful submission with references to updated or created objects","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formErrorResult","isActive":true,"type":"reference"},{"text":" - Represents a failed submission and contains an array of errors","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to identify the outcome of a form submission. The type determines","type":"text"},{"text":" ","type":"text"},{"text":"how the result should be interpreted and processed.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponseresulttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponseresulttype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"c:SMIFormResultType.h@T@SMIFormResultType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}],"symbolKind":"struct","title":"FormResponseResultType","modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"text":"FormResponseResultType","kind":"identifier"}],"roleHeading":"Structure"},"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of results that can be returned from a form submission."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/formRecordsResult":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMIFormResultTypeFormRecordsResult"}],"abstract":[{"text":"Represents a successful submission and contains references to objects that have been updated or created as a result.","type":"text"}],"url":"\/documentation\/smiclientcore\/formresponseresulttype\/formrecordsresult","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formRecordsResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType","kind":"typeIdentifier","text":"FormResponseResultType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formRecordsResult","kind":"symbol","title":"formRecordsResult","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/smiclientcore\/formresponseresulttype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/init(rawValue:)","role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formresponseresulttype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType/formErrorResult":{"type":"topic","role":"symbol","abstract":[{"text":"Represents a failed submission and contains an array of errors that prevent the form submission.","type":"text"}],"url":"\/documentation\/smiclientcore\/formresponseresulttype\/formerrorresult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType\/formErrorResult","title":"formErrorResult","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"formErrorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType"}],"navigatorTitle":[{"text":"SMIFormResultTypeFormErrorResult","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseResultType":{"navigatorTitle":[{"text":"FormResponseResultType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseresulttype","abstract":[{"text":"An enum that defines the types of results that can be returned from a form submission.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseResultType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseResultType","title":"FormResponseResultType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIFormResultType","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIFormResultType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIFormResultType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFormResultType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SMIFormResultTypeFormRecordsResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formRecordsResult\/title"},{"op":"replace","value":[{"text":"SMIFormResultTypeFormRecordsResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formRecordsResult\/fragments"},{"op":"replace","value":"SMIFormResultTypeFormErrorResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formErrorResult\/title"},{"op":"replace","value":[{"text":"SMIFormResultTypeFormErrorResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType~1formErrorResult\/fragments"},{"op":"replace","value":"SMIFormResultType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResultType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/fragments"},{"op":"replace","value":[{"text":"SMIFormResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseResultType\/navigatorTitle"}]}]}