{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FormResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","preciseIdentifier":"c:objc(pl)SMIFormResult","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Use this protocol to handle failed form submissions.","type":"text"},{"text":" ","type":"text"},{"text":"The errors array contains detailed information about what went wrong during the submission,","type":"text"},{"text":" ","type":"text"},{"text":"which can include validation errors, expired requests, or server-side issues.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"A protocol that represents a failed form submission with error details.","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult\/errors"],"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formerrorresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formerrorresult"]}],"metadata":{"title":"FormErrorResult","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorResult","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"FormErrorResult","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormErrorResult","role":"symbol"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorResult":{"title":"FormErrorResult","abstract":[{"text":"A protocol that represents a failed form submission with error details.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formerrorresult","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorResult","kind":"identifier"}],"navigatorTitle":[{"text":"FormErrorResult","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorResult/errors":{"abstract":[{"text":"The list of errors generated by the form submission.","type":"text"},{"text":" ","type":"text"},{"text":"This array contains one or more ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" objects that describe why the form submission","type":"text"},{"text":" ","type":"text"},{"text":"failed. Each error includes a domain, code, and user info that provides specific details","type":"text"},{"text":" ","type":"text"},{"text":"about the failure. Common error types include validation errors, expired requests,","type":"text"},{"text":" ","type":"text"},{"text":"and server-side issues.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult\/errors","type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formerrorresult\/errors","title":"errors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errors","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"errors","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResult":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResult"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResult"}],"type":"topic","url":"\/documentation\/smiclientcore\/formresult","title":"FormResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","abstract":[{"text":"A protocol that defines the base type for form submission results.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormErrorResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormErrorResult"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult\/errors"],"title":"Instance Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormErrorResult","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFormResult","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","preciseIdentifier":"c:objc(pl)SMIFormResult"},{"text":">","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/title","op":"replace","value":"SMIFormErrorResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormErrorResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/navigatorTitle","op":"replace","value":[{"text":"SMIFormErrorResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult~1errors\/title","op":"replace","value":"errors"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult~1errors\/fragments","op":"replace","value":[{"kind":"identifier","text":"errors"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/title","op":"replace","value":"SMIFormResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}