{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/selectedOptionIndex","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/value"],"anchor":"Instance-Properties"}],"sections":[],"abstract":[{"text":"A protocol that represents a single-selection option picker input field in a form.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formoptionpickerinput"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormOptionPickerInput"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","kind":"typeIdentifier","text":"FormInput"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to handle single-selection option picker inputs in forms. This protocol extends"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","type":"reference","isActive":true},{"type":"text","text":" to provide functionality for selecting a single option from a predefined list."},{"type":"text","text":" "},{"type":"text","text":"Each option in the list is represented by a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference","isActive":true},{"type":"text","text":" that contains both a title"},{"type":"text","text":" "},{"type":"text","text":"and a unique identifier."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"metadata":{"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"FormOptionPickerInput","kind":"identifier"}],"title":"FormOptionPickerInput","externalID":"c:objc(pl)SMIFormOptionPickerInput","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormOptionPickerInput"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/value":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/value","title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"kind":"text","text":")?"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The currently selected option for this input."},{"type":"text","text":" "},{"type":"text","text":"This property holds the currently selected option item. It can be read to get the current"},{"type":"text","text":" "},{"type":"text","text":"selection and written to programmatically set a new selection. The value must be one of"},{"type":"text","text":" "},{"type":"text","text":"the options in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems"},{"type":"text","text":" array."}],"url":"\/documentation\/smiclientcore\/formoptionpickerinput\/value","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","abstract":[{"text":"A protocol that represents a single-selection option picker input field in a form.","type":"text"}],"navigatorTitle":[{"text":"FormOptionPickerInput","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"FormOptionPickerInput","url":"\/documentation\/smiclientcore\/formoptionpickerinput","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormOptionPickerInput"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/optionItems":{"type":"topic","abstract":[{"type":"text","text":"A list of selectable options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property contains the available options that can be selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"},{"type":"text","text":" that includes a title and identifier."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem"},{"kind":"text","text":"]"}],"required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"optionItems"}],"title":"optionItems","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","url":"\/documentation\/smiclientcore\/formoptionpickerinput\/optionitems","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","type":"topic","abstract":[{"type":"text","text":"A protocol that defines a selectable option in a form that contains a title and unique identifier."}],"role":"symbol","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"title":"FormInputOptionItem","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormInput"}],"url":"\/documentation\/smiclientcore\/forminput","navigatorTitle":[{"kind":"identifier","text":"FormInput"}],"title":"FormInput","kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput/selectedOptionIndex":{"type":"topic","title":"selectedOptionIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptionIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The currently selected index in the options list."},{"type":"text","text":" "},{"type":"text","text":"This property indicates which option is currently selected in the picker."},{"type":"text","text":" "},{"type":"text","text":"The index corresponds to the position of the selected option in the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","isActive":true},{"type":"text","text":" array."}],"navigatorTitle":[{"text":"selectedOptionIndex","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formoptionpickerinput\/selectedoptionindex","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/selectedOptionIndex","required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormOptionPickerInput","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormOptionPickerInput"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/optionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/selectedOptionIndex","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput\/value"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormOptionPickerInput","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1value\/title"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1value\/fragments"},{"value":"SMIFormOptionPickerInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/title"},{"value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/fragments"},{"value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/navigatorTitle"},{"value":"optionItems","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/title"},{"value":[{"text":"optionItems","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1optionItems\/fragments"},{"value":"SMIFormTitleOptionItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle"},{"value":"SMIFormInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments"},{"value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle"},{"value":"selectedOptionIndex","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1selectedOptionIndex\/title"},{"value":[{"text":"selectedOptionIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput~1selectedOptionIndex\/fragments"}]}]}