{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseurlvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseurlvalue"]}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue\/urlValue"],"title":"Instance Properties","anchor":"Instance-Properties"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a URL."}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseURLValue","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormResponseURLValue","navigatorTitle":[{"text":"FormResponseURLValue","kind":"identifier"}],"title":"FormResponseURLValue","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseURLValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"Use this protocol to represent a form response that includes a URL.","type":"text"},{"text":" ","type":"text"},{"text":"The protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"reference","isActive":true},{"text":" to add support for URL values,","type":"text"},{"text":" ","type":"text"},{"text":"which are stored as ","type":"text"},{"code":"NSURL","type":"codeVoice"},{"text":" objects. This type of response is typically used with","type":"text"},{"text":" ","type":"text"},{"text":"text inputs that have a URL keyboard type.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseURLValue":{"abstract":[{"text":"A protocol that defines a form response value containing a URL.","type":"text"}],"title":"FormResponseURLValue","navigatorTitle":[{"text":"FormResponseURLValue","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue","url":"\/documentation\/smiclientcore\/formresponseurlvalue","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseURLValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseURLValue/urlValue":{"required":true,"url":"\/documentation\/smiclientcore\/formresponseurlvalue\/urlvalue","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue\/urlValue","abstract":[{"text":"The URL value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the URL entered by the user, stored as an ","type":"text"},{"code":"NSURL","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlValue"}],"title":"urlValue"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"type":"topic","title":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseValue"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"url":"\/documentation\/smiclientcore\/formresponsevalue","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormResponseURLValue","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseURLValue"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseURLValue"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue\/urlValue"],"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseURLValue"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier","text":"SMIFormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/title","op":"replace","value":"SMIFormResponseURLValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseURLValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseURLValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue~1urlValue\/title","op":"replace","value":"urlValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue~1urlValue\/fragments","op":"replace","value":[{"text":"urlValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","op":"replace","value":"SMIFormResponseValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]}]}]}