{"abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem\/optionIdentifier"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputoptionitem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputoptionitem"]}],"metadata":{"externalID":"c:objc(pl)SMIFormTitleOptionItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputOptionItem"}],"title":"FormInputOptionItem","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"role":"symbol","symbolKind":"protocol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FormTitleInteractionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleInteractionItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to create selectable options in forms, such as those used in option pickers or","type":"text"},{"text":" ","type":"text"},{"text":"select inputs. Each option combines a title item for visual representation with a unique identifier","type":"text"},{"text":" ","type":"text"},{"text":"that can be used to track selection state.","type":"text"}]}],"kind":"content"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItem":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem","title":"FormTitleInteractionItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines an interactive element on a form that contains a title item."}],"url":"\/documentation\/smiclientcore\/formtitleinteractionitem","navigatorTitle":[{"text":"FormTitleInteractionItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","type":"topic","abstract":[{"type":"text","text":"A protocol that defines a selectable option in a form that contains a title and unique identifier."}],"role":"symbol","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"title":"FormInputOptionItem","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem/optionIdentifier":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"optionIdentifier","abstract":[{"type":"text","text":"The unique identifier for this selectable option."},{"type":"text","text":" "},{"type":"text","text":"This identifier is used to track the selection state of the option and can be used to"},{"type":"text","text":" "},{"type":"text","text":"associate the option with other form components or data."}],"url":"\/documentation\/smiclientcore\/forminputoptionitem\/optionidentifier","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem\/optionIdentifier","required":true,"navigatorTitle":[{"text":"optionIdentifier","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormTitleOptionItem"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem\/optionIdentifier"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormTitleOptionItem","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleInteractionItem","text":"SMIFormTitleInteractionItem","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItem"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/title","op":"replace","value":"SMIFormTitleInteractionItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","op":"replace","value":"SMIFormTitleOptionItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","op":"replace","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem~1optionIdentifier\/title","op":"replace","value":"optionIdentifier"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem~1optionIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"optionIdentifier"}]}]}]}