{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"title":"Conforms To"}],"metadata":{"role":"symbol","externalID":"c:@E@SMIFormErrorType","navigatorTitle":[{"text":"FormErrorType","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"FormErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorType","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorType","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this enum to identify specific validation errors that can occur when validating form inputs."},{"type":"text","text":" "},{"type":"text","text":"Each case represents a different type of validation failure, such as missing required fields,"},{"type":"text","text":" "},{"type":"text","text":"invalid formats, or length restrictions. This enum is used by the form validation system to"},{"type":"text","text":" "},{"type":"text","text":"provide clear feedback about what went wrong during validation."}]}]}],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/emailFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/none","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/requiredField","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/urlFormat"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/smiclientcore\/formerrortype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/urlFormat":{"title":"FormErrorType.urlFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/urlFormat","url":"\/documentation\/smiclientcore\/formerrortype\/urlformat","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlFormat","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SMIFormErrorTypeUrlFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"URL field doesn’t have a valid URL format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when a URL input field contains text that doesn’t match the standard"},{"type":"text","text":" "},{"type":"text","text":"URL format (e.g., missing protocol or invalid characters)."}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/requiredField":{"navigatorTitle":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrortype\/requiredfield","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/requiredField","role":"symbol","title":"FormErrorType.requiredField","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"abstract":[{"text":"Required field not completed.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a field marked as required is left empty.","type":"text"}]},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/RawRepresentable-Implementations","url":"\/documentation\/smiclientcore\/formerrortype\/rawrepresentable-implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/emailFormat":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formerrortype\/emailformat","abstract":[{"type":"text","text":"Email field doesn’t have a valid email address."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when an email input field contains text that doesn’t match the standard"},{"type":"text","text":" "},{"type":"text","text":"email format (e.g., missing @ symbol or invalid domain)."}],"title":"FormErrorType.emailFormat","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/emailFormat","navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeEmailFormat"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailFormat"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/formerrortype\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/maxLength":{"title":"FormErrorType.maxLength","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"}],"url":"\/documentation\/smiclientcore\/formerrortype\/maxlength","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeMaxLength"}],"abstract":[{"type":"text","text":"Field value exceeds the maximum length."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input text is longer than the maximum allowed length specified"},{"type":"text","text":" "},{"type":"text","text":"by the form configuration."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/maxLength","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"role":"symbol","abstract":[{"text":"An enum that defines validation error types for form inputs.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","navigatorTitle":[{"kind":"identifier","text":"FormErrorType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formerrortype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormErrorType"}],"title":"FormErrorType","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType/none":{"title":"FormErrorType.none","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/none","abstract":[{"type":"text","text":"No validation error detected."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the input has passed all validation checks and is considered valid."}],"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/formerrortype\/none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormErrorTypeNone"}]},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormErrorType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorType"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormErrorType"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/emailFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/none","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/requiredField","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType\/urlFormat"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormErrorType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1urlFormat\/title","value":"SMIFormErrorTypeUrlFormat","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1urlFormat\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorTypeUrlFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1requiredField\/title","value":"SMIFormErrorTypeRequiredField","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1requiredField\/fragments","value":[{"text":"SMIFormErrorTypeRequiredField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1emailFormat\/title","value":"SMIFormErrorTypeEmailFormat","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1emailFormat\/fragments","value":[{"text":"SMIFormErrorTypeEmailFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1maxLength\/title","value":"SMIFormErrorTypeMaxLength","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1maxLength\/fragments","value":[{"text":"SMIFormErrorTypeMaxLength","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title","value":"SMIFormErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments","value":[{"kind":"identifier","text":"SMIFormErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","value":[{"text":"SMIFormErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1none\/title","value":"SMIFormErrorTypeNone","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType~1none\/fragments","value":[{"text":"SMIFormErrorTypeNone","kind":"identifier"}],"op":"replace"}]}]}