{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/titleItem"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleitemtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtitleitemtype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItemType","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"Possible-Values","level":2,"type":"heading","text":"Possible Values"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/titleItem"},{"text":" - Represents a set of strings comprised of a title (required) and optional decorators and subtitles","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"This enum is used to identify the type of item being used in a form title. The type determines"},{"type":"text","text":" "},{"type":"text","text":"how the item should be interpreted and displayed. Each type corresponds to a specific"},{"type":"text","text":" "},{"type":"text","text":"kind of content that can be included in a form title."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","symbolKind":"struct","title":"FormTitleItemType","navigatorTitle":[{"text":"FormTitleItemType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItemType","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Structure","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"An enum that defines ","type":"text"},{"code":"SMIFormTitleItemType","type":"codeVoice"},{"text":" types to decorate form fields or responses.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/smiclientcore\/formtitleitemtype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","kind":"article","abstract":[]},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType/titleItem":{"abstract":[{"text":"Represents a set of strings comprised of a title (required) and optional decorators and subtitles.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitemtype\/titleitem","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormTitleItemType","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/titleItem","title":"titleItem","navigatorTitle":[{"kind":"identifier","text":"SMIFormTitleItemTypeTitleItem"}]},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/smiclientcore\/formtitleitemtype\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType\/init(rawValue:)","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItemType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","url":"\/documentation\/smiclientcore\/formtitleitemtype","kind":"symbol","type":"topic","role":"symbol","title":"FormTitleItemType","abstract":[{"type":"text","text":"An enum that defines "},{"type":"codeVoice","code":"SMIFormTitleItemType"},{"type":"text","text":" types to decorate form fields or responses."}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItemType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormTitleItemType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormTitleItemType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItemType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormTitleItemType"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType~1titleItem\/title","value":"SMIFormTitleItemTypeTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType~1titleItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItemTypeTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/title","value":"SMIFormTitleItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/fragments","value":[{"text":"SMIFormTitleItemType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItemType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}