{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formsingleinputvalue"]}],"kind":"symbol","metadata":{"title":"FormSingleInputValue","externalID":"c:objc(pl)SMIFormSingleInputValue","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputValue","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"FormSingleInputValue","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/displayValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSingleInputValue"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","preciseIdentifier":"c:objc(pl)SMIFormInputValue","text":"SMIFormInputValue"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to represent a single value response in forms, such as text inputs,","type":"text"},{"text":" ","type":"text"},{"text":"date pickers, or single-selection option pickers. The response","type":"text"},{"text":" ","type":"text"},{"text":"value is represented by a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"text":" that contains the actual data in a","type":"text"},{"text":" ","type":"text"},{"text":"type-safe format.","type":"text"}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"abstract":[{"text":"A protocol that represents a form input value containing a single response value.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue/value":{"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","abstract":[{"text":"The typed response value.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the actual response value stored in a type-safe format. The value","type":"text"},{"text":" ","type":"text"},{"text":"is represented by a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"text":" that provides access to the underlying data","type":"text"},{"text":" ","type":"text"},{"text":"in its native type.","type":"text"}],"url":"\/documentation\/smiclientcore\/formsingleinputvalue\/value","role":"symbol","title":"value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"title":"FormResponseValue","abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponsevalue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue/displayValue":{"navigatorTitle":[{"kind":"identifier","text":"displayValue"}],"title":"displayValue","url":"\/documentation\/smiclientcore\/formsingleinputvalue\/displayvalue","type":"topic","abstract":[{"type":"text","text":"The display string that represents this value."},{"type":"text","text":" "},{"type":"text","text":"This property contains a human-readable string representation of the value, which can be"},{"type":"text","text":" "},{"type":"text","text":"used for display purposes in the UI. This may be formatted differently from the actual"},{"type":"text","text":" "},{"type":"text","text":"value stored in the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value","isActive":true},{"type":"text","text":" property."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/displayValue","kind":"symbol","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","type":"topic","abstract":[{"type":"text","text":"Protocol that defines the base type for session context values."}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","title":"AbstractValueProtocol","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputValue":{"url":"\/documentation\/smiclientcore\/formsingleinputvalue","kind":"symbol","title":"FormSingleInputValue","abstract":[{"text":"A protocol that represents a form input value containing a single response value.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue","type":"topic","navigatorTitle":[{"text":"FormSingleInputValue","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue":{"kind":"symbol","title":"SMIFormInputValue","url":"\/documentation\/smiclientcore\/smiforminputvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","abstract":[{"type":"text","text":"A protocol that defines a form input value with its associated metadata."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormInputValue","kind":"identifier"}],"navigatorTitle":[{"text":"SMIFormInputValue","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormSingleInputValue","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormSingleInputValue"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/displayValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputValue\/value"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormSingleInputValue"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIFormInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","preciseIdentifier":"c:objc(pl)SMIFormInputValue"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/title"},{"value":[{"kind":"identifier","text":"value"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1value\/fragments"},{"value":"SMIFormResponseValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle"},{"value":"displayValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1displayValue\/title"},{"value":[{"text":"displayValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue~1displayValue\/fragments"},{"value":"SMIAbstractValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title"},{"value":[{"kind":"identifier","text":"SMIAbstractValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments"},{"value":[{"text":"SMIAbstractValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle"},{"value":"SMIFormSingleInputValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/title"},{"value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/fragments"},{"value":[{"text":"SMIFormSingleInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputValue\/navigatorTitle"},{"value":"SMIFormInputValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/title"},{"value":[{"text":"SMIFormInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/fragments"},{"value":[{"text":"SMIFormInputValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/navigatorTitle"}]}]}