{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Use this protocol as the base for all form response value types. It provides"},{"type":"text","text":" "},{"type":"text","text":"a common interface for different types of form responses, such as text, URLs,"},{"type":"text","text":" "},{"type":"text","text":"numbers, and dates. The protocol is extended by specific value types to add"},{"type":"text","text":" "},{"type":"text","text":"support for their particular data formats."}],"type":"paragraph"},{"text":"Available Value Types","anchor":"Available-Value-Types","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","isActive":true},{"type":"text","text":" - For text input responses"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue"},{"text":" - For URL input responses","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","type":"reference","isActive":true},{"type":"text","text":" - For decimal number responses"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue"},{"type":"text","text":" - For whole number responses"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue","isActive":true,"type":"reference"},{"text":" - For date responses","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue"},{"type":"text","text":" - For date and time responses"}]}]}],"type":"unorderedList"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue\/valueType"],"generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(pl)SMIFormResponseValue","symbolKind":"protocol","title":"FormResponseValue","navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}]},"abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsevalue"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue"],"type":"inheritedBy","kind":"relationships"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDoubleValue":{"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a floating-point number."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseDoubleValue"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","title":"FormResponseDoubleValue","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDoubleValue"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsedoublevalue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseURLValue":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseURLValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponseurlvalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FormResponseURLValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a URL."}],"title":"FormResponseURLValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseIntegerValue":{"type":"topic","url":"\/documentation\/smiclientcore\/formresponseintegervalue","title":"FormResponseIntegerValue","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue","navigatorTitle":[{"kind":"identifier","text":"FormResponseIntegerValue"}],"abstract":[{"text":"A protocol that defines a form response value containing a whole number.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormResponseIntegerValue"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"title":"FormResponseValue","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}],"url":"\/documentation\/smiclientcore\/formresponsevalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateTimeValue":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDateTimeValue"}],"url":"\/documentation\/smiclientcore\/formresponsedatetimevalue","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseDateTimeValue"}],"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date and time."}],"title":"FormResponseDateTimeValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseTextValue":{"title":"FormResponseTextValue","abstract":[{"type":"text","text":"A protocol that defines a form response value containing text."}],"url":"\/documentation\/smiclientcore\/formresponsetextvalue","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseTextValue","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseTextValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateValue":{"url":"\/documentation\/smiclientcore\/formresponsedatevalue","abstract":[{"text":"A protocol that defines a form response value containing a date.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseDateValue"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDateValue"}],"type":"topic","title":"FormResponseDateValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue/valueType":{"abstract":[{"type":"text","text":"The type of response value."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the specific type of value this response contains."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue\/valueType","navigatorTitle":[{"kind":"identifier","text":"valueType"}],"title":"valueType","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsevalue\/valuetype"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResponseValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue\/valueType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDoubleValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseURLValue"],"type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseValue"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/title","value":"SMIFormResponseDoubleValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/fragments","value":[{"text":"SMIFormResponseDoubleValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDoubleValue\/navigatorTitle","value":[{"text":"SMIFormResponseDoubleValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/title","value":"SMIFormResponseURLValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseURLValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseURLValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseURLValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/title","value":"SMIFormResponseIntegerValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseIntegerValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseIntegerValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","value":"SMIFormResponseValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/title","value":"SMIFormResponseDateTimeValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseDateTimeValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/navigatorTitle","value":[{"text":"SMIFormResponseDateTimeValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/title","value":"SMIFormResponseTextValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/navigatorTitle","value":[{"text":"SMIFormResponseTextValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/title","value":"SMIFormResponseDateValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseDateValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/navigatorTitle","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue~1valueType\/title","value":"valueType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue~1valueType\/fragments","value":[{"text":"valueType","kind":"identifier"}],"op":"replace"}]}]}