{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"FormResponseDateValue","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"FormResponseDateValue","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDateValue","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMIFormResponseDateValue"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue\/dateValue"],"anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDateValue","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","text":"FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to represent a form response that includes date information."},{"type":"text","text":" "},{"type":"text","text":"The protocol extends "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"type":"text","text":" to add support for date values, which are"},{"type":"text","text":" "},{"type":"text","text":"stored as "},{"code":"NSDate","type":"codeVoice"},{"type":"text","text":" objects. This type of response is typically used with date picker inputs"},{"type":"text","text":" "},{"type":"text","text":"that allow users to select a date without time components. The date can be formatted"},{"text":" ","type":"text"},{"text":"according to a specified format string when needed.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsedatevalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsedatevalue"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A protocol that defines a form response value containing a date.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"title":"FormResponseValue","type":"topic","url":"\/documentation\/smiclientcore\/formresponsevalue","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateValue/dateValue":{"kind":"symbol","title":"dateValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The date value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the date information selected by the user, without any time","type":"text"},{"text":" ","type":"text"},{"text":"components.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue\/dateValue","url":"\/documentation\/smiclientcore\/formresponsedatevalue\/datevalue","role":"symbol","navigatorTitle":[{"text":"dateValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateValue":{"title":"FormResponseDateValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDateValue","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FormResponseDateValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponsedatevalue","abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormResponseDateValue","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateValue\/dateValue"],"title":"Instance Properties","anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseDateValue"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIFormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormResponseValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle"},{"op":"replace","value":"dateValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue~1dateValue\/title"},{"op":"replace","value":[{"text":"dateValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue~1dateValue\/fragments"},{"op":"replace","value":"SMIFormResponseDateValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/title"},{"op":"replace","value":[{"text":"SMIFormResponseDateValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseDateValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateValue\/navigatorTitle"}]}]}