{"sections":[],"abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date and time."}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue\/dateTimeValue"],"anchor":"Instance-Properties"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormResponseDateTimeValue","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDateTimeValue"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseDateTimeValue"}],"title":"FormResponseDateTimeValue"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDateTimeValue"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to represent a form response that includes both date and time information."},{"type":"text","text":" "},{"type":"text","text":"The protocol extends "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"reference","isActive":true},{"type":"text","text":" to add support for datetime values, which are"},{"type":"text","text":" "},{"type":"text","text":"stored as "},{"type":"codeVoice","code":"NSDate"},{"type":"text","text":" objects. This type of response is typically used with date picker inputs"},{"type":"text","text":" "},{"type":"text","text":"that allow users to select both a date and time."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsedatetimevalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsedatetimevalue"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateTimeValue/dateTimeValue":{"url":"\/documentation\/smiclientcore\/formresponsedatetimevalue\/datetimevalue","kind":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue\/dateTimeValue","title":"dateTimeValue","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"type":"topic","abstract":[{"type":"text","text":"The date and time value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the complete datetime information selected by the user,"},{"type":"text","text":" "},{"type":"text","text":"including both the date and time components."}],"navigatorTitle":[{"kind":"identifier","text":"dateTimeValue"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateTimeValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue","kind":"symbol","title":"FormResponseDateTimeValue","abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date and time."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseDateTimeValue"}],"url":"\/documentation\/smiclientcore\/formresponsedatetimevalue","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseDateTimeValue"}],"role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"title":"FormResponseValue","abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponsevalue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormResponseDateTimeValue","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIFormResponseDateTimeValue","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseDateTimeValue"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue\/dateTimeValue"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseDateTimeValue","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"},{"text":">","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue~1dateTimeValue\/title","value":"dateTimeValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue~1dateTimeValue\/fragments","value":[{"kind":"identifier","text":"dateTimeValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/title","value":"SMIFormResponseDateTimeValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseDateTimeValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/navigatorTitle","value":[{"text":"SMIFormResponseDateTimeValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","value":"SMIFormResponseValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}