{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"FormSelectInput","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"externalID":"c:objc(pl)SMIFormSelectInput","modules":[{"name":"SMIClientCore"}],"title":"FormSelectInput"},"sections":[],"abstract":[{"type":"text","text":"A protocol that represents a select input field in a form that supports single or multiple selections."}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/value"],"title":"Instance Properties","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInput","text":"FormInput"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"Use this protocol to handle select inputs in forms. This protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","isActive":true,"type":"reference"},{"text":" to","type":"text"},{"text":" ","type":"text"},{"text":"provide functionality for selecting one or more options from a predefined list. Each option in","type":"text"},{"text":" ","type":"text"},{"text":"the list is represented by a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","isActive":true,"type":"reference"},{"text":" that contains both a title and a unique","type":"text"},{"text":" ","type":"text"},{"text":"identifier. The selection mode (single or multiple) is determined by the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"property.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formselectinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formselectinput"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/value":{"abstract":[{"type":"text","text":"The currently selected options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property holds the currently selected option items. It can be read to get the current"},{"type":"text","text":" "},{"type":"text","text":"selections and written to programmatically set new selections. The values must be from the"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","type":"reference","isActive":true},{"type":"text","text":" array. When "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","type":"reference","isActive":true},{"type":"text","text":" is "},{"code":"NO","type":"codeVoice"},{"type":"text","text":", this array should contain at most"},{"type":"text","text":" "},{"type":"text","text":"one item."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/value","navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","kind":"typeIdentifier","text":"FormInputOptionItem"},{"kind":"text","text":"]?"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formselectinput\/value"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/optionItems":{"type":"topic","url":"\/documentation\/smiclientcore\/formselectinput\/optionitems","title":"optionItems","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"abstract":[{"type":"text","text":"A list of selectable options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property contains the available options that can be selected in the input."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","isActive":true,"type":"reference"},{"type":"text","text":" that includes a title and identifier."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputoptionitem","title":"FormInputOptionItem","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"abstract":[{"text":"A protocol that defines a selectable option in a form that contains a title and unique identifier.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputOptionItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/multipleSelection":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/smiclientcore\/formselectinput\/multipleselection","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"multipleSelection"}],"abstract":[{"type":"text","text":"Determines whether this input allows for multiple selections."},{"type":"text","text":" "},{"type":"text","text":"When set to "},{"code":"YES","type":"codeVoice"},{"type":"text","text":", users can select multiple options from the list. When set to "},{"code":"NO","type":"codeVoice"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"only a single option can be selected at a time."}],"title":"multipleSelection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"navigatorTitle":[{"kind":"identifier","text":"FormInput"}],"title":"FormInput","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FormInput","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminput","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","role":"symbol","url":"\/documentation\/smiclientcore\/formselectinput","abstract":[{"text":"A protocol that represents a select input field in a form that supports single or multiple selections.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormSelectInput"}],"title":"FormSelectInput"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormSelectInput"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectInput"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIFormSelectInput","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/value"],"generated":true,"anchor":"Instance-Properties"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SMIFormSelectInput","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","text":"SMIFormInput","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/title","value":"optionItems"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/fragments","value":[{"text":"optionItems","kind":"identifier"}]},{"value":"SMIFormTitleOptionItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","op":"replace"},{"value":[{"text":"SMIFormTitleOptionItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","op":"replace"},{"op":"replace","value":"multipleSelection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/fragments","value":[{"text":"multipleSelection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput"},{"value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle"},{"value":"SMIFormSelectInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormSelectInput"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectInput"}]}]}]}