{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInput","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to handle form input fields in a conversation. This protocol serves as the base"},{"type":"text","text":" "},{"type":"text","text":"type for different kinds of form inputs, such as text fields, date pickers, option pickers, and"},{"type":"text","text":" "},{"type":"text","text":"select inputs. Each input type can be configured with a title, hint text, and validation rules."}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminput"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"kind":"symbol","metadata":{"title":"FormInput","symbolKind":"protocol","roleHeading":"Protocol","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInput","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FormInput"}],"externalID":"c:objc(pl)SMIFormInput"},"abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/hintText","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/inputType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/required"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/validate()"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/label":{"url":"\/documentation\/smiclientcore\/forminput\/label","navigatorTitle":[{"text":"label","kind":"identifier"}],"required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The title of this input."},{"type":"text","text":" "},{"type":"text","text":"This property provides the label or heading for the input field."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/label","type":"topic","title":"label","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/validate()":{"navigatorTitle":[{"text":"validate","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Use this validation to determine if the current value for this input is valid.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method checks if the input’s current value meets all validation requirements."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@SMIFormErrorType","text":"FormErrorType","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/validate()","type":"topic","title":"validate()","kind":"symbol","url":"\/documentation\/smiclientcore\/forminput\/validate()","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormOptionPickerInput":{"type":"topic","title":"FormOptionPickerInput","abstract":[{"type":"text","text":"A protocol that represents a single-selection option picker input field in a form."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormOptionPickerInput","kind":"identifier"}],"navigatorTitle":[{"text":"FormOptionPickerInput","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","kind":"symbol","url":"\/documentation\/smiclientcore\/formoptionpickerinput","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"title":"FormDatePickerInput","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"type":"topic","url":"\/documentation\/smiclientcore\/formdatepickerinput","role":"symbol","abstract":[{"text":"A protocol that represents a date picker input field in a form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput":{"url":"\/documentation\/smiclientcore\/formselectinput","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a select input field in a form that supports single or multiple selections."}],"title":"FormSelectInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"navigatorTitle":[{"kind":"identifier","text":"FormSelectInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/hintText":{"url":"\/documentation\/smiclientcore\/forminput\/hinttext","abstract":[{"text":"The text to help explain the purpose of the input.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides additional context or instructions for the input field.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"hintText","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hintText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"hintText","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/hintText"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/required":{"navigatorTitle":[{"text":"required","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/required","type":"topic","abstract":[{"text":"Determines whether this input is required for the form.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When set to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", the form cannot be submitted without a value for this input."}],"required":true,"title":"required","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/forminput\/required","kind":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/inputType":{"navigatorTitle":[{"text":"inputType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/inputType","type":"topic","abstract":[{"text":"The data type of the input.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the specific type of input field, such as text, date picker,","type":"text"},{"text":" ","type":"text"},{"text":"option picker, or select input.","type":"text"}],"required":true,"title":"inputType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"url":"\/documentation\/smiclientcore\/forminput\/inputtype","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"abstract":[{"type":"text","text":"A protocol that defines the base type for form input fields."}],"title":"FormInput","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/forminput","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","navigatorTitle":[{"kind":"identifier","text":"FormInput"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput":{"abstract":[{"text":"A protocol that represents a text input field in a form that supports various text input types and validation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTextInput","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput","title":"FormTextInput","navigatorTitle":[{"text":"FormTextInput","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formtextinput","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/identifier":{"abstract":[{"text":"The unique identifier for this input.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property is used to uniquely identify the input within a form."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/smiclientcore\/forminput\/identifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/identifier","title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"kind":"symbol","type":"topic","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormInput"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormInput","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormInput"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/hintText","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/inputType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/required"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/validate()"],"generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormOptionPickerInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput"],"title":"Inherited By"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInput"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"label","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1label\/title"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1label\/fragments"},{"op":"replace","value":"validate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1validate()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1validate()\/fragments"},{"op":"replace","value":"SMIFormOptionPickerInput","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/title"},{"op":"replace","value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/fragments"},{"op":"replace","value":[{"text":"SMIFormOptionPickerInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormOptionPickerInput\/navigatorTitle"},{"op":"replace","value":"SMIFormDatePickerInput","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title"},{"op":"replace","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments"},{"op":"replace","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle"},{"op":"replace","value":"SMIFormSelectInput","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectInput"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/fragments"},{"op":"replace","value":[{"text":"SMIFormSelectInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/navigatorTitle"},{"op":"replace","value":"hintText","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1hintText\/title"},{"op":"replace","value":[{"text":"hintText","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1hintText\/fragments"},{"op":"replace","value":"required","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1required\/title"},{"op":"replace","value":[{"text":"required","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1required\/fragments"},{"op":"replace","value":"inputType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1inputType\/title"},{"op":"replace","value":[{"text":"inputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1inputType\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments","value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/title","value":"SMIFormTextInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/fragments","value":[{"text":"SMIFormTextInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTextInput"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}