{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseTextValue"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormResponseValue","text":"FormResponseValue"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to represent a form response that includes text input."},{"type":"text","text":" "},{"type":"text","text":"The protocol extends "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"reference","isActive":true},{"type":"text","text":" to add support for string values,"},{"type":"text","text":" "},{"type":"text","text":"which are stored as "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":" objects. This type of response is typically used with"},{"type":"text","text":" "},{"type":"text","text":"text inputs that accept text."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsetextvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsetextvalue"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"A protocol that defines a form response value containing text.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"kind":"symbol","metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseTextValue","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormResponseTextValue","modules":[{"name":"SMIClientCore"}],"title":"FormResponseTextValue","symbolKind":"protocol","roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"text":"FormResponseTextValue","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue\/textValue"],"anchor":"Instance-Properties"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseTextValue":{"title":"FormResponseTextValue","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseTextValue"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormResponseTextValue"}],"abstract":[{"text":"A protocol that defines a form response value containing text.","type":"text"}],"url":"\/documentation\/smiclientcore\/formresponsetextvalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"title":"FormResponseValue","abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formresponsevalue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseTextValue/textValue":{"required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue\/textValue","abstract":[{"text":"The text value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the string entered by the user, stored as an ","type":"text"},{"code":"NSString","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The value can contain any text content, including letters, numbers, and special","type":"text"},{"text":" ","type":"text"},{"text":"characters, depending on the input field’s configuration.","type":"text"}],"title":"textValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"textValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponsetextvalue\/textvalue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormResponseTextValue","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue\/textValue"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormResponseTextValue","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormResponseTextValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/fragments","op":"replace"},{"value":[{"text":"SMIFormResponseTextValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/navigatorTitle","op":"replace"},{"value":"SMIFormResponseValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","op":"replace"},{"value":[{"text":"SMIFormResponseValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","op":"replace"},{"value":[{"text":"SMIFormResponseValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","op":"replace"},{"value":"textValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue~1textValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"textValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue~1textValue\/fragments","op":"replace"}]}]}