{"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/keyboardType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/maximumCharacterCount","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/placeholder","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/prefixText","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textContentType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textInputType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/value"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInput"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"FormInput","preciseIdentifier":"c:objc(pl)SMIFormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"}]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to handle text inputs in forms. This protocol extends ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"provide functionality for collecting and validating text input from users. It supports various"},{"type":"text","text":" "},{"text":"input types, including single-line and multi-line text, with configurable keyboard types,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"content types, and validation rules. The input can be configured with a maximum character count,"},{"type":"text","text":" "},{"type":"text","text":"placeholder text, and optional prefix text."}]}]}],"metadata":{"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInput"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"FormTextInput","roleHeading":"Protocol","navigatorTitle":[{"text":"FormTextInput","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormTextInput"},"abstract":[{"text":"A protocol that represents a text input field in a form that supports various text input types and validation.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtextinput"]},{"paths":["\/documentation\/smiclientcore\/formtextinput"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType":{"url":"\/documentation\/smiclientcore\/formtextinputtype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormTextInputType"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An enum that defines the types of text input fields available in forms."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}],"title":"FormTextInputType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/textContentType":{"required":true,"kind":"symbol","url":"\/documentation\/smiclientcore\/formtextinput\/textcontenttype","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textContentType","role":"symbol","abstract":[{"text":"The content type for this input.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property helps the system provide appropriate keyboard and validation for specific"},{"type":"text","text":" "},{"text":"types of content, such as email addresses or URLs.","type":"text"}],"title":"textContentType","navigatorTitle":[{"kind":"identifier","text":"textContentType"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textContentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UITextContentType","text":"UITextContentType","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/maximumCharacterCount":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumCharacterCount"}],"type":"topic","title":"maximumCharacterCount","abstract":[{"type":"text","text":"The maximum number of characters this text input accepts."},{"type":"text","text":" "},{"type":"text","text":"This property sets an upper limit on the length of text that can be entered."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/maximumCharacterCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maximumCharacterCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"required":true,"url":"\/documentation\/smiclientcore\/formtextinput\/maximumcharactercount","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"navigatorTitle":[{"kind":"identifier","text":"FormInput"}],"title":"FormInput","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FormInput","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminput","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/keyboardType":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/keyboardType","url":"\/documentation\/smiclientcore\/formtextinput\/keyboardtype","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The suggested keyboard type which should be used to collect input from the user."},{"type":"text","text":" "},{"text":"This property determines the type of keyboard that appears when the input is focused.","type":"text"}],"title":"keyboardType","navigatorTitle":[{"kind":"identifier","text":"keyboardType"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardType","preciseIdentifier":"c:@E@UIKeyboardType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FormTextInput","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formtextinput","title":"FormTextInput","role":"symbol","navigatorTitle":[{"text":"FormTextInput","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a text input field in a form that supports various text input types and validation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/textInputType":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textInputType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The type of text expected for this input."},{"text":" ","type":"text"},{"type":"text","text":"This property determines whether the input accepts single-line or multi-line text."},{"type":"text","text":" "},{"text":"See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"},{"type":"text","text":" for available text input types."}],"navigatorTitle":[{"kind":"identifier","text":"textInputType"}],"url":"\/documentation\/smiclientcore\/formtextinput\/textinputtype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textInputType","title":"textInputType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/prefixText":{"url":"\/documentation\/smiclientcore\/formtextinput\/prefixtext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/prefixText","abstract":[{"text":"Text which is prefixed to the final output value.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property allows for adding a fixed prefix to the user’s input."}],"role":"symbol","navigatorTitle":[{"text":"prefixText","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prefixText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"required":true,"type":"topic","title":"prefixText"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/placeholder":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/smiclientcore\/formtextinput\/placeholder","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"abstract":[{"type":"text","text":"Placeholder text displayed to users when the input is empty."},{"type":"text","text":" "},{"type":"text","text":"This property provides a hint or example of the expected input."}],"title":"placeholder","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/placeholder"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInput/value":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/value","title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"abstract":[{"text":"The current text value for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property holds the text entered by the user. It can be read to get the current","type":"text"},{"text":" ","type":"text"},{"text":"value and written to programmatically set a new value.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/formtextinput\/value","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormTextInput"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormTextInput"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIFormTextInput","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/keyboardType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/maximumCharacterCount","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/placeholder","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/prefixText","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textContentType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/textInputType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInput\/value"],"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SMIFormTextInput","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","text":"SMIFormInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInput"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/title","value":"SMIFormTextInputType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/fragments","value":[{"kind":"identifier","text":"SMIFormTextInputType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/navigatorTitle","value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textContentType\/title","value":"textContentType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textContentType\/fragments","value":[{"text":"textContentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1maximumCharacterCount\/title","value":"maximumCharacterCount","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1maximumCharacterCount\/fragments","value":[{"text":"maximumCharacterCount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1keyboardType\/title","value":"keyboardType"},{"op":"replace","value":[{"text":"keyboardType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1keyboardType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/title","value":"SMIFormTextInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/fragments","value":[{"text":"SMIFormTextInput","kind":"identifier"}]},{"value":[{"text":"SMIFormTextInput","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput\/navigatorTitle","op":"replace"},{"value":"textInputType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textInputType\/title","op":"replace"},{"value":[{"text":"textInputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1textInputType\/fragments","op":"replace"},{"value":"prefixText","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1prefixText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"prefixText"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1prefixText\/fragments","op":"replace"},{"value":"placeholder","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"placeholder"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1placeholder\/fragments","op":"replace"},{"value":"value","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1value\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInput~1value\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]}]}]}