{"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/collectValues","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/confirm","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/inputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/response"],"anchor":"Instance-Properties","generated":true}],"metadata":{"symbolKind":"protocol","externalID":"c:objc(pl)SMIFormExperienceType","role":"symbol","roleHeading":"Protocol","title":"FormExperienceType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormExperienceType","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"FormExperienceType","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormExperienceType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","text":"EntryTypeFormMessage"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"All properties and features which are exposed in this class are subject to change.","type":"text"}]}],"name":"Note","type":"aside"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"text":"Experimental features\/APIs may be removed without advanced notification at any time.","type":"text"},{"text":" ","type":"text"},{"text":"Any use of these features will ","type":"text"},{"inlineContent":[{"type":"text","text":"NOT"}],"type":"strong"},{"text":" be offered any official support, until such time as they may be adopted as full and stable features.","type":"text"}]}],"name":"Warning","type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formexperiencetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formexperiencetype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/response":{"abstract":[{"type":"text","text":"nil until the form has been sent. The "},{"code":"inputValues","type":"codeVoice"},{"type":"text","text":" array of the response will be populated with the content of the "},{"code":"collectValues","type":"codeVoice"},{"type":"text","text":" array."}],"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/response","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormExperienceTypeResponse","text":"FormExperienceTypeResponse","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/smiclientcore\/formexperiencetype\/response","title":"response","kind":"symbol","navigatorTitle":[{"text":"response","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/collectValues":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectValues"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]!"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectValues"}],"title":"collectValues","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/collectValues","required":true,"abstract":[{"type":"text","text":"An array containing dictionaries representing form responses."},{"type":"text","text":" "},{"type":"text","text":"The intention is to return a value for each entry in the "},{"code":"inputs","type":"codeVoice"},{"type":"text","text":" property."},{"type":"text","text":" "},{"type":"text","text":"This array is only intended for collection of data. It is not persisted on this entry."},{"type":"text","text":" "},{"type":"text","text":"However upon sending this form entry, a "},{"code":"SMIFormExperienceTypeResponse","type":"codeVoice"},{"type":"text","text":" will be created and persisted with the collected data."}],"type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetype\/collectvalues"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/confirm":{"required":true,"title":"confirm","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirm"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConfirmExperienceType","kind":"typeIdentifier","text":"ConfirmExperienceType"},{"kind":"text","text":")?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"confirm"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetype\/confirm","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/confirm"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormMessage":{"url":"\/documentation\/smiclientcore\/entrytypeformmessage","navigatorTitle":[{"text":"EntryTypeFormMessage","kind":"identifier"}],"kind":"symbol","type":"topic","title":"EntryTypeFormMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","abstract":[{"type":"text","text":"A protocol that defines the base type for form messages in a conversation."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeFormMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetype","navigatorTitle":[{"kind":"identifier","text":"FormExperienceType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormExperienceType"}],"abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"title":"FormExperienceType","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"type":"topic","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}],"kind":"symbol","title":"EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/inputs":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/inputs","navigatorTitle":[{"kind":"identifier","text":"inputs"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputs"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]"}],"title":"inputs","kind":"symbol","abstract":[],"required":true,"type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetype\/inputs"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/message":{"required":true,"type":"topic","abstract":[],"url":"\/documentation\/smiclientcore\/formexperiencetype\/message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"message","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"message"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/message"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormExperienceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormExperienceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIFormExperienceType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/collectValues","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/confirm","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/inputs","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/response"],"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormExperienceType"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIEntryTypeFormMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1response\/title","value":"response"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1response\/fragments","value":[{"kind":"identifier","text":"response"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1collectValues\/title","value":"collectValues"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1collectValues\/fragments","value":[{"text":"collectValues","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1confirm\/title","value":"confirm"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1confirm\/fragments","value":[{"text":"confirm","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/title","value":"SMIEntryTypeFormMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/fragments","value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title","value":"SMIFormExperienceType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments","value":[{"text":"SMIFormExperienceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormExperienceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1inputs\/title","value":"inputs"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1inputs\/fragments","value":[{"text":"inputs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1message\/fragments","value":[{"text":"message","kind":"identifier"}]}]}]}