{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formrecordresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formrecordresult"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"FormRecordResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormRecordResult"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"FormRecordResult","symbolKind":"protocol","externalID":"c:objc(pl)SMIFormRecordResult"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents a record that has been created or updated as a result of a form submission."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/isCreated","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/recordReferenceId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/resultMessage"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access information about records that were affected by a form submission.","type":"text"},{"text":" ","type":"text"},{"text":"This protocol provides details about whether the record was newly created or updated,","type":"text"},{"text":" ","type":"text"},{"text":"its unique identifier, and any associated result message. This information is typically","type":"text"},{"text":" ","type":"text"},{"text":"used to track the outcome of form submissions and handle the created or updated data.","type":"text"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult/recordReferenceId":{"abstract":[{"type":"text","text":"The ID for the relevant record."},{"type":"text","text":" "},{"type":"text","text":"This property provides the unique identifier for the record that was created or"},{"type":"text","text":" "},{"type":"text","text":"updated as a result of the form submission. Use this ID to reference the record"},{"type":"text","text":" "},{"type":"text","text":"in subsequent operations."}],"required":true,"kind":"symbol","title":"recordReferenceId","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/recordReferenceId","role":"symbol","url":"\/documentation\/smiclientcore\/formrecordresult\/recordreferenceid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordReferenceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"recordReferenceId","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"FormRecordResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","url":"\/documentation\/smiclientcore\/formrecordresult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordResult","kind":"identifier"}],"title":"FormRecordResult","abstract":[{"text":"A protocol that represents a record that has been created or updated as a result of a form submission.","type":"text"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult/isCreated":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCreated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isCreated"}],"url":"\/documentation\/smiclientcore\/formrecordresult\/iscreated","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/isCreated","abstract":[{"type":"text","text":"Indicates whether a record has been created as a result of form submission."},{"type":"text","text":" "},{"type":"text","text":"This property is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the record was newly created during the form submission,"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"NO"},{"type":"text","text":" if an existing record was updated."}],"kind":"symbol","title":"isCreated","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult/resultMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/resultMessage","abstract":[{"type":"text","text":"A message generated as a result of the creation of the record."},{"type":"text","text":" "},{"type":"text","text":"This optional property contains any additional information or feedback about the"},{"type":"text","text":" "},{"type":"text","text":"record creation or update process."}],"url":"\/documentation\/smiclientcore\/formrecordresult\/resultmessage","title":"resultMessage","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resultMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"resultMessage","kind":"identifier"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormRecordResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIFormRecordResult","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormRecordResult"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/isCreated","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/recordReferenceId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/resultMessage"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormRecordResult","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"recordReferenceId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1recordReferenceId\/title","op":"replace"},{"value":[{"text":"recordReferenceId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1recordReferenceId\/fragments","op":"replace"},{"value":"SMIFormRecordResult","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormRecordResult"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/fragments","op":"replace"},{"value":[{"text":"SMIFormRecordResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/navigatorTitle","op":"replace"},{"value":"isCreated","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1isCreated\/title","op":"replace"},{"value":[{"text":"isCreated","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1isCreated\/fragments","op":"replace"},{"value":"resultMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1resultMessage\/title","op":"replace"},{"value":[{"text":"resultMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1resultMessage\/fragments","op":"replace"}]}]}