{"variants":[{"paths":["\/documentation\/smiclientcore\/formresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresult"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"FormResult","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormResult","symbolKind":"protocol","title":"FormResult","roleHeading":"Protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResult","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"],"type":"inheritedBy","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to handle the results of form submissions. This protocol serves as the","type":"text"},{"text":" ","type":"text"},{"text":"base type for different kinds of form results, which can indicate either successful","type":"text"},{"text":" ","type":"text"},{"text":"submissions with created\/updated records or failed submissions with error details.","type":"text"},{"text":" ","type":"text"},{"text":"The specific type of result is determined by the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult\/resultType"},{"text":" property.","type":"text"}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult\/resultType"],"generated":true}],"kind":"symbol","abstract":[{"text":"A protocol that defines the base type for form submission results.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorResult":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorResult","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FormErrorResult","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrorresult","abstract":[{"type":"text","text":"A protocol that represents a failed form submission with error details."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult","title":"FormErrorResult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordsResult":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult","abstract":[{"type":"text","text":"A protocol that represents a successful form submission with created or updated records."}],"title":"FormRecordsResult","url":"\/documentation\/smiclientcore\/formrecordsresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormRecordsResult"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormRecordsResult"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResult/resultType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormResponseResultType","preciseIdentifier":"c:SMIFormResultType.h@T@SMIFormResultType"}],"title":"resultType","navigatorTitle":[{"kind":"identifier","text":"resultType"}],"abstract":[{"type":"text","text":"The type of result response."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of form result, which can be either a"},{"type":"text","text":" "},{"type":"text","text":"successful submission with records or a failed submission with errors."}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult\/resultType","url":"\/documentation\/smiclientcore\/formresult\/resulttype","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResult":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formresult","navigatorTitle":[{"text":"FormResult","kind":"identifier"}],"title":"FormResult","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","abstract":[{"type":"text","text":"A protocol that defines the base type for form submission results."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResult","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIFormResult","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIFormResult","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult\/resultType"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResult"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/title","value":"SMIFormErrorResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/fragments","value":[{"text":"SMIFormErrorResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/navigatorTitle","value":[{"text":"SMIFormErrorResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/title","value":"SMIFormRecordsResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/fragments","value":[{"kind":"identifier","text":"SMIFormRecordsResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/navigatorTitle","value":[{"text":"SMIFormRecordsResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult~1resultType\/title","value":"resultType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult~1resultType\/fragments","value":[{"kind":"identifier","text":"resultType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/title","value":"SMIFormResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/fragments","value":[{"text":"SMIFormResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/navigatorTitle","value":[{"text":"SMIFormResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}