{"sections":[],"abstract":[{"text":"A protocol that defines the base type for form input sections.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputSection"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Use this protocol to handle form input sections in a conversation. This protocol serves as the base","type":"text"},{"text":" ","type":"text"},{"text":"type for different kinds of form sections, such as single input sections. Each section type can be","type":"text"},{"text":" ","type":"text"},{"text":"configured to collect specific types of user input and control the flow of the form. The section","type":"text"},{"text":" ","type":"text"},{"text":"type determines how the input is presented and collected from the user.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/forminputsection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputsection"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection\/sectionType"],"title":"Instance Properties"}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"FormInputSection","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMIFormInputSection","title":"FormInputSection","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormInputSection"}],"role":"symbol"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection"],"type":"inheritedBy"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection/sectionType":{"abstract":[{"type":"text","text":"The type of input contained in this section."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of section, which affects how the input is"},{"type":"text","text":" "},{"type":"text","text":"presented and collected. See "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","isActive":true},{"type":"text","text":" for available section types."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection\/sectionType","navigatorTitle":[{"text":"sectionType","kind":"identifier"}],"title":"sectionType","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sectionType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType","text":"FormInputSectionType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/forminputsection\/sectiontype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection":{"title":"FormInputSection","abstract":[{"text":"A protocol that defines the base type for form input sections.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminputsection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputSection","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputSection","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSingleInputSection":{"abstract":[{"text":"A protocol that represents a section in a form that collects a single input value from the user.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormSingleInputSection"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection","title":"FormSingleInputSection","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormSingleInputSection","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formsingleinputsection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputsectiontype","title":"FormInputSectionType","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","navigatorTitle":[{"text":"FormInputSectionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the types of form input sections available in the system."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputSectionType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormInputSection","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIFormInputSection","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormInputSection"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection\/sectionType"],"anchor":"Instance-Properties","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSingleInputSection"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInputSection"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"sectionType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection~1sectionType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sectionType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection~1sectionType\/fragments"},{"op":"replace","value":"SMIFormInputSection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/title"},{"op":"replace","value":[{"text":"SMIFormInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormInputSection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/navigatorTitle"},{"op":"replace","value":"SMIFormSingleInputSection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormSingleInputSection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormSingleInputSection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSingleInputSection\/navigatorTitle"},{"op":"replace","value":"SMIFormInputSectionType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/title"},{"op":"replace","value":[{"text":"SMIFormInputSectionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/fragments"},{"op":"replace","value":[{"text":"SMIFormInputSectionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/navigatorTitle"}]}]}