{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValueType","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseValueType","kind":"identifier"}],"role":"symbol","externalID":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","modules":[{"name":"SMIClientCore"}],"title":"FormResponseValueType","symbolKind":"struct","roleHeading":"Structure"},"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsevaluetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsevaluetype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An enum that defines the types of values that can be submitted in a form response."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValueType","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Possible-Values","type":"heading","text":"Possible Values"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/textValue"},{"type":"text","text":" - Represents a text value in a form response"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/urlValue","type":"reference"},{"text":" - Represents a URL value in a form response","type":"text"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/doubleValue"},{"text":" - Represents a double-precision number in a form response","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/integerValue"},{"type":"text","text":" - Represents an integer value in a form response"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateValue"},{"type":"text","text":" - Represents a date value in a form response"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateTimeValue","isActive":true},{"type":"text","text":" - Represents a date and time value in a form response"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to identify the type of value being submitted in a form response."},{"type":"text","text":" "},{"type":"text","text":"The type determines how the value should be interpreted and processed. Each type"},{"type":"text","text":" "},{"type":"text","text":"corresponds to a specific data type that can be submitted in a form."}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateTimeValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/doubleValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/integerValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/textValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/urlValue"],"generated":true,"anchor":"Type-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/urlValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/urlValue","title":"urlValue","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseValueTypeURLValue"}],"abstract":[{"text":"A URL response.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/formresponsevaluetype\/urlvalue","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormResponseValueType","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType"}]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType":{"abstract":[{"type":"text","text":"An enum that defines the types of values that can be submitted in a form response."}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValueType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","title":"FormResponseValueType","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseValueType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsevaluetype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/dateTimeValue":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType"}],"abstract":[{"type":"text","text":"A datetime response."}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseValueTypeDateTimeValue"}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/datetimevalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateTimeValue","title":"dateTimeValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsevaluetype\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/integerValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/integerValue","title":"integerValue","navigatorTitle":[{"text":"SMIFormResponseValueTypeIntegerValue","kind":"identifier"}],"abstract":[{"text":"An integer response.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/formresponsevaluetype\/integervalue","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"integerValue"},{"text":": ","kind":"text"},{"text":"FormResponseValueType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/doubleValue":{"abstract":[{"type":"text","text":"A double type response."}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseValueTypeDoubleValue"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/doubleValue","title":"doubleValue","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsevaluetype\/doublevalue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/textValue":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/textValue","role":"symbol","url":"\/documentation\/smiclientcore\/formresponsevaluetype\/textvalue","abstract":[{"type":"text","text":"A text response."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIFormResponseValueTypeTextValue"}],"title":"textValue"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType/dateValue":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType"}],"abstract":[{"type":"text","text":"A date response."}],"navigatorTitle":[{"text":"SMIFormResponseValueTypeDateValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype\/datevalue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType\/dateValue","title":"dateValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"value":"SMIFormResponseValueType","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIFormResponseValueType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"SMIFormResponseValueType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1urlValue\/title","op":"replace","value":"SMIFormResponseValueTypeURLValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1urlValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseValueTypeURLValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/title","op":"replace","value":"SMIFormResponseValueType"},{"value":[{"text":"SMIFormResponseValueType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/navigatorTitle"},{"value":"SMIFormResponseValueTypeDateTimeValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1dateTimeValue\/title"},{"value":[{"text":"SMIFormResponseValueTypeDateTimeValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1dateTimeValue\/fragments"},{"op":"replace","value":"SMIFormResponseValueTypeIntegerValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1integerValue\/title"},{"op":"replace","value":[{"text":"SMIFormResponseValueTypeIntegerValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1integerValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1doubleValue\/title","value":"SMIFormResponseValueTypeDoubleValue"},{"value":[{"kind":"identifier","text":"SMIFormResponseValueTypeDoubleValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1doubleValue\/fragments"},{"value":"SMIFormResponseValueTypeTextValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1textValue\/title"},{"value":[{"kind":"identifier","text":"SMIFormResponseValueTypeTextValue"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1textValue\/fragments"},{"value":"SMIFormResponseValueTypeDateValue","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1dateValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType~1dateValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueTypeDateValue"}]}]}]}