{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"An enum that defines the types of text input fields available in forms.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"},"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/init(rawValue:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/multiline","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/singleline"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/Equatable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Possible Values","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/singleline","type":"reference"},{"text":" - Represents a text input field that displays and accepts text on a single line","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/multiline","type":"reference","isActive":true},{"text":" - Represents a text input field that displays and accepts text across multiple lines","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to specify how text input fields should be presented to users."},{"type":"text","text":" "},{"type":"text","text":"The type determines whether the input field should be displayed as a single line"},{"type":"text","text":" "},{"type":"text","text":"or multiple lines, which affects the user interface and input behavior."}]}],"kind":"content"}],"metadata":{"role":"symbol","roleHeading":"Structure","externalID":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","symbolKind":"struct","title":"FormTextInputType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"FormTextInputType"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/formtextinputtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtextinputtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/multiline":{"navigatorTitle":[{"text":"SMIFormTextInputTypeMultiline","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/multiline","kind":"symbol","abstract":[{"type":"text","text":"Represents a text input field that displays and accepts text across multiple lines."},{"type":"text","text":" "},{"type":"text","text":"This type is used when you need to collect longer, more detailed text input from users."}],"url":"\/documentation\/smiclientcore\/formtextinputtype\/multiline","title":"multiline","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiline","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","text":"FormTextInputType","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/formtextinputtype\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/init(rawValue:)","abstract":[]},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/smiclientcore\/formtextinputtype\/equatable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/singleline":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/singleline","type":"topic","kind":"symbol","title":"singleline","abstract":[{"type":"text","text":"Represents a text input field that displays and accepts text on a single line."},{"type":"text","text":" "},{"type":"text","text":"This type is used when you need to collect short, concise text input from users."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/formtextinputtype\/singleline","navigatorTitle":[{"text":"SMIFormTextInputTypeSingleline","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType":{"kind":"symbol","abstract":[{"text":"An enum that defines the types of text input fields available in forms.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtextinputtype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTextInputType","kind":"identifier"}],"navigatorTitle":[{"text":"FormTextInputType","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","title":"FormTextInputType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFormTextInputType","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormTextInputType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormTextInputTypeMultiline","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1multiline\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTextInputTypeMultiline"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1multiline\/fragments"},{"op":"replace","value":"SMIFormTextInputTypeSingleline","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1singleline\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTextInputTypeSingleline"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1singleline\/fragments"},{"op":"replace","value":"SMIFormTextInputType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/title"},{"op":"replace","value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/fragments"},{"op":"replace","value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}