{"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Structure","navigatorTitle":[{"text":"FormInputValueType","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputValueType","kind":"identifier"}],"externalID":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","title":"FormInputValueType","role":"symbol","symbolKind":"struct"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"An enum that defines the types of values that can be collected from form inputs.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputValueType","kind":"identifier"}]}]},{"content":[{"text":"Possible Values","type":"heading","level":2,"anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/singleInputValue","isActive":true},{"type":"text","text":" - Represents a single value input from a form field"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/selectedOptionsInputValue","isActive":true},{"type":"text","text":" - Represents a collection of selected options from a form input"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This enum is used to specify how form input values should be structured and handled.","type":"text"},{"text":" ","type":"text"},{"text":"The type determines whether the input value represents a single value or a collection","type":"text"},{"text":" ","type":"text"},{"text":"of selected options, affecting how the value is stored and processed in the form system.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputvaluetype"]}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/selectedOptionsInputValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/singleInputValue"],"generated":true,"anchor":"Type-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/_SwiftNewtypeWrapper-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/selectedOptionsInputValue":{"navigatorTitle":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a collection of selected options from a form input."},{"type":"text","text":" "},{"type":"text","text":"This type is used when the form input allows users to select one or more options,"},{"type":"text","text":" "},{"type":"text","text":"such as in a multi-select dropdown or checkbox group."}],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/selectedoptionsinputvalue","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedOptionsInputValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"FormInputValueType","kind":"typeIdentifier"}],"title":"selectedOptionsInputValue","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/selectedOptionsInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/_SwiftNewtypeWrapper-Implementations":{"title":"_SwiftNewtypeWrapper Implementations","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/_SwiftNewtypeWrapper-Implementations","type":"topic","kind":"article","url":"\/documentation\/smiclientcore\/forminputvaluetype\/_swiftnewtypewrapper-implementations","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType":{"title":"FormInputValueType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputValueType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of values that can be collected from form inputs."}],"navigatorTitle":[{"text":"FormInputValueType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","kind":"symbol","url":"\/documentation\/smiclientcore\/forminputvaluetype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/singleInputValue":{"navigatorTitle":[{"text":"SMIFormInputValueTypeSingleInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a single value input from a form field."},{"type":"text","text":" "},{"type":"text","text":"This type is used when the form input collects a single value, such as text input,"},{"type":"text","text":" "},{"type":"text","text":"date picker, or single-selection option picker."}],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/singleinputvalue","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleInputValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","text":"FormInputValueType","kind":"typeIdentifier"}],"title":"singleInputValue","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/singleInputValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/init(rawValue:)":{"abstract":[],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/smiclientcore\/forminputvaluetype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType\/Equatable-Implementations"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIFormInputValueType","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputValueType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputValueType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIFormInputValueType"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIFormInputValueTypeSelectedOptionsInputValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1selectedOptionsInputValue\/title","op":"replace"},{"value":[{"text":"SMIFormInputValueTypeSelectedOptionsInputValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1selectedOptionsInputValue\/fragments","op":"replace"},{"value":"SMIFormInputValueType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputValueType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormInputValueType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/navigatorTitle","op":"replace"},{"value":"SMIFormInputValueTypeSingleInputValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1singleInputValue\/title","op":"replace"},{"value":[{"text":"SMIFormInputValueTypeSingleInputValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType~1singleInputValue\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}