{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/formrecordsresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formrecordsresult"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormRecordsResult","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormRecordsResult"}],"navigatorTitle":[{"text":"FormRecordsResult","kind":"identifier"}],"title":"FormRecordsResult","role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol"},"abstract":[{"type":"text","text":"A protocol that represents a successful form submission with created or updated records."}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult\/records"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormRecordsResult"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","preciseIdentifier":"c:objc(pl)SMIFormResult","kind":"typeIdentifier","text":"FormResult"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Use this protocol to handle successful form submissions that result in the creation or"},{"type":"text","text":" "},{"type":"text","text":"update of records. Each record in the result contains information about the created or updated data."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"},"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordsResult":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordsResult","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A protocol that represents a successful form submission with created or updated records.","type":"text"}],"url":"\/documentation\/smiclientcore\/formrecordsresult","navigatorTitle":[{"text":"FormRecordsResult","kind":"identifier"}],"title":"FormRecordsResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResult":{"navigatorTitle":[{"text":"FormResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResult","kind":"identifier"}],"abstract":[{"text":"A protocol that defines the base type for form submission results.","type":"text"}],"title":"FormResult","url":"\/documentation\/smiclientcore\/formresult","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordsResult/records":{"abstract":[{"type":"text","text":"The list of objects representing successful submission of the form."},{"type":"text","text":" "},{"type":"text","text":"This array contains the records that were created or updated as a result of the"},{"type":"text","text":" "},{"type":"text","text":"form submission. Each record includes details about the changes made."}],"navigatorTitle":[{"text":"records","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formrecordsresult\/records","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult\/records","required":true,"title":"records","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"records","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormRecordResult","preciseIdentifier":"c:objc(pl)SMIFormRecordResult","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormRecordsResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormRecordsResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormRecordsResult"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordsResult\/records"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormRecordsResult"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResult","preciseIdentifier":"c:objc(pl)SMIFormResult","text":"SMIFormResult"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/title","value":"SMIFormRecordsResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/fragments","value":[{"text":"SMIFormRecordsResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult\/navigatorTitle","value":[{"text":"SMIFormRecordsResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/title","value":"SMIFormResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/fragments","value":[{"kind":"identifier","text":"SMIFormResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResult\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult~1records\/title","value":"records"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordsResult~1records\/fragments","value":[{"kind":"identifier","text":"records"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}