{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleitem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtitleitem"]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to define title components that can be displayed in various parts of a form,"},{"type":"text","text":" "},{"type":"text","text":"such as form headers, input labels, or option titles. Each title item consists of a required"},{"type":"text","text":" "},{"type":"text","text":"main title and optional subtitles that can provide additional context or hierarchy."}]}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"FormTitleItem","externalID":"c:objc(pl)SMIFormTitleItem","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}]},"kind":"symbol","topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/itemType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/referenceId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/secondarySubTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/subTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/tertiarySubTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/title"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/tertiarySubTitle":{"navigatorTitle":[{"text":"tertiarySubTitle","kind":"identifier"}],"required":true,"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tertiarySubTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"tertiarySubTitle","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/tertiarySubTitle","url":"\/documentation\/smiclientcore\/formtitleitem\/tertiarysubtitle","abstract":[{"text":"Optional tertiary subtitle for this item.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This provides a third level of additional information or context."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/itemType":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","text":"FormTitleItemType","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/formtitleitem\/itemtype","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/itemType","abstract":[{"text":"The type of title item this object represents.","type":"text"},{"text":" ","type":"text"},{"text":"This property identifies the specific type of title component.","type":"text"}],"role":"symbol","title":"itemType","navigatorTitle":[{"text":"itemType","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/referenceId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/referenceId","title":"referenceId","role":"symbol","abstract":[{"type":"text","text":"Unique optional reference identifier for this item."},{"type":"text","text":" "},{"type":"text","text":"This can be used to associate the title item with other components or data."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"referenceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/smiclientcore\/formtitleitem\/referenceid","navigatorTitle":[{"kind":"identifier","text":"referenceId"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/subTitle":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem\/subtitle","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/subTitle","role":"symbol","title":"subTitle","required":true,"abstract":[{"type":"text","text":"Optional subtitle for this item."},{"type":"text","text":" "},{"type":"text","text":"This provides additional context or information below the main title."}],"navigatorTitle":[{"text":"subTitle","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/title":{"title":"title","abstract":[{"type":"text","text":"The required title description for this item."},{"type":"text","text":" "},{"type":"text","text":"This is the main text that will be displayed as the primary title."}],"required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/title","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formtitleitem\/title"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleImageItem":{"title":"TitleImageItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem","url":"\/documentation\/smiclientcore\/titleimageitem","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a title item with an associated image in a carousel or form."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TitleImageItem"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleImageItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/secondarySubTitle":{"abstract":[{"text":"Optional secondary subtitle for this item.","type":"text"},{"text":" ","type":"text"},{"text":"This provides a second level of additional information or context.","type":"text"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondarySubTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"secondarySubTitle","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/secondarySubTitle","url":"\/documentation\/smiclientcore\/formtitleitem\/secondarysubtitle","type":"topic","navigatorTitle":[{"text":"secondarySubTitle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormTitleItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/itemType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/referenceId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/secondarySubTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/subTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/tertiarySubTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/title"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem"],"type":"inheritedBy","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormTitleItem","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1tertiarySubTitle\/title","value":"tertiarySubTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1tertiarySubTitle\/fragments","value":[{"kind":"identifier","text":"tertiarySubTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1itemType\/title","value":"itemType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1itemType\/fragments","value":[{"kind":"identifier","text":"itemType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1referenceId\/title","value":"referenceId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1referenceId\/fragments","value":[{"text":"referenceId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1subTitle\/title","value":"subTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1subTitle\/fragments","value":[{"kind":"identifier","text":"subTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/title","value":"SMITitleImageItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/fragments","value":[{"text":"SMITitleImageItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/navigatorTitle","value":[{"text":"SMITitleImageItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1secondarySubTitle\/title","value":"secondarySubTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1secondarySubTitle\/fragments","value":[{"kind":"identifier","text":"secondarySubTitle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}