{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"metadata":{"title":"FormDatePickerInput","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIFormDatePickerInput","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/formdatepickerinput"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formdatepickerinput"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/isDateAndTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/maximumDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/minimumDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/startDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/value"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormDatePickerInput","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormInput","text":"FormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"text":"Use this protocol to handle date selection inputs in forms. This protocol extends ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","type":"reference"},{"text":" ","type":"text"},{"text":"to provide functionality for date and time selection. The input can be configured to accept","type":"text"},{"text":" ","type":"text"},{"text":"either just dates or both dates and times, with optional constraints on the selectable range","type":"text"},{"text":" ","type":"text"},{"text":"and a default value.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A protocol that represents a date picker input field in a form."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/dateFormat":{"required":true,"url":"\/documentation\/smiclientcore\/formdatepickerinput\/dateformat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"dateFormat"}],"title":"dateFormat","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","abstract":[{"text":"Required. The string format of the date.","type":"text"},{"text":" ","type":"text"},{"text":"This property defines how the date should be formatted when displayed or submitted.","type":"text"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/isDateAndTime":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/isDateAndTime","title":"isDateAndTime","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isDateAndTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A flag that indicates whether the date picker includes time selection."},{"type":"text","text":" "},{"type":"text","text":"This property is automatically determined based on the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"isDateAndTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formdatepickerinput\/isdateandtime"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/minimumDate":{"navigatorTitle":[{"kind":"identifier","text":"minimumDate"}],"type":"topic","abstract":[{"text":"The earliest allowable date this input accepts.","type":"text"},{"text":" ","type":"text"},{"text":"This property sets a lower bound on the selectable dates. If not set, there is no minimum date limit.","type":"text"}],"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"title":"minimumDate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/minimumDate","url":"\/documentation\/smiclientcore\/formdatepickerinput\/minimumdate","role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/value":{"role":"symbol","title":"value","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The current value of the date for this input."},{"type":"text","text":" "},{"type":"text","text":"This property holds the currently selected date and time (if applicable). It can be"},{"type":"text","text":" "},{"type":"text","text":"read to get the current selection and written to programmatically set a new value."}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/value","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/smiclientcore\/formdatepickerinput\/value"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/startDate":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"startDate","required":true,"abstract":[{"text":"The initial default value for the date assigned to this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a starting value for the date picker. If not set, no default date is selected.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"startDate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/startDate","url":"\/documentation\/smiclientcore\/formdatepickerinput\/startdate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormDatePickerInput"}],"title":"FormDatePickerInput","navigatorTitle":[{"kind":"identifier","text":"FormDatePickerInput"}],"type":"topic","url":"\/documentation\/smiclientcore\/formdatepickerinput","role":"symbol","abstract":[{"text":"A protocol that represents a date picker input field in a form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"abstract":[{"type":"text","text":"A protocol that defines the base type for form input fields."}],"title":"FormInput","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/forminput","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","navigatorTitle":[{"kind":"identifier","text":"FormInput"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormDatePickerInput/maximumDate":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formdatepickerinput\/maximumdate","abstract":[{"text":"The latest allowable date this input accepts.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This property sets an upper bound on the selectable dates. If not set, there is no maximum date limit."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/maximumDate","navigatorTitle":[{"kind":"identifier","text":"maximumDate"}],"title":"maximumDate","role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormDatePickerInput","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/dateFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/isDateAndTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/maximumDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/minimumDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/startDate","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormDatePickerInput\/value"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormDatePickerInput","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","text":"SMIFormInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormInput"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1dateFormat\/title","value":"dateFormat","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1dateFormat\/fragments","value":[{"text":"dateFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1isDateAndTime\/title","value":"isDateAndTime","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1isDateAndTime\/fragments","value":[{"kind":"identifier","text":"isDateAndTime"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1minimumDate\/title","value":"minimumDate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1minimumDate\/fragments","value":[{"kind":"identifier","text":"minimumDate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1startDate\/title","value":"startDate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1startDate\/fragments","value":[{"text":"startDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/title","value":"SMIFormDatePickerInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/fragments","value":[{"kind":"identifier","text":"SMIFormDatePickerInput"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput\/navigatorTitle","value":[{"text":"SMIFormDatePickerInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle","value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1maximumDate\/title","value":"maximumDate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormDatePickerInput~1maximumDate\/fragments","value":[{"kind":"identifier","text":"maximumDate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}