{"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"abstract":[{"text":"A protocol that defines a form response value containing a whole number.","type":"text"}],"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue\/integerValue"]}],"metadata":{"title":"FormResponseIntegerValue","symbolKind":"protocol","role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIFormResponseIntegerValue","roleHeading":"Protocol","navigatorTitle":[{"text":"FormResponseIntegerValue","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseIntegerValue"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponseintegervalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponseintegervalue"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseIntegerValue","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"FormResponseValue","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Use this protocol to represent a form response that includes an integer value.","type":"text"},{"text":" ","type":"text"},{"text":"The protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","type":"reference","isActive":true},{"text":" to add support for whole numbers,","type":"text"},{"text":" ","type":"text"},{"text":"which are stored as ","type":"text"},{"type":"codeVoice","code":"NSInteger"},{"text":" objects. This type of response is typically used with","type":"text"},{"text":" ","type":"text"},{"text":"text inputs that accept numeric values without decimal places.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"type":"topic","title":"FormResponseValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","abstract":[{"text":"A protocol that defines the base interface for form response values.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormResponseValue"}],"navigatorTitle":[{"kind":"identifier","text":"FormResponseValue"}],"url":"\/documentation\/smiclientcore\/formresponsevalue","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseIntegerValue/integerValue":{"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseintegervalue\/integervalue","abstract":[{"text":"The integer value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the whole number entered by the user, stored as an ","type":"text"},{"type":"codeVoice","code":"NSInteger"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue\/integerValue","title":"integerValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"integerValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"integerValue","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseIntegerValue":{"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formresponseintegervalue","abstract":[{"text":"A protocol that defines a form response value containing a whole number.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue","title":"FormResponseIntegerValue","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseIntegerValue","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseIntegerValue","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIFormResponseIntegerValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseIntegerValue"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseIntegerValue","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseIntegerValue\/integerValue"],"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormResponseIntegerValue"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","preciseIdentifier":"c:objc(pl)SMIFormResponseValue","kind":"typeIdentifier","text":"SMIFormResponseValue"},{"text":">","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","op":"replace","value":"SMIFormResponseValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","op":"replace","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue~1integerValue\/title","op":"replace","value":"integerValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue~1integerValue\/fragments","op":"replace","value":[{"text":"integerValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/title","op":"replace","value":"SMIFormResponseIntegerValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/fragments","op":"replace","value":[{"text":"SMIFormResponseIntegerValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseIntegerValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormResponseIntegerValue"}]}]}]}