{"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/formTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/reply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/response","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/result","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/sections"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs"},"metadata":{"symbolKind":"protocol","role":"symbol","externalID":"c:objc(pl)SMIFormInputs","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}]},"abstract":[{"text":"A protocol that represents a form in a conversation.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputs","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"EntryTypeFormMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"}]}]},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access and manage form content in a conversation. A form consists of","type":"text"},{"text":" ","type":"text"},{"text":"multiple input sections, each containing a single input field. The form can include a title,","type":"text"},{"text":" ","type":"text"},{"text":"optional message, and reply text. Once completed, the form generates a response and result.","type":"text"},{"text":" ","type":"text"},{"text":"This protocol extends ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","isActive":true,"type":"reference"},{"text":" to provide form-specific functionality.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputs"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputs"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/reply":{"abstract":[{"type":"text","text":"The reply text for the form."}],"type":"topic","url":"\/documentation\/smiclientcore\/forminputs\/reply","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/reply","required":true,"role":"symbol","title":"reply","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reply"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"reply"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/message":{"navigatorTitle":[{"text":"message","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/forminputs\/message","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/message","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A message which optionally accompanies a form."},{"type":"text","text":" "},{"type":"text","text":"This property provides additional context or instructions for the form."}],"title":"message","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs":{"url":"\/documentation\/smiclientcore\/forminputs","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputs"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputs"}],"title":"FormInputs","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs","abstract":[{"text":"A protocol that represents a form in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeFormMessage":{"type":"topic","navigatorTitle":[{"text":"EntryTypeFormMessage","kind":"identifier"}],"abstract":[{"text":"A protocol that defines the base type for form messages in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","kind":"symbol","url":"\/documentation\/smiclientcore\/entrytypeformmessage","role":"symbol","title":"EntryTypeFormMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeFormMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/result":{"url":"\/documentation\/smiclientcore\/forminputs\/result","abstract":[{"type":"text","text":"The result of the form."},{"type":"text","text":" "},{"type":"text","text":"This value is set once the acknowledgment is received after the form response is sent to the server."}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/result","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormResponseResult","text":"FormResponseResult","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"result","role":"symbol","navigatorTitle":[{"text":"result","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/formTitle":{"navigatorTitle":[{"kind":"identifier","text":"formTitle"}],"required":true,"title":"formTitle","url":"\/documentation\/smiclientcore\/forminputs\/formtitle","abstract":[{"type":"text","text":"The title of the form."},{"type":"text","text":" "},{"type":"text","text":"This property provides the main heading for the form."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/formTitle","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTitle"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"title":"EntryTypeMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"kind":"symbol","type":"topic","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/response":{"role":"symbol","abstract":[{"text":"The response to the form.","type":"text"},{"text":" ","type":"text"},{"text":"This value is set once the user has completed and submitted a form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/response","kind":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"FormResponseInputs","preciseIdentifier":"c:objc(pl)SMIFormResponseInputs"},{"kind":"text","text":")?"}],"url":"\/documentation\/smiclientcore\/forminputs\/response","navigatorTitle":[{"kind":"identifier","text":"response"}],"title":"response"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputs/sections":{"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"sections"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/sections","title":"sections","type":"topic","abstract":[{"text":"The sections which individually represent a single input for each form field.","type":"text"},{"text":" ","type":"text"},{"text":"Each section contains one input field that collects user data.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminputs\/sections","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sections"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIFormInputSection","kind":"typeIdentifier","text":"FormInputSection"},{"kind":"text","text":"]"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormInputs","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/formTitle","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/reply","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/response","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/result","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputs\/sections"],"anchor":"Instance-Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInputs"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeFormMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeFormMessage","text":"SMIEntryTypeFormMessage"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"reply","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1reply\/title"},{"value":[{"kind":"identifier","text":"reply"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1reply\/fragments"},{"value":"message","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1message\/title"},{"value":[{"kind":"identifier","text":"message"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1message\/fragments"},{"value":"SMIFormInputs","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/title"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/fragments"},{"value":[{"text":"SMIFormInputs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs\/navigatorTitle"},{"value":"SMIEntryTypeFormMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/title"},{"value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/fragments"},{"value":[{"text":"SMIEntryTypeFormMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeFormMessage\/navigatorTitle"},{"value":"result","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1result\/title"},{"value":[{"text":"result","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1result\/fragments"},{"value":"formTitle","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1formTitle\/title"},{"value":[{"kind":"identifier","text":"formTitle"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1formTitle\/fragments"},{"value":"SMIEntryTypeMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments"},{"value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle"},{"value":"SMIEntryPayload","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1response\/title","value":"response","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1response\/fragments","value":[{"text":"response","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1sections\/title","value":"sections","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputs~1sections\/fragments","value":[{"text":"sections","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}