{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion"},"metadata":{"title":"HiddenPreChatValueCompletion","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"typealias","externalID":"c:SMIHiddenPreChatDelegate.h@T@SMIHiddenPreChatValueCompletion","roleHeading":"Type Alias","navigatorTitle":[{"text":"HiddenPreChatValueCompletion","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatValueCompletion"}]},"abstract":[{"text":"Completion block for hidden pre-chat values.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/hiddenprechatvaluecompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/hiddenprechatvaluecompletion"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatValueCompletion"},{"kind":"text","text":" = ([any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField","kind":"typeIdentifier","text":"HiddenPreChatField"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"hiddenPreChatFields","content":[{"type":"paragraph","inlineContent":[{"text":"The array of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"reference"},{"text":" values to provide with completed values.","type":"text"}]}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatValueCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatValueCompletion","role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/hiddenprechatvaluecompletion","abstract":[{"text":"Completion block for hidden pre-chat values.","type":"text"}],"navigatorTitle":[{"text":"HiddenPreChatValueCompletion","kind":"identifier"}],"title":"HiddenPreChatValueCompletion","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HiddenPreChatValueCompletion","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a hidden pre-chat field in the conversation configuration."}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"title":"HiddenPreChatField","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIHiddenPreChatValueCompletion","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatValueCompletion"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIHiddenPreChatValueCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray)","text":"void (^)(NSArray<id<SMIHiddenPreChatField>> *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMIHiddenPreChatValueCompletion","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIHiddenPreChatValueCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/title"},{"op":"replace","value":[{"text":"SMIHiddenPreChatValueCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/fragments"},{"op":"replace","value":[{"text":"SMIHiddenPreChatValueCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatValueCompletion\/navigatorTitle"},{"op":"replace","value":"SMIHiddenPreChatField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle"}]}]}