{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset"},"metadata":{"navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAsset"}],"externalID":"c:objc(pl)SMIImageAsset","modules":[{"name":"SMIClientCore"}],"title":"ImageAsset"},"sections":[],"abstract":[{"text":"A protocol that represents an image asset in a conversation.","type":"text"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/height","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/image","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/width"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ImageAsset","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFileAsset","text":"FileAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access image assets in a conversation. This protocol extends","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","type":"reference","isActive":true},{"text":" to provide image-specific functionality, including dimensions and","type":"text"},{"text":" ","type":"text"},{"text":"image content. Images are loaded asynchronously to optimize performance.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/imageasset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/imageasset"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/width":{"abstract":[{"text":"The expected width of the image in pixels.","type":"text"},{"text":" ","type":"text"},{"text":"This property is available before the image is loaded and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"pre-allocate UI space or calculate layout constraints.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/width","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/imageasset\/width"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"abstract":[{"type":"text","text":"Fetches the content of this file asset asynchronously."},{"type":"text","text":" "},{"type":"text","text":"This method downloads the file content if it’s not already cached."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","navigatorTitle":[{"text":"fetchContentWithCompletion:","kind":"identifier"}],"title":"fetchContent(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset":{"title":"ImageAsset","abstract":[{"text":"A protocol that represents an image asset in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/imageasset","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAsset"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAsset"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/fileasset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","role":"symbol","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"title":"FileAsset","navigatorTitle":[{"kind":"identifier","text":"FileAsset"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileAsset","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/height":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The expected height of the image in pixels.","type":"text"},{"text":" ","type":"text"},{"text":"This property is available before the image is loaded and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"pre-allocate UI space or calculate layout constraints.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/smiclientcore\/imageasset\/height","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/height","title":"height"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/image":{"abstract":[{"text":"The image content of this asset.","type":"text"},{"text":" ","type":"text"},{"text":"This property is initially ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" and must be loaded using ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Once loaded, this property provides access to the image data for display.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/image","navigatorTitle":[{"text":"image","kind":"identifier"}],"title":"image","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/imageasset\/image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIImageAsset","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/height","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/image","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/width"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIImageAsset"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","kind":"typeIdentifier","text":"SMIFileAsset","preciseIdentifier":"c:objc(pl)SMIFileAsset"},{"kind":"text","text":">"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1width\/title","value":"width","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1width\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","value":"fetchContentWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchContentWithCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/title","value":"SMIImageAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/fragments","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/navigatorTitle","value":[{"text":"SMIImageAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","value":"SMIFileAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","value":[{"text":"SMIFileAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1height\/title","value":"height","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1height\/fragments","value":[{"text":"height","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"}]}]}