{"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents citation details with inline metadata for the given citations."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"metadata":{"role":"symbol","externalID":"c:objc(pl)SMIInlineMetadataCitedDetails","modules":[{"name":"SMIClientCore"}],"title":"InlineMetadataCitedDetails","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"InlineMetadataCitedDetails"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InlineMetadataCitedDetails"}],"symbolKind":"protocol"},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails\/inlineMetadata"],"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InlineMetadataCitedDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"CitedDetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","preciseIdentifier":"c:objc(pl)SMICitedDetails","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/inlinemetadataciteddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/inlinemetadataciteddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/InlineMetadataCitedDetails/inlineMetadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inlineMetadata","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"CitedInlineMetadata","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedInlineMetadata"},{"text":"]","kind":"text"}],"title":"inlineMetadata","type":"topic","kind":"symbol","abstract":[{"text":"The array of inline metadata entries for this citation.","type":"text"},{"text":" ","type":"text"},{"text":"Each entry in the array conforms to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","type":"reference"},{"text":" protocol and provides","type":"text"},{"text":" ","type":"text"},{"text":"detailed information about where the citation appears in the text, including claim","type":"text"},{"text":" ","type":"text"},{"text":"information and location offsets.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails\/inlineMetadata","navigatorTitle":[{"text":"inlineMetadata","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/inlinemetadataciteddetails\/inlinemetadata","required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails":{"role":"symbol","url":"\/documentation\/smiclientcore\/citeddetails","navigatorTitle":[{"text":"CitedDetails","kind":"identifier"}],"abstract":[{"text":"A protocol that represents the location and type information for a citation.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedDetails","kind":"identifier"}],"type":"topic","title":"CitedDetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/InlineMetadataCitedDetails":{"navigatorTitle":[{"kind":"identifier","text":"InlineMetadataCitedDetails"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails","kind":"symbol","title":"InlineMetadataCitedDetails","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InlineMetadataCitedDetails"}],"type":"topic","url":"\/documentation\/smiclientcore\/inlinemetadataciteddetails","abstract":[{"type":"text","text":"A protocol that represents citation details with inline metadata for the given citations."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedInlineMetadata":{"title":"CitedInlineMetadata","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedInlineMetadata","abstract":[{"type":"text","text":"A protocol that represents inline metadata for a citation, including its location and claim information."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedInlineMetadata","kind":"identifier"}],"navigatorTitle":[{"text":"CitedInlineMetadata","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/citedinlinemetadata"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIInlineMetadataCitedDetails","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIInlineMetadataCitedDetails"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIInlineMetadataCitedDetails","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/InlineMetadataCitedDetails\/inlineMetadata"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIInlineMetadataCitedDetails","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails","text":"SMICitedDetails","preciseIdentifier":"c:objc(pl)SMICitedDetails","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"inlineMetadata","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails~1inlineMetadata\/title"},{"value":[{"text":"inlineMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails~1inlineMetadata\/fragments"},{"value":"SMICitedDetails","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/title"},{"value":[{"kind":"identifier","text":"SMICitedDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/fragments"},{"value":[{"kind":"identifier","text":"SMICitedDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/navigatorTitle"},{"value":"SMIInlineMetadataCitedDetails","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/title"},{"value":[{"text":"SMIInlineMetadataCitedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/fragments"},{"value":[{"text":"SMIInlineMetadataCitedDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1InlineMetadataCitedDetails\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/title","value":"SMICitedInlineMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/fragments","value":[{"text":"SMICitedInlineMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedInlineMetadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMICitedInlineMetadata"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}