{"abstract":[{"type":"text","text":"A protocol that represents a citation reference that links to an external URL."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"sections":[],"kind":"symbol","metadata":{"title":"LinkCitedReference","externalID":"c:objc(pl)SMILinkCitedReference","navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkCitedReference"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"},{"kind":"text","text":" : "},{"text":"CitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","preciseIdentifier":"c:objc(pl)SMICitedReference","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"Use this protocol to access citation references that point to external URLs.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/recordId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/url"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/linkcitedreference"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/url":{"navigatorTitle":[{"kind":"identifier","text":"url"}],"abstract":[{"type":"text","text":"The URL that this citation references."},{"type":"text","text":" "},{"type":"text","text":"This property provides the target URL that the citation links to. The URL can be used"},{"type":"text","text":" "},{"type":"text","text":"to navigate to the referenced content when the citation is selected."}],"required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/url","type":"topic","url":"\/documentation\/smiclientcore\/linkcitedreference\/url","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/label":{"abstract":[{"type":"text","text":"A display label for the citation."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides a user-friendly label that can be used in place of"},{"type":"text","text":" "},{"type":"text","text":"the URL’s domain name, particularly useful when the domain is excessively long or"},{"type":"text","text":" "},{"type":"text","text":"not user-friendly."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"label"}],"type":"topic","url":"\/documentation\/smiclientcore\/linkcitedreference\/label","kind":"symbol","role":"symbol","title":"label","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference/recordId":{"abstract":[{"type":"text","text":"The unique identifier for the referenced record."},{"type":"text","text":" "},{"type":"text","text":"This optional property provides a record identifier that can be used to associate"},{"type":"text","text":" "},{"type":"text","text":"the citation with a specific record in the system."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"recordId"}],"type":"topic","url":"\/documentation\/smiclientcore\/linkcitedreference\/recordid","kind":"symbol","role":"symbol","title":"recordId","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/recordId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference":{"abstract":[{"type":"text","text":"A protocol that represents the reference information for a citation."}],"navigatorTitle":[{"kind":"identifier","text":"CitedReference"}],"type":"topic","url":"\/documentation\/smiclientcore\/citedreference","kind":"symbol","role":"symbol","title":"CitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedReference"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LinkCitedReference":{"role":"symbol","type":"topic","abstract":[{"text":"A protocol that represents a citation reference that links to an external URL.","type":"text"}],"title":"LinkCitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LinkCitedReference","kind":"identifier"}],"navigatorTitle":[{"text":"LinkCitedReference","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/linkcitedreference"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMILinkCitedReference"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILinkCitedReference"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMILinkCitedReference","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/recordId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LinkCitedReference\/url"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILinkCitedReference","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","text":"SMICitedReference","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitedReference"},{"text":">","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1url\/title","op":"replace","value":"url"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1url\/fragments","op":"replace","value":[{"text":"url","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1label\/title","op":"replace","value":"label"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1label\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1recordId\/title","op":"replace","value":"recordId"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference~1recordId\/fragments","op":"replace","value":[{"text":"recordId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/title","op":"replace","value":"SMICitedReference"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICitedReference"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/navigatorTitle","op":"replace","value":[{"text":"SMICitedReference","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/title","op":"replace","value":"SMILinkCitedReference"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILinkCitedReference"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LinkCitedReference\/navigatorTitle","op":"replace","value":[{"text":"SMILinkCitedReference","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}