{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/listapidirections"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/listapidirections"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"An enum that defines the ordering direction for list-based API requests."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListAPIDirections","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to specify the chronological ordering of items in list-based API responses,"},{"type":"text","text":" "},{"type":"text","text":"particularly for conversations and messages."}]},{"level":2,"text":"Possible Values","type":"heading","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/ascending"},{"text":" - Orders list items from oldest to newest","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending"},{"text":" - Orders list items from newest to oldest","type":"text"}]}]}]}],"kind":"content"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/ascending","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/_SwiftNewtypeWrapper-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"ListAPIDirections"}],"externalID":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListAPIDirections"}],"title":"ListAPIDirections","role":"symbol","roleHeading":"Structure"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections":{"navigatorTitle":[{"kind":"identifier","text":"ListAPIDirections"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListAPIDirections"}],"abstract":[{"type":"text","text":"An enum that defines the ordering direction for list-based API requests."}],"type":"topic","kind":"symbol","title":"ListAPIDirections","url":"\/documentation\/smiclientcore\/listapidirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","role":"symbol"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/Equatable-Implementations":{"type":"topic","url":"\/documentation\/smiclientcore\/listapidirections\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/Equatable-Implementations","kind":"article","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/descending":{"role":"symbol","title":"descending","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending","url":"\/documentation\/smiclientcore\/listapidirections\/descending","abstract":[{"type":"text","text":"Orders list items from newest to oldest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in reverse chronological order."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descending","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"}],"type":"topic","navigatorTitle":[{"text":"SMIListAPIDirectionsDescending","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/ascending":{"type":"topic","url":"\/documentation\/smiclientcore\/listapidirections\/ascending","role":"symbol","navigatorTitle":[{"text":"SMIListAPIDirectionsAscending","kind":"identifier"}],"title":"ascending","abstract":[{"type":"text","text":"Orders list items from oldest to newest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in chronological order."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ascending","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","text":"ListAPIDirections","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/ascending","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/_SwiftNewtypeWrapper-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/_SwiftNewtypeWrapper-Implementations","url":"\/documentation\/smiclientcore\/listapidirections\/_swiftnewtypewrapper-implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","title":"_SwiftNewtypeWrapper Implementations"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/init(rawValue:)":{"abstract":[],"type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/listapidirections\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIListAPIDirections","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIListAPIDirections"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"SMIListAPIDirections","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/title","value":"SMIListAPIDirections","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/fragments","value":[{"text":"SMIListAPIDirections","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/navigatorTitle","value":[{"kind":"identifier","text":"SMIListAPIDirections"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/title","value":"SMIListAPIDirectionsDescending","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/fragments","value":[{"text":"SMIListAPIDirectionsDescending","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1ascending\/title","value":"SMIListAPIDirectionsAscending","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1ascending\/fragments","value":[{"text":"SMIListAPIDirectionsAscending","kind":"identifier"}],"op":"replace"}]}]}