{"sections":[],"metadata":{"externalID":"c:objc(pl)SMIListPicker","modules":[{"name":"SMIClientCore"}],"title":"ListPicker","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPicker","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ListPicker","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/listpicker"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/listpicker"]}],"abstract":[{"type":"text","text":"A protocol that represents a list picker within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker\/text"],"anchor":"Instance-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPicker"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","text":"EntryPayload"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","text":"EntryTypeMessage"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(pl)SMIMessageChoices","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","kind":"typeIdentifier","text":"MessageChoices"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(pl)SMIMessageSelectable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","kind":"typeIdentifier","text":"MessageSelectable"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"Use this protocol to access the content of a list picker displayed in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"A list picker allows users to select an item from a predefined list of choices.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker":{"title":"ListPicker","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","abstract":[{"type":"text","text":"A protocol that represents a list picker within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListPicker","kind":"identifier"}],"navigatorTitle":[{"text":"ListPicker","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/listpicker"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker/text":{"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker\/text","role":"symbol","url":"\/documentation\/smiclientcore\/listpicker\/text","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The text content of the list picker."}],"title":"text","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageChoices":{"navigatorTitle":[{"kind":"identifier","text":"MessageChoices"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChoices"}],"role":"symbol","url":"\/documentation\/smiclientcore\/messagechoices","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a message with available choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"title":"MessageChoices"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSelectable"}],"abstract":[{"type":"text","text":"A protocol that represents a message with selectable choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"title":"MessageSelectable","role":"symbol","url":"\/documentation\/smiclientcore\/messageselectable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageSelectable"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"title":"EntryTypeMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","type":"unresolvable","title":"Foundation.NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"kind":"symbol","type":"topic","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIListPicker","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker\/text"],"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIListPicker"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload","text":"SMIEntryPayload"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIMessageSelectable","text":"SMIMessageSelectable"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","text":"SMIEntryTypeMessage"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIMessageChoices","text":"SMIMessageChoices"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIListPicker","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/title","op":"replace"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/fragments","op":"replace"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/navigatorTitle","op":"replace"},{"value":"text","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker~1text\/title","op":"replace"},{"value":[{"kind":"identifier","text":"text"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker~1text\/fragments","op":"replace"},{"value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace"},{"value":"SMIMessageChoices","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/title","op":"replace"},{"value":[{"text":"SMIMessageChoices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/fragments","op":"replace"},{"value":[{"text":"SMIMessageChoices","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/navigatorTitle","op":"replace"},{"value":"SMIMessageSelectable","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIMessageSelectable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/fragments","op":"replace"},{"value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/navigatorTitle","op":"replace"},{"value":"SMIEntryTypeMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","op":"replace"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","op":"replace"},{"value":"SMIEntryPayload","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace"},{"value":[{"text":"SMIEntryPayload","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}