{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol\/level"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingProtocol","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"Use this protocol to configure the logging level for the SDK. The logging level","type":"text"},{"text":" ","type":"text"},{"text":"determines what types of messages are logged and displayed to the console.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Logging"]}],"kind":"symbol","abstract":[{"text":"A protocol that defines the logging configuration for the SDK.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/loggingprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/loggingprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Protocol","title":"LoggingProtocol","role":"symbol","navigatorTitle":[{"text":"LoggingProtocol","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMILogging","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingProtocol","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingProtocol/level":{"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SMILoggingLevel","text":"LoggingLevel","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The logging level for the SDK."},{"type":"text","text":" "},{"type":"text","text":"This property controls the verbosity of logging output. When set to"},{"type":"text","text":" "},{"type":"codeVoice","code":"SMILoggingLevelNone"},{"type":"text","text":", no logging occurs. When set to "},{"type":"codeVoice","code":"SMILoggingLevelDebug"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"detailed debug information is logged."}],"navigatorTitle":[{"text":"level","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol\/level","title":"level","url":"\/documentation\/smiclientcore\/loggingprotocol\/level","kind":"symbol","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Logging":{"url":"\/documentation\/smiclientcore\/logging","kind":"symbol","type":"topic","title":"Logging","abstract":[{"type":"text","text":"A class that provides logging functionality for the SDK."}],"navigatorTitle":[{"text":"Logging","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logging","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Logging"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingProtocol":{"title":"LoggingProtocol","abstract":[{"type":"text","text":"A protocol that defines the logging configuration for the SDK."}],"url":"\/documentation\/smiclientcore\/loggingprotocol","navigatorTitle":[{"text":"LoggingProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMILogging","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMILogging","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMILogging","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol\/level"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Logging"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMILogging","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol~1level\/title","op":"replace","value":"level"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol~1level\/fragments","op":"replace","value":[{"text":"level","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Logging\/title","op":"replace","value":"SMILogging"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Logging\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILogging"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Logging\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMILogging"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/title","op":"replace","value":"SMILogging"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/fragments","op":"replace","value":[{"text":"SMILogging","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMILogging","kind":"identifier"}]}]}]}