{"variants":[{"paths":["\/documentation\/smiclientcore\/logginglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/logginglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/debug","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/none"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","metadata":{"symbolKind":"enum","modules":[{"name":"SMIClientCore"}],"roleHeading":"Enumeration","externalID":"c:@E@SMILoggingLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"role":"symbol","title":"LoggingLevel"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"Logging level values."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingLevel"}],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/none":{"abstract":[{"text":"No logging level.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"SMILoggingLevelNone","kind":"identifier"}],"title":"LoggingLevel.none","url":"\/documentation\/smiclientcore\/logginglevel\/none","kind":"symbol","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/debug":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"url":"\/documentation\/smiclientcore\/logginglevel\/debug","abstract":[{"text":"Debug logging level.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMILoggingLevelDebug"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/debug","type":"topic","title":"LoggingLevel.debug","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel":{"url":"\/documentation\/smiclientcore\/logginglevel","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","kind":"symbol","title":"LoggingLevel","type":"topic","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"Logging level values."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/RawRepresentable-Implementations":{"url":"\/documentation\/smiclientcore\/logginglevel\/rawrepresentable-implementations","type":"topic","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/init(rawValue:)":{"url":"\/documentation\/smiclientcore\/logginglevel\/init(rawvalue:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/Equatable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/smiclientcore\/logginglevel\/equatable-implementations","abstract":[]},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SMILoggingLevel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMILoggingLevel","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMILoggingLevel","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/debug","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/none"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMILoggingLevel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1none\/title","op":"replace","value":"SMILoggingLevelNone"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevelNone"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1debug\/title","op":"replace","value":"SMILoggingLevelDebug"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1debug\/fragments","op":"replace","value":[{"text":"SMILoggingLevelDebug","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/title","op":"replace","value":"SMILoggingLevel"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevel"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevel"}]}]}]}