{"kind":"symbol","metadata":{"externalID":"c:SMILoggingCategory.h@T@SMILoggingCategory","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}],"symbolKind":"struct","roleHeading":"Structure","navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"title":"LoggingCategory"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"Logging category information.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggingCategory","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/networking","isActive":true,"type":"reference"},{"text":" - Logging message associated with general network operations.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/API","isActive":true},{"type":"text","text":" - Logging message associated with core API operations."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/database"},{"text":" - Logging message associated with local database operations.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/event"},{"type":"text","text":" - Logging message associated with emitting delegate events."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/memory","type":"reference","isActive":true},{"text":" - Logging message associated with memory management.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/error","isActive":true},{"type":"text","text":" - Logging message associated with errors which are emitted to the consuming client."}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/realtimeConnection","isActive":true},{"type":"text","text":" - Logging message associated with the realtime event listener connection."}],"type":"paragraph"}]}]}],"kind":"content"}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/init(rawValue:)"]},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/API","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/database","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/error","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/event","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/memory","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/multimedia","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/networking","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/realtimeConnection"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/Equatable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/loggingcategory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/loggingcategory"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/realtimeConnection":{"abstract":[{"type":"text","text":"Logging message associated with the realtime event listener connection."}],"navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryRealtimeConnection"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/realtimeConnection","title":"realtimeConnection","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"realtimeConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","text":"LoggingCategory"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory\/realtimeconnection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/API":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","text":"LoggingCategory","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/loggingcategory\/api","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMILoggingCategoryAPI","kind":"identifier"}],"abstract":[{"text":"Logging message associated with core API operations.","type":"text"}],"title":"API","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/API"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/database":{"abstract":[{"text":"Logging message associated with local database operations.","type":"text"}],"navigatorTitle":[{"text":"SMILoggingCategoryDatabase","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/database","title":"database","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"database","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory\/database"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/smiclientcore\/loggingcategory\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/error":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","text":"LoggingCategory"}],"url":"\/documentation\/smiclientcore\/loggingcategory\/error","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryError"}],"abstract":[{"text":"Logging message associated with errors which are emitted to the consuming client.","type":"text"}],"title":"error","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/error"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/smiclientcore\/loggingcategory\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory":{"type":"topic","url":"\/documentation\/smiclientcore\/loggingcategory","title":"LoggingCategory","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory","navigatorTitle":[{"kind":"identifier","text":"LoggingCategory"}],"abstract":[{"type":"text","text":"Logging category information."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingCategory"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/networking":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/networking","abstract":[{"text":"Logging message associated with general network operations.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMILoggingCategoryNetworking","kind":"identifier"}],"title":"networking","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networking","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/loggingcategory\/networking"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/multimedia":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimedia","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LoggingCategory","preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory"}],"url":"\/documentation\/smiclientcore\/loggingcategory\/multimedia","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryMultimedia"}],"abstract":[{"type":"text","text":"Logging message associated with voice activity."}],"title":"multimedia","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/multimedia"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/event":{"url":"\/documentation\/smiclientcore\/loggingcategory\/event","abstract":[{"type":"text","text":"Logging message associated with emitting delegate events."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/event","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryEvent"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier","text":"LoggingCategory"}],"type":"topic","title":"event"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingCategory/memory":{"type":"topic","url":"\/documentation\/smiclientcore\/loggingcategory\/memory","title":"memory","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingCategory\/memory","navigatorTitle":[{"kind":"identifier","text":"SMILoggingCategoryMemory"}],"abstract":[{"type":"text","text":"Logging message associated with memory management."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMILoggingCategory.h@T@SMILoggingCategory","kind":"typeIdentifier","text":"LoggingCategory"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMILoggingCategory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMILoggingCategory"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategory"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMILoggingCategory"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SMILoggingCategoryRealtimeConnection","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1realtimeConnection\/title"},{"value":[{"kind":"identifier","text":"SMILoggingCategoryRealtimeConnection"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1realtimeConnection\/fragments"},{"value":"SMILoggingCategoryAPI","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1API\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMILoggingCategoryAPI"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1API\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1database\/title","value":"SMILoggingCategoryDatabase","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1database\/fragments","value":[{"kind":"identifier","text":"SMILoggingCategoryDatabase"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1error\/title","value":"SMILoggingCategoryError","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1error\/fragments","value":[{"kind":"identifier","text":"SMILoggingCategoryError"}],"op":"replace"},{"op":"replace","value":"SMILoggingCategory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/title"},{"op":"replace","value":[{"text":"SMILoggingCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/fragments"},{"value":[{"text":"SMILoggingCategory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory\/navigatorTitle"},{"value":"SMILoggingCategoryNetworking","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1networking\/title"},{"value":[{"text":"SMILoggingCategoryNetworking","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1networking\/fragments"},{"value":"SMILoggingCategoryMultimedia","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1multimedia\/title"},{"value":[{"text":"SMILoggingCategoryMultimedia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1multimedia\/fragments"},{"value":"SMILoggingCategoryEvent","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1event\/title"},{"value":[{"kind":"identifier","text":"SMILoggingCategoryEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1event\/fragments"},{"value":"SMILoggingCategoryMemory","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1memory\/title"},{"value":[{"text":"SMILoggingCategoryMemory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingCategory~1memory\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}