{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices"},"abstract":[{"type":"text","text":"A protocol that represents a message with available choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices\/choices"],"anchor":"Instance-Properties","generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/messagechoices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messagechoices"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"],"type":"inheritedBy"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageChoices","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use this protocol to access the available choices of a message displayed in a conversation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A message with choices provides users with a list of options to select from."}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MessageChoices"}],"modules":[{"name":"SMIClientCore"}],"title":"MessageChoices","roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:objc(pl)SMIMessageChoices","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageChoices","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageChoices/choices":{"required":true,"url":"\/documentation\/smiclientcore\/messagechoices\/choices","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"choices"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The list of possible choices for the message."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices\/choices","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": [any "},{"text":"Choice","preciseIdentifier":"c:objc(pl)SMIChoice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"choices"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuickReply","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/quickreply","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"QuickReply","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a quick reply within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"title":"QuickReply","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker":{"url":"\/documentation\/smiclientcore\/listpicker","abstract":[{"text":"A protocol that represents a list picker within a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPicker"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPicker"}],"type":"topic","title":"ListPicker"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageChoices":{"navigatorTitle":[{"text":"MessageChoices","kind":"identifier"}],"title":"MessageChoices","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageChoices"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","url":"\/documentation\/smiclientcore\/messagechoices","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a message with available choices within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIMessageChoices","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIMessageChoices"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageChoices"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices\/choices"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"],"type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIMessageChoices"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"choices","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices~1choices\/title"},{"value":[{"kind":"identifier","text":"choices"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices~1choices\/fragments"},{"value":"SMIQuickReply","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/title"},{"value":[{"text":"SMIQuickReply","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/fragments"},{"value":[{"text":"SMIQuickReply","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace"},{"value":"SMIListPicker","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/title","op":"replace"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/navigatorTitle","value":[{"text":"SMIListPicker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/title","value":"SMIMessageChoices","op":"replace"},{"value":[{"text":"SMIMessageChoices","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/fragments"},{"value":[{"kind":"identifier","text":"SMIMessageChoices"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}