{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MessageReason"}],"role":"symbol","roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReason","kind":"identifier"}],"externalID":"c:SMIMessageReason.h@T@SMIMessageReason","modules":[{"name":"SMIClientCore"}],"title":"MessageReason"},"abstract":[{"type":"text","text":"An enum that defines the possible reasons for a message in a conversation."}],"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/init(rawValue:)"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/automatedResponse","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/consent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/none"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/Equatable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReason","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"This enum is used to categorize different reasons why messages are sent in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"Each type represents a specific message reason that has been set.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Possible Values","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/automatedResponse","isActive":true},{"type":"text","text":" - Indicates the action of sending an automated response message"}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/consent"},{"type":"text","text":" - Indicates the action of sending a consent-related message"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/none","isActive":true,"type":"reference"},{"text":" - Indicates no specific reason for the message","type":"text"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/messagereason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/messagereason"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/automatedResponse":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatedResponse","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageReason","kind":"typeIdentifier","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason"}],"url":"\/documentation\/smiclientcore\/messagereason\/automatedresponse","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}],"abstract":[{"text":"Indicates the action of sending an automated response message.","type":"text"}],"title":"automatedResponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/automatedResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReason","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/messagereason","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MessageReason","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible reasons for a message in a conversation."}],"title":"MessageReason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/none":{"type":"topic","url":"\/documentation\/smiclientcore\/messagereason\/none","title":"none","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/none","navigatorTitle":[{"text":"SMIMessageReasonNone","kind":"identifier"}],"abstract":[{"text":"Indicates no specific reason for the message.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","text":"MessageReason","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/smiclientcore\/messagereason\/equatable-implementations","abstract":[],"kind":"article","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/messagereason\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason/consent":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason\/consent","role":"symbol","url":"\/documentation\/smiclientcore\/messagereason\/consent","abstract":[{"text":"Indicates the action of sending a consent-related message.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"SMIMessageReasonConsent","kind":"identifier"}],"title":"consent"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIMessageReason","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIMessageReason","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMessageReason"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIMessageReason"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1automatedResponse\/title","value":"SMIMessageReasonAutomatedResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1automatedResponse\/fragments","value":[{"text":"SMIMessageReasonAutomatedResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/title","value":"SMIMessageReason","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/fragments","value":[{"kind":"identifier","text":"SMIMessageReason"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/navigatorTitle","value":[{"text":"SMIMessageReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1none\/title","value":"SMIMessageReasonNone","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1none\/fragments","value":[{"kind":"identifier","text":"SMIMessageReasonNone"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1consent\/title","value":"SMIMessageReasonConsent","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason~1consent\/fragments","value":[{"text":"SMIMessageReasonConsent","kind":"identifier"}],"op":"replace"}]}]}