{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageSelectable","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"text":"Use this protocol to access the selected choices of a message displayed in a conversation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A selectable message allows users to choose from predefined options."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable\/selected"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"MessageSelectable","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSelectable"}],"externalID":"c:objc(pl)SMIMessageSelectable","modules":[{"name":"SMIClientCore"}],"title":"MessageSelectable"},"abstract":[{"type":"text","text":"A protocol that represents a message with selectable choices within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/smiclientcore\/messageselectable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messageselectable"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"],"type":"inheritedBy"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListPicker":{"url":"\/documentation\/smiclientcore\/listpicker","abstract":[{"text":"A protocol that represents a list picker within a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ListPicker"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListPicker"}],"type":"topic","title":"ListPicker"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuickReply","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/quickreply","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"QuickReply","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a quick reply within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"title":"QuickReply","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","title":"MessageSelectable","navigatorTitle":[{"kind":"identifier","text":"MessageSelectable"}],"abstract":[{"type":"text","text":"A protocol that represents a message with selectable choices within a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/smiclientcore\/messageselectable","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSelectable"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"url":"\/documentation\/smiclientcore\/carousel","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"title":"Carousel","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable/selected":{"title":"selected","required":true,"abstract":[{"type":"text","text":"The selected choice(s) from the message."}],"url":"\/documentation\/smiclientcore\/messageselectable\/selected","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable\/selected","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIChoice","kind":"typeIdentifier","text":"Choice"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"selected"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIMessageSelectable","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIMessageSelectable"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable\/selected"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListPicker","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"],"type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIMessageSelectable"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIListPicker","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/title"},{"value":[{"text":"SMIListPicker","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/fragments"},{"value":[{"kind":"identifier","text":"SMIListPicker"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListPicker\/navigatorTitle"},{"value":"SMIQuickReply","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/title"},{"value":[{"text":"SMIQuickReply","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/fragments"},{"value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/navigatorTitle"},{"value":"SMIMessageSelectable","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/title"},{"value":[{"kind":"identifier","text":"SMIMessageSelectable"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/fragments"},{"value":[{"kind":"identifier","text":"SMIMessageSelectable"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/navigatorTitle"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMICarousel","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title"},{"value":[{"kind":"identifier","text":"SMICarousel"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments"},{"value":[{"text":"SMICarousel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle"},{"value":"selected","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable~1selected\/title"},{"value":[{"text":"selected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable~1selected\/fragments"}]}]}