{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MessagingChannel"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessagingChannel"}],"externalID":"c:objc(pl)SMIMessagingChannel","modules":[{"name":"SMIClientCore"}],"title":"MessagingChannel"},"abstract":[{"text":"Messaging Channel Configurations","type":"text"}],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/isVoiceModeEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/supportedModes"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingChannel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From"}],"variants":[{"paths":["\/documentation\/smiclientcore\/messagingchannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messagingchannel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessagingChannel/supportedModes":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/messagingchannel\/supportedmodes","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"supportedModes","kind":"identifier"}],"abstract":[],"title":"supportedModes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/supportedModes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessagingChannel/isVoiceModeEnabled":{"abstract":[],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/isVoiceModeEnabled","navigatorTitle":[{"kind":"identifier","text":"voiceModeEnabled"}],"title":"isVoiceModeEnabled","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVoiceModeEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/messagingchannel\/isvoicemodeenabled"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessagingChannel":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel","role":"symbol","url":"\/documentation\/smiclientcore\/messagingchannel","abstract":[{"type":"text","text":"Messaging Channel Configurations"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagingChannel","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MessagingChannel","kind":"identifier"}],"title":"MessagingChannel"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIMessagingChannel","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIMessagingChannel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIMessagingChannel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/isVoiceModeEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessagingChannel\/supportedModes"]}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIMessagingChannel","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"supportedModes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel~1supportedModes\/title","op":"replace"},{"value":[{"text":"supportedModes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel~1supportedModes\/fragments","op":"replace"},{"value":"voiceModeEnabled","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel~1isVoiceModeEnabled\/title","op":"replace"},{"value":[{"text":"voiceModeEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel~1isVoiceModeEnabled\/fragments","op":"replace"},{"value":"SMIMessagingChannel","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIMessagingChannel"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel\/fragments","op":"replace"},{"value":[{"text":"SMIMessagingChannel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessagingChannel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}