{"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/token","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/turnId"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messagestreamingtoken"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(pl)SMIMessageStreamingToken","role":"symbol","symbolKind":"protocol","title":"MessageStreamingToken","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MessageStreamingToken","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessageStreamingToken","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"StreamingToken","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","preciseIdentifier":"c:objc(pl)SMIStreamingToken"}]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"Use this protocol to access individual tokens that make up a streamed message. This protocol","type":"text"},{"text":" ","type":"text"},{"text":"extends ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","type":"reference"},{"type":"text","text":" to provide functionality for handling message content that"},{"type":"text","text":" "},{"text":"is being streamed in parts. Each token represents a portion of the complete message and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"includes information about its relationship to the final transcribed entry."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/targetMessageIdentifier":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"targetMessageIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/messagestreamingtoken\/targetmessageidentifier","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"targetMessageIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"The identifier that will be used for the final transcribed entry."},{"type":"text","text":" "},{"type":"text","text":"This property provides a unique identifier that will be associated with the complete"},{"type":"text","text":" "},{"type":"text","text":"message once all streaming tokens have been received and processed."}],"title":"targetMessageIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/targetMessageIdentifier"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/turnId":{"abstract":[{"text":"Corresponds to an identifier applied to the agent’s response. This Identifier can be used to correlate all events to a single turn.","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/turnId","navigatorTitle":[{"text":"turnId","kind":"identifier"}],"title":"turnId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken\/turnid"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/batchNumber":{"url":"\/documentation\/smiclientcore\/messagestreamingtoken\/batchnumber","abstract":[{"text":"Corresponds to an identifier applied to the agent’s response. Events which have a strong association will be sent in batches.","type":"text"},{"text":" ","type":"text"},{"text":"This identifier can be used to identifier a batch of related events within a single turn.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/batchNumber","role":"symbol","navigatorTitle":[{"text":"batchNumber","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"batchNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"required":true,"type":"topic","title":"batchNumber"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","title":"EntryFormat","navigatorTitle":[{"kind":"identifier","text":"EntryFormat"}],"abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entryformat","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryFormat"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"abstract":[{"type":"text","text":"Common interface for the content of a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"type":"text","text":" object."}],"type":"topic","url":"\/documentation\/smiclientcore\/entrypayload","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken/token":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryFormat","text":"EntryFormat","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/messagestreamingtoken\/token","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"token","kind":"identifier"}],"abstract":[{"text":"The content of this streaming token.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the token’s content through the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"protocol.","type":"text"}],"title":"token","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/token"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingToken"}],"abstract":[{"type":"text","text":"A protocol that represents an individual token in a stream of content."}],"navigatorTitle":[{"kind":"identifier","text":"StreamingToken"}],"url":"\/documentation\/smiclientcore\/streamingtoken","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","title":"StreamingToken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MessageStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","url":"\/documentation\/smiclientcore\/messagestreamingtoken","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"title":"MessageStreamingToken","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIMessageStreamingToken","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/token","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken\/turnId"],"anchor":"Instance-Properties"}]},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SMIMessageStreamingToken","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIStreamingToken","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","text":"SMIStreamingToken"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"targetMessageIdentifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1targetMessageIdentifier\/title"},{"op":"replace","value":[{"text":"targetMessageIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1targetMessageIdentifier\/fragments"},{"op":"replace","value":"turnId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1turnId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"turnId"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1turnId\/fragments"},{"op":"replace","value":"batchNumber","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1batchNumber\/title"},{"value":[{"kind":"identifier","text":"batchNumber"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1batchNumber\/fragments","op":"replace"},{"value":"SMIEntryFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIEntryFormat"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle","value":[{"text":"SMIEntryFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace","value":"SMIEntryPayload"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1token\/title","op":"replace","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken~1token\/fragments","value":[{"text":"token","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/title","value":"SMIStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/fragments","value":[{"text":"SMIStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/navigatorTitle","value":[{"text":"SMIStreamingToken","kind":"identifier"}]},{"value":"SMIMessageStreamingToken","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title","op":"replace"},{"value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments","op":"replace"},{"value":[{"text":"SMIMessageStreamingToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle","op":"replace"},{"value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}