{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ModalityTransitionType"}],"role":"symbol","roleHeading":"Structure","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}],"externalID":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","modules":[{"name":"SMIClientCore"}],"title":"ModalityTransitionType"},"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"kind":"symbol","topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/modalityNotSupported","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/standard","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/transitionFailed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/unknown"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/Equatable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Possible Values","type":"heading","anchor":"Possible-Values","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/unknown","isActive":true},{"type":"text","text":" - The transition type is unknown or unsupported."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/standard"},{"text":" - Standard direct transition.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/modalityNotSupported","isActive":true},{"type":"text","text":" - The transition was rejected because the conversation does not currently support the given Modality."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/transitionFailed","type":"reference"},{"text":" - The transition experienced an error and had to abort.","type":"text"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","title":"ModalityTransitionType","navigatorTitle":[{"text":"ModalityTransitionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/unknown":{"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype\/unknown","title":"unknown","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/unknown","navigatorTitle":[{"text":"SMIModalityTransitionTypeUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"The transition type is unknown or unsupported."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/transitionFailed":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ModalityTransitionType","kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/transitionfailed","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}],"abstract":[{"type":"text","text":"The transition experienced an error and had to abort."}],"title":"transitionFailed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/transitionFailed"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/standard":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}],"abstract":[{"type":"text","text":"Standard direct transition."}],"navigatorTitle":[{"text":"SMIModalityTransitionTypeStandard","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/standard","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/standard","title":"standard"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/modalityNotSupported":{"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/modalitynotsupported","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/modalityNotSupported","abstract":[{"text":"The transition was rejected because the conversation does not currently support the requested Modality.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modalityNotSupported","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","kind":"typeIdentifier","text":"ModalityTransitionType"}],"type":"topic","title":"modalityNotSupported"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/init(rawValue:)":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIModalityTransitionType","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIModalityTransitionType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIModalityTransitionType","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIModalityTransitionType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/title"},{"value":[{"kind":"identifier","text":"SMIModalityTransitionType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIModalityTransitionType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/navigatorTitle","op":"replace"},{"value":"SMIModalityTransitionTypeUnknown","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1unknown\/title","op":"replace"},{"value":[{"text":"SMIModalityTransitionTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1unknown\/fragments","op":"replace"},{"value":"SMIModalityTransitionTypeTransitionFailed","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1transitionFailed\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1transitionFailed\/fragments","op":"replace","value":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1standard\/title","op":"replace","value":"SMIModalityTransitionTypeStandard"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1standard\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIModalityTransitionTypeStandard"}]},{"value":"SMIModalityTransitionTypeModalityNotSupported","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1modalityNotSupported\/title"},{"value":[{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1modalityNotSupported\/fragments"}]}]}