{"kind":"symbol","metadata":{"externalID":"c:objc(pl)SMIModalityUpdate","role":"symbol","symbolKind":"protocol","title":"ModalityUpdate","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"ModalityUpdate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityUpdate","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityUpdate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"ConversationUpdateOperation","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","preciseIdentifier":"c:objc(pl)SMIConversationUpdateOperation"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/activeModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/transitionType"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/modalityupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/modalityupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityUpdate/transitionType":{"abstract":[],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/transitionType","navigatorTitle":[{"kind":"identifier","text":"transitionType"}],"title":"transitionType","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","kind":"typeIdentifier","text":"ModalityTransitionType"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/modalityupdate\/transitiontype"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityUpdate":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModalityUpdate"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ModalityUpdate"}],"url":"\/documentation\/smiclientcore\/modalityupdate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate","title":"ModalityUpdate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateOperation":{"url":"\/documentation\/smiclientcore\/conversationupdateoperation","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","role":"symbol","navigatorTitle":[{"text":"ConversationUpdateOperation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUpdateOperation","kind":"identifier"}],"type":"topic","title":"ConversationUpdateOperation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityUpdate/activeModalities":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"activeModalities","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"]"}],"url":"\/documentation\/smiclientcore\/modalityupdate\/activemodalities","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"activeModalities"}],"abstract":[],"title":"activeModalities","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/activeModalities"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIModalityUpdate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIModalityUpdate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIModalityUpdate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/activeModalities","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityUpdate\/transitionType"],"generated":true,"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIModalityUpdate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIConversationUpdateOperation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","preciseIdentifier":"c:objc(pl)SMIConversationUpdateOperation"},{"kind":"text","text":">"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"transitionType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate~1transitionType\/title"},{"value":[{"text":"transitionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate~1transitionType\/fragments"},{"value":"SMIModalityUpdate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate\/title"},{"value":[{"text":"SMIModalityUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate\/fragments"},{"value":[{"text":"SMIModalityUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate\/navigatorTitle"},{"value":"SMIConversationUpdateOperation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/title"},{"value":[{"text":"SMIConversationUpdateOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/fragments"},{"value":[{"text":"SMIConversationUpdateOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/navigatorTitle"},{"value":"activeModalities","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate~1activeModalities\/title"},{"value":[{"text":"activeModalities","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityUpdate~1activeModalities\/fragments"}]}]}