{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"Represents a named value variable item with a name and ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","type":"reference","isActive":true},{"text":".","type":"text"}],"sections":[],"metadata":{"externalID":"c:objc(pl)SMINamedValue","navigatorTitle":[{"text":"NamedValueProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValueProtocol","kind":"identifier"}],"title":"NamedValueProtocol","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/value"]}],"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/namedvalueprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/namedvalueprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValueProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValue":{"url":"\/documentation\/smiclientcore\/namedvalue","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","role":"symbol","navigatorTitle":[{"text":"NamedValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValue","kind":"identifier"}],"title":"NamedValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","title":"AbstractValueProtocol","role":"symbol","type":"topic","abstract":[{"text":"Protocol that defines the base type for session context values.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol/name":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/name","abstract":[{"type":"text","text":"The name of the context variable."}],"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/namedvalueprotocol\/name","navigatorTitle":[{"kind":"identifier","text":"name"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"name","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"navigatorTitle":[{"kind":"identifier","text":"NamedValueProtocol"}],"title":"NamedValueProtocol","abstract":[{"type":"text","text":"Represents a named value variable item with a name and "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/smiclientcore\/namedvalueprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValueProtocol"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","type":"topic","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol/value":{"title":"value","kind":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/value","url":"\/documentation\/smiclientcore\/namedvalueprotocol\/value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractValue","text":"AbstractValueProtocol","kind":"typeIdentifier"}],"required":true,"abstract":[{"text":"The value of the context variable.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMINamedValue","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol\/value"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue"],"type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMINamedValue","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/title","value":"SMINamedValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/fragments","value":[{"kind":"identifier","text":"SMINamedValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","value":"SMIAbstractValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title","value":"SMINamedValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol~1value\/fragments","value":[{"text":"value","kind":"identifier"}]}]}]}