{"variants":[{"paths":["\/documentation\/smiclientcore\/networkconnectivitystate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/networkconnectivitystate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"externalID":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState","symbolKind":"struct","title":"NetworkConnectivityState","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectivityState","kind":"identifier"}],"navigatorTitle":[{"text":"NetworkConnectivityState","kind":"identifier"}],"roleHeading":"Structure"},"abstract":[{"text":"An enum that defines the possible states of network connectivity.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/connected","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/offline"],"generated":true,"anchor":"Type-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/_SwiftNewtypeWrapper-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectivityState"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Possible-Values","type":"heading","level":2,"text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/offline"},{"type":"text","text":" - The device is currently offline and unable to connect to the network"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/connected","isActive":true},{"type":"text","text":" - The device has an active network connection"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Use this enum to determine the current state of network connectivity."},{"type":"text","text":" "},{"type":"text","text":"The state indicates whether the device is able to communicate with"},{"type":"text","text":" "},{"type":"text","text":"the network or is currently offline."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/smiclientcore\/networkconnectivitystate\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/init(rawValue:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/connected":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/connected","url":"\/documentation\/smiclientcore\/networkconnectivitystate\/connected","title":"connected","navigatorTitle":[{"text":"SMINetworkConnectivityStateConnected","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}],"abstract":[{"text":"The device has an active network connection.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the device is connected to a network and","type":"text"},{"text":" ","type":"text"},{"text":"can communicate with remote services.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NetworkConnectivityState","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","abstract":[{"type":"text","text":"An enum that defines the possible states of network connectivity."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectivityState","kind":"identifier"}],"type":"topic","title":"NetworkConnectivityState"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/Equatable-Implementations":{"kind":"article","url":"\/documentation\/smiclientcore\/networkconnectivitystate\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/Equatable-Implementations","type":"topic","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/_SwiftNewtypeWrapper-Implementations":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate\/_swiftnewtypewrapper-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/_SwiftNewtypeWrapper-Implementations","abstract":[],"type":"topic","title":"_SwiftNewtypeWrapper Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/offline":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate\/offline","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/offline","type":"topic","kind":"symbol","abstract":[{"text":"The device is currently offline and unable to connect to the network.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the device has no active network connection","type":"text"},{"text":" ","type":"text"},{"text":"and cannot communicate with remote services.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMINetworkConnectivityStateOffline","kind":"identifier"}],"title":"offline","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMINetworkConnectivityState","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMINetworkConnectivityState"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMINetworkConnectivityStateConnected","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1connected\/title"},{"value":[{"kind":"identifier","text":"SMINetworkConnectivityStateConnected"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1connected\/fragments","op":"replace"},{"value":"SMINetworkConnectivityState","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkConnectivityState"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkConnectivityState"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/navigatorTitle","op":"replace"},{"value":"SMINetworkConnectivityStateOffline","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1offline\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkConnectivityStateOffline"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1offline\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}