{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"symbolKind":"struct","roleHeading":"Structure","title":"NetworkMimeTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"sections":[],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/GZIP","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOC","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOCX","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationJSON","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationOctetStream","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationPDF","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLS","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLSX","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXML","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageBMP","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageGIF","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageJPEG","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imagePNG","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageTIFF","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/multiPartForm","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textCSV","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textEventStream","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textPlain"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to specify the content type of data being transmitted over the network.","type":"text"}]},{"type":"heading","level":2,"anchor":"Possible-Values","text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textPlain","type":"reference","isActive":true},{"type":"text","text":" - Represents plain text content"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textEventStream"},{"type":"text","text":" - Represents server-sent events stream"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationJSON","type":"reference","isActive":true},{"type":"text","text":" - Represents JSON data"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationOctetStream","type":"reference","isActive":true},{"text":" - Represents binary data","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imagePNG"},{"type":"text","text":" - Represents PNG image data"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageJPEG","isActive":true,"type":"reference"},{"text":" - Represents JPEG image data","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageBMP","isActive":true,"type":"reference"},{"type":"text","text":" - Represents BMP image data"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageGIF","isActive":true},{"type":"text","text":" - Represents GIF image data"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageTIFF","isActive":true,"type":"reference"},{"text":" - Represents TIFF image data","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/multiPartForm"},{"type":"text","text":" - Represents multipart form data"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/GZIP"},{"type":"text","text":" - Represents GZIP compressed data"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationPDF"},{"type":"text","text":" - Represents PDF document data"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOCX","isActive":true},{"type":"text","text":" - Represents DOCX document data"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOC","isActive":true,"type":"reference"},{"text":" - Represents DOC document data","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textCSV"},{"type":"text","text":" - Represents CSV data"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLS"},{"type":"text","text":" - Represents XLS spreadsheet data"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLSX","type":"reference"},{"text":" - Represents XLSX spreadsheet data","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXML","type":"reference","isActive":true},{"type":"text","text":" - Represents XML data"}],"type":"paragraph"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationPDF":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationPDF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}],"abstract":[{"text":"Represents PDF document data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting PDF documents.","type":"text"}],"role":"symbol","title":"applicationPDF","kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationpdf","type":"topic","navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationPDF"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageGIF":{"url":"\/documentation\/smiclientcore\/networkmimetypes\/imagegif","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageGIF","role":"symbol","kind":"symbol","title":"imageGIF","abstract":[{"type":"text","text":"Represents GIF image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting GIF format images."}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageGIF"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesImageGIF"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationOctetStream":{"url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationoctetstream","kind":"symbol","title":"applicationOctetStream","role":"symbol","navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationOctetStream","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationOctetStream","abstract":[{"type":"text","text":"Represents binary data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting raw binary data."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationOctetStream","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/multiPartForm":{"title":"multiPartForm","abstract":[{"text":"Represents multipart form data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting form data with file uploads.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SMINetworkMimeTypesMultiPartForm","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/multipartform","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/multiPartForm","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiPartForm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationXML":{"abstract":[{"text":"Represents XML data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting XML formatted data.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationxml","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXML","title":"applicationXML","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationXML","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationXML","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationXLS":{"type":"topic","abstract":[{"type":"text","text":"Represents XLS spreadsheet data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting Microsoft Excel spreadsheets in XLS format."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationXLS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationXLS"}],"title":"applicationXLS","kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationxls","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLS"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/GZIP":{"url":"\/documentation\/smiclientcore\/networkmimetypes\/gzip","kind":"symbol","title":"GZIP","role":"symbol","navigatorTitle":[{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/GZIP","abstract":[{"text":"Represents GZIP compressed data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting GZIP compressed content.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GZIP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/textPlain":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPlain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesTextPlain","kind":"identifier"}],"abstract":[{"text":"Represents plain text content.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting unformatted text data.","type":"text"}],"url":"\/documentation\/smiclientcore\/networkmimetypes\/textplain","type":"topic","title":"textPlain","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textPlain"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/textEventStream":{"abstract":[{"text":"Represents server-sent events stream.","type":"text"},{"text":" ","type":"text"},{"text":"Used for real-time server updates and event streaming.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textEventStream","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textEventStream","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"title":"textEventStream","kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/texteventstream","role":"symbol","navigatorTitle":[{"text":"SMINetworkMimeTypesTextEventStream","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageJPEG":{"type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/imagejpeg","role":"symbol","abstract":[{"type":"text","text":"Represents JPEG image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting JPEG format images."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageJPEG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesImageJPEG","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageJPEG","kind":"symbol","title":"imageJPEG"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageTIFF":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageTIFF","title":"imageTIFF","type":"topic","role":"symbol","navigatorTitle":[{"text":"SMINetworkMimeTypesImageTIFF","kind":"identifier"}],"abstract":[{"text":"Represents TIFF image data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting TIFF format images.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/imagetiff","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageTIFF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/textCSV":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textCSV"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"abstract":[{"type":"text","text":"Represents CSV data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting comma-separated values data."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textCSV","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesTextCSV"}],"role":"symbol","title":"textCSV","type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/textcsv"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationDOC":{"title":"applicationDOC","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOC","url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationdoc","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOC"}],"abstract":[{"type":"text","text":"Represents DOC document data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting Microsoft Word documents in DOC format."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDOC"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier","text":"NetworkMimeTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageBMP":{"title":"imageBMP","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageBMP","role":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/imagebmp","abstract":[{"type":"text","text":"Represents BMP image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting BMP format images."}],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageBMP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesImageBMP","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkMimeTypes","kind":"identifier"}],"kind":"symbol","title":"NetworkMimeTypes","navigatorTitle":[{"text":"NetworkMimeTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/Equatable-Implementations":{"type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/equatable-implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/Equatable-Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationJSON":{"url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationjson","abstract":[{"text":"Represents JSON data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting structured data in JSON format.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationJSON"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"kind":"symbol","title":"applicationJSON","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationJSON"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationJSON","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imagePNG":{"url":"\/documentation\/smiclientcore\/networkmimetypes\/imagepng","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imagePNG","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imagePNG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"title":"imagePNG","type":"topic","abstract":[{"type":"text","text":"Represents PNG image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting PNG format images."}],"navigatorTitle":[{"text":"SMINetworkMimeTypesImagePNG","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationDOCX":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOCX"}],"title":"applicationDOCX","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOCX","abstract":[{"text":"Represents DOCX document data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting Microsoft Word documents in DOCX format.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDOCX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationdocx","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationXLSX":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationXLSX","navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationXLSX","kind":"identifier"}],"abstract":[{"text":"Represents XLSX spreadsheet data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting Microsoft Excel spreadsheets in XLSX format.","type":"text"}],"title":"applicationXLSX","kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationxlsx","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationXLSX","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMINetworkMimeTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMINetworkMimeTypes"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationPDF\/title","value":"SMINetworkMimeTypesApplicationPDF"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationPDF\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationPDF"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageGIF\/title","value":"SMINetworkMimeTypesImageGIF"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageGIF\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesImageGIF"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationOctetStream\/title","value":"SMINetworkMimeTypesApplicationOctetStream"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationOctetStream\/fragments","value":[{"text":"SMINetworkMimeTypesApplicationOctetStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1multiPartForm\/title","value":"SMINetworkMimeTypesMultiPartForm"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1multiPartForm\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesMultiPartForm"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXML\/title","value":"SMINetworkMimeTypesApplicationXML"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXML\/fragments","value":[{"text":"SMINetworkMimeTypesApplicationXML","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXLS\/title","value":"SMINetworkMimeTypesApplicationXLS"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXLS\/fragments","value":[{"text":"SMINetworkMimeTypesApplicationXLS","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1GZIP\/title","value":"SMINetworkMimeTypesGZIP"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1GZIP\/fragments","value":[{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textPlain\/title","value":"SMINetworkMimeTypesTextPlain"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textPlain\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesTextPlain"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textEventStream\/title","value":"SMINetworkMimeTypesTextEventStream"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textEventStream\/fragments","value":[{"text":"SMINetworkMimeTypesTextEventStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageJPEG\/title","value":"SMINetworkMimeTypesImageJPEG"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageJPEG\/fragments","value":[{"text":"SMINetworkMimeTypesImageJPEG","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageTIFF\/title","value":"SMINetworkMimeTypesImageTIFF"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageTIFF\/fragments","value":[{"text":"SMINetworkMimeTypesImageTIFF","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textCSV\/title","value":"SMINetworkMimeTypesTextCSV"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textCSV\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesTextCSV"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOC\/title","value":"SMINetworkMimeTypesApplicationDOC"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOC\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageBMP\/title","value":"SMINetworkMimeTypesImageBMP"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageBMP\/fragments","value":[{"text":"SMINetworkMimeTypesImageBMP","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title","value":"SMINetworkMimeTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationJSON\/title","value":"SMINetworkMimeTypesApplicationJSON"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationJSON\/fragments","value":[{"text":"SMINetworkMimeTypesApplicationJSON","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imagePNG\/title","value":"SMINetworkMimeTypesImagePNG"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imagePNG\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesImagePNG"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOCX\/title","value":"SMINetworkMimeTypesApplicationDOCX"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOCX\/fragments","value":[{"text":"SMINetworkMimeTypesApplicationDOCX","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXLSX\/title","value":"SMINetworkMimeTypesApplicationXLSX"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationXLSX\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationXLSX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}