{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionExperienceType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractChoice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","text":"AbstractChoice","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"All properties and features which are exposed in this class are subject to change.","type":"text"}]}],"type":"aside"},{"style":"warning","name":"Warning","content":[{"inlineContent":[{"text":"Experimental features\/APIs may be removed without advanced notification at any time.","type":"text"},{"text":" ","type":"text"},{"text":"Any use of these features will ","type":"text"},{"type":"strong","inlineContent":[{"text":"NOT","type":"text"}]},{"text":" be offered any official support, until such time as they may be adopted as full and stable features.","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"variants":[{"paths":["\/documentation\/smiclientcore\/optionexperiencetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/optionexperiencetype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"OptionExperienceType"}],"title":"OptionExperienceType","externalID":"c:objc(pl)SMIOptionExperienceType","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","roleHeading":"Protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionExperienceType"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType\/content"],"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","role":"symbol","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractchoice","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"}],"abstract":[],"title":"AbstractChoice","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/OptionExperienceType/content":{"navigatorTitle":[{"text":"content","kind":"identifier"}],"type":"topic","kind":"symbol","required":true,"url":"\/documentation\/smiclientcore\/optionexperiencetype\/content","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType\/content","role":"symbol","title":"content","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"abstract":[]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/OptionExperienceType":{"role":"symbol","kind":"symbol","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionExperienceType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType","url":"\/documentation\/smiclientcore\/optionexperiencetype","navigatorTitle":[{"text":"OptionExperienceType","kind":"identifier"}],"title":"OptionExperienceType","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIOptionExperienceType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType\/content"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIOptionExperienceType"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIAbstractChoice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","preciseIdentifier":"c:objc(pl)SMIAbstractChoice"},{"kind":"text","text":">"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/title","value":"SMIAbstractChoice","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/fragments","value":[{"text":"SMIAbstractChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/navigatorTitle","value":[{"text":"SMIAbstractChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType~1content\/title","value":"content","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType~1content\/fragments","value":[{"text":"content","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/title","value":"SMIOptionExperienceType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/fragments","value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/navigatorTitle","value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}