{"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents an individual menu option available to a participant."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantclientmenuoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantclientmenuoption"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"identifier"}],"navigatorTitle":[{"text":"ParticipantClientMenuOption","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIParticipantClientMenuOption","roleHeading":"Protocol","title":"ParticipantClientMenuOption","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenuOption"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"typeIdentifier","text":"Choice","preciseIdentifier":"c:objc(pl)SMIChoice"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","isActive":true},{"type":"text","text":" to provide menu options for participants in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each option represents a specific action that can be performed by or on behalf of the participant."}]}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenuOption":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ParticipantClientMenuOption","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","url":"\/documentation\/smiclientcore\/participantclientmenuoption","abstract":[{"type":"text","text":"A protocol that represents an individual menu option available to a participant."}],"title":"ParticipantClientMenuOption","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"url":"\/documentation\/smiclientcore\/choice","navigatorTitle":[{"kind":"identifier","text":"Choice"}],"title":"Choice","type":"topic","abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Choice"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractChoice":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AbstractChoice","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractChoice","url":"\/documentation\/smiclientcore\/abstractchoice","abstract":[],"title":"AbstractChoice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractChoice","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIParticipantClientMenuOption","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIParticipantClientMenuOption"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)SMIChoice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"typeIdentifier","text":"SMIChoice"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIParticipantClientMenuOption","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/title"},{"value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/fragments"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenuOption"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/navigatorTitle"},{"value":"SMIChoice","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title"},{"value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments"},{"value":[{"kind":"identifier","text":"SMIChoice"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle"},{"value":"SMIAbstractChoice","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/title"},{"value":[{"text":"SMIAbstractChoice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/fragments"},{"value":[{"kind":"identifier","text":"SMIAbstractChoice"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractChoice\/navigatorTitle"}]}]}