{"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"ParticipantRole","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:SMIParticipantRole.h@T@SMIParticipantRole","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantRole","kind":"identifier"}],"navigatorTitle":[{"text":"ParticipantRole","kind":"identifier"}]},"abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantRole"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Possible Values","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/system","isActive":true},{"type":"text","text":" - Represents a system-level participant"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/user"},{"text":" - Represents an end user participant","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/agent","type":"reference","isActive":true},{"text":" - Represents a human agent participant","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/chatbot","isActive":true,"type":"reference"},{"text":" - Represents an automated chatbot participant","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/router","isActive":true,"type":"reference"},{"type":"text","text":" - Represents a routing system participant"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/supervisor"},{"type":"text","text":" - Represents a supervisory participant"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This enum is used to identify the role and permissions of participants in a conversation.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantrole"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantrole"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/agent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/chatbot","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/router","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/supervisor","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/system","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/user"],"anchor":"Type-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/Equatable-Implementations"],"anchor":"Default-Implementations","generated":true}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/agent":{"url":"\/documentation\/smiclientcore\/participantrole\/agent","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier","text":"ParticipantRole"}],"navigatorTitle":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/agent","title":"agent","role":"symbol","kind":"symbol","abstract":[{"text":"Represents a human agent participant.","type":"text"},{"text":" ","type":"text"},{"text":"Used for customer service representatives or support staff.","type":"text"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"navigatorTitle":[{"text":"ParticipantRole","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantrole","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantRole","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"role":"symbol","title":"ParticipantRole","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/system":{"abstract":[{"type":"text","text":"Represents a system-level participant."},{"type":"text","text":" "},{"type":"text","text":"Used for automated system messages."}],"type":"topic","role":"symbol","kind":"symbol","title":"system","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/system","url":"\/documentation\/smiclientcore\/participantrole\/system","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIParticipantRoleSystem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/participantrole\/equatable-implementations","kind":"article"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/supervisor":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supervisor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"url":"\/documentation\/smiclientcore\/participantrole\/supervisor","abstract":[{"type":"text","text":"Represents a supervisory participant."},{"type":"text","text":" "},{"type":"text","text":"Used for managers or supervisors overseeing conversations."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/supervisor","title":"supervisor","navigatorTitle":[{"text":"SMIParticipantRoleSupervisor","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/user":{"type":"topic","navigatorTitle":[{"text":"SMIParticipantRoleUser","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/user","title":"user","url":"\/documentation\/smiclientcore\/participantrole\/user","abstract":[{"type":"text","text":"Represents an end user participant."},{"type":"text","text":" "},{"type":"text","text":"Used for customers or users interacting with the conversation."}]},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/router":{"abstract":[{"text":"Represents a routing system participant.","type":"text"},{"text":" ","type":"text"},{"text":"Used for systems that handle conversation routing and assignment.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"router","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/router","type":"topic","navigatorTitle":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantrole\/router","title":"router","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/init(rawValue:)":{"type":"topic","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/participantrole\/init(rawvalue:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/chatbot":{"navigatorTitle":[{"text":"SMIParticipantRoleChatbot","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/participantrole\/chatbot","title":"chatbot","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatbot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/chatbot","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Represents an automated chatbot participant."}]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIParticipantRole","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIParticipantRole","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantRole"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIParticipantRole"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1agent\/title","value":"SMIParticipantRoleAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1agent\/fragments","value":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title","value":"SMIParticipantRole"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments","value":[{"kind":"identifier","text":"SMIParticipantRole"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle","value":[{"text":"SMIParticipantRole","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1system\/title","value":"SMIParticipantRoleSystem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1system\/fragments","value":[{"text":"SMIParticipantRoleSystem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1supervisor\/title","value":"SMIParticipantRoleSupervisor"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1supervisor\/fragments","value":[{"kind":"identifier","text":"SMIParticipantRoleSupervisor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1user\/title","value":"SMIParticipantRoleUser"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1user\/fragments","value":[{"kind":"identifier","text":"SMIParticipantRoleUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1router\/title","value":"SMIParticipantRoleRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1router\/fragments","value":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1chatbot\/title","value":"SMIParticipantRoleChatbot"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1chatbot\/fragments","value":[{"text":"SMIParticipantRoleChatbot","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}