{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"},"abstract":[{"type":"text","text":"An enum that defines the possible operations that can be performed on conversation participants."}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/init(rawValue:)"]},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/add","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/remove"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/Equatable-Implementations"]}],"variants":[{"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantchangedoperationtypes"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperationTypes"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to track changes in conversation participation. Each operation type represents","type":"text"},{"text":" ","type":"text"},{"text":"a different way that the participant list can be modified.","type":"text"}]},{"type":"heading","text":"Possible Values","level":2,"anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/add","isActive":true},{"type":"text","text":" - Indicates the action of adding a participant to the conversation"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/remove"},{"type":"text","text":" - Indicates the action of removing a participant from the conversation"}],"type":"paragraph"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperationTypes"}],"modules":[{"name":"SMIClientCore"}],"title":"ParticipantChangedOperationTypes","symbolKind":"struct","roleHeading":"Structure","externalID":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/init(rawValue:)","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"abstract":[{"text":"An enum that defines the possible operations that can be performed on conversation participants.","type":"text"}],"navigatorTitle":[{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","title":"ParticipantChangedOperationTypes","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/remove":{"abstract":[{"type":"text","text":"Indicates the action of removing a participant from the conversation."}],"navigatorTitle":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesRemove"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/remove","title":"remove","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","kind":"typeIdentifier","text":"ParticipantChangedOperationTypes"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/remove"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/add":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/add","title":"add","navigatorTitle":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"}],"abstract":[{"type":"text","text":"Indicates the action of adding a participant to the conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/add","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","text":"ParticipantChangedOperationTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes/Equatable-Implementations":{"url":"\/documentation\/smiclientcore\/participantchangedoperationtypes\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIParticipantChangedOperationTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypes"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title","value":"SMIParticipantChangedOperationTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1remove\/title","value":"SMIParticipantChangedOperationTypesRemove","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1remove\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesRemove"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1add\/title","value":"SMIParticipantChangedOperationTypesAdd","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes~1add\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperationTypesAdd"}],"op":"replace"}]}]}