{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/participant"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participant"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)SMIParticipant","role":"symbol","title":"Participant","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Participant","kind":"identifier"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}],"symbolKind":"protocol"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/clientMenu","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/displayName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/isLocal","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/role","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/subject"],"anchor":"Instance-Properties"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Use this protocol to access information about a participant in a conversation,"},{"type":"text","text":" "},{"type":"text","text":"including their role, identity, and available actions. Participants can be users,"},{"type":"text","text":" "},{"type":"text","text":"agents, or other entities that interact within the conversation."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/subject":{"url":"\/documentation\/smiclientcore\/participant\/subject","title":"subject","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/subject","navigatorTitle":[{"kind":"identifier","text":"subject"}],"abstract":[{"text":"The unique identifier for this participant.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a stable way to identify and reference the participant.","type":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Participant"}],"title":"Participant","url":"\/documentation\/smiclientcore\/participant","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"type":"topic","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/isLocal":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/isLocal","type":"topic","title":"isLocal","navigatorTitle":[{"text":"isLocal","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Indicates whether this participant represents the local device user."},{"text":" ","type":"text"},{"text":"This property helps identify the current local user in the conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/participant\/islocal","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLocal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/role":{"kind":"symbol","url":"\/documentation\/smiclientcore\/participant\/role","abstract":[{"type":"text","text":"The role assigned to this participant."}],"title":"role","type":"topic","role":"symbol","navigatorTitle":[{"text":"role","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/role","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"role","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/clientMenu":{"role":"symbol","url":"\/documentation\/smiclientcore\/participant\/clientmenu","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/clientMenu","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientMenu","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ParticipantClientMenu","preciseIdentifier":"c:objc(pl)SMIParticipantClientMenu","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","title":"clientMenu","abstract":[{"type":"text","text":"The client menu associated with this participant."}],"required":true,"navigatorTitle":[{"text":"clientMenu","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant/displayName":{"url":"\/documentation\/smiclientcore\/participant\/displayname","role":"symbol","title":"displayName","required":true,"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The display name for this participant."},{"type":"text","text":" "},{"type":"text","text":"This property provides the text shown in the UI to represent the participant."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/displayName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIParticipant"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIParticipant"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIParticipant","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/clientMenu","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/displayName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/isLocal","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/role","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant\/subject"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIParticipant","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1subject\/title","value":"subject","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1subject\/fragments","value":[{"text":"subject","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title","value":"SMIParticipant","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments","value":[{"text":"SMIParticipant","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle","value":[{"text":"SMIParticipant","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1isLocal\/title","value":"isLocal","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1isLocal\/fragments","value":[{"text":"isLocal","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1role\/title","value":"role","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1role\/fragments","value":[{"text":"role","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1clientMenu\/title","value":"clientMenu","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1clientMenu\/fragments","value":[{"kind":"identifier","text":"clientMenu"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1displayName\/title","value":"displayName","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant~1displayName\/fragments","value":[{"text":"displayName","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}