{"metadata":{"symbolKind":"typealias","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantQueryCompletion"}],"externalID":"c:SMIQueryCompletions.h@T@SMIParticipantQueryCompletion","roleHeading":"Type Alias","title":"ParticipantQueryCompletion","navigatorTitle":[{"kind":"identifier","text":"ParticipantQueryCompletion"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantQueryCompletion","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantQueryCompletion","kind":"identifier"},{"text":" = ([any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","preciseIdentifier":"c:objc(pl)SMIParticipant","text":"Participant","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"participants","content":[{"type":"paragraph","inlineContent":[{"text":"An unsorted array of ","type":"text"},{"code":"SMIParticipant","type":"codeVoice"},{"text":" results ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no results are found.","type":"text"}]}]},{"name":"conversation","content":[{"inlineContent":[{"type":"codeVoice","code":"SMIConversation"},{"type":"text","text":" object associated with all returned entries."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"If the query results in an error, it is returned here. An empty result is not considered an error."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"abstract":[{"type":"text","text":"Completion block for queries returning "},{"type":"codeVoice","code":"SMIParticipant"},{"type":"text","text":" objects."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/participantquerycompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantquerycompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantQueryCompletion":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ParticipantQueryCompletion","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantQueryCompletion","abstract":[{"text":"Completion block for queries returning ","type":"text"},{"code":"SMIParticipant","type":"codeVoice"},{"text":" objects.","type":"text"}],"url":"\/documentation\/smiclientcore\/participantquerycompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantQueryCompletion","kind":"identifier"}],"title":"ParticipantQueryCompletion","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","title":"Conversation","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"kind":"symbol","type":"topic","title":"Participant","navigatorTitle":[{"text":"Participant","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participant"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIParticipantQueryCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIParticipantQueryCompletion","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIParticipantQueryCompletion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSArray<id<SMIParticipant>> *, id<SMIConversation>, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*Qoobjc(pl)SMIConversation#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIParticipantQueryCompletion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantQueryCompletion\/title","value":"SMIParticipantQueryCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantQueryCompletion\/fragments","value":[{"text":"SMIParticipantQueryCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantQueryCompletion\/navigatorTitle","value":[{"text":"SMIParticipantQueryCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","value":"SMIConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"kind":"identifier","text":"SMIConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"text":"SMIConversation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title","value":"SMIParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments","value":[{"text":"SMIParticipant","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle","value":[{"text":"SMIParticipant","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}