{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperation"]}],"abstract":[{"type":"text","text":"A protocol that represents an operation describing a change to a participant in a conversation."}],"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperation"}],"title":"ParticipantChangedOperation","symbolKind":"protocol","externalID":"c:objc(pl)SMIParticipantChangedOperation","navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperation"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/displayName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/participant","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/type"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access information about participant changes in a conversation,"},{"type":"text","text":" "},{"type":"text","text":"such as when a participant joins or leaves."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation":{"role":"symbol","title":"ParticipantChangedOperation","kind":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperation","abstract":[{"type":"text","text":"A protocol that represents an operation describing a change to a participant in a conversation."}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperation"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperation"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/displayName":{"kind":"symbol","title":"displayName","type":"topic","navigatorTitle":[{"text":"displayName","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/displayName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/smiclientcore\/participantchangedoperation\/displayname","required":true,"abstract":[{"text":"The display name associated with this operation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a human-readable description of the operation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Participant","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/participant","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","title":"Participant","role":"symbol","kind":"symbol","abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"navigatorTitle":[{"text":"Participant","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/participant":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participant","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SMISerializable","text":"Serializable","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIParticipant","text":"Participant","kind":"typeIdentifier"}],"title":"participant","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/participant","abstract":[{"type":"text","text":"The participant affected by this operation."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","type":"reference","isActive":true},{"type":"text","text":" object that was changed."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"participant","kind":"identifier"}],"required":true,"url":"\/documentation\/smiclientcore\/participantchangedoperation\/participant","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","text":"ParticipantChangedOperationTypes","kind":"typeIdentifier"}],"abstract":[{"text":"The type of participant change operation being performed.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/type","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/participantchangedoperation\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"required":true,"title":"type"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIParticipantChangedOperation","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIParticipantChangedOperation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/displayName","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/participant","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/type"],"generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIParticipantChangedOperation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/title"},{"value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/fragments"},{"value":[{"text":"SMIParticipantChangedOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/navigatorTitle"},{"value":"displayName","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1displayName\/title"},{"value":[{"text":"displayName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1displayName\/fragments"},{"value":"SMIParticipant","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title"},{"value":[{"text":"SMIParticipant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments"},{"value":[{"kind":"identifier","text":"SMIParticipant"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle"},{"value":"participant","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1participant\/title"},{"value":[{"text":"participant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1participant\/fragments"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1type\/title"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1type\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}