{"variants":[{"paths":["\/documentation\/smiclientcore\/participantclientmenu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantclientmenu"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"A protocol that represents a menu of available actions for a participant.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenu"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMIParticipantClientMenu","role":"symbol","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantClientMenu"}],"roleHeading":"Protocol","title":"ParticipantClientMenu"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantClientMenu","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access the available menu options for a participant in a conversation."},{"type":"text","text":" "},{"type":"text","text":"The menu options represent actions that can be performed by or on behalf of the participant."}]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu\/options"],"generated":true,"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenu":{"title":"ParticipantClientMenu","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenu"}],"url":"\/documentation\/smiclientcore\/participantclientmenu","abstract":[{"type":"text","text":"A protocol that represents a menu of available actions for a participant."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantClientMenu"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenu/options":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIParticipantClientMenuOption","text":"ParticipantClientMenuOption","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/participantclientmenu\/options","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu\/options","required":true,"type":"topic","role":"symbol","navigatorTitle":[{"text":"options","kind":"identifier"}],"title":"options","abstract":[{"type":"text","text":"The array of available menu options for the participant."},{"type":"text","text":" "},{"type":"text","text":"Each option in the array represents a possible action that can be taken. The options"},{"type":"text","text":" "},{"type":"text","text":"are typically displayed in a menu or list interface for the user to select from."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIParticipantClientMenu","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIParticipantClientMenu","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantClientMenu"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu\/options"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIParticipantClientMenu","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/title","value":"SMIParticipantClientMenu","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/fragments","value":[{"text":"SMIParticipantClientMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/navigatorTitle","value":[{"text":"SMIParticipantClientMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu~1options\/title","value":"options","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu~1options\/fragments","value":[{"text":"options","kind":"identifier"}],"op":"replace"}]}]}