{"abstract":[{"type":"text","text":"A class that represents a verified user’s authentication credentials."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/passthroughverification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/passthroughverification"]}],"kind":"symbol","metadata":{"modules":[{"name":"SMIClientCore"}],"role":"symbol","title":"PassthroughVerification","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"externalID":"c:objc(cs)SMIPassthroughVerification","roleHeading":"Class","navigatorTitle":[{"text":"PassthroughVerification","kind":"identifier"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)-2r9jf"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/lastEventId"],"generated":true,"anchor":"Instance-Properties"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIAuthorization","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"This class allows you to take an existing valid minted MIAW JWT and pass that in with an authentication challenge.","type":"text"},{"text":" ","type":"text"},{"text":"This allows you to retrieve an authorized token independently, to pass into the SDK.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIAuthorization":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIAuthorization","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines the authorization requirements for API requests."}],"type":"topic","role":"symbol","title":"SMIAuthorization","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIAuthorization","kind":"identifier"}],"navigatorTitle":[{"text":"SMIAuthorization","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/smiauthorization"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/init(jwt:lastEventId:)-2r9jf":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)-2r9jf","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJWT:lastEventId:"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/passthroughverification\/init(jwt:lasteventid:)-2r9jf","type":"topic","title":"init(jwt:lastEventId:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","isActive":true,"type":"reference"},{"text":" with the specified credentials, which is used to pass in user verification credentials.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification/lastEventId":{"navigatorTitle":[{"kind":"identifier","text":"lastEventId"}],"kind":"symbol","title":"lastEventId","role":"symbol","abstract":[{"text":"The lastEventId represents the latest event which has been retrieved by a given authorized user.","type":"text"},{"text":" ","type":"text"},{"text":"When retrieving a MIAW JWT the lastEventId is also provided in the response.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/lastEventId","type":"topic","url":"\/documentation\/smiclientcore\/passthroughverification\/lasteventid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastEventId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","type":"topic","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}],"url":"\/documentation\/smiclientcore\/passthroughverification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"role":"symbol","title":"PassthroughVerification"},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"role":"symbol","type":"topic","title":"UserVerification","kind":"symbol","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerification"}],"navigatorTitle":[{"kind":"identifier","text":"UserVerification"}],"url":"\/documentation\/smiclientcore\/userverification"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIPassthroughVerification","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIPassthroughVerification","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/lastEventId"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification\/init(jwt:lastEventId:)-2r9jf"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPassthroughVerification","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","text":"SMIUserVerification","preciseIdentifier":"c:objc(cs)SMIUserVerification","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIAuthorization","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/fragments","op":"replace","value":[{"text":"SMIAuthorization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAuthorization"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)-2r9jf\/title","op":"replace","value":"initWithJWT:lastEventId:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1init(jwt:lastEventId:)-2r9jf\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJWT:lastEventId:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1lastEventId\/title","op":"replace","value":"lastEventId"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification~1lastEventId\/fragments","op":"replace","value":[{"kind":"identifier","text":"lastEventId"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title","op":"replace","value":"SMIPassthroughVerification"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","op":"replace","value":"SMIUserVerification"},{"op":"replace","value":[{"kind":"identifier","text":"SMIUserVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIUserVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}