{"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFAsset"}],"symbolKind":"protocol","title":"PDFAsset","externalID":"c:objc(pl)SMIPDFAsset","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"PDFAsset"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/pdfasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/pdfasset"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"]}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset\/pdf"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFAsset"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)SMIFileAsset","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","text":"FileAsset"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access PDF document assets in a conversation. This protocol extends"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","isActive":true,"type":"reference"},{"type":"text","text":" to provide PDF-specific functionality, allowing access to the PDF document"},{"type":"text","text":" "},{"type":"text","text":"content and metadata. PDFs are loaded asynchronously to optimize performance."}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A protocol that represents a PDF document asset in a conversation."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PDFAsset/pdf":{"kind":"symbol","required":true,"title":"pdf","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset\/pdf","url":"\/documentation\/smiclientcore\/pdfasset\/pdf","abstract":[{"type":"text","text":"The PDF document content of this asset."},{"type":"text","text":" "},{"type":"text","text":"This property is initially "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" and must be loaded using "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Once loaded, this property provides access to the PDF document for viewing and interaction."}],"role":"symbol","navigatorTitle":[{"text":"pdf","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdf","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFDocument","text":"PDFDocument","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fileasset","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"title":"FileAsset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PDFAsset":{"type":"topic","abstract":[{"text":"A protocol that represents a PDF document asset in a conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFAsset"}],"url":"\/documentation\/smiclientcore\/pdfasset","title":"PDFAsset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PDFAsset"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"title":"fetchContent(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)","role":"symbol","type":"topic","abstract":[{"text":"Fetches the content of this file asset asynchronously.","type":"text"},{"text":" ","type":"text"},{"text":"This method downloads the file content if it’s not already cached.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","navigatorTitle":[{"text":"fetchContentWithCompletion:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIPDFAsset"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIPDFAsset","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPDFAsset"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset\/pdf"],"title":"Instance Properties","anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPDFAsset","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIFileAsset","preciseIdentifier":"c:objc(pl)SMIFileAsset","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset~1pdf\/title","op":"replace","value":"pdf"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset~1pdf\/fragments","op":"replace","value":[{"kind":"identifier","text":"pdf"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","op":"replace","value":"SMIFileAsset"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","op":"replace","value":[{"text":"SMIFileAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFileAsset"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/title","op":"replace","value":"SMIPDFAsset"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPDFAsset"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/navigatorTitle","op":"replace","value":[{"text":"SMIPDFAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","op":"replace","value":"fetchContentWithCompletion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchContentWithCompletion:"}]}]}]}