{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult"},"abstract":[{"type":"text","text":"Represents an attachment upload that is in a pending state."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult\/referenceId"],"anchor":"Instance-Properties","generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/pendingattachmentuploadresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/pendingattachmentuploadresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"],"type":"inheritsFrom","kind":"relationships"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PendingAttachmentUploadResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","text":"AttachmentUploadResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"PendingAttachmentUploadResult"}],"modules":[{"name":"SMIClientCore"}],"title":"PendingAttachmentUploadResult","symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:objc(pl)SMIPendingAttachmentUploadResult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PendingAttachmentUploadResult","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PendingAttachmentUploadResult/referenceId":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult\/referenceId","title":"referenceId","navigatorTitle":[{"text":"referenceId","kind":"identifier"}],"abstract":[{"type":"text","text":"A unique reference identifier for the pending upload."},{"text":" ","type":"text"},{"type":"text","text":"This can be used to track the status of the upload or correlate it with other operations."}],"type":"topic","url":"\/documentation\/smiclientcore\/pendingattachmentuploadresult\/referenceid","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"referenceId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"abstract":[{"text":"Result of an attachment upload operation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResult"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","title":"AttachmentUploadResult","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResult"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/attachmentuploadresult"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PendingAttachmentUploadResult":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult","title":"PendingAttachmentUploadResult","navigatorTitle":[{"text":"PendingAttachmentUploadResult","kind":"identifier"}],"abstract":[{"text":"Represents an attachment upload that is in a pending state.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/pendingattachmentuploadresult","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PendingAttachmentUploadResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIPendingAttachmentUploadResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PendingAttachmentUploadResult\/referenceId"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIPendingAttachmentUploadResult"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentUploadResult","text":"SMIAttachmentUploadResult","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"},{"text":">","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult~1referenceId\/title","value":"referenceId"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult~1referenceId\/fragments","value":[{"kind":"identifier","text":"referenceId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title","value":"SMIAttachmentUploadResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments","value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAttachmentUploadResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/title","op":"replace","value":"SMIPendingAttachmentUploadResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/fragments","op":"replace","value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}]},{"value":[{"text":"SMIPendingAttachmentUploadResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PendingAttachmentUploadResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}