{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"PreChatConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIPreChatConfiguration","modules":[{"name":"SMIClientCore"}],"title":"PreChatConfiguration","roleHeading":"Protocol","symbolKind":"protocol"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/prechatconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A protocol that defines the configuration for a pre-chat form.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol represents the complete configuration for a pre-chat form, including"},{"type":"text","text":" "},{"text":"its type, visible fields, and hidden fields. The configuration determines how the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"pre-chat form is structured and what information is collected from users."}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/formType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/hiddenPreChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/preChatFields"],"generated":true,"anchor":"Instance-Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/preChatFields":{"abstract":[{"text":"The list of visible fields in the pre-chat form.","type":"text"},{"text":" ","type":"text"},{"text":"These fields are displayed to users and can be filled out directly.","type":"text"},{"text":" ","type":"text"},{"text":"Each field is an instance of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","type":"reference","isActive":true},{"text":".","type":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/preChatFields","navigatorTitle":[{"kind":"identifier","text":"preChatFields"}],"title":"preChatFields","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatFields"},{"kind":"text","text":": [any "},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","kind":"typeIdentifier","text":"PreChatField"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/prechatconfiguration\/prechatfields"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"title":"PreChatField","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatField"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechatfield"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/hiddenPreChatFields":{"url":"\/documentation\/smiclientcore\/prechatconfiguration\/hiddenprechatfields","abstract":[{"type":"text","text":"The list of hidden fields in the pre-chat form."},{"type":"text","text":" "},{"type":"text","text":"These fields are not displayed to users but can contain values set programmatically."},{"type":"text","text":" "},{"text":"Each field is an instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/hiddenPreChatFields","role":"symbol","navigatorTitle":[{"text":"hiddenPreChatFields","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hiddenPreChatFields","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"HiddenPreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatField"},{"text":"]","kind":"text"}],"required":true,"type":"topic","title":"hiddenPreChatFields"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration":{"url":"\/documentation\/smiclientcore\/prechatconfiguration","abstract":[{"text":"A protocol that defines the configuration for a pre-chat form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration","role":"symbol","navigatorTitle":[{"text":"PreChatConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatConfiguration","kind":"identifier"}],"type":"topic","title":"PreChatConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration/formType":{"title":"formType","required":true,"abstract":[{"text":"The type of form this configuration represents.","type":"text"},{"text":" ","type":"text"},{"text":"This value determines the form’s behavior and presentation.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechatconfiguration\/formtype","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/formType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes","text":"SMIPreChatConfigurationFormTypes"}],"navigatorTitle":[{"kind":"identifier","text":"formType"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"abstract":[{"text":"A protocol that represents a hidden pre-chat field in the conversation configuration.","type":"text"}],"title":"HiddenPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIPreChatConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/formType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/hiddenPreChatFields","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration\/preChatFields"],"generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfiguration","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"preChatFields","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1preChatFields\/title","op":"replace"},{"value":[{"text":"preChatFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1preChatFields\/fragments","op":"replace"},{"value":"SMIPreChatField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","op":"replace"},{"value":"hiddenPreChatFields","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1hiddenPreChatFields\/title","op":"replace"},{"value":[{"text":"hiddenPreChatFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1hiddenPreChatFields\/fragments","op":"replace"},{"value":"SMIPreChatConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/title","op":"replace"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/navigatorTitle","op":"replace"},{"value":"formType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1formType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"formType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration~1formType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title","value":"SMIHiddenPreChatField"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle","value":[{"text":"SMIHiddenPreChatField","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}