{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"},"abstract":[{"text":"An enum that defines the possible validation errors for pre-chat fields.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/booleanFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/checkBoxSelected","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/emailFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/none","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/numberFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/phoneFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/requiredField"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum represents the different types of validation errors that can occur"},{"type":"text","text":" "},{"type":"text","text":"when validating pre-chat form fields. Each error type corresponds to a specific"},{"type":"text","text":" "},{"type":"text","text":"validation failure case."}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"SMIClientCore"}],"externalID":"c:@E@SMIPreChatErrorTypes","role":"symbol","navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"title":"PreChatErrorTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatErrorTypes"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/maxLength":{"navigatorTitle":[{"text":"SMIPreChatErrorTypesMaxLength","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes\/maxlength","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/maxLength","type":"topic","abstract":[{"type":"text","text":"Indicates that a field’s value exceeds its maximum allowed length."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input text is longer than the field’s "},{"type":"codeVoice","code":"maxLength"},{"type":"text","text":" property."}],"role":"symbol","title":"PreChatErrorTypes.maxLength","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible validation errors for pre-chat fields."}],"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/booleanFormat":{"kind":"symbol","role":"symbol","title":"PreChatErrorTypes.booleanFormat","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesBooleanFormat"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanFormat"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/booleanFormat","url":"\/documentation\/smiclientcore\/prechaterrortypes\/booleanformat","abstract":[{"text":"Indicates that a boolean field contains an invalid value.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input is not “true” or “false”.","type":"text"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/emailFormat":{"title":"PreChatErrorTypes.emailFormat","type":"topic","kind":"symbol","abstract":[{"text":"Indicates that an email field contains an invalid email address format.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input doesn’t match standard email address patterns.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emailFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SMIPreChatErrorTypesEmailFormat","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes\/emailformat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/emailFormat"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/prechaterrortypes\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/init(rawValue:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/smiclientcore\/prechaterrortypes\/rawrepresentable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/RawRepresentable-Implementations","abstract":[],"kind":"article","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/prechaterrortypes\/equatable-implementations","abstract":[],"kind":"article","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/numberFormat":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/numberFormat","type":"topic","title":"PreChatErrorTypes.numberFormat","abstract":[{"text":"Indicates that a number field contains non-numeric characters.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input contains characters other than digits.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes\/numberformat","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesNumberFormat"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/checkBoxSelected":{"url":"\/documentation\/smiclientcore\/prechaterrortypes\/checkboxselected","kind":"symbol","title":"PreChatErrorTypes.checkBoxSelected","role":"symbol","type":"topic","abstract":[{"text":"Indicates that a required checkbox field is not selected.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a checkbox marked as required is not checked.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkBoxSelected"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/checkBoxSelected","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesCheckBoxSelected"}]},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/phoneFormat":{"url":"\/documentation\/smiclientcore\/prechaterrortypes\/phoneformat","role":"symbol","abstract":[{"type":"text","text":"Indicates that a phone field contains an invalid phone number format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input doesn’t match standard phone number patterns."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneFormat"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/phoneFormat","title":"PreChatErrorTypes.phoneFormat","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesPhoneFormat"}]},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/requiredField":{"url":"\/documentation\/smiclientcore\/prechaterrortypes\/requiredfield","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/requiredField","title":"PreChatErrorTypes.requiredField","navigatorTitle":[{"text":"SMIPreChatErrorTypesRequiredField","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Indicates that a required field was left empty."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when a field marked as required has no value."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/none":{"navigatorTitle":[{"text":"SMIPreChatErrorTypesNone","kind":"identifier"}],"role":"symbol","title":"PreChatErrorTypes.none","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/none","kind":"symbol","abstract":[{"text":"Indicates that no validation errors were detected.","type":"text"},{"text":" ","type":"text"},{"text":"This value is returned when all validation checks pass successfully.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIPreChatErrorTypes","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/booleanFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/checkBoxSelected","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/emailFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/none","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/numberFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/phoneFormat","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/requiredField"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIPreChatErrorTypes"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIPreChatErrorTypesMaxLength","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1maxLength\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesMaxLength"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1maxLength\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle","op":"replace"},{"value":"SMIPreChatErrorTypesBooleanFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1booleanFormat\/title","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypesBooleanFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1booleanFormat\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesEmailFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1emailFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesEmailFormat"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1emailFormat\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesNumberFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1numberFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesNumberFormat"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1numberFormat\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesCheckBoxSelected","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1checkBoxSelected\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesCheckBoxSelected"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1checkBoxSelected\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesPhoneFormat","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1phoneFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesPhoneFormat"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1phoneFormat\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesRequiredField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1requiredField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesRequiredField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1requiredField\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypesNone","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1none\/title","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypesNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1none\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}