{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"],"title":"Inherits From"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"externalID":"c:objc(pl)SMIPreChatChoiceListField","title":"PreChatChoiceListField","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatChoiceListField","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PreChatChoiceListField"}],"role":"symbol","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/prechatchoicelistfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatchoicelistfield"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A protocol that defines a choice list field in the pre-chat form."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatChoiceListField"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatField","text":"PreChatField"}]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This protocol represents a field in the pre-chat form that presents users with a list of options to choose from.","type":"text"},{"text":" ","type":"text"},{"text":"It extends ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},{"text":" and adds functionality for managing a collection of predefined choices.","type":"text"},{"text":" ","type":"text"},{"text":"The field can be configured with a specific ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},{"text":" that defines the available options.","type":"text"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceList","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceListId"],"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField/choiceListId":{"title":"choiceListId","required":true,"abstract":[{"text":"The identifier of the choice list associated with this field.","type":"text"},{"text":" ","type":"text"},{"text":"This ID is used to reference the specific ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","type":"reference","isActive":true},{"text":" that contains the available options.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechatchoicelistfield\/choicelistid","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceListId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceListId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"choiceListId","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","title":"ChoiceListValue","navigatorTitle":[{"text":"ChoiceListValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a single option within a choice list in pre-chat."}],"type":"topic","url":"\/documentation\/smiclientcore\/choicelistvalue","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField/choiceList":{"url":"\/documentation\/smiclientcore\/prechatchoicelistfield\/choicelist","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceList","abstract":[{"type":"text","text":"The choice list that defines the available options for this field."},{"type":"text","text":" "},{"type":"text","text":"This object contains the collection of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","type":"reference","isActive":true},{"text":" objects that users can select from.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"choiceList"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"choiceList","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIChoiceList","text":"ChoiceList","kind":"typeIdentifier"}],"required":true,"type":"topic","title":"choiceList"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"title":"PreChatField","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatField"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechatfield"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField","abstract":[{"type":"text","text":"A protocol that defines a choice list field in the pre-chat form."}],"role":"symbol","navigatorTitle":[{"text":"PreChatChoiceListField","kind":"identifier"}],"title":"PreChatChoiceListField","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatChoiceListField","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechatchoicelistfield"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","navigatorTitle":[{"text":"ChoiceList","kind":"identifier"}],"title":"ChoiceList","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelist"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIPreChatChoiceListField"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatChoiceListField"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatChoiceListField"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceList","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceListId"],"anchor":"Instance-Properties","title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatChoiceListField","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","text":"SMIPreChatField","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceListId\/title","op":"replace","value":"choiceListId"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceListId\/fragments","op":"replace","value":[{"text":"choiceListId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/title","op":"replace","value":"SMIChoiceListValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/fragments","op":"replace","value":[{"text":"SMIChoiceListValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIChoiceListValue"}]},{"value":"choiceList","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceList\/title"},{"value":[{"text":"choiceList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceList\/fragments"},{"value":"SMIPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title"},{"value":[{"text":"SMIPreChatField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","op":"replace"},{"value":"SMIPreChatChoiceListField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatChoiceListField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatChoiceListField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/navigatorTitle","op":"replace"},{"op":"replace","value":"SMIChoiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title"},{"op":"replace","value":[{"text":"SMIChoiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments"},{"value":[{"text":"SMIChoiceList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle"}]}]}