{"abstract":[{"text":"A type that defines the available field types for the pre-chat form.","type":"text"}],"metadata":{"roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatFieldTypes","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"PreChatFieldTypes","kind":"identifier"}],"symbolKind":"struct","role":"symbol","externalID":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","title":"PreChatFieldTypes"},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/init(rawValue:)"]},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/checkbox","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/choiceList","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/email","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/number","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/phone","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/text","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/textArea"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/Equatable-Implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatFieldTypes","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This type represents the different kinds of input fields that can be used in the pre-chat form."},{"type":"text","text":" "},{"type":"text","text":"Each field type has its own validation rules and UI presentation requirements."},{"type":"text","text":" "},{"type":"text","text":"The following field types are available:"}],"type":"paragraph"},{"anchor":"Possible-Values","text":"Possible Values","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/text"},{"type":"text","text":" - For single-line text input"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/textArea"},{"text":" - For multi-line text input","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/email","type":"reference"},{"text":" - For email addresses","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/number","isActive":true},{"type":"text","text":" - For numeric values"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/phone"},{"type":"text","text":" - For phone numbers"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/checkbox","type":"reference"},{"type":"text","text":" - For boolean values"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/choiceList","isActive":true,"type":"reference"},{"type":"text","text":" - For selecting from predefined options"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfieldtypes"]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/text":{"type":"topic","abstract":[{"type":"text","text":"A field type for single-line text input."},{"type":"text","text":" "},{"type":"text","text":"Use this type for short text inputs such as names or short answers."}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesText"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/text","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/text","kind":"symbol","title":"text"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/choiceList":{"type":"topic","navigatorTitle":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","text":"PreChatFieldTypes","kind":"typeIdentifier"}],"title":"choiceList","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/choiceList","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/choicelist","abstract":[{"type":"text","text":"A field type for selecting from predefined options."},{"type":"text","text":" "},{"type":"text","text":"Use this type when you want users to choose from a list of predefined values."},{"type":"text","text":" "},{"type":"text","text":"The available options are defined by an associated "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","isActive":true},{"type":"text","text":"."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}],"title":"ChoiceList","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/textArea":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/textarea","abstract":[{"type":"text","text":"A field type for multi-line text input."},{"type":"text","text":" "},{"type":"text","text":"Use this type for longer text inputs that may require multiple lines."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/textArea","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textArea","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","text":"PreChatFieldTypes","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SMIPreChatFieldTypesTextArea","kind":"identifier"}],"role":"symbol","title":"textArea"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/number":{"type":"topic","role":"symbol","title":"number","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"number","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIPreChatFieldTypesNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/number","abstract":[{"text":"A field type for numeric values.","type":"text"},{"text":" ","type":"text"},{"text":"Use this type when collecting numbers.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/number"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/phone":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/phone","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/phone","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreChatFieldTypes","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatFieldTypesPhone"}],"kind":"symbol","type":"topic","title":"phone","abstract":[{"type":"text","text":"A field type for phone numbers."},{"type":"text","text":" "},{"type":"text","text":"Use this type when collecting phone numbers."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/checkbox":{"abstract":[{"text":"A field type for boolean values.","type":"text"},{"text":" ","type":"text"},{"text":"Use this type for true\/false choices.","type":"text"}],"kind":"symbol","title":"checkbox","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PreChatFieldTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes"}],"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/checkbox","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/checkbox","role":"symbol","navigatorTitle":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/Equatable-Implementations","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/equatable-implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatFieldTypes"}],"abstract":[{"type":"text","text":"A type that defines the available field types for the pre-chat form."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes","title":"PreChatFieldTypes","navigatorTitle":[{"kind":"identifier","text":"PreChatFieldTypes"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/init(rawValue:)":{"url":"\/documentation\/smiclientcore\/prechatfieldtypes\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/init(rawValue:)","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatFieldTypes/email":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatFieldTypes\/email","title":"email","kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/prechatfieldtypes\/email","abstract":[{"type":"text","text":"A field type for email addresses."},{"type":"text","text":" "},{"type":"text","text":"Use this type when collecting email addresses."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","text":"PreChatFieldTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIPreChatFieldTypesEmail","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMIPreChatFieldTypes","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPreChatFieldTypes"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIPreChatFieldTypes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1text\/title","op":"replace","value":"SMIPreChatFieldTypesText"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1text\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1choiceList\/title","op":"replace","value":"SMIPreChatFieldTypesChoiceList"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1choiceList\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesChoiceList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","op":"replace","value":"SMIChoiceList"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIChoiceList"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","op":"replace","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1textArea\/title","op":"replace","value":"SMIPreChatFieldTypesTextArea"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1textArea\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatFieldTypesTextArea"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1number\/title","op":"replace","value":"SMIPreChatFieldTypesNumber"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1number\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatFieldTypesNumber"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1phone\/title","op":"replace","value":"SMIPreChatFieldTypesPhone"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1phone\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatFieldTypesPhone"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1checkbox\/title","op":"replace","value":"SMIPreChatFieldTypesCheckbox"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1checkbox\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesCheckbox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/title","op":"replace","value":"SMIPreChatFieldTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIPreChatFieldTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1email\/title","op":"replace","value":"SMIPreChatFieldTypesEmail"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatFieldTypes~1email\/fragments","op":"replace","value":[{"text":"SMIPreChatFieldTypesEmail","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}