{"sections":[],"abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfield"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}]}]},{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"This protocol represents a field that can be displayed in the pre-chat form."},{"type":"text","text":" "},{"type":"text","text":"Each field has a specific type, validation rules, and UI presentation requirements."},{"type":"text","text":" "},{"type":"text","text":"Fields can be configured as required or optional, and can have maximum length constraints."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isEditable","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isHidden","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/order","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/type","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/value"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/validate()"],"anchor":"Instance-Methods","generated":true}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIPreChatField","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"protocol","title":"PreChatField"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/value":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechatfield\/value","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/value","kind":"symbol","type":"topic","title":"value","required":true,"abstract":[{"type":"text","text":"The current value of this field."},{"type":"text","text":" "},{"type":"text","text":"This value can be set programmatically."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/validate()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PreChatErrorTypes","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIPreChatErrorTypes"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/validate()","required":true,"title":"validate()","abstract":[{"type":"text","text":"Validates the current value of this field."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/prechatfield\/validate()","navigatorTitle":[{"text":"validate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/maxLength":{"abstract":[{"text":"The maximum number of characters allowed in this field.","type":"text"},{"text":" ","type":"text"},{"text":"This value is used to validate the field’s content length.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechatfield\/maxlength","kind":"symbol","role":"symbol","title":"maxLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"maxLength"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/maxLength","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/identifier":{"role":"symbol","url":"\/documentation\/smiclientcore\/prechatfield\/identifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/identifier","title":"identifier","abstract":[{"type":"text","text":"A unique identifier for this field."},{"type":"text","text":" "},{"type":"text","text":"This identifier is used to associate the field with its data in the conversation."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/name":{"abstract":[{"text":"The internal name for this field.","type":"text"},{"text":" ","type":"text"},{"text":"This name is used to identify the field in the system.","type":"text"}],"url":"\/documentation\/smiclientcore\/prechatfield\/name","kind":"symbol","role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"name"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/name","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/isEditable":{"title":"isEditable","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isEditable","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEditable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/smiclientcore\/prechatfield\/iseditable","navigatorTitle":[{"kind":"identifier","text":"editable"}],"abstract":[{"text":"Indicates whether this field can be edited by the user.","type":"text"},{"text":" ","type":"text"},{"text":"When false, the field’s value can only be set programmatically, defaults to true.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/isHidden":{"kind":"symbol","navigatorTitle":[{"text":"isHidden","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isHidden","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isHidden","required":true,"url":"\/documentation\/smiclientcore\/prechatfield\/ishidden","type":"topic","abstract":[{"text":"Indicates whether this field should be hidden from the user.","type":"text"},{"text":" ","type":"text"},{"text":"Hidden fields are not displayed in the pre-chat form but can still contain values.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatField":{"title":"HiddenPreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HiddenPreChatField"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a hidden pre-chat field in the conversation configuration."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HiddenPreChatField"}],"url":"\/documentation\/smiclientcore\/hiddenprechatfield"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/type":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/type","kind":"symbol","title":"type","type":"topic","url":"\/documentation\/smiclientcore\/prechatfield\/type","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIPreChatFieldTypes.h@T@SMIPreChatFieldTypes","kind":"typeIdentifier","text":"PreChatFieldTypes"}],"abstract":[{"type":"text","text":"The type of this field."},{"type":"text","text":" "},{"type":"text","text":"This value determines the field’s validation rules and UI presentation."}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"symbol","title":"PreChatField","type":"topic","url":"\/documentation\/smiclientcore\/prechatfield","role":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/order":{"required":true,"role":"symbol","abstract":[{"type":"text","text":"The display order of this field in the form."},{"type":"text","text":" "},{"type":"text","text":"Fields are displayed in ascending order based on this value."}],"title":"order","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/order","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"order"}],"url":"\/documentation\/smiclientcore\/prechatfield\/order"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatChoiceListField"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField","url":"\/documentation\/smiclientcore\/prechatchoicelistfield","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines a choice list field in the pre-chat form."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatChoiceListField"}],"title":"PreChatChoiceListField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/isRequired":{"title":"isRequired","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"required"}],"abstract":[{"type":"text","text":"Indicates whether this field must be filled out before submission."},{"type":"text","text":" "},{"type":"text","text":"When true, the field must contain a valid "},{"code":"value","type":"codeVoice"},{"type":"text","text":" to pass validation."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/prechatfield\/isrequired","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isRequired"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/label":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/label","abstract":[{"type":"text","text":"The display label for this field."},{"type":"text","text":" "},{"type":"text","text":"This text is shown to the user in the pre-chat form."}],"kind":"symbol","title":"label","navigatorTitle":[{"kind":"identifier","text":"label"}],"required":true,"url":"\/documentation\/smiclientcore\/prechatfield\/label","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIPreChatField","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/identifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isEditable","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isHidden","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/label","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/maxLength","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/order","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/type","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/value"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/validate()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatField","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIPreChatField"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1value\/title"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1value\/fragments"},{"op":"replace","value":"validate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1validate()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1validate()\/fragments"},{"op":"replace","value":"maxLength","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1maxLength\/title"},{"op":"replace","value":[{"text":"maxLength","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1maxLength\/fragments"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1identifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1identifier\/fragments"},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1name\/title"},{"op":"replace","value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1name\/fragments"},{"op":"replace","value":"editable","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isEditable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"editable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isEditable\/fragments"},{"op":"replace","value":"isHidden","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isHidden\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isHidden"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isHidden\/fragments"},{"op":"replace","value":"SMIHiddenPreChatField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatField\/navigatorTitle"},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1type\/title"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1type\/fragments"},{"op":"replace","value":"SMIPreChatField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title"},{"op":"replace","value":[{"text":"SMIPreChatField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments"},{"op":"replace","value":[{"text":"SMIPreChatField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle"},{"op":"replace","value":"order","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1order\/title"},{"op":"replace","value":[{"text":"order","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1order\/fragments"},{"op":"replace","value":"SMIPreChatChoiceListField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/title"},{"op":"replace","value":[{"text":"SMIPreChatChoiceListField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/fragments"},{"op":"replace","value":[{"text":"SMIPreChatChoiceListField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/navigatorTitle"},{"op":"replace","value":"required","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isRequired\/title"},{"op":"replace","value":[{"text":"required","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isRequired\/fragments"},{"op":"replace","value":"label","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1label\/title"},{"op":"replace","value":[{"kind":"identifier","text":"label"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1label\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}