{"kind":"symbol","metadata":{"roleHeading":"Structure","externalID":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressIndicatorTypes","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"ProgressIndicatorTypes"}],"title":"ProgressIndicatorTypes"},"abstract":[{"type":"text","text":"An enum that defines the possible types of progress indicators in a conversation."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressIndicatorTypes","kind":"identifier"}]}]},{"kind":"content","content":[{"anchor":"Possible-Values","type":"heading","level":2,"text":"Possible Values"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/update","isActive":true,"type":"reference"},{"text":" - Indicates the action of updating progress information","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to categorize different types of progress indicators that can appear in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"Each type represents a specific progress indicator state that has been triggered.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"]}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/progressindicatortypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/progressindicatortypes"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/update"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/_SwiftNewtypeWrapper-Implementations"],"anchor":"Default-Implementations"}],"references":{"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes":{"title":"ProgressIndicatorTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressIndicatorTypes"}],"abstract":[{"text":"An enum that defines the possible types of progress indicators in a conversation.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressIndicatorTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","url":"\/documentation\/smiclientcore\/progressindicatortypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/init(rawValue:)":{"url":"\/documentation\/smiclientcore\/progressindicatortypes\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/init(rawValue:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/update":{"role":"symbol","abstract":[{"type":"text","text":"Indicates the action of updating progress information."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/update","kind":"symbol","navigatorTitle":[{"text":"SMIProgressIndicatorTypesUpdate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProgressIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes"}],"url":"\/documentation\/smiclientcore\/progressindicatortypes\/update","title":"update"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/smiclientcore\/progressindicatortypes\/equatable-implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/_SwiftNewtypeWrapper-Implementations":{"kind":"article","title":"_SwiftNewtypeWrapper Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/_SwiftNewtypeWrapper-Implementations","abstract":[],"url":"\/documentation\/smiclientcore\/progressindicatortypes\/_swiftnewtypewrapper-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIProgressIndicatorTypes","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIProgressIndicatorTypes"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIProgressIndicatorTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIProgressIndicatorTypes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIProgressIndicatorTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIProgressIndicatorTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/fragments","op":"replace"},{"value":[{"text":"SMIProgressIndicatorTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/navigatorTitle","op":"replace"},{"value":"SMIProgressIndicatorTypesUpdate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes~1update\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIProgressIndicatorTypesUpdate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes~1update\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}