{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour"},"abstract":[{"type":"text","text":"The offline and network behaviour of an entry query."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localOnly","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/waitForNetwork"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The offline and network behaviour of an entry query."}]}]}],"metadata":{"externalID":"c:@E@SMIQueryBehaviour","symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}],"title":"QueryBehaviour","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"QueryBehaviour","kind":"identifier"}]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/querybehaviour"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/querybehaviour"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/localWithNetwork":{"abstract":[{"text":"Will return locally cached entities immediately within the completion of the query.","type":"text"}],"title":"QueryBehaviour.localWithNetwork","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localWithNetwork","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/querybehaviour\/localwithnetwork","navigatorTitle":[{"text":"SMIQueryBehaviourLocalWithNetwork","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/waitForNetwork":{"role":"symbol","abstract":[{"type":"text","text":"Similar to "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","isActive":true},{"type":"text","text":" this will return locally cached entities as well as attempt to resolve any"},{"type":"text","text":" "},{"type":"text","text":"missing entities and update the local cache."}],"url":"\/documentation\/smiclientcore\/querybehaviour\/waitfornetwork","navigatorTitle":[{"kind":"identifier","text":"SMIQueryBehaviourWaitForNetwork"}],"kind":"symbol","title":"QueryBehaviour.waitForNetwork","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForNetwork"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/waitForNetwork"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/localOnly":{"role":"symbol","url":"\/documentation\/smiclientcore\/querybehaviour\/localonly","type":"topic","title":"QueryBehaviour.localOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localOnly"}],"navigatorTitle":[{"text":"SMIQueryBehaviourLocalOnly","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localOnly","kind":"symbol","abstract":[{"type":"text","text":"Will return locally cached entities immediately within the completion of the query."}]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour":{"abstract":[{"text":"The offline and network behaviour of an entry query.","type":"text"}],"kind":"symbol","title":"QueryBehaviour","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueryBehaviour","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour","navigatorTitle":[{"text":"QueryBehaviour","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/querybehaviour"},"doc://com.salesforce.SMIClientCore/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/smiclientcore\/querybehaviour\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","kind":"article"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/init(rawValue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/querybehaviour\/init(rawvalue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QueryBehaviour/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/smiclientcore\/querybehaviour\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SMIQueryBehaviour"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIQueryBehaviour","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localOnly","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/localWithNetwork","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QueryBehaviour\/waitForNetwork"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIQueryBehaviour","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/title","value":"SMIQueryBehaviourLocalWithNetwork"},{"value":[{"kind":"identifier","text":"SMIQueryBehaviourLocalWithNetwork"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localWithNetwork\/fragments"},{"value":"SMIQueryBehaviourWaitForNetwork","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1waitForNetwork\/title"},{"value":[{"kind":"identifier","text":"SMIQueryBehaviourWaitForNetwork"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1waitForNetwork\/fragments"},{"value":"SMIQueryBehaviourLocalOnly","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localOnly\/title"},{"value":[{"kind":"identifier","text":"SMIQueryBehaviourLocalOnly"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour~1localOnly\/fragments"},{"value":"SMIQueryBehaviour","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/title"},{"value":[{"text":"SMIQueryBehaviour","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/fragments"},{"value":[{"text":"SMIQueryBehaviour","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QueryBehaviour\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}