{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply"},"kind":"symbol","abstract":[{"type":"text","text":"A protocol that represents a quick reply within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickReply"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","text":"EntryPayload"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","text":"EntryTypeMessage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","preciseIdentifier":"c:objc(pl)SMIMessageChoices","text":"MessageChoices"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","preciseIdentifier":"c:objc(pl)SMIMessageSelectable","text":"MessageSelectable"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access the content of a quick reply displayed in a conversation."},{"type":"text","text":" "},{"type":"text","text":"A quick reply provides users with predefined response options to quickly respond to a message."}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/quickreply"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/quickreply"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"QuickReply"}],"title":"QuickReply","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuickReply"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)SMIQuickReply"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply\/text"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"kind":"symbol","type":"topic","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSelectable"}],"abstract":[{"type":"text","text":"A protocol that represents a message with selectable choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"title":"MessageSelectable","role":"symbol","url":"\/documentation\/smiclientcore\/messageselectable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageSelectable"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageChoices":{"navigatorTitle":[{"kind":"identifier","text":"MessageChoices"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageChoices"}],"role":"symbol","url":"\/documentation\/smiclientcore\/messagechoices","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a message with available choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"title":"MessageChoices"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply","url":"\/documentation\/smiclientcore\/quickreply","type":"topic","role":"symbol","navigatorTitle":[{"text":"QuickReply","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QuickReply","kind":"identifier"}],"kind":"symbol","title":"QuickReply","abstract":[{"type":"text","text":"A protocol that represents a quick reply within a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":"."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/QuickReply/text":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/smiclientcore\/quickreply\/text","abstract":[{"text":"The question text content of the quick reply.","type":"text"}],"type":"topic","kind":"symbol","required":true,"title":"text","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply\/text","navigatorTitle":[{"text":"text","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"title":"EntryTypeMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIQuickReply","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/QuickReply\/text"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIQuickReply","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"SMIEntryPayload","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIMessageSelectable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable","text":"SMIMessageSelectable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","text":"SMIEntryTypeMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIMessageChoices","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageChoices","text":"SMIMessageChoices","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIEntryPayload","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments"},{"value":[{"text":"SMIEntryPayload","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle"},{"value":"SMIMessageSelectable","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/title"},{"value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/fragments"},{"value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/navigatorTitle"},{"value":"SMIMessageChoices","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/title"},{"value":[{"kind":"identifier","text":"SMIMessageChoices"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/fragments"},{"value":[{"kind":"identifier","text":"SMIMessageChoices"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageChoices\/navigatorTitle"},{"value":"SMIQuickReply","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/title"},{"value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/fragments"},{"value":[{"kind":"identifier","text":"SMIQuickReply"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply\/navigatorTitle"},{"value":"text","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply~1text\/title"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1QuickReply~1text\/fragments"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMIEntryTypeMessage","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title"},{"value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments"},{"value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle"}]}]}