{"metadata":{"roleHeading":"Structure","externalID":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","title":"RealtimeConnectionState","symbolKind":"struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}]},"abstract":[{"text":"An enum that defines the possible states of the realtime event connection.","type":"text"}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/closed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/connecting","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/open"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/Equatable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"Possible-Values","type":"heading","text":"Possible Values"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/closed","type":"reference"},{"text":" - The realtime event connection is closed and not receiving events","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/open"},{"text":" - The realtime event connection is open and receiving events","type":"text"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/connecting","type":"reference"},{"type":"text","text":" - The realtime event connection is in the process of establishing"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Use this enum to determine the current state of the realtime event connection.","type":"text"},{"text":" ","type":"text"},{"text":"The state indicates whether the connection is established, in progress,","type":"text"},{"text":" ","type":"text"},{"text":"or closed.","type":"text"}]}],"kind":"content"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/realtimeconnectionstate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/equatable-implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/connecting":{"title":"connecting","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/connecting","kind":"symbol","navigatorTitle":[{"text":"SMIRealtimeConnectionStateConnecting","kind":"identifier"}],"abstract":[{"text":"The realtime event connection is in the process of establishing.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the connection to the realtime event service is being established. Events will not be received until the connection transitions to the open state.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RealtimeConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/connecting"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/init(rawValue:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/open":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/open","type":"topic","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/open","abstract":[{"text":"The realtime event connection is open and receiving events.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the connection to the realtime event service","type":"text"},{"text":" ","type":"text"},{"text":"is fully established and events are being received.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"open"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","kind":"typeIdentifier","text":"RealtimeConnectionState"}],"title":"open","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIRealtimeConnectionStateOpen"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of the realtime event connection."}],"role":"symbol","title":"RealtimeConnectionState","kind":"symbol","navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState/closed":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState\/closed","navigatorTitle":[{"kind":"identifier","text":"SMIRealtimeConnectionStateClosed"}],"type":"topic","abstract":[{"type":"text","text":"The realtime event connection is closed and not receiving events."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the connection to the realtime event service"},{"type":"text","text":" "},{"type":"text","text":"is closed and no events will be received until a new connection is established."}],"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/realtimeconnectionstate\/closed","title":"closed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"}]},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SMIRealtimeConnectionState"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRealtimeConnectionState"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIRealtimeConnectionState"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIRealtimeConnectionState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1connecting\/title","op":"replace","value":"SMIRealtimeConnectionStateConnecting"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1connecting\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRealtimeConnectionStateConnecting"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1open\/title","op":"replace","value":"SMIRealtimeConnectionStateOpen"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1open\/fragments","op":"replace","value":[{"text":"SMIRealtimeConnectionStateOpen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title","op":"replace","value":"SMIRealtimeConnectionState"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRealtimeConnectionState"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIRealtimeConnectionState"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1closed\/title","op":"replace","value":"SMIRealtimeConnectionStateClosed"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState~1closed\/fragments","op":"replace","value":[{"text":"SMIRealtimeConnectionStateClosed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}