{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"typealias","externalID":"c:SMIRemoteConfiguration.h@T@SMIRemoteConfigurationCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfigurationCompletion","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"RemoteConfigurationCompletion","kind":"identifier"}],"roleHeading":"Type Alias","role":"symbol","title":"RemoteConfigurationCompletion"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfigurationCompletion","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfigurationcompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfigurationcompletion"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"type":"text","text":"A completion block that returns the remote configuration for an embedded service deployment."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfigurationCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIRemoteConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","text":"RemoteConfiguration","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The remote configuration matching your configured embedded service deployment.","type":"text"}]}],"name":"remoteConfiguration"},{"name":"error","content":[{"inlineContent":[{"text":"If the query results in an error, it is returned here.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An empty result is "},{"type":"strong","inlineContent":[{"type":"text","text":"NOT"}]},{"type":"text","text":" considered an error."}]}],"style":"note"}],"kind":"content"}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfigurationCompletion":{"kind":"symbol","type":"topic","title":"RemoteConfigurationCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfigurationCompletion","abstract":[{"type":"text","text":"A completion block that returns the remote configuration for an embedded service deployment."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RemoteConfigurationCompletion"}],"url":"\/documentation\/smiclientcore\/remoteconfigurationcompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfigurationCompletion"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}],"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/remoteconfiguration","title":"RemoteConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"RemoteConfiguration","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIRemoteConfigurationCompletion","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIRemoteConfigurationCompletion"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIRemoteConfigurationCompletion","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMIRemoteConfiguration#*$objc(cs)NSError)","text":"void (^)(id<SMIRemoteConfiguration>, NSError *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIRemoteConfigurationCompletion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIRemoteConfigurationCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfigurationCompletion\/title"},{"value":[{"kind":"identifier","text":"SMIRemoteConfigurationCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfigurationCompletion\/fragments"},{"value":[{"kind":"identifier","text":"SMIRemoteConfigurationCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfigurationCompletion\/navigatorTitle"},{"value":"SMIRemoteConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"}]}]}