{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfiguration","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol represents the complete configuration for an embedded service deployment,"},{"type":"text","text":" "},{"type":"text","text":"including pre-chat forms, choice lists, terms and conditions, and fallback messaging."},{"type":"text","text":" "},{"type":"text","text":"The configuration is typically retrieved from the server and used to customize the"},{"type":"text","text":" "},{"type":"text","text":"behavior and appearance of the embedded service."}]}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfiguration","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"symbolKind":"protocol","externalID":"c:objc(pl)SMIRemoteConfiguration","title":"RemoteConfiguration"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/choiceListConfiguration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/deploymentType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/fallbackMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/preChatConfiguration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/termsAndConditions","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/timestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/transcriptConfiguration"],"generated":true}],"abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/timestamp":{"abstract":[{"type":"text","text":"The timestamp when this configuration was last updated."},{"type":"text","text":" "},{"type":"text","text":"This value is used to track when the configuration was last modified on the server."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"timestamp","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/timestamp","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration\/timestamp"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/name":{"type":"topic","kind":"symbol","title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"required":true,"url":"\/documentation\/smiclientcore\/remoteconfiguration\/name","role":"symbol","abstract":[{"type":"text","text":"The name of this remote configuration."},{"type":"text","text":" "},{"type":"text","text":"This name identifies the specific configuration for this embedded service deployment."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/preChatConfiguration":{"required":true,"type":"topic","title":"preChatConfiguration","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/preChatConfiguration","url":"\/documentation\/smiclientcore\/remoteconfiguration\/prechatconfiguration","abstract":[{"text":"The list of pre-chat configurations available for this deployment.","type":"text"},{"text":" ","type":"text"},{"text":"Each configuration defines a set of fields that can be displayed in the pre-chat form.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatConfiguration"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatConfiguration","text":"PreChatConfiguration"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"preChatConfiguration"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/deploymentType":{"required":true,"type":"topic","title":"deploymentType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deploymentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"deploymentType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/deploymentType","abstract":[{"text":"The deployment type of the remote configuration.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates the type of deployment this configuration is associated with.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/remoteconfiguration\/deploymenttype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/transcriptConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"transcriptConfiguration"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/transcriptConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transcriptConfiguration"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMITranscriptConfiguration","kind":"typeIdentifier","text":"TranscriptConfiguration"}],"abstract":[{"text":"The transcription configuration.","type":"text"}],"title":"transcriptConfiguration","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration\/transcriptconfiguration","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/termsAndConditions":{"url":"\/documentation\/smiclientcore\/remoteconfiguration\/termsandconditions","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/termsAndConditions","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"termsAndConditions","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMITermsAndConditions","text":"TermsAndConditions","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The terms and conditions that users must accept."},{"type":"text","text":" "},{"type":"text","text":"This object defines the terms and conditions text and acceptance requirements."}],"navigatorTitle":[{"text":"termsAndConditions","kind":"identifier"}],"title":"termsAndConditions"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/choiceListConfiguration":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceListConfiguration","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIChoiceListConfiguration","text":"ChoiceListConfiguration","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"choiceListConfiguration","kind":"identifier"}],"required":true,"title":"choiceListConfiguration","url":"\/documentation\/smiclientcore\/remoteconfiguration\/choicelistconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/choiceListConfiguration","kind":"symbol","abstract":[{"type":"text","text":"The configuration for choice lists used in pre-chat forms."},{"type":"text","text":" "},{"type":"text","text":"This object defines the available options and their relationships for choice list fields."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/fallbackMessage":{"title":"fallbackMessage","abstract":[{"type":"text","text":"The fallback message configuration."},{"type":"text","text":" "},{"type":"text","text":"This object defines the message to display when the service is unavailable."}],"type":"topic","required":true,"url":"\/documentation\/smiclientcore\/remoteconfiguration\/fallbackmessage","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fallbackMessage","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFallbackMessage","text":"FallbackMessage","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"fallbackMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/fallbackMessage"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIRemoteConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/choiceListConfiguration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/deploymentType","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/fallbackMessage","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/name","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/preChatConfiguration","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/termsAndConditions","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/timestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/transcriptConfiguration"],"anchor":"Instance-Properties","title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIRemoteConfiguration"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"timestamp","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1timestamp\/title","op":"replace"},{"value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1timestamp\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1name\/title","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1name\/fragments","op":"replace"},{"value":"preChatConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1preChatConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"preChatConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1preChatConfiguration\/fragments","op":"replace"},{"value":"deploymentType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1deploymentType\/title","op":"replace"},{"value":[{"text":"deploymentType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1deploymentType\/fragments","op":"replace"},{"value":"transcriptConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1transcriptConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"transcriptConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1transcriptConfiguration\/fragments","op":"replace"},{"value":"termsAndConditions","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1termsAndConditions\/title","op":"replace"},{"value":[{"text":"termsAndConditions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1termsAndConditions\/fragments","op":"replace"},{"value":"SMIRemoteConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","op":"replace"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","op":"replace"},{"value":"choiceListConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1choiceListConfiguration\/title","op":"replace"},{"value":[{"text":"choiceListConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1choiceListConfiguration\/fragments","op":"replace"},{"value":"fallbackMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1fallbackMessage\/title","op":"replace"},{"value":[{"text":"fallbackMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1fallbackMessage\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}