{"abstract":[{"text":"An enum that defines the possible types of routing work operations that can occur in a conversation.","type":"text"}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"kind":"symbol","metadata":{"externalID":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"role":"symbol","title":"RoutingWorkTypes","symbolKind":"struct","roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingworktypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/routingworktypes"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"This enum is used to categorize different types of routing work operations that can occur in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a specific routing work action that has been performed."}],"type":"paragraph"},{"level":2,"anchor":"Possible-Values","text":"Possible Values","type":"heading"},{"items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/assigned","type":"reference","isActive":true},{"text":" - Indicates the action of assigning a routing work to an agent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/accepted","type":"reference","isActive":true},{"type":"text","text":" - Indicates the action of an agent accepting a routing work"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/closed","isActive":true,"type":"reference"},{"text":" - Indicates the action of closing a routing work","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/accepted","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/assigned","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/closed","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/escalated"],"anchor":"Type-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/Equatable-Implementations"],"anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/init(rawValue:)","url":"\/documentation\/smiclientcore\/routingworktypes\/init(rawvalue:)","abstract":[],"role":"symbol","title":"init(rawValue:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/closed":{"url":"\/documentation\/smiclientcore\/routingworktypes\/closed","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SMIRoutingWorkTypesClosed","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/closed","title":"closed","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","kind":"typeIdentifier"}],"abstract":[{"text":"Indicates the action of closing a routing work.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/accepted":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/accepted","role":"symbol","url":"\/documentation\/smiclientcore\/routingworktypes\/accepted","abstract":[{"type":"text","text":"Indicates the action of an agent accepting a routing work."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accepted"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","kind":"typeIdentifier","text":"RoutingWorkTypes"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIRoutingWorkTypesAccepted"}],"title":"accepted"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes","title":"RoutingWorkTypes","navigatorTitle":[{"text":"RoutingWorkTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of routing work operations that can occur in a conversation."}],"type":"topic","url":"\/documentation\/smiclientcore\/routingworktypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/Equatable-Implementations":{"type":"topic","url":"\/documentation\/smiclientcore\/routingworktypes\/equatable-implementations","title":"Equatable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/Equatable-Implementations","abstract":[]},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/assigned":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assigned","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingWorkTypes","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/routingworktypes\/assigned","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIRoutingWorkTypesAssigned","kind":"identifier"}],"abstract":[{"text":"Indicates the action of assigning a routing work to an agent.","type":"text"}],"title":"assigned","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/assigned"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkTypes/escalated":{"title":"escalated","abstract":[{"type":"text","text":"Indicates the action of escalating to a new agent."}],"url":"\/documentation\/smiclientcore\/routingworktypes\/escalated","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkTypes\/escalated","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"escalated"},{"kind":"text","text":": "},{"text":"RoutingWorkTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes"}],"navigatorTitle":[{"text":"SMIRoutingWorkTypesEscalated","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SMIRoutingWorkTypes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"value":[{"kind":"identifier","text":"SMIRoutingWorkTypes"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"SMIRoutingWorkTypes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1closed\/title","value":"SMIRoutingWorkTypesClosed"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1closed\/fragments","value":[{"text":"SMIRoutingWorkTypesClosed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1accepted\/title","value":"SMIRoutingWorkTypesAccepted"},{"value":[{"kind":"identifier","text":"SMIRoutingWorkTypesAccepted"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1accepted\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/title","op":"replace","value":"SMIRoutingWorkTypes"},{"op":"replace","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes\/navigatorTitle","value":[{"text":"SMIRoutingWorkTypes","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1assigned\/title","value":"SMIRoutingWorkTypesAssigned"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1assigned\/fragments","value":[{"kind":"identifier","text":"SMIRoutingWorkTypesAssigned"}]},{"op":"replace","value":"SMIRoutingWorkTypesEscalated","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1escalated\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRoutingWorkTypesEscalated"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkTypes~1escalated\/fragments"}]}]}