{"metadata":{"modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingWorkResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RoutingWorkResult"}],"role":"symbol","title":"RoutingWorkResult","externalID":"c:objc(pl)SMIRoutingWorkResult"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"A protocol that represents a routing work result within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":".","type":"text"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult\/workType"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoutingWorkResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","text":"EntryPayload"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Use this protocol to access the content of a routing work result displayed in a conversation."},{"type":"text","text":" "},{"type":"text","text":"A routing work result indicates the type of work that was performed during message routing."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"],"type":"inheritsFrom"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/routingworkresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/routingworkresult"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" object."}],"url":"\/documentation\/smiclientcore\/entrypayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"title":"EntryPayload"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkResult/workType":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"workType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingWorkTypes.h@T@SMIRoutingWorkTypes","text":"RoutingWorkTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult\/workType","url":"\/documentation\/smiclientcore\/routingworkresult\/worktype","abstract":[{"type":"text","text":"The type of work performed during routing."}],"kind":"symbol","type":"topic","title":"workType","navigatorTitle":[{"kind":"identifier","text":"workType"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingWorkResult":{"abstract":[{"text":"A protocol that represents a routing work result within a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult","navigatorTitle":[{"kind":"identifier","text":"RoutingWorkResult"}],"title":"RoutingWorkResult","url":"\/documentation\/smiclientcore\/routingworkresult","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoutingWorkResult"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIRoutingWorkResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIRoutingWorkResult","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIRoutingWorkResult"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingWorkResult\/workType"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIRoutingWorkResult","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","op":"replace","value":"SMIEntryPayload"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","op":"replace","value":"SMIConversationEntry"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult~1workType\/title","op":"replace","value":"workType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult~1workType\/fragments","op":"replace","value":[{"text":"workType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/title","op":"replace","value":"SMIRoutingWorkResult"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRoutingWorkResult"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingWorkResult\/navigatorTitle","op":"replace","value":[{"text":"SMIRoutingWorkResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}