{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoutingTypes"}],"navigatorTitle":[{"kind":"identifier","text":"RoutingTypes"}],"role":"symbol","externalID":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","modules":[{"name":"SMIClientCore"}],"title":"RoutingTypes","roleHeading":"Structure","symbolKind":"struct"},"variants":[{"paths":["\/documentation\/smiclientcore\/routingtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/routingtypes"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An enum that defines the possible types of routing operations that can occur in a conversation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoutingTypes"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to categorize different types of routing operations that can occur in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a specific routing action that has been performed."}]},{"type":"heading","level":2,"anchor":"Possible-Values","text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/initial"},{"type":"text","text":" - Indicates the action of initializing a new routing operation"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/transfer","isActive":true},{"text":" - Indicates the action of transferring the conversation to a different agent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/conference"},{"type":"text","text":" - Indicates the action of adding a new participant to a conference"}]}]}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/conference","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/initial","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/transfer"],"anchor":"Type-Properties","title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes":{"url":"\/documentation\/smiclientcore\/routingtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes","abstract":[{"text":"An enum that defines the possible types of routing operations that can occur in a conversation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RoutingTypes","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoutingTypes","kind":"identifier"}],"type":"topic","title":"RoutingTypes"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/Equatable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/smiclientcore\/routingtypes\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/initial":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","kind":"typeIdentifier","text":"RoutingTypes"}],"url":"\/documentation\/smiclientcore\/routingtypes\/initial","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIRoutingTypesInitial"}],"abstract":[{"type":"text","text":"Indicates the action of initializing a new routing operation."}],"title":"initial","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/initial"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/routingtypes\/init(rawvalue:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/init(rawValue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/conference":{"url":"\/documentation\/smiclientcore\/routingtypes\/conference","abstract":[{"text":"Indicates the action of adding a new participant to a conference.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/conference","role":"symbol","navigatorTitle":[{"text":"SMIRoutingTypesConference","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"conference","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingTypes","preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes","kind":"typeIdentifier"}],"type":"topic","title":"conference"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RoutingTypes/transfer":{"url":"\/documentation\/smiclientcore\/routingtypes\/transfer","abstract":[{"type":"text","text":"Indicates the action of transferring the conversation to a different agent."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RoutingTypes\/transfer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIRoutingTypesTransfer"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transfer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RoutingTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIRoutingTypes.h@T@SMIRoutingTypes"}],"type":"topic","title":"transfer"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIRoutingTypes","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRoutingTypes"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIRoutingTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIRoutingTypes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/title","value":"SMIRoutingTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/fragments","value":[{"text":"SMIRoutingTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRoutingTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1initial\/title","value":"SMIRoutingTypesInitial"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1initial\/fragments","value":[{"text":"SMIRoutingTypesInitial","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1conference\/title","value":"SMIRoutingTypesConference"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1conference\/fragments","value":[{"text":"SMIRoutingTypesConference","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1transfer\/title","value":"SMIRoutingTypesTransfer"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RoutingTypes~1transfer\/fragments","value":[{"text":"SMIRoutingTypesTransfer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}