{"sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionTitle"]}],"metadata":{"symbolKind":"protocol","externalID":"c:objc(pl)SMIFormSelectedOption","title":"SelectedOption","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectedOption"}],"navigatorTitle":[{"kind":"identifier","text":"SelectedOption"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},"abstract":[{"text":"A protocol that defines a selected option in a multi-option form input.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelectedOption"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Use this protocol to represent a selected option in forms that support multiple selections,","type":"text"},{"text":" ","type":"text"},{"text":"such as option pickers or select inputs. Each selected option combines a unique identifier","type":"text"},{"text":" ","type":"text"},{"text":"with a title item that provides visual representation.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/selectedoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/selectedoption"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SelectedOption","kind":"identifier"}],"title":"SelectedOption","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelectedOption","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a selected option in a multi-option form input."}],"url":"\/documentation\/smiclientcore\/selectedoption","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption/optionIdentifier":{"abstract":[{"text":"The unique identifier for this selected option.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides a stable identifier that can be used to track the selection state","type":"text"},{"text":" ","type":"text"},{"text":"and associate the option with other form components or data.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"optionIdentifier"}],"role":"symbol","title":"optionIdentifier","type":"topic","url":"\/documentation\/smiclientcore\/selectedoption\/optionidentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionIdentifier","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SelectedOption/optionTitle":{"title":"optionTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionTitle","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"optionTitle","kind":"identifier"}],"abstract":[{"text":"The title of this selected option.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the visual representation of the selected option, including its","type":"text"},{"text":" ","type":"text"},{"text":"text content and any associated styling or formatting.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/selectedoption\/optiontitle","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionTitle"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormSelectedOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormSelectedOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormSelectedOption"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SelectedOption\/optionTitle"],"anchor":"Instance-Properties","title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormSelectedOption"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/title","value":"SMIFormSelectedOption"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/fragments","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption\/navigatorTitle","value":[{"text":"SMIFormSelectedOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionIdentifier\/title","value":"optionIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionIdentifier\/fragments","value":[{"kind":"identifier","text":"optionIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionTitle\/title","value":"optionTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SelectedOption~1optionTitle\/fragments","value":[{"kind":"identifier","text":"optionTitle"}]}]}]}