{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Serializable"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"Serializable","kind":"identifier"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"SMIClientCore"}],"title":"Serializable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"externalID":"c:objc(cs)SMISerializable"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"sections":[],"abstract":[{"type":"text","text":"Base class for JSON serializable objects used with network communication for In-App Messaging."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"},"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/smiclientcore\/serializable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/serializable"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContext"}],"abstract":[{"text":"This class serves as the base implementation for all session context types.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","title":"AbstractSessionContext","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AbstractSessionContext"}],"url":"\/documentation\/smiclientcore\/abstractsessioncontext","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContext":{"abstract":[{"text":"Concrete implementation of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol","isActive":true,"type":"reference"},{"text":" protocol.","type":"text"}],"type":"topic","title":"SessionContext","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SessionContext"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext","url":"\/documentation\/smiclientcore\/sessioncontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContext"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol":{"role":"symbol","title":"SessionContextProtocol","url":"\/documentation\/smiclientcore\/sessioncontextprotocol","abstract":[{"type":"text","text":"Represents a session context item that contains an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol","navigatorTitle":[{"text":"SessionContextProtocol","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValueProtocol"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","url":"\/documentation\/smiclientcore\/namedvalueprotocol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Represents a named value variable item with a name and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"},{"type":"text","text":"."}],"title":"NamedValueProtocol","navigatorTitle":[{"kind":"identifier","text":"NamedValueProtocol"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue":{"type":"topic","title":"StructuredValue","abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/structuredvalue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValue","kind":"identifier"}],"navigatorTitle":[{"text":"StructuredValue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValue":{"url":"\/documentation\/smiclientcore\/namedvalue","abstract":[{"type":"text","text":"Concrete implementation of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","type":"reference","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NamedValue"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValue"}],"title":"NamedValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol":{"abstract":[{"type":"text","text":"A structured value that contains a dictionary of key-value pairs."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","type":"topic","navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/structuredvalueprotocol","title":"StructuredValueProtocol","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Serializable":{"navigatorTitle":[{"text":"Serializable","kind":"identifier"}],"abstract":[{"text":"Base class for JSON serializable objects used with network communication for In-App Messaging.","type":"text"}],"type":"topic","kind":"symbol","title":"Serializable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","url":"\/documentation\/smiclientcore\/serializable","role":"symbol"},"doc://com.salesforce.SMIClientCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValue":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue","title":"AbstractValue","abstract":[{"text":"Concrete implementation of SMIAbstractValue protocol.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/abstractvalue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValue","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SMISerializable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMISerializable"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMISerializable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"],"type":"inheritedBy","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMISerializable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/title","value":"SMIAbstractSessionContext","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/fragments","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/title","value":"SMISessionContext","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/fragments","value":[{"kind":"identifier","text":"SMISessionContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/title","value":"SMISessionContext","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/fragments","value":[{"text":"SMISessionContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/navigatorTitle","value":[{"text":"SMISessionContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title","value":"SMINamedValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments","value":[{"kind":"identifier","text":"SMINamedValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/title","value":"SMIStructuredValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/fragments","value":[{"kind":"identifier","text":"SMIStructuredValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/navigatorTitle","value":[{"text":"SMIStructuredValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/title","value":"SMINamedValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/fragments","value":[{"kind":"identifier","text":"SMINamedValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMINamedValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/title","value":"SMIStructuredValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/fragments","value":[{"text":"SMIStructuredValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStructuredValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/title","value":"SMISerializable","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/fragments","value":[{"text":"SMISerializable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/navigatorTitle","value":[{"kind":"identifier","text":"SMISerializable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/title","value":"SMIAbstractValue","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/fragments","value":[{"text":"SMIAbstractValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValue\/navigatorTitle","value":[{"text":"SMIAbstractValue","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}