{"kind":"symbol","abstract":[{"type":"text","text":"Concrete implementation of SMISessionContextSet protocol."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"},"metadata":{"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(cs)SMISessionContextSet","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSet"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SessionContextSet"}],"symbolKind":"class","title":"SessionContextSet"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"]}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet\/init(contextVariables:)"],"generated":true}],"variants":[{"paths":["\/documentation\/smiclientcore\/sessioncontextset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessioncontextset"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSet","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This class represents a collection of named context variables that form a session context set.","type":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContext":{"title":"AbstractSessionContext","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This class serves as the base implementation for all session context types."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContext","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractSessionContext","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","url":"\/documentation\/smiclientcore\/abstractsessioncontext"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol":{"title":"SessionContextSetProtocol","kind":"symbol","abstract":[{"text":"Represents a session context item with a name and value.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSetProtocol","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SessionContextSetProtocol","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet":{"navigatorTitle":[{"text":"SessionContextSet","kind":"identifier"}],"type":"topic","abstract":[{"text":"Concrete implementation of SMISessionContextSet protocol.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContextSet","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet","url":"\/documentation\/smiclientcore\/sessioncontextset","title":"SessionContextSet"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"title":"AbstractSessionContextProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet/init(contextVariables:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithContextVariables:"}],"abstract":[{"text":"Initializes a new session context set with the provided context variables.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet\/init(contextVariables:)","role":"symbol","type":"topic","title":"init(contextVariables:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contextVariables"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMINamedValue","text":"NamedValueProtocol"},{"kind":"text","text":"])"}],"url":"\/documentation\/smiclientcore\/sessioncontextset\/init(contextvariables:)"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"abstract":[{"type":"text","text":"Represents a named value variable item with a name and "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","type":"topic","title":"NamedValueProtocol","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValueProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"NamedValueProtocol"}],"url":"\/documentation\/smiclientcore\/namedvalueprotocol"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP"},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValue":{"navigatorTitle":[{"text":"NamedValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue","title":"NamedValue","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NamedValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/namedvalue","kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SMISessionContextSet"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMISessionContextSet"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet\/init(contextVariables:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol"],"type":"conformsTo","kind":"relationships"}],"op":"replace"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValue"],"anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMISessionContextSet"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContext","preciseIdentifier":"c:objc(cs)SMIAbstractSessionContext","text":"SMIAbstractSessionContext"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIAbstractSessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/title"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/fragments"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContext\/navigatorTitle"},{"value":"SMISessionContextSet","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/title"},{"value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/fragments"},{"value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/title","value":"SMISessionContextSet"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/fragments","value":[{"text":"SMISessionContextSet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionContextSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title","value":"SMIAbstractSessionContext"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet~1init(contextVariables:)\/title","value":"initWithContextVariables:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet~1init(contextVariables:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithContextVariables:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title","value":"SMINamedValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments","value":[{"kind":"identifier","text":"SMINamedValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMINamedValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/title","value":"SMINamedValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/fragments","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMINamedValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}