{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to track the current state of a session. Each status represents"},{"type":"text","text":" "},{"type":"text","text":"a different stage in the session’s lifecycle."}]},{"text":"Possible Values","level":2,"type":"heading","anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/unknown","isActive":true},{"type":"text","text":" - Indicates an unknown or unspecified session state"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/active"},{"text":" - Indicates a session that’s currently active","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/inactive"},{"type":"text","text":" - Indicates a session that’s currently inactive"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/ended","isActive":true},{"type":"text","text":" - Indicates a session that has been ended"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/waiting","type":"reference","isActive":true},{"type":"text","text":" - Indicates a session that’s waiting for a response or action"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/new","type":"reference"},{"type":"text","text":" - Indicates a newly created session"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/error","isActive":true,"type":"reference"},{"text":" - Indicates a session that has encountered an error","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/consent","isActive":true,"type":"reference"},{"type":"text","text":" - Indicates a session that requires user consent"}],"type":"paragraph"}]}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatus"]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"SessionStatus","kind":"identifier"}],"role":"symbol","title":"SessionStatus","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"externalID":"c:SMISessionStatus.h@T@SMISessionStatus","roleHeading":"Structure","modules":[{"name":"SMIClientCore"}],"symbolKind":"struct"},"abstract":[{"text":"An enum that defines the possible states of a session.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/active","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/consent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/ended","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/error","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/inactive","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/new","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/unknown","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/waiting"],"generated":true,"anchor":"Type-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/Equatable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/unknown":{"url":"\/documentation\/smiclientcore\/sessionstatus\/unknown","role":"symbol","navigatorTitle":[{"text":"SMISessionStatusUnknown","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/unknown","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"title":"unknown","abstract":[{"type":"text","text":"Unknown session status."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session’s state cannot be determined."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/active":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"}],"kind":"symbol","role":"symbol","title":"active","url":"\/documentation\/smiclientcore\/sessionstatus\/active","abstract":[{"type":"text","text":"Session is currently active."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session is active and can handle interactions."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/active","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusActive"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/inactive":{"navigatorTitle":[{"text":"SMISessionStatusInactive","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/sessionstatus\/inactive","abstract":[{"type":"text","text":"Session is currently inactive."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session is inactive but not ended."}],"title":"inactive","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/inactive","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/init(rawValue:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/smiclientcore\/sessionstatus\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/init(rawValue:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/smiclientcore\/sessionstatus\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/Equatable-Implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/waiting":{"abstract":[{"text":"Session is waiting.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session is waiting for a response or action.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/sessionstatus\/waiting","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/waiting","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiting","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMISessionStatusWaiting","kind":"identifier"}],"title":"waiting"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/error":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/error","title":"error","abstract":[{"type":"text","text":"Session has an error."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session has encountered an error state."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMISessionStatusError","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/sessionstatus\/error"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"type":"topic","navigatorTitle":[{"text":"SessionStatus","kind":"identifier"}],"title":"SessionStatus","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatus","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/sessionstatus","kind":"symbol","abstract":[{"text":"An enum that defines the possible states of a session.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","role":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/ended":{"url":"\/documentation\/smiclientcore\/sessionstatus\/ended","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ended"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier","text":"SessionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SMISessionStatusEnded"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/ended","abstract":[{"type":"text","text":"Session has ended."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session has been terminated."}],"role":"symbol","title":"ended","kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/consent":{"url":"\/documentation\/smiclientcore\/sessionstatus\/consent","kind":"symbol","title":"consent","navigatorTitle":[{"text":"SMISessionStatusConsent","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Session requires consent."},{"type":"text","text":" "},{"type":"text","text":"This value indicates that the session requires user consent to proceed."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/consent"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus/new":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"new","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus\/new","title":"new","navigatorTitle":[{"text":"SMISessionStatusNew","kind":"identifier"}],"abstract":[{"text":"Session is new.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates that the session has just been created.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/sessionstatus\/new"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMISessionStatus","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMISessionStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMISessionStatus"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMISessionStatusUnknown","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1unknown\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusUnknown"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1unknown\/fragments"},{"op":"replace","value":"SMISessionStatusActive","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1active\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusActive"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1active\/fragments"},{"op":"replace","value":"SMISessionStatusInactive","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1inactive\/title"},{"op":"replace","value":[{"text":"SMISessionStatusInactive","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1inactive\/fragments"},{"op":"replace","value":"SMISessionStatusWaiting","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1waiting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusWaiting"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1waiting\/fragments"},{"op":"replace","value":"SMISessionStatusError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1error\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusError"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1error\/fragments"},{"op":"replace","value":"SMISessionStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle"},{"op":"replace","value":"SMISessionStatusEnded","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1ended\/title"},{"op":"replace","value":[{"text":"SMISessionStatusEnded","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1ended\/fragments"},{"op":"replace","value":"SMISessionStatusConsent","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1consent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusConsent"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1consent\/fragments"},{"op":"replace","value":"SMISessionStatusNew","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1new\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusNew"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus~1new\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}