{"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/channelAddressIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndedByRole","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStartTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatus","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatusPrev"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"abstract":[{"text":"A protocol that represents a session status change event within a conversation.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatusChanged","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"EntryPayload","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access information about session status changes in a conversation,"},{"type":"text","text":" "},{"type":"text","text":"such as when a session becomes active, inactive, or ends."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatuschanged"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatuschanged"]}],"kind":"symbol","metadata":{"title":"SessionStatusChanged","externalID":"c:objc(pl)SMISessionStatusChanged","symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionStatusChanged"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"SessionStatusChanged","kind":"identifier"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryPayload"}],"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"type":"text","text":"Common interface for the content of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" object."}],"kind":"symbol","type":"topic","title":"EntryPayload","navigatorTitle":[{"kind":"identifier","text":"EntryPayload"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/channelAddressIdentifier":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/channelAddressIdentifier","required":true,"abstract":[{"type":"text","text":"The channel address identifier for the session."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the channel through which the session is conducted."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"channelAddressIdentifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelAddressIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/channeladdressidentifier","title":"channelAddressIdentifier"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged":{"kind":"symbol","type":"topic","role":"symbol","title":"SessionStatusChanged","url":"\/documentation\/smiclientcore\/sessionstatuschanged","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatusChanged","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","abstract":[{"type":"text","text":"A protocol that represents a session status change event within a conversation."}],"navigatorTitle":[{"text":"SessionStatusChanged","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionStatusPrev":{"abstract":[{"type":"text","text":"The previous status of the session before the change."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatusPrev","role":"symbol","kind":"symbol","title":"sessionStatusPrev","required":true,"navigatorTitle":[{"text":"sessionStatusPrev","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstatusprev","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStatusPrev"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"},{"kind":"text","text":"?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionEndTime":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndTime","title":"sessionEndTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionEndTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"The end time of the session."},{"type":"text","text":" "},{"type":"text","text":"This property contains the date when the session ended, if applicable."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionendtime","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sessionEndTime"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionStartTime":{"abstract":[{"text":"The start time of the session.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the date when the session started.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionStartTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstarttime","type":"topic","role":"symbol","navigatorTitle":[{"text":"sessionStartTime","kind":"identifier"}],"title":"sessionStartTime","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStartTime"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionId":{"title":"sessionId","abstract":[{"type":"text","text":"The unique identifier for the session."},{"type":"text","text":" "},{"type":"text","text":"This property provides a stable way to identify and reference the session."}],"role":"symbol","required":true,"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionid","navigatorTitle":[{"kind":"identifier","text":"sessionId"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionId"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionStatus":{"abstract":[{"type":"text","text":"The current status of the session."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatus","navigatorTitle":[{"text":"sessionStatus","kind":"identifier"}],"role":"symbol","title":"sessionStatus","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstatus"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionEndedByRole":{"role":"symbol","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionendedbyrole","navigatorTitle":[{"text":"sessionEndedByRole","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndedByRole","required":true,"type":"topic","abstract":[{"type":"text","text":"The role of the participant that ended the session."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionEndedByRole","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"sessionEndedByRole"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMISessionStatusChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/channelAddressIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionEndedByRole","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStartTime","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatus","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatusPrev"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMISessionStatusChanged","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1channelAddressIdentifier\/title","value":"channelAddressIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1channelAddressIdentifier\/fragments","value":[{"text":"channelAddressIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/title","value":"SMISessionStatusChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/fragments","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/navigatorTitle","value":[{"text":"SMISessionStatusChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatusPrev\/title","value":"sessionStatusPrev"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatusPrev\/fragments","value":[{"text":"sessionStatusPrev","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionEndTime\/title","value":"sessionEndTime"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionEndTime\/fragments","value":[{"text":"sessionEndTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStartTime\/title","value":"sessionStartTime","op":"replace"},{"op":"replace","value":[{"text":"sessionStartTime","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStartTime\/fragments"},{"op":"replace","value":"sessionId","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionId\/title"},{"op":"replace","value":[{"text":"sessionId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionId\/fragments"},{"op":"replace","value":"sessionStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatus\/fragments"},{"op":"replace","value":"sessionEndedByRole","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionEndedByRole\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sessionEndedByRole"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionEndedByRole\/fragments"}]}]}