{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSetProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AbstractSessionContextProtocol","preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSetProtocol"}],"role":"symbol","roleHeading":"Protocol","title":"SessionContextSetProtocol","symbolKind":"protocol","externalID":"c:objc(pl)SMISessionContextSet","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"SessionContextSetProtocol"}]},"abstract":[{"type":"text","text":"Represents a session context item with a name and value."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"type":"conformingTypes","title":"Conforming Types"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol\/contextVariables"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/smiclientcore\/sessioncontextsetprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessioncontextsetprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol":{"url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol","navigatorTitle":[{"kind":"identifier","text":"SessionContextSetProtocol"}],"title":"SessionContextSetProtocol","kind":"symbol","role":"symbol","abstract":[{"text":"Represents a session context item with a name and value.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSetProtocol"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"navigatorTitle":[{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"title":"AbstractSessionContextProtocol","abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSet"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextset","title":"SessionContextSet","navigatorTitle":[{"kind":"identifier","text":"SessionContextSet"}],"abstract":[{"text":"Concrete implementation of SMISessionContextSet protocol.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSetProtocol/contextVariables":{"abstract":[{"text":"Array of named context variables that make up this session context set.","type":"text"}],"url":"\/documentation\/smiclientcore\/sessioncontextsetprotocol\/contextvariables","navigatorTitle":[{"text":"contextVariables","kind":"identifier"}],"title":"contextVariables","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol\/contextVariables","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextVariables","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"NamedValueProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMINamedValue"},{"text":"]","kind":"text"}],"required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMISessionContextSet","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSetProtocol\/contextVariables"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMISessionContextSet"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","kind":"typeIdentifier","text":"SMIAbstractSessionContext"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SMISessionContextSet","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/title"},{"value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/fragments"},{"value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol\/navigatorTitle"},{"value":"SMIAbstractSessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title"},{"value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle"},{"value":"SMISessionContextSet","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/title"},{"value":[{"kind":"identifier","text":"SMISessionContextSet"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/fragments"},{"value":[{"text":"SMISessionContextSet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/navigatorTitle"},{"value":"contextVariables","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol~1contextVariables\/title"},{"value":[{"text":"contextVariables","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSetProtocol~1contextVariables\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}