{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SingleConversationQueryCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SMIConversation"},{"type":"text","text":" objects, based on the given UUID."}]}],"name":"conversation"},{"content":[{"inlineContent":[{"text":"If the query results in an error, it is returned here. An empty result is not considered an error.","type":"text"}],"type":"paragraph"}],"name":"error"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/singleconversationquerycompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/singleconversationquerycompletion"]}],"abstract":[{"type":"text","text":"The completion block for returning all conversations stored in the database."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SingleConversationQueryCompletion"},"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"SingleConversationQueryCompletion","role":"symbol","navigatorTitle":[{"text":"SingleConversationQueryCompletion","kind":"identifier"}],"symbolKind":"typealias","roleHeading":"Type Alias","externalID":"c:SMIQueryCompletions.h@T@SMISingleConversationQueryCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SingleConversationQueryCompletion","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a conversation between participants."}],"title":"Conversation","url":"\/documentation\/smiclientcore\/conversation","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SingleConversationQueryCompletion":{"abstract":[{"text":"The completion block for returning all conversations stored in the database.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConversationQueryCompletion"}],"url":"\/documentation\/smiclientcore\/singleconversationquerycompletion","navigatorTitle":[{"kind":"identifier","text":"SingleConversationQueryCompletion"}],"kind":"symbol","type":"topic","role":"symbol","title":"SingleConversationQueryCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SingleConversationQueryCompletion"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SMISingleConversationQueryCompletion"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISingleConversationQueryCompletion"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMISingleConversationQueryCompletion"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMIConversation#*$objc(cs)NSError)","text":"void (^)(id<SMIConversation>, NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMISingleConversationQueryCompletion","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace","value":"SMIConversation"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace","value":[{"text":"SMIConversation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleConversationQueryCompletion\/title","op":"replace","value":"SMISingleConversationQueryCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleConversationQueryCompletion\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMISingleConversationQueryCompletion"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleConversationQueryCompletion\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMISingleConversationQueryCompletion"}]}]}]}