{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SingleEntryQueryCompletion","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Completion block for queries returning "},{"type":"codeVoice","code":"SMIConversationEntry"},{"type":"text","text":" object."}],"variants":[{"paths":["\/documentation\/smiclientcore\/singleentryquerycompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/singleentryquerycompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SingleEntryQueryCompletion","kind":"identifier"}],"roleHeading":"Type Alias","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SingleEntryQueryCompletion"}],"externalID":"c:SMIQueryCompletions.h@T@SMISingleEntryQueryCompletion","modules":[{"name":"SMIClientCore"}],"symbolKind":"typealias","title":"SingleEntryQueryCompletion"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SingleEntryQueryCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" result, ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no results are found.","type":"text"}]}]},{"name":"conversation","content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"SMIConversation"},{"type":"text","text":" object associated with all returned entries."}]}]},{"name":"error","content":[{"inlineContent":[{"text":"If the query results in an error, it is returned here. An empty result is not considered an error.","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SingleEntryQueryCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SingleEntryQueryCompletion","kind":"symbol","url":"\/documentation\/smiclientcore\/singleentryquerycompletion","title":"SingleEntryQueryCompletion","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleEntryQueryCompletion"}],"abstract":[{"text":"Completion block for queries returning ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":" object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SingleEntryQueryCompletion"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMISingleEntryQueryCompletion","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMISingleEntryQueryCompletion"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMISingleEntryQueryCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMIConversationEntry#*Qoobjc(pl)SMIConversation#*$objc(cs)NSError)","text":"void (^)(id<SMIConversationEntry>, id<SMIConversation>, NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMISingleEntryQueryCompletion","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIConversation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","value":[{"kind":"identifier","text":"SMIConversation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleEntryQueryCompletion\/title","value":"SMISingleEntryQueryCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleEntryQueryCompletion\/fragments","value":[{"text":"SMISingleEntryQueryCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SingleEntryQueryCompletion\/navigatorTitle","value":[{"text":"SMISingleEntryQueryCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"}]}]}