{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/preChat"],"anchor":"Type-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/Equatable-Implementations"],"anchor":"Default-Implementations","generated":true}],"metadata":{"roleHeading":"Structure","navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"SMIPreChatConfigurationFormTypes","role":"symbol","symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"externalID":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"This type represents the different kinds of pre-chat forms that can be configured."},{"type":"text","text":" "},{"type":"text","text":"Each form type determines how the pre-chat form is presented and behaves."}],"type":"paragraph"},{"anchor":"Possible-Values","type":"heading","text":"Possible Values","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/preChat"},{"text":" - The standard pre-chat form type.","type":"text"}],"type":"paragraph"}]}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"A type that defines the available form types for pre-chat configurations."}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/smiprechatconfigurationformtypes"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/equatable-implementations","type":"topic","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/preChat":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/preChat","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/prechat","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypesPreChat"}],"title":"preChat","abstract":[{"text":"The standard pre-chat form type.","type":"text"},{"text":" ","type":"text"},{"text":"This form type is used for collecting user information before starting a chat session.","type":"text"},{"text":" ","type":"text"},{"text":"The form includes visible fields that users can fill out and hidden fields that can","type":"text"},{"text":" ","type":"text"},{"text":"be set programmatically.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIPreChatConfigurationFormTypes.h@T@SMIPreChatConfigurationFormTypes","kind":"typeIdentifier","text":"SMIPreChatConfigurationFormTypes"}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes/init(rawValue:)":{"role":"symbol","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIPreChatConfigurationFormTypes":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"navigatorTitle":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that defines the available form types for pre-chat configurations."}],"type":"topic","title":"SMIPreChatConfigurationFormTypes","url":"\/documentation\/smiclientcore\/smiprechatconfigurationformtypes","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIPreChatConfigurationFormTypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/SY":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIPreChatConfigurationFormTypes","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes~1preChat\/title","op":"replace","value":"SMIPreChatConfigurationFormTypesPreChat"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes~1preChat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypesPreChat"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/title","op":"replace","value":"SMIPreChatConfigurationFormTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/fragments","op":"replace","value":[{"text":"SMIPreChatConfigurationFormTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIPreChatConfigurationFormTypes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatConfigurationFormTypes"}]}]}]}