{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorCode","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorMessages"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/staticerrordetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/staticerrordetails"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"sections":[],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorDetails","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:objc(pl)SMIStaticErrorDetails","modules":[{"name":"SMIClientCore"}],"title":"StaticErrorDetails","symbolKind":"protocol","navigatorTitle":[{"text":"StaticErrorDetails","kind":"identifier"}]},"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Static LightningType messages with Agentforce."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StaticErrorDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"aside","content":[{"inlineContent":[{"text":"All properties and features which are exposed in this class are subject to change.","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Experimental features\/APIs may be removed without advanced notification at any time."},{"type":"text","text":" "},{"type":"text","text":"Any use of these features will "},{"type":"strong","inlineContent":[{"text":"NOT","type":"text"}]},{"type":"text","text":" be offered any official support, until such time as they may be adopted as full and stable features."}]}],"style":"warning","name":"Warning"}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails/errorMessages":{"url":"\/documentation\/smiclientcore\/staticerrordetails\/errormessages","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorMessages","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"errorMessages","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"errorMessages"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails/errorCode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/smiclientcore\/staticerrordetails\/errorcode","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorCode","title":"errorCode","abstract":[],"required":true,"navigatorTitle":[{"kind":"identifier","text":"errorCode"}],"role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StaticErrorDetails":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticErrorDetails"}],"url":"\/documentation\/smiclientcore\/staticerrordetails","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails","title":"StaticErrorDetails","abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Static LightningType messages with Agentforce.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StaticErrorDetails"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIStaticErrorDetails","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIStaticErrorDetails","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStaticErrorDetails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorCode","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StaticErrorDetails\/errorMessages"],"generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIStaticErrorDetails"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorMessages\/title","value":"errorMessages"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorMessages\/fragments","value":[{"text":"errorMessages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorCode\/title","value":"errorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails~1errorCode\/fragments","value":[{"text":"errorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/title","value":"SMIStaticErrorDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/fragments","value":[{"text":"SMIStaticErrorDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StaticErrorDetails\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStaticErrorDetails"}]}]}]}