{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtoken"]}],"metadata":{"title":"StreamingToken","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingToken","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"StreamingToken","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:objc(pl)SMIStreamingToken"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingToken"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","text":"EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Use this protocol to access individual tokens that make up a streamed content payload. This protocol"},{"type":"text","text":" "},{"type":"text","text":"extends "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"},{"type":"text","text":" to provide functionality for handling content that is being streamed"},{"type":"text","text":" "},{"type":"text","text":"in fragments. Each token represents a portion of the complete payload and includes information"},{"type":"text","text":" "},{"type":"text","text":"about its position in the sequence and when it was generated."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"A protocol that represents an individual token in a stream of content.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/sequenceNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/timestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/tokenType"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"role":"symbol","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","title":"StreamingTokenValidation","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","url":"\/documentation\/smiclientcore\/streamingtokentypes","abstract":[{"text":"An enum that defines the possible types of streaming tokens in a conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenTypes"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken/sequenceNumber":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sequenceNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"required":true,"abstract":[{"text":"The position of this token in the overall message sequence.","type":"text"},{"text":" ","type":"text"},{"text":"This property indicates the order in which this token should be processed relative to","type":"text"},{"text":" ","type":"text"},{"text":"other tokens in the stream. Lower sequence numbers should be processed before higher ones.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/sequenceNumber","title":"sequenceNumber","url":"\/documentation\/smiclientcore\/streamingtoken\/sequencenumber","type":"topic","navigatorTitle":[{"text":"sequenceNumber","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken/timestamp":{"role":"symbol","url":"\/documentation\/smiclientcore\/streamingtoken\/timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/timestamp","title":"timestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"The time at which this token was generated."},{"type":"text","text":" "},{"type":"text","text":"This property provides the timestamp when this specific token was created. Note that this"},{"type":"text","text":" "},{"type":"text","text":"timestamp may differ from the final conversation entry’s timestamp, as tokens are generated"},{"type":"text","text":" "},{"type":"text","text":"before the complete entry is assembled."}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken/tokenType":{"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StreamingTokenTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"url":"\/documentation\/smiclientcore\/streamingtoken\/tokentype","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/tokenType","navigatorTitle":[{"text":"tokenType","kind":"identifier"}],"title":"tokenType","abstract":[{"type":"text","text":"The type of streaming token."},{"type":"text","text":" "},{"type":"text","text":"This property indicates the type of token through the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","isActive":true},{"type":"text","text":" enum,"},{"type":"text","text":" "},{"type":"text","text":"which helps determine how the token should be processed and what kind of content it contains."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken":{"abstract":[{"type":"text","text":"A protocol that represents an individual token in a stream of content."}],"title":"StreamingToken","navigatorTitle":[{"text":"StreamingToken","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingToken","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/streamingtoken","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageStreamingToken":{"title":"MessageStreamingToken","navigatorTitle":[{"kind":"identifier","text":"MessageStreamingToken"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageStreamingToken"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/messagestreamingtoken","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an individual token in a streamed message."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIStreamingToken","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIStreamingToken","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingToken"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/sequenceNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/timestamp","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/tokenType"],"anchor":"Instance-Properties","title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageStreamingToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingToken","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIStreamingTokenValidation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle"},{"value":"SMIStreamingTokenTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle"},{"value":"sequenceNumber","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1sequenceNumber\/title"},{"value":[{"text":"sequenceNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1sequenceNumber\/fragments"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1timestamp\/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1timestamp\/fragments"},{"value":"tokenType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1tokenType\/title"},{"value":[{"text":"tokenType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1tokenType\/fragments"},{"value":"SMIEntryPayload","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments"},{"value":[{"kind":"identifier","text":"SMIEntryPayload"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"value":"SMIStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/title"},{"value":[{"text":"SMIStreamingToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/fragments"},{"value":[{"text":"SMIStreamingToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/navigatorTitle"},{"value":"SMIMessageStreamingToken","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/title"},{"value":[{"kind":"identifier","text":"SMIMessageStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/fragments"},{"value":[{"kind":"identifier","text":"SMIMessageStreamingToken"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageStreamingToken\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}