{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"],"kind":"relationships","type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenValidation"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","preciseIdentifier":"c:objc(pl)SMIStreamingToken","kind":"typeIdentifier","text":"StreamingToken"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access validation information for a streamed message. This protocol"},{"type":"text","text":" "},{"type":"text","text":"extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","isActive":true},{"type":"text","text":" to provide functionality for validating the content of"},{"type":"text","text":" "},{"type":"text","text":"streamed messages. It is used to indicate whether the content of a stream has been"},{"type":"text","text":" "},{"type":"text","text":"validated as acceptable by the backend LLM (Large Language Model)."}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/streamingtokenvalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/reason","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/turnId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid"],"generated":true,"anchor":"Instance-Properties"}],"metadata":{"navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}],"role":"symbol","title":"StreamingTokenValidation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Protocol","externalID":"c:objc(pl)SMIStreamingTokenValidation"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A protocol that represents a validation event for a streamed message."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/valid":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid","required":true,"navigatorTitle":[{"text":"valid","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The validation status of the composed token."},{"type":"text","text":" "},{"type":"text","text":"This property indicates whether the content of the stream has been validated as"},{"type":"text","text":" "},{"type":"text","text":"acceptable. When "},{"type":"codeVoice","code":"NO"},{"type":"text","text":", the content should be considered invalid and may be"},{"type":"text","text":" "},{"type":"text","text":"discarded or replaced."}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/valid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"valid"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/turnId":{"kind":"symbol","url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/turnid","role":"symbol","required":true,"type":"topic","abstract":[{"text":"The unique identifier for the current conversation turn.","type":"text"},{"text":" ","type":"text"},{"text":"This identifier correlates all events and responses within a single interaction between","type":"text"},{"text":" ","type":"text"},{"text":"the user and agent. Use this to track and group related messages and events that occur","type":"text"},{"text":" ","type":"text"},{"text":"within the same conversation turn.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/turnId","title":"turnId","navigatorTitle":[{"text":"turnId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ComposedStreamingToken":{"url":"\/documentation\/smiclientcore\/composedstreamingtoken","navigatorTitle":[{"text":"ComposedStreamingToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","title":"ComposedStreamingToken","type":"topic","kind":"symbol","abstract":[{"text":"A protocol that represents a conversation entry composed of multiple streaming tokens.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComposedStreamingToken","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/targetMessageIdentifier":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The identifier that will be used for the final transcribed entry."},{"type":"text","text":" "},{"type":"text","text":"This property provides a unique identifier that links this validation token to its"},{"type":"text","text":" "},{"type":"text","text":"corresponding "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ComposedStreamingToken","type":"reference","isActive":true},{"type":"text","text":", allowing the validation status to be"},{"type":"text","text":" "},{"type":"text","text":"associated with the correct message stream."}],"role":"symbol","url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/targetmessageidentifier","required":true,"title":"targetMessageIdentifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"targetMessageIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/targetMessageIdentifier","navigatorTitle":[{"text":"targetMessageIdentifier","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken":{"abstract":[{"type":"text","text":"A protocol that represents an individual token in a stream of content."}],"title":"StreamingToken","navigatorTitle":[{"text":"StreamingToken","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingToken","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/streamingtoken","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/batchNumber":{"abstract":[{"text":"The sequence number for related events within a turn.","type":"text"},{"text":" ","type":"text"},{"text":"Events with the same batch number are strongly associated and are delivered together.","type":"text"},{"text":" ","type":"text"},{"text":"Use this to identify and process groups of related events that should be handled","type":"text"},{"text":" ","type":"text"},{"text":"as a single unit within a conversation turn.","type":"text"}],"title":"batchNumber","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/batchNumber","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"batchNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"batchNumber"}],"url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/batchnumber","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation/reason":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"reason"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/reason","type":"topic","role":"symbol","required":true,"url":"\/documentation\/smiclientcore\/streamingtokenvalidation\/reason","abstract":[{"text":"The reason for invalidation, if applicable.","type":"text"},{"text":" ","type":"text"},{"text":"This optional property provides a detailed explanation of why the content was","type":"text"},{"text":" ","type":"text"},{"text":"considered invalid. Note that this property is intended for debugging and","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"traceability purposes only and should not be displayed to end users."}],"title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenValidation":{"role":"symbol","abstract":[{"text":"A protocol that represents a validation event for a streamed message.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenValidation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation","title":"StreamingTokenValidation","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/streamingtokenvalidation","navigatorTitle":[{"text":"StreamingTokenValidation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIStreamingTokenValidation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/batchNumber","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/reason","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/targetMessageIdentifier","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/turnId","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenValidation\/valid"],"title":"Instance Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStreamingTokenValidation","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIStreamingToken","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIStreamingToken"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/title","value":"valid"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1valid\/fragments","value":[{"text":"valid","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1turnId\/title","value":"turnId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1turnId\/fragments","value":[{"kind":"identifier","text":"turnId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/title","value":"SMIComposedStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/fragments","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ComposedStreamingToken\/navigatorTitle","value":[{"text":"SMIComposedStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1targetMessageIdentifier\/title","value":"targetMessageIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1targetMessageIdentifier\/fragments","value":[{"text":"targetMessageIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title","value":"SMIEntryPayload"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments","value":[{"kind":"identifier","text":"SMIEntryPayload"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle","value":[{"text":"SMIEntryPayload","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/title","value":"SMIStreamingToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/fragments","value":[{"text":"SMIStreamingToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/navigatorTitle","value":[{"kind":"identifier","text":"SMIStreamingToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1batchNumber\/title","value":"batchNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1batchNumber\/fragments","value":[{"kind":"identifier","text":"batchNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1reason\/title","value":"reason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation~1reason\/fragments","value":[{"text":"reason","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/title","value":"SMIStreamingTokenValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenValidation\/navigatorTitle","value":[{"text":"SMIStreamingTokenValidation","kind":"identifier"}]}]}]}