{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenTypes"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"Possible-Values","text":"Possible Values","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/message","isActive":true,"type":"reference"},{"text":" - Indicates the action of streaming a partial message content","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/validation","isActive":true},{"type":"text","text":" - Indicates the action of validating a batch of streamed tokens"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enum is used to categorize different types of streaming tokens that can appear in a conversation."},{"type":"text","text":" "},{"type":"text","text":"Each type represents a specific streaming token state that has been triggered."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/streamingtokentypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/streamingtokentypes"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"role":"symbol","roleHeading":"Structure","title":"StreamingTokenTypes","symbolKind":"struct","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"externalID":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/init(rawValue:)"]},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/message","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/validation"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/Equatable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"title":"StreamingTokenTypes","url":"\/documentation\/smiclientcore\/streamingtokentypes","abstract":[{"text":"An enum that defines the possible types of streaming tokens in a conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingTokenTypes"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/validation":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIStreamingTokenTypesValidation"}],"title":"validation","url":"\/documentation\/smiclientcore\/streamingtokentypes\/validation","abstract":[{"text":"Indicates the action of validating a batch of streamed tokens.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/validation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/message":{"kind":"symbol","title":"message","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/message","url":"\/documentation\/smiclientcore\/streamingtokentypes\/message","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Indicates the action of streaming a partial message content."}],"navigatorTitle":[{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/SY":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","title":"Swift.RawRepresentable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/Equatable-Implementations":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/smiclientcore\/streamingtokentypes\/equatable-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes/init(rawValue:)":{"url":"\/documentation\/smiclientcore\/streamingtokentypes\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes\/init(rawValue:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIStreamingTokenTypes","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIStreamingTokenTypes","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title","value":"SMIStreamingTokenTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments","value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle","value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1validation\/title","value":"SMIStreamingTokenTypesValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1validation\/fragments","value":[{"kind":"identifier","text":"SMIStreamingTokenTypesValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1message\/title","value":"SMIStreamingTokenTypesMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes~1message\/fragments","value":[{"text":"SMIStreamingTokenTypesMessage","kind":"identifier"}]}]}]}