{"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue\/init(value:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValue","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This class provides a structured value container that holds a dictionary of key-value pairs.","type":"text"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/structuredvalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/structuredvalue"]}],"metadata":{"title":"StructuredValue","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(cs)SMIStructuredValue","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StructuredValue"}],"navigatorTitle":[{"kind":"identifier","text":"StructuredValue"}],"symbolKind":"class","roleHeading":"Class"},"kind":"symbol","abstract":[{"text":"Concrete implementation of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","isActive":true,"type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Serializable":{"navigatorTitle":[{"text":"Serializable","kind":"identifier"}],"abstract":[{"text":"Base class for JSON serializable objects used with network communication for In-App Messaging.","type":"text"}],"type":"topic","kind":"symbol","title":"Serializable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","url":"\/documentation\/smiclientcore\/serializable","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue/init(value:)":{"abstract":[{"type":"text","text":"Initializes a new structured value with the provided dictionary."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"role":"symbol","title":"init(value:)","url":"\/documentation\/smiclientcore\/structuredvalue\/init(value:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue\/init(value:)"},"doc://com.salesforce.SMIClientCore/SQ":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol":{"abstract":[{"type":"text","text":"A structured value that contains a dictionary of key-value pairs."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","type":"topic","navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/structuredvalueprotocol","title":"StructuredValueProtocol","role":"symbol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue":{"type":"topic","title":"StructuredValue","abstract":[{"type":"text","text":"Concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/structuredvalue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValue","kind":"identifier"}],"navigatorTitle":[{"text":"StructuredValue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","type":"topic","abstract":[{"type":"text","text":"Protocol that defines the base type for session context values."}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","title":"AbstractValueProtocol","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP"},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SMIStructuredValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue\/init(value:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"],"title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStructuredValue","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SMISerializable","text":"SMISerializable","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"}],"languages":["occ"]}]}},{"value":"SMISerializable","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMISerializable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMISerializable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/navigatorTitle","op":"replace"},{"value":"initWithValue:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue~1init(value:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue~1init(value:)\/fragments","op":"replace"},{"value":"SMIStructuredValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStructuredValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIStructuredValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/navigatorTitle","op":"replace"},{"value":"SMIStructuredValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/title","op":"replace"},{"value":[{"text":"SMIStructuredValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStructuredValue"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/navigatorTitle","op":"replace"},{"value":"SMIAbstractValue","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","op":"replace"},{"value":[{"text":"SMIAbstractValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIAbstractValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","op":"replace"}]}]}