{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StructuredValueProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","text":"AbstractValueProtocol","preciseIdentifier":"c:objc(pl)SMIAbstractValue"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/structuredvalueprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/structuredvalueprotocol"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol"},"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"title":"StructuredValueProtocol","externalID":"c:objc(pl)SMIStructuredValue","role":"symbol","symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol\/value"],"generated":true,"title":"Instance Properties"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"A structured value that contains a dictionary of key-value pairs.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol":{"title":"StructuredValueProtocol","url":"\/documentation\/smiclientcore\/structuredvalueprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValueProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"StructuredValueProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","kind":"symbol","abstract":[{"type":"text","text":"A structured value that contains a dictionary of key-value pairs."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValueProtocol/value":{"required":true,"title":"value","type":"topic","abstract":[{"text":"Dictionary containing the structured value data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/structuredvalueprotocol\/value","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol\/value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"role":"symbol","title":"AbstractValueProtocol","abstract":[{"text":"Protocol that defines the base type for session context values.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StructuredValue":{"type":"topic","abstract":[{"text":"Concrete implementation of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/smiclientcore\/structuredvalue","navigatorTitle":[{"text":"StructuredValue","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StructuredValue","kind":"identifier"}],"role":"symbol","title":"StructuredValue","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SMIStructuredValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValueProtocol\/value"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"],"kind":"relationships"},{"title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StructuredValue"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIStructuredValue","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractValue","text":"SMIAbstractValue","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/title","op":"replace","value":"SMIStructuredValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMIStructuredValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValueProtocol~1value\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","op":"replace","value":"SMIAbstractValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","op":"replace","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIAbstractValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/title","op":"replace","value":"SMIStructuredValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StructuredValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIStructuredValue"}]}]}]}