{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TermsAndConditions"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsAndConditions"}],"externalID":"c:objc(pl)SMITermsAndConditions","modules":[{"name":"SMIClientCore"}],"title":"TermsAndConditions"},"abstract":[{"type":"text","text":"A protocol that defines the terms and conditions for the pre-chat form."}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/label"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TermsAndConditions","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"This protocol represents the terms and conditions that users must acknowledge","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"before starting a chat session. The terms can be displayed as formatted text"},{"type":"text","text":" "},{"type":"text","text":"and can be configured as required or optional."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/termsandconditions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/termsandconditions"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions/isRequired":{"abstract":[{"text":"Indicates whether users must accept the terms and conditions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When true, users must acknowledge the terms before proceeding with the chat."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isRequired","navigatorTitle":[{"text":"isRequired","kind":"identifier"}],"title":"isRequired","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRequired","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/termsandconditions\/isrequired"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions/label":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/label","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/termsandconditions\/label","abstract":[{"text":"The formatted text of the terms and conditions.","type":"text"},{"text":" ","type":"text"},{"text":"This text can include rich formatting and is displayed to users in the pre-chat form.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"title":"label"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions/isEnabled":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Indicates whether the terms and conditions are active."},{"type":"text","text":" "},{"type":"text","text":"When false, the terms and conditions are not displayed in the pre-chat form."}],"navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/termsandconditions\/isenabled","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isEnabled","title":"isEnabled"},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsAndConditions"}],"abstract":[{"type":"text","text":"A protocol that defines the terms and conditions for the pre-chat form."}],"navigatorTitle":[{"kind":"identifier","text":"TermsAndConditions"}],"url":"\/documentation\/smiclientcore\/termsandconditions","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions","title":"TermsAndConditions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMITermsAndConditions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMITermsAndConditions","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMITermsAndConditions"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isEnabled","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/isRequired","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions\/label"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMITermsAndConditions"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isRequired","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isRequired\/title"},{"value":[{"text":"isRequired","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isRequired\/fragments"},{"value":"label","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1label\/title"},{"value":[{"kind":"identifier","text":"label"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1label\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isEnabled\/title","value":"isEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions~1isEnabled\/fragments","value":[{"kind":"identifier","text":"isEnabled"}],"op":"replace"},{"value":"SMITermsAndConditions","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/fragments","op":"replace","value":[{"text":"SMITermsAndConditions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/navigatorTitle","op":"replace","value":[{"text":"SMITermsAndConditions","kind":"identifier"}]}]}]}