{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(pl)SMITextMessage","symbolKind":"protocol","role":"symbol","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TextMessage"}],"roleHeading":"Protocol","title":"TextMessage","navigatorTitle":[{"kind":"identifier","text":"TextMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A protocol that represents a text message within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/citationContent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/text"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextMessage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"EntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"text":", ","kind":"text"},{"text":"EntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access the content of a text message displayed in a conversation."},{"type":"text","text":" "},{"type":"text","text":"A text message can optionally include citation content that provides additional context."}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/textmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/textmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TextMessage":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage","abstract":[{"type":"text","text":"A protocol that represents a text message within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TextMessage","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/textmessage","role":"symbol","title":"TextMessage","navigatorTitle":[{"text":"TextMessage","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryPayload":{"role":"symbol","url":"\/documentation\/smiclientcore\/entrypayload","abstract":[{"text":"Common interface for the content of a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryPayload","kind":"identifier"}],"title":"EntryPayload","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"symbol","navigatorTitle":[{"text":"EntryPayload","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TextMessage/citationContent":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citationContent","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"CitationContent","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICitationContent"},{"text":")?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"citationContent","kind":"identifier"}],"abstract":[{"type":"text","text":"The citation content for this text message."}],"url":"\/documentation\/smiclientcore\/textmessage\/citationcontent","title":"citationContent","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/citationContent","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TextMessage/text":{"navigatorTitle":[{"text":"text","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"text","url":"\/documentation\/smiclientcore\/textmessage\/text","abstract":[{"type":"text","text":"The content of the text message."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/text","required":true},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that provides additional details for message-type entries in a conversation."}],"type":"topic","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}],"kind":"symbol","title":"EntryTypeMessage","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMITextMessage","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMITextMessage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SMITextMessage"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/citationContent","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TextMessage\/text"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMITextMessage","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SMIEntryPayload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryPayload"},{"text":", ","kind":"text"},{"text":"SMIEntryTypeMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryTypeMessage"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMITextMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/title"},{"op":"replace","value":[{"text":"SMITextMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/fragments"},{"op":"replace","value":[{"text":"SMITextMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage\/navigatorTitle"},{"op":"replace","value":"SMIEntryPayload","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIEntryPayload"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/fragments"},{"op":"replace","value":[{"text":"SMIEntryPayload","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryPayload\/navigatorTitle"},{"op":"replace","value":"citationContent","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage~1citationContent\/title"},{"op":"replace","value":[{"text":"citationContent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage~1citationContent\/fragments"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage~1text\/title"},{"op":"replace","value":[{"text":"text","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TextMessage~1text\/fragments"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"op":"replace","value":"SMIEntryTypeMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title"},{"op":"replace","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments"},{"op":"replace","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}