{"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleImageItem"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Use this protocol to access a title item that includes both text and an image. This protocol"},{"type":"text","text":" "},{"type":"text","text":"extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","isActive":true},{"type":"text","text":" to provide additional image functionality. The image is identified"},{"type":"text","text":" "},{"type":"text","text":"by its unique identifier and can be used in various UI contexts such as carousels or forms."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/titleimageitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/titleimageitem"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem\/imageId"],"title":"Instance Properties","generated":true}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"TitleImageItem"}],"externalID":"c:objc(pl)SMITitleImageItem","symbolKind":"protocol","title":"TitleImageItem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TitleImageItem","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents a title item with an associated image in a carousel or form."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","role":"symbol","abstract":[{"text":"A protocol that defines the structure for title components used in forms.","type":"text"}],"url":"\/documentation\/smiclientcore\/formtitleitem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleImageItem/imageId":{"url":"\/documentation\/smiclientcore\/titleimageitem\/imageid","navigatorTitle":[{"kind":"identifier","text":"imageId"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The unique identifier of the image associated with this title item."},{"type":"text","text":" "},{"type":"text","text":"This identifier can be used to fetch the actual image content from the SDK’s"},{"type":"text","text":" "},{"type":"text","text":"asset management system."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem\/imageId","required":true,"title":"imageId","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleImageItem":{"url":"\/documentation\/smiclientcore\/titleimageitem","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleImageItem"}],"navigatorTitle":[{"kind":"identifier","text":"TitleImageItem"}],"title":"TitleImageItem","abstract":[{"text":"A protocol that represents a title item with an associated image in a carousel or form.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMITitleImageItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMITitleImageItem"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMITitleImageItem","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleImageItem\/imageId"],"generated":true,"anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITitleImageItem"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","text":"SMIFormTitleItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"},{"kind":"text","text":">"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem~1imageId\/title","value":"imageId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem~1imageId\/fragments","value":[{"text":"imageId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/title","value":"SMITitleImageItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/fragments","value":[{"kind":"identifier","text":"SMITitleImageItem"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleImageItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMITitleImageItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}