{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/interactionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/titleItem"],"title":"Instance Properties","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TitleLinkItem","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to access an item that combines a title with interactive elements. Each item"},{"type":"text","text":" "},{"type":"text","text":"consists of a title component and a set of interaction options that users can select from. This"},{"type":"text","text":" "},{"type":"text","text":"protocol is commonly used in carousels to present interactive content to users."}]}],"kind":"content"}],"metadata":{"role":"symbol","title":"TitleLinkItem","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMITitleLinkItem","navigatorTitle":[{"text":"TitleLinkItem","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TitleLinkItem","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol that represents an interactive item in a carousel with a title and selectable options."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/titlelinkitem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/titlelinkitem"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem":{"title":"TitleLinkItem","navigatorTitle":[{"text":"TitleLinkItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an interactive item in a carousel with a title and selectable options."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TitleLinkItem","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/titlelinkitem","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem/interactionItems":{"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/interactionItems","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interactionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"interactionItems","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/titlelinkitem\/interactionitems","kind":"symbol","title":"interactionItems","abstract":[{"text":"The array of interaction options available for this item.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice"},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option that users can interact with.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem/titleItem":{"url":"\/documentation\/smiclientcore\/titlelinkitem\/titleitem","title":"titleItem","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/titleItem","role":"symbol","abstract":[{"type":"text","text":"The title information for this item."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the text and presentation details of the item’s title"},{"type":"text","text":" "},{"type":"text","text":"through the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"},{"type":"text","text":" protocol."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleItem","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"FormTitleItem","preciseIdentifier":"c:objc(pl)SMIFormTitleItem","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"titleItem","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"title":"FormTitleItem","type":"topic","url":"\/documentation\/smiclientcore\/formtitleitem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"type":"topic","url":"\/documentation\/smiclientcore\/choice","role":"symbol","title":"Choice","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","kind":"symbol","navigatorTitle":[{"text":"Choice","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Choice","kind":"identifier"}],"abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMITitleLinkItem","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMITitleLinkItem"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMITitleLinkItem"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/interactionItems","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem\/titleItem"],"title":"Instance Properties","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMITitleLinkItem","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMITitleLinkItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/title"},{"op":"replace","value":[{"text":"SMITitleLinkItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMITitleLinkItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/navigatorTitle"},{"op":"replace","value":"interactionItems","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1interactionItems\/title"},{"op":"replace","value":[{"kind":"identifier","text":"interactionItems"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1interactionItems\/fragments"},{"op":"replace","value":"titleItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1titleItem\/title"},{"op":"replace","value":[{"text":"titleItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem~1titleItem\/fragments"},{"op":"replace","value":"SMIFormTitleItem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"op":"replace","value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle"},{"op":"replace","value":"SMIChoice","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIChoice"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments"},{"op":"replace","value":[{"text":"SMIChoice","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle"}]}]}