{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranscriptRequestCompletion","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"PDFDocument","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFDocument"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}]},{"kind":"parameters","parameters":[{"name":"conversationTranscript","content":[{"type":"paragraph","inlineContent":[{"text":"A PDF document containing a transcript of the conversation.","type":"text"}]}]},{"name":"error","content":[{"inlineContent":[{"text":"If the conversation transcript request results in an error, it is returned here.","type":"text"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"TranscriptRequestCompletion","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"TranscriptRequestCompletion","externalID":"c:SMIConversationRequestCompletion.h@T@SMITranscriptRequestCompletion","role":"symbol","roleHeading":"Type Alias","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranscriptRequestCompletion","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/transcriptrequestcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/transcriptrequestcompletion"]}],"abstract":[{"text":"The completion block for returning a conversation transcript.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptRequestCompletion"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TranscriptRequestCompletion":{"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TranscriptRequestCompletion"}],"navigatorTitle":[{"kind":"identifier","text":"TranscriptRequestCompletion"}],"role":"symbol","url":"\/documentation\/smiclientcore\/transcriptrequestcompletion","title":"TranscriptRequestCompletion","abstract":[{"type":"text","text":"The completion block for returning a conversation transcript."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptRequestCompletion"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SMITranscriptRequestCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMITranscriptRequestCompletion"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMITranscriptRequestCompletion"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(PDFDocument *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)PDFDocument#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITranscriptRequestCompletion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"SMITranscriptRequestCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/title"},{"value":[{"text":"SMITranscriptRequestCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/fragments"},{"value":[{"kind":"identifier","text":"SMITranscriptRequestCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptRequestCompletion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}