{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TranscriptConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TranscriptConfiguration"}],"externalID":"c:objc(pl)SMITranscriptConfiguration","navigatorTitle":[{"kind":"identifier","text":"TranscriptConfiguration"}],"roleHeading":"Protocol","title":"TranscriptConfiguration","symbolKind":"protocol","role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol for defining configuration properties related to Transcription."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration\/allowTranscriptDownload"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"variants":[{"paths":["\/documentation\/smiclientcore\/transcriptconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/transcriptconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"references":{"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TranscriptConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to Transcription."}],"type":"topic","url":"\/documentation\/smiclientcore\/transcriptconfiguration","title":"TranscriptConfiguration","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranscriptConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"TranscriptConfiguration","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TranscriptConfiguration/allowTranscriptDownload":{"url":"\/documentation\/smiclientcore\/transcriptconfiguration\/allowtranscriptdownload","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration\/allowTranscriptDownload","abstract":[{"text":"Determines whether transcription is currently enabled.","type":"text"}],"type":"topic","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowTranscriptDownload","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"allowTranscriptDownload","navigatorTitle":[{"text":"allowTranscriptDownload","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMITranscriptConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMITranscriptConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMITranscriptConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration\/allowTranscriptDownload"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITranscriptConfiguration"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/title","value":"SMITranscriptConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/fragments","value":[{"text":"SMITranscriptConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/navigatorTitle","value":[{"text":"SMITranscriptConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration~1allowTranscriptDownload\/title","value":"allowTranscriptDownload","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration~1allowTranscriptDownload\/fragments","value":[{"text":"allowTranscriptDownload","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}