{"abstract":[{"text":"An enum that defines the possible states of a typing indicator in a conversation.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/started","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/stopped"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/Equatable-Implementations","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/_SwiftNewtypeWrapper-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This enum is used to track the typing status of participants in a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"Each type represents a specific typing indicator state that has been triggered.","type":"text"}]},{"type":"heading","level":2,"anchor":"Possible-Values","text":"Possible Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/started","type":"reference","isActive":true},{"text":" - Indicates that a participant has started to type","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/stopped","isActive":true,"type":"reference"},{"type":"text","text":" - Indicates that a participant has stopped typing"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"metadata":{"externalID":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TypingIndicatorTypes"}],"navigatorTitle":[{"text":"TypingIndicatorTypes","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Structure","title":"TypingIndicatorTypes","symbolKind":"struct"},"variants":[{"paths":["\/documentation\/smiclientcore\/typingindicatortypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/typingindicatortypes"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/started":{"title":"started","abstract":[{"type":"text","text":"Indicates the action of a participant started to type."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/started","url":"\/documentation\/smiclientcore\/typingindicatortypes\/started","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"started","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TypingIndicatorTypes","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMITypingIndicatorTypesStarted","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/_SwiftNewtypeWrapper-Implementations":{"kind":"article","abstract":[],"title":"_SwiftNewtypeWrapper Implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/_SwiftNewtypeWrapper-Implementations","type":"topic","url":"\/documentation\/smiclientcore\/typingindicatortypes\/_swiftnewtypewrapper-implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/stopped":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMITypingIndicatorTypes.h@T@SMITypingIndicatorTypes"}],"abstract":[{"type":"text","text":"Indicates the action of a participant stopped typing."}],"url":"\/documentation\/smiclientcore\/typingindicatortypes\/stopped","role":"symbol","title":"stopped","navigatorTitle":[{"text":"SMITypingIndicatorTypesStopped","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/stopped"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/smiclientcore\/typingindicatortypes\/equatable-implementations","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/Equatable-Implementations","role":"collectionGroup"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes/init(rawValue:)":{"kind":"symbol","type":"topic","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/typingindicatortypes\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes\/init(rawValue:)","role":"symbol"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s8SendableP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicatorTypes":{"role":"symbol","url":"\/documentation\/smiclientcore\/typingindicatortypes","title":"TypingIndicatorTypes","navigatorTitle":[{"text":"TypingIndicatorTypes","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicatorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicatorTypes","abstract":[{"text":"An enum that defines the possible states of a typing indicator in a conversation.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMITypingIndicatorTypes","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMITypingIndicatorTypes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMITypingIndicatorTypes","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"SMITypingIndicatorTypes","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMITypingIndicatorTypesStarted","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1started\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMITypingIndicatorTypesStarted"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1started\/fragments","op":"replace"},{"value":"SMITypingIndicatorTypesStopped","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1stopped\/title","op":"replace"},{"value":[{"text":"SMITypingIndicatorTypesStopped","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes~1stopped\/fragments","op":"replace"},{"value":"SMITypingIndicatorTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMITypingIndicatorTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMITypingIndicatorTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicatorTypes\/navigatorTitle","op":"replace"}]}]}