{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownAsset","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/unknownasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/unknownasset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"kind":"relationships","title":"Inherits From"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"UnknownAsset","kind":"identifier"}],"role":"symbol","title":"UnknownAsset","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownAsset"}],"externalID":"c:objc(pl)SMIUnknownAsset","roleHeading":"Protocol","modules":[{"name":"SMIClientCore"}],"symbolKind":"protocol"},"abstract":[{"text":"A protocol that represents an unknown or unsupported file asset type in a conversation.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownAsset"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"FileAsset","preciseIdentifier":"c:objc(pl)SMIFileAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Use this protocol to handle file assets that cannot be parsed or are not supported"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK. This protocol extends "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","isActive":true},{"type":"text","text":" to provide"},{"type":"text","text":" "},{"type":"text","text":"basic file asset functionality while allowing the conversation to continue functioning"},{"type":"text","text":" "},{"type":"text","text":"even when encountering unknown asset types."}],"type":"paragraph"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UnknownAsset":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnknownAsset","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UnknownAsset","title":"UnknownAsset","role":"symbol","navigatorTitle":[{"text":"UnknownAsset","kind":"identifier"}],"abstract":[{"text":"A protocol that represents an unknown or unsupported file asset type in a conversation.","type":"text"}],"url":"\/documentation\/smiclientcore\/unknownasset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset":{"url":"\/documentation\/smiclientcore\/fileasset","abstract":[{"text":"A protocol that represents a file asset in a conversation.","type":"text"}],"navigatorTitle":[{"text":"FileAsset","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileAsset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset","title":"FileAsset","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIUnknownAsset","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUnknownAsset"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUnknownAsset"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIUnknownAsset","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFileAsset","text":"SMIFileAsset","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIUnknownAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUnknownAsset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/fragments","op":"replace"},{"value":[{"text":"SMIUnknownAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UnknownAsset\/navigatorTitle","op":"replace"},{"value":"SMIFileAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/title","op":"replace"},{"value":[{"text":"SMIFileAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFileAsset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}