{"abstract":[{"type":"text","text":"Completion block for a templated URL used by the auto-response messaging component."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLParameterValueCompletion","kind":"identifier"},{"text":" = (any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","text":"SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/urlparametervaluecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/urlparametervaluecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"URLParameterValueCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLParameterValueCompletion","kind":"identifier"}],"role":"symbol","symbolKind":"typealias","externalID":"c:SMITemplatedUrlDelegate.h@T@SMITemplatedUrlParametersCompletion","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"URLParameterValueCompletion"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMITemplateable":{"kind":"symbol","title":"SMITemplateable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITemplateable"}],"url":"\/documentation\/smiclientcore\/smitemplateable","abstract":[{"type":"text","text":"A protocol that defines the interface for managing template parameters in URLs."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMITemplateable"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/URLParameterValueCompletion":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion","navigatorTitle":[{"text":"URLParameterValueCompletion","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLParameterValueCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/urlparametervaluecompletion","abstract":[{"type":"text","text":"Completion block for a templated URL used by the auto-response messaging component."}],"role":"symbol","title":"URLParameterValueCompletion"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMITemplatedUrlParametersCompletion","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMITemplatedUrlParametersCompletion"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMITemplatedUrlParametersCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv(#*Qoobjc(pl)SMITemplateable)","kind":"typeIdentifier","text":"void (^)(id<SMITemplateable>)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITemplatedUrlParametersCompletion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMITemplateable","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMITemplateable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/fragments"},{"op":"replace","value":[{"text":"SMITemplateable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/navigatorTitle"},{"op":"replace","value":"SMITemplatedUrlParametersCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/title"},{"op":"replace","value":[{"text":"SMITemplatedUrlParametersCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/fragments"},{"op":"replace","value":[{"text":"SMITemplatedUrlParametersCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}