{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerificationChallengeCompletion"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SMIUserVerification","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","text":"UserVerification"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"userVerification","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SMIUserVerification"},{"type":"text","text":" object which contains the customer identity token used to verify the user identity."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/userverificationchallengecompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/userverificationchallengecompletion"]}],"abstract":[{"text":"Completion block for user verification.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationChallengeCompletion","interfaceLanguage":"swift"},"metadata":{"title":"UserVerificationChallengeCompletion","externalID":"c:SMIUserVerificationDelegate.h@T@SMIUserVerificationChallengeCompletion","role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerificationChallengeCompletion","kind":"identifier"}],"navigatorTitle":[{"text":"UserVerificationChallengeCompletion","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerificationChallengeCompletion":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerificationChallengeCompletion","kind":"identifier"}],"title":"UserVerificationChallengeCompletion","url":"\/documentation\/smiclientcore\/userverificationchallengecompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationChallengeCompletion","navigatorTitle":[{"text":"UserVerificationChallengeCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Completion block for user verification.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/userverification","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","role":"symbol","type":"topic","title":"UserVerification","navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents a verified user’s authentication credentials."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIUserVerificationChallengeCompletion","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIUserVerificationChallengeCompletion","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIUserVerificationChallengeCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(SMIUserVerification *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)SMIUserVerification)"},{"text":" ","kind":"text"},{"text":"SMIUserVerificationChallengeCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIUserVerificationChallengeCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUserVerificationChallengeCompletion"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUserVerificationChallengeCompletion"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/navigatorTitle","op":"replace"},{"value":"SMIUserVerification","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIUserVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments","op":"replace"},{"value":[{"text":"SMIUserVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}