{"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/init(customerIdentityToken:type:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/customerIdentityToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/type"],"anchor":"Instance-Properties","title":"Instance Properties"}],"abstract":[{"type":"text","text":"A class that represents a verified user’s authentication credentials."}],"variants":[{"paths":["\/documentation\/smiclientcore\/userverification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/userverification"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"},"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:objc(cs)SMIUserVerification","title":"UserVerification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}],"navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"],"title":"Inherited By","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying","doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIAuthorization","doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP","doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerification"}]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"This class encapsulates the authentication information required to verify a user’s"},{"type":"text","text":" "},{"type":"text","text":"identity with the service. It includes the customer identity token and its"},{"type":"text","text":" "},{"type":"text","text":"authorization type, which are used to authenticate API requests."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.salesforce.SMIClientCore/objc(cs)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","role":"symbol","navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"title":"UserVerification","url":"\/documentation\/smiclientcore\/userverification","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/type":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/type","abstract":[{"text":"The type of authorization used for the customer identity token.","type":"text"},{"text":" ","type":"text"},{"text":"This determines how the token should be processed and validated.","type":"text"}],"title":"type","url":"\/documentation\/smiclientcore\/userverification\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"AuthorizationTypes"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.salesforce.SMIClientCore/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSCopying"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/init(customerIdentityToken:type:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/init(customerIdentityToken:type:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","type":"reference"},{"text":" with the specified credentials, which is used to pass in user verification credentials.","type":"text"}],"url":"\/documentation\/smiclientcore\/userverification\/init(customeridentitytoken:type:)","navigatorTitle":[{"kind":"identifier","text":"initWithCustomerIdentityToken:type:"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerIdentityToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"AuthorizationTypes"},{"kind":"text","text":")"}],"title":"init(customerIdentityToken:type:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIAuthorization":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAuthorization"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIAuthorization","role":"symbol","title":"SMIAuthorization","type":"topic","url":"\/documentation\/smiclientcore\/smiauthorization","navigatorTitle":[{"kind":"identifier","text":"SMIAuthorization"}],"kind":"symbol","abstract":[{"text":"A protocol that defines the authorization requirements for API requests.","type":"text"}]},"doc://com.salesforce.SMIClientCore/s7CVarArgP":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PassthroughVerification":{"abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"url":"\/documentation\/smiclientcore\/passthroughverification","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification","type":"topic","title":"PassthroughVerification","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassthroughVerification"}],"navigatorTitle":[{"kind":"identifier","text":"PassthroughVerification"}]},"doc://com.salesforce.SMIClientCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/objc(pl)NSObject"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/customerIdentityToken":{"abstract":[{"type":"text","text":"The authentication token used to verify the user’s identity."}],"navigatorTitle":[{"text":"customerIdentityToken","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/customerIdentityToken","title":"customerIdentityToken","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerIdentityToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/userverification\/customeridentitytoken"},"doc://com.salesforce.SMIClientCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH"},"doc://com.salesforce.SMIClientCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SMIUserVerification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/customerIdentityToken","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/type"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/init(customerIdentityToken:type:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PassthroughVerification"],"title":"Inherited By","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIAuthorization"],"title":"Conforms To","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIUserVerification","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","value":"SMIUserVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle","value":[{"kind":"identifier","text":"SMIUserVerification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1init(customerIdentityToken:type:)\/title","value":"initWithCustomerIdentityToken:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1init(customerIdentityToken:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerIdentityToken:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/title","value":"SMIAuthorization"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/fragments","value":[{"kind":"identifier","text":"SMIAuthorization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIAuthorization\/navigatorTitle","value":[{"text":"SMIAuthorization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/title","value":"SMIPassthroughVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/fragments","value":[{"kind":"identifier","text":"SMIPassthroughVerification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PassthroughVerification\/navigatorTitle","value":[{"text":"SMIPassthroughVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1customerIdentityToken\/title","value":"customerIdentityToken"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1customerIdentityToken\/fragments","value":[{"kind":"identifier","text":"customerIdentityToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}