{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/SQ","doc:\/\/com.salesforce.SMIClientCore\/SH","doc:\/\/com.salesforce.SMIClientCore\/SY","doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"navigatorTitle":[{"kind":"identifier","text":"VoiceProvider"}],"role":"symbol","externalID":"c:SMIVoiceProvider.h@T@SMIVoiceProvider","modules":[{"name":"SMIClientCore"}],"title":"VoiceProvider","symbolKind":"struct","roleHeading":"Structure"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/voiceprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/voiceprovider"]}],"abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Possible Values","type":"heading","level":2,"anchor":"Possible-Values"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/liveKit","type":"reference"},{"text":" - Voice connection serviced via LiveKit","type":"text"}]}]}]}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/liveKit"],"anchor":"Type-Properties","title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/init(rawValue:)":{"type":"topic","url":"\/documentation\/smiclientcore\/voiceprovider\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/SH":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/liveKit":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveKit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VoiceProvider","kind":"typeIdentifier","preciseIdentifier":"c:SMIVoiceProvider.h@T@SMIVoiceProvider"}],"abstract":[{"text":"Voice connection serviced via LiveKit","type":"text"}],"navigatorTitle":[{"text":"SMIVoiceProviderLiveKit","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/voiceprovider\/livekit","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/liveKit","title":"liveKit"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider/Equatable-Implementations":{"type":"topic","url":"\/documentation\/smiclientcore\/voiceprovider\/equatable-implementations","title":"Equatable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider\/Equatable-Implementations","abstract":[]},"doc://com.salesforce.SMIClientCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.salesforce.SMIClientCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SY","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://com.salesforce.SMIClientCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/VoiceProvider":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceProvider"}],"abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"navigatorTitle":[{"kind":"identifier","text":"VoiceProvider"}],"url":"\/documentation\/smiclientcore\/voiceprovider","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/VoiceProvider","title":"VoiceProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SMIVoiceProvider"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIVoiceProvider"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIVoiceProvider"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider~1liveKit\/title","value":"SMIVoiceProviderLiveKit","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider~1liveKit\/fragments","value":[{"text":"SMIVoiceProviderLiveKit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/title","value":"SMIVoiceProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/fragments","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1VoiceProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]}]}]}