{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/isEnabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates whether the fallback message is active."},{"type":"text","text":" "},{"type":"text","text":"When true, the fallback message will be displayed when the service is unavailable."}],"variants":[{"paths":["\/documentation\/smiclientcore\/fallbackmessage\/isenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/fallbackmessage\/isenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"modules":[{"name":"SMIClientCore"}],"title":"isEnabled","roleHeading":"Instance Property","required":true,"symbolKind":"property","externalID":"c:objc(pl)SMIFallbackMessage(py)isEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage/isEnabled":{"url":"\/documentation\/smiclientcore\/fallbackmessage\/isenabled","kind":"symbol","type":"topic","role":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage\/isEnabled","title":"isEnabled","navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Indicates whether the fallback message is active.","type":"text"},{"text":" ","type":"text"},{"text":"When true, the fallback message will be displayed when the service is unavailable.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FallbackMessage","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/fallbackmessage","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FallbackMessage","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the fallback message configuration for when the service is unavailable."}],"title":"FallbackMessage","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEnabled","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1isEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isEnabled"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage~1isEnabled\/fragments"},{"op":"replace","value":"SMIFallbackMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFallbackMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFallbackMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}