{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"miawMobileV2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","text":"ClientType"}],"extendedModule":"SMIClientCore","role":"symbol","externalID":"c:@SMIClientTypeMIAWMobileV2","navigatorTitle":[{"kind":"identifier","text":"SMIClientTypeMIAWMobileV2"}],"modules":[{"name":"SMIClientCore"}],"title":"miawMobileV2","roleHeading":"Type Property","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType"]]},"abstract":[{"type":"text","text":"Enhanced mobile client type for MIAW integrations with additional capabilities."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"miawMobileV2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType","text":"ClientType"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV2","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/clienttype\/miawmobilev2"]},{"paths":["\/documentation\/smiclientcore\/clienttype\/miawmobilev2"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType","title":"ClientType","navigatorTitle":[{"kind":"identifier","text":"ClientType"}],"abstract":[{"type":"text","text":"A type that defines the client type sent during authentication to identify the SDK integration type."}],"type":"topic","url":"\/documentation\/smiclientcore\/clienttype","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ClientType/miawMobileV2":{"abstract":[{"type":"text","text":"Enhanced mobile client type for MIAW integrations with additional capabilities."}],"navigatorTitle":[{"kind":"identifier","text":"SMIClientTypeMIAWMobileV2"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType\/miawMobileV2","title":"miawMobileV2","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"miawMobileV2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","text":"ClientType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/clienttype\/miawmobilev2"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIClientTypeMIAWMobileV2","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIClientTypeMIAWMobileV2","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIClientType.h@T@SMIClientType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ClientType","text":"SMIClientType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIClientTypeMIAWMobileV2"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"SMIClientType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIClientType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIClientType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType\/navigatorTitle"},{"value":"SMIClientTypeMIAWMobileV2","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV2\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ClientType~1miawMobileV2\/fragments","value":[{"kind":"identifier","text":"SMIClientTypeMIAWMobileV2"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}