{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/height","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset"]]},"sections":[],"metadata":{"platforms":[{"name":"iOS","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","required":true,"externalID":"c:objc(pl)SMIImageAsset(py)height","modules":[{"name":"SMIClientCore"}]},"abstract":[{"text":"The expected height of the image in pixels.","type":"text"},{"text":" ","type":"text"},{"text":"This property is available before the image is loaded and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"pre-allocate UI space or calculate layout constraints.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/imageasset\/height"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/imageasset\/height"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset":{"abstract":[{"type":"text","text":"A protocol that represents an image asset in a conversation."}],"navigatorTitle":[{"kind":"identifier","text":"ImageAsset"}],"title":"ImageAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/imageasset","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAsset"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/height":{"title":"height","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","required":true,"role":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"abstract":[{"text":"The expected height of the image in pixels.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property is available before the image is loaded and can be used to"},{"type":"text","text":" "},{"type":"text","text":"pre-allocate UI space or calculate layout constraints."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/height","url":"\/documentation\/smiclientcore\/imageasset\/height"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"height"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"height","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/title","value":"SMIImageAsset"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/fragments","value":[{"kind":"identifier","text":"SMIImageAsset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/navigatorTitle","value":[{"text":"SMIImageAsset","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1height\/fragments","value":[{"kind":"identifier","text":"height"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}