{"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","title":"image","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"platforms":[{"name":"iOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false}],"externalID":"c:objc(pl)SMIImageAsset(py)image","required":true,"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/image","interfaceLanguage":"swift"},"abstract":[{"text":"The image content of this asset.","type":"text"},{"text":" ","type":"text"},{"text":"This property is initially ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" and must be loaded using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Once loaded, this property provides access to the image data for display.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/imageasset\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/imageasset\/image"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset":{"type":"topic","abstract":[{"text":"A protocol that represents an image asset in a conversation.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageAsset","kind":"identifier"}],"navigatorTitle":[{"text":"ImageAsset","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","url":"\/documentation\/smiclientcore\/imageasset","title":"ImageAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"kind":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","title":"fetchContent(completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchContentWithCompletion:"}],"abstract":[{"text":"Fetches the content of this file asset asynchronously.","type":"text"},{"text":" ","type":"text"},{"text":"This method downloads the file content if it’s not already cached.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchContent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/image":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/image","url":"\/documentation\/smiclientcore\/imageasset\/image","kind":"symbol","abstract":[{"text":"The image content of this asset.","type":"text"},{"text":" ","type":"text"},{"text":"This property is initially ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" and must be loaded using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Once loaded, this property provides access to the image data for display.","type":"text"}],"title":"image","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"image"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"image"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/title","op":"replace","value":"SMIImageAsset"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIImageAsset"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/navigatorTitle","op":"replace","value":[{"text":"SMIImageAsset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","op":"replace","value":"fetchContentWithCompletion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchContentWithCompletion:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1image\/title","op":"replace","value":"image"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1image\/fragments","op":"replace","value":[{"text":"image","kind":"identifier"}]}]}]}