{"metadata":{"navigatorTitle":[{"text":"width","kind":"identifier"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"2.0","deprecated":false,"unavailable":false}],"roleHeading":"Instance Property","title":"width","externalID":"c:objc(pl)SMIImageAsset(py)width","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"modules":[{"name":"SMIClientCore"}],"required":true},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/width","interfaceLanguage":"swift"},"abstract":[{"text":"The expected width of the image in pixels.","type":"text"},{"text":" ","type":"text"},{"text":"This property is available before the image is loaded and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"pre-allocate UI space or calculate layout constraints.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/imageasset\/width"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/imageasset\/width"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset/width":{"navigatorTitle":[{"kind":"identifier","text":"width"}],"type":"topic","title":"width","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset\/width","abstract":[{"text":"The expected width of the image in pixels.","type":"text"},{"text":" ","type":"text"},{"text":"This property is available before the image is loaded and can be used to","type":"text"},{"text":" ","type":"text"},{"text":"pre-allocate UI space or calculate layout constraints.","type":"text"}],"url":"\/documentation\/smiclientcore\/imageasset\/width","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ImageAsset":{"abstract":[{"type":"text","text":"A protocol that represents an image asset in a conversation."}],"navigatorTitle":[{"kind":"identifier","text":"ImageAsset"}],"title":"ImageAsset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ImageAsset","kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/imageasset","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageAsset"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"width","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"width","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1width\/title","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset~1width\/fragments","op":"replace"},{"value":"SMIImageAsset","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/title","op":"replace"},{"value":[{"text":"SMIImageAsset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIImageAsset"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ImageAsset\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}