{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FormInputSectionType","preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType"}],"navigatorTitle":[{"text":"sectionType","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIFormInputSection(py)sectionType","modules":[{"name":"SMIClientCore"}],"title":"sectionType","roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"paths":["\/documentation\/smiclientcore\/forminputsection\/sectiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputsection\/sectiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The type of input contained in this section."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of section, which affects how the input is"},{"type":"text","text":" "},{"type":"text","text":"presented and collected. See "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","type":"reference"},{"text":" for available section types.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sectionType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType","kind":"typeIdentifier","text":"FormInputSectionType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection\/sectionType","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection":{"title":"FormInputSection","abstract":[{"text":"A protocol that defines the base type for form input sections.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminputsection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputSection","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputSection","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSection/sectionType":{"abstract":[{"type":"text","text":"The type of input contained in this section."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of section, which affects how the input is"},{"type":"text","text":" "},{"type":"text","text":"presented and collected. See "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","isActive":true},{"type":"text","text":" for available section types."}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSection\/sectionType","navigatorTitle":[{"text":"sectionType","kind":"identifier"}],"title":"sectionType","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sectionType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType","text":"FormInputSectionType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/forminputsection\/sectiontype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputSectionType":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputsectiontype","title":"FormInputSectionType","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","navigatorTitle":[{"text":"FormInputSectionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the types of form input sections available in the system."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputSectionType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"sectionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"sectionType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMIFormInputSectionType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputSectionType","preciseIdentifier":"c:SMIFormInputSectionType.h@T@SMIFormInputSectionType"},{"text":" ","kind":"text"},{"text":"sectionType","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"SMIFormInputSection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/title","op":"replace"},{"value":[{"text":"SMIFormInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/fragments","op":"replace"},{"value":[{"text":"SMIFormInputSection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection\/navigatorTitle","op":"replace"},{"value":"sectionType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection~1sectionType\/title"},{"op":"replace","value":[{"text":"sectionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSection~1sectionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/title","value":"SMIFormInputSectionType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/fragments","value":[{"kind":"identifier","text":"SMIFormInputSectionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputSectionType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormInputSectionType"}]}]}]}