{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/booleanFormat","interfaceLanguage":"swift"},"abstract":[{"text":"Indicates that a boolean field contains an invalid value.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input is not “true” or “false”.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/booleanformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/booleanformat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesBooleanFormat"}],"roleHeading":"Case","externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesBooleanFormat","symbolKind":"case","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanFormat"}],"title":"PreChatErrorTypes.booleanFormat"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanFormat"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/booleanFormat":{"title":"PreChatErrorTypes.booleanFormat","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesBooleanFormat"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Indicates that a boolean field contains an invalid value."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input is not “true” or “false”."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"booleanFormat"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes\/booleanformat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/booleanFormat"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An enum that defines the possible validation errors for pre-chat fields.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIPreChatErrorTypesBooleanFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIPreChatErrorTypesBooleanFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMIPreChatErrorTypesBooleanFormat","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1booleanFormat\/title","value":"SMIPreChatErrorTypesBooleanFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1booleanFormat\/fragments","value":[{"kind":"identifier","text":"SMIPreChatErrorTypesBooleanFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title","value":"SMIPreChatErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments","value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}