{"sections":[],"abstract":[{"text":"Indicates that a required checkbox field is not selected.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a checkbox marked as required is not checked.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/checkBoxSelected","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkBoxSelected","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/checkboxselected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/checkboxselected"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesCheckBoxSelected"}],"symbolKind":"case","externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesCheckBoxSelected","title":"PreChatErrorTypes.checkBoxSelected","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkBoxSelected","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","abstract":[{"type":"text","text":"An enum that defines the possible validation errors for pre-chat fields."}],"role":"symbol","navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"title":"PreChatErrorTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/checkBoxSelected":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkBoxSelected","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/checkBoxSelected","url":"\/documentation\/smiclientcore\/prechaterrortypes\/checkboxselected","abstract":[{"text":"Indicates that a required checkbox field is not selected.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a checkbox marked as required is not checked.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMIPreChatErrorTypesCheckBoxSelected","kind":"identifier"}],"title":"PreChatErrorTypes.checkBoxSelected","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIPreChatErrorTypesCheckBoxSelected","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesCheckBoxSelected"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SMIPreChatErrorTypesCheckBoxSelected","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIPreChatErrorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle"},{"value":"SMIPreChatErrorTypesCheckBoxSelected","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1checkBoxSelected\/title"},{"value":[{"text":"SMIPreChatErrorTypesCheckBoxSelected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1checkBoxSelected\/fragments"}]}]}