{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/emailFormat"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"metadata":{"externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesEmailFormat","role":"symbol","roleHeading":"Case","title":"PreChatErrorTypes.emailFormat","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIPreChatErrorTypesEmailFormat","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailFormat"}],"symbolKind":"case"},"sections":[],"abstract":[{"type":"text","text":"Indicates that an email field contains an invalid email address format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input doesn’t match standard email address patterns."}],"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/emailformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/emailformat"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emailFormat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"navigatorTitle":[{"kind":"identifier","text":"PreChatErrorTypes"}],"type":"topic","abstract":[{"text":"An enum that defines the possible validation errors for pre-chat fields.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatErrorTypes"}],"role":"symbol","kind":"symbol","title":"PreChatErrorTypes","url":"\/documentation\/smiclientcore\/prechaterrortypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/emailFormat":{"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesEmailFormat"}],"role":"symbol","kind":"symbol","title":"PreChatErrorTypes.emailFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/emailFormat","abstract":[{"type":"text","text":"Indicates that an email field contains an invalid email address format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input doesn’t match standard email address patterns."}],"url":"\/documentation\/smiclientcore\/prechaterrortypes\/emailformat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailFormat"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SMIPreChatErrorTypesEmailFormat","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypesEmailFormat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SMIPreChatErrorTypesEmailFormat","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIPreChatErrorTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle"},{"value":"SMIPreChatErrorTypesEmailFormat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1emailFormat\/title"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesEmailFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1emailFormat\/fragments"}]}]}