{"sections":[],"kind":"symbol","metadata":{"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"}],"externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesMaxLength","title":"PreChatErrorTypes.maxLength","roleHeading":"Case","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIPreChatErrorTypesMaxLength","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/maxLength"},"abstract":[{"text":"Indicates that a field’s value exceeds its maximum allowed length.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input text is longer than the field’s ","type":"text"},{"code":"maxLength","type":"codeVoice"},{"text":" property.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/maxlength"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/maxlength"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxLength"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/maxLength":{"navigatorTitle":[{"text":"SMIPreChatErrorTypesMaxLength","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes\/maxlength","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/maxLength","type":"topic","abstract":[{"type":"text","text":"Indicates that a field’s value exceeds its maximum allowed length."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input text is longer than the field’s "},{"type":"codeVoice","code":"maxLength"},{"type":"text","text":" property."}],"role":"symbol","title":"PreChatErrorTypes.maxLength","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible validation errors for pre-chat fields."}],"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SMIPreChatErrorTypesMaxLength","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesMaxLength"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SMIPreChatErrorTypesMaxLength","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIPreChatErrorTypesMaxLength","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1maxLength\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatErrorTypesMaxLength"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1maxLength\/fragments","op":"replace"},{"value":"SMIPreChatErrorTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle","op":"replace"}]}]}