{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SMIPreChatErrorTypesNumberFormat","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesNumberFormat","title":"PreChatErrorTypes.numberFormat"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/numberformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/numberformat"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/numberFormat","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Indicates that a number field contains non-numeric characters.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input contains characters other than digits.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberFormat","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the possible validation errors for pre-chat fields."}],"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/numberFormat":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/numberFormat","type":"topic","title":"PreChatErrorTypes.numberFormat","abstract":[{"text":"Indicates that a number field contains non-numeric characters.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input contains characters other than digits.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes\/numberformat","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesNumberFormat"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIPreChatErrorTypesNumberFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIPreChatErrorTypesNumberFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIPreChatErrorTypesNumberFormat"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIPreChatErrorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle"},{"value":"SMIPreChatErrorTypesNumberFormat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1numberFormat\/title"},{"value":[{"text":"SMIPreChatErrorTypesNumberFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1numberFormat\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}