{"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/phoneformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/phoneformat"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesPhoneFormat","title":"PreChatErrorTypes.phoneFormat","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIPreChatErrorTypesPhoneFormat","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneFormat"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/phoneFormat","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"text":"Indicates that a phone field contains an invalid phone number format.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when the input doesn’t match standard phone number patterns.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/phoneFormat":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneFormat"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/phoneFormat","url":"\/documentation\/smiclientcore\/prechaterrortypes\/phoneformat","abstract":[{"type":"text","text":"Indicates that a phone field contains an invalid phone number format."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when the input doesn’t match standard phone number patterns."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIPreChatErrorTypesPhoneFormat"}],"title":"PreChatErrorTypes.phoneFormat","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","abstract":[{"type":"text","text":"An enum that defines the possible validation errors for pre-chat fields."}],"role":"symbol","navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"title":"PreChatErrorTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIPreChatErrorTypesPhoneFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIPreChatErrorTypesPhoneFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SMIPreChatErrorTypesPhoneFormat"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SMIPreChatErrorTypesPhoneFormat","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1phoneFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1phoneFormat\/fragments","value":[{"text":"SMIPreChatErrorTypesPhoneFormat","kind":"identifier"}]},{"value":"SMIPreChatErrorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle"}]}]}