{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/requiredField","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/requiredfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechaterrortypes\/requiredfield"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Indicates that a required field was left empty.","type":"text"},{"text":" ","type":"text"},{"text":"This error occurs when a field marked as required has no value.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","externalID":"c:@E@SMIPreChatErrorTypes@SMIPreChatErrorTypesRequiredField","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}],"title":"PreChatErrorTypes.requiredField","role":"symbol","navigatorTitle":[{"text":"SMIPreChatErrorTypesRequiredField","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SMIClientCore"}]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes/requiredField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes\/requiredField","navigatorTitle":[{"text":"SMIPreChatErrorTypesRequiredField","kind":"identifier"}],"title":"PreChatErrorTypes.requiredField","type":"topic","abstract":[{"type":"text","text":"Indicates that a required field was left empty."},{"type":"text","text":" "},{"type":"text","text":"This error occurs when a field marked as required has no value."}],"role":"symbol","url":"\/documentation\/smiclientcore\/prechaterrortypes\/requiredfield","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredField","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An enum that defines the possible validation errors for pre-chat fields.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SMIPreChatErrorTypesRequiredField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIPreChatErrorTypesRequiredField","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SMIPreChatErrorTypesRequiredField"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1requiredField\/title","value":"SMIPreChatErrorTypesRequiredField"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes~1requiredField\/fragments","value":[{"text":"SMIPreChatErrorTypesRequiredField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title","value":"SMIPreChatErrorTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments","value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIPreChatErrorTypes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}