{"metadata":{"symbolKind":"protocol","modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractModalityConnection","kind":"identifier"}],"navigatorTitle":[{"text":"AbstractModalityConnection","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection","title":"AbstractModalityConnection","roleHeading":"Protocol"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection\/modality"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection"],"anchor":"Connection-Models","title":"Connection Models","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SMIAbstractModalityConnection) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractModalityConnection","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/abstractmodalityconnection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/abstractmodalityconnection"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"abstract":[{"type":"text","text":"A protocol that represents a connection to a conversation modality."}],"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject","title":"NSObject"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection":{"navigatorTitle":[{"text":"AbstractVoiceConnection","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"identifier"}],"title":"AbstractVoiceConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an abstract voice connection and identifies the voice provider."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/Modality":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/Modality","title":"Modality","type":"topic","url":"\/documentation\/smimultimediacommon\/modality","kind":"symbol","navigatorTitle":[{"text":"Modality","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modality","kind":"identifier"}],"abstract":[{"text":"An enum that defines the supported conversation modalities.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceModalityConnection":{"navigatorTitle":[{"kind":"identifier","text":"VoiceModalityConnection"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/voicemodalityconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceModalityConnection"}],"title":"VoiceModalityConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a voice-specific modality connection."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractModalityConnection":{"role":"symbol","type":"topic","title":"AbstractModalityConnection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractModalityConnection"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractModalityConnection"}],"url":"\/documentation\/smimultimediacommon\/abstractmodalityconnection","abstract":[{"type":"text","text":"A protocol that represents a connection to a conversation modality."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractModalityConnection/modality":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modality","preciseIdentifier":"c:SMIModality.h@T@SMIModality"}],"url":"\/documentation\/smimultimediacommon\/abstractmodalityconnection\/modality","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection\/modality","abstract":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/Modality"},{"type":"text","text":" type for this connection."}],"type":"topic","title":"modality","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"modality"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection":{"url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveKitVoiceConnection","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveKitVoiceConnection"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection","abstract":[{"text":"A protocol that represents a LiveKit voice connection and provides the credentials needed to join a room.","type":"text"}],"title":"LiveKitVoiceConnection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIAbstractModalityConnection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection\/modality"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection"],"anchor":"Connection-Models","generated":true,"title":"Connection Models"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIAbstractModalityConnection"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/title","value":"SMIAbstractVoiceConnection"},{"value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/fragments","op":"replace"},{"value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/navigatorTitle","op":"replace"},{"value":"SMIModality","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/title","op":"replace"},{"value":[{"text":"SMIModality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/fragments","op":"replace"},{"value":[{"text":"SMIModality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/navigatorTitle","op":"replace"},{"value":"SMIVoiceModalityConnection","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/title","op":"replace"},{"value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/fragments","op":"replace"},{"value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/navigatorTitle","op":"replace"},{"value":"SMIAbstractModalityConnection","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/title","op":"replace"},{"value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAbstractModalityConnection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection~1modality\/title","value":"modality"},{"value":[{"text":"modality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection~1modality\/fragments","op":"replace"},{"value":"SMILiveKitVoiceConnection","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/fragments","value":[{"kind":"identifier","text":"SMILiveKitVoiceConnection"}]},{"value":[{"kind":"identifier","text":"SMILiveKitVoiceConnection"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/navigatorTitle","op":"replace"}]}]}