{"sections":[],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SMIAudioProcessReceiver) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:s8SendableP","text":"Sendable","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Implement this protocol to receive raw audio buffers for rendering or normalized","type":"text"},{"text":" ","type":"text"},{"text":"channel levels for visualization.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/audioprocessreceiver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/audioprocessreceiver"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver"},"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioProcessReceiver","modules":[{"name":"SMIMultimediaCommon"}],"title":"AudioProcessReceiver","navigatorTitle":[{"text":"AudioProcessReceiver","kind":"identifier"}],"roleHeading":"Protocol"},"abstract":[{"type":"text","text":"A protocol for receiving processed audio data from an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","isActive":true},{"type":"text","text":"."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/s8SendableP","doc:\/\/com.salesforce.SMIMultimediaCommon\/s16SendableMetatypeP"],"type":"inheritsFrom"}],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"]},{"title":"Audio","anchor":"Audio","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/s16SendableMetatypeP","type":"unresolvable"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioStreamProtocol":{"role":"symbol","type":"topic","title":"AudioStreamProtocol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioStreamProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"AudioStreamProtocol","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audiostreamprotocol","abstract":[{"type":"text","text":"A protocol that represents a collection of audio tracks associated with a participant."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioTrackProtocol":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","type":"topic","title":"AudioTrackProtocol","url":"\/documentation\/smimultimediacommon\/audiotrackprotocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioTrackProtocol"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioTrackProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents an individual audio track and manages its process receivers."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver/receive(normalizedChannels:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedChannels","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"])","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver\/receive(normalizedchannels:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","abstract":[{"text":"Receives normalized audio channel levels for visualization.","type":"text"}],"type":"topic","title":"receive(normalizedChannels:)","kind":"symbol","navigatorTitle":[{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver/render(buffer:)":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"render","kind":"identifier"},{"text":"(","kind":"text"},{"text":"buffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","text":"AVAudioPCMBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"renderWithBuffer:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)","abstract":[{"type":"text","text":"Receives the raw audio PCM buffer for rendering or processing."}],"title":"render(buffer:)","url":"\/documentation\/smimultimediacommon\/audioprocessreceiver\/render(buffer:)"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioProcessReceiver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioProcessReceiver","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audioprocessreceiver","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver","abstract":[{"type":"text","text":"A protocol for receiving processed audio data from an "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"AudioProcessReceiver","kind":"symbol","navigatorTitle":[{"text":"AudioProcessReceiver","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/s8SendableP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIAudioProcessReceiver","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SMIAudioProcessReceiver","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SMIAudioProcessReceiver","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/receive(normalizedChannels:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioProcessReceiver\/render(buffer:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"],"title":"Related Documentation","anchor":"Related-Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioTrackProtocol"],"generated":true,"title":"Audio","anchor":"Audio"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIAudioProcessReceiver"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIAudioStream","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/title"},{"op":"replace","value":[{"text":"SMIAudioStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIAudioStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/navigatorTitle"},{"op":"replace","value":"SMIAudioTrack","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/title"},{"op":"replace","value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioTrackProtocol\/navigatorTitle"},{"op":"replace","value":"receiveWithNormalizedChannels:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"receiveWithNormalizedChannels:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1receive(normalizedChannels:)\/fragments"},{"op":"replace","value":"renderWithBuffer:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1render(buffer:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"renderWithBuffer:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver~1render(buffer:)\/fragments"},{"op":"replace","value":"SMIAudioProcessReceiver","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/title"},{"op":"replace","value":[{"text":"SMIAudioProcessReceiver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/fragments"},{"op":"replace","value":[{"text":"SMIAudioProcessReceiver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioProcessReceiver\/navigatorTitle"}]}]}