{"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"title":"Connection Models","generated":true,"anchor":"Connection-Models"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/smimultimediacommon\/livekitvoiceconnection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/livekitvoiceconnection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"LiveKitVoiceConnection"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LiveKitVoiceConnection"}],"title":"LiveKitVoiceConnection","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMILiveKitVoiceConnection"},"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/endpoint","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/roomName","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/token"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SMILiveKitVoiceConnection) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveKitVoiceConnection","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractVoiceConnection"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"A protocol that represents a LiveKit voice connection and provides the credentials needed to join a room.","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractModalityConnection":{"role":"symbol","type":"topic","title":"AbstractModalityConnection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractModalityConnection"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractModalityConnection"}],"url":"\/documentation\/smimultimediacommon\/abstractmodalityconnection","abstract":[{"type":"text","text":"A protocol that represents a connection to a conversation modality."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection/roomName":{"role":"symbol","required":true,"type":"topic","title":"roomName","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/roomName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"roomName"}],"url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection\/roomname","abstract":[{"type":"text","text":"The name of the LiveKit room to join."}]},"doc://com.salesforce.SMIMultimediaCommon/objc(pl)NSObject":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection":{"url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveKitVoiceConnection","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveKitVoiceConnection"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection","abstract":[{"text":"A protocol that represents a LiveKit voice connection and provides the credentials needed to join a room.","type":"text"}],"title":"LiveKitVoiceConnection","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection/token":{"navigatorTitle":[{"text":"token","kind":"identifier"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection\/token","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/token","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"token","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The authentication token for the LiveKit room."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection":{"navigatorTitle":[{"text":"AbstractVoiceConnection","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"identifier"}],"title":"AbstractVoiceConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an abstract voice connection and identifies the voice provider."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceModalityConnection":{"navigatorTitle":[{"kind":"identifier","text":"VoiceModalityConnection"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/voicemodalityconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceModalityConnection"}],"title":"VoiceModalityConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a voice-specific modality connection."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection/endpoint":{"url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection\/endpoint","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endpoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"endpoint","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/endpoint","abstract":[{"text":"The WebSocket endpoint URL for the LiveKit server.","type":"text"}],"title":"endpoint","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMILiveKitVoiceConnection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMILiveKitVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SMILiveKitVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/endpoint","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/roomName","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection\/token"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"anchor":"Related-Documentation","title":"Related Documentation"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"anchor":"Connection-Models","title":"Connection Models"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMILiveKitVoiceConnection"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"SMIAbstractVoiceConnection","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractVoiceConnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/title","value":"SMIAbstractModalityConnection","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/fragments","value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/navigatorTitle","value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1roomName\/title","value":"roomName","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1roomName\/fragments","value":[{"text":"roomName","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/title","value":"SMILiveKitVoiceConnection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/fragments","value":[{"text":"SMILiveKitVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/navigatorTitle","value":[{"text":"SMILiveKitVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1token\/fragments","value":[{"text":"token","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/title","value":"SMIAbstractVoiceConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/fragments","value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/navigatorTitle","value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/title","value":"SMIVoiceModalityConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/fragments","value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/navigatorTitle","value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1endpoint\/title","value":"endpoint"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection~1endpoint\/fragments","value":[{"kind":"identifier","text":"endpoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}