{"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/Modality","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode"],"anchor":"Enums","title":"Enums","generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconnectionstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconnectionstate"]}],"metadata":{"roleHeading":"Structure","role":"symbol","title":"MultimediaConnectionState","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaConnectionState","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaConnectionState","kind":"identifier"}],"externalID":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connected","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connecting","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnected","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnecting","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/ended","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/initial"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/Equatable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/SQ","doc:\/\/com.salesforce.SMIMultimediaCommon\/SH","doc:\/\/com.salesforce.SMIMultimediaCommon\/SY","doc:\/\/com.salesforce.SMIMultimediaCommon\/s8SendableP","doc:\/\/com.salesforce.SMIMultimediaCommon\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaConnectionState","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"Possible-Values","text":"Possible Values","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/initial","type":"reference"},{"text":" - The session has been created but no connection attempt has been made","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnected","type":"reference"},{"text":" - The session is not connected","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connecting","type":"reference"},{"text":" - A connection attempt is in progress","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connected","type":"reference"},{"text":" - The session is actively connected","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnecting","type":"reference"},{"text":" - A disconnection is in progress","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/ended","type":"reference"},{"text":" - The session has ended and cannot be reconnected","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"Use this enum to observe the lifecycle of a multimedia session connection.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"An enum that defines the possible connection states of a multimedia session."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/SH"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/ended":{"role":"symbol","type":"topic","title":"ended","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/ended","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState","text":"MultimediaConnectionState","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateEnded","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/ended","abstract":[{"type":"text","text":"The session has ended and cannot be reconnected."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/connecting":{"role":"symbol","type":"topic","title":"connecting","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connecting","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateConnecting","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/connecting","abstract":[{"type":"text","text":"A connection attempt is in progress."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/Equatable-Implementations","url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/equatable-implementations","abstract":[]},"doc://com.salesforce.SMIMultimediaCommon/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/SY"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/initial":{"role":"symbol","type":"topic","title":"initial","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/initial","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initial","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateInitial","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/initial","abstract":[{"type":"text","text":"The session has been created but no connection attempt has been made."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState":{"title":"MultimediaConnectionState","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate","kind":"symbol","navigatorTitle":[{"text":"MultimediaConnectionState","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaConnectionState","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible connection states of a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/SQ","type":"unresolvable"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/disconnecting":{"role":"symbol","type":"topic","title":"disconnecting","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnecting","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnecting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateDisconnecting","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/disconnecting","abstract":[{"type":"text","text":"A disconnection is in progress."}]},"doc://com.salesforce.SMIMultimediaCommon/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/s8SendableP","type":"unresolvable"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/Modality":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/Modality","title":"Modality","type":"topic","url":"\/documentation\/smimultimediacommon\/modality","kind":"symbol","navigatorTitle":[{"text":"Modality","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modality","kind":"identifier"}],"abstract":[{"text":"An enum that defines the supported conversation modalities.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/init(rawValue:)":{"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/connected":{"role":"symbol","type":"topic","title":"connected","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/connected","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateConnected","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/connected","abstract":[{"type":"text","text":"The session is actively connected."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceProvider":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoiceProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"VoiceProvider","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","abstract":[{"type":"text","text":"An enum describing the supported Voice capability providers."}],"title":"VoiceProvider","url":"\/documentation\/smimultimediacommon\/voiceprovider"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState/disconnected":{"role":"symbol","type":"topic","title":"disconnected","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState\/disconnected","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState"}],"navigatorTitle":[{"text":"SMIMultimediaConnectionStateDisconnected","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate\/disconnected","abstract":[{"type":"text","text":"The session is not connected."}]},"doc://com.salesforce.SMIMultimediaCommon/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/s16SendableMetatypeP","type":"unresolvable"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaErrorCode":{"title":"MultimediaErrorCode","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode","url":"\/documentation\/smimultimediacommon\/multimediaerrorcode","kind":"symbol","navigatorTitle":[{"text":"MultimediaErrorCode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaErrorCode"}],"abstract":[{"text":"An enum that defines the categories of errors that can occur within the multimedia client.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIMultimediaConnectionState","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"anchor":"Enums","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/Modality","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceProvider","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaErrorCode"],"title":"Enums"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SMIMultimediaConnectionState"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIMultimediaConnectionStateEnded","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1ended\/title"},{"value":[{"kind":"identifier","text":"SMIMultimediaConnectionStateEnded"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1ended\/fragments"},{"value":"SMIMultimediaConnectionStateConnecting","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connecting\/title"},{"value":[{"kind":"identifier","text":"SMIMultimediaConnectionStateConnecting"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connecting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1initial\/title","value":"SMIMultimediaConnectionStateInitial"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1initial\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaConnectionStateInitial"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/title","value":"SMIMultimediaConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/fragments","value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}]},{"op":"replace","value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1disconnecting\/title","value":"SMIMultimediaConnectionStateDisconnecting"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionStateDisconnecting","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1disconnecting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/title","value":"SMIModality"},{"op":"replace","value":[{"text":"SMIModality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1Modality\/navigatorTitle","value":[{"kind":"identifier","text":"SMIModality"}]},{"op":"replace","value":"SMIMultimediaConnectionStateConnected","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connected\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionStateConnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1connected\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/title","value":"SMIVoiceProvider"},{"op":"replace","value":[{"text":"SMIVoiceProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceProvider\/navigatorTitle","value":[{"kind":"identifier","text":"SMIVoiceProvider"}]},{"op":"replace","value":"SMIMultimediaConnectionStateDisconnected","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1disconnected\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConnectionStateDisconnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState~1disconnected\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/title","value":"SMIMultimediaErrorCode"},{"op":"replace","value":[{"text":"SMIMultimediaErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaErrorCode"}]}]}]}