{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/init(_:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/session","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/wrappedClient"],"generated":true},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/sdkVersion"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/MultimediaClientDelegate-Implementations","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/ObservableObject-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaclient"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient"},"metadata":{"navigatorTitle":[{"text":"MultimediaClient","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClient","kind":"identifier"}],"title":"MultimediaClient","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"s:19SMIMultimediaCommon16MultimediaClientC"},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession"]},{"title":"Observable Wrappers","anchor":"Observable-Wrappers","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant"],"generated":true}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/7Combine16ObservableObjectP","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate","doc:\/\/com.salesforce.SMIMultimediaCommon\/s8CopyableP"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClient","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservableObject"},{"type":"text","text":" wrapper around "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","isActive":true},{"type":"text","text":" that publishes session changes for use in SwiftUI views."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/init(_:)":{"role":"symbol","type":"topic","title":"init(_:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultimediaClientProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":"?)","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediaclient\/init(_:)","abstract":[{"text":"Creates a new observable client wrapping the given ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/MultimediaClientDelegate-Implementations":{"role":"collectionGroup","type":"topic","title":"MultimediaClientDelegate Implementations","kind":"article","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/MultimediaClientDelegate-Implementations","url":"\/documentation\/smimultimediacommon\/multimediaclient\/multimediaclientdelegate-implementations","abstract":[]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/wrappedClient":{"role":"symbol","type":"topic","title":"wrappedClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/wrappedClient","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrappedClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":"?","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediaclient\/wrappedclient","abstract":[{"text":"The underlying ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/7Combine16ObservableObjectP":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/7Combine16ObservableObjectP","type":"unresolvable","title":"Combine.ObservableObject"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient":{"navigatorTitle":[{"text":"MultimediaClient","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaclient","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClient","kind":"identifier"}],"title":"MultimediaClient","kind":"symbol","type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"ObservableObject","type":"codeVoice"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"reference","isActive":true},{"text":" that publishes session changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientDelegate":{"title":"MultimediaClientDelegate","type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientDelegate","url":"\/documentation\/smimultimediacommon\/multimediaclientdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultimediaClientDelegate"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaClientDelegate"}],"abstract":[{"type":"text","text":"A delegate protocol for receiving events from a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"},{"type":"text","text":" instance."}]},"doc://com.salesforce.SMIMultimediaCommon/s8CopyableP":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipant":{"role":"symbol","type":"topic","title":"MultimediaParticipant","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipant","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipant","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaParticipant","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaparticipant","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservableObject"},{"type":"text","text":" wrapper around "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"},{"type":"text","text":" that publishes participant state for use in SwiftUI views."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/sdkVersion":{"title":"sdkVersion","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/sdkVersion","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclient\/sdkversion","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The version of the multimedia SDK bundle, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if unavailable."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSession":{"url":"\/documentation\/smimultimediacommon\/multimediasession","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSession","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MultimediaSession","navigatorTitle":[{"kind":"identifier","text":"MultimediaSession"}],"abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservableObject"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference","isActive":true},{"text":" that publishes session state changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/ObservableObject-Implementations":{"role":"collectionGroup","url":"\/documentation\/smimultimediacommon\/multimediaclient\/observableobject-implementations","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/ObservableObject-Implementations","title":"ObservableObject Implementations","kind":"article","type":"topic","abstract":[]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/session":{"role":"symbol","type":"topic","title":"session","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/session","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaSession","kind":"typeIdentifier","preciseIdentifier":"s:19SMIMultimediaCommon17MultimediaSessionC"}],"url":"\/documentation\/smimultimediacommon\/multimediaclient\/session","abstract":[{"type":"text","text":"The current "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSession","isActive":true},{"type":"text","text":" observable wrapper."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SMIMultimediaClient","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle"},{"op":"replace","value":"SMIMultimediaParticipant","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle"},{"op":"replace","value":"SMIMultimediaSession","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle"},{"op":"replace","value":"SMIMultimediaClientDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/title"},{"op":"replace","value":[{"text":"SMIMultimediaClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientDelegate\/navigatorTitle"}]}]}