{"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"]},{"anchor":"Configuration","title":"Configuration","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"],"generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaConfiguration","symbolKind":"protocol","modules":[{"name":"SMIMultimediaCommon"}],"title":"MultimediaConfigurationProtocol","navigatorTitle":[{"text":"MultimediaConfigurationProtocol","kind":"identifier"}],"roleHeading":"Protocol"},"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol\/displayName"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"],"type":"conformingTypes"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SMIMultimediaConfiguration) "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MultimediaConfigurationProtocol","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A protocol that defines the configuration options for a multimedia client."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfiguration"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfiguration"}],"title":"MultimediaConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol"},{"type":"text","text":" that stores configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfigurationProtocol":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"title":"MultimediaConfigurationProtocol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfigurationProtocol/displayName":{"role":"symbol","required":true,"type":"topic","title":"displayName","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol\/displayName","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol\/displayname","abstract":[{"text":"The display name for the local participant in a multimedia session.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIMultimediaConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol\/displayName"],"title":"Instance Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"],"type":"conformingTypes","title":"Conforming Types"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"],"title":"Related Documentation"},{"anchor":"Configuration","title":"Configuration","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIMultimediaConfiguration"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIMultimediaConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/title"},{"value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SMIMultimediaConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/navigatorTitle"},{"value":"SMIMultimediaConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/navigatorTitle"},{"op":"replace","value":"displayName","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol~1displayName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"displayName"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol~1displayName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}