{"metadata":{"symbolKind":"protocol","modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSessionProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","title":"MultimediaSessionProtocol","roleHeading":"Protocol"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDate","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDetails","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/conversationId","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/displayName","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/identifier","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/isMicrophoneMuted","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/localParticipant","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remoteParticipants","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/state"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/add(delegate:queue:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/audioInput(enable:completion:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/join(completion:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/leave(_:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/muteMicrophone(completion:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remove(delegate:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/unmuteMicrophone(completion:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaExtensionProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"],"anchor":"Lifecycle","generated":true,"title":"Lifecycle"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SMIMultimediaSession) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaSessionProtocol"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this protocol to join and leave voice sessions, manage participants, and control microphone state."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediasessionprotocol"]},{"paths":["\/documentation\/smimultimediacommon\/multimediasessionprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/identifier":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/identifier","abstract":[{"type":"text","text":"The unique identifier for this session."}],"title":"identifier","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/identifier"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/state":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIMultimediaConnectionState.h@T@SMIMultimediaConnectionState","text":"MultimediaConnectionState","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"state","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/state","abstract":[{"text":"The current ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","type":"reference","isActive":true},{"text":" of the session.","type":"text"}],"title":"state","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/state"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/displayName":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"displayName"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/displayName","abstract":[{"text":"The display name of the session.","type":"text"},{"type":"text","text":" "},{"text":"This is determined at session creation time based on the configuration name or the name provided during creation.","type":"text"}],"title":"displayName","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/displayname"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/connectionDetails":{"role":"symbol","required":true,"type":"topic","title":"connectionDetails","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDetails","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractVoiceConnection"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"connectionDetails","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/connectiondetails","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","isActive":true,"type":"reference"},{"text":" containing the connection credentials for this session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/audioInput(enable:completion:)":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioInput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enable","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"audioInputWithEnable:completion:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/audioInput(enable:completion:)","abstract":[{"text":"Enables or disables the local participant’s microphone audio input.","type":"text"}],"title":"audioInput(enable:completion:)","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/audioinput(enable:completion:)"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaExtensionProtocol":{"role":"symbol","type":"topic","title":"MultimediaExtensionProtocol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaExtensionProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaExtensionProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaExtensionProtocol","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediaextensionprotocol","abstract":[{"type":"text","text":"A protocol that provides a factory for creating multimedia client instances."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/remove(delegate:)":{"role":"symbol","required":true,"type":"topic","title":"remove(delegate:)","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remove(delegate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultimediaSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSessionDelegate"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeWithDelegate:","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/remove(delegate:)","abstract":[{"type":"text","text":"Removes a previously registered delegate."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/muteMicrophone(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muteMicrophone"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/mutemicrophone(completion:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/muteMicrophone(completion:)","abstract":[{"text":"Mutes the local participant’s microphone.","type":"text"}],"type":"topic","title":"muteMicrophone(completion:)","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/add(delegate:queue:)":{"role":"symbol","required":true,"type":"topic","title":"add(delegate:queue:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/add(delegate:queue:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"MultimediaSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSessionDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"addWithDelegate:queue:","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/add(delegate:queue:)","abstract":[{"type":"text","text":"Registers a delegate to receive session events."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/unmuteMicrophone(completion:)":{"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/unmutemicrophone(completion:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/unmuteMicrophone(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmuteMicrophone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"unmuteMicrophone(completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Unmutes the local participant’s microphone.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/conversationId":{"role":"symbol","required":true,"type":"topic","title":"conversationId","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/conversationId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"}],"navigatorTitle":[{"text":"conversationId","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/conversationid","abstract":[{"type":"text","text":"The identifier of the conversation associated with this session."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection":{"navigatorTitle":[{"text":"AbstractVoiceConnection","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"identifier"}],"title":"AbstractVoiceConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an abstract voice connection and identifies the voice provider."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConnectionState":{"title":"MultimediaConnectionState","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConnectionState","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaconnectionstate","kind":"symbol","navigatorTitle":[{"text":"MultimediaConnectionState","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaConnectionState","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible connection states of a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/isMicrophoneMuted":{"role":"symbol","required":true,"type":"topic","title":"isMicrophoneMuted","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/isMicrophoneMuted","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isMicrophoneMuted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isMicrophoneMuted","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/ismicrophonemuted","abstract":[{"type":"text","text":"Whether the local participant’s microphone is currently muted."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/remoteParticipants":{"role":"symbol","required":true,"type":"topic","title":"remoteParticipants","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remoteParticipants","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteParticipants","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"remoteParticipants","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/remoteparticipants","abstract":[{"text":"The remote participants currently in the session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionDelegate":{"role":"symbol","type":"topic","title":"MultimediaSessionDelegate","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSessionDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaSessionDelegate","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessiondelegate","abstract":[{"type":"text","text":"A delegate protocol for receiving events from a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true},{"type":"text","text":" instance."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/join(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"joinWithCompletion:"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/join(completion:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/join(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"join(completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Joins an active voice session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/localParticipant":{"role":"symbol","required":true,"type":"topic","title":"localParticipant","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/localParticipant","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localParticipant","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant"}],"navigatorTitle":[{"text":"localParticipant","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/localparticipant","abstract":[{"text":"The local participant in the session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/connectionDate":{"navigatorTitle":[{"text":"connectionDate","kind":"identifier"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/connectiondate","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"title":"connectionDate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The date of the last successful call connection."},{"type":"text","text":" "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if not currently connected to a call."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol/leave(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leave","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol\/leave(_:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/leave(_:)","abstract":[{"type":"text","text":"Leaves the current voice session."}],"type":"topic","title":"leave(_:)","kind":"symbol","navigatorTitle":[{"text":"leave:","kind":"identifier"}],"required":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIMultimediaSession","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDate","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/connectionDetails","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/conversationId","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/displayName","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/identifier","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/isMicrophoneMuted","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/localParticipant","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remoteParticipants","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/state"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/add(delegate:queue:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/audioInput(enable:completion:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/join(completion:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/leave(_:)","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol\/remove(delegate:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaExtensionProtocol","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol"],"anchor":"Lifecycle","generated":true,"title":"Lifecycle"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIMultimediaSession","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"identifier","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1identifier\/title","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1identifier\/fragments","op":"replace"},{"value":"state","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1state\/title","op":"replace"},{"value":[{"text":"state","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1state\/fragments","op":"replace"},{"value":"displayName","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1displayName\/title","op":"replace"},{"value":[{"text":"displayName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1displayName\/fragments","op":"replace"},{"value":"connectionDetails","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1connectionDetails\/title","op":"replace"},{"value":[{"text":"connectionDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1connectionDetails\/fragments","op":"replace"},{"value":"audioInputWithEnable:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1audioInput(enable:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"audioInputWithEnable:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1audioInput(enable:completion:)\/fragments","op":"replace"},{"value":"SMIMultimediaExtension","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaExtensionProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaExtension","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaExtensionProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaExtension","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaExtensionProtocol\/navigatorTitle","op":"replace"},{"value":"removeWithDelegate:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1remove(delegate:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeWithDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1remove(delegate:)\/fragments","op":"replace"},{"value":"SMIMultimediaParticipant","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","op":"replace"},{"value":"addWithDelegate:queue:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1add(delegate:queue:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addWithDelegate:queue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1add(delegate:queue:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1conversationId\/title","value":"conversationId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1conversationId\/fragments","value":[{"text":"conversationId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title","value":"SMIMultimediaClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments","value":[{"text":"SMIMultimediaClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle","value":[{"text":"SMIMultimediaClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/title","value":"SMIAbstractVoiceConnection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/fragments","value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/navigatorTitle","value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/title","value":"SMIMultimediaConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/fragments","value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}]},{"value":[{"text":"SMIMultimediaConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConnectionState\/navigatorTitle","op":"replace"},{"value":"SMIMultimediaSession","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1isMicrophoneMuted\/title","value":"isMicrophoneMuted","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1isMicrophoneMuted\/fragments","value":[{"text":"isMicrophoneMuted","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1remoteParticipants\/title","value":"remoteParticipants","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1remoteParticipants\/fragments","value":[{"text":"remoteParticipants","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/title","value":"SMIMultimediaSessionDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/fragments","value":[{"text":"SMIMultimediaSessionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/navigatorTitle","value":[{"text":"SMIMultimediaSessionDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1join(completion:)\/title","value":"joinWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1join(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joinWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1localParticipant\/title","value":"localParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1localParticipant\/fragments","value":[{"text":"localParticipant","kind":"identifier"}]},{"value":"connectionDate","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1connectionDate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"connectionDate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1connectionDate\/fragments","op":"replace"},{"value":"leave:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1leave(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"leave:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol~1leave(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}