{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/audioStream","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/identifier","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/origin"],"generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaParticipantProtocol"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaParticipantProtocol"}],"title":"MultimediaParticipantProtocol","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant"},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol"]},{"title":"Participants","anchor":"Participants","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin"],"generated":true}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SMIMultimediaParticipant) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaParticipantProtocol"}]}]}],"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol/origin":{"navigatorTitle":[{"kind":"identifier","text":"origin"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/origin","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultimediaParticipantOrigin","preciseIdentifier":"c:@M@SMIMultimediaCommon@E@SMIVoiceParticipantOrigin"}],"title":"origin","kind":"symbol","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","isActive":true},{"text":" indicating whether this participant is local or remote.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AudioStreamProtocol":{"role":"symbol","type":"topic","title":"AudioStreamProtocol","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioStreamProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"AudioStreamProtocol","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/audiostreamprotocol","abstract":[{"type":"text","text":"A protocol that represents a collection of audio tracks associated with a participant."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantOrigin":{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","title":"MultimediaParticipantOrigin","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantorigin","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantOrigin","kind":"identifier"}],"abstract":[{"text":"An enum that identifies the origin of a participant in a multimedia session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol/identifier":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/identifier","abstract":[{"type":"text","text":"The unique identifier for this participant."}],"title":"identifier","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/identifier"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol/audioStream":{"navigatorTitle":[{"kind":"identifier","text":"audioStream"}],"required":true,"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/audiostream","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/audioStream","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audioStream","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioStreamProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAudioStream"}],"title":"audioStream","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol","isActive":true},{"type":"text","text":" associated with this participant’s audio."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SMIMultimediaParticipant"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/audioStream","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/identifier","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/origin"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AudioStreamProtocol"]},{"anchor":"Participants","title":"Participants","generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantOrigin"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIMultimediaParticipant","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1origin\/title","value":"origin"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1origin\/fragments","value":[{"kind":"identifier","text":"origin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","value":"SMIMultimediaParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIMultimediaParticipant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/title","value":"SMIAudioStream"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/fragments","value":[{"kind":"identifier","text":"SMIAudioStream"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AudioStreamProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAudioStream"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/title","value":"SMIVoiceParticipantOrigin"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/fragments","value":[{"kind":"identifier","text":"SMIVoiceParticipantOrigin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantOrigin\/navigatorTitle","value":[{"kind":"identifier","text":"SMIVoiceParticipantOrigin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1audioStream\/title","value":"audioStream"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1audioStream\/fragments","value":[{"kind":"identifier","text":"audioStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}