{"sections":[],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection\/voiceConnection"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SMIVoiceModalityConnection) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoiceModalityConnection","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AbstractModalityConnection","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/voicemodalityconnection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/voicemodalityconnection"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection"},"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VoiceModalityConnection","kind":"identifier"}],"symbolKind":"protocol","externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIVoiceModalityConnection","modules":[{"name":"SMIMultimediaCommon"}],"title":"VoiceModalityConnection","navigatorTitle":[{"text":"VoiceModalityConnection","kind":"identifier"}],"roleHeading":"Protocol"},"abstract":[{"type":"text","text":"A protocol that represents a voice-specific modality connection."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject"],"type":"inheritsFrom"}],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"]},{"title":"Connection Models","anchor":"Connection-Models","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/LiveKitVoiceConnection":{"url":"\/documentation\/smimultimediacommon\/livekitvoiceconnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveKitVoiceConnection","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LiveKitVoiceConnection"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection","abstract":[{"text":"A protocol that represents a LiveKit voice connection and provides the credentials needed to join a room.","type":"text"}],"title":"LiveKitVoiceConnection","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceModalityConnection/voiceConnection":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voiceConnection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractVoiceConnection","text":"AbstractVoiceConnection","kind":"typeIdentifier"}],"url":"\/documentation\/smimultimediacommon\/voicemodalityconnection\/voiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection\/voiceConnection","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","isActive":true,"type":"reference"},{"text":" associated with this modality.","type":"text"}],"type":"topic","title":"voiceConnection","kind":"symbol","navigatorTitle":[{"text":"voiceConnection","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractVoiceConnection":{"navigatorTitle":[{"text":"AbstractVoiceConnection","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/abstractvoiceconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractVoiceConnection","kind":"identifier"}],"title":"AbstractVoiceConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an abstract voice connection and identifies the voice provider."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/AbstractModalityConnection":{"role":"symbol","type":"topic","title":"AbstractModalityConnection","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractModalityConnection"}],"navigatorTitle":[{"kind":"identifier","text":"AbstractModalityConnection"}],"url":"\/documentation\/smimultimediacommon\/abstractmodalityconnection","abstract":[{"type":"text","text":"A protocol that represents a connection to a conversation modality."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/VoiceModalityConnection":{"navigatorTitle":[{"kind":"identifier","text":"VoiceModalityConnection"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/voicemodalityconnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VoiceModalityConnection"}],"title":"VoiceModalityConnection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a voice-specific modality connection."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SMIVoiceModalityConnection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SMIVoiceModalityConnection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/VoiceModalityConnection\/voiceConnection"],"anchor":"Instance-Properties","title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection"],"anchor":"Related-Documentation","title":"Related Documentation"},{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractVoiceConnection","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/LiveKitVoiceConnection"],"anchor":"Connection-Models","title":"Connection Models"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIVoiceModalityConnection"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"SMIAbstractModalityConnection","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/AbstractModalityConnection"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/title","op":"replace","value":"SMILiveKitVoiceConnection"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILiveKitVoiceConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1LiveKitVoiceConnection\/navigatorTitle","value":[{"kind":"identifier","text":"SMILiveKitVoiceConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection~1voiceConnection\/title","value":"voiceConnection"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection~1voiceConnection\/fragments","value":[{"kind":"identifier","text":"voiceConnection"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/title","value":"SMIAbstractVoiceConnection"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/fragments","value":[{"text":"SMIAbstractVoiceConnection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractVoiceConnection\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAbstractVoiceConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/title","value":"SMIAbstractModalityConnection"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/fragments","value":[{"kind":"identifier","text":"SMIAbstractModalityConnection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1AbstractModalityConnection\/navigatorTitle","value":[{"text":"SMIAbstractModalityConnection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/title","value":"SMIVoiceModalityConnection","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/fragments","value":[{"kind":"identifier","text":"SMIVoiceModalityConnection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1VoiceModalityConnection\/navigatorTitle","value":[{"kind":"identifier","text":"SMIVoiceModalityConnection"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}