{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"kind":"article","variants":[{"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","title":"ModalityTransitionType","navigatorTitle":[{"text":"ModalityTransitionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/!=(_:_:)":{"abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/modalitytransitiontype\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/title","value":"SMIModalityTransitionType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/fragments","value":[{"kind":"identifier","text":"SMIModalityTransitionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/navigatorTitle","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}],"op":"replace"}]}]}