{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/modalityNotSupported","interfaceLanguage":"swift"},"abstract":[{"text":"The transition was rejected because the conversation does not currently support the requested Modality.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/modalitynotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/modalitynotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modalityNotSupported","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","text":"ModalityTransitionType","kind":"typeIdentifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType"]]},"metadata":{"navigatorTitle":[{"text":"SMIModalityTransitionTypeModalityNotSupported","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"modalityNotSupported","roleHeading":"Type Property","symbolKind":"property","externalID":"c:@SMIModalityTransitionTypeModalityNotSupported","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalityNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","text":"ModalityTransitionType"}],"extendedModule":"SMIClientCore","role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","title":"ModalityTransitionType","navigatorTitle":[{"text":"ModalityTransitionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/modalityNotSupported":{"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/modalitynotsupported","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/modalityNotSupported","abstract":[{"text":"The transition was rejected because the conversation does not currently support the requested Modality.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modalityNotSupported","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","kind":"typeIdentifier","text":"ModalityTransitionType"}],"type":"topic","title":"modalityNotSupported"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIModalityTransitionTypeModalityNotSupported","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","text":"SMIModalityTransitionType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/title","value":"SMIModalityTransitionType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/fragments","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIModalityTransitionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1modalityNotSupported\/title","value":"SMIModalityTransitionTypeModalityNotSupported","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1modalityNotSupported\/fragments","value":[{"kind":"identifier","text":"SMIModalityTransitionTypeModalityNotSupported"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}