{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/standard"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIModalityTransitionTypeStandard"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","text":"ModalityTransitionType"}],"externalID":"c:@SMIModalityTransitionTypeStandard","modules":[{"name":"SMIClientCore"}],"title":"standard","extendedModule":"SMIClientCore"},"sections":[],"abstract":[{"type":"text","text":"Standard direct transition."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","text":"ModalityTransitionType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/standard"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/standard"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","title":"ModalityTransitionType","navigatorTitle":[{"text":"ModalityTransitionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/standard":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}],"abstract":[{"type":"text","text":"Standard direct transition."}],"navigatorTitle":[{"text":"SMIModalityTransitionTypeStandard","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/standard","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/standard","title":"standard"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIModalityTransitionTypeStandard","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIModalityTransitionTypeStandard","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","kind":"typeIdentifier","text":"SMIModalityTransitionType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIModalityTransitionTypeStandard"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/title","value":"SMIModalityTransitionType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/fragments","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/navigatorTitle","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1standard\/title","value":"SMIModalityTransitionTypeStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1standard\/fragments","value":[{"kind":"identifier","text":"SMIModalityTransitionTypeStandard"}]}]}]}