{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/transitionfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/modalitytransitiontype\/transitionfailed"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@SMIModalityTransitionTypeTransitionFailed","role":"symbol","title":"transitionFailed","extendedModule":"SMIClientCore","roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ModalityTransitionType","kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/transitionFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ModalityTransitionType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The transition experienced an error and had to abort.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType","title":"ModalityTransitionType","navigatorTitle":[{"text":"ModalityTransitionType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum indicating the type\/nature of modality transition."}],"type":"topic","url":"\/documentation\/smiclientcore\/modalitytransitiontype","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityTransitionType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityTransitionType/transitionFailed":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ModalityTransitionType","kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType"}],"url":"\/documentation\/smiclientcore\/modalitytransitiontype\/transitionfailed","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}],"abstract":[{"type":"text","text":"The transition experienced an error and had to abort."}],"title":"transitionFailed","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType\/transitionFailed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMIModalityTransitionTypeTransitionFailed"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIModalityTransitionType","kind":"typeIdentifier","preciseIdentifier":"c:SMIModalityTransitionType.h@T@SMIModalityTransitionType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityTransitionType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/title","op":"replace","value":"SMIModalityTransitionType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/fragments","op":"replace","value":[{"text":"SMIModalityTransitionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIModalityTransitionType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1transitionFailed\/title","op":"replace","value":"SMIModalityTransitionTypeTransitionFailed"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityTransitionType~1transitionFailed\/fragments","op":"replace","value":[{"text":"SMIModalityTransitionTypeTransitionFailed","kind":"identifier"}]}]}]}