{"metadata":{"navigatorTitle":[{"text":"closeConversationWithIdentifier:completion:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)SMICoreClient(im)closeConversationWithIdentifier:completion:","role":"symbol","required":true,"title":"closeConversation(withIdentifier:completion:)","modules":[{"name":"SMIClientCore"}],"symbolKind":"method","platforms":[{"introducedAt":"6.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"6.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"6.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/closeConversation(withIdentifier:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"closeConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The unique identifier of the conversation to close.","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"inlineContent":[{"type":"text","text":"Returns the result of the operation. If error is nil, the request is successful."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"abstract":[{"text":"Closes the conversation identified by the given identifier.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/coreclient\/closeconversation(withidentifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coreclient\/closeconversation(withidentifier:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CloseConversationCompletion":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationCompletion","abstract":[{"type":"text","text":"The completion block for returning the error result from the closeConversation call."}],"url":"\/documentation\/smiclientcore\/closeconversationcompletion","kind":"symbol","title":"CloseConversationCompletion","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationCompletion","kind":"identifier"}],"navigatorTitle":[{"text":"CloseConversationCompletion","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/closeConversation(withIdentifier:completion:)":{"url":"\/documentation\/smiclientcore\/coreclient\/closeconversation(withidentifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"closeConversation(withIdentifier:completion:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/closeConversation(withIdentifier:completion:)","kind":"symbol","type":"topic","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"closeConversationWithIdentifier:completion:"}],"abstract":[{"text":"Closes the conversation identified by the given identifier.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"closeConversationWithIdentifier:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeConversationWithIdentifier:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"closeConversationWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:SMIAPICompletions.h@T@SMICloseConversationCompletion","text":"SMICloseConversationCompletion","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the conversation to close.","type":"text"}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Returns the result of the operation. If error is nil, the request is successful.","type":"text"}]}],"name":"completion"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/title","value":"SMICloseConversationCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/fragments","value":[{"text":"SMICloseConversationCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationCompletion\/navigatorTitle","value":[{"text":"SMICloseConversationCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1closeConversation(withIdentifier:completion:)\/title","value":"closeConversationWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1closeConversation(withIdentifier:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"closeConversationWithIdentifier:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}