{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:sortedByActivityDirection:completion:)"},"abstract":[{"text":"Retrieves n number of conversations from offline cached data sorted by latest activity. This only returns an order based on offline cached data, and","type":"text"},{"text":" ","type":"text"},{"text":"may not reflect the real-time state of conversations if the client has not retrieved that activity.","type":"text"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sortedByActivityDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIConversationQueryCompletion"},{"kind":"text","text":")"}],"title":"conversations(withLimit:sortedByActivityDirection:completion:)","roleHeading":"Instance Method","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"conversationsWithLimit:sortedByActivityDirection:completion:"}],"externalID":"c:objc(pl)SMICoreClient(im)conversationsWithLimit:sortedByActivityDirection:completion:","modules":[{"name":"SMIClientCore"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sortedByActivityDirection","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"direction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationQueryCompletion","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIConversationQueryCompletion"},{"text":")","kind":"text"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sortedByActivityDirection","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"direction","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","text":"ListAPIDirections","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","text":"Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"limit","content":[{"inlineContent":[{"text":"The maximum number of conversations to return in the query.","type":"text"}],"type":"paragraph"}]},{"name":"direction","content":[{"inlineContent":[{"type":"text","text":"The direction based on last activity. Default value is "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion that contains the result of the search query."}]}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:sortedbyactivitydirection:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:sortedbyactivitydirection:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections":{"navigatorTitle":[{"kind":"identifier","text":"ListAPIDirections"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ListAPIDirections"}],"abstract":[{"type":"text","text":"An enum that defines the ordering direction for list-based API requests."}],"type":"topic","kind":"symbol","title":"ListAPIDirections","url":"\/documentation\/smiclientcore\/listapidirections","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationQueryCompletion":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationQueryCompletion"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationQueryCompletion"}],"abstract":[{"text":"The completion block for returning all conversations stored in the database.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationQueryCompletion","kind":"symbol","title":"ConversationQueryCompletion","type":"topic","url":"\/documentation\/smiclientcore\/conversationquerycompletion"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ListAPIDirections/descending":{"role":"symbol","title":"descending","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending","url":"\/documentation\/smiclientcore\/listapidirections\/descending","abstract":[{"type":"text","text":"Orders list items from newest to oldest."},{"type":"text","text":" "},{"type":"text","text":"Used when you want to retrieve items in reverse chronological order."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descending","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ListAPIDirections","kind":"typeIdentifier","preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections"}],"type":"topic","navigatorTitle":[{"text":"SMIListAPIDirectionsDescending","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"type":"text","text":" instance using the "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"type":"text","text":" class."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"type":"topic","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}],"title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversations(withLimit:sortedByActivityDirection:completion:)":{"kind":"symbol","navigatorTitle":[{"text":"conversationsWithLimit:sortedByActivityDirection:completion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sortedByActivityDirection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIListAPIDirections.h@T@SMIListAPIDirections","text":"ListAPIDirections","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIConversationQueryCompletion","text":"ConversationQueryCompletion","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:sortedByActivityDirection:completion:)","role":"symbol","required":true,"title":"conversations(withLimit:sortedByActivityDirection:completion:)","abstract":[{"type":"text","text":"Retrieves n number of conversations from offline cached data sorted by latest activity. This only returns an order based on offline cached data, and"},{"type":"text","text":" "},{"type":"text","text":"may not reflect the real-time state of conversations if the client has not retrieved that activity."}],"url":"\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:sortedbyactivitydirection:completion:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"conversationsWithLimit:sortedByActivityDirection:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationsWithLimit:sortedByActivityDirection:completion:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"conversationsWithLimit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"limit"},{"kind":"text","text":" "},{"kind":"identifier","text":"sortedByActivityDirection:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"direction"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(NSArray<id<SMIConversation>> *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of conversations to return in the query."}]}]},{"name":"direction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The direction based on last activity. Default value is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ListAPIDirections\/descending"},{"type":"text","text":"."}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"The completion that contains the result of the search query.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/title","op":"replace","value":"SMIListAPIDirections"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIListAPIDirections"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIListAPIDirections"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/title","op":"replace","value":"SMIConversationQueryCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationQueryCompletion"}]},{"value":[{"text":"SMIConversationQueryCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/navigatorTitle"},{"value":"SMIListAPIDirectionsDescending","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/title"},{"value":[{"text":"SMIListAPIDirectionsDescending","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ListAPIDirections~1descending\/fragments"},{"value":"SMICoreConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"value":"SMIConversation","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title"},{"value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments"},{"value":[{"text":"SMIConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle"},{"value":"conversationsWithLimit:sortedByActivityDirection:completion:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:sortedByActivityDirection:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationsWithLimit:sortedByActivityDirection:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:sortedByActivityDirection:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}