{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:forceRefresh:completion:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:","kind":"identifier"}],"required":true,"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"title":"conversations(withLimit:olderThanConversation:forceRefresh:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanConversation","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","text":"Conversation","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SMICoreClient(im)conversationsWithLimit:olderThanConversation:forceRefresh:completion:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanConversation","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","text":"Conversation","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"([any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","text":"Conversation","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"olderThanConversation","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [any ","kind":"text"},{"text":"Conversation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","preciseIdentifier":"c:objc(pl)SMIConversation","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum number of results to expect.","type":"text"}]}],"name":"limit"},{"content":[{"inlineContent":[{"type":"text","text":"The comparison conversation which serves as a base for returning older conversations. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"the query starts from the newest known conversation."}],"type":"paragraph"}],"name":"olderThanConversation"},{"content":[{"inlineContent":[{"text":"Forces the conversation list to be updated from the network bypassing the local cache.","type":"text"}],"type":"paragraph"}],"name":"forceRefresh"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion that contains the result of the search query.","type":"text"}]}],"name":"completion"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Retrieves conversations available to the local participant."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:olderthanconversation:forcerefresh:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:olderthanconversation:forcerefresh:completion:)"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and provide an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Conversation":{"abstract":[{"text":"A protocol that represents a conversation between participants.","type":"text"}],"role":"symbol","title":"Conversation","url":"\/documentation\/smiclientcore\/conversation","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Conversation","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/conversations(withLimit:olderThanConversation:forceRefresh:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"olderThanConversation","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":")?, ","kind":"text"},{"text":"forceRefresh","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([any ","kind":"text"},{"text":"Conversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversation"},{"text":"]?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/coreclient\/conversations(withlimit:olderthanconversation:forcerefresh:completion:)","abstract":[{"type":"text","text":"Retrieves conversations available to the local participant."}],"navigatorTitle":[{"text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/conversations(withLimit:olderThanConversation:forceRefresh:completion:)","required":true,"type":"topic","kind":"symbol","role":"symbol","title":"conversations(withLimit:olderThanConversation:forceRefresh:completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationQueryCompletion":{"abstract":[{"text":"The completion block for returning all conversations stored in the database.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationQueryCompletion","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationQueryCompletion","navigatorTitle":[{"text":"ConversationQueryCompletion","kind":"identifier"}],"title":"ConversationQueryCompletion","type":"topic","url":"\/documentation\/smiclientcore\/conversationquerycompletion"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"role":"symbol","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","type":"topic","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"type":"text","text":" class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"Configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"conversationsWithLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"olderThanConversation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIConversation>","preciseIdentifier":"c:Qoobjc(pl)SMIConversation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"olderThanConversation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forceRefresh:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"forceRefresh","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationQueryCompletion","preciseIdentifier":"c:SMIQueryCompletions.h@T@SMIConversationQueryCompletion","text":"SMIConversationQueryCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of results to expect."}]}],"name":"limit"},{"content":[{"inlineContent":[{"text":"The comparison conversation which serves as a base for returning older conversations. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"the query starts from the newest known conversation.","type":"text"}],"type":"paragraph"}],"name":"olderThanConversation"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Forces the conversation list to be updated from the network bypassing the local cache.","type":"text"}]}],"name":"forceRefresh"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion that contains the result of the search query."}]}],"name":"completion"}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/title","op":"replace","value":"SMIConversation"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Conversation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversation"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:forceRefresh:completion:)\/title","op":"replace","value":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1conversations(withLimit:olderThanConversation:forceRefresh:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsWithLimit:olderThanConversation:forceRefresh:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/title","op":"replace","value":"SMIConversationQueryCompletion"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/fragments","op":"replace","value":[{"text":"SMIConversationQueryCompletion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationQueryCompletion\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationQueryCompletion","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","op":"replace","value":"SMICoreConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]}]}]}