{"variants":[{"paths":["\/documentation\/smiclientcore\/coreclient\/destroystorage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coreclient\/destroystorage()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"abstract":[{"type":"text","text":"Deletes the In-App Message store."},{"type":"text","text":" "},{"type":"text","text":"This will reset all conversation as well as authorization credentials."},{"type":"text","text":" "},{"type":"text","text":"By default this will also clear all auth credentials."}],"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"destroyStorage:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyStorage"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)SMICoreClient(im)destroyStorage:","title":"destroyStorage()","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"role":"symbol","platforms":[{"unavailable":false,"beta":false,"deprecated":true,"message":"Will be removed in a future version. Use `destroyStorageAndAuthorization:completion:`"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroyStorage","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroyStorage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Completion block that returns with the success or failure of the operation.","type":"text"}]}],"name":"completion"}]}],"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in a future version. Use `destroyStorageAndAuthorization:completion:`","type":"text"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage()"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"role":"symbol","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","type":"topic","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/destroyStorage()":{"required":true,"title":"destroyStorage()","role":"symbol","url":"\/documentation\/smiclientcore\/coreclient\/destroystorage()","abstract":[{"type":"text","text":"Deletes the In-App Message store."},{"type":"text","text":" "},{"type":"text","text":"This will reset all conversation as well as authorization credentials."},{"type":"text","text":" "},{"type":"text","text":"By default this will also clear all auth credentials."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroyStorage","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"deprecated":true,"navigatorTitle":[{"text":"destroyStorage:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/destroyStorage()","kind":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and provide an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/DataOperationCompletion":{"role":"symbol","title":"DataOperationCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataOperationCompletion"}],"kind":"symbol","abstract":[{"type":"text","text":"Completion for data store operations."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataOperationCompletion","navigatorTitle":[{"kind":"identifier","text":"DataOperationCompletion"}],"url":"\/documentation\/smiclientcore\/dataoperationcompletion","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"type":"text","text":" class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"Configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"destroyStorage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyStorage:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"destroyStorage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SMIDataTypes.h@T@SMIDataOperationCompletion","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataOperationCompletion","text":"SMIDataOperationCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion block that returns with the success or failure of the operation."}]}],"name":"completion"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in a future version. Use `destroyStorageAndAuthorization:completion:`","type":"text"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"SMICoreFactory","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title"},{"value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"value":"destroyStorage:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"destroyStorage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1destroyStorage()\/fragments"},{"value":"SMICoreClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"value":"SMIDataOperationCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/title"},{"value":[{"kind":"identifier","text":"SMIDataOperationCompletion"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/fragments"},{"value":[{"text":"SMIDataOperationCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/navigatorTitle"},{"value":"SMICoreConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"}]}]}