{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaClient","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/multimediaClient"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)SMICoreClient(py)multimediaClient","symbolKind":"property","title":"multimediaClient","navigatorTitle":[{"kind":"identifier","text":"multimediaClient"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaClient","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MultimediaClientProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"abstract":[{"text":"The MultiMedia client currently available on the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"text":" This is used to monitor the Multimedia communication when","type":"text"},{"text":" ","type":"text"},{"text":"the conversation is in a supported Modality.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/multimediaclient"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/multimediaclient"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/multimediaClient":{"title":"multimediaClient","required":true,"abstract":[{"text":"The MultiMedia client currently available on the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":" This is used to monitor the Multimedia communication when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the conversation is in a supported Modality."}],"url":"\/documentation\/smiclientcore\/coreclient\/multimediaclient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/multimediaClient","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multimediaClient","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MultimediaClientProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"multimediaClient","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"multimediaClient","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"multimediaClient","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIMultimediaClient>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":" ","kind":"text"},{"text":"multimediaClient","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1multimediaClient\/title","value":"multimediaClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1multimediaClient\/fragments","value":[{"text":"multimediaClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace"},{"value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace"},{"value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}