{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/realtimeconnectionstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/realtimeconnectionstate"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"realtimeConnectionState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","kind":"typeIdentifier","text":"RealtimeConnectionState"}],"title":"realtimeConnectionState","required":true,"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMICoreClient(py)realtimeConnectionState","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"realtimeConnectionState"}]},"abstract":[{"type":"text","text":"Current realtime connection state."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"realtimeConnectionState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RealtimeConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","kind":"symbol","title":"Configuration","url":"\/documentation\/smiclientcore\/configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"This class stores configuration information that is necessary when creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true},{"text":" instance using the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" class.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","title":"CoreClient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreClient"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RealtimeConnectionState":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RealtimeConnectionState","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of the realtime event connection."}],"role":"symbol","title":"RealtimeConnectionState","kind":"symbol","navigatorTitle":[{"text":"RealtimeConnectionState","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/realtimeconnectionstate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"}],"kind":"symbol","title":"CoreFactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/realtimeConnectionState":{"url":"\/documentation\/smiclientcore\/coreclient\/realtimeconnectionstate","title":"realtimeConnectionState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"realtimeConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RealtimeConnectionState","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState"}],"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"realtimeConnectionState"}],"abstract":[{"text":"Current realtime connection state.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"realtimeConnectionState","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"realtimeConnectionState"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"SMIRealtimeConnectionState","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RealtimeConnectionState","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"realtimeConnectionState","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/title","op":"replace","value":"SMIRealtimeConnectionState"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/fragments","op":"replace","value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RealtimeConnectionState\/navigatorTitle","op":"replace","value":[{"text":"SMIRealtimeConnectionState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/title","op":"replace","value":"realtimeConnectionState"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/fragments","op":"replace","value":[{"text":"realtimeConnectionState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}