{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveAgentAvailability","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"((any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","text":"AgentAvailabilityInfo","preciseIdentifier":"c:objc(pl)SMIAgentAvailabilityInfo","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveAgentAvailability"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> any "},{"kind":"typeIdentifier","text":"AgentAvailabilityInfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","preciseIdentifier":"c:objc(pl)SMIAgentAvailabilityInfo"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Contains a reference to an ","type":"text"},{"code":"SMIAgentAvailabilityInfoCompletion","type":"codeVoice"},{"text":" object if successful, or an ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" describing the failure.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Retrieves the agent availability info for the current deployment."}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveAgentAvailability(completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)SMICoreClient(im)retrieveAgentAvailabilityWithCompletion:","navigatorTitle":[{"text":"retrieveAgentAvailabilityWithCompletion:","kind":"identifier"}],"required":true,"symbolKind":"method","title":"retrieveAgentAvailability(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveAgentAvailability","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAgentAvailabilityInfo","text":"AgentAvailabilityInfo","kind":"typeIdentifier"},{"text":")?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/coreclient\/retrieveagentavailability(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coreclient\/retrieveagentavailability(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfoCompletion":{"role":"symbol","title":"AgentAvailabilityInfoCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfoCompletion","kind":"symbol","url":"\/documentation\/smiclientcore\/agentavailabilityinfocompletion","abstract":[{"text":"A completion handler used to deliver the result of an agent availability request.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"AgentAvailabilityInfoCompletion","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfoCompletion","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AgentAvailabilityInfo":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"identifier"}],"navigatorTitle":[{"text":"AgentAvailabilityInfo","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"A protocol that defines the agent availability configuration for a deployment.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/agentavailabilityinfo","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfo","title":"AgentAvailabilityInfo"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","title":"CoreClient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreClient"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/retrieveAgentAvailability(completion:)":{"role":"symbol","title":"retrieveAgentAvailability(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveAgentAvailability","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"AgentAvailabilityInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAgentAvailabilityInfo"},{"text":")?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/coreclient\/retrieveagentavailability(completion:)","kind":"symbol","abstract":[{"text":"Retrieves the agent availability info for the current deployment.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/retrieveAgentAvailability(completion:)","navigatorTitle":[{"text":"retrieveAgentAvailabilityWithCompletion:","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","kind":"symbol","title":"Configuration","url":"\/documentation\/smiclientcore\/configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"This class stores configuration information that is necessary when creating an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true},{"text":" instance using the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" class.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"}],"kind":"symbol","title":"CoreFactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"retrieveAgentAvailabilityWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"retrieveAgentAvailabilityWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"retrieveAgentAvailabilityWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AgentAvailabilityInfoCompletion","preciseIdentifier":"c:SMIAgentAvailabilityInfo.h@T@SMIAgentAvailabilityInfoCompletion","text":"SMIAgentAvailabilityInfoCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Contains a reference to an ","type":"text"},{"code":"SMIAgentAvailabilityInfoCompletion","type":"codeVoice"},{"text":" object if successful, or an ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" describing the failure.","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/title","value":"SMIAgentAvailabilityInfoCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/fragments","value":[{"text":"SMIAgentAvailabilityInfoCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfoCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAgentAvailabilityInfoCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/title","value":"SMIAgentAvailabilityInfo","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/fragments","value":[{"kind":"identifier","text":"SMIAgentAvailabilityInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AgentAvailabilityInfo\/navigatorTitle","value":[{"text":"SMIAgentAvailabilityInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveAgentAvailability(completion:)\/title","value":"retrieveAgentAvailabilityWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1retrieveAgentAvailability(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveAgentAvailabilityWithCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}