{"sections":[],"abstract":[{"text":"Revokes the authorization credentials associated with this configuration and optionally de-registers the device from receiving push notifications.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokeTokenAndDeregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deregisterDevice","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokeTokenAndDeregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"deregisterDevice","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"deregisterDevice","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not to also de-register device from push notifications."}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Returns the result of the operation. If error is nil, the request is successful.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeTokenAndDeregisterDevice(_:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/revoketokenandderegisterdevice(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/revoketokenandderegisterdevice(_:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"kind":"symbol","metadata":{"title":"revokeTokenAndDeregisterDevice(_:completion:)","required":true,"roleHeading":"Instance Method","externalID":"c:objc(pl)SMICoreClient(im)revokeTokenAndDeregisterDevice:completion:","modules":[{"name":"SMIClientCore"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokeTokenAndDeregisterDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"revokeTokenAndDeregisterDevice:completion:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and provide an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"role":"symbol","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","type":"topic","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/revokeTokenAndDeregisterDevice(_:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/revokeTokenAndDeregisterDevice(_:completion:)","url":"\/documentation\/smiclientcore\/coreclient\/revoketokenandderegisterdevice(_:completion:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"revokeTokenAndDeregisterDevice:completion:"}],"title":"revokeTokenAndDeregisterDevice(_:completion:)","abstract":[{"type":"text","text":"Revokes the authorization credentials associated with this configuration and optionally de-registers the device from receiving push notifications."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokeTokenAndDeregisterDevice"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"type":"text","text":" class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"Configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/DataOperationCompletion":{"role":"symbol","title":"DataOperationCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataOperationCompletion"}],"kind":"symbol","abstract":[{"type":"text","text":"Completion for data store operations."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataOperationCompletion","navigatorTitle":[{"kind":"identifier","text":"DataOperationCompletion"}],"url":"\/documentation\/smiclientcore\/dataoperationcompletion","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"revokeTokenAndDeregisterDevice:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revokeTokenAndDeregisterDevice:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"revokeTokenAndDeregisterDevice:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"deregisterDevice"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SMIDataTypes.h@T@SMIDataOperationCompletion","kind":"typeIdentifier","text":"SMIDataOperationCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/DataOperationCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Whether or not to also de-register device from push notifications."}],"type":"paragraph"}],"name":"deregisterDevice"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the result of the operation. If error is nil, the request is successful."}]}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"op":"replace","value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments"},{"op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"op":"replace","value":"revokeTokenAndDeregisterDevice:completion:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeTokenAndDeregisterDevice(_:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"revokeTokenAndDeregisterDevice:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1revokeTokenAndDeregisterDevice(_:completion:)\/fragments"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"op":"replace","value":"SMIDataOperationCompletion","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/title"},{"op":"replace","value":[{"text":"SMIDataOperationCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIDataOperationCompletion"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1DataOperationCompletion\/navigatorTitle"}]}]}