{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/setprechatdelegate(delegate:queue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/setprechatdelegate(delegate:queue:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"abstract":[{"text":"Sets the preChatDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setPreChatDelegate(delegate:queue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreChatDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preChatDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatDelegate","kind":"typeIdentifier","text":"HiddenPreChatDelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The delegate to add.","type":"text"}],"type":"paragraph"}],"name":"preChatDelegate"},{"content":[{"inlineContent":[{"text":"The dispatch queue to listen for events.","type":"text"}],"type":"paragraph"}],"name":"queue"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"externalID":"c:objc(pl)SMICoreClient(im)setPreChatDelegate:queue:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreChatDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"HiddenPreChatDelegate","preciseIdentifier":"c:objc(pl)SMIHiddenPreChatDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t"},{"kind":"text","text":")"}],"required":true,"role":"symbol","title":"setPreChatDelegate(delegate:queue:)","navigatorTitle":[{"kind":"identifier","text":"setPreChatDelegate:queue:"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"type":"text","text":" instance using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"type":"text","text":" class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"Configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"role":"symbol","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","type":"topic","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"and provide an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/HiddenPreChatDelegate":{"abstract":[{"type":"text","text":"Delegate that handles requests for hidden pre-chat values."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/HiddenPreChatDelegate","title":"HiddenPreChatDelegate","url":"\/documentation\/smiclientcore\/hiddenprechatdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HiddenPreChatDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"HiddenPreChatDelegate","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setPreChatDelegate(delegate:queue:)":{"required":true,"url":"\/documentation\/smiclientcore\/coreclient\/setprechatdelegate(delegate:queue:)","role":"symbol","abstract":[{"type":"text","text":"Sets the preChatDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"setPreChatDelegate:queue:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setPreChatDelegate(delegate:queue:)","title":"setPreChatDelegate(delegate:queue:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreChatDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIHiddenPreChatDelegate","text":"HiddenPreChatDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setPreChatDelegate:queue:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreChatDelegate:queue:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPreChatDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIHiddenPreChatDelegate","text":"id<SMIHiddenPreChatDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preChatDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The delegate to add.","type":"text"}],"type":"paragraph"}],"name":"preChatDelegate"},{"content":[{"inlineContent":[{"text":"The dispatch queue to listen for events.","type":"text"}],"type":"paragraph"}],"name":"queue"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"op":"replace","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"op":"replace","value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments"},{"op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"op":"replace","value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"op":"replace","value":"SMIHiddenPreChatDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIHiddenPreChatDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/fragments"},{"op":"replace","value":[{"text":"SMIHiddenPreChatDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1HiddenPreChatDelegate\/navigatorTitle"},{"op":"replace","value":"setPreChatDelegate:queue:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setPreChatDelegate(delegate:queue:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreChatDelegate:queue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setPreChatDelegate(delegate:queue:)\/fragments"}]}]}