{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTemplatedUrlDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate","text":"TemplatedUrlDelegate","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The delegate to add."}],"type":"paragraph"}],"name":"templatedUrlDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The dispatch queue to listen for events."}],"type":"paragraph"}],"name":"queue"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/settemplatedurldelegate(delegate:queue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/settemplatedurldelegate(delegate:queue:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setTemplatedUrlDelegate(delegate:queue:)"},"sections":[],"abstract":[{"type":"text","text":"Sets the templatedUrlDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"metadata":{"role":"symbol","required":true,"externalID":"c:objc(pl)SMICoreClient(im)setTemplatedUrlDelegate:queue:","title":"setTemplatedUrlDelegate(delegate:queue:)","roleHeading":"Instance Method","modules":[{"name":"SMIClientCore"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTemplatedUrlDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setTemplatedUrlDelegate:queue:","kind":"identifier"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setTemplatedUrlDelegate(delegate:queue:)":{"navigatorTitle":[{"text":"setTemplatedUrlDelegate:queue:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient\/settemplatedurldelegate(delegate:queue:)","role":"symbol","kind":"symbol","required":true,"abstract":[{"text":"Sets the templatedUrlDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTemplatedUrlDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"type":"topic","title":"setTemplatedUrlDelegate(delegate:queue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setTemplatedUrlDelegate(delegate:queue:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedUrlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TemplatedUrlDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate","type":"topic","url":"\/documentation\/smiclientcore\/templatedurldelegate","title":"TemplatedUrlDelegate","abstract":[{"text":"Delegate that handles requests for auto-response messaging component parameter values.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setTemplatedUrlDelegate:queue:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTemplatedUrlDelegate:queue:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setTemplatedUrlDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMITemplatedUrlDelegate","text":"id<SMITemplatedUrlDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"templatedUrlDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"queue","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"templatedUrlDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to add."}]}]},{"name":"queue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The dispatch queue to listen for events."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"text":"SMICoreFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setTemplatedUrlDelegate(delegate:queue:)\/title","value":"setTemplatedUrlDelegate:queue:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setTemplatedUrlDelegate(delegate:queue:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setTemplatedUrlDelegate:queue:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/title","value":"SMITemplatedUrlDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/fragments","value":[{"kind":"identifier","text":"SMITemplatedUrlDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SMITemplatedUrlDelegate"}],"op":"replace"}]}]}