{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"metadata":{"externalID":"c:objc(pl)SMICoreClient(im)setUserVerificationDelegate:queue:","roleHeading":"Instance Method","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"setUserVerificationDelegate:queue:","kind":"identifier"}],"symbolKind":"method","required":true,"title":"setUserVerificationDelegate(delegate:queue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserVerificationDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UserVerificationDelegate","preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t"},{"kind":"text","text":")"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Sets the userVerificationDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI."}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setUserVerificationDelegate(delegate:queue:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserVerificationDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"userVerificationDelegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"UserVerificationDelegate","preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"userVerificationDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate to add.","type":"text"}]}]},{"name":"queue","content":[{"inlineContent":[{"type":"text","text":"The dispatch queue to listen for events."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/coreclient\/setuserverificationdelegate(delegate:queue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/coreclient\/setuserverificationdelegate(delegate:queue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerificationDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerificationDelegate"}],"abstract":[{"text":"Delegate that handles requests for user verification.","type":"text"}],"title":"UserVerificationDelegate","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserVerificationDelegate"}],"url":"\/documentation\/smiclientcore\/userverificationdelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/setUserVerificationDelegate(delegate:queue:)":{"role":"symbol","title":"setUserVerificationDelegate(delegate:queue:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserVerificationDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UserVerificationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIUserVerificationDelegate"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setUserVerificationDelegate:queue:"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/setUserVerificationDelegate(delegate:queue:)","url":"\/documentation\/smiclientcore\/coreclient\/setuserverificationdelegate(delegate:queue:)","kind":"symbol","abstract":[{"text":"Sets the userVerificationDelegate while also defining the dispatch queue that events fired to this delegate will be emitted to.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that the main queue is passed to this method if you plan to handle events directly with changes to the UI.","type":"text"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserVerificationDelegate:queue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUserVerificationDelegate:queue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setUserVerificationDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIUserVerificationDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIUserVerificationDelegate"},{"text":") ","kind":"text"},{"text":"userVerificationDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"queue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dispatch_queue_t","preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"queue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to add."}]}],"name":"userVerificationDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The dispatch queue to listen for events."}],"type":"paragraph"}],"name":"queue"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/title","op":"replace","value":"SMIUserVerificationDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIUserVerificationDelegate"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/navigatorTitle","op":"replace","value":[{"text":"SMIUserVerificationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setUserVerificationDelegate(delegate:queue:)\/title","op":"replace","value":"setUserVerificationDelegate:queue:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1setUserVerificationDelegate(delegate:queue:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setUserVerificationDelegate:queue:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","op":"replace","value":"SMICoreConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]}]}]}