{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"metadata":{"roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)SMICoreClient(im)stop","symbolKind":"method","title":"stop()","navigatorTitle":[{"kind":"identifier","text":"stop"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState"],"title":"Related Documentation","anchor":"Related-Documentation"}],"abstract":[{"type":"text","text":"Terminates the connection listening for realtime remote events."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/stop()"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/stop()","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/stop()":{"title":"stop()","required":true,"abstract":[{"type":"text","text":"Terminates the connection listening for realtime remote events."}],"url":"\/documentation\/smiclientcore\/coreclient\/stop()","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/stop()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stop"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/realtimeConnectionState":{"title":"realtimeConnectionState","required":true,"abstract":[{"type":"text","text":"Current realtime connection state."}],"url":"\/documentation\/smiclientcore\/coreclient\/realtimeconnectionstate","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"realtimeConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIRealtimeConnectionState.h@T@SMIRealtimeConnectionState","text":"RealtimeConnectionState"}],"navigatorTitle":[{"kind":"identifier","text":"realtimeConnectionState"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"stop","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stop"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/realtimeConnectionState"],"anchor":"Related-Documentation","title":"Related Documentation"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"value":"stop","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1stop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1stop()\/fragments"},{"op":"replace","value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/title","value":"realtimeConnectionState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1realtimeConnectionState\/fragments","value":[{"kind":"identifier","text":"realtimeConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}