{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"TemplatedUrlDelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMICoreClient(py)templatedUrlDelegate","required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"TemplatedUrlDelegate","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"templatedUrlDelegate","kind":"identifier"}],"title":"templatedUrlDelegate"},"kind":"symbol","abstract":[{"text":"The delegate that provides the auto-response messaging component parameter values.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/templatedUrlDelegate"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/coreclient\/templatedurldelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/coreclient\/templatedurldelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"]]},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedUrlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TemplatedUrlDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate","type":"topic","url":"\/documentation\/smiclientcore\/templatedurldelegate","title":"TemplatedUrlDelegate","abstract":[{"text":"Delegate that handles requests for auto-response messaging component parameter values.","type":"text"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient/templatedUrlDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient\/templatedUrlDelegate","title":"templatedUrlDelegate","required":true,"kind":"symbol","type":"topic","abstract":[{"text":"The delegate that provides the auto-response messaging component parameter values.","type":"text"}],"navigatorTitle":[{"text":"templatedUrlDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient\/templatedurldelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplatedUrlDelegate"},{"text":")?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"templatedUrlDelegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"templatedUrlDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate"],"title":"Related Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMITemplatedUrlDelegate","text":"id<SMITemplatedUrlDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"templatedUrlDelegate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMITemplatedUrlDelegate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/title"},{"value":[{"text":"SMITemplatedUrlDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/fragments"},{"value":[{"text":"SMITemplatedUrlDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/navigatorTitle"},{"value":"SMICoreFactory","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle"},{"value":"templatedUrlDelegate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1templatedUrlDelegate\/title"},{"value":[{"text":"templatedUrlDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient~1templatedUrlDelegate\/fragments"},{"value":"SMICoreConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle"},{"value":"SMICoreClient","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments"},{"value":[{"text":"SMICoreClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"}]}]}