{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantclientmenu\/options"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantclientmenu\/options"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu\/options"},"metadata":{"title":"options","externalID":"c:objc(pl)SMIParticipantClientMenu(py)options","symbolKind":"property","navigatorTitle":[{"text":"options","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipantClientMenuOption"},{"text":"]","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","text":"ParticipantClientMenuOption","preciseIdentifier":"c:objc(pl)SMIParticipantClientMenuOption"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The array of available menu options for the participant.","type":"text"},{"text":" ","type":"text"},{"text":"Each option in the array represents a possible action that can be taken. The options","type":"text"},{"text":" ","type":"text"},{"text":"are typically displayed in a menu or list interface for the user to select from.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenu/options":{"role":"symbol","navigatorTitle":[{"text":"options","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu\/options","required":true,"title":"options","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ParticipantClientMenuOption","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipantClientMenuOption"},{"text":"]","kind":"text"}],"url":"\/documentation\/smiclientcore\/participantclientmenu\/options","type":"topic","abstract":[{"type":"text","text":"The array of available menu options for the participant."},{"type":"text","text":" "},{"type":"text","text":"Each option in the array represents a possible action that can be taken. The options"},{"type":"text","text":" "},{"type":"text","text":"are typically displayed in a menu or list interface for the user to select from."}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenu":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenu","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenu"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantClientMenu"}],"url":"\/documentation\/smiclientcore\/participantclientmenu","abstract":[{"type":"text","text":"A protocol that represents a menu of available actions for a participant."}],"role":"symbol","title":"ParticipantClientMenu"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantClientMenuOption":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantClientMenuOption","url":"\/documentation\/smiclientcore\/participantclientmenuoption","navigatorTitle":[{"kind":"identifier","text":"ParticipantClientMenuOption"}],"title":"ParticipantClientMenuOption","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantClientMenuOption"}],"kind":"symbol","abstract":[{"text":"A protocol that represents an individual menu option available to a participant.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"options","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"options","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIParticipantClientMenuOption>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"options","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"options","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu~1options\/title","op":"replace"},{"value":[{"text":"options","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu~1options\/fragments","op":"replace"},{"value":"SMIParticipantClientMenu","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenu"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/fragments","op":"replace"},{"value":[{"text":"SMIParticipantClientMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenu\/navigatorTitle","op":"replace"},{"value":"SMIParticipantClientMenuOption","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/title","op":"replace"},{"value":[{"text":"SMIParticipantClientMenuOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantClientMenuOption"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantClientMenuOption\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}