{"kind":"symbol","metadata":{"roleHeading":"Type Property","title":"experimentalConfig","modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"text":"experimentalConfig","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)SMICoreFactory(cpy)experimentalConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"experimentalConfig","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"ExperimentalConfiguration","preciseIdentifier":"c:objc(pl)SMIExperimentalConfiguration","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"experimentalConfig"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration","preciseIdentifier":"c:objc(pl)SMIExperimentalConfiguration","text":"ExperimentalConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"All properties and features which are exposed in this class are subject to change.","type":"text"}]}],"style":"note","name":"Note"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Experimental features\/APIs may be removed without advanced notification at any time.","type":"text"},{"text":" ","type":"text"},{"text":"Any use of these features will ","type":"text"},{"inlineContent":[{"type":"text","text":"NOT"}],"type":"strong"},{"text":" be offered any official support, until such time as they may be adopted as full and stable features.","type":"text"}]}],"style":"warning","name":"Warning"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/corefactory\/experimentalconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/corefactory\/experimentalconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This class stores configuration for experimental or beta features."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/experimentalConfig","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ExperimentalConfiguration":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExperimentalConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"This class stores configuration for experimental or beta features."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ExperimentalConfiguration","url":"\/documentation\/smiclientcore\/experimentalconfiguration","kind":"symbol","navigatorTitle":[{"text":"ExperimentalConfiguration","kind":"identifier"}],"title":"ExperimentalConfiguration","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory/experimentalConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"experimentalConfig","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIExperimentalConfiguration","text":"ExperimentalConfiguration","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"This class stores configuration for experimental or beta features.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/experimentalConfig","title":"experimentalConfig","url":"\/documentation\/smiclientcore\/corefactory\/experimentalconfig","navigatorTitle":[{"text":"experimentalConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"experimentalConfig","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"experimentalConfig"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIExperimentalConfiguration>","preciseIdentifier":"c:Qoobjc(pl)SMIExperimentalConfiguration","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"experimentalConfig","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace"},{"value":[{"text":"SMICoreClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace"},{"value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace"},{"value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace"},{"value":"SMIExperimentalConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/title","op":"replace"},{"value":[{"text":"SMIExperimentalConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIExperimentalConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ExperimentalConfiguration\/navigatorTitle","op":"replace"},{"value":"experimentalConfig","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1experimentalConfig\/title","op":"replace"},{"value":[{"kind":"identifier","text":"experimentalConfig"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1experimentalConfig\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}