{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"]]},"sections":[],"abstract":[{"type":"text","text":"Provide the APNS token which will be forwarded to the In-App services to forward notifications related to conversations."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"deviceToken","content":[{"inlineContent":[{"text":"The APNS device token.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This method is idempotent. It is safe to call whenever the application receives or retrieves an APNS device token.","type":"text"},{"text":" ","type":"text"},{"text":"The token will not be uploaded to our services until needed. Executing this method does not result in any network traffic directly.","type":"text"}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/smiclientcore\/corefactory\/provide(devicetoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/corefactory\/provide(devicetoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"provideDeviceToken:"}],"externalID":"c:objc(cs)SMICoreFactory(cm)provideDeviceToken:","role":"symbol","symbolKind":"method","modules":[{"name":"SMIClientCore"}],"title":"provide(deviceToken:)"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/provide(deviceToken:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","kind":"symbol","navigatorTitle":[{"text":"CoreFactory","kind":"identifier"}],"title":"CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory/provide(deviceToken:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Provide the APNS token which will be forwarded to the In-App services to forward notifications related to conversations.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory\/provide(deviceToken:)","title":"provide(deviceToken:)","url":"\/documentation\/smiclientcore\/corefactory\/provide(devicetoken:)","navigatorTitle":[{"text":"provideDeviceToken:","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"CoreClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/coreclient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"provideDeviceToken:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"provideDeviceToken:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"provideDeviceToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"deviceToken","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"deviceToken","content":[{"inlineContent":[{"text":"The APNS device token.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace","value":"SMICoreFactory"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICoreFactory"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1provide(deviceToken:)\/title","op":"replace","value":"provideDeviceToken:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory~1provide(deviceToken:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"provideDeviceToken:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace","value":"SMICoreClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","op":"replace","value":[{"text":"SMICoreClient","kind":"identifier"}]}]}]}