{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Debug logging level."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/debug"},"variants":[{"paths":["\/documentation\/smiclientcore\/logginglevel\/debug"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/logginglevel\/debug"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","externalID":"c:@E@SMILoggingLevel@SMILoggingLevelDebug","title":"LoggingLevel.debug","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMILoggingLevelDebug","kind":"identifier"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/debug":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"url":"\/documentation\/smiclientcore\/logginglevel\/debug","abstract":[{"text":"Debug logging level.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SMILoggingLevelDebug"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/debug","type":"topic","title":"LoggingLevel.debug","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel":{"url":"\/documentation\/smiclientcore\/logginglevel","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","kind":"symbol","title":"LoggingLevel","type":"topic","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"Logging level values."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMILoggingLevelDebug","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMILoggingLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SMILoggingLevelDebug","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1debug\/title","op":"replace","value":"SMILoggingLevelDebug"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel~1debug\/fragments","op":"replace","value":[{"text":"SMILoggingLevelDebug","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/title","op":"replace","value":"SMILoggingLevel"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevel"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}