{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"SMIClientCore"}]},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/Equatable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/logginglevel\/equatable-implementations"]}],"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","type":"topic","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"title":"LoggingLevel","url":"\/documentation\/smiclientcore\/logginglevel","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoggingLevel","kind":"identifier"}],"abstract":[{"text":"Logging level values.","type":"text"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel/!=(_:_:)":{"title":"!=(_:_:)","type":"topic","abstract":[],"url":"\/documentation\/smiclientcore\/logginglevel\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel\/!=(_:_:)","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/title","value":"SMILoggingLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/fragments","value":[{"text":"SMILoggingLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/navigatorTitle","value":[{"text":"SMILoggingLevel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}