{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/loggingprotocol\/level"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/loggingprotocol\/level"]}],"abstract":[{"text":"The logging level for the SDK.","type":"text"},{"text":" ","type":"text"},{"text":"This property controls the verbosity of logging output. When set to","type":"text"},{"text":" ","type":"text"},{"code":"SMILoggingLevelNone","type":"codeVoice"},{"text":", no logging occurs. When set to ","type":"text"},{"code":"SMILoggingLevelDebug","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"detailed debug information is logged.","type":"text"}],"sections":[],"metadata":{"externalID":"c:objc(pl)SMILogging(cpy)level","role":"symbol","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMILoggingLevel"}],"title":"level","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"level","kind":"identifier"}],"required":true},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol\/level"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","text":"LoggingLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMILoggingLevel"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingLevel":{"url":"\/documentation\/smiclientcore\/logginglevel","navigatorTitle":[{"text":"LoggingLevel","kind":"identifier"}],"role":"symbol","type":"topic","title":"LoggingLevel","abstract":[{"type":"text","text":"Logging level values."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggingLevel","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggingProtocol"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol","title":"LoggingProtocol","navigatorTitle":[{"kind":"identifier","text":"LoggingProtocol"}],"url":"\/documentation\/smiclientcore\/loggingprotocol","abstract":[{"text":"A protocol that defines the logging configuration for the SDK.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/LoggingProtocol/level":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingProtocol\/level","required":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggingLevel","preciseIdentifier":"c:@E@SMILoggingLevel","kind":"typeIdentifier"}],"title":"level","type":"topic","navigatorTitle":[{"text":"level","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The logging level for the SDK.","type":"text"},{"text":" ","type":"text"},{"text":"This property controls the verbosity of logging output. When set to","type":"text"},{"text":" ","type":"text"},{"code":"SMILoggingLevelNone","type":"codeVoice"},{"type":"text","text":", no logging occurs. When set to "},{"type":"codeVoice","code":"SMILoggingLevelDebug"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"detailed debug information is logged."}],"url":"\/documentation\/smiclientcore\/loggingprotocol\/level"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"level"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"level","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/LoggingLevel","preciseIdentifier":"c:@E@SMILoggingLevel","text":"SMILoggingLevel","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"level","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/title","op":"replace","value":"SMILoggingLevel"},{"op":"replace","value":[{"kind":"identifier","text":"SMILoggingLevel"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/fragments"},{"op":"replace","value":[{"text":"SMILoggingLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingLevel\/navigatorTitle"},{"op":"replace","value":"SMILogging","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/title"},{"op":"replace","value":[{"text":"SMILogging","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMILogging"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol\/navigatorTitle"},{"op":"replace","value":"level","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol~1level\/title"},{"op":"replace","value":[{"kind":"identifier","text":"level"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1LoggingProtocol~1level\/fragments"}]}]}