{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"citedDetailsType"}],"externalID":"c:objc(pl)SMICitedDetails(py)citedDetailsType","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetailsType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","text":"CitedDetailsType"}],"modules":[{"name":"SMIClientCore"}],"title":"citedDetailsType","required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails\/citedDetailsType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citeddetails\/citeddetailstype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citeddetails\/citeddetailstype"]}],"kind":"symbol","abstract":[{"type":"text","text":"The type identifier for this citation’s details."},{"type":"text","text":" "},{"type":"text","text":"The type is defined by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"},{"type":"text","text":" enum and helps determine the"},{"type":"text","text":" "},{"type":"text","text":"appropriate way to process and display the citation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetailsType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","text":"CitedDetailsType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails":{"role":"symbol","url":"\/documentation\/smiclientcore\/citeddetails","navigatorTitle":[{"text":"CitedDetails","kind":"identifier"}],"abstract":[{"text":"A protocol that represents the location and type information for a citation.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CitedDetails","kind":"identifier"}],"type":"topic","title":"CitedDetails","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetailsType":{"title":"CitedDetailsType","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedDetailsType"}],"abstract":[{"type":"text","text":"An enum that defines the types of citation details available in the system."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","navigatorTitle":[{"kind":"identifier","text":"CitedDetailsType"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/citeddetailstype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedDetails/citedDetailsType":{"title":"citedDetailsType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetailsType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","text":"CitedDetailsType"}],"url":"\/documentation\/smiclientcore\/citeddetails\/citeddetailstype","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetails\/citedDetailsType","navigatorTitle":[{"kind":"identifier","text":"citedDetailsType"}],"abstract":[{"type":"text","text":"The type identifier for this citation’s details."},{"type":"text","text":" "},{"type":"text","text":"The type is defined by the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType","isActive":true},{"type":"text","text":" enum and helps determine the"},{"type":"text","text":" "},{"type":"text","text":"appropriate way to process and display the citation."}],"required":true,"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"citedDetailsType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"citedDetailsType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:SMICitedDetailsType.h@T@SMICitedDetailsType","kind":"typeIdentifier","text":"SMICitedDetailsType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedDetailsType"},{"kind":"text","text":" "},{"kind":"identifier","text":"citedDetailsType"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/title","value":"SMICitedDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/fragments","value":[{"text":"SMICitedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails\/navigatorTitle","value":[{"text":"SMICitedDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/title","value":"SMICitedDetailsType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/fragments","value":[{"text":"SMICitedDetailsType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetailsType\/navigatorTitle","value":[{"text":"SMICitedDetailsType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails~1citedDetailsType\/title","value":"citedDetailsType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedDetails~1citedDetailsType\/fragments","value":[{"kind":"identifier","text":"citedDetailsType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}