{"kind":"symbol","metadata":{"required":true,"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormExperienceType(py)collectValues","title":"collectValues","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectValues"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]!"}],"navigatorTitle":[{"kind":"identifier","text":"collectValues"}]},"abstract":[{"text":"An array containing dictionaries representing form responses.","type":"text"},{"text":" ","type":"text"},{"text":"The intention is to return a value for each entry in the ","type":"text"},{"code":"inputs","type":"codeVoice"},{"text":" property.","type":"text"},{"text":" ","type":"text"},{"text":"This array is only intended for collection of data. It is not persisted on this entry.","type":"text"},{"text":" ","type":"text"},{"text":"However upon sending this form entry, a ","type":"text"},{"code":"SMIFormExperienceTypeResponse","type":"codeVoice"},{"text":" will be created and persisted with the collected data.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectValues","kind":"identifier"},{"text":": [[","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]]! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/formexperiencetype\/collectvalues"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formexperiencetype\/collectvalues"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/collectValues","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetype","navigatorTitle":[{"kind":"identifier","text":"FormExperienceType"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormExperienceType"}],"abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"title":"FormExperienceType","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/collectValues":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectValues"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]!"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectValues"}],"title":"collectValues","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/collectValues","required":true,"abstract":[{"type":"text","text":"An array containing dictionaries representing form responses."},{"type":"text","text":" "},{"type":"text","text":"The intention is to return a value for each entry in the "},{"code":"inputs","type":"codeVoice"},{"type":"text","text":" property."},{"type":"text","text":" "},{"type":"text","text":"This array is only intended for collection of data. It is not persisted on this entry."},{"type":"text","text":" "},{"type":"text","text":"However upon sending this form entry, a "},{"code":"SMIFormExperienceTypeResponse","type":"codeVoice"},{"type":"text","text":" will be created and persisted with the collected data."}],"type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetype\/collectvalues"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"collectValues","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"collectValues","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSDictionary<NSString *,id> *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"collectValues","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title","value":"SMIFormExperienceType","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle","op":"replace"},{"value":"collectValues","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1collectValues\/title","op":"replace"},{"value":[{"text":"collectValues","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1collectValues\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}