{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/confirm"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirm"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIConfirmExperienceType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConfirmExperienceType","text":"ConfirmExperienceType"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"confirm","kind":"identifier"}],"title":"confirm","symbolKind":"property","externalID":"c:objc(pl)SMIFormExperienceType(py)confirm","modules":[{"name":"SMIClientCore"}],"required":true,"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirm","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ConfirmExperienceType","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConfirmExperienceType"},{"text":")?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formexperiencetype\/confirm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formexperiencetype\/confirm"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"type":"topic","title":"FormExperienceType","role":"symbol","navigatorTitle":[{"text":"FormExperienceType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormExperienceType","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formexperiencetype","abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/confirm":{"required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/confirm","title":"confirm","abstract":[],"url":"\/documentation\/smiclientcore\/formexperiencetype\/confirm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirm"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"ConfirmExperienceType","preciseIdentifier":"c:objc(pl)SMIConfirmExperienceType"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"confirm"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConfirmExperienceType":{"title":"ConfirmExperienceType","navigatorTitle":[{"text":"ConfirmExperienceType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConfirmExperienceType","url":"\/documentation\/smiclientcore\/confirmexperiencetype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConfirmExperienceType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"confirm","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"confirm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIConfirmExperienceType>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConfirmExperienceType"},{"text":" ","kind":"text"},{"text":"confirm","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormExperienceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title"},{"value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle"},{"value":"confirm","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1confirm\/title"},{"value":[{"text":"confirm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1confirm\/fragments"},{"value":"SMIConfirmExperienceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConfirmExperienceType\/title"},{"value":[{"text":"SMIConfirmExperienceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConfirmExperienceType\/fragments"},{"value":[{"text":"SMIConfirmExperienceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConfirmExperienceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}