{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formexperiencetype\/response"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formexperiencetype\/response"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType"]]},"kind":"symbol","abstract":[{"type":"text","text":"nil until the form has been sent. The "},{"type":"codeVoice","code":"inputValues"},{"type":"text","text":" array of the response will be populated with the content of the "},{"type":"codeVoice","code":"collectValues"},{"type":"text","text":" array."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/response"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormExperienceTypeResponse","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","preciseIdentifier":"c:objc(pl)SMIFormExperienceTypeResponse"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"response","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormExperienceTypeResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormExperienceTypeResponse"},{"text":")?","kind":"text"}],"required":true,"title":"response","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIFormExperienceType(py)response","symbolKind":"property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormExperienceTypeResponse","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formexperiencetyperesponse","type":"topic","navigatorTitle":[{"text":"FormExperienceTypeResponse","kind":"identifier"}],"abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"kind":"symbol","title":"FormExperienceTypeResponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType/response":{"abstract":[{"type":"text","text":"nil until the form has been sent. The "},{"type":"codeVoice","code":"inputValues"},{"type":"text","text":" array of the response will be populated with the content of the "},{"type":"codeVoice","code":"collectValues"},{"type":"text","text":" array."}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FormExperienceTypeResponse","preciseIdentifier":"c:objc(pl)SMIFormExperienceTypeResponse","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType\/response","title":"response","navigatorTitle":[{"text":"response","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formexperiencetype\/response"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceType":{"url":"\/documentation\/smiclientcore\/formexperiencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceType","type":"topic","abstract":[{"type":"strong","inlineContent":[{"text":"Experimental","type":"text"}]},{"type":"text","text":" Support for Forms for LightningType interactions with Agentforce."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FormExperienceType","kind":"identifier"}],"title":"FormExperienceType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormExperienceType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"response","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"response"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFormExperienceTypeResponse>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFormExperienceTypeResponse"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormExperienceTypeResponse","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/title"},{"op":"replace","value":[{"text":"SMIFormExperienceTypeResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormExperienceTypeResponse"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/navigatorTitle"},{"op":"replace","value":"response","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1response\/title"},{"op":"replace","value":[{"text":"response","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType~1response\/fragments"},{"op":"replace","value":"SMIFormExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/title"},{"op":"replace","value":[{"text":"SMIFormExperienceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFormExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceType\/navigatorTitle"}]}]}