{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/messageReason"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"messageReason","kind":"identifier"}],"required":true,"externalID":"c:objc(pl)SMIEntryTypeMessage(py)messageReason","roleHeading":"Instance Property","title":"messageReason","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"messageReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","kind":"typeIdentifier"}],"role":"symbol"},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageReason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property indicates why an automated response was generated."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/entrytypemessage\/messagereason"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/entrytypemessage\/messagereason"]}],"abstract":[{"type":"text","text":"The reason for an automated message response."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage/messageReason":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"messageReason"}],"title":"messageReason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/messageReason","url":"\/documentation\/smiclientcore\/entrytypemessage\/messagereason","abstract":[{"type":"text","text":"The reason for an automated message response."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason","text":"MessageReason"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageReason":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReason"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageReason"}],"abstract":[{"type":"text","text":"An enum that defines the possible reasons for a message in a conversation."}],"title":"MessageReason","role":"symbol","url":"\/documentation\/smiclientcore\/messagereason","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}],"abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","type":"topic","kind":"symbol","title":"EntryTypeMessage","role":"symbol","url":"\/documentation\/smiclientcore\/entrytypemessage","navigatorTitle":[{"text":"EntryTypeMessage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"messageReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"messageReason","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason"],"anchor":"Related-Documentation","title":"Related Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMIMessageReason","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageReason","preciseIdentifier":"c:SMIMessageReason.h@T@SMIMessageReason"},{"text":" ","kind":"text"},{"text":"messageReason","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1messageReason\/title","value":"messageReason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1messageReason\/fragments","value":[{"kind":"identifier","text":"messageReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/title","value":"SMIMessageReason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/fragments","value":[{"text":"SMIMessageReason","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageReason\/navigatorTitle","value":[{"text":"SMIMessageReason","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","value":"SMIEntryTypeMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","value":[{"kind":"identifier","text":"SMIEntryTypeMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]}]}]}