{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wasRevised","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/wasRevised"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(pl)SMIEntryTypeMessage(py)wasRevised","symbolKind":"property","title":"wasRevised","navigatorTitle":[{"kind":"identifier","text":"wasRevised"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wasRevised"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"abstract":[{"type":"text","text":"If this message was generated as part of a streamed response, this property can be used to determine if this final static response has been modified in any way from the original set of streamed tokens."}],"variants":[{"paths":["\/documentation\/smiclientcore\/entrytypemessage\/wasrevised"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/entrytypemessage\/wasrevised"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage"]]},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage/wasRevised":{"type":"topic","kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wasRevised","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"If this message was generated as part of a streamed response, this property can be used to determine if this final static response has been modified in any way from the original set of streamed tokens.","type":"text"}],"navigatorTitle":[{"text":"wasRevised","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/entrytypemessage\/wasrevised","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage\/wasRevised","title":"wasRevised"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryTypeMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryTypeMessage","title":"EntryTypeMessage","navigatorTitle":[{"kind":"identifier","text":"EntryTypeMessage"}],"abstract":[{"text":"A protocol that provides additional details for message-type entries in a conversation.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entrytypemessage","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryTypeMessage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"wasRevised"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"wasRevised","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"wasRevised"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1wasRevised\/title","op":"replace","value":"wasRevised"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage~1wasRevised\/fragments","op":"replace","value":[{"kind":"identifier","text":"wasRevised"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/title","op":"replace","value":"SMIEntryTypeMessage"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/fragments","op":"replace","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryTypeMessage\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryTypeMessage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}