{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate"]]},"abstract":[{"text":"Delegate event that is triggered when a user verification token is required to be provided by the app.","type":"text"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate\/core(_:userVerificationChallengeWith:completionHandler:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"core"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userVerificationChallengeWith"},{"text":" ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SMIChallengeReason","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","text":"ChallengeReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","preciseIdentifier":"c:objc(cs)SMIUserVerification","text":"UserVerification","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"core","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient"},{"text":", ","kind":"text"},{"text":"userVerificationChallengeWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ChallengeReason","preciseIdentifier":"c:@E@SMIChallengeReason","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UserVerification","preciseIdentifier":"c:objc(cs)SMIUserVerification","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"SMICoreClient","type":"codeVoice"},{"text":" instance that is managing the current connection.","type":"text"}]}],"name":"core"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"SMIChallengeReason","type":"codeVoice"},{"type":"text","text":" which generated this user verification challenge."}]}],"name":"reason"},{"content":[{"inlineContent":[{"text":"The completion that provides a user verification token.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"content":[{"inlineContent":[{"text":"To cancel you can return ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to the completion block. This event may still fire several times when a challenge is required even if cancelled.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/userverificationdelegate\/core(_:userverificationchallengewith:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/userverificationdelegate\/core(_:userverificationchallengewith:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"symbolKind":"method","externalID":"c:objc(pl)SMIUserVerificationDelegate(im)core:userVerificationChallengeWithReason:completionHandler:","navigatorTitle":[{"text":"core:userVerificationChallengeWithReason:completionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SMICoreClient","kind":"typeIdentifier","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userVerificationChallengeWith"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SMIChallengeReason","kind":"typeIdentifier","text":"ChallengeReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)SMIUserVerification","kind":"typeIdentifier","text":"UserVerification"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true,"title":"core(_:userVerificationChallengeWith:completionHandler:)","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"role":"symbol","title":"Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","isActive":true},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","isActive":true},{"text":".","type":"text"}],"type":"topic","title":"CoreClient","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"navigatorTitle":[{"text":"CoreClient","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerificationDelegate/core(_:userVerificationChallengeWith:completionHandler:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate\/core(_:userVerificationChallengeWith:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"CoreClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"text":", ","kind":"text"},{"text":"userVerificationChallengeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChallengeReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIChallengeReason"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"UserVerification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SMIUserVerification"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Delegate event that is triggered when a user verification token is required to be provided by the app.","type":"text"}],"title":"core(_:userVerificationChallengeWith:completionHandler:)","role":"symbol","kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"core:userVerificationChallengeWithReason:completionHandler:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/userverificationdelegate\/core(_:userverificationchallengewith:completionhandler:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerificationDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerificationDelegate"}],"abstract":[{"text":"Delegate that handles requests for user verification.","type":"text"}],"title":"UserVerificationDelegate","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserVerificationDelegate"}],"url":"\/documentation\/smiclientcore\/userverificationdelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","url":"\/documentation\/smiclientcore\/corefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoreFactory"}],"abstract":[{"text":"Factory for creating and managing instances of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true,"type":"reference"}],"role":"symbol","kind":"symbol","title":"CoreFactory","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","kind":"symbol","navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"url":"\/documentation\/smiclientcore\/userverification","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}],"type":"topic","title":"UserVerification"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChallengeReason":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","url":"\/documentation\/smiclientcore\/challengereason","navigatorTitle":[{"kind":"identifier","text":"ChallengeReason"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeReason"}],"abstract":[{"text":"An enum that defines the possible reasons for a user verification challenge.","type":"text"}],"title":"ChallengeReason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerificationChallengeCompletion":{"title":"UserVerificationChallengeCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationChallengeCompletion","kind":"symbol","abstract":[{"text":"Completion block for user verification.","type":"text"}],"navigatorTitle":[{"text":"UserVerificationChallengeCompletion","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/userverificationchallengecompletion","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerificationChallengeCompletion","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"core:userVerificationChallengeWithReason:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:userVerificationChallengeWithReason:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"core:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMICoreClient","text":"id<SMICoreClient>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"core"},{"kind":"text","text":" "},{"kind":"identifier","text":"userVerificationChallengeWithReason:"},{"kind":"text","text":"("},{"text":"SMIChallengeReason","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChallengeReason","preciseIdentifier":"c:@E@SMIChallengeReason"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SMIUserVerificationChallengeCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIUserVerificationDelegate.h@T@SMIUserVerificationChallengeCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerificationChallengeCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"core","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"SMICoreClient","type":"codeVoice"},{"text":" instance that is managing the current connection.","type":"text"}],"type":"paragraph"}]},{"name":"reason","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"SMIChallengeReason","type":"codeVoice"},{"text":" which generated this user verification challenge.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion that provides a user verification token."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","value":"SMICoreConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","value":[{"kind":"identifier","text":"SMICoreConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","value":[{"text":"SMICoreConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","value":"SMICoreClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"kind":"identifier","text":"SMICoreClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate~1core(_:userVerificationChallengeWith:completionHandler:)\/title","value":"core:userVerificationChallengeWithReason:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate~1core(_:userVerificationChallengeWith:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"core:userVerificationChallengeWithReason:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/title","value":"SMIUserVerificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/fragments","value":[{"text":"SMIUserVerificationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SMIUserVerificationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","value":"SMICoreFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","value":[{"text":"SMICoreFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","value":"SMIUserVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/title","value":"SMIChallengeReason"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/fragments","value":[{"kind":"identifier","text":"SMIChallengeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChallengeReason\/navigatorTitle","value":[{"kind":"identifier","text":"SMIChallengeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/title","value":"SMIUserVerificationChallengeCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/fragments","value":[{"kind":"identifier","text":"SMIUserVerificationChallengeCompletion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerificationChallengeCompletion\/navigatorTitle","value":[{"text":"SMIUserVerificationChallengeCompletion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}