{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue\/valueType"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/formresponsevalue\/valuetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsevalue\/valuetype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"valueType","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","kind":"typeIdentifier","text":"FormResponseValueType"}],"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIFormResponseValue(py)valueType","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"valueType"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType","text":"FormResponseValueType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"],"anchor":"Related-Documentation","title":"Related Documentation"}],"abstract":[{"type":"text","text":"The type of response value."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the specific type of value this response contains."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValueType":{"role":"symbol","title":"FormResponseValueType","abstract":[{"type":"text","text":"An enum that defines the types of values that can be submitted in a form response."}],"url":"\/documentation\/smiclientcore\/formresponsevaluetype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValueType","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FormResponseValueType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseValue","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FormResponseValue","kind":"identifier"}],"title":"FormResponseValue","type":"topic","url":"\/documentation\/smiclientcore\/formresponsevalue","abstract":[{"type":"text","text":"A protocol that defines the base interface for form response values."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseValue/valueType":{"abstract":[{"type":"text","text":"The type of response value."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the specific type of value this response contains."}],"role":"symbol","kind":"symbol","title":"valueType","navigatorTitle":[{"text":"valueType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValue\/valueType","type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormResponseValueType.h@T@SMIFormResponseValueType","text":"FormResponseValueType","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/formresponsevalue\/valuetype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"valueType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"valueType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseValueType"],"title":"Related Documentation"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"valueType"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/title","value":"SMIFormResponseValueType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseValueType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValueType\/navigatorTitle","value":[{"text":"SMIFormResponseValueType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/title","value":"SMIFormResponseValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/fragments","value":[{"text":"SMIFormResponseValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue~1valueType\/title","value":"valueType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseValue~1valueType\/fragments","value":[{"kind":"identifier","text":"valueType"}]}]}]}