{"metadata":{"externalID":"c:objc(pl)SMIAttachmentUploadResult(py)resultType","required":true,"title":"resultType","modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"resultType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resultType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AttachmentUploadResultType","kind":"typeIdentifier","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType"}]},"sections":[],"abstract":[{"type":"text","text":"The type\/status of the upload result (Completed, Pending, Error)."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","kind":"typeIdentifier","text":"AttachmentUploadResultType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/attachmentuploadresult\/resulttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/attachmentuploadresult\/resulttype"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult\/resultType","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult","title":"AttachmentUploadResult","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/attachmentuploadresult","abstract":[{"type":"text","text":"Result of an attachment upload operation."}],"navigatorTitle":[{"text":"AttachmentUploadResult","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttachmentUploadResult","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResult/resultType":{"url":"\/documentation\/smiclientcore\/attachmentuploadresult\/resulttype","abstract":[{"text":"The type\/status of the upload result (Completed, Pending, Error).","type":"text"}],"required":true,"title":"resultType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","text":"AttachmentUploadResultType"}],"navigatorTitle":[{"kind":"identifier","text":"resultType"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResult\/resultType","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentUploadResultType":{"role":"symbol","title":"AttachmentUploadResultType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttachmentUploadResultType"}],"url":"\/documentation\/smiclientcore\/attachmentuploadresulttype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentUploadResultType"}],"abstract":[{"type":"text","text":"An enum that defines the possible states of an attachment upload operation."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"resultType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"resultType"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMIAttachmentUploadResultType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentUploadResultType","preciseIdentifier":"c:SMIAttachmentUploadResultTypes.h@T@SMIAttachmentUploadResultType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"resultType","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/title","value":"SMIAttachmentUploadResult","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/fragments","value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult\/navigatorTitle","value":[{"text":"SMIAttachmentUploadResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult~1resultType\/title","value":"resultType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResult~1resultType\/fragments","value":[{"kind":"identifier","text":"resultType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/title","value":"SMIAttachmentUploadResultType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/fragments","value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentUploadResultType\/navigatorTitle","value":[{"text":"SMIAttachmentUploadResultType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}