{"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"customerIdentityToken"}],"symbolKind":"property","externalID":"c:objc(cs)SMIUserVerification(py)customerIdentityToken","title":"customerIdentityToken","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerIdentityToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/userverification\/customeridentitytoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/userverification\/customeridentitytoken"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerIdentityToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/customerIdentityToken","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The authentication token used to verify the user’s identity."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/userverification","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","role":"symbol","type":"topic","title":"UserVerification","navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents a verified user’s authentication credentials."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/customerIdentityToken":{"role":"symbol","title":"customerIdentityToken","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerIdentityToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"customerIdentityToken","kind":"identifier"}],"abstract":[{"type":"text","text":"The authentication token used to verify the user’s identity."}],"url":"\/documentation\/smiclientcore\/userverification\/customeridentitytoken","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/customerIdentityToken"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customerIdentityToken"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"customerIdentityToken","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"customerIdentityToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","op":"replace","value":"SMIUserVerification"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIUserVerification"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle","op":"replace","value":[{"text":"SMIUserVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1customerIdentityToken\/title","op":"replace","value":"customerIdentityToken"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1customerIdentityToken\/fragments","op":"replace","value":[{"text":"customerIdentityToken","kind":"identifier"}]}]}]}