{"variants":[{"paths":["\/documentation\/smiclientcore\/userverification\/init(customeridentitytoken:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/userverification\/init(customeridentitytoken:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/init(customerIdentityToken:type:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"customerIdentityToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"AuthorizationTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The authentication token that is used to verify the user with the service.","type":"text"}]}],"name":"customerIdentityToken"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","isActive":true},{"text":" type for the customer identity token.","type":"text"}],"type":"paragraph"}],"name":"type"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"},{"text":" with the specified credentials, which is used to pass in user verification credentials.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"]]},"metadata":{"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithCustomerIdentityToken:type:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerIdentityToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"AuthorizationTypes"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)SMIUserVerification(im)initWithCustomerIdentityToken:type:","title":"init(customerIdentityToken:type:)","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","title":"UserVerification","navigatorTitle":[{"text":"UserVerification","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents a verified user’s authentication credentials."}],"type":"topic","url":"\/documentation\/smiclientcore\/userverification","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserVerification","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/init(customerIdentityToken:type:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/init(customerIdentityToken:type:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"},{"type":"text","text":" with the specified credentials, which is used to pass in user verification credentials."}],"role":"symbol","navigatorTitle":[{"text":"initWithCustomerIdentityToken:type:","kind":"identifier"}],"title":"init(customerIdentityToken:type:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customerIdentityToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthorizationTypes","preciseIdentifier":"c:@E@SMIAuthorizationTypes"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/userverification\/init(customeridentitytoken:type:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"abstract":[{"text":"An enum that defines the types of authorization for API requests.","type":"text"}],"navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/authorizationtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","title":"AuthorizationTypes"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCustomerIdentityToken:type:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerIdentityToken:type:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCustomerIdentityToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"customerIdentityToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"SMIAuthorizationTypes","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The authentication token that is used to verify the user with the service."}]}],"name":"customerIdentityToken"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","isActive":true,"type":"reference"},{"text":" type for the customer identity token.","type":"text"}]}],"name":"type"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SMIUserVerification","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIUserVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIUserVerification"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1init(customerIdentityToken:type:)\/title","op":"replace","value":"initWithCustomerIdentityToken:type:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCustomerIdentityToken:type:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1init(customerIdentityToken:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title","value":"SMIAuthorizationTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}