{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/type"},"kind":"symbol","metadata":{"title":"type","externalID":"c:objc(cs)SMIUserVerification(py)type","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthorizationTypes","preciseIdentifier":"c:@E@SMIAuthorizationTypes"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"type"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthorizationTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","preciseIdentifier":"c:@E@SMIAuthorizationTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The type of authorization used for the customer identity token.","type":"text"},{"text":" ","type":"text"},{"text":"This determines how the token should be processed and validated.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/smiclientcore\/userverification\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/userverification\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification/type":{"title":"type","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"AuthorizationTypes","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"The type of authorization used for the customer identity token.","type":"text"},{"text":" ","type":"text"},{"text":"This determines how the token should be processed and validated.","type":"text"}],"url":"\/documentation\/smiclientcore\/userverification\/type","role":"symbol","type":"topic","navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AuthorizationTypes":{"role":"symbol","title":"AuthorizationTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/authorizationtypes","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes","type":"topic","abstract":[{"type":"text","text":"An enum that defines the types of authorization for API requests."}],"navigatorTitle":[{"text":"AuthorizationTypes","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/UserVerification":{"role":"symbol","type":"topic","title":"UserVerification","kind":"symbol","abstract":[{"text":"A class that represents a verified user’s authentication credentials.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/UserVerification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserVerification"}],"navigatorTitle":[{"kind":"identifier","text":"UserVerification"}],"url":"\/documentation\/smiclientcore\/userverification"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIAuthorizationTypes","text":"SMIAuthorizationTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AuthorizationTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/title","value":"SMIAuthorizationTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/fragments","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AuthorizationTypes\/navigatorTitle","value":[{"text":"SMIAuthorizationTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/title","value":"SMIUserVerification","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/fragments","value":[{"text":"SMIUserVerification","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1UserVerification\/navigatorTitle","value":[{"text":"SMIUserVerification","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}