{"sections":[],"abstract":[{"type":"text","text":"The time when the typing indicator was created."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"platforms":[{"introducedAt":"8.0","beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"introducedAt":"8.0","beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"8.0","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"required":true,"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","role":"symbol","title":"timestamp","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"externalID":"c:objc(pl)SMITypingIndicator(py)timestamp"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/smiclientcore\/typingindicator\/timestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/typingindicator\/timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator\/timestamp"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicator":{"abstract":[{"text":"A protocol that represents a typing indicator within a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TypingIndicator","kind":"identifier"}],"navigatorTitle":[{"text":"TypingIndicator","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator","title":"TypingIndicator","type":"topic","url":"\/documentation\/smiclientcore\/typingindicator"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TypingIndicator/timestamp":{"kind":"symbol","title":"timestamp","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"url":"\/documentation\/smiclientcore\/typingindicator\/timestamp","abstract":[{"type":"text","text":"The time when the typing indicator was created."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TypingIndicator\/timestamp","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","title":"ConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"url":"\/documentation\/smiclientcore\/conversationentry","navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"timestamp"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"timestamp"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timestamp"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMITypingIndicator","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMITypingIndicator"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMITypingIndicator"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator\/navigatorTitle"},{"op":"replace","value":"timestamp","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator~1timestamp\/title"},{"op":"replace","value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TypingIndicator~1timestamp\/fragments"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"}]}]}