{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue\/textValue"},"sections":[],"kind":"symbol","abstract":[{"text":"The text value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the string entered by the user, stored as an ","type":"text"},{"type":"codeVoice","code":"NSString"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The value can contain any text content, including letters, numbers, and special","type":"text"},{"text":" ","type":"text"},{"text":"characters, depending on the input field’s configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/formresponsetextvalue\/textvalue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formresponsetextvalue\/textvalue"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"role":"symbol","externalID":"c:objc(pl)SMIFormResponseTextValue(py)textValue","title":"textValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"required":true,"navigatorTitle":[{"text":"textValue","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseTextValue/textValue":{"abstract":[{"type":"text","text":"The text value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the string entered by the user, stored as an "},{"type":"codeVoice","code":"NSString"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The value can contain any text content, including letters, numbers, and special"},{"type":"text","text":" "},{"type":"text","text":"characters, depending on the input field’s configuration."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"textValue","required":true,"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue\/textValue","url":"\/documentation\/smiclientcore\/formresponsetextvalue\/textvalue","navigatorTitle":[{"text":"textValue","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseTextValue":{"title":"FormResponseTextValue","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseTextValue","navigatorTitle":[{"text":"FormResponseTextValue","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formresponsetextvalue","abstract":[{"text":"A protocol that defines a form response value containing text.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseTextValue","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"textValue","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"textValue"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textValue"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue~1textValue\/title","op":"replace","value":"textValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue~1textValue\/fragments","value":[{"kind":"identifier","text":"textValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/title","value":"SMIFormResponseTextValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseTextValue\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormResponseTextValue"}]}]}]}