{"variants":[{"paths":["\/documentation\/smiclientcore\/failuretypes\/cancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/failuretypes\/cancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/cancelled"},"metadata":{"roleHeading":"Type Property","externalID":"c:@SMIFailureTypesCancelled","title":"cancelled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FailureTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFailureTypesCancelled"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore"},"abstract":[{"text":"The routing operation was cancelled.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier","text":"FailureTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","title":"FailureTypes","navigatorTitle":[{"kind":"identifier","text":"FailureTypes"}],"abstract":[{"text":"An enum that defines the possible types of routing failures that can occur.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/failuretypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/cancelled":{"url":"\/documentation\/smiclientcore\/failuretypes\/cancelled","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/cancelled","abstract":[{"type":"text","text":"The routing operation was cancelled."}],"role":"symbol","navigatorTitle":[{"text":"SMIFailureTypesCancelled","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes"}],"type":"topic","title":"cancelled"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"SMIFailureTypesCancelled","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIFailureTypesCancelled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"SMIFailureTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFailureTypesCancelled"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title","value":"SMIFailureTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments","value":[{"text":"SMIFailureTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFailureTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1cancelled\/title","value":"SMIFailureTypesCancelled","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1cancelled\/fragments","value":[{"text":"SMIFailureTypesCancelled","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}