{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/Equatable-Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/failuretypes\/equatable-implementations"]}],"metadata":{"title":"Equatable Implementations","modules":[{"name":"SMIClientCore"}],"role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/!=(_:_:)"],"generated":true}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/!=(_:_:)":{"type":"topic","abstract":[],"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/smiclientcore\/failuretypes\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/!=(_:_:)","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"role":"symbol","navigatorTitle":[{"text":"FailureTypes","kind":"identifier"}],"title":"FailureTypes","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FailureTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/failuretypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","abstract":[{"type":"text","text":"An enum that defines the possible types of routing failures that can occur."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SMIFailureTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments","value":[{"kind":"identifier","text":"SMIFailureTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle","value":[{"text":"SMIFailureTypes","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}