{"sections":[],"abstract":[{"type":"text","text":"A failure occurred during the routing process."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"]]},"metadata":{"externalID":"c:@SMIFailureTypesRoutingError","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"SMIFailureTypesRoutingError"}],"title":"routingError","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/failuretypes\/routingerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/failuretypes\/routingerror"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/routingError","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FailureTypes","kind":"identifier"}],"navigatorTitle":[{"text":"FailureTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","title":"FailureTypes","type":"topic","abstract":[{"text":"An enum that defines the possible types of routing failures that can occur.","type":"text"}],"url":"\/documentation\/smiclientcore\/failuretypes","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/routingError":{"type":"topic","navigatorTitle":[{"text":"SMIFailureTypesRoutingError","kind":"identifier"}],"title":"routingError","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/failuretypes\/routingerror","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/routingError","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A failure occurred during the routing process."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFailureTypesRoutingError","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIFailureTypesRoutingError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"SMIFailureTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFailureTypesRoutingError"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title","value":"SMIFailureTypes","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments","value":[{"text":"SMIFailureTypes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFailureTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1routingError\/title","value":"SMIFailureTypesRoutingError","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1routingError\/fragments","value":[{"kind":"identifier","text":"SMIFailureTypesRoutingError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}