{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SMIFailureTypesSubmissionError"}],"role":"symbol","externalID":"c:@SMIFailureTypesSubmissionError","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","extendedModule":"SMIClientCore","title":"submissionError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"submissionError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/submissionError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submissionError","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes","kind":"typeIdentifier"}]}],"kind":"declarations"}],"abstract":[{"text":"A failure occurred during data submission.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/failuretypes\/submissionerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/failuretypes\/submissionerror"]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/submissionError":{"url":"\/documentation\/smiclientcore\/failuretypes\/submissionerror","navigatorTitle":[{"text":"SMIFailureTypesSubmissionError","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/submissionError","abstract":[{"type":"text","text":"A failure occurred during data submission."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submissionError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"FailureTypes","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"submissionError"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"abstract":[{"text":"An enum that defines the possible types of routing failures that can occur.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FailureTypes"}],"title":"FailureTypes","url":"\/documentation\/smiclientcore\/failuretypes","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFailureTypesSubmissionError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMIFailureTypesSubmissionError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFailureTypesSubmissionError","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFailureTypesSubmissionError","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1submissionError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFailureTypesSubmissionError"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1submissionError\/fragments"},{"op":"replace","value":"SMIFailureTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIFailureTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments"},{"op":"replace","value":[{"text":"SMIFailureTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle"}]}]}