{"sections":[],"abstract":[{"text":"An unknown or unspecified routing failure.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/unknown","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","kind":"typeIdentifier","text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/failuretypes\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/failuretypes\/unknown"]}],"metadata":{"externalID":"c:@SMIFailureTypesUnknown","title":"unknown","role":"symbol","extendedModule":"SMIClientCore","roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier","text":"FailureTypes"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","title":"FailureTypes","navigatorTitle":[{"kind":"identifier","text":"FailureTypes"}],"abstract":[{"text":"An enum that defines the possible types of routing failures that can occur.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/failuretypes","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureTypes"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FailureTypes/unknown":{"title":"unknown","abstract":[{"text":"An unknown or unspecified routing failure.","type":"text"}],"url":"\/documentation\/smiclientcore\/failuretypes\/unknown","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes\/unknown","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIFailureTypesUnknown","path":"\/metadata\/title"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FailureTypes","preciseIdentifier":"c:SMIFailureTypes.h@T@SMIFailureTypes","text":"SMIFailureTypes"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFailureTypesUnknown"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIFailureTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/title","op":"replace"},{"value":[{"text":"SMIFailureTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/fragments","op":"replace"},{"value":[{"text":"SMIFailureTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes\/navigatorTitle","op":"replace"},{"value":"SMIFailureTypesUnknown","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1unknown\/title","op":"replace"},{"value":[{"text":"SMIFailureTypesUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FailureTypes~1unknown\/fragments","op":"replace"}]}]}