{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/wrappedClient"},"kind":"symbol","variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaclient\/wrappedclient"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:19SMIMultimediaCommon16MultimediaClientC07wrappedD0AA0cD8Protocol_pSgvp","roleHeading":"Instance Property","title":"wrappedClient","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrappedClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":"?","kind":"text"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrappedClient","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient","text":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The underlying ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"reference","isActive":true},{"text":" instance.","type":"text"}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient/wrappedClient":{"role":"symbol","type":"topic","title":"wrappedClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient\/wrappedClient","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrappedClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaClient"},{"text":"?","kind":"text"}],"url":"\/documentation\/smimultimediacommon\/multimediaclient\/wrappedclient","abstract":[{"text":"The underlying ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClient":{"navigatorTitle":[{"text":"MultimediaClient","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaclient","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClient","kind":"identifier"}],"title":"MultimediaClient","kind":"symbol","type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"ObservableObject","type":"codeVoice"},{"text":" wrapper around ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"reference","isActive":true},{"text":" that publishes session changes for use in SwiftUI views.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaClientProtocol":{"title":"MultimediaClientProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaClientProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaclientprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaClientProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaClientProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the main entry point for creating and managing multimedia sessions."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SMIMultimediaClient","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaClientProtocol\/navigatorTitle"}]}]}