{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/smiclientcore\/formselectinput\/multipleselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formselectinput\/multipleselection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determines whether this input allows for multiple selections."},{"type":"text","text":" "},{"type":"text","text":"When set to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", users can select multiple options from the list. When set to "},{"type":"codeVoice","code":"NO"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"only a single option can be selected at a time."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormSelectInput(py)multipleSelection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"SMIClientCore"}],"required":true,"navigatorTitle":[{"text":"multipleSelection","kind":"identifier"}],"title":"multipleSelection","role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput":{"url":"\/documentation\/smiclientcore\/formselectinput","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a select input field in a form that supports single or multiple selections."}],"title":"FormSelectInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"navigatorTitle":[{"kind":"identifier","text":"FormSelectInput"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/multipleSelection":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"multipleSelection","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","url":"\/documentation\/smiclientcore\/formselectinput\/multipleselection","title":"multipleSelection","abstract":[{"type":"text","text":"Determines whether this input allows for multiple selections."},{"type":"text","text":" "},{"type":"text","text":"When set to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", users can select multiple options from the list. When set to "},{"type":"codeVoice","code":"NO"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"only a single option can be selected at a time."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"multipleSelection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"multipleSelection"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"multipleSelection","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/title","value":"SMIFormSelectInput","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/fragments","value":[{"text":"SMIFormSelectInput","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormSelectInput"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/title","value":"multipleSelection","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/fragments","value":[{"kind":"identifier","text":"multipleSelection"}],"op":"replace"}]}]}