{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionItems"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormSelectInput(py)optionItems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","title":"optionItems","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","required":true},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/formselectinput\/optionitems"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formselectinput\/optionitems"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A list of selectable options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property contains the available options that can be selected in the input."},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference"},{"type":"text","text":" that includes a title and identifier."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/optionItems":{"url":"\/documentation\/smiclientcore\/formselectinput\/optionitems","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"optionItems","abstract":[{"text":"A list of selectable options for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the available options that can be selected in the input.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference","isActive":true},{"type":"text","text":" that includes a title and identifier."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput":{"title":"FormSelectInput","type":"topic","kind":"symbol","navigatorTitle":[{"text":"FormSelectInput","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","abstract":[{"text":"A protocol that represents a select input field in a form that supports single or multiple selections.","type":"text"}],"url":"\/documentation\/smiclientcore\/formselectinput"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","type":"topic","abstract":[{"type":"text","text":"A protocol that defines a selectable option in a form that contains a title and unique identifier."}],"role":"symbol","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"title":"FormInputOptionItem","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"optionItems","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"optionItems"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIFormTitleOptionItem>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"optionItems"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"optionItems","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/title"},{"op":"replace","value":[{"text":"optionItems","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/fragments"},{"value":"SMIFormSelectInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormSelectInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/fragments"},{"value":[{"text":"SMIFormSelectInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/navigatorTitle"},{"value":"SMIFormTitleOptionItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title"},{"value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle"}]}]}