{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/value","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/smiclientcore\/formselectinput\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formselectinput\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(pl)SMIFormSelectInput(py)value","required":true,"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"role":"symbol"},"abstract":[{"type":"text","text":"The currently selected options for this input."},{"type":"text","text":" "},{"type":"text","text":"This property holds the currently selected option items. It can be read to get the current"},{"type":"text","text":" "},{"type":"text","text":"selections and written to programmatically set new selections. The values must be from the"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","isActive":true},{"type":"text","text":" array. When "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","isActive":true},{"type":"text","text":" is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":", this array should contain at most"},{"type":"text","text":" "},{"type":"text","text":"one item."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","text":"FormInputOptionItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput"]]},"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/optionItems":{"url":"\/documentation\/smiclientcore\/formselectinput\/optionitems","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionItems","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"optionItems","abstract":[{"text":"A list of selectable options for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the available options that can be selected in the input.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Each option is represented by a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","type":"reference","isActive":true},{"type":"text","text":" that includes a title and identifier."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","navigatorTitle":[{"text":"optionItems","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputOptionItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputOptionItem","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputOptionItem","url":"\/documentation\/smiclientcore\/forminputoptionitem","type":"topic","abstract":[{"type":"text","text":"A protocol that defines a selectable option in a form that contains a title and unique identifier."}],"role":"symbol","navigatorTitle":[{"text":"FormInputOptionItem","kind":"identifier"}],"title":"FormInputOptionItem","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/value":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"FormInputOptionItem","preciseIdentifier":"c:objc(pl)SMIFormTitleOptionItem","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"text":"The currently selected options for this input.","type":"text"},{"text":" ","type":"text"},{"text":"This property holds the currently selected option items. It can be read to get the current","type":"text"},{"type":"text","text":" "},{"type":"text","text":"selections and written to programmatically set new selections. The values must be from the"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/optionItems","type":"reference","isActive":true},{"type":"text","text":" array. When "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","type":"reference","isActive":true},{"type":"text","text":" is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":", this array should contain at most"},{"type":"text","text":" "},{"type":"text","text":"one item."}],"title":"value","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/value","required":true,"role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/formselectinput\/value","navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput/multipleSelection":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Determines whether this input allows for multiple selections.","type":"text"},{"text":" ","type":"text"},{"text":"When set to ","type":"text"},{"type":"codeVoice","code":"YES"},{"type":"text","text":", users can select multiple options from the list. When set to "},{"type":"codeVoice","code":"NO"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"only a single option can be selected at a time."}],"kind":"symbol","url":"\/documentation\/smiclientcore\/formselectinput\/multipleselection","role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput\/multipleSelection","navigatorTitle":[{"text":"multipleSelection","kind":"identifier"}],"required":true,"title":"multipleSelection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormSelectInput":{"title":"FormSelectInput","type":"topic","kind":"symbol","navigatorTitle":[{"text":"FormSelectInput","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormSelectInput"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormSelectInput","abstract":[{"text":"A protocol that represents a select input field in a form that supports single or multiple selections.","type":"text"}],"url":"\/documentation\/smiclientcore\/formselectinput"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"value"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIFormTitleOptionItem>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/title","value":"optionItems"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1optionItems\/fragments","value":[{"text":"optionItems","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/title","op":"replace","value":"SMIFormTitleOptionItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputOptionItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormTitleOptionItem"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1value\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/title","op":"replace","value":"multipleSelection"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput~1multipleSelection\/fragments","op":"replace","value":[{"text":"multipleSelection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/title","op":"replace","value":"SMIFormSelectInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormSelectInput"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormSelectInput\/navigatorTitle","op":"replace","value":[{"text":"SMIFormSelectInput","kind":"identifier"}]}]}]}