{"abstract":[{"type":"text","text":"The date and time value of the response."},{"type":"text","text":" "},{"type":"text","text":"This property contains the complete datetime information selected by the user,"},{"type":"text","text":" "},{"type":"text","text":"including both the date and time components."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue\/dateTimeValue"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formresponsedatetimevalue\/datetimevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formresponsedatetimevalue\/datetimevalue"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue"]]},"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"dateTimeValue","symbolKind":"property","required":true,"externalID":"c:objc(pl)SMIFormResponseDateTimeValue(py)dateTimeValue","roleHeading":"Instance Property","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"8.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"8.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"8.0","beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"dateTimeValue"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateTimeValue/dateTimeValue":{"kind":"symbol","title":"dateTimeValue","abstract":[{"text":"The date and time value of the response.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the complete datetime information selected by the user,","type":"text"},{"text":" ","type":"text"},{"text":"including both the date and time components.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue\/dateTimeValue","navigatorTitle":[{"kind":"identifier","text":"dateTimeValue"}],"required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/formresponsedatetimevalue\/datetimevalue","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormResponseDateTimeValue":{"url":"\/documentation\/smiclientcore\/formresponsedatetimevalue","role":"symbol","abstract":[{"type":"text","text":"A protocol that defines a form response value containing a date and time."}],"title":"FormResponseDateTimeValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormResponseDateTimeValue","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormResponseDateTimeValue","kind":"identifier"}],"navigatorTitle":[{"text":"FormResponseDateTimeValue","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dateTimeValue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dateTimeValue","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dateTimeValue"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue~1dateTimeValue\/title","value":"dateTimeValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue~1dateTimeValue\/fragments","value":[{"text":"dateTimeValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/title","value":"SMIFormResponseDateTimeValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/fragments","value":[{"kind":"identifier","text":"SMIFormResponseDateTimeValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormResponseDateTimeValue\/navigatorTitle","value":[{"text":"SMIFormResponseDateTimeValue","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}