{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet\/init(contextVariables:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)SMISessionContextSet(im)initWithContextVariables:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"contextVariables","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"NamedValueProtocol","preciseIdentifier":"c:objc(pl)SMINamedValue","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithContextVariables:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"SMIClientCore"}],"roleHeading":"Initializer","role":"symbol","title":"init(contextVariables:)"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet"]]},"abstract":[{"type":"text","text":"Initializes a new session context set with the provided context variables."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"contextVariables","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMINamedValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","text":"NamedValueProtocol","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An array of named values representing the context variables.","type":"text"}],"type":"paragraph"}],"name":"contextVariables"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/sessioncontextset\/init(contextvariables:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessioncontextset\/init(contextvariables:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NamedValueProtocol":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NamedValueProtocol"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NamedValueProtocol","url":"\/documentation\/smiclientcore\/namedvalueprotocol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Represents a named value variable item with a name and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol"},{"type":"text","text":"."}],"title":"NamedValueProtocol","navigatorTitle":[{"kind":"identifier","text":"NamedValueProtocol"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet":{"kind":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextset","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet","title":"SessionContextSet","navigatorTitle":[{"kind":"identifier","text":"SessionContextSet"}],"abstract":[{"text":"Concrete implementation of SMISessionContextSet protocol.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextSet"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractValueProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractValueProtocol","type":"topic","abstract":[{"type":"text","text":"Protocol that defines the base type for session context values."}],"url":"\/documentation\/smiclientcore\/abstractvalueprotocol","title":"AbstractValueProtocol","navigatorTitle":[{"text":"AbstractValueProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractValueProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextSet/init(contextVariables:)":{"url":"\/documentation\/smiclientcore\/sessioncontextset\/init(contextvariables:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithContextVariables:"}],"abstract":[{"type":"text","text":"Initializes a new session context set with the provided context variables."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextSet\/init(contextVariables:)","kind":"symbol","title":"init(contextVariables:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contextVariables"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMINamedValue","text":"NamedValueProtocol"},{"kind":"text","text":"])"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithContextVariables:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContextVariables:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithContextVariables:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMINamedValue>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contextVariables"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"contextVariables","content":[{"inlineContent":[{"text":"An array of named values representing the context variables.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/title","value":"SMINamedValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/fragments","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NamedValueProtocol\/navigatorTitle","value":[{"text":"SMINamedValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/title","value":"SMISessionContextSet"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/fragments","value":[{"kind":"identifier","text":"SMISessionContextSet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet\/navigatorTitle","value":[{"text":"SMISessionContextSet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/title","value":"SMIAbstractValue"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/fragments","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractValueProtocol\/navigatorTitle","value":[{"text":"SMIAbstractValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet~1init(contextVariables:)\/title","value":"initWithContextVariables:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextSet~1init(contextVariables:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContextVariables:"}],"op":"replace"}]}]}