{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel\/items"},"kind":"symbol","abstract":[{"text":"The array of items displayed in this carousel.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","type":"reference"},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option in the carousel.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"TitleLinkItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITitleLinkItem","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/carousel\/items"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/carousel\/items"]}],"metadata":{"roleHeading":"Instance Property","title":"items","navigatorTitle":[{"kind":"identifier","text":"items"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"TitleLinkItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITitleLinkItem"},{"text":"]?","kind":"text"}],"modules":[{"name":"SMIClientCore"}],"required":true,"externalID":"c:objc(pl)SMICarousel(py)items"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TitleLinkItem":{"navigatorTitle":[{"kind":"identifier","text":"TitleLinkItem"}],"title":"TitleLinkItem","abstract":[{"type":"text","text":"A protocol that represents an interactive item in a carousel with a title and selectable options."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TitleLinkItem"}],"type":"topic","url":"\/documentation\/smiclientcore\/titlelinkitem"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel":{"url":"\/documentation\/smiclientcore\/carousel","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents a carousel of selectable items in a conversation."}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Carousel"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel","navigatorTitle":[{"kind":"identifier","text":"Carousel"}],"kind":"symbol","title":"Carousel"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Carousel/items":{"abstract":[{"text":"The array of items displayed in this carousel.","type":"text"},{"text":" ","type":"text"},{"text":"Each item in the array conforms to the ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TitleLinkItem","isActive":true,"type":"reference"},{"text":" protocol and represents","type":"text"},{"text":" ","type":"text"},{"text":"a selectable option in the carousel.","type":"text"}],"kind":"symbol","type":"topic","title":"items","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"TitleLinkItem","preciseIdentifier":"c:objc(pl)SMITitleLinkItem"},{"kind":"text","text":"]?"}],"url":"\/documentation\/smiclientcore\/carousel\/items","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Carousel\/items","navigatorTitle":[{"kind":"identifier","text":"items"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"items"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"items"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMITitleLinkItem>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"items"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/title","op":"replace","value":"SMITitleLinkItem"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/fragments","op":"replace","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TitleLinkItem\/navigatorTitle","op":"replace","value":[{"text":"SMITitleLinkItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/title","op":"replace","value":"SMICarousel"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/fragments","op":"replace","value":[{"text":"SMICarousel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMICarousel"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel~1items\/title","op":"replace","value":"items"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Carousel~1items\/fragments","op":"replace","value":[{"kind":"identifier","text":"items"}]}]}]}