{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"choiceList"}],"title":"choiceList","role":"symbol","required":true,"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIPreChatChoiceListField(py)choiceList","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"choiceList"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceList","text":"ChoiceList"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceList","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The choice list that defines the available options for this field."},{"type":"text","text":" "},{"type":"text","text":"This object contains the collection of "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","isActive":true,"type":"reference"},{"type":"text","text":" objects that users can select from."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"ChoiceList","preciseIdentifier":"c:objc(pl)SMIChoiceList","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/smiclientcore\/prechatchoicelistfield\/choicelist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatchoicelistfield\/choicelist"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceList","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines a collection of choice list values."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","kind":"symbol","navigatorTitle":[{"text":"ChoiceList","kind":"identifier"}],"title":"ChoiceList","url":"\/documentation\/smiclientcore\/choicelist","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField":{"role":"symbol","url":"\/documentation\/smiclientcore\/prechatchoicelistfield","kind":"symbol","type":"topic","title":"PreChatChoiceListField","navigatorTitle":[{"kind":"identifier","text":"PreChatChoiceListField"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatChoiceListField"}],"abstract":[{"text":"A protocol that defines a choice list field in the pre-chat form.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListValue":{"title":"ChoiceListValue","navigatorTitle":[{"kind":"identifier","text":"ChoiceListValue"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceListValue"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","url":"\/documentation\/smiclientcore\/choicelistvalue","abstract":[{"text":"A protocol that defines a single option within a choice list in pre-chat.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatChoiceListField/choiceList":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceList","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"ChoiceList","preciseIdentifier":"c:objc(pl)SMIChoiceList","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/prechatchoicelistfield\/choicelist","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatChoiceListField\/choiceList","role":"symbol","type":"topic","navigatorTitle":[{"text":"choiceList","kind":"identifier"}],"kind":"symbol","title":"choiceList","abstract":[{"text":"The choice list that defines the available options for this field.","type":"text"},{"text":" ","type":"text"},{"text":"This object contains the collection of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListValue","isActive":true,"type":"reference"},{"text":" objects that users can select from.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"choiceList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"choiceList"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)SMIChoiceList","kind":"typeIdentifier","text":"id<SMIChoiceList>"},{"kind":"text","text":" "},{"kind":"identifier","text":"choiceList"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","value":"SMIChoiceList"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","value":[{"text":"SMIChoiceList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/title","value":"SMIPreChatChoiceListField"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/fragments","value":[{"text":"SMIPreChatChoiceListField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField\/navigatorTitle","value":[{"text":"SMIPreChatChoiceListField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/title","value":"SMIChoiceListValue"},{"value":[{"text":"SMIChoiceListValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/fragments","op":"replace"},{"value":[{"text":"SMIChoiceListValue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListValue\/navigatorTitle","op":"replace"},{"value":"choiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceList\/title","op":"replace"},{"value":[{"text":"choiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatChoiceListField~1choiceList\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}