{"abstract":[{"type":"text","text":"Represents DOCX document data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting Microsoft Word documents in DOCX format."}],"metadata":{"externalID":"c:@SMINetworkMimeTypesApplicationDOCX","title":"applicationDOCX","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDOCX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"roleHeading":"Type Property","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOCX"}],"symbolKind":"property","role":"symbol","modules":[{"name":"SMIClientCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/applicationdocx"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/applicationdocx"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOCX","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDOCX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkMimeTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkMimeTypes","kind":"identifier"}],"kind":"symbol","title":"NetworkMimeTypes","navigatorTitle":[{"text":"NetworkMimeTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","role":"symbol","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationDOCX":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOCX"}],"title":"applicationDOCX","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationDOCX","abstract":[{"text":"Represents DOCX document data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting Microsoft Word documents in DOCX format.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDOCX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationdocx","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMINetworkMimeTypesApplicationDOCX","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOCX"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"SMINetworkMimeTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMINetworkMimeTypesApplicationDOCX"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMINetworkMimeTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle"},{"value":"SMINetworkMimeTypesApplicationDOCX","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOCX\/title"},{"value":[{"text":"SMINetworkMimeTypesApplicationDOCX","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationDOCX\/fragments"}]}]}