{"sections":[],"abstract":[{"type":"text","text":"Represents PDF document data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting PDF documents."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationPDF","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationPDF","kind":"identifier"},{"kind":"text","text":": "},{"text":"NetworkMimeTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/networkmimetypes\/applicationpdf"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/networkmimetypes\/applicationpdf"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"}],"externalID":"c:@SMINetworkMimeTypesApplicationPDF","symbolKind":"property","title":"applicationPDF","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationPDF","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/applicationPDF":{"title":"applicationPDF","abstract":[{"text":"Represents PDF document data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting PDF documents.","type":"text"}],"url":"\/documentation\/smiclientcore\/networkmimetypes\/applicationpdf","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/applicationPDF","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationPDF","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"type":"topic","title":"NetworkMimeTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMINetworkMimeTypesApplicationPDF","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMINetworkMimeTypesApplicationPDF","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationPDF\/title"},{"value":[{"text":"SMINetworkMimeTypesApplicationPDF","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1applicationPDF\/fragments"},{"value":"SMINetworkMimeTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle"}]}]}