{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"abstract":[{"text":"Represents GZIP compressed data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting GZIP compressed content.","type":"text"}],"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"GZIP","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GZIP","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@SMINetworkMimeTypesGZIP","roleHeading":"Type Property","extendedModule":"SMIClientCore","symbolKind":"property","navigatorTitle":[{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/GZIP","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/gzip"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/gzip"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GZIP","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"url":"\/documentation\/smiclientcore\/networkmimetypes","role":"symbol","title":"NetworkMimeTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/GZIP":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GZIP"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier","text":"NetworkMimeTypes"}],"navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesGZIP"}],"title":"GZIP","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/GZIP","url":"\/documentation\/smiclientcore\/networkmimetypes\/gzip","kind":"symbol","abstract":[{"type":"text","text":"Represents GZIP compressed data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting GZIP compressed content."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMINetworkMimeTypesGZIP","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"SMINetworkMimeTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle"},{"value":"SMINetworkMimeTypesGZIP","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1GZIP\/title"},{"value":[{"text":"SMINetworkMimeTypesGZIP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1GZIP\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}