{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Represents JPEG image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting JPEG format images."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageJPEG","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/imagejpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/imagejpeg"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageJPEG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","extendedModule":"SMIClientCore","navigatorTitle":[{"kind":"identifier","text":"SMINetworkMimeTypesImageJPEG"}],"externalID":"c:@SMINetworkMimeTypesImageJPEG","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageJPEG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","roleHeading":"Type Property","title":"imageJPEG"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageJPEG":{"type":"topic","url":"\/documentation\/smiclientcore\/networkmimetypes\/imagejpeg","role":"symbol","abstract":[{"type":"text","text":"Represents JPEG image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting JPEG format images."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageJPEG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesImageJPEG","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageJPEG","kind":"symbol","title":"imageJPEG"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkMimeTypes","kind":"identifier"}],"kind":"symbol","title":"NetworkMimeTypes","navigatorTitle":[{"text":"NetworkMimeTypes","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMINetworkMimeTypesImageJPEG","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypesImageJPEG"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypesImageJPEG","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMINetworkMimeTypesImageJPEG","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageJPEG\/title","op":"replace"},{"value":[{"text":"SMINetworkMimeTypesImageJPEG","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageJPEG\/fragments","op":"replace"},{"value":"SMINetworkMimeTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}