{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"imageGIF","externalID":"c:@SMINetworkMimeTypesImageGIF","symbolKind":"property","extendedModule":"SMIClientCore","navigatorTitle":[{"text":"SMINetworkMimeTypesImageGIF","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageGIF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"Represents GIF image data."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting GIF format images."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageGIF"},"variants":[{"paths":["\/documentation\/smiclientcore\/networkmimetypes\/imagegif"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/networkmimetypes\/imagegif"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageGIF"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"url":"\/documentation\/smiclientcore\/networkmimetypes","role":"symbol","title":"NetworkMimeTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/imageGIF":{"role":"symbol","title":"imageGIF","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageGIF","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesImageGIF","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/imageGIF","kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/imagegif","abstract":[{"text":"Represents GIF image data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting GIF format images.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMINetworkMimeTypesImageGIF"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMINetworkMimeTypesImageGIF"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"SMINetworkMimeTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypesImageGIF","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SMINetworkMimeTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle"},{"value":"SMINetworkMimeTypesImageGIF","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageGIF\/title"},{"value":[{"kind":"identifier","text":"SMINetworkMimeTypesImageGIF"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1imageGIF\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}