{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/textcsv"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/textcsv"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textCSV","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textCSV"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","text":"NetworkMimeTypes"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Represents CSV data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting comma-separated values data.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"metadata":{"navigatorTitle":[{"text":"SMINetworkMimeTypesTextCSV","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"textCSV","roleHeading":"Type Property","symbolKind":"property","externalID":"c:@SMINetworkMimeTypesTextCSV","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textCSV","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"}],"extendedModule":"SMIClientCore","role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/textCSV":{"title":"textCSV","abstract":[{"text":"Represents CSV data.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting comma-separated values data.","type":"text"}],"url":"\/documentation\/smiclientcore\/networkmimetypes\/textcsv","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textCSV","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textCSV","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesTextCSV","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"url":"\/documentation\/smiclientcore\/networkmimetypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}],"type":"topic","title":"NetworkMimeTypes"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMINetworkMimeTypesTextCSV","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMINetworkMimeTypesTextCSV"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","text":"SMINetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes"},{"text":" ","kind":"text"},{"text":"SMINetworkMimeTypesTextCSV","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMINetworkMimeTypesTextCSV","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textCSV\/title"},{"op":"replace","value":[{"text":"SMINetworkMimeTypesTextCSV","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textCSV\/fragments"},{"op":"replace","value":"SMINetworkMimeTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMINetworkMimeTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle","op":"replace","value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}