{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textPlain"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/textplain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkmimetypes\/textplain"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPlain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@SMINetworkMimeTypesTextPlain","extendedModule":"SMIClientCore","symbolKind":"property","title":"textPlain","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPlain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMINetworkMimeTypesTextPlain","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Represents plain text content.","type":"text"},{"text":" ","type":"text"},{"text":"Used for transmitting unformatted text data.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes/textPlain":{"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/networkmimetypes\/textplain","navigatorTitle":[{"text":"SMINetworkMimeTypesTextPlain","kind":"identifier"}],"title":"textPlain","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes\/textPlain","abstract":[{"type":"text","text":"Represents plain text content."},{"type":"text","text":" "},{"type":"text","text":"Used for transmitting unformatted text data."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPlain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"NetworkMimeTypes","kind":"typeIdentifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkMimeTypes":{"title":"NetworkMimeTypes","url":"\/documentation\/smiclientcore\/networkmimetypes","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkMimeTypes"}],"type":"topic","abstract":[{"type":"text","text":"An enum that defines the standard MIME types used for network communication."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMimeTypes"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMINetworkMimeTypesTextPlain","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMINetworkMimeTypesTextPlain"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkMimeTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkMimeTypes.h@T@SMINetworkMimeTypes","text":"SMINetworkMimeTypes"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMINetworkMimeTypesTextPlain"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMINetworkMimeTypesTextPlain","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textPlain\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMINetworkMimeTypesTextPlain"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes~1textPlain\/fragments"},{"op":"replace","value":"SMINetworkMimeTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/title"},{"op":"replace","value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/fragments"},{"op":"replace","value":[{"text":"SMINetworkMimeTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkMimeTypes\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}