{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/streamingtoken\/tokentype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/streamingtoken\/tokentype"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","kind":"typeIdentifier","text":"StreamingTokenTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","title":"tokenType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StreamingTokenTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"symbolKind":"property","required":true,"navigatorTitle":[{"text":"tokenType","kind":"identifier"}],"externalID":"c:objc(pl)SMIStreamingToken(py)tokenType","modules":[{"name":"SMIClientCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/tokenType","interfaceLanguage":"swift"},"abstract":[{"text":"The type of streaming token.","type":"text"},{"text":" ","type":"text"},{"text":"This property indicates the type of token through the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},{"text":" enum,","type":"text"},{"text":" ","type":"text"},{"text":"which helps determine how the token should be processed and what kind of content it contains.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingTokenTypes":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","role":"symbol","navigatorTitle":[{"text":"StreamingTokenTypes","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StreamingTokenTypes","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum that defines the possible types of streaming tokens in a conversation."}],"url":"\/documentation\/smiclientcore\/streamingtokentypes","title":"StreamingTokenTypes","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken/tokenType":{"abstract":[{"text":"The type of streaming token.","type":"text"},{"text":" ","type":"text"},{"text":"This property indicates the type of token through the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes","type":"reference"},{"text":" enum,","type":"text"},{"text":" ","type":"text"},{"text":"which helps determine how the token should be processed and what kind of content it contains.","type":"text"}],"title":"tokenType","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StreamingTokenTypes","preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes"}],"navigatorTitle":[{"kind":"identifier","text":"tokenType"}],"type":"topic","url":"\/documentation\/smiclientcore\/streamingtoken\/tokentype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken\/tokenType","required":true,"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/StreamingToken":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingToken","role":"symbol","abstract":[{"type":"text","text":"A protocol that represents an individual token in a stream of content."}],"url":"\/documentation\/smiclientcore\/streamingtoken","kind":"symbol","type":"topic","title":"StreamingToken","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StreamingToken"}],"navigatorTitle":[{"kind":"identifier","text":"StreamingToken"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tokenType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"tokenType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:SMIStreamingTokenTypes.h@T@SMIStreamingTokenTypes","text":"SMIStreamingTokenTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/StreamingTokenTypes"},{"text":" ","kind":"text"},{"text":"tokenType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIStreamingTokenTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/title","op":"replace"},{"value":[{"text":"SMIStreamingTokenTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIStreamingTokenTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingTokenTypes\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1tokenType\/title","op":"replace","value":"tokenType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken~1tokenType\/fragments","op":"replace","value":[{"kind":"identifier","text":"tokenType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/title","op":"replace","value":"SMIStreamingToken"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/fragments","op":"replace","value":[{"text":"SMIStreamingToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1StreamingToken\/navigatorTitle","op":"replace","value":[{"text":"SMIStreamingToken","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}