{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityConnection\/modalityConnection"},"metadata":{"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIModalityConnection(py)modalityConnection","symbolKind":"property","title":"modalityConnection","navigatorTitle":[{"text":"modalityConnection","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modalityConnection","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AbstractModalityConnection","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection"},{"text":")!","kind":"text"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalityConnection"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection","kind":"typeIdentifier","text":"AbstractModalityConnection"},{"kind":"text","text":")! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityConnection"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/modalityconnection\/modalityconnection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/modalityconnection\/modalityconnection"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityConnection/modalityConnection":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityConnection\/modalityConnection","title":"modalityConnection","navigatorTitle":[{"text":"modalityConnection","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/smiclientcore\/modalityconnection\/modalityconnection","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modalityConnection","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection","text":"AbstractModalityConnection","kind":"typeIdentifier"},{"kind":"text","text":")!"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ModalityConnection":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ModalityConnection","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/modalityconnection","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ModalityConnection"}],"abstract":[],"title":"ModalityConnection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ModalityConnection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"modalityConnection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"modalityConnection","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<SMIAbstractModalityConnection>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIAbstractModalityConnection"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modalityConnection"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"modalityConnection","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityConnection~1modalityConnection\/title","op":"replace"},{"op":"replace","value":[{"text":"modalityConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityConnection~1modalityConnection\/fragments"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityConnection\/title","op":"replace","value":"SMIModalityConnection"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityConnection\/fragments","op":"replace","value":[{"text":"SMIModalityConnection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ModalityConnection\/navigatorTitle","op":"replace","value":[{"text":"SMIModalityConnection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}