{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/forminputtype\/datepickerinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/forminputtype\/datepickerinput"]}],"abstract":[{"text":"Represents a form input that allows users to select a date and\/or time.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"SMIFormInputTypeDatePickerInput"}],"extendedModule":"SMIClientCore","externalID":"c:@SMIFormInputTypeDatePickerInput","title":"datePickerInput","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerInput"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","text":"FormInputType"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/datePickerInput","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/datePickerInput":{"title":"datePickerInput","url":"\/documentation\/smiclientcore\/forminputtype\/datepickerinput","abstract":[{"text":"Represents a form input that allows users to select a date and\/or time.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"datePickerInput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormInputTypeDatePickerInput"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/datePickerInput","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","role":"symbol","url":"\/documentation\/smiclientcore\/forminputtype","title":"FormInputType","navigatorTitle":[{"kind":"identifier","text":"FormInputType"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputType"}],"kind":"symbol","abstract":[{"text":"An enum that defines the types of form input fields available in the system.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIFormInputTypeDatePickerInput","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIFormInputTypeDatePickerInput"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SMIFormInputType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIFormInputTypeDatePickerInput"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormInputTypeDatePickerInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1datePickerInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormInputTypeDatePickerInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1datePickerInput\/fragments"},{"value":"SMIFormInputType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/title"},{"value":[{"kind":"identifier","text":"SMIFormInputType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormInputType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/navigatorTitle"}]}]}