{"kind":"symbol","metadata":{"externalID":"c:@SMIFormInputTypeSelectInput","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"SMIFormInputTypeSelectInput","kind":"identifier"}],"extendedModule":"SMIClientCore","title":"selectInput"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Represents a form input that allows users to select one or more options."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectInput"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","kind":"typeIdentifier","text":"FormInputType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/selectInput","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/forminputtype\/selectinput"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminputtype\/selectinput"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputType"}],"url":"\/documentation\/smiclientcore\/forminputtype","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInputType"}],"abstract":[{"type":"text","text":"An enum that defines the types of form input fields available in the system."}],"title":"FormInputType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType/selectInput":{"type":"topic","url":"\/documentation\/smiclientcore\/forminputtype\/selectinput","title":"selectInput","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType\/selectInput","navigatorTitle":[{"kind":"identifier","text":"SMIFormInputTypeSelectInput"}],"abstract":[{"text":"Represents a form input that allows users to select one or more options.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectInput"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","kind":"typeIdentifier","text":"FormInputType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormInputTypeSelectInput"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormInputTypeSelectInput"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormInputType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SMIFormInputTypeSelectInput"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/title","op":"replace","value":"SMIFormInputType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/fragments","op":"replace","value":[{"text":"SMIFormInputType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputType"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1selectInput\/title","op":"replace","value":"SMIFormInputTypeSelectInput"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType~1selectInput\/fragments","op":"replace","value":[{"text":"SMIFormInputTypeSelectInput","kind":"identifier"}]}]}]}