{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formerrorresult\/errors"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formerrorresult\/errors"]}],"metadata":{"title":"errors","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errors","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormErrorResult(py)errors","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","navigatorTitle":[{"text":"errors","kind":"identifier"}],"role":"symbol","required":true},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult"]]},"abstract":[{"text":"The list of errors generated by the form submission.","type":"text"},{"text":" ","type":"text"},{"text":"This array contains one or more ","type":"text"},{"type":"codeVoice","code":"NSError"},{"text":" objects that describe why the form submission","type":"text"},{"text":" ","type":"text"},{"text":"failed. Each error includes a domain, code, and user info that provides specific details","type":"text"},{"text":" ","type":"text"},{"text":"about the failure. Common error types include validation errors, expired requests,","type":"text"},{"text":" ","type":"text"},{"text":"and server-side issues.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult\/errors"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errors"},{"kind":"text","text":": [any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorResult/errors":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errors"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult\/errors","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"errors"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formerrorresult\/errors","abstract":[{"text":"The list of errors generated by the form submission.","type":"text"},{"text":" ","type":"text"},{"text":"This array contains one or more ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" objects that describe why the form submission","type":"text"},{"text":" ","type":"text"},{"text":"failed. Each error includes a domain, code, and user info that provides specific details","type":"text"},{"text":" ","type":"text"},{"text":"about the failure. Common error types include validation errors, expired requests,","type":"text"},{"text":" ","type":"text"},{"text":"and server-side issues.","type":"text"}],"required":true,"title":"errors"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorResult":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormErrorResult","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/formerrorresult","navigatorTitle":[{"text":"FormErrorResult","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that represents a failed form submission with error details."}],"title":"FormErrorResult","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorResult","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"errors","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"errors","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSError *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"errors","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult~1errors\/title","op":"replace","value":"errors"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult~1errors\/fragments","op":"replace","value":[{"text":"errors","kind":"identifier"}]},{"value":"SMIFormErrorResult","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/title"},{"value":[{"text":"SMIFormErrorResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/fragments"},{"value":[{"text":"SMIFormErrorResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorResult\/navigatorTitle"}]}]}