{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdf","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFDocument","text":"PDFDocument","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset\/pdf"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset"]]},"abstract":[{"type":"text","text":"The PDF document content of this asset."},{"type":"text","text":" "},{"type":"text","text":"This property is initially "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and must be loaded using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Once loaded, this property provides access to the PDF document for viewing and interaction."}],"metadata":{"externalID":"c:objc(pl)SMIPDFAsset(py)pdf","required":true,"platforms":[{"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"11.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"title":"pdf","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PDFDocument","text":"PDFDocument"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"pdf"}]},"variants":[{"paths":["\/documentation\/smiclientcore\/pdfasset\/pdf"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/pdfasset\/pdf"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PDFAsset/pdf":{"navigatorTitle":[{"text":"pdf","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdf","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PDFDocument","preciseIdentifier":"c:objc(cs)PDFDocument","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/pdfasset\/pdf","title":"pdf","role":"symbol","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset\/pdf","abstract":[{"text":"The PDF document content of this asset.","type":"text"},{"text":" ","type":"text"},{"text":"This property is initially ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" and must be loaded using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Once loaded, this property provides access to the PDF document for viewing and interaction.","type":"text"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FileAsset/fetchContent(completion:)":{"abstract":[{"text":"Fetches the content of this file asset asynchronously.","type":"text"},{"text":" ","type":"text"},{"text":"This method downloads the file content if it’s not already cached.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"fetchContentWithCompletion:","kind":"identifier"}],"type":"topic","title":"fetchContent(completion:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FileAsset\/fetchContent(completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FileFetchCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SMIFileAsset.h@T@SMIFileFetchCompletion"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/fileasset\/fetchcontent(completion:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PDFAsset":{"url":"\/documentation\/smiclientcore\/pdfasset","navigatorTitle":[{"text":"PDFAsset","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFAsset","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a PDF document asset in a conversation.","type":"text"}],"role":"symbol","title":"PDFAsset","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PDFAsset"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"pdf","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"pdf","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"PDFDocument","preciseIdentifier":"c:objc(cs)PDFDocument"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pdf"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset~1pdf\/title","value":"pdf","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset~1pdf\/fragments","value":[{"kind":"identifier","text":"pdf"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/title","value":"fetchContentWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FileAsset~1fetchContent(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchContentWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/title","value":"SMIPDFAsset","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/fragments","value":[{"text":"SMIPDFAsset","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PDFAsset\/navigatorTitle","value":[{"text":"SMIPDFAsset","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}