{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/attachmentConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The attachment configuration."},{"type":"text","text":" "},{"type":"text","text":"This object defines the allowed file types, size limits, and whether end users can send attachments."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/attachmentconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/attachmentconfiguration"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentConfiguration"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","preciseIdentifier":"c:objc(pl)SMIAttachmentConfiguration","kind":"typeIdentifier","text":"AttachmentConfiguration"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"attachmentConfiguration"}],"modules":[{"name":"SMIClientCore"}],"title":"attachmentConfiguration","roleHeading":"Instance Property","required":true,"symbolKind":"property","externalID":"c:objc(pl)SMIRemoteConfiguration(py)attachmentConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentConfiguration"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentConfiguration","text":"AttachmentConfiguration"},{"kind":"text","text":")?"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AttachmentConfiguration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AttachmentConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AttachmentConfiguration"}],"title":"AttachmentConfiguration","url":"\/documentation\/smiclientcore\/attachmentconfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AttachmentConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for defining configuration properties related to attachments."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/attachmentConfiguration":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachmentConfiguration","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AttachmentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAttachmentConfiguration"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/attachmentConfiguration","url":"\/documentation\/smiclientcore\/remoteconfiguration\/attachmentconfiguration","abstract":[{"type":"text","text":"The attachment configuration."},{"type":"text","text":" "},{"type":"text","text":"This object defines the allowed file types, size limits, and whether end users can send attachments."}],"role":"symbol","navigatorTitle":[{"text":"attachmentConfiguration","kind":"identifier"}],"required":true,"title":"attachmentConfiguration","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"abstract":[{"text":"A protocol that defines the configuration information for an embedded service deployment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","title":"RemoteConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"attachmentConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"attachmentConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIAttachmentConfiguration>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIAttachmentConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachmentConfiguration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/title","value":"SMIAttachmentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/fragments","value":[{"kind":"identifier","text":"SMIAttachmentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AttachmentConfiguration\/navigatorTitle","value":[{"text":"SMIAttachmentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1attachmentConfiguration\/title","value":"attachmentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1attachmentConfiguration\/fragments","value":[{"text":"attachmentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","value":"SMIRemoteConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace"}]}]}