{"sections":[],"metadata":{"symbolKind":"property","title":"choiceListConfiguration","modules":[{"name":"SMIClientCore"}],"required":true,"navigatorTitle":[{"text":"choiceListConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIRemoteConfiguration(py)choiceListConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceListConfiguration","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ChoiceListConfiguration","preciseIdentifier":"c:objc(pl)SMIChoiceListConfiguration","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property"},"abstract":[{"text":"The configuration for choice lists used in pre-chat forms.","type":"text"},{"text":" ","type":"text"},{"text":"This object defines the available options and their relationships for choice list fields.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/choicelistconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/choicelistconfiguration"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/choiceListConfiguration","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"choiceListConfiguration"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","text":"ChoiceListConfiguration"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/choiceListConfiguration":{"navigatorTitle":[{"text":"choiceListConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The configuration for choice lists used in pre-chat forms."},{"type":"text","text":" "},{"type":"text","text":"This object defines the available options and their relationships for choice list fields."}],"url":"\/documentation\/smiclientcore\/remoteconfiguration\/choicelistconfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceListConfiguration","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ChoiceListConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListConfiguration"},{"text":")?","kind":"text"}],"required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/choiceListConfiguration","title":"choiceListConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}],"kind":"symbol","role":"symbol","url":"\/documentation\/smiclientcore\/remoteconfiguration","title":"RemoteConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"RemoteConfiguration","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration":{"title":"ChoiceListConfiguration","abstract":[{"text":"A protocol that defines the configuration for a collection of choice lists used in pre-chat.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","navigatorTitle":[{"kind":"identifier","text":"ChoiceListConfiguration"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistconfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceListConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"choiceListConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"choiceListConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIChoiceListConfiguration","text":"id<SMIChoiceListConfiguration>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"choiceListConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"choiceListConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1choiceListConfiguration\/title"},{"value":[{"text":"choiceListConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1choiceListConfiguration\/fragments"},{"value":"SMIRemoteConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"},{"value":"SMIChoiceListConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIChoiceListConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SMIChoiceListConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/navigatorTitle"}]}]}