{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/deploymenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/deploymenttype"]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/deploymentType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deploymentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"deploymentType","kind":"identifier"}],"required":true,"modules":[{"name":"SMIClientCore"}],"title":"deploymentType","symbolKind":"property","externalID":"c:objc(pl)SMIRemoteConfiguration(py)deploymentType","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"abstract":[{"text":"The deployment type of the remote configuration.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates the type of deployment this configuration is associated with.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deploymentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/deploymentType":{"required":true,"type":"topic","title":"deploymentType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deploymentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"deploymentType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/deploymentType","abstract":[{"text":"The deployment type of the remote configuration.","type":"text"},{"text":" ","type":"text"},{"text":"This value indicates the type of deployment this configuration is associated with.","type":"text"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/remoteconfiguration\/deploymenttype"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"deploymentType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"deploymentType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deploymentType"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","op":"replace","value":"SMIRemoteConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}]},{"op":"replace","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"},{"op":"replace","value":"deploymentType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1deploymentType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"deploymentType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1deploymentType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}