{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"abstract":[{"text":"The fallback message configuration.","type":"text"},{"text":" ","type":"text"},{"text":"This object defines the message to display when the service is unavailable.","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fallbackMessage","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"FallbackMessage","preciseIdentifier":"c:objc(pl)SMIFallbackMessage","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"required":true,"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"fallbackMessage","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIRemoteConfiguration(py)fallbackMessage","title":"fallbackMessage"},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/fallbackMessage","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/fallbackmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/fallbackmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fallbackMessage"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMIFallbackMessage","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage","text":"FallbackMessage"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/fallbackMessage":{"title":"fallbackMessage","abstract":[{"type":"text","text":"The fallback message configuration."},{"type":"text","text":" "},{"type":"text","text":"This object defines the message to display when the service is unavailable."}],"type":"topic","required":true,"url":"\/documentation\/smiclientcore\/remoteconfiguration\/fallbackmessage","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fallbackMessage","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIFallbackMessage","text":"FallbackMessage","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"fallbackMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/fallbackMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FallbackMessage":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FallbackMessage","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FallbackMessage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A protocol that defines the fallback message configuration for when the service is unavailable.","type":"text"}],"url":"\/documentation\/smiclientcore\/fallbackmessage","kind":"symbol","navigatorTitle":[{"text":"FallbackMessage","kind":"identifier"}],"title":"FallbackMessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fallbackMessage","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"fallbackMessage"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIFallbackMessage>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIFallbackMessage"},{"text":" ","kind":"text"},{"text":"fallbackMessage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fallbackMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1fallbackMessage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"fallbackMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1fallbackMessage\/fragments","op":"replace"},{"value":"SMIFallbackMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFallbackMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIFallbackMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FallbackMessage\/navigatorTitle","op":"replace"},{"value":"SMIRemoteConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","op":"replace"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","op":"replace"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","op":"replace"}]}]}