{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/prechatconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/prechatconfiguration"]}],"abstract":[{"type":"text","text":"The list of pre-chat configurations available for this deployment."},{"type":"text","text":" "},{"type":"text","text":"Each configuration defines a set of fields that can be displayed in the pre-chat form."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatConfiguration"},{"kind":"text","text":": [any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration","preciseIdentifier":"c:objc(pl)SMIPreChatConfiguration","kind":"typeIdentifier","text":"PreChatConfiguration"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/preChatConfiguration","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:objc(pl)SMIRemoteConfiguration(py)preChatConfiguration","required":true,"role":"symbol","symbolKind":"property","title":"preChatConfiguration","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preChatConfiguration","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIPreChatConfiguration","text":"PreChatConfiguration","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"preChatConfiguration","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/remoteconfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/preChatConfiguration":{"required":true,"type":"topic","title":"preChatConfiguration","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/preChatConfiguration","url":"\/documentation\/smiclientcore\/remoteconfiguration\/prechatconfiguration","abstract":[{"text":"The list of pre-chat configurations available for this deployment.","type":"text"},{"text":" ","type":"text"},{"text":"Each configuration defines a set of fields that can be displayed in the pre-chat form.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preChatConfiguration"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIPreChatConfiguration","text":"PreChatConfiguration"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"preChatConfiguration"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatConfiguration":{"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatConfiguration","title":"PreChatConfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration for a pre-chat form."}],"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"PreChatConfiguration","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechatconfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"preChatConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"preChatConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIPreChatConfiguration>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"preChatConfiguration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIRemoteConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"},{"value":"preChatConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1preChatConfiguration\/title"},{"value":[{"text":"preChatConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1preChatConfiguration\/fragments"},{"value":"SMIPreChatConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/title"},{"value":[{"kind":"identifier","text":"SMIPreChatConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/fragments"},{"value":[{"text":"SMIPreChatConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatConfiguration\/navigatorTitle"}]}]}