{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"termsAndConditions"}],"required":true,"role":"symbol","externalID":"c:objc(pl)SMIRemoteConfiguration(py)termsAndConditions","roleHeading":"Instance Property","title":"termsAndConditions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"termsAndConditions"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"TermsAndConditions","preciseIdentifier":"c:objc(pl)SMITermsAndConditions"},{"kind":"text","text":")?"}],"modules":[{"name":"SMIClientCore"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"termsAndConditions","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions","preciseIdentifier":"c:objc(pl)SMITermsAndConditions","text":"TermsAndConditions","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/termsandconditions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/termsandconditions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/termsAndConditions"},"sections":[],"abstract":[{"type":"text","text":"The terms and conditions that users must accept."},{"text":" ","type":"text"},{"text":"This object defines the terms and conditions text and acceptance requirements.","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/termsAndConditions":{"navigatorTitle":[{"kind":"identifier","text":"termsAndConditions"}],"abstract":[{"text":"The terms and conditions that users must accept.","type":"text"},{"text":" ","type":"text"},{"text":"This object defines the terms and conditions text and acceptance requirements.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/termsAndConditions","title":"termsAndConditions","role":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"termsAndConditions"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SMITermsAndConditions","kind":"typeIdentifier","text":"TermsAndConditions"},{"kind":"text","text":")?"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/remoteconfiguration\/termsandconditions"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TermsAndConditions":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsAndConditions"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TermsAndConditions","navigatorTitle":[{"kind":"identifier","text":"TermsAndConditions"}],"title":"TermsAndConditions","abstract":[{"text":"A protocol that defines the terms and conditions for the pre-chat form.","type":"text"}],"url":"\/documentation\/smiclientcore\/termsandconditions","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"url":"\/documentation\/smiclientcore\/remoteconfiguration","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"termsAndConditions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"termsAndConditions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMITermsAndConditions","text":"id<SMITermsAndConditions>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"termsAndConditions","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"termsAndConditions","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1termsAndConditions\/title"},{"value":[{"kind":"identifier","text":"termsAndConditions"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1termsAndConditions\/fragments"},{"value":"SMITermsAndConditions","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/title"},{"value":[{"text":"SMITermsAndConditions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/fragments"},{"value":[{"text":"SMITermsAndConditions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TermsAndConditions\/navigatorTitle"},{"value":"SMIRemoteConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}