{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/timestamp"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIRemoteConfiguration(py)timestamp","modules":[{"name":"SMIClientCore"}],"role":"symbol","required":true,"platforms":[{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"Mac Catalyst"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"timestamp","navigatorTitle":[{"kind":"identifier","text":"timestamp"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/timestamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/timestamp"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The timestamp when this configuration was last updated."},{"type":"text","text":" "},{"type":"text","text":"This value is used to track when the configuration was last modified on the server."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/timestamp":{"title":"timestamp","url":"\/documentation\/smiclientcore\/remoteconfiguration\/timestamp","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/timestamp","role":"symbol","required":true,"navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[{"type":"text","text":"The timestamp when this configuration was last updated."},{"type":"text","text":" "},{"type":"text","text":"This value is used to track when the configuration was last modified on the server."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"url":"\/documentation\/smiclientcore\/remoteconfiguration","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","role":"symbol","title":"RemoteConfiguration","navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration information for an embedded service deployment."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"timestamp","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1timestamp\/title","value":"timestamp","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title","value":"SMIRemoteConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments","value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}