{"abstract":[{"text":"The transcription configuration.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","required":true,"externalID":"c:objc(pl)SMIRemoteConfiguration(py)transcriptConfiguration","symbolKind":"property","title":"transcriptConfiguration","navigatorTitle":[{"text":"transcriptConfiguration","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transcriptConfiguration"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"TranscriptConfiguration","preciseIdentifier":"c:objc(pl)SMITranscriptConfiguration"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/transcriptconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/remoteconfiguration\/transcriptconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transcriptConfiguration"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMITranscriptConfiguration","text":"TranscriptConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/transcriptConfiguration"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteConfiguration"}],"abstract":[{"text":"A protocol that defines the configuration information for an embedded service deployment.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"RemoteConfiguration"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration","title":"RemoteConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RemoteConfiguration/transcriptConfiguration":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transcriptConfiguration","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"TranscriptConfiguration","preciseIdentifier":"c:objc(pl)SMITranscriptConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/remoteconfiguration\/transcriptconfiguration","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"transcriptConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The transcription configuration."}],"title":"transcriptConfiguration","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RemoteConfiguration\/transcriptConfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TranscriptConfiguration":{"abstract":[{"type":"text","text":"Protocol for defining configuration properties related to Transcription."}],"navigatorTitle":[{"text":"TranscriptConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TranscriptConfiguration","title":"TranscriptConfiguration","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranscriptConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/transcriptconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"transcriptConfiguration","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"transcriptConfiguration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMITranscriptConfiguration","text":"id<SMITranscriptConfiguration>"},{"kind":"text","text":" "},{"text":"transcriptConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIRemoteConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/title"},{"value":[{"text":"SMIRemoteConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SMIRemoteConfiguration"}]},{"value":"transcriptConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1transcriptConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"transcriptConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RemoteConfiguration~1transcriptConfiguration\/fragments","op":"replace"},{"value":"SMITranscriptConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/title","op":"replace"},{"value":[{"text":"SMITranscriptConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMITranscriptConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TranscriptConfiguration\/navigatorTitle","op":"replace"}]}]}