{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"The collection of available choice lists for pre-chat fields.","type":"text"},{"text":" ","type":"text"},{"text":"Each list in this array is a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList"},{"text":" that defines a set of options.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/choiceLists"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choicelistconfiguration\/choicelists"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choicelistconfiguration\/choicelists"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceLists","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ChoiceList","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","preciseIdentifier":"c:objc(pl)SMIChoiceList"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:objc(pl)SMIChoiceListConfiguration(py)choiceLists","title":"choiceLists","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choiceLists","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"ChoiceList","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceList"},{"text":"]?","kind":"text"}],"required":true,"role":"symbol","navigatorTitle":[{"text":"choiceLists","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration":{"title":"ChoiceListConfiguration","abstract":[{"text":"A protocol that defines the configuration for a collection of choice lists used in pre-chat.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","navigatorTitle":[{"kind":"identifier","text":"ChoiceListConfiguration"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistconfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceListConfiguration"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceList":{"title":"ChoiceList","abstract":[{"text":"A protocol that defines a collection of choice list values.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","navigatorTitle":[{"kind":"identifier","text":"ChoiceList"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/choicelist","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceList"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration/choiceLists":{"navigatorTitle":[{"kind":"identifier","text":"choiceLists"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"choiceLists"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceList","text":"ChoiceList"},{"kind":"text","text":"]?"}],"abstract":[{"text":"The collection of available choice lists for pre-chat fields.","type":"text"},{"text":" ","type":"text"},{"text":"Each list in this array is a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceList","type":"reference","isActive":true},{"text":" that defines a set of options.","type":"text"}],"url":"\/documentation\/smiclientcore\/choicelistconfiguration\/choicelists","required":true,"title":"choiceLists","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/choiceLists","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"choiceLists","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"choiceLists","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIChoiceList>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"choiceLists","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIChoiceListConfiguration","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/title"},{"value":[{"text":"SMIChoiceListConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SMIChoiceListConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/navigatorTitle","op":"replace"},{"value":"SMIChoiceList","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoiceList"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/fragments","op":"replace"},{"value":[{"text":"SMIChoiceList","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceList\/navigatorTitle","op":"replace"},{"value":"choiceLists","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1choiceLists\/title","op":"replace"},{"value":[{"kind":"identifier","text":"choiceLists"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1choiceLists\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}