{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueDependencies"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","preciseIdentifier":"c:objc(pl)SMIChoiceListDependency","text":"ChoiceListDependency"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choicelistconfiguration\/valuedependencies"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choicelistconfiguration\/valuedependencies"]}],"sections":[],"abstract":[{"text":"The relationships between different choice lists in pre-chat.","type":"text"},{"text":" ","type":"text"},{"text":"Each dependency in this array is a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","isActive":true,"type":"reference"},{"text":" that defines how choice lists","type":"text"},{"text":" ","type":"text"},{"text":"are related to each other.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueDependencies"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoiceListDependency","text":"ChoiceListDependency"},{"kind":"text","text":"]"}],"title":"valueDependencies","navigatorTitle":[{"kind":"identifier","text":"valueDependencies"}],"externalID":"c:objc(pl)SMIChoiceListConfiguration(py)valueDependencies","symbolKind":"property","required":true,"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/valueDependencies"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration/valueDependencies":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valueDependencies","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIChoiceListDependency","text":"ChoiceListDependency","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration\/valueDependencies","abstract":[{"type":"text","text":"The relationships between different choice lists in pre-chat."},{"type":"text","text":" "},{"type":"text","text":"Each dependency in this array is a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","isActive":true,"type":"reference"},{"type":"text","text":" that defines how choice lists"},{"type":"text","text":" "},{"type":"text","text":"are related to each other."}],"role":"symbol","url":"\/documentation\/smiclientcore\/choicelistconfiguration\/valuedependencies","required":true,"navigatorTitle":[{"text":"valueDependencies","kind":"identifier"}],"title":"valueDependencies","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListConfiguration":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListConfiguration","kind":"identifier"}],"title":"ChoiceListConfiguration","abstract":[{"type":"text","text":"A protocol that defines the configuration for a collection of choice lists used in pre-chat."}],"navigatorTitle":[{"text":"ChoiceListConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/choicelistconfiguration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceListDependency":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceListDependency","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that defines a dependency relationship between two choice lists in pre-chat."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceListDependency","kind":"symbol","navigatorTitle":[{"text":"ChoiceListDependency","kind":"identifier"}],"title":"ChoiceListDependency","url":"\/documentation\/smiclientcore\/choicelistdependency","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"valueDependencies","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"valueDependencies","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIChoiceListDependency>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"valueDependencies","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"valueDependencies","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1valueDependencies\/title","op":"replace"},{"value":[{"kind":"identifier","text":"valueDependencies"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration~1valueDependencies\/fragments","op":"replace"},{"value":"SMIChoiceListConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/title","op":"replace"},{"value":[{"text":"SMIChoiceListConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/fragments","op":"replace"},{"value":[{"text":"SMIChoiceListConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListConfiguration\/navigatorTitle","op":"replace"},{"value":"SMIChoiceListDependency","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoiceListDependency"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIChoiceListDependency"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceListDependency\/navigatorTitle","op":"replace"}]}]}