{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate"]]},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestTemplatedValues"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplateable","text":"SMITemplateable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplateable","text":"SMITemplateable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"core:didRequestTemplatedValues:completionHandler:"}],"role":"symbol","externalID":"c:objc(pl)SMITemplatedUrlDelegate(im)core:didRequestTemplatedValues:completionHandler:","modules":[{"name":"SMIClientCore"}],"title":"core(_:didRequestTemplatedValues:completionHandler:)","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/templatedurldelegate\/core(_:didrequesttemplatedvalues:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/templatedurldelegate\/core(_:didrequesttemplatedvalues:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Delegate event that is triggered when created a templated URL for an auto-response messaging component."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"core","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient","text":"CoreClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRequestTemplatedValues","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"values","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable","text":"SMITemplateable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"(any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable","text":"SMITemplateable","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"core"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestTemplatedValues"},{"kind":"text","text":" "},{"kind":"internalParam","text":"values"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","kind":"typeIdentifier","text":"SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> any ","kind":"text"},{"text":"SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"core","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance that is managing the current connection."}]}]},{"name":"values","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL parameters that will be used by the auto-response messaging component."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion"},{"type":"text","text":" that provides the values for the auto-response parameters."}]}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate\/core(_:didRequestTemplatedValues:completionHandler:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreFactory":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","abstract":[{"type":"text","text":"Factory for creating and managing instances of "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","isActive":true}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CoreFactory"}],"title":"CoreFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoreFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/corefactory"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMITemplateable":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMITemplateable","abstract":[{"text":"A protocol that defines the interface for managing template parameters in URLs.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMITemplateable","kind":"identifier"}],"title":"SMITemplateable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMITemplateable"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/smitemplateable"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Configuration":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration","abstract":[{"type":"text","text":"This class stores configuration information that is necessary when creating an "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference","isActive":true},{"type":"text","text":" instance using the "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/configuration"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedUrlDelegate":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate","role":"symbol","type":"topic","navigatorTitle":[{"text":"TemplatedUrlDelegate","kind":"identifier"}],"title":"TemplatedUrlDelegate","url":"\/documentation\/smiclientcore\/templatedurldelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplatedUrlDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Delegate that handles requests for auto-response messaging component parameter values."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CoreClient":{"url":"\/documentation\/smiclientcore\/coreclient","abstract":[{"text":"Main entry point for the In-App Messaging core API. To create an instance of this class, use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreFactory"},{"text":" ","type":"text"},{"text":"and provide an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Configuration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","role":"symbol","navigatorTitle":[{"text":"CoreClient","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreClient","kind":"identifier"}],"type":"topic","title":"CoreClient"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/URLParameterValueCompletion":{"url":"\/documentation\/smiclientcore\/urlparametervaluecompletion","abstract":[{"type":"text","text":"Completion block for a templated URL used by the auto-response messaging component."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion","role":"symbol","navigatorTitle":[{"text":"URLParameterValueCompletion","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLParameterValueCompletion","kind":"identifier"}],"type":"topic","title":"URLParameterValueCompletion"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/TemplatedUrlDelegate/core(_:didRequestTemplatedValues:completionHandler:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/TemplatedUrlDelegate\/core(_:didRequestTemplatedValues:completionHandler:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"core:didRequestTemplatedValues:completionHandler:","kind":"identifier"}],"required":true,"url":"\/documentation\/smiclientcore\/templatedurldelegate\/core(_:didrequesttemplatedvalues:completionhandler:)","title":"core(_:didRequestTemplatedValues:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"core"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"CoreClient","preciseIdentifier":"c:objc(pl)SMICoreClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestTemplatedValues"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SMITemplateable","preciseIdentifier":"c:objc(pl)SMITemplateable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMITemplateable","text":"SMITemplateable"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Delegate event that is triggered when created a templated URL for an auto-response messaging component.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"core:didRequestTemplatedValues:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"core:didRequestTemplatedValues:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"core:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMICoreClient>","preciseIdentifier":"c:Qoobjc(pl)SMICoreClient"},{"kind":"text","text":") "},{"kind":"internalParam","text":"core"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRequestTemplatedValues:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SMITemplateable>","preciseIdentifier":"c:Qoobjc(pl)SMITemplateable"},{"kind":"text","text":") "},{"kind":"internalParam","text":"values"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SMITemplatedUrlParametersCompletion","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion","preciseIdentifier":"c:SMITemplatedUrlDelegate.h@T@SMITemplatedUrlParametersCompletion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"core","content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CoreClient","type":"reference"},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}]},{"name":"values","content":[{"inlineContent":[{"text":"The URL parameters that will be used by the auto-response messaging component.","type":"text"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/URLParameterValueCompletion","isActive":true},{"type":"text","text":" that provides the values for the auto-response parameters."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SMICoreFactory","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/title","op":"replace"},{"value":[{"text":"SMICoreFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreFactory"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreFactory\/navigatorTitle","op":"replace"},{"value":"SMITemplateable","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/title","op":"replace"},{"value":[{"text":"SMITemplateable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMITemplateable"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMITemplateable\/navigatorTitle","op":"replace"},{"value":"SMICoreConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/title","op":"replace"},{"value":[{"text":"SMICoreConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMICoreConfiguration"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Configuration\/navigatorTitle","op":"replace"},{"value":"SMITemplatedUrlDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMITemplatedUrlDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/fragments","op":"replace"},{"value":[{"text":"SMITemplatedUrlDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate\/navigatorTitle","op":"replace"},{"value":"SMICoreClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/fragments","value":[{"text":"SMICoreClient","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SMICoreClient"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CoreClient\/navigatorTitle"},{"value":"SMITemplatedUrlParametersCompletion","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/title"},{"value":[{"text":"SMITemplatedUrlParametersCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/fragments"},{"value":[{"text":"SMITemplatedUrlParametersCompletion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1URLParameterValueCompletion\/navigatorTitle"},{"value":"core:didRequestTemplatedValues:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate~1core(_:didRequestTemplatedValues:completionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"core:didRequestTemplatedValues:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1TemplatedUrlDelegate~1core(_:didRequestTemplatedValues:completionHandler:)\/fragments"}]}]}