{"sections":[],"metadata":{"title":"init(rawValue:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:So23SMIAcknowledgementTypesV8rawValueABSgSi_tcfc"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes\/init(rawValue:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/acknowledgementtypes\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AcknowledgementTypes/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/smiclientcore\/acknowledgementtypes\/init(rawvalue:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AcknowledgementTypes":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AcknowledgementTypes"}],"type":"topic","abstract":[{"text":"An enum that defines the types of acknowledgements that can be associated with a conversation entry.","type":"text"},{"text":" ","type":"text"},{"text":"These types are used by ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","type":"reference"},{"text":" to track message delivery and read status.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AcknowledgementTypes"}],"title":"AcknowledgementTypes","url":"\/documentation\/smiclientcore\/acknowledgementtypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryAck","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that represents an acknowledgement within a "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","kind":"symbol","navigatorTitle":[{"text":"EntryAck","kind":"identifier"}],"title":"EntryAck","url":"\/documentation\/smiclientcore\/entryack","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/title","op":"replace","value":"SMIAcknowledgementTypes"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/fragments","op":"replace","value":[{"text":"SMIAcknowledgementTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/navigatorTitle","op":"replace","value":[{"text":"SMIAcknowledgementTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/title","op":"replace","value":"SMIEntryAck"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/fragments","op":"replace","value":[{"text":"SMIEntryAck","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/navigatorTitle","op":"replace","value":[{"text":"SMIEntryAck","kind":"identifier"}]}]}]}