{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes\/unknown"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/acknowledgementtypes\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/acknowledgementtypes\/unknown"]}],"abstract":[{"text":"An invalid or unknown acknowledgement type.","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"SMIAcknowledgementTypesUnknown","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@SMIAcknowledgementTypes@SMIAcknowledgementTypesUnknown","role":"symbol","symbolKind":"case","modules":[{"name":"SMIClientCore"}],"title":"AcknowledgementTypes.unknown"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AcknowledgementTypes":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AcknowledgementTypes"}],"type":"topic","abstract":[{"text":"An enum that defines the types of acknowledgements that can be associated with a conversation entry.","type":"text"},{"text":" ","type":"text"},{"text":"These types are used by ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","type":"reference"},{"text":" to track message delivery and read status.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AcknowledgementTypes"}],"title":"AcknowledgementTypes","url":"\/documentation\/smiclientcore\/acknowledgementtypes","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AcknowledgementTypes/unknown":{"type":"topic","navigatorTitle":[{"text":"SMIAcknowledgementTypesUnknown","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/acknowledgementtypes\/unknown","role":"symbol","title":"AcknowledgementTypes.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AcknowledgementTypes\/unknown","kind":"symbol","abstract":[{"text":"An invalid or unknown acknowledgement type.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryAck":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EntryAck","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A protocol that represents an acknowledgement within a "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryAck","kind":"symbol","navigatorTitle":[{"text":"EntryAck","kind":"identifier"}],"title":"EntryAck","url":"\/documentation\/smiclientcore\/entryack","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIAcknowledgementTypesUnknown","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIAcknowledgementTypesUnknown","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SMIAcknowledgementTypesUnknown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIAcknowledgementTypes","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIAcknowledgementTypes"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes\/navigatorTitle","value":[{"kind":"identifier","text":"SMIAcknowledgementTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes~1unknown\/title","value":"SMIAcknowledgementTypesUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AcknowledgementTypes~1unknown\/fragments","value":[{"kind":"identifier","text":"SMIAcknowledgementTypesUnknown"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/title","value":"SMIEntryAck","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/fragments","value":[{"kind":"identifier","text":"SMIEntryAck"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryAck\/navigatorTitle","value":[{"kind":"identifier","text":"SMIEntryAck"}],"op":"replace"}]}]}