{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/connected","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@SMINetworkConnectivityStateConnected","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}],"extendedModule":"SMIClientCore","role":"symbol","title":"connected","navigatorTitle":[{"text":"SMINetworkConnectivityStateConnected","kind":"identifier"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","text":"NetworkConnectivityState","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState"]]},"abstract":[{"text":"The device has an active network connection.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the device is connected to a network and","type":"text"},{"text":" ","type":"text"},{"text":"can communicate with remote services.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/connected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/connected"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/connected":{"navigatorTitle":[{"text":"SMINetworkConnectivityStateConnected","kind":"identifier"}],"title":"connected","url":"\/documentation\/smiclientcore\/networkconnectivitystate\/connected","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState","text":"NetworkConnectivityState","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The device has an active network connection."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the device is connected to a network and"},{"type":"text","text":" "},{"type":"text","text":"can communicate with remote services."}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/connected","type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState":{"role":"symbol","title":"NetworkConnectivityState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectivityState","kind":"identifier"}],"navigatorTitle":[{"text":"NetworkConnectivityState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","url":"\/documentation\/smiclientcore\/networkconnectivitystate","type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible states of network connectivity."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SMINetworkConnectivityStateConnected"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMINetworkConnectivityStateConnected","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","kind":"typeIdentifier","text":"SMINetworkConnectivityState"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMINetworkConnectivityStateConnected"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1connected\/title","op":"replace","value":"SMINetworkConnectivityStateConnected"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1connected\/fragments","op":"replace","value":[{"text":"SMINetworkConnectivityStateConnected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/title","op":"replace","value":"SMINetworkConnectivityState"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/fragments","op":"replace","value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMINetworkConnectivityState"}]}]}]}