{"kind":"article","metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"SMIClientCore"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/equatable-implementations"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","role":"symbol","url":"\/documentation\/smiclientcore\/networkconnectivitystate","abstract":[{"text":"An enum that defines the possible states of network connectivity.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectivityState"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectivityState"}],"title":"NetworkConnectivityState"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/!=(_:_:)":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/!=(_:_:)","role":"symbol","url":"\/documentation\/smiclientcore\/networkconnectivitystate\/!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"value":"SMINetworkConnectivityState","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMINetworkConnectivityState"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/fragments","op":"replace"},{"value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}