{"metadata":{"role":"symbol","title":"hash(into:)","symbolKind":"method","roleHeading":"Instance Method","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"modules":[{"name":"SMIClientCore","relatedModules":["Swift"]}],"externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState","extendedModule":"Swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/_SwiftNewtypeWrapper-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"_SwiftNewtypeWrapper.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/hash(into:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/hash(into:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/hash(into:)","abstract":[],"url":"\/documentation\/smiclientcore\/networkconnectivitystate\/hash(into:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"kind":"symbol","title":"hash(into:)","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/_SwiftNewtypeWrapper-Implementations":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate\/_swiftnewtypewrapper-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/_SwiftNewtypeWrapper-Implementations","abstract":[],"type":"topic","title":"_SwiftNewtypeWrapper Implementations"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NetworkConnectivityState","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","abstract":[{"type":"text","text":"An enum that defines the possible states of network connectivity."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectivityState","kind":"identifier"}],"type":"topic","title":"NetworkConnectivityState"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/title","value":"SMINetworkConnectivityState"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/fragments","value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/navigatorTitle","value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}