{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}]}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/offline","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/offline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/networkconnectivitystate\/offline"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState"]]},"metadata":{"role":"symbol","symbolKind":"property","title":"offline","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState","text":"NetworkConnectivityState","kind":"typeIdentifier"}],"externalID":"c:@SMINetworkConnectivityStateOffline","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"SMINetworkConnectivityStateOffline","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The device is currently offline and unable to connect to the network."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the device has no active network connection"},{"type":"text","text":" "},{"type":"text","text":"and cannot communicate with remote services."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState/offline":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate\/offline","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState\/offline","type":"topic","kind":"symbol","abstract":[{"text":"The device is currently offline and unable to connect to the network.","type":"text"},{"text":" ","type":"text"},{"text":"This state indicates that the device has no active network connection","type":"text"},{"text":" ","type":"text"},{"text":"and cannot communicate with remote services.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SMINetworkConnectivityStateOffline","kind":"identifier"}],"title":"offline","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NetworkConnectivityState","kind":"typeIdentifier","preciseIdentifier":"c:SMINetworkConnectivityState.h@T@SMINetworkConnectivityState"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/NetworkConnectivityState":{"url":"\/documentation\/smiclientcore\/networkconnectivitystate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NetworkConnectivityState","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/NetworkConnectivityState","abstract":[{"type":"text","text":"An enum that defines the possible states of network connectivity."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectivityState","kind":"identifier"}],"type":"topic","title":"NetworkConnectivityState"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMINetworkConnectivityStateOffline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SMINetworkConnectivityStateOffline","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMINetworkConnectivityStateOffline","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1offline\/title","value":"SMINetworkConnectivityStateOffline"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState~1offline\/fragments","value":[{"kind":"identifier","text":"SMINetworkConnectivityStateOffline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/title","value":"SMINetworkConnectivityState"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/fragments","value":[{"text":"SMINetworkConnectivityState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1NetworkConnectivityState\/navigatorTitle","value":[{"kind":"identifier","text":"SMINetworkConnectivityState"}]}]}]}