{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"s:So25SMIProgressIndicatorTypesa8rawValueABSS_tcfc","title":"init(rawValue:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/init(rawValue:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/progressindicatortypes\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes":{"kind":"symbol","navigatorTitle":[{"text":"ProgressIndicatorTypes","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressIndicatorTypes","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","url":"\/documentation\/smiclientcore\/progressindicatortypes","abstract":[{"text":"An enum that defines the possible types of progress indicators in a conversation.","type":"text"}],"title":"ProgressIndicatorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/init(rawValue:)":{"url":"\/documentation\/smiclientcore\/progressindicatortypes\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/init(rawValue:)","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SMIProgressIndicatorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/title"},{"value":[{"kind":"identifier","text":"SMIProgressIndicatorTypes"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/fragments"},{"value":[{"text":"SMIProgressIndicatorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/navigatorTitle"}]}]}