{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes"]]},"abstract":[{"text":"Indicates the action of updating progress information.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","preciseIdentifier":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes","text":"ProgressIndicatorTypes"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/update"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/progressindicatortypes\/update"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/progressindicatortypes\/update"]}],"metadata":{"symbolKind":"property","externalID":"c:@SMIProgressIndicatorTypesUpdate","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"role":"symbol","extendedModule":"SMIClientCore","title":"update","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ProgressIndicatorTypes","preciseIdentifier":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIProgressIndicatorTypesUpdate","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes":{"kind":"symbol","navigatorTitle":[{"text":"ProgressIndicatorTypes","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressIndicatorTypes","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","url":"\/documentation\/smiclientcore\/progressindicatortypes","abstract":[{"text":"An enum that defines the possible types of progress indicators in a conversation.","type":"text"}],"title":"ProgressIndicatorTypes"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicatorTypes/update":{"navigatorTitle":[{"text":"SMIProgressIndicatorTypesUpdate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/progressindicatortypes\/update","abstract":[{"type":"text","text":"Indicates the action of updating progress information."}],"title":"update","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes","text":"ProgressIndicatorTypes","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes\/update","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIProgressIndicatorTypesUpdate","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SMIProgressIndicatorTypesUpdate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIProgressIndicatorTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicatorTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIProgressIndicatorTypes.h@T@SMIProgressIndicatorTypes"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIProgressIndicatorTypesUpdate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIProgressIndicatorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/title"},{"value":[{"text":"SMIProgressIndicatorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/fragments"},{"value":[{"text":"SMIProgressIndicatorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes\/navigatorTitle"},{"op":"replace","value":"SMIProgressIndicatorTypesUpdate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes~1update\/title"},{"op":"replace","value":[{"text":"SMIProgressIndicatorTypesUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicatorTypes~1update\/fragments"}]}]}