{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceiveentries:paged:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceiveentries:paged:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveEntries","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"entries","kind":"internalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"paged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","type":"reference","isActive":true},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"client"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" data models. Each entry represents an incoming\/outgoing message.","type":"text"}]}],"name":"entries"},{"content":[{"inlineContent":[{"type":"text","text":"Indicates whether this event was fired as a result of a database paging request."},{"type":"text","text":" "},{"type":"text","text":"These entries are a result of requesting additional or missing entries from the local database populated from the service."}],"type":"paragraph"}],"name":"paged"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"The subject on the sender can be checked to determine whether a specific entry was sent by a local","type":"text"},{"text":" ","type":"text"},{"text":"participant.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Outbound entries are echoed back on this event due to the chance it could be modified"},{"type":"text","text":" "},{"type":"text","text":"by any configured sensitive data rules. This event is also an acknowledgement that"},{"type":"text","text":" "},{"type":"text","text":"the entries have been cached locally."}]},{"type":"paragraph","inlineContent":[{"text":"The best practice, if choosing to display outgoing entries, is to wait for this event rather","type":"text"},{"text":" ","type":"text"},{"text":"than displaying entries directly.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEntries:paged:)"},"abstract":[{"text":"Delegate event that is triggered when entries have been added to a conversation.","type":"text"},{"text":" ","type":"text"},{"text":"This fires for both inbound and outbound entries.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didReceiveEntries","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":"], ","kind":"text"},{"text":"paged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"SMIClientCore"}],"title":"client(_:didReceiveEntries:paged:)","externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didReceiveEntries:paged:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"client:didReceiveEntries:paged:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveEntries:paged:)":{"abstract":[{"type":"text","text":"Delegate event that is triggered when entries have been added to a conversation."},{"type":"text","text":" "},{"type":"text","text":"This fires for both inbound and outbound entries."}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceiveentries:paged:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didReceiveEntries","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":"], ","kind":"text"},{"text":"paged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveEntries:paged:)","title":"client(_:didReceiveEntries:paged:)","navigatorTitle":[{"text":"client:didReceiveEntries:paged:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"title":"ConversationClientDelegate","type":"topic","url":"\/documentation\/smiclientcore\/conversationclientdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"kind":"symbol","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"client:didReceiveEntries:paged:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveEntries:paged:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"client:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient","kind":"typeIdentifier","text":"id<SMIConversationClient>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"client"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveEntries:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<SMIConversationEntry>>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entries"},{"kind":"text","text":" "},{"kind":"identifier","text":"paged:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"paged"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true,"type":"reference"},{"text":" instance that is managing the current connection.","type":"text"}],"type":"paragraph"}],"name":"client"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"type":"text","text":" data models. Each entry represents an incoming\/outgoing message."}]}],"name":"entries"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Indicates whether this event was fired as a result of a database paging request.","type":"text"},{"text":" ","type":"text"},{"text":"These entries are a result of requesting additional or missing entries from the local database populated from the service.","type":"text"}]}],"name":"paged"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEntries:paged:)\/title","value":"client:didReceiveEntries:paged:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveEntries:paged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveEntries:paged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","value":"SMIConversationClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}