{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateActiveModalities:)"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"client:didUpdateActiveModalities:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateActiveModalities"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality"},{"kind":"text","text":"])"}],"externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didUpdateActiveModalities:","modules":[{"name":"SMIClientCore"}],"title":"client(_:didUpdateActiveModalities:)"},"abstract":[{"text":"Delegate event that is triggered when the active modalities on a conversation have changed.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateActiveModalities","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"activeModalities","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true},{"text":" instance that is managing the current connection.","type":"text"}]}],"name":"client"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of active Modalities on the conversation.","type":"text"}]}],"name":"activeModalities"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateactivemodalities:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateactivemodalities:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","title":"ConversationClientDelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateActiveModalities:)":{"abstract":[{"text":"Delegate event that is triggered when the active modalities on a conversation have changed.","type":"text"}],"navigatorTitle":[{"text":"client:didUpdateActiveModalities:","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateActiveModalities:)","title":"client(_:didUpdateActiveModalities:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"client"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didUpdateActiveModalities","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Modality","preciseIdentifier":"c:SMIModality.h@T@SMIModality","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateactivemodalities:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"client:didUpdateActiveModalities:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didUpdateActiveModalities:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIConversationClient>","preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateActiveModalities:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"activeModalities","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true,"type":"reference"},{"text":" instance that is managing the current connection.","type":"text"}]}]},{"name":"activeModalities","content":[{"inlineContent":[{"text":"The array of active Modalities on the conversation.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","value":"SMIConversationClientDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title"},{"op":"replace","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"value":"client:didUpdateActiveModalities:","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateActiveModalities:)\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateActiveModalities:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"client:didUpdateActiveModalities:"}],"op":"replace"}]}]}