{"metadata":{"modules":[{"name":"SMIClientCore"}],"title":"client(_:didReceiveTypingStoppedEvent:)","externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didReceiveTypingStoppedEvent:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveTypingStoppedEvent","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"client:didReceiveTypingStoppedEvent:","kind":"identifier"}],"platforms":[],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"abstract":[{"text":"Delegate event that is triggered when receiving a typing stopped event from another participant.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceivetypingstoppedevent:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceivetypingstoppedevent:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"client"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTypingStoppedEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"client","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}]},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry"},{"text":" which contains the typing event as a payload.","type":"text"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStoppedEvent:)"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed in a future version. Use `-client:didReceiveEvents:` instead."}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"title":"ConversationClientDelegate","abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate","type":"topic","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didReceiveTypingStoppedEvent:)":{"title":"client(_:didReceiveTypingStoppedEvent:)","deprecated":true,"abstract":[{"text":"Delegate event that is triggered when receiving a typing stopped event from another participant.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTypingStoppedEvent"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry","text":"ConversationEntry"},{"kind":"text","text":")"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didreceivetypingstoppedevent:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"client:didReceiveTypingStoppedEvent:"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didReceiveTypingStoppedEvent:)","kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"title":"ConversationClient","abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclient","type":"topic","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"client:didReceiveTypingStoppedEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didReceiveTypingStoppedEvent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient","text":"id<SMIConversationClient>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveTypingStoppedEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry","text":"id<SMIConversationEntry>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","type":"reference","isActive":true},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"client"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":" which contains the typing event as a payload."}],"type":"paragraph"}],"name":"event"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","value":"SMIConversationClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"text":"SMIConversationEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStoppedEvent:)\/title","value":"client:didReceiveTypingStoppedEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didReceiveTypingStoppedEvent:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveTypingStoppedEvent:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}