{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateUnreadMessageCount:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateUnreadMessageCount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}]}]},{"name":"count","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of current unread messages."}]}]}],"kind":"parameters"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"metadata":{"modules":[{"name":"SMIClientCore"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"client:didUpdateUnreadMessageCount:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didUpdateUnreadMessageCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didUpdateUnreadMessageCount:","title":"client(_:didUpdateUnreadMessageCount:)","symbolKind":"method"},"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateunreadmessagecount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateunreadmessagecount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Delegate event that is triggered when the unread message counter is updated","type":"text"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateUnreadMessageCount:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateUnreadMessageCount:)","role":"symbol","navigatorTitle":[{"text":"client:didUpdateUnreadMessageCount:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"client(_:didUpdateUnreadMessageCount:)","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateunreadmessagecount:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateUnreadMessageCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Delegate event that is triggered when the unread message counter is updated","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"title":"ConversationClientDelegate","type":"topic","url":"\/documentation\/smiclientcore\/conversationclientdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"kind":"symbol","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"client:didUpdateUnreadMessageCount:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateUnreadMessageCount:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient","text":"id<SMIConversationClient>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateUnreadMessageCount:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","type":"reference","isActive":true},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}],"name":"client"},{"content":[{"inlineContent":[{"text":"The number of current unread messages.","type":"text"}],"type":"paragraph"}],"name":"count"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"client:didUpdateUnreadMessageCount:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateUnreadMessageCount:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didUpdateUnreadMessageCount:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateUnreadMessageCount:)\/fragments"},{"op":"replace","value":"SMIConversationClient","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title"},{"op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments"},{"op":"replace","value":[{"text":"SMIConversationClient","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle"},{"op":"replace","value":"SMIConversationClientDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title"},{"op":"replace","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIConversationClientDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}