{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"client(_:didUpdate:)","navigatorTitle":[{"text":"client:didUpdateEntry:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didUpdateEntry:","platforms":[{"beta":false,"message":"Will be removed in a future version. Use `-client:didUpdateEntries:` instead.","deprecated":true,"unavailable":false}],"role":"symbol","modules":[{"name":"SMIClientCore"}]},"abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)"],"anchor":"Related-Documentation","title":"Related Documentation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"client"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier","text":"ConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"entry"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier","text":"ConversationEntry"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}]}]},{"name":"entry","content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true,"type":"reference"},{"text":" data model which represents an incoming\/outgoing message.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdate:)-jlte"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdate:)-jlte"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Will be removed in a future version. Use `-client:didUpdateEntries:` instead.","type":"text"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-jlte"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"kind":"symbol","title":"ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEntry"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdate:)-jlte":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdate:)-jlte","abstract":[{"text":"Delegate event that is triggered when a message’s status has been updated.","type":"text"},{"text":" ","type":"text"},{"text":"It is recommended that any current references to an entry with a matching ID are refreshed.","type":"text"},{"text":" ","type":"text"},{"text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI","type":"text"},{"text":" ","type":"text"},{"text":"should account for that.","type":"text"}],"title":"client(_:didUpdate:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"ConversationEntry","preciseIdentifier":"c:objc(pl)SMIConversationEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdate:)-jlte","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"client:didUpdateEntry:","kind":"identifier"}],"deprecated":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateEntries:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didUpdateEntries","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"ConversationEntry","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationEntry"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"client:didUpdateEntries:","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdateentries:)","abstract":[{"type":"text","text":"Delegate event that is triggered when a message’s status has been updated."},{"type":"text","text":" "},{"type":"text","text":"It is recommended that any current references to an entry with a matching ID are refreshed."},{"type":"text","text":" "},{"type":"text","text":"It is possible for entries to change type entirely due to backend translation, and any consuming UI"},{"type":"text","text":" "},{"type":"text","text":"should account for that."}],"title":"client(_:didUpdateEntries:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"title":"ConversationClientDelegate","type":"topic","url":"\/documentation\/smiclientcore\/conversationclientdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"kind":"symbol","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationClient"}],"title":"ConversationClient","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","url":"\/documentation\/smiclientcore\/conversationclient","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"abstract":[{"type":"text","text":"Class that allows you to perform actions related to a conversation and to listen"},{"type":"text","text":" "},{"type":"text","text":"for events using the associated delegate."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"client:didUpdateEntry:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateEntry:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateEntries:)"],"anchor":"Related-Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIConversationClient>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateEntry:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIConversationEntry>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConversationEntry"},{"text":") ","kind":"text"},{"text":"entry","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"client"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":" data model which represents an incoming\/outgoing message."}],"type":"paragraph"}],"name":"entry"}],"kind":"parameters"}},{"op":"replace","path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"Will be removed in a future version. Use `-client:didUpdateEntries:` instead.","type":"text"}],"type":"paragraph"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-jlte\/title","value":"client:didUpdateEntry:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdate:)-jlte\/fragments","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateEntry:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateEntries:)\/title","value":"client:didUpdateEntries:"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateEntries:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didUpdateEntries:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","value":"SMIConversationClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"text":"SMIConversationClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}]}]}]}