{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","isActive":true,"type":"reference"},{"type":"text","text":" instance that is managing the current connection."}]}],"name":"client"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"NSError"},{"text":" which triggered this event.","type":"text"}]}],"name":"error"}]}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate event that is triggered if an unhandled error is detected as part"},{"type":"text","text":" "},{"type":"text","text":"of the normal activity of the In-App Messaging client."}],"variants":[{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:diderror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:diderror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didError:","navigatorTitle":[{"text":"client:didError:","kind":"identifier"}],"role":"symbol","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"client(_:didError:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"role":"symbol","title":"ConversationClientDelegate","navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didError:)":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didError:)","abstract":[{"text":"Delegate event that is triggered if an unhandled error is detected as part","type":"text"},{"text":" ","type":"text"},{"text":"of the normal activity of the In-App Messaging client.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"kind":"symbol","title":"client(_:didError:)","navigatorTitle":[{"text":"client:didError:","kind":"identifier"}],"type":"topic","url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:diderror:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClient","kind":"identifier"}],"abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"text":"for events using the associated delegate.","type":"text"}],"url":"\/documentation\/smiclientcore\/conversationclient","role":"symbol","navigatorTitle":[{"text":"ConversationClient","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"client:didError:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didError:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SMIConversationClient>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}]}]},{"name":"error","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"NSError"},{"text":" which triggered this event.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","op":"replace","value":"SMIConversationClientDelegate"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","op":"replace","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","op":"replace","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didError:)\/title","op":"replace","value":"client:didError:"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didError:"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","op":"replace","value":"SMIConversationClient"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIConversationClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}