{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"ConversationClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIConversationClient"},{"text":", ","kind":"text"},{"text":"didUpdateSupportedModalities","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"client:didUpdateSupportedModalities:"}],"role":"symbol","externalID":"c:objc(pl)SMIConversationClientDelegate(im)client:didUpdateSupportedModalities:","modules":[{"name":"SMIClientCore"}],"title":"client(_:didUpdateSupportedModalities:)","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdatesupportedmodalities:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdatesupportedmodalities:)"]}],"abstract":[{"type":"text","text":"Delegate event that is triggered when the supported modalities on a conversation have changed."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"ConversationClient","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","preciseIdentifier":"c:objc(pl)SMIConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateSupportedModalities","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"Modality","preciseIdentifier":"c:SMIModality.h@T@SMIModality","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}],"name":"client"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of supported Modalities on the conversation.","type":"text"}]}],"name":"supportedModalities"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateSupportedModalities:)"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate/client(_:didUpdateSupportedModalities:)":{"url":"\/documentation\/smiclientcore\/conversationclientdelegate\/client(_:didupdatesupportedmodalities:)","abstract":[{"text":"Delegate event that is triggered when the supported modalities on a conversation have changed.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate\/client(_:didUpdateSupportedModalities:)","role":"symbol","navigatorTitle":[{"text":"client:didUpdateSupportedModalities:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIConversationClient","text":"ConversationClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateSupportedModalities","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","title":"client(_:didUpdateSupportedModalities:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClientDelegate":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationClientDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate that handles events related to a conversation."}],"navigatorTitle":[{"text":"ConversationClientDelegate","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationclientdelegate","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClientDelegate","title":"ConversationClientDelegate"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationClient":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationClient"}],"url":"\/documentation\/smiclientcore\/conversationclient","title":"ConversationClient","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationClient"}],"kind":"symbol","abstract":[{"text":"Class that allows you to perform actions related to a conversation and to listen","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for events using the associated delegate."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"client:didUpdateSupportedModalities:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didUpdateSupportedModalities:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"client:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIConversationClient","text":"id<SMIConversationClient>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"client"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateSupportedModalities:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"supportedModalities"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationClient"},{"type":"text","text":" instance that is managing the current connection."}],"type":"paragraph"}],"name":"client"},{"content":[{"inlineContent":[{"type":"text","text":"The array of supported Modalities on the conversation."}],"type":"paragraph"}],"name":"supportedModalities"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateSupportedModalities:)\/title","value":"client:didUpdateSupportedModalities:","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate~1client(_:didUpdateSupportedModalities:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"client:didUpdateSupportedModalities:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/title","value":"SMIConversationClientDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/fragments","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClientDelegate\/navigatorTitle","value":[{"text":"SMIConversationClientDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/title","value":"SMIConversationClient","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/fragments","value":[{"kind":"identifier","text":"SMIConversationClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationClient\/navigatorTitle","value":[{"text":"SMIConversationClient","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}