{"abstract":[{"text":"The data type of the input.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the specific type of input field, such as text, date picker,","type":"text"},{"text":" ","type":"text"},{"text":"option picker, or select input.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/forminput\/inputtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminput\/inputtype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"externalID":"c:objc(pl)SMIFormInput(py)inputType","required":true,"role":"symbol","symbolKind":"property","title":"inputType","navigatorTitle":[{"text":"inputType","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/inputType","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"],"anchor":"Related-Documentation","title":"Related Documentation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputType":{"title":"FormInputType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of form input fields available in the system."}],"role":"symbol","type":"topic","url":"\/documentation\/smiclientcore\/forminputtype","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormInputType","kind":"identifier"}],"navigatorTitle":[{"text":"FormInputType","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/inputType":{"required":true,"navigatorTitle":[{"text":"inputType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"}],"abstract":[{"text":"The data type of the input.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the specific type of input field, such as text, date picker,","type":"text"},{"text":" ","type":"text"},{"text":"option picker, or select input.","type":"text"}],"url":"\/documentation\/smiclientcore\/forminput\/inputtype","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/inputType","role":"symbol","title":"inputType","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"url":"\/documentation\/smiclientcore\/forminput","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInput"}],"kind":"symbol","title":"FormInput","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormInput"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"inputType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"inputType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType"],"anchor":"Related-Documentation"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputType","text":"SMIFormInputType","preciseIdentifier":"c:SMIFormInputType.h@T@SMIFormInputType"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIFormInputType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/title"},{"value":[{"text":"SMIFormInputType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/fragments"},{"value":[{"text":"SMIFormInputType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputType\/navigatorTitle"},{"value":"inputType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1inputType\/title"},{"value":[{"text":"inputType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1inputType\/fragments"},{"value":"SMIFormInput","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title"},{"value":[{"kind":"identifier","text":"SMIFormInput"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments"},{"value":[{"text":"SMIFormInput","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle"}]}]}