{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput"]]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"],"title":"Related Documentation","anchor":"Related-Documentation"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIFormErrorType","text":"FormErrorType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/smiclientcore\/forminput\/validate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/forminput\/validate()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Use this validation to determine if the current value for this input is valid."},{"type":"text","text":" "},{"type":"text","text":"This method checks if the input’s current value meets all validation requirements."}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/validate()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"FormErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIFormErrorType"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"validate","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormInput(im)validate","role":"symbol","modules":[{"name":"SMIClientCore"}],"title":"validate()","required":true},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormErrorType":{"navigatorTitle":[{"kind":"identifier","text":"FormErrorType"}],"title":"FormErrorType","abstract":[{"type":"text","text":"An enum that defines validation error types for form inputs."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormErrorType"}],"url":"\/documentation\/smiclientcore\/formerrortype"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput/validate()":{"kind":"symbol","title":"validate()","url":"\/documentation\/smiclientcore\/forminput\/validate()","type":"topic","role":"symbol","navigatorTitle":[{"text":"validate","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"FormErrorType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIFormErrorType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput\/validate()","abstract":[{"type":"text","text":"Use this validation to determine if the current value for this input is valid."},{"type":"text","text":" "},{"type":"text","text":"This method checks if the input’s current value meets all validation requirements."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInput":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInput","abstract":[{"text":"A protocol that defines the base type for form input fields.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormInput"}],"url":"\/documentation\/smiclientcore\/forminput","navigatorTitle":[{"kind":"identifier","text":"FormInput"}],"title":"FormInput","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validate","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validate"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"],"anchor":"Related-Documentation","title":"Related Documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@SMIFormErrorType","text":"SMIFormErrorType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormErrorType"},{"text":") ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIFormErrorType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/title"},{"op":"replace","value":[{"text":"SMIFormErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormErrorType\/navigatorTitle","value":[{"text":"SMIFormErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1validate()\/title","value":"validate"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput~1validate()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/title","value":"SMIFormInput"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/fragments","value":[{"kind":"identifier","text":"SMIFormInput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInput\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormInput"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}