{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"channelAddressIdentifier","externalID":"c:objc(pl)SMISessionStatusChanged(py)channelAddressIdentifier","required":true,"modules":[{"name":"SMIClientCore"}],"symbolKind":"property","navigatorTitle":[{"text":"channelAddressIdentifier","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelAddressIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/channelAddressIdentifier","interfaceLanguage":"swift"},"abstract":[{"text":"The channel address identifier for the session.","type":"text"},{"text":" ","type":"text"},{"text":"This property identifies the channel through which the session is conducted.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelAddressIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/sessionstatuschanged\/channeladdressidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessionstatuschanged\/channeladdressidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged":{"kind":"symbol","type":"topic","role":"symbol","title":"SessionStatusChanged","url":"\/documentation\/smiclientcore\/sessionstatuschanged","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionStatusChanged","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","abstract":[{"type":"text","text":"A protocol that represents a session status change event within a conversation."}],"navigatorTitle":[{"text":"SessionStatusChanged","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/channelAddressIdentifier":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/channelAddressIdentifier","required":true,"abstract":[{"type":"text","text":"The channel address identifier for the session."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the channel through which the session is conducted."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"channelAddressIdentifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelAddressIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/smiclientcore\/sessionstatuschanged\/channeladdressidentifier","title":"channelAddressIdentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"channelAddressIdentifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"channelAddressIdentifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"channelAddressIdentifier","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SMISessionStatusChanged","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/title"},{"op":"replace","value":[{"text":"SMISessionStatusChanged","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/navigatorTitle"},{"op":"replace","value":"channelAddressIdentifier","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1channelAddressIdentifier\/title"},{"op":"replace","value":[{"text":"channelAddressIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1channelAddressIdentifier\/fragments"}]}]}