{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"sessionStatusPrev","externalID":"c:objc(pl)SMISessionStatusChanged(py)sessionStatusPrev","modules":[{"name":"SMIClientCore"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionStatusPrev","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SessionStatus","kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sessionStatusPrev","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatusPrev","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"],"title":"Related Documentation"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstatusprev"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstatusprev"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStatusPrev"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","kind":"typeIdentifier","text":"SessionStatus"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The previous status of the session before the change.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatus":{"navigatorTitle":[{"kind":"identifier","text":"SessionStatus"}],"url":"\/documentation\/smiclientcore\/sessionstatus","title":"SessionStatus","abstract":[{"type":"text","text":"An enum that defines the possible states of a session."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionStatus"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged/sessionStatusPrev":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStatusPrev"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SessionStatus"},{"kind":"text","text":"?"}],"title":"sessionStatusPrev","required":true,"navigatorTitle":[{"kind":"identifier","text":"sessionStatusPrev"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged\/sessionStatusPrev","abstract":[{"type":"text","text":"The previous status of the session before the change."}],"url":"\/documentation\/smiclientcore\/sessionstatuschanged\/sessionstatusprev"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionStatusChanged":{"url":"\/documentation\/smiclientcore\/sessionstatuschanged","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SessionStatusChanged"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatusChanged","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionStatusChanged"}],"title":"SessionStatusChanged","type":"topic","abstract":[{"type":"text","text":"A protocol that represents a session status change event within a conversation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sessionStatusPrev","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"sessionStatusPrev"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMISessionStatus.h@T@SMISessionStatus","text":"SMISessionStatus","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionStatusPrev"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SMISessionStatus","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatus"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatus\/navigatorTitle"},{"op":"replace","value":"sessionStatusPrev","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatusPrev\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sessionStatusPrev"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged~1sessionStatusPrev\/fragments"},{"op":"replace","value":"SMISessionStatusChanged","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMISessionStatusChanged"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionStatusChanged\/navigatorTitle"}]}]}