{"variants":[{"paths":["\/documentation\/smiclientcore\/richlinkmessage\/title"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/richlinkmessage\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage\/title"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"text":"The title of the rich link message.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage"]]},"metadata":{"symbolKind":"property","required":true,"role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:objc(pl)SMIRichLinkMessage(py)title","title":"title","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage":{"abstract":[{"type":"text","text":"A protocol that represents a rich link message within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"RichLinkMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","title":"RichLinkMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RichLinkMessage","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/richlinkmessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage/title":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage\/title","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/richlinkmessage\/title","abstract":[{"text":"The title of the rich link message.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"title","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"title","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"title"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIRichLinkMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIRichLinkMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/fragments"},{"op":"replace","value":[{"text":"SMIRichLinkMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/navigatorTitle"},{"op":"replace","value":"title","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage~1title\/title"},{"value":[{"text":"title","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage~1title\/fragments"},{"value":"SMIConversationEntry","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}