{"variants":[{"paths":["\/documentation\/smiclientcore\/richlinkmessage\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/richlinkmessage\/url"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage\/url","interfaceLanguage":"swift"},"metadata":{"title":"url","platforms":[{"introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"}],"required":true,"externalID":"c:objc(pl)SMIRichLinkMessage(py)url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"url"}],"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The URL representing the website pointed to by the rich link."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage":{"abstract":[{"type":"text","text":"A protocol that represents a rich link message within a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"RichLinkMessage","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage","title":"RichLinkMessage","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RichLinkMessage","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/richlinkmessage"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/RichLinkMessage/url":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/RichLinkMessage\/url","title":"url","navigatorTitle":[{"text":"url","kind":"identifier"}],"abstract":[{"text":"The URL representing the website pointed to by the rich link.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/richlinkmessage\/url","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"url","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"text":"url","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIRichLinkMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRichLinkMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIRichLinkMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage\/navigatorTitle"},{"op":"replace","value":"SMIConversationEntry","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments"},{"op":"replace","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1RichLinkMessage~1url\/fragments","value":[{"text":"url","kind":"identifier"}],"op":"replace"}]}]}