{"kind":"symbol","metadata":{"required":true,"role":"symbol","title":"isHidden","externalID":"c:objc(pl)SMIPreChatField(py)isHidden","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"isHidden","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"abstract":[{"text":"Indicates whether this field should be hidden from the user.","type":"text"},{"text":" ","type":"text"},{"text":"Hidden fields are not displayed in the pre-chat form but can still contain values.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isHidden"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfield\/ishidden"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfield\/ishidden"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","kind":"symbol","title":"PreChatField","type":"topic","url":"\/documentation\/smiclientcore\/prechatfield","role":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/isHidden":{"kind":"symbol","navigatorTitle":[{"text":"isHidden","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/isHidden","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isHidden","required":true,"url":"\/documentation\/smiclientcore\/prechatfield\/ishidden","type":"topic","abstract":[{"text":"Indicates whether this field should be hidden from the user.","type":"text"},{"text":" ","type":"text"},{"text":"Hidden fields are not displayed in the pre-chat form but can still contain values.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isHidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isHidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","op":"replace","value":"SMIPreChatField"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatField"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIPreChatField"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isHidden\/title","op":"replace","value":"isHidden"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1isHidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"isHidden"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}