{"kind":"symbol","abstract":[{"text":"The display order of this field in the form.","type":"text"},{"text":" ","type":"text"},{"text":"Fields are displayed in ascending order based on this value.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"order","role":"symbol","required":true,"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"order"}],"roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"externalID":"c:objc(pl)SMIPreChatField(py)order"},"variants":[{"paths":["\/documentation\/smiclientcore\/prechatfield\/order"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/prechatfield\/order"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/order"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatField"}],"abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"title":"PreChatField","role":"symbol","url":"\/documentation\/smiclientcore\/prechatfield","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/order":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/order","required":true,"role":"symbol","url":"\/documentation\/smiclientcore\/prechatfield\/order","kind":"symbol","abstract":[{"type":"text","text":"The display order of this field in the form."},{"type":"text","text":" "},{"type":"text","text":"Fields are displayed in ascending order based on this value."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"order","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"title":"order","type":"topic","navigatorTitle":[{"text":"order","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"order","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"order"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIPreChatField","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","op":"replace"},{"value":[{"text":"SMIPreChatField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","op":"replace"},{"value":"order","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1order\/title","op":"replace"},{"value":[{"text":"order","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1order\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}