{"abstract":[{"type":"text","text":"Validates the current value of this field."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/prechatfield\/validate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfield\/validate()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PreChatErrorTypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","preciseIdentifier":"c:@E@SMIPreChatErrorTypes","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","isActive":true},{"text":" value indicating the validation result.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/validate()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIPreChatErrorTypes","text":"PreChatErrorTypes"}],"title":"validate()","externalID":"c:objc(pl)SMIPreChatField(im)validate","roleHeading":"Instance Method","required":true,"symbolKind":"method","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"validate"}]},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"]]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatErrorTypes":{"navigatorTitle":[{"text":"PreChatErrorTypes","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/prechaterrortypes","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes","title":"PreChatErrorTypes","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatErrorTypes","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An enum that defines the possible validation errors for pre-chat fields.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreChatField","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"url":"\/documentation\/smiclientcore\/prechatfield","kind":"symbol","navigatorTitle":[{"text":"PreChatField","kind":"identifier"}],"type":"topic","title":"PreChatField","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/validate()":{"abstract":[{"text":"Validates the current value of this field.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/validate()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SMIPreChatErrorTypes","text":"PreChatErrorTypes"}],"url":"\/documentation\/smiclientcore\/prechatfield\/validate()","title":"validate()","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"validate"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"validate","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"validate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@SMIPreChatErrorTypes","text":"SMIPreChatErrorTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"},{"text":") ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatErrorTypes"},{"text":" value indicating the validation result.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SMIPreChatErrorTypes","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/title"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/fragments"},{"value":[{"text":"SMIPreChatErrorTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatErrorTypes\/navigatorTitle"},{"value":"SMIPreChatField","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments"},{"value":[{"kind":"identifier","text":"SMIPreChatField"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle"},{"value":"validate","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1validate()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validate"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1validate()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}