{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/value","interfaceLanguage":"swift"},"abstract":[{"text":"The current value of this field.","type":"text"},{"text":" ","type":"text"},{"text":"This value can be set programmatically.","type":"text"}],"variants":[{"paths":["\/documentation\/smiclientcore\/prechatfield\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/prechatfield\/value"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SMIPreChatField(py)value","modules":[{"name":"SMIClientCore"}],"title":"value","roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField","abstract":[{"type":"text","text":"A protocol that defines a field in the pre-chat form."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreChatField"}],"title":"PreChatField","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreChatField"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/prechatfield"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/PreChatField/value":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/smiclientcore\/prechatfield\/value","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}],"abstract":[{"type":"text","text":"The current value of this field."},{"type":"text","text":" "},{"type":"text","text":"This value can be set programmatically."}],"title":"value","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/PreChatField\/value"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"value","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"value","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/title","value":"SMIPreChatField","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/fragments","value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField\/navigatorTitle","value":[{"text":"SMIPreChatField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1PreChatField~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}