{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue\/inputValueType","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/smiforminputvalue\/inputvaluetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/smiforminputvalue\/inputvaluetype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValueType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","kind":"typeIdentifier","text":"FormInputValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The type of input value this object represents."},{"type":"text","text":" "},{"type":"text","text":"This property determines the specific type of value and its behavior."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","isActive":true},{"type":"text","text":" for available input value types."}],"metadata":{"roleHeading":"Instance Property","required":true,"title":"inputValueType","navigatorTitle":[{"kind":"identifier","text":"inputValueType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValueType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType"}],"symbolKind":"property","role":"symbol","externalID":"c:objc(pl)SMIFormInputValue(py)inputValueType","modules":[{"name":"SMIClientCore"}]},"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue/inputValueType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValueType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","kind":"typeIdentifier","text":"FormInputValueType"}],"navigatorTitle":[{"kind":"identifier","text":"inputValueType"}],"type":"topic","kind":"symbol","title":"inputValueType","abstract":[{"text":"The type of input value this object represents.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the specific type of value and its behavior.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","isActive":true,"type":"reference"},{"text":" for available input value types.","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/smiforminputvalue\/inputvaluetype","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue\/inputValueType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIFormInputValue":{"type":"topic","url":"\/documentation\/smiclientcore\/smiforminputvalue","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormInputValue","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines a form input value with its associated metadata."}],"title":"SMIFormInputValue","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIFormInputValue","navigatorTitle":[{"text":"SMIFormInputValue","kind":"identifier"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormInputValueType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormInputValueType"}],"navigatorTitle":[{"kind":"identifier","text":"FormInputValueType"}],"type":"topic","title":"FormInputValueType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","url":"\/documentation\/smiclientcore\/forminputvaluetype","abstract":[{"type":"text","text":"An enum that defines the types of values that can be collected from form inputs."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"inputValueType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"inputValueType","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormInputValueType","text":"SMIFormInputValueType","preciseIdentifier":"c:SMIFormInputValueType.h@T@SMIFormInputValueType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"inputValueType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue~1inputValueType\/title","op":"replace","value":"inputValueType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue~1inputValueType\/fragments","op":"replace","value":[{"text":"inputValueType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/title","op":"replace","value":"SMIFormInputValue"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIFormInputValue"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SMIFormInputValue\/navigatorTitle","op":"replace","value":[{"text":"SMIFormInputValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/title","op":"replace","value":"SMIFormInputValueType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/fragments","op":"replace","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormInputValueType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormInputValueType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}