{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate\/session(_:didDisconnectWithError:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diddisconnectwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diddisconnectwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"SMIMultimediaCommon"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"session:didDisconnectWithError:","kind":"identifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSessionDelegate(im)session:didDisconnectWithError:","title":"session(_:didDisconnectWithError:)","roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDisconnectWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol"},{"type":"text","text":" instance that disconnected."}],"type":"paragraph"}],"name":"session"},{"content":[{"inlineContent":[{"type":"text","text":"The error that caused the disconnection, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the disconnection was intentional."}],"type":"paragraph"}],"name":"error"}]}],"abstract":[{"type":"text","text":"Delegate event that is triggered when the session disconnects."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionDelegate/session(_:didDisconnectWithError:)":{"navigatorTitle":[{"text":"session:didDisconnectWithError:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diddisconnectwitherror:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate\/session(_:didDisconnectWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"session"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultimediaSessionProtocol","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"kind":"text","text":", "},{"text":"didDisconnectWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"session(_:didDisconnectWithError:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate event that is triggered when the session disconnects."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionDelegate":{"role":"symbol","type":"topic","title":"MultimediaSessionDelegate","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSessionDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaSessionDelegate","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessiondelegate","abstract":[{"type":"text","text":"A delegate protocol for receiving events from a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true},{"type":"text","text":" instance."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"session:didDisconnectWithError:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:didDisconnectWithError:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"id<SMIMultimediaSession>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDisconnectWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"session","content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true,"type":"reference"},{"text":" instance that disconnected.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that caused the disconnection, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the disconnection was intentional.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"session:didDisconnectWithError:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate~1session(_:didDisconnectWithError:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:didDisconnectWithError:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate~1session(_:didDisconnectWithError:)\/fragments"},{"op":"replace","value":"SMIMultimediaSessionDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaSessionDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaSessionDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/navigatorTitle"},{"op":"replace","value":"SMIMultimediaSession","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaSession"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaSession"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle"}]}]}