{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate\/session(_:didError:)"},"metadata":{"navigatorTitle":[{"text":"session:didError:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"session(_:didError:)","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSessionDelegate(im)session:didError:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diderror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diderror:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"MultimediaSessionProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"session","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","type":"reference"},{"text":" instance that triggered the event.","type":"text"}],"type":"paragraph"}]},{"name":"didError","content":[{"inlineContent":[{"text":"The error that occurred.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Delegate event that is triggered when an error occurs during the session."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionDelegate":{"role":"symbol","type":"topic","title":"MultimediaSessionDelegate","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaSessionDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MultimediaSessionDelegate","kind":"identifier"}],"url":"\/documentation\/smimultimediacommon\/multimediasessiondelegate","abstract":[{"type":"text","text":"A delegate protocol for receiving events from a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true},{"type":"text","text":" instance."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionProtocol":{"url":"\/documentation\/smimultimediacommon\/multimediasessionprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultimediaSessionProtocol"}],"role":"symbol","navigatorTitle":[{"text":"MultimediaSessionProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","abstract":[{"text":"A protocol that represents an active multimedia session and provides control over the session lifecycle.","type":"text"}],"title":"MultimediaSessionProtocol","kind":"symbol"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaSessionDelegate/session(_:didError:)":{"navigatorTitle":[{"text":"session:didError:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediasessiondelegate\/session(_:diderror:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionDelegate\/session(_:didError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"session","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultimediaSessionProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession"},{"text":", ","kind":"text"},{"text":"didError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"title":"session(_:didError:)","kind":"symbol","type":"topic","abstract":[{"text":"Delegate event that is triggered when an error occurs during the session.","type":"text"}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"session:didError:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"session:didError:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"session:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SMIMultimediaCommon@objc(pl)SMIMultimediaSession","text":"id<SMIMultimediaSession>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"didError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"didError"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaSessionProtocol","isActive":true,"type":"reference"},{"type":"text","text":" instance that triggered the event."}],"type":"paragraph"}],"name":"session"},{"content":[{"inlineContent":[{"type":"text","text":"The error that occurred."}],"type":"paragraph"}],"name":"didError"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SMIMultimediaSessionDelegate","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIMultimediaSessionDelegate"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaSessionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate\/navigatorTitle"},{"value":"SMIMultimediaSession","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionProtocol\/navigatorTitle","op":"replace"},{"value":"session:didError:","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate~1session(_:didError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"session:didError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaSessionDelegate~1session(_:didError:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}