{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/agent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents a human agent participant."},{"type":"text","text":" "},{"type":"text","text":"Used for customer service representatives or support staff."}],"metadata":{"roleHeading":"Type Property","externalID":"c:@SMIParticipantRoleAgent","role":"symbol","symbolKind":"property","title":"agent","extendedModule":"SMIClientCore","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"agent","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantrole\/agent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantrole\/agent"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"navigatorTitle":[{"text":"ParticipantRole","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantrole","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantRole","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"role":"symbol","title":"ParticipantRole","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/agent":{"url":"\/documentation\/smiclientcore\/participantrole\/agent","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier","text":"ParticipantRole"}],"navigatorTitle":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/agent","title":"agent","role":"symbol","kind":"symbol","abstract":[{"text":"Represents a human agent participant.","type":"text"},{"text":" ","type":"text"},{"text":"Used for customer service representatives or support staff.","type":"text"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIParticipantRoleAgent","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}],"path":"\/metadata\/fragments","op":"replace"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","text":"SMIParticipantRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIParticipantRoleAgent"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIParticipantRole","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantRole"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments","op":"replace"},{"value":[{"text":"SMIParticipantRole","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle","op":"replace"},{"value":"SMIParticipantRoleAgent","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1agent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantRoleAgent"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1agent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}