{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantrole\/chatbot"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantrole\/chatbot"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"chatbot","roleHeading":"Type Property","extendedModule":"SMIClientCore","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatbot"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIParticipantRoleChatbot","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SMIClientCore"}],"externalID":"c:@SMIParticipantRoleChatbot"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/chatbot"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatbot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Represents an automated chatbot participant."}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/chatbot":{"title":"chatbot","abstract":[{"text":"Represents an automated chatbot participant.","type":"text"}],"url":"\/documentation\/smiclientcore\/participantrole\/chatbot","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/chatbot","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatbot","kind":"identifier"},{"kind":"text","text":": "},{"text":"ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIParticipantRoleChatbot","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantRole"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","url":"\/documentation\/smiclientcore\/participantrole","abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantRole"}],"title":"ParticipantRole","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"SMIParticipantRoleChatbot","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SMIParticipantRoleChatbot","kind":"identifier"}]},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIParticipantRole","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"},{"text":" ","kind":"text"},{"text":"SMIParticipantRoleChatbot","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1chatbot\/title","op":"replace","value":"SMIParticipantRoleChatbot"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1chatbot\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIParticipantRoleChatbot"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title","op":"replace","value":"SMIParticipantRole"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIParticipantRole"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMIParticipantRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}