{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/router"},"sections":[],"metadata":{"navigatorTitle":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}],"externalID":"c:@SMIParticipantRoleRouter","role":"symbol","title":"router","roleHeading":"Type Property","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"router","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole","kind":"typeIdentifier"}],"extendedModule":"SMIClientCore"},"variants":[{"paths":["\/documentation\/smiclientcore\/participantrole\/router"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantrole\/router"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Represents a routing system participant.","type":"text"},{"text":" ","type":"text"},{"text":"Used for systems that handle conversation routing and assignment.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"router"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","text":"ParticipantRole"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/router":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/router","abstract":[{"type":"text","text":"Represents a routing system participant."},{"type":"text","text":" "},{"type":"text","text":"Used for systems that handle conversation routing and assignment."}],"type":"topic","role":"symbol","title":"router","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"router","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"url":"\/documentation\/smiclientcore\/participantrole\/router","kind":"symbol","navigatorTitle":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantRole","kind":"identifier"}],"abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"navigatorTitle":[{"text":"ParticipantRole","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","title":"ParticipantRole","url":"\/documentation\/smiclientcore\/participantrole"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIParticipantRoleRouter","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace","path":"\/hierarchy"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","text":"SMIParticipantRole","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMIParticipantRoleRouter","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIParticipantRoleRouter","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1router\/title"},{"value":[{"text":"SMIParticipantRoleRouter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1router\/fragments"},{"value":"SMIParticipantRole","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title"},{"value":[{"text":"SMIParticipantRole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments"},{"value":[{"text":"SMIParticipantRole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}