{"abstract":[{"text":"Represents a system-level participant.","type":"text"},{"text":" ","type":"text"},{"text":"Used for automated system messages.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/system","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/participantrole\/system"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantrole\/system"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"system","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"externalID":"c:@SMIParticipantRoleSystem","role":"symbol","navigatorTitle":[{"text":"SMIParticipantRoleSystem","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"platforms":["iOS"]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"url":"\/documentation\/smiclientcore\/participantrole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantRole","kind":"identifier"}],"title":"ParticipantRole","kind":"symbol","navigatorTitle":[{"text":"ParticipantRole","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum that defines the possible roles a participant can have in a conversation."}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/system":{"navigatorTitle":[{"text":"SMIParticipantRoleSystem","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a system-level participant."},{"type":"text","text":" "},{"type":"text","text":"Used for automated system messages."}],"title":"system","url":"\/documentation\/smiclientcore\/participantrole\/system","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/system","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SMIParticipantRoleSystem","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SMIParticipantRoleSystem"}],"path":"\/metadata\/fragments"},{"op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"path":"\/hierarchy"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier","text":"SMIParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMIParticipantRoleSystem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIParticipantRole","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title"},{"op":"replace","value":[{"text":"SMIParticipantRole","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments"},{"op":"replace","value":[{"text":"SMIParticipantRole","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle"},{"op":"replace","value":"SMIParticipantRoleSystem","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1system\/title"},{"op":"replace","value":[{"text":"SMIParticipantRoleSystem","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1system\/fragments"}]}]}