{"kind":"symbol","metadata":{"externalID":"c:@SMIParticipantRoleUser","modules":[{"name":"SMIClientCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier","text":"ParticipantRole"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"SMIParticipantRoleUser","kind":"identifier"}],"extendedModule":"SMIClientCore","title":"user"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"]]},"abstract":[{"type":"text","text":"Represents an end user participant."},{"type":"text","text":" "},{"type":"text","text":"Used for customers or users interacting with the conversation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/user"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantrole\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantrole\/user"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole/user":{"title":"user","abstract":[{"type":"text","text":"Represents an end user participant."},{"type":"text","text":" "},{"type":"text","text":"Used for customers or users interacting with the conversation."}],"url":"\/documentation\/smiclientcore\/participantrole\/user","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole\/user","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantRole","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole"}],"navigatorTitle":[{"text":"SMIParticipantRoleUser","kind":"identifier"}],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantRole":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantRole"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","url":"\/documentation\/smiclientcore\/participantrole","abstract":[{"text":"An enum that defines the possible roles a participant can have in a conversation.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantRole"}],"title":"ParticipantRole","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SMIParticipantRoleUser","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"text":"SMIParticipantRoleUser","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/hierarchy","op":"replace","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantRole","text":"SMIParticipantRole","preciseIdentifier":"c:SMIParticipantRole.h@T@SMIParticipantRole","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SMIParticipantRoleUser","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMIParticipantRoleUser","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1user\/title"},{"value":[{"kind":"identifier","text":"SMIParticipantRoleUser"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole~1user\/fragments"},{"value":"SMIParticipantRole","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/title"},{"value":[{"text":"SMIParticipantRole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/fragments"},{"value":[{"text":"SMIParticipantRole","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantRole\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}