{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participant"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Serializable","preciseIdentifier":"c:objc(cs)SMISerializable"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Participant","preciseIdentifier":"c:objc(pl)SMIParticipant"}],"navigatorTitle":[{"kind":"identifier","text":"participant"}],"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"title":"participant","role":"symbol","externalID":"c:objc(pl)SMIParticipantChangedOperation(py)participant","required":true,"roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The participant affected by this operation."},{"type":"text","text":" "},{"type":"text","text":"This property provides access to the "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","isActive":true},{"type":"text","text":" object that was changed."}],"variants":[{"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/participant"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/participant"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participant","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Serializable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SMISerializable","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable"},{"text":" & ","kind":"text"},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/participant"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/participant":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participant","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"Serializable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SMISerializable"},{"text":" & ","kind":"text"},{"text":"Participant","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIParticipant"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/participant","navigatorTitle":[{"text":"participant","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantchangedoperation\/participant","type":"topic","abstract":[{"text":"The participant affected by this operation.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides access to the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","type":"reference"},{"text":" object that was changed.","type":"text"}],"title":"participant","required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Participant":{"abstract":[{"text":"A protocol that represents a participant in a conversation.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Participant","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Participant"}],"kind":"symbol","type":"topic","title":"Participant","navigatorTitle":[{"text":"Participant","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participant"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Serializable":{"navigatorTitle":[{"text":"Serializable","kind":"identifier"}],"abstract":[{"text":"Base class for JSON serializable objects used with network communication for In-App Messaging.","type":"text"}],"type":"topic","kind":"symbol","title":"Serializable","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Serializable","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Serializable","url":"\/documentation\/smiclientcore\/serializable","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperation"}],"abstract":[{"type":"text","text":"A protocol that represents an operation describing a change to a participant in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","url":"\/documentation\/smiclientcore\/participantchangedoperation","kind":"symbol","title":"ParticipantChangedOperation","navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperation"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"participant","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"participant","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)SMISerializableobjc(pl)SMIParticipant","text":"SMISerializable<SMIParticipant>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"participant","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1participant\/title","value":"participant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1participant\/fragments","value":[{"kind":"identifier","text":"participant"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/title","value":"SMIParticipant"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/fragments","value":[{"text":"SMIParticipant","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Participant\/navigatorTitle","value":[{"text":"SMIParticipant","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/title","value":"SMISerializable"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/fragments","value":[{"text":"SMISerializable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Serializable\/navigatorTitle","value":[{"text":"SMISerializable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/title","value":"SMIParticipantChangedOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}