{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedModalities"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","kind":"typeIdentifier","text":"Modality"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"supportedModalities"}],"role":"symbol","externalID":"c:objc(pl)SMIParticipantChangedOperation(py)supportedModalities","modules":[{"name":"SMIClientCore"}],"title":"supportedModalities","roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/supportedmodalities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/supportedmodalities"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SMIModality.h@T@SMIModality","text":"Modality","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/supportedModalities"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation":{"url":"\/documentation\/smiclientcore\/participantchangedoperation","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","abstract":[{"text":"A protocol that represents an operation describing a change to a participant in a conversation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ParticipantChangedOperation","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperation"}],"type":"topic","title":"ParticipantChangedOperation"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/supportedModalities":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportedModalities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Modality","kind":"typeIdentifier","preciseIdentifier":"c:SMIModality.h@T@SMIModality"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"XXX: JWRIGHT DOCS"}],"navigatorTitle":[{"text":"supportedModalities","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/participantchangedoperation\/supportedmodalities","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/supportedModalities","title":"supportedModalities"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"supportedModalities","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"supportedModalities","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"supportedModalities"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIParticipantChangedOperation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/title"},{"value":[{"text":"SMIParticipantChangedOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/navigatorTitle"},{"value":"supportedModalities","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1supportedModalities\/title"},{"op":"replace","value":[{"kind":"identifier","text":"supportedModalities"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1supportedModalities\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}