{"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"type"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes","kind":"typeIdentifier","text":"ParticipantChangedOperationTypes"}],"role":"symbol","title":"type","roleHeading":"Instance Property","externalID":"c:objc(pl)SMIParticipantChangedOperation(py)type","modules":[{"name":"SMIClientCore"}]},"abstract":[{"type":"text","text":"The type of participant change operation being performed."}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/type","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/participantchangedoperation\/type"]}],"sections":[],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation/type":{"required":true,"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperation\/type","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ParticipantChangedOperationTypes","kind":"typeIdentifier","preciseIdentifier":"c:SMIParticipantChangedOperationTypes.h@T@SMIParticipantChangedOperationTypes"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","abstract":[{"text":"The type of participant change operation being performed.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperation":{"abstract":[{"text":"A protocol that represents an operation describing a change to a participant in a conversation.","type":"text"}],"title":"ParticipantChangedOperation","role":"symbol","url":"\/documentation\/smiclientcore\/participantchangedoperation","type":"topic","navigatorTitle":[{"text":"ParticipantChangedOperation","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperation","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParticipantChangedOperation","kind":"identifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ParticipantChangedOperationTypes":{"title":"ParticipantChangedOperationTypes","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParticipantChangedOperationTypes"}],"role":"symbol","abstract":[{"text":"An enum that defines the possible operations that can be performed on conversation participants.","type":"text"}],"url":"\/documentation\/smiclientcore\/participantchangedoperationtypes","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantChangedOperationTypes"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ParticipantChangedOperationTypes"],"anchor":"Related-Documentation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/title","value":"SMIParticipantChangedOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/fragments","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperation\/navigatorTitle","value":[{"kind":"identifier","text":"SMIParticipantChangedOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/title","value":"SMIParticipantChangedOperationTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/fragments","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ParticipantChangedOperationTypes\/navigatorTitle","value":[{"text":"SMIParticipantChangedOperationTypes","kind":"identifier"}]}]}]}