{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration\/displayName"},"metadata":{"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"displayName","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"c:@M@SMIMultimediaCommon@objc(cs)SMIMultimediaConfiguration(py)displayName"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconfiguration\/displayname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaconfiguration\/displayname"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The display name for the local participant in a multimedia session."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfigurationProtocol":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"title":"MultimediaConfigurationProtocol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfiguration"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfiguration"}],"title":"MultimediaConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol"},{"type":"text","text":" that stores configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration/displayName":{"navigatorTitle":[{"kind":"identifier","text":"displayName"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration\/displayname","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration\/displayName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"displayName","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The display name for the local participant in a multimedia session."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"displayName","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"displayName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SMIMultimediaConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/navigatorTitle"},{"op":"replace","value":"SMIMultimediaConfiguration","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/title"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/fragments"},{"op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/navigatorTitle"},{"op":"replace","value":"displayName","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration~1displayName\/title"},{"op":"replace","value":[{"text":"displayName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration~1displayName\/fragments"}]}]}