{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration\/init(displayName:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"displayName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(displayName:)","modules":[{"name":"SMIMultimediaCommon"}],"externalID":"s:19SMIMultimediaCommon23MultimediaConfigurationC11displayNameACSSSg_tcfc"},"variants":[{"paths":["\/documentation\/smimultimediacommon\/multimediaconfiguration\/init(displayname:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"displayName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"displayName","content":[{"type":"paragraph","inlineContent":[{"text":"The display name for the local participant, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to use the default.","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Creates a new configuration with the given display name."}],"references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfiguration"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfiguration"}],"title":"MultimediaConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A concrete implementation of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol"},{"type":"text","text":" that stores configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfigurationProtocol":{"navigatorTitle":[{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfigurationprotocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfigurationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimediaConfigurationProtocol"}],"title":"MultimediaConfigurationProtocol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that defines the configuration options for a multimedia client."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaConfiguration/init(displayName:)":{"role":"symbol","url":"\/documentation\/smimultimediacommon\/multimediaconfiguration\/init(displayname:)","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaConfiguration\/init(displayName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(displayName:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a new configuration with the given display name."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/title","op":"replace","value":"SMIMultimediaConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/fragments","op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/title","op":"replace","value":"SMIMultimediaConfiguration"},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/fragments","op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaConfigurationProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMIMultimediaConfiguration","kind":"identifier"}]}]}]}