{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse\/inputValues","interfaceLanguage":"swift"},"abstract":[{"text":"An array containing dictionaries representing form responses.","type":"text"},{"text":" ","type":"text"},{"text":"The intention is to return a value for each entry in the ","type":"text"},{"type":"codeVoice","code":"inputs"},{"text":" property.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formexperiencetyperesponse\/inputvalues"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formexperiencetyperesponse\/inputvalues"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValues"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse"]]},"metadata":{"navigatorTitle":[{"text":"inputValues","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"title":"inputValues","required":true,"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(pl)SMIFormExperienceTypeResponse(py)inputValues","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inputValues","kind":"identifier"},{"text":": [[","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]]","kind":"text"}],"role":"symbol"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse":{"abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Forms for LightningType interactions with Agentforce.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FormExperienceTypeResponse"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse","title":"FormExperienceTypeResponse","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FormExperienceTypeResponse"}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetyperesponse"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormExperienceTypeResponse/inputValues":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormExperienceTypeResponse\/inputValues","abstract":[{"text":"An array containing dictionaries representing form responses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The intention is to return a value for each entry in the "},{"type":"codeVoice","code":"inputs"},{"text":" property.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"inputValues"}],"title":"inputValues","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputValues"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]]","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/smiclientcore\/formexperiencetyperesponse\/inputvalues"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"inputValues"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"inputValues","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSDictionary<NSString *,id> *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"inputValues"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/title","value":"SMIFormExperienceTypeResponse","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/fragments","value":[{"text":"SMIFormExperienceTypeResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse\/navigatorTitle","value":[{"text":"SMIFormExperienceTypeResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse~1inputValues\/title","value":"inputValues","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormExperienceTypeResponse~1inputValues\/fragments","value":[{"kind":"identifier","text":"inputValues"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}