{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIOptionExperienceType","text":"OptionExperienceType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType"]]},"metadata":{"title":"choices","role":"symbol","externalID":"c:objc(pl)SMIChoicesExperienceType(py)choices","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"choices"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"choices"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIOptionExperienceType","text":"OptionExperienceType"},{"kind":"text","text":"]"}],"required":true,"modules":[{"name":"SMIClientCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/choices"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/choices"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/choices"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType/choices":{"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/choices","url":"\/documentation\/smiclientcore\/choiceexperiencetype\/choices","navigatorTitle":[{"text":"choices","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"choices","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"OptionExperienceType","preciseIdentifier":"c:objc(pl)SMIOptionExperienceType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","required":true,"title":"choices"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType":{"title":"ChoiceExperienceType","url":"\/documentation\/smiclientcore\/choiceexperiencetype","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceExperienceType","kind":"identifier"}],"navigatorTitle":[{"text":"ChoiceExperienceType","kind":"identifier"}],"abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/OptionExperienceType":{"role":"symbol","url":"\/documentation\/smiclientcore\/optionexperiencetype","kind":"symbol","title":"OptionExperienceType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionExperienceType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"OptionExperienceType","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/OptionExperienceType","abstract":[{"inlineContent":[{"type":"text","text":"Experimental"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"choices","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"choices","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SMIOptionExperienceType>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"choices","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"choices","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1choices\/title"},{"value":[{"kind":"identifier","text":"choices"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1choices\/fragments"},{"value":"SMIChoicesExperienceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/title"},{"value":[{"kind":"identifier","text":"SMIChoicesExperienceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/fragments"},{"value":[{"text":"SMIChoicesExperienceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/navigatorTitle"},{"value":"SMIOptionExperienceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/title"},{"value":[{"kind":"identifier","text":"SMIOptionExperienceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/fragments"},{"value":[{"text":"SMIOptionExperienceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1OptionExperienceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}