{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","title":"response","externalID":"c:objc(pl)SMIChoicesExperienceType(py)response","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"ChoicesExperienceTypeResponse","preciseIdentifier":"c:objc(pl)SMIChoicesExperienceTypeResponse"},{"kind":"text","text":")?"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"response"}]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/response","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoicesExperienceTypeResponse","text":"ChoicesExperienceTypeResponse","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/response"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/response"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType/response":{"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/response","url":"\/documentation\/smiclientcore\/choiceexperiencetype\/response","kind":"symbol","navigatorTitle":[{"text":"response","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ChoicesExperienceTypeResponse","preciseIdentifier":"c:objc(pl)SMIChoicesExperienceTypeResponse","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"response","abstract":[],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType":{"title":"ChoiceExperienceType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceExperienceType"}],"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/choiceexperiencetype","abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"text":" Support for Choices for LightningType interactions with Agentforce.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ChoiceExperienceType"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoicesExperienceTypeResponse":{"title":"ChoicesExperienceTypeResponse","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Experimental"}]},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"url":"\/documentation\/smiclientcore\/choicesexperiencetyperesponse","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoicesExperienceTypeResponse","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoicesExperienceTypeResponse"}],"navigatorTitle":[{"kind":"identifier","text":"ChoicesExperienceTypeResponse"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"response","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"response"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SMIChoicesExperienceTypeResponse>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIChoicesExperienceTypeResponse"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"response","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1response\/title"},{"op":"replace","value":[{"text":"response","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1response\/fragments"},{"op":"replace","value":"SMIChoicesExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SMIChoicesExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SMIChoicesExperienceType"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/navigatorTitle"},{"op":"replace","value":"SMIChoicesExperienceTypeResponse","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/title"},{"op":"replace","value":[{"text":"SMIChoicesExperienceTypeResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/fragments"},{"op":"replace","value":[{"text":"SMIChoicesExperienceTypeResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoicesExperienceTypeResponse\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}