{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/sourcetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/choiceexperiencetype\/sourcetype"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/sourceType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"required":true,"symbolKind":"property","externalID":"c:objc(pl)SMIChoicesExperienceType(py)sourceType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceType"}],"title":"sourceType","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType/sourceType":{"abstract":[],"type":"topic","required":true,"url":"\/documentation\/smiclientcore\/choiceexperiencetype\/sourcetype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"sourceType"}],"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType\/sourceType","kind":"symbol","title":"sourceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ChoiceExperienceType":{"url":"\/documentation\/smiclientcore\/choiceexperiencetype","role":"symbol","navigatorTitle":[{"text":"ChoiceExperienceType","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChoiceExperienceType","kind":"identifier"}],"kind":"symbol","abstract":[{"inlineContent":[{"text":"Experimental","type":"text"}],"type":"strong"},{"type":"text","text":" Support for Choices for LightningType interactions with Agentforce."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ChoiceExperienceType","title":"ChoiceExperienceType","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sourceType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"sourceType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sourceType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"sourceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1sourceType\/title"},{"op":"replace","value":[{"text":"sourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType~1sourceType\/fragments"},{"op":"replace","value":"SMIChoicesExperienceType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/title"},{"op":"replace","value":[{"text":"SMIChoicesExperienceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/fragments"},{"op":"replace","value":[{"text":"SMIChoicesExperienceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ChoiceExperienceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}