{"kind":"symbol","abstract":[{"text":"Initializes a new session context with the provided abstract session context.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext\/init(sessionContext:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/sessioncontext\/init(sessioncontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/sessioncontext\/init(sessioncontext:)"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"symbolKind":"init","title":"init(sessionContext:)","navigatorTitle":[{"kind":"identifier","text":"initWithSessionContext:"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionContext","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)SMISessionContext(im)initWithSessionContext:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sessionContext","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AbstractSessionContextProtocol","preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sessionContext","content":[{"inlineContent":[{"type":"text","text":"The abstract session context to wrap."}],"type":"paragraph"}]}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol":{"kind":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextprotocol","abstract":[{"type":"text","text":"Represents a session context item that contains an "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","type":"reference"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SessionContextProtocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextProtocol"}],"type":"topic","title":"SessionContextProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContext/init(sessionContext:)":{"url":"\/documentation\/smiclientcore\/sessioncontext\/init(sessioncontext:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Initializes a new session context with the provided abstract session context."}],"title":"init(sessionContext:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSessionContext:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionContext"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AbstractSessionContextProtocol","preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext\/init(sessionContext:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"title":"AbstractSessionContextProtocol","abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContext":{"abstract":[{"type":"text","text":"Concrete implementation of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol"},{"type":"text","text":" protocol."}],"kind":"symbol","title":"SessionContext","role":"symbol","navigatorTitle":[{"text":"SessionContext","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SessionContext","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/sessioncontext"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithSessionContext:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionContext:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSessionContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SMIAbstractSessionContext","text":"id<SMIAbstractSessionContext>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sessionContext","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"sessionContext","content":[{"inlineContent":[{"type":"text","text":"The abstract session context to wrap."}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"SMISessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/title"},{"value":[{"text":"SMISessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/fragments"},{"value":[{"text":"SMISessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/navigatorTitle","op":"replace"},{"value":"initWithSessionContext:","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext~1init(sessionContext:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionContext:"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext~1init(sessionContext:)\/fragments","op":"replace"},{"value":"SMIAbstractSessionContext","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title","op":"replace"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle","op":"replace"},{"value":"SMISessionContext","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMISessionContext"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/fragments","op":"replace"},{"value":[{"text":"SMISessionContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContext\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}