{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation"]]},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationUpdateType","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType"}],"navigatorTitle":[{"kind":"identifier","text":"updateType"}],"role":"symbol","externalID":"c:objc(pl)SMIConversationUpdateOperation(py)updateType","modules":[{"name":"SMIClientCore"}],"title":"updateType","roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/conversationupdateoperation\/updatetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/conversationupdateoperation\/updatetype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","text":"ConversationUpdateType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation\/updateType","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateType":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationupdatetype","title":"ConversationUpdateType","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","navigatorTitle":[{"kind":"identifier","text":"ConversationUpdateType"}],"abstract":[{"type":"text","text":"An enum that defines types of updates that may be received on the state of the conversation."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationUpdateType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateOperation/updateType":{"type":"topic","url":"\/documentation\/smiclientcore\/conversationupdateoperation\/updatetype","title":"updateType","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation\/updateType","navigatorTitle":[{"text":"updateType","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationUpdateType","kind":"typeIdentifier","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationUpdateOperation":{"url":"\/documentation\/smiclientcore\/conversationupdateoperation","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateOperation","role":"symbol","navigatorTitle":[{"text":"ConversationUpdateOperation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationUpdateOperation","kind":"identifier"}],"type":"topic","title":"ConversationUpdateOperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"updateType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"updateType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationUpdateType","preciseIdentifier":"c:SMIConversationUpdateType.h@T@SMIConversationUpdateType","text":"SMIConversationUpdateType"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SMIConversationUpdateType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/title","op":"replace"},{"value":[{"text":"SMIConversationUpdateType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/fragments","op":"replace"},{"value":[{"text":"SMIConversationUpdateType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateType\/navigatorTitle","op":"replace"},{"value":"updateType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation~1updateType\/title","op":"replace"},{"value":[{"text":"updateType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation~1updateType\/fragments","op":"replace"},{"value":"SMIConversationUpdateOperation","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationUpdateOperation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SMIConversationUpdateOperation"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationUpdateOperation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}