{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"identifier","roleHeading":"Instance Property","externalID":"c:objc(pl)SMISessionContext(py)identifier","modules":[{"name":"SMIClientCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This identifier is used to distinguish between different session context instances"},{"type":"text","text":" "},{"type":"text","text":"and is typically generated automatically when the context is created."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/smiclientcore\/sessioncontextprotocol\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessioncontextprotocol\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Unique identifier for this session context item."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol\/identifier"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AbstractSessionContextProtocol","kind":"identifier"}],"title":"AbstractSessionContextProtocol","abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol/identifier":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol\/identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"title":"identifier","kind":"symbol","abstract":[{"text":"Unique identifier for this session context item.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/smiclientcore\/sessioncontextprotocol\/identifier"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol":{"kind":"symbol","url":"\/documentation\/smiclientcore\/sessioncontextprotocol","abstract":[{"type":"text","text":"Represents a session context item that contains an "},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","type":"reference"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SessionContextProtocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextProtocol"}],"type":"topic","title":"SessionContextProtocol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"identifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title","op":"replace","value":"SMIAbstractSessionContext"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle","op":"replace","value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol~1identifier\/title","op":"replace","value":"identifier"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol~1identifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/title","op":"replace","value":"SMISessionContext"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/fragments","op":"replace","value":[{"text":"SMISessionContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SMISessionContext"}]}]}]}