{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol\/sessionContext","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"sessionContext","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"AbstractSessionContextProtocol","preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","kind":"typeIdentifier"}],"externalID":"c:objc(pl)SMISessionContext(py)sessionContext","required":true,"modules":[{"name":"SMIClientCore"}],"title":"sessionContext"},"abstract":[{"text":"The abstract session context data associated with this session context item.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionContext","kind":"identifier"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","text":"AbstractSessionContextProtocol","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This property contains the actual context data wrapped by this session context."},{"type":"text","text":" "},{"type":"text","text":"The context data can be any type that conforms to the SMIAbstractSessionContext protocol."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol"]]},"variants":[{"paths":["\/documentation\/smiclientcore\/sessioncontextprotocol\/sessioncontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/sessioncontextprotocol\/sessioncontext"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol/sessionContext":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionContext"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIAbstractSessionContext","kind":"typeIdentifier","text":"AbstractSessionContextProtocol"}],"abstract":[{"text":"The abstract session context data associated with this session context item.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sessionContext"}],"url":"\/documentation\/smiclientcore\/sessioncontextprotocol\/sessioncontext","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol\/sessionContext","title":"sessionContext"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/AbstractSessionContextProtocol":{"abstract":[{"type":"text","text":"Protocol that defines the base type for all session contexts."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"url":"\/documentation\/smiclientcore\/abstractsessioncontextprotocol","title":"AbstractSessionContextProtocol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AbstractSessionContextProtocol"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SessionContextProtocol":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionContextProtocol"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SessionContextProtocol","url":"\/documentation\/smiclientcore\/sessioncontextprotocol","abstract":[{"text":"Represents a session context item that contains an ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/AbstractSessionContextProtocol","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SessionContextProtocol","kind":"identifier"}],"title":"SessionContextProtocol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sessionContext","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"sessionContext"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIAbstractSessionContext","text":"id<SMIAbstractSessionContext>"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionContext"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol~1sessionContext\/title"},{"value":[{"text":"sessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol~1sessionContext\/fragments"},{"value":"SMIAbstractSessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/title"},{"value":[{"text":"SMIAbstractSessionContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/fragments"},{"value":[{"kind":"identifier","text":"SMIAbstractSessionContext"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1AbstractSessionContextProtocol\/navigatorTitle"},{"value":"SMISessionContext","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/title"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/fragments","value":[{"kind":"identifier","text":"SMISessionContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1SessionContextProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SMISessionContext"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}