{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"SMIClientCore"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMICloseConversationEvent(py)conversationIdentifier","navigatorTitle":[{"kind":"identifier","text":"conversationIdentifier"}],"required":true,"role":"symbol","symbolKind":"property","title":"conversationIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"sections":[],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent\/conversationIdentifier","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/closeconversationevent\/conversationidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/closeconversationevent\/conversationidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"The conversation identifier that was closed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CloseConversationEvent":{"url":"\/documentation\/smiclientcore\/closeconversationevent","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent","abstract":[{"text":"Represents a close conversation event within an ","type":"text"},{"code":"SMIConversationEntry","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"CloseConversationEvent","kind":"identifier"}],"type":"topic","title":"CloseConversationEvent","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CloseConversationEvent","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CloseConversationEvent/conversationIdentifier":{"abstract":[{"text":"The conversation identifier that was closed.","type":"text"}],"navigatorTitle":[{"text":"conversationIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"conversationIdentifier","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CloseConversationEvent\/conversationIdentifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/smiclientcore\/closeconversationevent\/conversationidentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"conversationIdentifier","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"conversationIdentifier","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"conversationIdentifier","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMICloseConversationEvent","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/fragments","value":[{"text":"SMICloseConversationEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent\/navigatorTitle","value":[{"kind":"identifier","text":"SMICloseConversationEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent~1conversationIdentifier\/title","value":"conversationIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CloseConversationEvent~1conversationIdentifier\/fragments","value":[{"text":"conversationIdentifier","kind":"identifier"}]}]}]}