{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/multiline","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Represents a text input field that displays and accepts text across multiple lines."},{"type":"text","text":" "},{"type":"text","text":"This type is used when you need to collect longer, more detailed text input from users."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtextinputtype\/multiline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtextinputtype\/multiline"]}],"metadata":{"symbolKind":"property","modules":[{"name":"SMIClientCore"}],"extendedModule":"SMIClientCore","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","text":"FormTextInputType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormTextInputTypeMultiline"}],"title":"multiline","externalID":"c:@SMIFormTextInputTypeMultiline","roleHeading":"Type Property","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"],["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/multiline":{"title":"multiline","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"}],"url":"\/documentation\/smiclientcore\/formtextinputtype\/multiline","role":"symbol","navigatorTitle":[{"text":"SMIFormTextInputTypeMultiline","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/multiline","abstract":[{"text":"Represents a text input field that displays and accepts text across multiple lines.","type":"text"},{"text":" ","type":"text"},{"text":"This type is used when you need to collect longer, more detailed text input from users.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}],"abstract":[{"type":"text","text":"An enum that defines the types of text input fields available in forms."}],"url":"\/documentation\/smiclientcore\/formtextinputtype","title":"FormTextInputType","navigatorTitle":[{"kind":"identifier","text":"FormTextInputType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SMIFormTextInputTypeMultiline","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SMIFormTextInputTypeMultiline","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"SMIFormTextInputTypeMultiline","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SMIFormTextInputTypeMultiline","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1multiline\/title","op":"replace"},{"value":[{"text":"SMIFormTextInputTypeMultiline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1multiline\/fragments","op":"replace"},{"value":"SMIFormTextInputType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/title","op":"replace"},{"value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/fragments","op":"replace"},{"value":[{"text":"SMIFormTextInputType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}