{"abstract":[{"type":"text","text":"Represents a text input field that displays and accepts text on a single line."},{"type":"text","text":" "},{"type":"text","text":"This type is used when you need to collect short, concise text input from users."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"SMIClientCore"}],"externalID":"c:@SMIFormTextInputTypeSingleline","symbolKind":"property","navigatorTitle":[{"text":"SMIFormTextInputTypeSingleline","kind":"identifier"}],"extendedModule":"SMIClientCore","title":"singleline","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType"}],"roleHeading":"Type Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType"]]},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/singleline","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/smiclientcore\/formtextinputtype\/singleline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtextinputtype\/singleline"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType/singleline":{"abstract":[{"text":"Represents a text input field that displays and accepts text on a single line.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This type is used when you need to collect short, concise text input from users."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType\/singleline","role":"symbol","navigatorTitle":[{"text":"SMIFormTextInputTypeSingleline","kind":"identifier"}],"title":"singleline","url":"\/documentation\/smiclientcore\/formtextinputtype\/singleline","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleline","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","text":"FormTextInputType","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTextInputType":{"url":"\/documentation\/smiclientcore\/formtextinputtype","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTextInputType"}],"navigatorTitle":[{"kind":"identifier","text":"FormTextInputType"}],"title":"FormTextInputType","abstract":[{"text":"An enum that defines the types of text input fields available in forms.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SMIFormTextInputTypeSingleline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormTextInputTypeSingleline"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTextInputType","text":"SMIFormTextInputType","preciseIdentifier":"c:SMIFormTextInputType.h@T@SMIFormTextInputType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormTextInputTypeSingleline","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1singleline\/title","value":"SMIFormTextInputTypeSingleline"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType~1singleline\/fragments","value":[{"text":"SMIFormTextInputTypeSingleline","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/title","value":"SMIFormTextInputType"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/fragments","value":[{"kind":"identifier","text":"SMIFormTextInputType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTextInputType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTextInputType"}]}]}]}