{"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable\/selected"},"metadata":{"role":"symbol","symbolKind":"property","title":"selected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice"},{"kind":"text","text":"]?"}],"externalID":"c:objc(pl)SMIMessageSelectable(py)selected","roleHeading":"Instance Property","modules":[{"name":"SMIClientCore"}],"navigatorTitle":[{"text":"selected","kind":"identifier"}],"required":true},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": [any ","kind":"text"},{"text":"Choice","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","preciseIdentifier":"c:objc(pl)SMIChoice"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The selected choice(s) from the message."}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/messageselectable\/selected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/messageselectable\/selected"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable/selected":{"url":"\/documentation\/smiclientcore\/messageselectable\/selected","abstract":[{"type":"text","text":"The selected choice(s) from the message."}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable\/selected","required":true,"navigatorTitle":[{"kind":"identifier","text":"selected"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIChoice","text":"Choice"},{"kind":"text","text":"]?"}],"title":"selected"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEntry","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationEntry","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/conversationentry","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"topic","title":"ConversationEntry","abstract":[{"text":"A protocol that represents an entry in a conversation.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/Choice":{"type":"topic","navigatorTitle":[{"text":"Choice","kind":"identifier"}],"url":"\/documentation\/smiclientcore\/choice","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice","abstract":[{"text":"A response type that represents a specific choice for text based choice messages.","type":"text"}],"kind":"symbol","title":"Choice","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Choice","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/MessageSelectable":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageSelectable"}],"abstract":[{"type":"text","text":"A protocol that represents a message with selectable choices within a "},{"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","isActive":true},{"type":"text","text":"."}],"title":"MessageSelectable","role":"symbol","url":"\/documentation\/smiclientcore\/messageselectable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageSelectable"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/MessageSelectable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"selected"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"selected","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/Choice"],"anchor":"Related-Documentation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SMIChoice>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable~1selected\/title","op":"replace","value":"selected"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable~1selected\/fragments","op":"replace","value":[{"text":"selected","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"text":"SMIConversationEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/title","value":"SMIChoice","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/fragments","value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1Choice\/navigatorTitle","value":[{"text":"SMIChoice","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/title","value":"SMIMessageSelectable","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/fragments","value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1MessageSelectable\/navigatorTitle","value":[{"text":"SMIMessageSelectable","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}