{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/hashValue"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/hash(into:)"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/_SwiftNewtypeWrapper-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"]]},"sections":[],"kind":"article","metadata":{"title":"_SwiftNewtypeWrapper Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype\/_swiftnewtypewrapper-implementations"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/hash(into:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/hash(into:)","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)","abstract":[],"type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/hashValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/hashValue","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/hashvalue","type":"topic","title":"hashValue","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType":{"url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype","navigatorTitle":[{"text":"FormTitleInteractionItemType","kind":"identifier"}],"title":"FormTitleInteractionItemType","type":"topic","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","abstract":[{"text":"An enum that defines the types of interactive elements that can be used in form titles.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleInteractionItemType","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/title","value":"SMIFormTitleInteractionItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/fragments","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}