{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"]]},"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"SMIClientCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/Equatable-Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype\/equatable-implementations"]}],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/!=(_:_:)":{"kind":"symbol","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/!=(_:_:)","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/!=(_:_:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType":{"type":"topic","abstract":[{"type":"text","text":"An enum that defines the types of interactive elements that can be used in form titles."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItemType"}],"role":"symbol","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype","navigatorTitle":[{"kind":"identifier","text":"FormTitleInteractionItemType"}],"kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","title":"FormTitleInteractionItemType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/title","op":"replace","value":"SMIFormTitleInteractionItemType"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/fragments","op":"replace","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/navigatorTitle","op":"replace","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}]}]}]}