{"variants":[{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype\/titleoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formtitleinteractionitemtype\/titleoption"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","text":"FormTitleInteractionItemType"}],"navigatorTitle":[{"kind":"identifier","text":"SMIFormTitleInteractionItemTypeTitleOption"}],"roleHeading":"Type Property","extendedModule":"SMIClientCore","modules":[{"name":"SMIClientCore"}],"symbolKind":"property","role":"symbol","title":"titleOption","externalID":"c:@SMIFormTitleInteractionItemTypeTitleOption"},"abstract":[{"text":"Defines a selectable option that contains a ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","isActive":true,"type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/titleOption","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleOption","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","text":"FormTitleInteractionItemType","kind":"typeIdentifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType"]]},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType":{"abstract":[{"text":"An enum that defines the types of interactive elements that can be used in form titles.","type":"text"}],"title":"FormTitleInteractionItemType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleInteractionItemType"}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleInteractionItemType"}],"role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleInteractionItemType/titleOption":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FormTitleInteractionItemType","preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SMIFormTitleInteractionItemTypeTitleOption","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType\/titleOption","kind":"symbol","title":"titleOption","url":"\/documentation\/smiclientcore\/formtitleinteractionitemtype\/titleoption","abstract":[{"type":"text","text":"Defines a selectable option that contains a "},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SMIFormTitleInteractionItemTypeTitleOption","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemTypeTitleOption"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"]]},"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:SMIFormTitleInteractionItemType.h@T@SMIFormTitleInteractionItemType","text":"SMIFormTitleInteractionItemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleInteractionItemType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SMIFormTitleInteractionItemTypeTitleOption","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/title","value":"SMIFormTitleInteractionItemType","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/fragments","value":[{"text":"SMIFormTitleInteractionItemType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleInteractionItemType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType~1titleOption\/title","value":"SMIFormTitleInteractionItemTypeTitleOption","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleInteractionItemType~1titleOption\/fragments","value":[{"text":"SMIFormTitleInteractionItemTypeTitleOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem","op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}