{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordReferenceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordReferenceId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:objc(pl)SMIFormRecordResult(py)recordReferenceId","modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"text":"recordReferenceId","kind":"identifier"}],"roleHeading":"Instance Property","title":"recordReferenceId","required":true},"abstract":[{"text":"The ID for the relevant record.","type":"text"},{"text":" ","type":"text"},{"text":"This property provides the unique identifier for the record that was created or","type":"text"},{"text":" ","type":"text"},{"text":"updated as a result of the form submission. Use this ID to reference the record","type":"text"},{"text":" ","type":"text"},{"text":"in subsequent operations.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/recordReferenceId"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formrecordresult\/recordreferenceid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formrecordresult\/recordreferenceid"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult/recordReferenceId":{"role":"symbol","abstract":[{"type":"text","text":"The ID for the relevant record."},{"type":"text","text":" "},{"type":"text","text":"This property provides the unique identifier for the record that was created or"},{"type":"text","text":" "},{"type":"text","text":"updated as a result of the form submission. Use this ID to reference the record"},{"type":"text","text":" "},{"type":"text","text":"in subsequent operations."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/recordReferenceId","url":"\/documentation\/smiclientcore\/formrecordresult\/recordreferenceid","navigatorTitle":[{"kind":"identifier","text":"recordReferenceId"}],"type":"topic","kind":"symbol","title":"recordReferenceId","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordReferenceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","url":"\/documentation\/smiclientcore\/formrecordresult","title":"FormRecordResult","navigatorTitle":[{"text":"FormRecordResult","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordResult","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a record that has been created or updated as a result of a form submission.","type":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recordReferenceId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"recordReferenceId","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recordReferenceId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1recordReferenceId\/title","value":"recordReferenceId"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1recordReferenceId\/fragments","value":[{"kind":"identifier","text":"recordReferenceId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/title","value":"SMIFormRecordResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/fragments","value":[{"kind":"identifier","text":"SMIFormRecordResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/navigatorTitle","value":[{"text":"SMIFormRecordResult","kind":"identifier"}]}]}]}