{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/resultMessage","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult"]]},"abstract":[{"type":"text","text":"A message generated as a result of the creation of the record."},{"type":"text","text":" "},{"type":"text","text":"This optional property contains any additional information or feedback about the"},{"type":"text","text":" "},{"type":"text","text":"record creation or update process."}],"variants":[{"paths":["\/documentation\/smiclientcore\/formrecordresult\/resultmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/smiclientcore\/formrecordresult\/resultmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"resultMessage"}],"modules":[{"name":"SMIClientCore"}],"title":"resultMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"c:objc(pl)SMIFormRecordResult(py)resultMessage"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"FormRecordResult","kind":"identifier"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult","url":"\/documentation\/smiclientcore\/formrecordresult","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormRecordResult","kind":"identifier"}],"title":"FormRecordResult","abstract":[{"text":"A protocol that represents a record that has been created or updated as a result of a form submission.","type":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormRecordResult/resultMessage":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormRecordResult\/resultMessage","abstract":[{"type":"text","text":"A message generated as a result of the creation of the record."},{"type":"text","text":" "},{"type":"text","text":"This optional property contains any additional information or feedback about the"},{"type":"text","text":" "},{"type":"text","text":"record creation or update process."}],"url":"\/documentation\/smiclientcore\/formrecordresult\/resultmessage","title":"resultMessage","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resultMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"resultMessage","kind":"identifier"}],"required":true},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"title":"SMIClientCore","url":"\/documentation\/smiclientcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"resultMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"resultMessage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"resultMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/title","value":"SMIFormRecordResult"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/fragments","value":[{"text":"SMIFormRecordResult","kind":"identifier"}]},{"value":[{"text":"SMIFormRecordResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult\/navigatorTitle","op":"replace"},{"value":"resultMessage","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1resultMessage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"resultMessage"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormRecordResult~1resultMessage\/fragments","op":"replace"}]}]}