{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/identifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/identifier"]}],"metadata":{"role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@SMIMultimediaCommon@objc(pl)SMIMultimediaParticipant(py)identifier","modules":[{"name":"SMIMultimediaCommon"}],"symbolKind":"property","title":"identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/identifier","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The unique identifier for this participant.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol"]]},"kind":"symbol","references":{"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol/identifier":{"kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol\/identifier","abstract":[{"type":"text","text":"The unique identifier for this participant."}],"title":"identifier","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol\/identifier"},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon":{"role":"collection","type":"topic","title":"SMIMultimediaCommon","kind":"symbol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon","url":"\/documentation\/smimultimediacommon","abstract":[{"type":"text","text":"The common protocols and types that define the public API surface for multimedia capabilities."}]},"doc://com.salesforce.SMIMultimediaCommon/documentation/SMIMultimediaCommon/MultimediaParticipantProtocol":{"title":"MultimediaParticipantProtocol","identifier":"doc:\/\/com.salesforce.SMIMultimediaCommon\/documentation\/SMIMultimediaCommon\/MultimediaParticipantProtocol","type":"topic","url":"\/documentation\/smimultimediacommon\/multimediaparticipantprotocol","kind":"symbol","navigatorTitle":[{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimediaParticipantProtocol","kind":"identifier"}],"abstract":[{"text":"A protocol that represents a participant in a multimedia session.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"identifier","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"identifier","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1identifier\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol~1identifier\/fragments"},{"value":"SMIMultimediaParticipant","path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/title","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/fragments","op":"replace"},{"value":[{"text":"SMIMultimediaParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.salesforce.SMIMultimediaCommon~1documentation~1SMIMultimediaCommon~1MultimediaParticipantProtocol\/navigatorTitle","op":"replace"}]}]}