{"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The type identifier for this citation reference.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the nature and format of the reference through the","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType"},{"text":" enum. The type helps determine how the reference","type":"text"},{"text":" ","type":"text"},{"text":"should be processed and displayed in the UI.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedReferenceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedReferenceType","kind":"typeIdentifier","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"title":"citedReferenceType","externalID":"c:objc(pl)SMICitedReference(py)citedReferenceType","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedReferenceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedReferenceType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType"}],"navigatorTitle":[{"text":"citedReferenceType","kind":"identifier"}],"modules":[{"name":"SMIClientCore"}],"required":true},"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference\/citedReferenceType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/citedreference\/citedreferencetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/citedreference\/citedreferencetype"]}],"sections":[],"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","abstract":[],"role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","title":"SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReferenceType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CitedReferenceType"}],"url":"\/documentation\/smiclientcore\/citedreferencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum that defines the types of citation references available in the system."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedReferenceType"}],"title":"CitedReferenceType"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference":{"abstract":[{"type":"text","text":"A protocol that represents the reference information for a citation."}],"navigatorTitle":[{"kind":"identifier","text":"CitedReference"}],"type":"topic","url":"\/documentation\/smiclientcore\/citedreference","kind":"symbol","role":"symbol","title":"CitedReference","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CitedReference"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/CitedReference/citedReferenceType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"citedReferenceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CitedReferenceType","kind":"typeIdentifier","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType"}],"kind":"symbol","title":"citedReferenceType","url":"\/documentation\/smiclientcore\/citedreference\/citedreferencetype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReference\/citedReferenceType","navigatorTitle":[{"text":"citedReferenceType","kind":"identifier"}],"required":true,"abstract":[{"text":"The type identifier for this citation reference.","type":"text"},{"text":" ","type":"text"},{"text":"This property determines the nature and format of the reference through the","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","type":"reference","isActive":true},{"text":" enum. The type helps determine how the reference","type":"text"},{"text":" ","type":"text"},{"text":"should be processed and displayed in the UI.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"citedReferenceType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"citedReferenceType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/CitedReferenceType","text":"SMICitedReferenceType","preciseIdentifier":"c:SMICitedReferenceType.h@T@SMICitedReferenceType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"citedReferenceType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SMICitedReferenceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/title"},{"value":[{"text":"SMICitedReferenceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/fragments"},{"value":[{"kind":"identifier","text":"SMICitedReferenceType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReferenceType\/navigatorTitle"},{"value":"SMICitedReference","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/title"},{"value":[{"kind":"identifier","text":"SMICitedReference"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/fragments"},{"value":[{"text":"SMICitedReference","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference\/navigatorTitle"},{"value":"citedReferenceType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference~1citedReferenceType\/title"},{"value":[{"text":"citedReferenceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1CitedReference~1citedReferenceType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}