{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","kind":"typeIdentifier","text":"FormTitleItemType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"]]},"abstract":[{"type":"text","text":"The type of title item this object represents."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the specific type of title component."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(pl)SMIFormTitleItem(py)itemType","title":"itemType","required":true,"modules":[{"name":"SMIClientCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"itemType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FormTitleItemType","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleitem\/itemtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtitleitem\/itemtype"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/itemType","interfaceLanguage":"swift"},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/itemType":{"url":"\/documentation\/smiclientcore\/formtitleitem\/itemtype","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/itemType","title":"itemType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","text":"FormTitleItemType","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"itemType","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"The type of title item this object represents."},{"type":"text","text":" "},{"type":"text","text":"This property identifies the specific type of title component."}],"kind":"symbol","role":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItemType":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItemType"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","url":"\/documentation\/smiclientcore\/formtitleitemtype","kind":"symbol","type":"topic","role":"symbol","title":"FormTitleItemType","abstract":[{"type":"text","text":"An enum that defines "},{"type":"codeVoice","code":"SMIFormTitleItemType"},{"type":"text","text":" types to decorate form fields or responses."}],"navigatorTitle":[{"kind":"identifier","text":"FormTitleItemType"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","kind":"symbol","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FormTitleItem"}],"abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","title":"FormTitleItem","role":"symbol","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormTitleItem"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"itemType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"itemType"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","identifiers":["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType"],"anchor":"Related-Documentation"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SMIFormTitleItemType","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItemType","preciseIdentifier":"c:SMIFormTitleItemType.h@T@SMIFormTitleItemType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"itemType","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1itemType\/title"},{"value":[{"kind":"identifier","text":"itemType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1itemType\/fragments"},{"value":"SMIFormTitleItemType","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/title"},{"value":[{"kind":"identifier","text":"SMIFormTitleItemType"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/fragments"},{"value":[{"text":"SMIFormTitleItemType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItemType\/navigatorTitle"},{"value":"SMIFormTitleItem","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title"},{"value":[{"text":"SMIFormTitleItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments"},{"value":[{"kind":"identifier","text":"SMIFormTitleItem"}],"path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","op":"replace"}]}]}