{"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tertiarySubTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"tertiarySubTitle","kind":"identifier"}],"externalID":"c:objc(pl)SMIFormTitleItem(py)tertiarySubTitle","title":"tertiarySubTitle","symbolKind":"property","required":true,"role":"symbol","modules":[{"name":"SMIClientCore"}]},"sections":[],"abstract":[{"type":"text","text":"Optional tertiary subtitle for this item."},{"type":"text","text":" "},{"type":"text","text":"This provides a third level of additional information or context."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tertiarySubTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/formtitleitem\/tertiarysubtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/formtitleitem\/tertiarysubtitle"]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/tertiarySubTitle"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem/tertiarySubTitle":{"url":"\/documentation\/smiclientcore\/formtitleitem\/tertiarysubtitle","abstract":[{"type":"text","text":"Optional tertiary subtitle for this item."},{"type":"text","text":" "},{"type":"text","text":"This provides a third level of additional information or context."}],"navigatorTitle":[{"text":"tertiarySubTitle","kind":"identifier"}],"kind":"symbol","type":"topic","required":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem\/tertiarySubTitle","role":"symbol","title":"tertiarySubTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tertiarySubTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/FormTitleItem":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/FormTitleItem","title":"FormTitleItem","abstract":[{"type":"text","text":"A protocol that defines the structure for title components used in forms."}],"type":"topic","role":"symbol","url":"\/documentation\/smiclientcore\/formtitleitem","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FormTitleItem","kind":"identifier"}],"navigatorTitle":[{"text":"FormTitleItem","kind":"identifier"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"tertiarySubTitle","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"tertiarySubTitle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tertiarySubTitle"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"tertiarySubTitle","op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1tertiarySubTitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem~1tertiarySubTitle\/fragments","value":[{"text":"tertiarySubTitle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/title","value":"SMIFormTitleItem"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/fragments","value":[{"text":"SMIFormTitleItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1FormTitleItem\/navigatorTitle","value":[{"kind":"identifier","text":"SMIFormTitleItem"}]}]}]}