{"identifier":{"url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator\/progressMessage","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"progressMessage"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressMessage"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SMIEntryFormat","kind":"typeIdentifier","text":"EntryFormat"}],"externalID":"c:objc(pl)SMIProgressIndicator(py)progressMessage","required":true,"modules":[{"name":"SMIClientCore"}],"title":"progressMessage"},"sections":[],"abstract":[{"text":"The formatted message content of the progress indicator.","type":"text"},{"text":" ","type":"text"},{"text":"This property contains the text and\/or type that describes the current progress.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressMessage"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SMIEntryFormat","text":"EntryFormat","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/smiclientcore\/progressindicator\/progressmessage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/smiclientcore\/progressindicator\/progressmessage"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicator/progressMessage":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressMessage"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"EntryFormat","preciseIdentifier":"c:objc(pl)SMIEntryFormat"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator\/progressMessage","url":"\/documentation\/smiclientcore\/progressindicator\/progressmessage","abstract":[{"type":"text","text":"The formatted message content of the progress indicator."},{"type":"text","text":" "},{"type":"text","text":"This property contains the text and\/or type that describes the current progress."}],"role":"symbol","navigatorTitle":[{"text":"progressMessage","kind":"identifier"}],"required":true,"title":"progressMessage","type":"topic"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/EntryFormat":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/EntryFormat","title":"EntryFormat","navigatorTitle":[{"kind":"identifier","text":"EntryFormat"}],"abstract":[{"text":"A protocol that defines the format of content in a conversation entry.","type":"text"}],"type":"topic","url":"\/documentation\/smiclientcore\/entryformat","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EntryFormat"}]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ConversationEntry":{"url":"\/documentation\/smiclientcore\/conversationentry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEntry"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A protocol that represents an entry in a conversation."}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationEntry","kind":"identifier"}],"title":"ConversationEntry"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"title":"SMIClientCore","role":"collection","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","abstract":[],"url":"\/documentation\/smiclientcore","type":"topic","kind":"symbol"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/ProgressIndicator":{"url":"\/documentation\/smiclientcore\/progressindicator","abstract":[{"text":"A protocol that represents a progress indicator within a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ConversationEntry","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/ProgressIndicator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressIndicator"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressIndicator"}],"type":"topic","title":"ProgressIndicator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"progressMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"progressMessage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SMIEntryFormat","text":"id<SMIEntryFormat>"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressMessage"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator~1progressMessage\/title","value":"progressMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator~1progressMessage\/fragments","value":[{"text":"progressMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/title","value":"SMIEntryFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/fragments","value":[{"kind":"identifier","text":"SMIEntryFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1EntryFormat\/navigatorTitle","value":[{"text":"SMIEntryFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/title","value":"SMIConversationEntry"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/fragments","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ConversationEntry\/navigatorTitle","value":[{"kind":"identifier","text":"SMIConversationEntry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/title","value":"SMIProgressIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/fragments","value":[{"kind":"identifier","text":"SMIProgressIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.salesforce.SMIClientCore~1documentation~1SMIClientCore~1ProgressIndicator\/navigatorTitle","value":[{"kind":"identifier","text":"SMIProgressIndicator"}]}]}]}